### ISSUE TITLE
Error on remote delete (Error: RPC method is not valid)

### ISSUE THREAD

**Issue by mhe** [borgbackup/borg#114]
While I was experimenting with borg I issued a delete command on a repository. This repository was remote repository. The delete command resulted in an error (shown below). Running on Mac OS X, linux (Ubuntu 14.04) remote, borg installed through pip3 on both ends.

```
You requested to completely DELETE the repository *including* all archives it contains:
first                                Sat Jul 25 21:15:35 2015
second                               Sat Jul 25 21:16:07 2015
third                                Sat Jul 25 21:17:25 2015
Type "YES" if you understand this and want to continue.

Do you want to continue? YES
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/borg/archiver.py", line 857, in main
    exit_code = archiver.run(sys.argv[1:])
  File "/usr/local/lib/python3.4/site-packages/borg/archiver.py", line 813, in run
    return args.func(args)
  File "/usr/local/lib/python3.4/site-packages/borg/archiver.py", line 291, in do_delete
    repository.destroy()
  File "/usr/local/lib/python3.4/site-packages/borg/remote.py", line 255, in destroy
    return self.call('destroy')
  File "/usr/local/lib/python3.4/site-packages/borg/remote.py", line 153, in call
    for resp in self.call_many(cmd, [args], **kw):
  File "/usr/local/lib/python3.4/site-packages/borg/remote.py", line 188, in call_many
    raise InvalidRPCMethod(*res)
borg.remote.InvalidRPCMethod: (82, 101, 109, 111, 116, 101, 32, 84, 114, 97, 99, 101, 98, 97, 99, 107, 32, 98, 121, 32, 66, 111, 114, 103, 32, 48, 46, 50, 51, 46, 48, 10, 84, 114, 97, 99, 101, 98, 97, 99, 107, 32, 40, 109, 111, 115, 116, 32, 114, 101, 99, 101, 110, 116, 32, 99, 97, 108, 108, 32, 108, 97, 115, 116, 41, 58, 10, 32, 32, 70, 105, 108, 101, 32, 34, 47, 117, 115, 114, 47, 108, 111, 99, 97, 108, 47, 108, 105, 98, 47, 112, 121, 116, 104, 111, 110, 51, 46, 52, 47, 100, 105, 115, 116, 45, 112, 97, 99, 107, 97, 103, 101, 115, 47, 98, 111, 114, 103, 47, 114, 101, 109, 111, 116, 101, 46, 112, 121, 34, 44, 32, 108, 105, 110, 101, 32, 55, 53, 44, 32, 105, 110, 32, 115, 101, 114, 118, 101, 10, 32, 32, 32, 32, 114, 97, 105, 115, 101, 32, 73, 110, 118, 97, 108, 105, 100, 82, 80, 67, 77, 101, 116, 104, 111, 100, 40, 109, 101, 116, 104, 111, 100, 41, 10, 98, 111, 114, 103, 46, 114, 101, 109, 111, 116, 101, 46, 73, 110, 118, 97, 108, 105, 100, 82, 80, 67, 77, 101, 116, 104, 111, 100, 58, 32, 100, 101, 115, 116, 114, 111, 121, 10)
borg: Error: RPC method is not valid
```

**Comment by ThomasWaldmann** [comment]
oh, oops. seems like I only tested that locally. will try to fix it right now.

also, the exception looks strange.
