### ISSUE TITLE
Exception on the client when server pipe is closed

### ISSUE THREAD

**Issue by verygreen** [borgbackup/borg#1197]
```
Remote: packet_write_wait: Connection to 192.168.1.20 port 22: Broken pipe
Exception ignored in: <bound method RemoteRepository.__del__ of <RemoteRepository ssh://backup@backup.localnet/backup1/mordor>>
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/borg/remote.py", line 181, in __del__
    assert False, "cleanup happened in Repository.__del__"
AssertionError: cleanup happened in Repository.__del__
Connection closed by remote host
```

(the connection was closed because the power was lost at the other end).

This is borg 1.0.3 from Fedora23 repo.

**Comment by ThomasWaldmann** [comment]
can you check again with 1.0-maint code? maybe pulling the plug is enough, no need for power switch.

**Comment by ThomasWaldmann** [comment]
Is this maybe because the context manager's `__exit__` is called on the ConnectionClosed exception and then tries to do a rollback, which requires a working connection - and if it has none, maybe triggers a ConnectionClosed (or other) exception again (which terminates borg) and does not reach the self.close() it wanted also to do? Instead, on termination the repo object gets deleted and thus the AssertionError is triggered.

See `remote.RemoteRepository.__exit__`.

**Comment by verygreen** [comment]
anyway, I just tried 1.0-maint and the issue is still there.

Easy way to reproduce:

borg create user@host:repo some_big_files

on the other host:
ps ax | grep ssh
kill -9 pid of the sshd from borg

**Comment by verygreen** [comment]
With your patch I now get:
```
myhost:borg green$ .tox/py35/bin/borg create --compression lz4 backup:/backups/borg/repo::name ~
Remote: Write failed: Broken pipe
Connection closed by remote host
```

rc code returned is 2.
I guess this is much better then before. Not sure if it needs to be any more verbose than that.

**Comment by ThomasWaldmann** [comment]
OK, thanks for testing! I'll merge it...

**Comment by aiso-net** [comment]
Im getting this issue as well, network loss to remote side I think during a backup and now just doing a simple check results in this error:

[root@webXXXX ~]# borg check --repository-only root@IP-ADDRESS:/home/backups/webXXXX
Exception ignored in: <bound method RemoteRepository.__del__ of <RemoteRepository ssh://root@IP-ADDRESS/home/backups/webXXXX>>
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/borg/remote.py", line 618, in __del__
    assert False, 'cleanup happened in Repository.__del__'
AssertionError: cleanup happened in Repository.__del__
Received SIGHUP.
[root@webXXXX ~]# borg -V
borg 1.1.7

**Comment by aiso-net** [comment]
In the backup logs we have for borg commands that are run, it said this during the outage:
Unknown Error: Remote: ssh: connect to host IP-ADDRESS port 22: Connection timed out
Connection closed by remote host. Is borg working on the server?
