### ISSUE TITLE
Backup to USB drive caused I/O Error

### ISSUE THREAD

**Issue by haslinger** [borgbackup/borg#1209]
When my script (that ran for months without any issues, executed (on Ubuntu 16.04, borgbackup 1.0.2)
```
borg prune -v $REPOSITORY --prefix `hostname`-             \
           --keep-daily=7 --keep-weekly=4 --keep-monthly=6
```
the following error message appeared:
```
Local Exception.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1498, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1452, in run
    return args.func(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 80, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 606, in do_prune
    repository.commit(save_space=args.save_space)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 187, in commit
    self.compact_segments(save_space=save_space)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 271, in compact_segments
    for tag, key, offset, data in self.io.iter_objects(segment, include_data=True):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 612, in iter_objects
    (TAG_PUT, TAG_DELETE, TAG_COMMIT))
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 670, in _read
    data = fd.read(length)
OSError: [Errno 5] Input/output error

Platform: Linux aristoteles 4.4.0-24-generic #43-Ubuntu SMP Wed Jun 8 19:27:37 UTC 2016 x86_64 x86_64
Linux: Ubuntu 16.04 xenial
Borg: 1.0.2  Python: CPython 3.5.1+
PID: 22456  CWD: /home/stefan/INFORMATOM/scripts/vorgarten
sys.argv: ['/usr/bin/borg', 'prune', '-v', '/media/stefan/6506f10a-7f74-470a-82b5-4655f4414eaa/borgbackup', '--prefix', 'aristoteles-', '--keep-daily=7', '--keep-weekly=4', '--keep-monthly=6']
SSH_ORIGINAL_COMMAND: None
```

When running a second time "fetching and building archive index" where displayed for each archive, but no more errors displayed.
I thought, I'll post an issue anyways. If I can provide any more debugging info, please let me know. I don't have Python skills (any more), but I'm a Ruby dev, so developer speak in requests is fine :-)

**Comment by ThomasWaldmann** [comment]
The I/O error means it could not read from your repository.
Your USB disk (or interface or cabling) might have a problem, check SMART values of that disk.
If these are ok, maybe also run a filesystem check on the filesystem there.

Also, borg 1.0.3 is released. :)

**Comment by haslinger** [comment]
Thanks for pointing at out to me, that I forgot to reenable the ppa's after updating.
Borg check running ...
Meanwhile also my girlfriend switched to borgbackup and we are both digging it!

**Comment by haslinger** [comment]
So borgbackup apparently showed me a corrupt hard drive. 💔 Awesome!
