### ISSUE TITLE
Another upgrade error from 0.3 to 1.0.3

### ISSUE THREAD

**Issue by ovizii** [borgbackup/borg#1280]
Any advice how to fix this and proceed?

```
#borg upgrade -v /mnt/pve/SYS_bckp/james
making a hardlink copy in /mnt/pve/SYS_bckp/james.upgrade-2016-07-07-14:34:04
/bin/sh: symbol lookup error: /lib/x86_64-linux-gnu/libncurses.so.5: undefined symbol: _nc_putchar
Local Exception.
Traceback (most recent call last):
  File "borg/archiver.py", line 1520, in main
  File "borg/archiver.py", line 1465, in run
  File "borg/archiver.py", line 629, in do_upgrade
  File "borg/upgrader.py", line 39, in upgrade
  File "shutil.py", line 353, in copytree
shutil.Error: [
    ('/mnt/pve/SYS_bckp/james/data/0', '/mnt/pve/SYS_bckp/james.upgrade-2016-07-07-14:34:04/data/0', "[Errno 5] Input/output error: '/mnt/pve/SYS_bckp/james.upgrade-2016-07-07-14:34:04/data/0'"),
    ('/mnt/pve/SYS_bckp/james/data', '/mnt/pve/SYS_bckp/james.upgrade-2016-07-07-14:34:04/data', "[Errno 5] Input/output error: '/mnt/pve/SYS_bckp/james.upgrade-2016-07-07-14:34:04/data'"),
    ('/mnt/pve/SYS_bckp/james', '/mnt/pve/SYS_bckp/james.upgrade-2016-07-07-14:34:04', "[Errno 5] Input/output error: '/mnt/pve/SYS_bckp/james.upgrade-2016-07-07-14:34:04'")
]

Platform: Linux james 4.4.10-1-pve #1 SMP Fri Jun 10 21:23:44 CEST 2016 x86_64
Linux: debian 8.5
Borg: 1.0.3  Python: CPython 3.5.1
PID: 15724  CWD: /tmp
sys.argv: ['borg', 'upgrade', '-v', '/mnt/pve/SYS_bckp/james']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ovizii** [comment]
or should I rather give up and start from scratch like in this thread => https://github.com/borgbackup/borg/issues/904 which btw. was a different backup.

**Comment by ThomasWaldmann** [comment]
Input/Output Error sounds like there is some problem with reading or writing the mentioned files.

Bad disk? Corrupt filesystem?

There seems to be another problem with libncurses, but guess that is unrelated.

**Comment by ovizii** [comment]
don't think so, the target is an NFS share. 
Anyway, I can just start from scratch and keep the old backups for a while.

Going to close this ticket seeing there is no obvious/quick solution.

**Comment by enkore** [comment]
IIRC the only thing an upgrade from 0.x to 1.0 would do is to move local key files, if any.

> moved keyfile keys from ~/.borg/keys to ~/.config/borg/keys, you can either move them manually or run "borg upgrade <REPO>"
