### ISSUE TITLE
borg: Error: RPC method is not valid

### ISSUE THREAD

**Issue by breyer** [borgbackup/borg#131]
Hello,

i´m not sure if i make somethink wrong, but i´m getting an error when i like to delete a backup under FreeBSD 10.1-RELEASE-p15.

I make a new backup:
```
borg create --stats ssh://username@remotehost:port//backup/test::1 /etc/
Password for username@hostname:

Archive name: 1
Archive fingerprint: aaadfb90767845382d65896ffbeb9009f0be330bb978cbcc7add86df7ac05675
Start time: Mon Aug  3 08:26:34 2015
End time: Mon Aug  3 08:26:38 2015
Duration: 4.54 seconds
Number of files: 379

Original size      Compressed size    Deduplicated size
This archive:                1.95 MB            459.73 kB            430.96 kB
All archives:                1.95 MB            459.73 kB            430.96 kB
```

Now i would like to delete the complete backup, but getting an error:
```
borg delete ssh://username@hostname:port//backup/test
Password for username@hostname:
You requested to completely DELETE the repository *including* all archives it contains:
1                                    Mon Aug  3 08:26:38 2015
Type "YES" if you understand this and want to continue.

Do you want to continue? YES
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/borg/archiver.py", line 857, in main
    exit_code = archiver.run(sys.argv[1:])
  File "/usr/local/lib/python3.4/site-packages/borg/archiver.py", line 813, in run
    return args.func(args)
  File "/usr/local/lib/python3.4/site-packages/borg/archiver.py", line 291, in do_delete
    repository.destroy()
  File "/usr/local/lib/python3.4/site-packages/borg/remote.py", line 255, in destroy
    return self.call('destroy')
  File "/usr/local/lib/python3.4/site-packages/borg/remote.py", line 153, in call
    for resp in self.call_many(cmd, [args], **kw):
  File "/usr/local/lib/python3.4/site-packages/borg/remote.py", line 188, in call_many
    raise InvalidRPCMethod(*res)
borg.remote.InvalidRPCMethod: (82, 101, 109, 111, 116, 101, 32, 84, 114, 97, 99, 101, 98, 97, 99, 107, 32, 98, 121, 32, 66, 111, 114, 103, 32, 48, 46, 50, 51, 46, 48, 10, 84, 114, 97, 99, 101, 98, 97, 99, 107, 32, 40, 109, 111, 115, 116, 32, 114, 101, 99, 101, 110, 116, 32, 99, 97, 108, 108, 32, 108, 97, 115, 116, 41, 58, 10, 32, 32, 70, 105, 108, 101, 32, 34, 47, 117, 115, 114, 47, 108, 111, 99, 97, 108, 47, 108, 105, 98, 47, 112, 121, 116, 104, 111, 110, 51, 46, 52, 47, 115, 105, 116, 101, 45, 112, 97, 99, 107, 97, 103, 101, 115, 47, 98, 111, 114, 103, 47, 114, 101, 109, 111, 116, 101, 46, 112, 121, 34, 44, 32, 108, 105, 110, 101, 32, 55, 53, 44, 32, 105, 110, 32, 115, 101, 114, 118, 101, 10, 32, 32, 32, 32, 114, 97, 105, 115, 101, 32, 73, 110, 118, 97, 108, 105, 100, 82, 80, 67, 77, 101, 116, 104, 111, 100, 40, 109, 101, 116, 104, 111, 100, 41, 10, 98, 111, 114, 103, 46, 114, 101, 109, 111, 116, 101, 46, 73, 110, 118, 97, 108, 105, 100, 82, 80, 67, 77, 101, 116, 104, 111, 100, 58, 32, 100, 101, 115, 116, 114, 111, 121, 10)
borg: Error: RPC method is not valid
```

I receive no error when i delete just the backup "1":
```
borg delete ssh://username@hostname:port//backup/test::1
```

Does anyone have an idea?

Thanks
Mark

**Comment by breyer** [comment]
Ahh, it seems this bug is already known.
https://github.com/borgbackup/borg/issues/114

**Comment by ThomasWaldmann** [comment]
@breyer exactly, fix is in git master and also in next release (0.24, soon).

closing this as duplicate.
