### ISSUE TITLE
pip3 install from github on CentOS 6 issues

### ISSUE THREAD

**Issue by tgharold** [borgbackup/borg#132]
Installing borg from the github master branch can't seem to find Cython, which is already installed.

Maybe the setup is looking for a specific version?

```
# pip3 install git+https://github.com/borgbackup/borg.git@master 
Collecting git+https://github.com/borgbackup/borg.git@master
  Cloning https://github.com/borgbackup/borg.git (to master) to /tmp/pip-4f_n5ecn-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-4f_n5ecn-build/setup.py", line 30, in <module>
        from Cython.Distutils import build_ext
    ImportError: No module named 'Cython'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-4f_n5ecn-build/setup.py", line 63, in <module>
        raise ImportError('The GIT version of Borg needs Cython. Install Cython or use a released version')
    ImportError: The GIT version of Borg needs Cython. Install Cython or use a released version
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-4f_n5ecn-build

# yum info Cython
Installed Packages
Name        : Cython
Arch        : x86_64
Version     : 0.14.1
Release     : 3.el6
Size        : 6.5 M
Repo        : installed
From repo   : epel
Summary     : A language for writing Python extension modules
URL         : http://www.cython.org
License     : Python
Description : This is a development version of Pyrex, a language
            : for writing Python extension modules.
            : 
            : For more info, see:
            : 
            :     Doc/About.html for a description of the language
            :     INSTALL.txt           for installation instructions
            :     USAGE.txt           for usage instructions
            :     Demos           for usage examples

**Comment by ThomasWaldmann** [comment]
Did you install borgbackup into a virtualenv?
If so, it won't find your system Cython, you need to install Cython into virtualenv also.

**Comment by tgharold** [comment]
The original install command for borg was:

# pip3 install borgbackup

Maybe I need to 'pip3 install Cython' instead of installing it from EPEL via yum.

**Comment by tgharold** [comment]
Yeah, that worked - installing Cython via pip3 fixed the issue.

```
# pip3 install Cython
# pip3 install git+https://github.com/borgbackup/borg.git@master
