### ISSUE TITLE
borg: error: unrecognized arguments: --umask 077

### ISSUE THREAD

**Issue by tgharold** [borgbackup/borg#135]
This happened a few times on a repository where borg had failed to write a few times.  I had to run "borg check -v" a few times to get the error to go away, then "borg check" finally started running.  I have no idea where it's getting the "--umask" argument since it's not one that I'm passing in on the command line.

So I'm not sure I can get the error to happen again.  Except maybe by constantly interrupting "borg create" commands that write to the repo.

```
$ borg check -v ssh://backups.tgharold.com/backup/thomast61p/borgs/borgmatic.borg
usage: borg [-h]
            {serve,init,check,change-passphrase,create,extract,rename,delete,list,mount,info,prune,help}
            ...
borg: error: unrecognized arguments: --umask 077
borg: Error: Local Exception.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/borg/archiver.py", line 871, in main
    exit_code = archiver.run(sys.argv[1:])
  File "/usr/lib/python3.4/site-packages/borg/archiver.py", line 827, in run
    return args.func(args)
  File "/usr/lib/python3.4/site-packages/borg/archiver.py", line 73, in do_check
    repository = self.open_repository(args.repository, exclusive=args.repair)
  File "/usr/lib/python3.4/site-packages/borg/archiver.py", line 35, in open_repository
    repository = RemoteRepository(location, create=create)
  File "/usr/lib/python3.4/site-packages/borg/remote.py", line 149, in __init__
    version = self.call('negotiate', 1)
  File "/usr/lib/python3.4/site-packages/borg/remote.py", line 163, in call
    for resp in self.call_many(cmd, [args], **kw):
  File "/usr/lib/python3.4/site-packages/borg/remote.py", line 209, in call_many
    raise Exception('FD exception occurred')
Exception: FD exception occurred

borg: Exiting with failure status due to previous errors

**Comment by tgharold** [comment]
Both client and server are running latest master.

```
$ pip3 install git+https://github.com/borgbackup/borg.git@master                                                                    Collecting git+https://github.com/borgbackup/borg.git@master
  Cloning https://github.com/borgbackup/borg.git (to master) to /tmp/pip-q1_rmnin-build
Requirement already satisfied (use --upgrade to upgrade): msgpack-python>=0.4.6 in /usr/lib/python3.4/site-packages (from borgbackup==0.23.0+88.gd567537)
Installing collected packages: borgbackup
  Found existing installation: borgbackup 0.23.0+86.g3be55be
    Uninstalling borgbackup-0.23.0+86.g3be55be:
      Successfully uninstalled borgbackup-0.23.0+86.g3be55be
  Running setup.py install for borgbackup
Successfully installed borgbackup-0.23.0+88.gd567537

**Comment by ThomasWaldmann** [comment]
I don't see any --umask 077 in your borg invokation. Also you would not need that as it is the default.

Try:
```
borg check --umask 007 ...
```

**Comment by tgharold** [comment]
Found where the umask argument is coming from.  It's the server side copy of borg that gets started under SSH.

```
/usr/bin/python3 /usr/bin/borg serve --umask 077

**Comment by ThomasWaldmann** [comment]
ok, so is there a problem left?

**Comment by tgharold** [comment]
Not sure - it got stuck there once, maybe it will get stuck there again.

**Comment by ThomasWaldmann** [comment]
Labelled as invalid.

It just looks like the borg on the server is running older borg code that does not yet have the --umask option.
New borg ALWAYS issues that option for remote borg invocations, even if you do not specify it on the commandline. By that, it's making sure it uses the same umask on remote as on local and that the umask is sane.

**Comment by ThomasWaldmann** [comment]
adding a CHANGES compatibility note for this...
