### ISSUE TITLE
borg-check doesn't handle one case of truncated metadata chunks

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#1351]
https://gist.github.com/esteigler/7a9b21a7b91d20b6463bdc30e9bcbd80

```pytraceback
Exception while unpacking item metadata [chunk: 020920_c393225222c0b08962d01582c2ae30adb488becda8b23fde3cd651a02f89037f]
Local Exception.
Traceback (most recent call last):
  File "borg/archiver.py", line 1609, in main
  File "borg/archiver.py", line 1546, in run
  File "borg/archiver.py", line 81, in wrapper
  File "borg/archiver.py", line 148, in do_check
  File "borg/archive.py", line 823, in check
  File "borg/archive.py", line 1058, in rebuild_refcounts
  File "borg/archive.py", line 1015, in robust_iterator
  File "borg/archive.py", line 801, in __next__
  File "msgpack/_unpacker.pyx", line 469, in msgpack._unpacker.Unpacker.__next__ (msgpack/_unpacker.cpp:469)
  File "msgpack/_unpacker.pyx", line 400, in msgpack._unpacker.Unpacker._unpack (msgpack/_unpacker.cpp:400)
TypeError: unhashable type: 'StableDict'
```

What likely happened here is that one metadata chunk was truncated in a msgpack-map (#1138) where a key is expected. As the next chunk contains an item dict which is not hashable and therefore not a valid key in any dict. This error condition is not handled by RobustUnpacker, but should be.

A possible workaround is to debug-delete-obj the metadata chunks (one should be enough) causing the error, which switches to resync-mode in the RobustUnpacker.

***

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/36171983-borg-check-doesn-t-handle-one-case-of-truncated-metadata-chunks)

**Comment by enkore** [comment]
#1402
