### ISSUE TITLE
borg-init: crash if the filesystem is replaced during password prompt

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#1376]
The specific issue seems to be that the roster may be lost in the case it's removed with force, _not cleanly_ (in which case there is probably no problem). Thus roster entries may be missing, leading to a crash like:

```
Traceback (most recent call last):
  File "/home/mabe/Projekte/_oss/borg/src/borg/repository.py", line 114, in __del__
    self.close()
  File "/home/mabe/Projekte/_oss/borg/src/borg/repository.py", line 240, in close
    self.lock.release()
  File "/home/mabe/Projekte/_oss/borg/src/borg/locking.py", line 291, in release
    self._roster.modify(EXCLUSIVE, REMOVE)
  File "/home/mabe/Projekte/_oss/borg/src/borg/locking.py", line 211, in modify
    elements.remove(self.id)
KeyError: (('tiger', 4444, 0),)
Local Exception.
Traceback (most recent call last):
  File "/home/mabe/Projekte/_oss/borg/src/borg/archiver.py", line 2261, in main
    exit_code = archiver.run(args)
  File "/home/mabe/Projekte/_oss/borg/src/borg/archiver.py", line 2194, in run
    return args.func(args)
  File "/home/mabe/Projekte/_oss/borg/src/borg/archiver.py", line 90, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/home/mabe/Projekte/_oss/borg/src/borg/repository.py", line 136, in __exit__
    self.close()
  File "/home/mabe/Projekte/_oss/borg/src/borg/repository.py", line 240, in close
    self.lock.release()
  File "/home/mabe/Projekte/_oss/borg/src/borg/locking.py", line 291, in release
    self._roster.modify(EXCLUSIVE, REMOVE)
  File "/home/mabe/Projekte/_oss/borg/src/borg/locking.py", line 211, in modify
    elements.remove(self.id)
KeyError: ('tiger', 4444, 0)
```

I'm almost tempted to wontfix this right away.

**Comment by PlasmaPower** [comment]
Sounds like a combination of not very likely and not our problem IMHO.
