### ISSUE TITLE
borg check --verify-data crashes

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1395]
This showed up while practically testing my in-file-checkpoints branch code:
First, I started a backup and interrupted it in the middle using Ctrl-C:

```
(borg-env)tw@tux:~/w/borg$ borg create --checkpoint-interval=1 repo::3 ~/Downloads/pycharm-2016.1/pycharm-professional-2016.1.2.tar.gz 
^CKeyboard interrupt.
Traceback (most recent call last):
  File "/home/tw/w/borg/src/borg/archiver.py", line 2282, in main
    exit_code = archiver.run(args)
  File "/home/tw/w/borg/src/borg/archiver.py", line 2215, in run
    return args.func(args)
  File "/home/tw/w/borg/src/borg/archiver.py", line 94, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/home/tw/w/borg/src/borg/archiver.py", line 308, in do_create
    create_inner(archive, cache)
  File "/home/tw/w/borg/src/borg/archiver.py", line 282, in create_inner
    read_special=args.read_special, dry_run=dry_run, st=st)
  File "/home/tw/w/borg/src/borg/archiver.py", line 342, in _process
    status = archive.process_file(path, st, cache, self.ignore_inode)
  File "/home/tw/w/borg/src/borg/archive.py", line 825, in process_file
    self.chunk_file(item, cache, self.stats, fd, fh, compress=compress)
  File "/home/tw/w/borg/src/borg/archive.py", line 737, in chunk_file
    for data in backup_io_iter(self.chunker.chunkify(fd, fh)):
  File "/home/tw/w/borg/src/borg/archive.py", line 139, in backup_io_iter
    item = next(iterator)
KeyboardInterrupt

Platform: Linux tux 4.6.4-tw2 #4 SMP Mon Jul 18 15:44:28 CEST 2016 x86_64 x86_64
Linux: Ubuntu 16.04 xenial
Borg: 1.1.dev191+ng0c89218  Python: CPython 3.5.1+
PID: 17878  CWD: /home/tw/w/borg
sys.argv: ['/home/tw/w/borg-env/bin/borg', 'create', '--checkpoint-interval=1', 'repo::3', '/home/tw/Downloads/pycharm-2016.1/pycharm-professional-2016.1.2.tar.gz']
SSH_ORIGINAL_COMMAND: None
```

Then checked repo state:
```
(borg-env)tw@tux:~/w/borg$ borg check -v --verify-data repo
Starting repository check
Completed repository check, no problems found.
Starting archive consistency check...
Analyzing archive 3.checkpoint (3/3)
Analyzing archive 2.checkpoint (2/3)
Analyzing archive 1.checkpoint (1/3)
Starting cryptographic data integrity verification...
Object with key b"\xa4\xb7Wi\xebe*E\x901\xfa\x9f\x1b\x95\xa3Jja%\xa2\xe6\xb0\x84('i\xbaI\xce\t\xcd\xd9" not found in repository /home/tw/w/borg/repo.
Traceback (most recent call last):
  File "/home/tw/w/borg/src/borg/archiver.py", line 2282, in main
    exit_code = archiver.run(args)
  File "/home/tw/w/borg/src/borg/archiver.py", line 2215, in run
    return args.func(args)
  File "/home/tw/w/borg/src/borg/archiver.py", line 94, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/home/tw/w/borg/src/borg/archiver.py", line 210, in do_check
    save_space=args.save_space):
  File "/home/tw/w/borg/src/borg/archive.py", line 968, in check
    self.verify_data()
  File "/home/tw/w/borg/src/borg/archive.py", line 1011, in verify_data
    encrypted_data = self.repository.get(chunk_id)
  File "/home/tw/w/borg/src/borg/repository.py", line 574, in get
    raise self.ObjectNotFound(id_, self.path) from None
borg.repository.Repository.ObjectNotFound: (b"\xa4\xb7Wi\xebe*E\x901\xfa\x9f\x1b\x95\xa3Jja%\xa2\xe6\xb0\x84('i\xbaI\xce\t\xcd\xd9", '/home/tw/w/borg/repo')

Platform: Linux tux 4.6.4-tw2 #4 SMP Mon Jul 18 15:44:28 CEST 2016 x86_64 x86_64
Linux: Ubuntu 16.04 xenial
Borg: 1.1.dev191+ng0c89218  Python: CPython 3.5.1+
PID: 17889  CWD: /home/tw/w/borg
sys.argv: ['/home/tw/w/borg-env/bin/borg', 'check', '-v', '--verify-data', 'repo']
SSH_ORIGINAL_COMMAND: None
```

Not sure yet if the missing object is somehow related to my code changes in that branch or a general problem.

But likely, verify_data should not crash if a chunk is missing, but just report it.

**Comment by enkore** [comment]
> But likely, verify_data should not crash if a chunk is missing, but just report it.

Yes.

However, in this sequence Borg may not fail in any way at all.

**Comment by ThomasWaldmann** [comment]
Also interesting: running this on same repo where it fails as seen above:
```
(borg-env)tw@tux:~/w/borg$ borg check -v repo
Starting repository check
Completed repository check, no problems found.
Starting archive consistency check...
Analyzing archive 3.checkpoint (3/3)
Analyzing archive 2.checkpoint (2/3)
Analyzing archive 1.checkpoint (1/3)
Archive consistency check complete, no problems found.
```

**Comment by enkore** [comment]
Reproduced with current master. Oh...

**Comment by enkore** [comment]
Ok this seems specific issue looks like it's merely a bug in verify_data. It doesnt/cannot (by principle, unless --repair) find the chunks created in rebuild_refcounts here:

```
                new_archive_id = self.key.id_hash(data)
                cdata = self.key.encrypt(Chunk(data))
                add_reference(new_archive_id, len(data), len(cdata), cdata)
                info[b'id'] = new_archive_id
```
