### ISSUE TITLE
LockTimeout: better error message

### ISSUE THREAD

**Issue by ptitvert** [borgbackup/borg#1440]
When I have a locking problem, I would like to have a "normal" error message like:

Error: The repository is locked, please try again later, or use the option --lock-wait.

Instead of the horrible stack trace:
```
Remote: Borg 1.0.6: exception in RPC call:
Remote: Traceback (most recent call last):
Remote:   File "/home/xyz/borg-env/lib/python3.4/site-packages/borg/locking.py", line 136, in acquire
Remote:     os.mkdir(self.path)
Remote: FileExistsError: [Errno 17] File exists: '/home/xyz/repos/host/trunk/lock.exclusive'
Remote:
Remote: During handling of the above exception, another exception occurred:
Remote:
Remote: Traceback (most recent call last):
Remote:   File "/home/xyz/borg-env/lib/python3.4/site-packages/borg/remote.py", line 97, in serve
Remote:     res = f(*args)
Remote:   File "/home/xyz/borg-env/lib/python3.4/site-packages/borg/remote.py", line 128, in open
Remote:     self.repository.__enter__()  # clean exit handled by serve() method
Remote:   File "/home/xyz/borg-env/lib/python3.4/site-packages/borg/repository.py", line 82, in __enter__
Remote:     self.open(self.path, self.exclusive, lock_wait=self.lock_wait, lock=self.do_lock)
Remote:   File "/home/xyz/borg-env/lib/python3.4/site-packages/borg/repository.py", line 171, in open
Remote:     self.lock = UpgradableLock(os.path.join(path, 'lock'), exclusive, timeout=lock_wait).acquire()
Remote:   File "/home/xyz/borg-env/lib/python3.4/site-packages/borg/locking.py", line 265, in acquire
Remote:     with self._lock:
Remote:   File "/home/xyz/borg-env/lib/python3.4/site-packages/borg/locking.py", line 120, in __enter__
Remote:     return self.acquire()
Remote:   File "/home/xyz/borg-env/lib/python3.4/site-packages/borg/locking.py", line 141, in acquire
Remote:     raise LockTimeout(self.path)
Remote: borg.locking.LockTimeout: /home/xyz/repos/host/trunk/lock.exclusive
Remote: Platform: Linux xyz 3.13.0-76-generic #120-Ubuntu SMP Mon Jan 18 15:59:10 UTC 2016 x86_64 x86_64
Remote: Linux: Ubuntu 14.04 trusty
Remote: Borg: 1.0.6  Python: CPython 3.4.3
Remote: PID: 37645  CWD: /home/xyz/repos/host
Remote: sys.argv: ['/home/xyz/bin/borg', 'serve', '--restrict-to-path', '/home/xyz/repos/host']
Remote: SSH_ORIGINAL_COMMAND: 'borg serve --umask=077'
Remote:
Remote Exception (see remote log for the traceback)
Platform: Linux host 3.2.0-4-amd64 #1 SMP Debian 3.2.81-1 x86_64
Linux: debian 7.11
Borg: 1.0.6  Python: CPython 3.5.2
PID: 45908  CWD: /root/bin
sys.argv: ['borg', 'mount', 'xyz@backup.example.com:trunk::20160804', '/mnt']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment]
For expected cases of "this is locked", I agree, it should be prettier.
The problem might be if there is some unexpected case or bug, then we might need more information and if we suppress the stacktrace, we don't get it.

**Comment by ptitvert** [comment]
Yep, I think there must be a sweet spot to find, where a "this is locked" is the message and otherwise you get the stacktrace.

**Comment by ThomasWaldmann** [comment]
Hmm, maybe we could emit the traceback at DEBUG level for cases that are somehow expected to happen often under normal conditions.

So if something weird comes up, we can still give `--debug` and get the trace, if the problem can be reproduced.

**Comment by ThomasWaldmann** [comment]
For local repos with current borg 1.0.7pre, it is already cleaned up:
```
(borg-env)tw@tux:~/w/borg$ borg create repo::3 borg
Failed to create/acquire the lock /home/tw/w/borg/repo/lock (timeout).
```
It still happens for remote repos. Guess we can improve that in 1.1 with the better remote logging system.

**Comment by enkore** [comment]
Yes, in 1.0.x the log level information isn't transported; moving the messages to a different log level would not help there. For 1.1 this should be relatively simple.
