### ISSUE TITLE
Repository: MAX_OBJECT_SIZE is not enforced at write-time

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#1451]
E.g.

```py

>>> with borg.repository.Repository("repo", exclusive=True) as r:
...     r.put(b'0' * 32, bytes(50*1024*1024))
...     r.get(b'0' * 32)
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/usr/lib/python3.5/site-packages/borg/repository.py", line 474, in get
    return self.io.read(segment, offset, id_)
  File "/usr/lib/python3.5/site-packages/borg/repository.py", line 695, in read
    size, tag, key, data = self._read(fd, self.put_header_fmt, header, segment, offset, (TAG_PUT, ))
  File "/usr/lib/python3.5/site-packages/borg/repository.py", line 717, in _read
    segment, offset))
borg.helpers.IntegrityError: Invalid segment entry size [segment 1, offset 8]
Invalid segment entry size [segment 1, offset 8]
```

**Comment by ThomasWaldmann** [comment]
Fixed by #1454.
