### ISSUE TITLE
crash: logging not yet set up in preprocess_args

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1486]
current git master:
```
$ borg list --list-format '{formatkeys}{LF}' repo::1
Traceback (most recent call last):
  File "/home/tw/w/borg-env/bin/borg", line 9, in <module>
    load_entry_point('borgbackup==1.1.dev333-ngd5edaa5', 'console_scripts', 'borg')()
  File "/home/tw/w/borg/src/borg/archiver.py", line 2359, in main
    args = archiver.get_args(sys.argv, os.environ.get('SSH_ORIGINAL_COMMAND'))
  File "/home/tw/w/borg/src/borg/archiver.py", line 2243, in get_args
    result = self.parse_args(argv[1:])
  File "/home/tw/w/borg/src/borg/archiver.py", line 2259, in parse_args
    args = self.preprocess_args(args)
  File "/home/tw/w/borg/src/borg/archiver.py", line 1254, in preprocess_args
    self.print_warning(warning)
  File "/home/tw/w/borg/src/borg/archiver.py", line 127, in print_warning
    logger.warning(msg)
  File "/home/tw/w/borg/src/borg/logger.py", line 175, in warning
    return self.__logger.warning(*args, **kw)
  File "/home/tw/w/borg/src/borg/logger.py", line 150, in __logger
    raise Exception("tried to call a logger before setup_logging() was called")
Exception: tried to call a logger before setup_logging() was called
```

**Comment by ThomasWaldmann** [comment]
note: maybe --list-format (borg 1.0) is not valid or deprecated now (in master/1.1 it is --format).
