### ISSUE TITLE
crash: manifest.timestamp == None?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1487]
current git master:
```
[nix-shell:/run/media/ronny/backups]$ borg list borg::home-ronny-pc-2016-05-07T15:02:35+0200 --format '{path}{LF}'
Local Exception.
Traceback (most recent call last):
  File "/nix/store/lskgyhvci1wzzc4nv02g6f8c4dl3bhaf-borgbackup-1.0.6/lib/python3.4/site-packages/borg/archiver.py", line 2368, in main
    exit_code = archiver.run(args)
  File "/nix/store/lskgyhvci1wzzc4nv02g6f8c4dl3bhaf-borgbackup-1.0.6/lib/python3.4/site-packages/borg/archiver.py", line 2301, in run
    return args.func(args)
  File "/nix/store/lskgyhvci1wzzc4nv02g6f8c4dl3bhaf-borgbackup-1.0.6/lib/python3.4/site-packages/borg/archiver.py", line 97, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/nix/store/lskgyhvci1wzzc4nv02g6f8c4dl3bhaf-borgbackup-1.0.6/lib/python3.4/site-packages/borg/archiver.py", line 792, in do_list
    with Cache(repository, key, manifest, lock_wait=self.lock_wait) as cache:
  File "/nix/store/lskgyhvci1wzzc4nv02g6f8c4dl3bhaf-borgbackup-1.0.6/lib/python3.4/site-packages/borg/cache.py", line 102, in __init__
    self.commit()
  File "/nix/store/lskgyhvci1wzzc4nv02g6f8c4dl3bhaf-borgbackup-1.0.6/lib/python3.4/site-packages/borg/cache.py", line 227, in commit
    self.config.set('cache', 'timestamp', self.manifest.timestamp)
  File "/nix/store/n9p1x3ss0y0fj7j7h5mrzrajjhi08m3z-python3-3.4.5/lib/python3.4/configparser.py", line 1165, in set
    self._validate_value_types(option=option, value=value)
  File "/nix/store/n9p1x3ss0y0fj7j7h5mrzrajjhi08m3z-python3-3.4.5/lib/python3.4/configparser.py", line 1154, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings

Platform: Linux ronny-rh-work-nix 4.4.17 #1-NixOS SMP Wed Aug 10 09:49:43 UTC 2016 x86_64 
Linux:   
Borg: 1.1+git  Python: CPython 3.4.5
PID: 31509  CWD: /run/media/ronny/backups
sys.argv: ['borg', 'list', 'borg::home-ronny-pc-2016-05-07T15:02:35+0200', '--format', '{path}{LF}']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment]
Is there no "timestamp" in borg 1.0.5 repo manifest, so the .get('timestamp') results in None?
