### ISSUE TITLE
exception on list comand

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [borgbackup/borg#1499]
borg version: commit - f7c1c71ff17bdec5dc261df5fe36bb29c892a2ab
```
$ sh forall.sh 
handleing home-heisenbug-2015-09-06.checkpoint
handleing home-heisenbug-2015-09-07
handleing home-heisenbug-2015-09-08-2
handleing home-heisenbug-2015-09-08
handleing home-heisenbug-2015-11-16
handleing home-ronny-pc-2016-05-07
handleing home-ronny-pc-2016-05-07T15:02:35+0200
^Thhandleing home-ronny-pc-2016-05-07T15:24:21+0200
handleing home-ronny-pc-2016-05-14T00:26:57+0200
handleing home-ronny-pc-2016-05-14T00:34:27+0200
handleing home-ronny-pc-2016-05-14T00:38:47+0200
handleing home-ronny-pc-2016-05-14T00:41:49+0200
handleing home-ronny-pc-2016-05-26T12:16:20+02:00
handleing home-ronny-pc-2016-05-26T12:19:15+02:00
handleing home-ronny-pc-2016-05-28T19:06:01+02:00
handleing home-ronny-pc-2016-05-28T19:07:43+02:00
handleing home-ronny-pc-2016-05-30T22:26:13+02:00
handleing sda8-ronny-pc-2016-05-31T13:20:10+02:00.checkpoint
handleing sda8-ronny-pc-2016-05-31T16:33:59+02:00
handleing home-ronny-pc-2016-06-01T09:16:05+02:00
handleing home-ronny-pc-2016-06-03 15:37:42.289397
Local Exception.
Traceback (most recent call last):
  File "/nix/store/dv8cnrgx6hxyzcykixk3fzkasf61gfl2-borgbackup-1.0.6/lib/python3.4/site-packages/borg/archiver.py", line 2368, in main
    exit_code = archiver.run(args)
  File "/nix/store/dv8cnrgx6hxyzcykixk3fzkasf61gfl2-borgbackup-1.0.6/lib/python3.4/site-packages/borg/archiver.py", line 2301, in run
    return args.func(args)
  File "/nix/store/dv8cnrgx6hxyzcykixk3fzkasf61gfl2-borgbackup-1.0.6/lib/python3.4/site-packages/borg/archiver.py", line 97, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/nix/store/dv8cnrgx6hxyzcykixk3fzkasf61gfl2-borgbackup-1.0.6/lib/python3.4/site-packages/borg/archiver.py", line 791, in do_list
    matcher, _ = self.build_matcher(args.excludes, args.paths)
  File "/nix/store/dv8cnrgx6hxyzcykixk3fzkasf61gfl2-borgbackup-1.0.6/lib/python3.4/site-packages/borg/archiver.py", line 167, in build_matcher
    include_patterns.extend(parse_pattern(i, PathPrefixPattern) for i in paths)
  File "/nix/store/dv8cnrgx6hxyzcykixk3fzkasf61gfl2-borgbackup-1.0.6/lib/python3.4/site-packages/borg/archiver.py", line 167, in <genexpr>
    include_patterns.extend(parse_pattern(i, PathPrefixPattern) for i in paths)
  File "/nix/store/dv8cnrgx6hxyzcykixk3fzkasf61gfl2-borgbackup-1.0.6/lib/python3.4/site-packages/borg/helpers.py", line 496, in parse_pattern
    raise ValueError("Unknown pattern style: {}".format(style))
ValueError: Unknown pattern style: 15

Platform: Linux ronny-rh-work-nix 4.4.17 #1-NixOS SMP Wed Aug 10 09:49:43 UTC 2016 x86_64 
Linux:   
Borg: 1.1+git  Python: CPython 3.4.5
PID: 26861  CWD: /run/media/ronny/backups
sys.argv: ['borg', 'list', '--format', '{archivename} {sha256} {path}{LF}', 'borg::home-ronny-pc-2016-06-03', '15:37:42.289397']
SSH_ORIGINAL_COMMAND: None

handleing home-ronny-pc-2016-06-12 12:52:21.284504
Local Exception.
Traceback (most recent call last):
  File "/nix/store/dv8cnrgx6hxyzcykixk3fzkasf61gfl2-borgbackup-1.0.6/lib/python3.4/site-packages/borg/archiver.py", line 2368, in main
    exit_code = archiver.run(args)
  File "/nix/store/dv8cnrgx6hxyzcykixk3fzkasf61gfl2-borgbackup-1.0.6/lib/python3.4/site-packages/borg/archiver.py", line 2301, in run
    return args.func(args)
  File "/nix/store/dv8cnrgx6hxyzcykixk3fzkasf61gfl2-borgbackup-1.0.6/lib/python3.4/site-packages/borg/archiver.py", line 97, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/nix/store/dv8cnrgx6hxyzcykixk3fzkasf61gfl2-borgbackup-1.0.6/lib/python3.4/site-packages/borg/archiver.py", line 791, in do_list
    matcher, _ = self.build_matcher(args.excludes, args.paths)
  File "/nix/store/dv8cnrgx6hxyzcykixk3fzkasf61gfl2-borgbackup-1.0.6/lib/python3.4/site-packages/borg/archiver.py", line 167, in build_matcher
    include_patterns.extend(parse_pattern(i, PathPrefixPattern) for i in paths)
  File "/nix/store/dv8cnrgx6hxyzcykixk3fzkasf61gfl2-borgbackup-1.0.6/lib/python3.4/site-packages/borg/archiver.py", line 167, in <genexpr>
    include_patterns.extend(parse_pattern(i, PathPrefixPattern) for i in paths)
  File "/nix/store/dv8cnrgx6hxyzcykixk3fzkasf61gfl2-borgbackup-1.0.6/lib/python3.4/site-packages/borg/helpers.py", line 496, in parse_pattern
    raise ValueError("Unknown pattern style: {}".format(style))
ValueError: Unknown pattern style: 12

Platform: Linux ronny-rh-work-nix 4.4.17 #1-NixOS SMP Wed Aug 10 09:49:43 UTC 2016 x86_64 
Linux:   
Borg: 1.1+git  Python: CPython 3.4.5
PID: 26922  CWD: /run/media/ronny/backups
sys.argv: ['borg', 'list', '--format', '{archivename} {sha256} {path}{LF}', 'borg::home-ronny-pc-2016-06-12', '12:52:21.284504']
SSH_ORIGINAL_COMMAND: None
```

fora-all.sh:
```
cat archive_names.txt| while read name
do
  echo handleing $name
  borg list --format '{archivename} {sha256} {path}{LF}' borg::$name >> elements.txt
done
```

**Comment by enkore** [comment]
Shell escaping issue; archive name is split by shell or has spaces:

`sys.argv: [... 'borg::home-ronny-pc-2016-06-12', '12:52:21.284504']`

The traceback for this error is a bit too much... :D

**Comment by RonnyPfannschmidt** [comment]
thanks for being that pair of eyes - i completely missed that
