### ISSUE TITLE
Handling FUSE filesystem errors

### ISSUE THREAD

**Issue by RealityFork** [borgbackup/borg#1533]
Using: Borg 1.0.2, Ubuntu Server 16.04

I am trying to use borg with the cloud storage system Backblae B2 using [b2_fuse](https://github.com/sondree/b2_fuse), mounting a b2 bucket as the 'data' directory inside a borg repo.
When the FUSE filesystem fails mid-backup, borg fails badly and reads some files in the repo when the user resumes a backup. On large backups borg may read a large amount of data, which may cost the user (most cloud storage charges for downloads).

Steps to reproduce:
- Init a borg repo `borg init /backup`
- Copy contents of data folder to b2 bucket
- mount b2 bucket over data folder `python b2fuse.py /backup/data`
- Create a backup and let it finish `borg create /backup::1 /flash`
- Change the contents of `/flash` and start another backup `borg create /backup::2 /flash`
- Kill the fuse filesystem process. The resulting error from borg is this:

```
~ borg create -psv /backup/::2 /flash
Enter passphrase for key /backup:
^CException ignored in: <bound method Repository.__del__ of <Repository /backup>>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 71, in __del__
    assert False, "cleanup happened in Repository.__del__"
AssertionError: cleanup happened in Repository.__del__
Local Exception.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 80, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 246, in do_create
    create_inner(archive, cache)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 218, in create_inner
    read_special=args.read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 300, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 274, in _process
    status = archive.process_file(path, st, cache, self.ignore_inode)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 557, in process_file
    chunks.append(cache.add_chunk(self.key.id_hash(chunk), chunk, self.stats))
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 365, in add_chunk
    self.repository.put(id, data, wait=False)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 465, in put
    segment, offset = self.io.write_put(id, data)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 690, in write_put
    fd.write(b''.join((crc, header, id, data)))
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1498, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1452, in run
    return args.func(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 80, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 86, in __exit__
    self.close()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 177, in close
    self.io.close()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 517, in close
    self.fds.clear()
  File "/usr/lib/python3/dist-packages/borg/lrucache.py", line 33, in clear
    self._dispose(value)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 508, in <lambda>
    dispose=lambda fd: fd.close())
OSError: [Errno 107] Transport endpoint is not connected

Platform: Linux cheryl 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64
Linux: Ubuntu 16.04 xenial
Borg: 1.0.2  Python: CPython 3.5.1
PID: 9649  CWD: /root
sys.argv: ['/usr/bin/borg', 'create', '-psv', '/backup/::2', '/flash']
SSH_ORIGINAL_COMMAND: None
```
[hints.17.txt](https://github.com/borgbackup/borg/files/436477/hints.17.txt)
[index.17.txt](https://github.com/borgbackup/borg/files/436476/index.17.txt)
[lock.roster.txt](https://github.com/borgbackup/borg/files/436478/lock.roster.txt)
The attached files were taken after this error from borg.

- Resume the backup `borg create /backup::2 /flash`
Below is the log from the FUSE filesystem since the backup is resumed:
```
2016-08-25 19:39:54,570:INFO:list_buckets
2016-08-25 19:40:10,016:DEBUG:Get attr /
2016-08-25 19:40:10,016:DEBUG:Memory used 0.0
2016-08-25 19:40:10,017:DEBUG:Readdir /
2016-08-25 19:40:10,017:INFO:_list_dir 
2016-08-25 19:40:10,958:DEBUG:Get attr /0
2016-08-25 19:40:10,959:DEBUG:Memory used 0.0
2016-08-25 19:40:10,960:DEBUG:Readdir /0
2016-08-25 19:40:10,960:INFO:_list_dir 0
2016-08-25 19:40:11,677:DEBUG:Get attr /0/23
2016-08-25 19:40:11,677:DEBUG:Memory used 0.0
2016-08-25 19:40:11,678:DEBUG:Open /0/23 (flags:32768)
2016-08-25 19:40:11,678:INFO:_get_file 0/23
2016-08-25 19:40:12,385:INFO:_get_file File downloaded
2016-08-25 19:40:17,746:DEBUG:Get attr /0/23
2016-08-25 19:40:17,747:DEBUG:Memory used 4.16
2016-08-25 19:40:17,748:DEBUG:Read /0/23 (len:4096 offset:4362240 fh:1)
2016-08-25 19:40:17,748:DEBUG:Flush /0/23 1
2016-08-25 19:40:17,749:DEBUG:File not dirty, skipping upload
2016-08-25 19:40:17,749:DEBUG:Release /0/23 1
2016-08-25 19:40:17,749:DEBUG:Flushing file in case it was dirty
2016-08-25 19:40:17,750:DEBUG:Flush 0/23 1
2016-08-25 19:40:17,750:DEBUG:File not dirty, skipping upload
2016-08-25 19:40:17,750:DEBUG:Get attr /0
2016-08-25 19:40:17,750:DEBUG:Memory used 4.16
2016-08-25 19:40:17,751:DEBUG:Get attr /0/22
2016-08-25 19:40:17,751:DEBUG:Memory used 4.16
2016-08-25 19:40:17,752:DEBUG:Open /0/22 (flags:32768)
2016-08-25 19:40:17,752:INFO:_get_file 0/22
2016-08-25 19:40:18,469:INFO:_get_file File downloaded
2016-08-25 19:40:30,465:DEBUG:Get attr /0/22
2016-08-25 19:40:30,466:DEBUG:Memory used 10.8
2016-08-25 19:40:30,467:DEBUG:Read /0/22 (len:4096 offset:6955008 fh:2)
2016-08-25 19:40:30,468:DEBUG:Flush /0/22 2
2016-08-25 19:40:30,468:DEBUG:File not dirty, skipping upload
2016-08-25 19:40:30,469:DEBUG:Release /0/22 2
2016-08-25 19:40:30,469:DEBUG:Flushing file in case it was dirty
2016-08-25 19:40:30,469:DEBUG:Flush 0/22 2
2016-08-25 19:40:30,470:DEBUG:File not dirty, skipping upload
2016-08-25 19:40:30,470:DEBUG:Get attr /0
2016-08-25 19:40:30,470:DEBUG:Memory used 10.8
2016-08-25 19:40:30,471:DEBUG:Get attr /0/21
2016-08-25 19:40:30,471:DEBUG:Memory used 10.8
2016-08-25 19:40:30,472:DEBUG:Open /0/21 (flags:32768)
2016-08-25 19:40:30,472:INFO:_get_file 0/21
2016-08-25 19:40:31,471:INFO:_get_file File downloaded
2016-08-25 19:40:39,012:DEBUG:Get attr /0/21
2016-08-25 19:40:39,013:DEBUG:Memory used 20.64
2016-08-25 19:40:39,014:DEBUG:Read /0/21 (len:4096 offset:10326016 fh:3)
2016-08-25 19:40:39,015:DEBUG:Flush /0/21 3
2016-08-25 19:40:39,015:DEBUG:File not dirty, skipping upload
2016-08-25 19:40:39,016:DEBUG:Release /0/21 3
2016-08-25 19:40:39,016:DEBUG:Flushing file in case it was dirty
2016-08-25 19:40:39,016:DEBUG:Flush 0/21 3
2016-08-25 19:40:39,017:DEBUG:File not dirty, skipping upload
2016-08-25 19:40:39,017:DEBUG:Get attr /0
2016-08-25 19:40:39,017:DEBUG:Memory used 20.64
2016-08-25 19:40:39,018:DEBUG:Get attr /0/20
2016-08-25 19:40:39,018:DEBUG:Memory used 20.64
2016-08-25 19:40:39,019:DEBUG:Open /0/20 (flags:32768)
2016-08-25 19:40:39,019:INFO:_get_file 0/20
2016-08-25 19:40:39,721:INFO:_get_file File downloaded
2016-08-25 19:40:47,243:DEBUG:Get attr /0/20
2016-08-25 19:40:47,243:DEBUG:Memory used 26.67
2016-08-25 19:40:47,245:DEBUG:Read /0/20 (len:4096 offset:6311936 fh:4)
2016-08-25 19:40:47,245:DEBUG:Flush /0/20 4
2016-08-25 19:40:47,246:DEBUG:File not dirty, skipping upload
2016-08-25 19:40:47,246:DEBUG:Release /0/20 4
2016-08-25 19:40:47,246:DEBUG:Flushing file in case it was dirty
2016-08-25 19:40:47,247:DEBUG:Flush 0/20 4
2016-08-25 19:40:47,247:DEBUG:File not dirty, skipping upload
2016-08-25 19:40:47,247:DEBUG:Get attr /0
2016-08-25 19:40:47,248:DEBUG:Memory used 26.67
2016-08-25 19:40:47,248:DEBUG:Get attr /0/19
2016-08-25 19:40:47,248:DEBUG:Memory used 26.67
2016-08-25 19:40:47,249:DEBUG:Open /0/19 (flags:32768)
2016-08-25 19:40:47,250:INFO:_get_file 0/19
2016-08-25 19:40:48,191:INFO:_get_file File downloaded
2016-08-25 19:40:57,574:DEBUG:Get attr /0/19
2016-08-25 19:40:57,574:DEBUG:Memory used 35.21
2016-08-25 19:40:57,576:DEBUG:Read /0/19 (len:4096 offset:8962048 fh:5)
2016-08-25 19:40:57,576:DEBUG:Flush /0/19 5
2016-08-25 19:40:57,577:DEBUG:File not dirty, skipping upload
2016-08-25 19:40:57,577:DEBUG:Release /0/19 5
2016-08-25 19:40:57,578:DEBUG:Flushing file in case it was dirty
2016-08-25 19:40:57,578:DEBUG:Flush 0/19 5
2016-08-25 19:40:57,578:DEBUG:File not dirty, skipping upload
2016-08-25 19:40:57,578:DEBUG:Get attr /0
2016-08-25 19:40:57,579:DEBUG:Memory used 35.21
2016-08-25 19:40:57,579:DEBUG:Get attr /0/18
2016-08-25 19:40:57,579:DEBUG:Memory used 35.21
2016-08-25 19:40:57,580:DEBUG:Open /0/18 (flags:32768)
2016-08-25 19:40:57,581:INFO:_get_file 0/18
2016-08-25 19:40:58,371:INFO:_get_file File downloaded
2016-08-25 19:41:05,379:DEBUG:Get attr /0/18
2016-08-25 19:41:05,380:DEBUG:Memory used 42.12
2016-08-25 19:41:05,381:DEBUG:Read /0/18 (len:4096 offset:7237632 fh:6)
2016-08-25 19:41:05,382:DEBUG:Flush /0/18 6
2016-08-25 19:41:05,382:DEBUG:File not dirty, skipping upload
2016-08-25 19:41:05,383:DEBUG:Release /0/18 6
2016-08-25 19:41:05,383:DEBUG:Flushing file in case it was dirty
2016-08-25 19:41:05,383:DEBUG:Flush 0/18 6
2016-08-25 19:41:05,384:DEBUG:File not dirty, skipping upload
2016-08-25 19:41:05,384:DEBUG:Get attr /0
2016-08-25 19:41:05,384:DEBUG:Memory used 42.12
2016-08-25 19:41:05,385:DEBUG:Get attr /0/17
2016-08-25 19:41:05,385:DEBUG:Memory used 42.12
2016-08-25 19:41:05,386:DEBUG:Open /0/17 (flags:32768)
2016-08-25 19:41:05,386:INFO:_get_file 0/17
2016-08-25 19:41:06,046:INFO:_get_file File downloaded
2016-08-25 19:41:09,156:DEBUG:Get attr /0/17
2016-08-25 19:41:09,156:DEBUG:Memory used 43.18
2016-08-25 19:41:09,158:DEBUG:Read /0/17 (len:4096 offset:1110016 fh:7)
2016-08-25 19:41:09,159:DEBUG:Flush /0/17 7
2016-08-25 19:41:09,159:DEBUG:File not dirty, skipping upload
2016-08-25 19:41:09,160:DEBUG:Release /0/17 7
2016-08-25 19:41:09,160:DEBUG:Flushing file in case it was dirty
2016-08-25 19:41:09,160:DEBUG:Flush 0/17 7
2016-08-25 19:41:09,160:DEBUG:File not dirty, skipping upload
2016-08-25 19:41:09,161:DEBUG:Get attr /0
2016-08-25 19:41:09,161:DEBUG:Memory used 43.18
2016-08-25 19:41:09,162:DEBUG:Get attr /0/17
2016-08-25 19:41:09,162:DEBUG:Memory used 43.18
2016-08-25 19:41:09,163:DEBUG:Open /0/17 (flags:32768)
2016-08-25 19:41:09,164:DEBUG:Read /0/17 (len:4096 offset:1110016 fh:8)
2016-08-25 19:41:33,893:DEBUG:Get attr /
2016-08-25 19:41:33,894:DEBUG:Memory used 43.18
2016-08-25 19:41:33,895:DEBUG:Readdir /
2016-08-25 19:41:33,896:DEBUG:Get attr /0
2016-08-25 19:41:33,897:DEBUG:Memory used 43.18
2016-08-25 19:41:33,897:DEBUG:Readdir /0
2016-08-25 19:41:33,899:DEBUG:Get attr /0/23
2016-08-25 19:41:33,899:DEBUG:Memory used 43.18
2016-08-25 19:41:33,900:DEBUG:Open /0/23 (flags:32768)
2016-08-25 19:41:33,901:DEBUG:Read /0/23 (len:4096 offset:4362240 fh:9)
2016-08-25 19:41:33,902:DEBUG:Flush /0/23 9
2016-08-25 19:41:33,902:DEBUG:File not dirty, skipping upload
2016-08-25 19:41:33,902:DEBUG:Release /0/23 9
2016-08-25 19:41:33,903:DEBUG:Flushing file in case it was dirty
2016-08-25 19:41:33,903:DEBUG:Flush 0/23 9
2016-08-25 19:41:33,903:DEBUG:File not dirty, skipping upload
2016-08-25 19:41:33,903:DEBUG:Get attr /0/22
2016-08-25 19:41:33,904:DEBUG:Memory used 43.18
2016-08-25 19:41:33,905:DEBUG:Open /0/22 (flags:32768)
2016-08-25 19:41:33,906:DEBUG:Read /0/22 (len:4096 offset:6955008 fh:10)
2016-08-25 19:41:33,906:DEBUG:Flush /0/22 10
2016-08-25 19:41:33,907:DEBUG:File not dirty, skipping upload
2016-08-25 19:41:33,907:DEBUG:Release /0/22 10
2016-08-25 19:41:33,908:DEBUG:Flushing file in case it was dirty
2016-08-25 19:41:33,908:DEBUG:Flush 0/22 10
2016-08-25 19:41:33,908:DEBUG:File not dirty, skipping upload
2016-08-25 19:41:33,908:DEBUG:Get attr /0/21
2016-08-25 19:41:33,909:DEBUG:Memory used 43.18
2016-08-25 19:41:33,909:DEBUG:Open /0/21 (flags:32768)
2016-08-25 19:41:33,910:DEBUG:Read /0/21 (len:4096 offset:10326016 fh:11)
2016-08-25 19:41:33,911:DEBUG:Flush /0/21 11
2016-08-25 19:41:33,911:DEBUG:File not dirty, skipping upload
2016-08-25 19:41:33,912:DEBUG:Release /0/21 11
2016-08-25 19:41:33,912:DEBUG:Flushing file in case it was dirty
2016-08-25 19:41:33,912:DEBUG:Flush 0/21 11
2016-08-25 19:41:33,913:DEBUG:File not dirty, skipping upload
2016-08-25 19:41:33,913:DEBUG:Get attr /0/20
2016-08-25 19:41:33,913:DEBUG:Memory used 43.18
2016-08-25 19:41:33,914:DEBUG:Open /0/20 (flags:32768)
2016-08-25 19:41:33,915:DEBUG:Read /0/20 (len:4096 offset:6311936 fh:12)
2016-08-25 19:41:33,916:DEBUG:Flush /0/20 12
2016-08-25 19:41:33,916:DEBUG:File not dirty, skipping upload
2016-08-25 19:41:33,917:DEBUG:Release /0/20 12
2016-08-25 19:41:33,917:DEBUG:Flushing file in case it was dirty
2016-08-25 19:41:33,917:DEBUG:Flush 0/20 12
2016-08-25 19:41:33,917:DEBUG:File not dirty, skipping upload
2016-08-25 19:41:33,918:DEBUG:Get attr /0/19
2016-08-25 19:41:33,918:DEBUG:Memory used 43.18
2016-08-25 19:41:33,919:DEBUG:Open /0/19 (flags:32768)
2016-08-25 19:41:33,920:DEBUG:Read /0/19 (len:4096 offset:8962048 fh:13)
2016-08-25 19:41:33,920:DEBUG:Flush /0/19 13
2016-08-25 19:41:33,921:DEBUG:File not dirty, skipping upload
2016-08-25 19:41:33,921:DEBUG:Release /0/19 13
2016-08-25 19:41:33,921:DEBUG:Flushing file in case it was dirty
2016-08-25 19:41:33,922:DEBUG:Flush 0/19 13
2016-08-25 19:41:33,922:DEBUG:File not dirty, skipping upload
2016-08-25 19:41:33,922:DEBUG:Get attr /0/18
2016-08-25 19:41:33,922:DEBUG:Memory used 43.18
2016-08-25 19:41:33,923:DEBUG:Open /0/18 (flags:32768)
2016-08-25 19:41:33,924:DEBUG:Read /0/18 (len:4096 offset:7237632 fh:14)
2016-08-25 19:41:33,925:DEBUG:Flush /0/18 14
2016-08-25 19:41:33,925:DEBUG:File not dirty, skipping upload
2016-08-25 19:41:33,926:DEBUG:Release /0/18 14
2016-08-25 19:41:33,926:DEBUG:Flushing file in case it was dirty
2016-08-25 19:41:33,926:DEBUG:Flush 0/18 14
2016-08-25 19:41:33,926:DEBUG:File not dirty, skipping upload
2016-08-25 19:41:33,926:DEBUG:Get attr /0/17
2016-08-25 19:41:33,927:DEBUG:Memory used 43.18
2016-08-25 19:41:33,928:DEBUG:Open /0/17 (flags:32768)
2016-08-25 19:41:33,929:DEBUG:Read /0/17 (len:4096 offset:1110016 fh:15)
2016-08-25 19:41:33,929:DEBUG:Flush /0/17 15
2016-08-25 19:41:33,929:DEBUG:File not dirty, skipping upload
2016-08-25 19:41:33,930:DEBUG:Release /0/17 15
2016-08-25 19:41:33,930:DEBUG:Flushing file in case it was dirty
2016-08-25 19:41:33,930:DEBUG:Flush 0/17 15
2016-08-25 19:41:33,931:DEBUG:File not dirty, skipping upload
2016-08-25 19:41:33,932:DEBUG:Get attr /
2016-08-25 19:41:33,932:DEBUG:Memory used 43.18
2016-08-25 19:41:33,933:DEBUG:Readdir /
2016-08-25 19:41:33,934:DEBUG:Get attr /0
2016-08-25 19:41:33,935:DEBUG:Memory used 43.18
2016-08-25 19:41:33,935:DEBUG:Readdir /0
2016-08-25 19:41:33,937:DEBUG:Unlink /0/23
2016-08-25 19:41:33,937:INFO:get_file_versions 0/23
2016-08-25 19:41:34,625:INFO:_delete_file 0/23 (1)
2016-08-25 19:41:35,382:INFO:_delete_file File deleted (0/23) 
2016-08-25 19:41:35,383:DEBUG:Get attr /0
2016-08-25 19:41:35,383:DEBUG:Memory used 39.02
2016-08-25 19:41:35,384:DEBUG:Get attr /0/22
2016-08-25 19:41:35,384:DEBUG:Memory used 39.02
2016-08-25 19:41:35,385:DEBUG:Unlink /0/22
2016-08-25 19:41:35,386:INFO:get_file_versions 0/22
2016-08-25 19:41:36,042:INFO:_delete_file 0/22 (1)
2016-08-25 19:41:36,766:INFO:_delete_file File deleted (0/22) 
2016-08-25 19:41:36,767:DEBUG:Get attr /0
2016-08-25 19:41:36,767:DEBUG:Memory used 32.38
2016-08-25 19:41:36,768:DEBUG:Get attr /0/21
2016-08-25 19:41:36,768:DEBUG:Memory used 32.38
2016-08-25 19:41:36,769:DEBUG:Unlink /0/21
2016-08-25 19:41:36,770:INFO:get_file_versions 0/21
2016-08-25 19:41:37,483:INFO:_delete_file 0/21 (1)
2016-08-25 19:41:38,338:INFO:_delete_file File deleted (0/21) 
2016-08-25 19:41:38,339:DEBUG:Get attr /0
2016-08-25 19:41:38,339:DEBUG:Memory used 22.53
2016-08-25 19:41:38,340:DEBUG:Get attr /0/20
2016-08-25 19:41:38,340:DEBUG:Memory used 22.53
2016-08-25 19:41:38,341:DEBUG:Unlink /0/20
2016-08-25 19:41:38,342:INFO:get_file_versions 0/20
2016-08-25 19:41:39,004:INFO:_delete_file 0/20 (1)
2016-08-25 19:41:39,759:INFO:_delete_file File deleted (0/20) 
2016-08-25 19:41:39,760:DEBUG:Get attr /0
2016-08-25 19:41:39,760:DEBUG:Memory used 16.51
2016-08-25 19:41:39,761:DEBUG:Get attr /0/19
2016-08-25 19:41:39,761:DEBUG:Memory used 16.51
2016-08-25 19:41:39,762:DEBUG:Unlink /0/19
2016-08-25 19:41:39,763:INFO:get_file_versions 0/19
2016-08-25 19:41:40,428:INFO:_delete_file 0/19 (1)
2016-08-25 19:41:41,254:INFO:_delete_file File deleted (0/19) 
2016-08-25 19:41:41,255:DEBUG:Get attr /0
2016-08-25 19:41:41,255:DEBUG:Memory used 7.96
2016-08-25 19:41:41,256:DEBUG:Get attr /0/18
2016-08-25 19:41:41,256:DEBUG:Memory used 7.96
2016-08-25 19:41:41,257:DEBUG:Unlink /0/18
2016-08-25 19:41:41,257:INFO:get_file_versions 0/18
2016-08-25 19:41:41,916:INFO:_delete_file 0/18 (1)
2016-08-25 19:41:42,702:INFO:_delete_file File deleted (0/18) 
2016-08-25 19:41:42,703:DEBUG:Get attr /0
2016-08-25 19:41:42,704:DEBUG:Memory used 1.06
2016-08-25 19:41:42,704:DEBUG:Get attr /0/18
2016-08-25 19:41:42,705:DEBUG:Memory used 1.06
2016-08-25 19:41:42,705:DEBUG:Create /0/18 (mode:33152)
2016-08-25 19:41:42,706:DEBUG:Get attr /0/18
2016-08-25 19:41:42,706:DEBUG:Memory used 1.06
2016-08-25 19:41:42,821:DEBUG:Write /0/18 (len:168 offset:0)
2016-08-25 19:41:42,822:DEBUG:Write /0/18 (len:3928 offset:168)
2016-08-25 19:41:42,824:DEBUG:Write /0/18 (len:4096 offset:4096)
2016-08-25 19:41:42,825:DEBUG:Write /0/18 (len:4096 offset:8192)
2016-08-25 19:41:42,827:DEBUG:Write /0/18 (len:4096 offset:12288)
2016-08-25 19:41:42,828:DEBUG:Write /0/18 (len:4096 offset:16384)
```
(It continues on writing /0/18 through /0/60 until the backup is done successfully).
I'm interested the `_get_file` calls above.

I'm guessing the hard error from borg made it lose it's place.
With larger backups I fear that borg may download large amounts of data when trying to rebuild and incur some charges.

Let me know if you need any other info.

**Comment by infectormp** [comment]
Can you try reproduce this problem with borg 1.0.7?

**Comment by RealityFork** [comment]
The error is different (using the binary release of 1.0.7) but the effect is the same.
The error when killing the fuse filesystem::
```➜  ~ ./borg-linux64 create -psv /backup/::4 /flash
Enter passphrase for key /backup:
Exception ignored in: <bound method Repository.__del__ of <Repository /backup>>ld/region/r.0.0.mcr
Traceback (most recent call last):
  File "borg/repository.py", line 72, in __del__
  File "borg/repository.py", line 190, in close
  File "borg/repository.py", line 586, in close
  File "borg/repository.py", line 815, in close_segment
ValueError: flush of closed file
Local Exception.
Traceback (most recent call last):
  File "borg/archiver.py", line 85, in wrapper
  File "borg/archiver.py", line 249, in do_create
  File "borg/archiver.py", line 223, in create_inner
  File "borg/archiver.py", line 303, in _process
  File "borg/archiver.py", line 303, in _process
  File "borg/archiver.py", line 303, in _process
  File "borg/archiver.py", line 303, in _process
  File "borg/archiver.py", line 303, in _process
  File "borg/archiver.py", line 277, in _process
  File "borg/archive.py", line 683, in process_file
  File "borg/cache.py", line 371, in add_chunk
  File "borg/repository.py", line 535, in put
  File "borg/repository.py", line 784, in write_put
  File "borg/repository.py", line 662, in get_write_fd
  File "borg/repository.py", line 821, in close_segment
OSError: [Errno 14] Bad address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "borg/archiver.py", line 1684, in main
  File "borg/archiver.py", line 1621, in run
  File "borg/archiver.py", line 85, in wrapper
  File "borg/repository.py", line 94, in __exit__
  File "borg/repository.py", line 190, in close
  File "borg/repository.py", line 586, in close
  File "borg/repository.py", line 815, in close_segment
ValueError: flush of closed file

Platform: Linux cheryl 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64
Linux: debian stretch/sid
Borg: 1.0.7  Python: CPython 3.5.2
PID: 10278  CWD: /root
sys.argv: ['./borg-linux64', 'create', '-psv', '/backup/::4', '/flash']
SSH_ORIGINAL_COMMAND: None
```

**Comment by enkore** [comment]
> When the FUSE filesystem fails mid-backup, borg fails badly

Expected behaviour

> reads some files in the repo when the user resumes a backup. On large backups borg may read a large amount of data, which may cost the user (most cloud storage charges for downloads).

This is also expected behaviour for the local FS repository backend.

I don't see the bug...?

**Comment by enkore** [comment]
> I'm interested the _get_file calls above.

> I'm guessing the hard error from borg made it lose it's place.
> With larger backups I fear that borg may download large amounts of data when trying to rebuild and incur some charges.

When it crashes (borg itself, computer, filesystem) it needs to find the last commit. Worst case: reads all data you can write between two checkpoints. If index.N, hints.N are not in sync with the last commit (in, say, segment M), then it has to read al segments from N to M. If you have no index/hints, then that's all data in the repo.

**Comment by RealityFork** [comment]
Ok no worries guys.
I was talking to ThomasW and green-- on IRC earlier today and they didn't seem keen that the error was unhandled - told me to put this data up in an issue when I got home.
If it is expected behaviour then just close this.
