### ISSUE TITLE
fuse: "Invalid argument" OSError with negative number for seek (-o versions)

### ISSUE THREAD

**Issue by blueyed** [borgbackup/borg#1599]
I have tried to use the `-o versions` option with `borg mount`, but got the following error:

```
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 2436, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 2353, in run
    return args.func(args)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 98, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 799, in do_mount
    operations.mount(args.mountpoint, args.options, args.foreground)
  File "/usr/lib/python3.5/site-packages/borg/fuse.py", line 108, in mount
    self._create_filesystem()
  File "/usr/lib/python3.5/site-packages/borg/fuse.py", line 86, in _create_filesystem
    self.process_archive(archive)
  File "/usr/lib/python3.5/site-packages/borg/fuse.py", line 159, in process_archive
    self.process_leaf(segments[-1], item, parent, prefix, is_dir)
  File "/usr/lib/python3.5/site-packages/borg/fuse.py", line 176, in process_leaf
    item = self.cache.get(inode)
  File "/usr/lib/python3.5/site-packages/borg/fuse.py", line 46, in get
    self.fd.seek(inode - self.offset, io.SEEK_SET)
OSError: [Errno 22] Invalid argument

Platform: Linux lena.thequod.de 4.7.2-1-ARCH #1 SMP PREEMPT Sat Aug 20 23:02:56 CEST 2016 x86_64 
Linux: arch Arch Linux
Borg: 1.1.0b2.dev35+ng783d01f  Python: CPython 3.5.2
PID: 16776  CWD: /home/user
sys.argv: ['/usr/bin/borg', 'mount', '-o', 'versions', 'tmp/borg-backup', 'tmp/mnt']
SSH_ORIGINAL_COMMAND: None
```

The problem is that `inode - self.offset` is negative here:

```
> /usr/lib/python3.5/site-packages/borg/fuse.py(48)get()
-> self.fd.seek(inode - self.offset, io.SEEK_SET)
(Pdb) inode
16069
(Pdb) self.offset
1000000
(Pdb) io.SEEK_SET
0
(Pdb) self.fd
<_io.BufferedRandom name=4>
(Pdb) self.fd.seek(inode - self.offset, io.SEEK_SET)
*** OSError: [Errno 22] Invalid argument
(Pdb) 
```

**Comment by enkore** [comment]
What does the (anonymized) command line look like used for creating the archive in question? (borg info)

**Comment by blueyed** [comment]
@enkore 
What do you mean?
I am running it on a repo here..  and `borg info` does not say much for it.

**Comment by enkore** [comment]
Ah, alright my bad.

**Comment by ThomasWaldmann** [comment]
I think i have the reason why it malfunctions. It is related to the modified filenames for versioning and finding hardlink masters (which it tries with the unmodified name). I'll try to fix it...

**Comment by blueyed** [comment]
FWIW, I've created the repo with the current stable version, but then switched to master to try this feature.

Initially I was looking for a report to see which files have changed since the last run, but that seems to be difficult (IIRC it can only be done based on some cache?!).

**Comment by blueyed** [comment]
@ThomasWaldmann 
Confirmed.  Thanks!
