### ISSUE TITLE
usable error message for repo permission errors

### ISSUE THREAD

**Issue by lightonflux** [borgbackup/borg#1617]
Dear borg collective,

when i tried to make a backup to remote with a newly create repository it got an error message that was not as helpful as i expected. 

The error i got was:

```
Remote: Borg 1.0.7: exception in RPC call:
Remote: Traceback (most recent call last):
Remote: File "borg/remote.py", line 98, in serve
Remote: File "borg/remote.py", line 136, in open
Remote: File "borg/repository.py", line 82, in __enter__
Remote: File "borg/repository.py", line 178, in open
Remote: borg.repository.Repository.InvalidRepository: /home/borg/repos/client
    […]
('Remote Exception (see remote log for the traceback)', 'InvalidRepository')
```

Which is not a very helpful error, as the repository is valid and can be used by borg just fine. So after some time of guessing i found out that i accidentally created the repository with the wrong user.

It would be helpful if borg throws a permission error just like `ls` and other tools.

```
ls: cannot open directory '/tmp/test': Permission denied
```

Here the structure:

```
test
├── [-rw-------]  config
├── [drwx------]  data
│   └── [drwx------]  0
│       └── [-rw-------]  0
├── [-rw-------]  hints.0
├── [-rw-------]  index.0
└── [-rw-------]  README
```

**Comment by ThomasWaldmann** [comment]
Tried to reproduce this:
```
$ borg init rights
$ sudo chown -R root.root rights
$ borg create rights::1 borg
Failed to create/acquire the lock /home/tw/w/borg/rights/lock.exclusive ([Errno 13] Permission denied: '/home/tw/w/borg/rights/lock.exclusive').
Traceback (most recent call last):
  File "/home/tw/w/borg/borg/archiver.py", line 1928, in main
    exit_code = archiver.run(args)
  File "/home/tw/w/borg/borg/archiver.py", line 1873, in run
    return args.func(args)
  File "/home/tw/w/borg/borg/archiver.py", line 79, in wrapper
    with repository:
  File "/home/tw/w/borg/borg/repository.py", line 82, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/home/tw/w/borg/borg/repository.py", line 171, in open
    self.lock = Lock(os.path.join(path, 'lock'), exclusive, timeout=lock_wait).acquire()
  File "/home/tw/w/borg/borg/locking.py", line 265, in acquire
    self._wait_for_readers_finishing(remove, sleep)
  File "/home/tw/w/borg/borg/locking.py", line 278, in _wait_for_readers_finishing
    self._lock.acquire()
  File "/home/tw/w/borg/borg/locking.py", line 143, in acquire
    raise LockFailed(self.path, str(err)) from None
borg.locking.LockFailed: ('/home/tw/w/borg/rights/lock.exclusive', "[Errno 13] Permission denied: '/home/tw/w/borg/rights/lock.exclusive'")

Platform: Linux tux 4.7.9-tw2 #5 SMP Fri Oct 21 06:05:38 CEST 2016 x86_64 x86_64
Linux: Ubuntu 16.04 xenial
Borg: 1.0.9.dev6+nge38e416  Python: CPython 3.5.1+
PID: 17129  CWD: /home/tw/w/borg
sys.argv: ['/home/tw/w/borg-env/bin/borg', 'create', 'rights::1', 'borg']
SSH_ORIGINAL_COMMAND: None
```

So, while this is rather verbose, it clearly says "permission denied".

The verbosity might be a bit annoying sometimes, but it can help borg developers debugging less simple issues.

**Comment by ThomasWaldmann** [comment]
see #1973.
