### ISSUE TITLE
borg crashes in narrow terminal

### ISSUE THREAD

**Issue by lightonflux** [borgbackup/borg#1628]
System info:

 * Debian 7
 * Borg 1.0.7
 * tmux 1.9.6

## How to reproduce (hopefully):

 1. Open tmux
 1. open 4 panes (`ctrl+b` then `shift + 2` opens new pane)
 1. make sure your terminal windows is not too big, font size 13 in a window circa 1202x739px is perfect
 1. start `borg create -v --list`
 1. change tmux layout with `ctrl+b` then `space`
 1. do that several times so you get the the narrow-st view
 1. hope that borg crashes

## Traceback

	423.63 GB O 113.70 GB C 80.11 GB D 8393152 N vps_...4ac52ne3
	Traceback (most recent call last):
	  File "borg/archiver.py", line 1684, in main
	  File "borg/archiver.py", line 1621, in run
	  File "borg/archiver.py", line 85, in wrapper
	  File "borg/archiver.py", line 249, in do_create
	  File "borg/archiver.py", line 223, in create_inner
	  File "borg/archiver.py", line 303, in _process
	  File "borg/archiver.py", line 303, in _process
	  File "borg/archiver.py", line 303, in _process
	  File "borg/archiver.py", line 303, in _process
	  File "borg/archiver.py", line 303, in _process
	  File "borg/archiver.py", line 303, in _process
	  File "borg/archiver.py", line 303, in _process
	  File "borg/archiver.py", line 303, in _process
	  File "borg/archiver.py", line 303, in _process
	  File "borg/archiver.py", line 277, in _process
	  File "borg/archive.py", line 647, in process_file
	  File "borg/archive.py", line 287, in add_item
	  File "borg/helpers.py", line 228, in show_progress
	ValueError: Sign not allowed in string format specifier

	Platform: Linux atlas 3.14-0.bpo.1-amd64 #1 SMP Debian 3.14.12-1~bpo70+1 (2014-07-13) x86_64 
	Linux: debian 7.11 
	Borg: 1.0.7  Python: CPython 3.5.2
	PID: 7017  CWD: /root
	sys.argv: ['borg', 'create', '-vpsC', 'lz4', '/mnt/nas-03/borgbackup/::{now:%Y-%m-%d}-vps', '/vps', '--exclude=*[cC]ache*']
	SSH_ORIGINAL_COMMAND: None

**Comment by ThomasWaldmann** [comment]
Fixed. Was because {space} could get negative for narrow screens.
