### ISSUE TITLE
ObjectNotFound on delete (repo had recreates and one cache clean)

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [borgbackup/borg#1658]
```
$ borg delete borg::home-ronny-pc-2016-05-07T15:02:35+0200 --progress
Object with key ed09942013aca9bccee00f207335245795f70152bd09ce0b5eb656fe6e6988b4 not found in repository /run/media/ronny/backups/borg.
Traceback (most recent call last):
  File "/nix/store/2v84q6cxzgscwsr1hzjcjmaxyixm3x6c-borgbackup-1.0.7/lib/python3.4/site-packages/borg/archiver.py", line 2675, in main
    exit_code = archiver.run(args)
  File "/nix/store/2v84q6cxzgscwsr1hzjcjmaxyixm3x6c-borgbackup-1.0.7/lib/python3.4/site-packages/borg/archiver.py", line 2612, in run
    return args.func(args)
  File "/nix/store/2v84q6cxzgscwsr1hzjcjmaxyixm3x6c-borgbackup-1.0.7/lib/python3.4/site-packages/borg/archiver.py", line 99, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/nix/store/2v84q6cxzgscwsr1hzjcjmaxyixm3x6c-borgbackup-1.0.7/lib/python3.4/site-packages/borg/archiver.py", line 774, in do_delete
    with Cache(repository, key, manifest, lock_wait=self.lock_wait) as cache:
  File "/nix/store/2v84q6cxzgscwsr1hzjcjmaxyixm3x6c-borgbackup-1.0.7/lib/python3.4/site-packages/borg/cache.py", line 103, in __init__
    self.sync()
  File "/nix/store/2v84q6cxzgscwsr1hzjcjmaxyixm3x6c-borgbackup-1.0.7/lib/python3.4/site-packages/borg/cache.py", line 382, in sync
    self.chunks = create_master_idx(self.chunks)
  File "/nix/store/2v84q6cxzgscwsr1hzjcjmaxyixm3x6c-borgbackup-1.0.7/lib/python3.4/site-packages/borg/cache.py", line 349, in create_master_idx
    archive_chunk_idx = fetch_and_build_idx(archive_id, repository, self.key)
  File "/nix/store/2v84q6cxzgscwsr1hzjcjmaxyixm3x6c-borgbackup-1.0.7/lib/python3.4/site-packages/borg/cache.py", line 301, in fetch_and_build_idx
    for item_id, chunk in zip(archive.items, repository.get_many(archive.items)):
  File "/nix/store/2v84q6cxzgscwsr1hzjcjmaxyixm3x6c-borgbackup-1.0.7/lib/python3.4/site-packages/borg/remote.py", line 546, in get_many
    for data in self.repository.get_many(keys):
  File "/nix/store/2v84q6cxzgscwsr1hzjcjmaxyixm3x6c-borgbackup-1.0.7/lib/python3.4/site-packages/borg/repository.py", line 768, in get_many
    yield self.get(id_)
  File "/nix/store/2v84q6cxzgscwsr1hzjcjmaxyixm3x6c-borgbackup-1.0.7/lib/python3.4/site-packages/borg/repository.py", line 764, in get
    raise self.ObjectNotFound(id_, self.path) from None
borg.repository.ObjectNotFound: ('ed09942013aca9bccee00f207335245795f70152bd09ce0b5eb656fe6e6988b4', '/run/media/ronny/backups/borg')

Platform: Linux ronny-rh-work-nix 4.4.20 #1-NixOS SMP Wed Sep 7 06:32:59 UTC 2016 x86_64 
Linux:   
Borg: 1.1+git  Python: CPython 3.4.5
PID: 31558  CWD: /run/media/ronny/backups
sys.argv: ['borg', 'delete', 'borg::home-ronny-pc-2016-05-07T15:02:35+0200', '--progress']
SSH_ORIGINAL_COMMAND: None
```

borg revision is 62bec8ab1c08abeacaa537020433c2aa08dfab78

**Comment by ThomasWaldmann** [comment]
Well, looks like a archive items metadata stream repo object is missing and it stumbled over it when resyncing the chunks cache.

Hmm, why does the borg revision just say 1.1+git without a revision hash?

**Comment by RonnyPfannschmidt** [comment]
im installing using nix fetch from github

**Comment by ThomasWaldmann** [comment]
maybe #1598?

**Comment by enkore** [comment]
No

**Comment by enkore** [comment]
*bump*

**Comment by ThomasWaldmann** [comment]
@ronny see enkore's unanswered question. Maybe still in .bash_history or so?

**Comment by RonnyPfannschmidt** [comment]
No longer in.history, i used multiple recreates with filters, it crashed multiple times and i removed all borg Caches once

**Comment by ThomasWaldmann** [comment]
As the recreate code is just getting major changes, shall we close this and re-test with 1.1.0b3 when it is out?

**Comment by ThomasWaldmann** [comment]
I started trying to reproduce:
- copied bigger production repo to usb3 disk
- borg check --repository-only
- borg recreate (changed compression) on some archives
- borg delete on bigger number of archives
- borg prune, reducing the whole repo to ~ 10 archives
- borg check (complete, archives too)
- borg recreate with --exclude on a bigger directory
- borg check (complete, archives too)
...

**Comment by RonnyPfannschmidt** [comment]
the issue happened again even after the #1598 fix - i believe the key part is about rechunking (a few of my backups predate the new chunker params, i created them with old chunking and recreated them with new chunking including recompression

**Comment by enkore** [comment]
Was the trace different?

I would expect that the above trace - where an item of the metadata stream is absent from the repository during the cache sync, which isn't specific to deletion, - was fixed by removing all that complex interruption logic which handled these parts. Archive meta items are now only handled by regular Archive.add_item.

**Comment by RonnyPfannschmidt** [comment]
will recheck when i get that repo

**Comment by ThomasWaldmann** [comment]
i did some practical testing on a small ~1GB repo: create, delete, recreate (changing compression, chunker params, excluding files), check, extract --dry-run.

No problems encountered.

@RonnyPfannschmidt close? or do you want to do another test?

**Comment by RonnyPfannschmidt** [comment]
ID like to retest in my wn repo which exhibited the issue

**Comment by ThomasWaldmann** [comment]
OK, then please do ASAP, we want to release 1.1.0b3 soon.

**Comment by RonnyPfannschmidt** [comment]
check without cache clear completed, now checking with cache cleared before

**Comment by RonnyPfannschmidt** [comment]
@ThomasWaldmann everything is fine now
@enkore thanks for the hard work
