### ISSUE TITLE
NFS I/O error in borg delete

### ISSUE THREAD

**Issue by jbe-x** [borgbackup/borg#1816]
I have a pretty big Repo (about 6TB) and deleting an archive gives me the following error:

```
Local Exception.
Traceback (most recent call last):
  File "borg/archiver.py", line 1928, in main
  File "borg/archiver.py", line 1873, in run
  File "borg/archiver.py", line 87, in wrapper
  File "borg/archiver.py", line 483, in do_delete
  File "borg/repository.py", line 200, in commit
  File "borg/repository.py", line 355, in compact_segments
  File "borg/repository.py", line 293, in complete_xfer
  File "borg/repository.py", line 686, in delete_segment
OSError: [Errno 5] Input/output error: '/storage/ahsay.borg/data/102/1028029'

Platform: Linux cen-ah-rep 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 
Linux: debian 8.6 
Borg: 1.0.8  Python: CPython 3.5.2
PID: 4204  CWD: /home/centaur
sys.argv: ['borg', 'delete', '/storage/ahsay.borg::ahsay-2016-10-28T04:00:07+0200']
SSH_ORIGINAL_COMMAND: None
```
The Archive seems to be deleted as it will not show up on borg list and some storage is freed.
The Storage is mounted via NFS3 with soft option.
I did a borg check of the full repository and it did get through clean.
Could this mean there are still some orphaned files around?

**Comment by enkore** [comment]
Does `dmesg` / logs on the machine with the NFS mount, or on the machine exporting it, say something about this?

**Comment by ThomasWaldmann** [comment]
no feedback (and likely not a borg issue anyway).
