### ISSUE TITLE
"fread buckets failed (expected $FOO, got $BAR) (Input/output error)"

### ISSUE THREAD

**Issue by bjornfor** [borgbackup/borg#1861]
I run borg backup every night (```borg create && borg prune && borg check```). Last night this error happened and seemingly broke the whole repository (I cannot run ```borg list``` anymore):

```
[...]
bkup[2375]: A /var/www/munin/mini/mini/df_abs.html
bkup[2375]: A /var/www/munin/mini/mini/df_inode-day.png
bkup[2375]: A /var/www/munin/mini/mini/df_inode-month.png
bkup[2375]: hashindex: /mnt/backup-disk/backups/backup.borg/index.386315: fread buckets failed (expected 1107826120, got 285204462) (Input/output error)
bkup[2375]: Local Exception.
bkup[2375]: Traceback (most recent call last):
bkup[2375]:   File "/nix/store/0cdnjh3h8r4xpslqf0hkzg75ai41kdkx-borgbackup-1.0.8/lib/python3.4/site-packages/borg/archiver.py", line 1928, in main
bkup[2375]:     exit_code = archiver.run(args)
bkup[2375]:   File "/nix/store/0cdnjh3h8r4xpslqf0hkzg75ai41kdkx-borgbackup-1.0.8/lib/python3.4/site-packages/borg/archiver.py", line 1873, in run
bkup[2375]:     return args.func(args)
bkup[2375]:   File "/nix/store/0cdnjh3h8r4xpslqf0hkzg75ai41kdkx-borgbackup-1.0.8/lib/python3.4/site-packages/borg/archiver.py", line 87, in wrapper
bkup[2375]:     return method(self, args, repository=repository, **kwargs)
bkup[2375]:   File "/nix/store/0cdnjh3h8r4xpslqf0hkzg75ai41kdkx-borgbackup-1.0.8/lib/python3.4/site-packages/borg/archiver.py", line 285, in do_create
bkup[2375]:     create_inner(archive, cache)
bkup[2375]:   File "/nix/store/0cdnjh3h8r4xpslqf0hkzg75ai41kdkx-borgbackup-1.0.8/lib/python3.4/site-packages/borg/archiver.py", line 259, in create_inner
bkup[2375]:     read_special=args.read_special, dry_run=dry_run)
bkup[2375]:   File "/nix/store/0cdnjh3h8r4xpslqf0hkzg75ai41kdkx-borgbackup-1.0.8/lib/python3.4/site-packages/borg/archiver.py", line 339, in _process
bkup[2375]:     read_special=read_special, dry_run=dry_run)
bkup[2375]:   File "/nix/store/0cdnjh3h8r4xpslqf0hkzg75ai41kdkx-borgbackup-1.0.8/lib/python3.4/site-packages/borg/archiver.py", line 339, in _process
bkup[2375]:     read_special=read_special, dry_run=dry_run)
bkup[2375]:   File "/nix/store/0cdnjh3h8r4xpslqf0hkzg75ai41kdkx-borgbackup-1.0.8/lib/python3.4/site-packages/borg/archiver.py", line 339, in _process
bkup[2375]:     read_special=read_special, dry_run=dry_run)
bkup[2375]:   File "/nix/store/0cdnjh3h8r4xpslqf0hkzg75ai41kdkx-borgbackup-1.0.8/lib/python3.4/site-packages/borg/archiver.py", line 339, in _process
bkup[2375]:     read_special=read_special, dry_run=dry_run)
bkup[2375]:   File "/nix/store/0cdnjh3h8r4xpslqf0hkzg75ai41kdkx-borgbackup-1.0.8/lib/python3.4/site-packages/borg/archiver.py", line 339, in _process
bkup[2375]:     read_special=read_special, dry_run=dry_run)
bkup[2375]:   File "/nix/store/0cdnjh3h8r4xpslqf0hkzg75ai41kdkx-borgbackup-1.0.8/lib/python3.4/site-packages/borg/archiver.py", line 339, in _process
bkup[2375]:     read_special=read_special, dry_run=dry_run)
bkup[2375]:   File "/nix/store/0cdnjh3h8r4xpslqf0hkzg75ai41kdkx-borgbackup-1.0.8/lib/python3.4/site-packages/borg/archiver.py", line 339, in _process
bkup[2375]:     read_special=read_special, dry_run=dry_run)
bkup[2375]:   File "/nix/store/0cdnjh3h8r4xpslqf0hkzg75ai41kdkx-borgbackup-1.0.8/lib/python3.4/site-packages/borg/archiver.py", line 339, in _process
bkup[2375]:     read_special=read_special, dry_run=dry_run)
bkup[2375]:   File "/nix/store/0cdnjh3h8r4xpslqf0hkzg75ai41kdkx-borgbackup-1.0.8/lib/python3.4/site-packages/borg/archiver.py", line 339, in _process
bkup[2375]:     read_special=read_special, dry_run=dry_run)
bkup[2375]:   File "/nix/store/0cdnjh3h8r4xpslqf0hkzg75ai41kdkx-borgbackup-1.0.8/lib/python3.4/site-packages/borg/archiver.py", line 339, in _process
bkup[2375]:     read_special=read_special, dry_run=dry_run)
bkup[2375]:   File "/nix/store/0cdnjh3h8r4xpslqf0hkzg75ai41kdkx-borgbackup-1.0.8/lib/python3.4/site-packages/borg/archiver.py", line 339, in _process
bkup[2375]:     read_special=read_special, dry_run=dry_run)
bkup[2375]:   File "/nix/store/0cdnjh3h8r4xpslqf0hkzg75ai41kdkx-borgbackup-1.0.8/lib/python3.4/site-packages/borg/archiver.py", line 313, in _process
bkup[2375]:     status = archive.process_file(path, st, cache, self.ignore_inode)
bkup[2375]:   File "/nix/store/0cdnjh3h8r4xpslqf0hkzg75ai41kdkx-borgbackup-1.0.8/lib/python3.4/site-packages/borg/archive.py", line 698, in process_file
bkup[2375]:     self.add_item(item)
bkup[2375]:   File "/nix/store/0cdnjh3h8r4xpslqf0hkzg75ai41kdkx-borgbackup-1.0.8/lib/python3.4/site-packages/borg/archive.py", line 289, in add_item
bkup[2375]:     self.write_checkpoint()
bkup[2375]:   File "/nix/store/0cdnjh3h8r4xpslqf0hkzg75ai41kdkx-borgbackup-1.0.8/lib/python3.4/site-packages/borg/archive.py", line 295, in write_checkpoint
bkup[2375]:     self.cache.chunk_decref(self.id, self.stats)
bkup[2375]:   File "/nix/store/0cdnjh3h8r4xpslqf0hkzg75ai41kdkx-borgbackup-1.0.8/lib/python3.4/site-packages/borg/cache.py", line 425, in chunk_decref
bkup[2375]:     self.repository.delete(id, wait=False)
bkup[2375]:   File "/nix/store/0cdnjh3h8r4xpslqf0hkzg75ai41kdkx-borgbackup-1.0.8/lib/python3.4/site-packages/borg/repository.py", line 542, in delete
bkup[2375]:     self.prepare_txn(self.get_transaction_id())
bkup[2375]:   File "/nix/store/0cdnjh3h8r4xpslqf0hkzg75ai41kdkx-borgbackup-1.0.8/lib/python3.4/site-packages/borg/repository.py", line 229, in prepare_txn
bkup[2375]:     self.index = self.open_index(transaction_id)
bkup[2375]:   File "/nix/store/0cdnjh3h8r4xpslqf0hkzg75ai41kdkx-borgbackup-1.0.8/lib/python3.4/site-packages/borg/repository.py", line 207, in open_index
bkup[2375]:     return NSIndex.read((os.path.join(self.path, 'index.%d') % transaction_id).encode('utf-8'))
bkup[2375]:   File "borg/hashindex.pyx", line 79, in borg.hashindex.IndexBase.read (borg/hashindex.c:1376)
bkup[2375]:   File "borg/hashindex.pyx", line 67, in borg.hashindex.IndexBase.__cinit__ (borg/hashindex.c:1179)
bkup[2375]: Exception: hashindex_read failed
bkup[2375]: Platform: Linux mini 4.4.31 #1-NixOS SMP Thu Nov 10 15:37:00 UTC 2016 x86_64
bkup[2375]: Linux:
bkup[2375]: Borg: 1.0.8  Python: CPython 3.4.5
bkup[2375]: PID: 2378  CWD: /
bkup[2375]: sys.argv: ['borg', 'create', '--stats', '--verbose', '--list', '--filter', 'AME', '--show-rc', '--one-file-system', '--exclude-caches', '--exclude', '/nix/', '--exclude', '/tmp/', '--exclude', '/var/tmp/', '--exclude', '/home/*/.cache/', '--exclude', '/home/*/.thumbnails/', '--exclude', '/home/*/.nox/', '--exclude', '*/.Trash*/', '--compression', 'lz4', '/mnt/backup-disk/backups/backup.borg::{hostname}-20161119T051517', '/', '/mnt/data']
bkup[2375]: SSH_ORIGINAL_COMMAND: None
bkup[2375]: terminating with error status, rc 2
```

My disk(s) are not full and I haven't noticed any other issue on my system.

Is this a borg bug or can it be (silent) data corruption on my disk? I use ext4.

I'm running ```borg check``` now, and plan to run ```borg check --repair``` after that to see if borg can fix it. (It takes several hours to check/repair my 1 TB repo.)

**Comment by enkore** [comment]
If borg check --repair fixes it and has no other complains then it would suggest that only this particular file was corrupted (length field) or truncated; since this is only an index borg-check will restore it from the actual data in the repo.

Take a look at the output of `smartctl -x /dev/sdYourDrive`, perhaps dmesg/journalctl if it logged write or read errors. Since the OS returns EIO it should log *something*.

**Comment by bjornfor** [comment]
Ah, right. I *was* a disk issue. Some journal output from the same timespan:

```
nov. 19 05:21:27 mini kernel: ata4.00: exception Emask 0x0 SAct 0x78000000 SErr 0x0 action 0x0
nov. 19 05:21:27 mini kernel: ata4.00: irq_stat 0x40000008
nov. 19 05:21:27 mini kernel: ata4.00: failed command: READ FPDMA QUEUED
nov. 19 05:21:27 mini kernel: ata4.00: cmd 60/20:d8:e0:c7:62/00:00:8d:00:00/40 tag 27 ncq 16384 in
                                       res 41/40:00:f0:c7:62/00:00:8d:00:00/40 Emask 0x409 (media error) <F>
nov. 19 05:21:27 mini kernel: ata4.00: status: { DRDY ERR }
nov. 19 05:21:27 mini kernel: ata4.00: error: { UNC }
nov. 19 05:21:27 mini kernel: ata4.00: configured for UDMA/133
nov. 19 05:21:27 mini kernel: sd 3:0:0:0: [sdc] tag#27 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
nov. 19 05:21:27 mini kernel: sd 3:0:0:0: [sdc] tag#27 Sense Key : Medium Error [current] [descriptor] 
nov. 19 05:21:27 mini kernel: sd 3:0:0:0: [sdc] tag#27 Add. Sense: Unrecovered read error - auto reallocate failed
nov. 19 05:21:27 mini kernel: sd 3:0:0:0: [sdc] tag#27 CDB: Read(16) 88 00 00 00 00 00 8d 62 c7 e0 00 00 00 20 00 00
nov. 19 05:21:27 mini kernel: blk_update_request: I/O error, dev sdc, sector 2372061168
nov. 19 05:21:27 mini kernel: ata4: EH complete
nov. 19 05:21:30 mini kernel: ata4.00: exception Emask 0x0 SAct 0x400000 SErr 0x0 action 0x0
nov. 19 05:21:30 mini kernel: ata4.00: irq_stat 0x40000008
nov. 19 05:21:30 mini kernel: ata4.00: failed command: READ FPDMA QUEUED
nov. 19 05:21:30 mini kernel: ata4.00: cmd 60/08:b0:f0:c7:62/00:00:8d:00:00/40 tag 22 ncq 4096 in
                                       res 41/40:00:f0:c7:62/00:00:8d:00:00/40 Emask 0x409 (media error) <F>
nov. 19 05:21:30 mini kernel: ata4.00: status: { DRDY ERR }
nov. 19 05:21:30 mini kernel: ata4.00: error: { UNC }
```

And SMART data indicates the disk has one bad sector now. (@enkore: Sorry for doing bad detective work and thanks a lot for helping me.)

**Comment by ThomasWaldmann** [comment]
if you don't discard the drive anyway, do a `smartctl -t long /dev/sdX` and look at the test result after it completed (usually: some hours later) with `smartctl -a /dev/sdX`.

**Comment by bjornfor** [comment]
```borg check --repair``` did fix the repo, although it didn't say _what_ it fixed (or how):

```
$ time sudo borg check -v --show-rc --repair /mnt/backup-disk/backups/backup.borg/
'check --repair' is an experimental feature that might result in data loss.
Type 'YES' if you understand this and want to continue: YES
Starting repository check
hashindex: /mnt/backup-disk/backups/backup.borg/index.386315: fread buckets failed (expected 1107826120, got 285204462) (Input/output error)
Completed repository check, no problems found.
Starting archive consistency check...
Analyzing archive mini-20161119T051517.checkpoint (19/19)
Analyzing archive mini-20161118T051517 (18/19)
[...]
Analyzing archive mini-20160430T051503 (2/19)
Analyzing archive mini-20160331T051514 (1/19)
Archive consistency check complete, no problems found.
terminating with success status, rc 0

real	268m47.270s
user	59m44.891s
sys	8m59.374s
```

The next ```borg check --repair``` didn't have that "fread buckets failed" message, and I can ```borg list``` now, so apparently it did fix the repo.

Running the long disk test with ```sudo smartctl -t long /dev/sdc``` didn't seem to fix the bad sector:

```
$ sudo smartctl -a /dev/sdc | grep "Reallocated\|Pending"
  5 Reallocated_Sector_Ct   0x0033   200   200   140    Pre-fail  Always       -       0
196 Reallocated_Event_Count 0x0032   200   200   000    Old_age   Always       -       0
197 Current_Pending_Sector  0x0032   200   200   000    Old_age   Always       -       1
```

Oh well, the disk has been running for 31926 hours (~3.5 years), so I cannot blame it for dying now :-)

**Comment by enkore** [comment]
Current_Pending_Sector only gets fixed when the same LBA is written to again; Borg transaction semantics make that ~~unlikely~~ impossible in this instance. However, the failed LBA isn't mapped to a file anymore, so it should eventually vanish.
