### ISSUE TITLE
`borg debug` call fails due to missing logger setup

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [borgbackup/borg#1932]
```
[nix-shell:/run/media/ronny/backups/borg_test/borg_recreate_repair_test]$ borg debug
Traceback (most recent call last):
  File "/run/user/1000/tmp.53SX7QRY7s/bin/borg", line 11, in <module>
    load_entry_point('borgbackup', 'console_scripts', 'borg')()
  File "/home/ronny/Projects/borgbackup/borg/src/borg/archiver.py", line 2800, in main
    logger.error(msg)
  File "/home/ronny/Projects/borgbackup/borg/src/borg/logger.py", line 178, in error
    return self.__logger.error(*args, **kw)
  File "/home/ronny/Projects/borgbackup/borg/src/borg/logger.py", line 150, in __logger
    raise Exception("tried to call a logger before setup_logging() was called")
Exception: tried to call a logger before setup_logging() was called

[nix-shell:/run/media/ronny/backups/borg_test/borg_recreate_repair_test]$ borg --version
borg 1.1.0.dev76+ng7e5ed40
```

**Comment by ThomasWaldmann** [comment]
fixed by #1953.
