### ISSUE TITLE
Generic error message when trying to use non-upgraded attic repository

### ISSUE THREAD

**Issue by slavkoja** [borgbackup/borg#1933]
Hi,

while playing with borg (as attic user) i accidentally run borg commands on attic*s repository and i get ugly trackback:
```
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/borg/archiver.py", line 1928, in main
    exit_code = archiver.run(args)
  File "/usr/lib64/python3.4/site-packages/borg/archiver.py", line 1873, in run
    return args.func(args)
  File "/usr/lib64/python3.4/site-packages/borg/archiver.py", line 81, in wrapper
    kwargs['manifest'], kwargs['key'] = Manifest.load(repository)
  File "/usr/lib64/python3.4/site-packages/borg/helpers.py", line 113, in load
    cdata = repository.get(cls.MANIFEST_ID)
  File "/usr/lib64/python3.4/site-packages/borg/repository.py", line 512, in get
    self.index = self.open_index(self.get_transaction_id())
  File "/usr/lib64/python3.4/site-packages/borg/repository.py", line 152, in get_transaction_id
    raise self.CheckNeeded(self.path)
borg.repository.CheckNeeded: /srv/backup/system.borg
```
IMO, this exception have to be catched and only error message needs to be reported, to get more better look ;-)

---

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/39795380-generic-error-message-when-trying-to-use-non-upgraded-attic-repository)

**Comment by infectormp** [comment]
@slavkoja please provide more info: command that you run, borg version and etc.

**Comment by slavkoja** [comment]
Perhaps i was not clear, it is expected error, as i mentioned i forget to convert attic repo before ;-) I complain only for catching it. For now i get:
```python
borg list /srv/backup/projekty.attic/
Inconsistency detected. Please run "borg check /srv/backup/projekty.attic".
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/borg/archiver.py", line 1928, in main
    exit_code = archiver.run(args)
  File "/usr/lib64/python3.4/site-packages/borg/archiver.py", line 1873, in run
    return args.func(args)
  File "/usr/lib64/python3.4/site-packages/borg/archiver.py", line 81, in wrapper
    kwargs['manifest'], kwargs['key'] = Manifest.load(repository)
  File "/usr/lib64/python3.4/site-packages/borg/helpers.py", line 113, in load
    cdata = repository.get(cls.MANIFEST_ID)
  File "/usr/lib64/python3.4/site-packages/borg/repository.py", line 512, in get
    self.index = self.open_index(self.get_transaction_id())
  File "/usr/lib64/python3.4/site-packages/borg/repository.py", line 152, in get_transaction_id
    raise self.CheckNeeded(self.path)
borg.repository.CheckNeeded: /srv/backup/projekty.attic
```
And i expect to get only:
```
borg list /srv/backup/projekty.attic/
Inconsistency detected. Please run "borg check /srv/backup/projekty.attic".
```

**Comment by slavkoja** [comment]
I forgot to mention:
```
borg --version
borg 1.0.8
```

**Comment by ThomasWaldmann** [comment]
Yeah, this special case maybe could be more pretty. An attic repo looks quite similar as a borg one, but has other magics, so it is not a valid borg repo. One needs to run "borg upgrade" on it to transform it into a valid borg repo.

But in general we try to have informative exception tracebacks (even if a bit ugly sometimes) rather than "pretty", but uninformative / unhelpful error messages.

**Comment by slavkoja** [comment]
It is OK to provide full information in library/module. Perhaps full trackback in debug mode can be good idea, but in application self (i.e. borg itself) all known exceptions have to ne catched. 

It is not very straightforward, when to get --stats output i need to raise loglevel, but i get debug information in default one.

**Comment by ThomasWaldmann** [comment]
moved to 1.1 due to new 1.0 policy.

**Comment by ThomasWaldmann** [comment]
@lfos claim the bounty! :)
