### ISSUE TITLE
Error messages instead of tracebacks

### ISSUE THREAD

**Issue by ddeimeke** [borgbackup/borg#1973]
No issues with having tracebacks.

Wouldn't it be better for endusers to have a proper error message instead of a Python traceback?

**Comment by infectormp** [comment]
A very detailed bug report

**Comment by enkore** [comment]
Generally speaking, we want error messages when we are sure, and rather dump a traceback if we aren't sure about the error cause.

There are many instances where a TB could be replaced with an error message. If you have specific instances in mind, don't hesitate to post them (otherwise this isn't a very helpful report).

**Comment by ddeimeke** [comment]
It is a general question. I agree with your point of view that a traceback should be raised, if the error cause is not known. In my opinion this should be the only reason for tracebacks.

Examples:

Please check that the last line "see remote log for the traceback" shows a way to handle it. Traceback should go to the log, error message for the user.

```
Remote: Borg 1.0.8: exception in RPC call:
Remote: Traceback (most recent call last):
Remote:   File "/usr/lib64/python3.4/site-packages/borg/remote.py", line 113, in serve
Remote:     res = f(*args)
Remote:   File "/usr/lib64/python3.4/site-packages/borg/remote.py", line 153, in open
Remote:     self.repository.__enter__()  # clean exit handled by serve() method
Remote:   File "/usr/lib64/python3.4/site-packages/borg/repository.py", line 82, in __enter__
Remote:     self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
Remote:   File "/usr/lib64/python3.4/site-packages/borg/repository.py", line 171, in open
Remote:     self.lock = Lock(os.path.join(path, 'lock'), exclusive, timeout=lock_wait).acquire()
Remote:   File "/usr/lib64/python3.4/site-packages/borg/locking.py", line 265, in acquire
Remote:     self._wait_for_readers_finishing(remove, sleep)
Remote:   File "/usr/lib64/python3.4/site-packages/borg/locking.py", line 282, in _wait_for_readers_finishing
Remote:     if len(self._roster.get(SHARED)) == 0:
Remote:   File "/usr/lib64/python3.4/site-packages/borg/locking.py", line 201, in get
Remote:     roster = self.load()
Remote:   File "/usr/lib64/python3.4/site-packages/borg/locking.py", line 183, in load
Remote:     with open(self.path) as f:
Remote: PermissionError: [Errno 13] Permission denied: '/srv/borg/lenim/lock.roster'
Remote: Platform: Linux len.mhochzwei.net 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64
Remote: Linux: CentOS Linux 7.3.1611 Core
Remote: Borg: 1.0.8  Python: CPython 3.4.5
Remote: PID: 23049  CWD: /srv/backup
Remote: sys.argv: ['/usr/bin/borg', 'serve', '--umask=077']
Remote: SSH_ORIGINAL_COMMAND: None
Remote:
('Remote Exception (see remote log for the traceback)', 'PermissionError')
```

or

```
Remote: Borg 1.0.8: exception in RPC call:
Remote: Traceback (most recent call last):
Remote:   File "/usr/lib64/python3.4/site-packages/borg/locking.py", line 136, in acquire
Remote:     os.mkdir(self.path)
Remote: FileExistsError: [Errno 17] File exists: '/srv/borg/tiga/lock.exclusive'
Remote:
Remote: During handling of the above exception, another exception occurred:
Remote:
Remote: Traceback (most recent call last):
Remote:   File "/usr/lib64/python3.4/site-packages/borg/remote.py", line 113, in serve
Remote:     res = f(*args)
Remote:   File "/usr/lib64/python3.4/site-packages/borg/remote.py", line 153, in open
Remote:     self.repository.__enter__()  # clean exit handled by serve() method
Remote:   File "/usr/lib64/python3.4/site-packages/borg/repository.py", line 82, in __enter__
Remote:     self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
Remote:   File "/usr/lib64/python3.4/site-packages/borg/repository.py", line 171, in open
Remote:     self.lock = Lock(os.path.join(path, 'lock'), exclusive, timeout=lock_wait).acquire()
Remote:   File "/usr/lib64/python3.4/site-packages/borg/locking.py", line 268, in acquire
Remote:     with self._lock:
Remote:   File "/usr/lib64/python3.4/site-packages/borg/locking.py", line 120, in __enter__
Remote:     return self.acquire()
Remote:   File "/usr/lib64/python3.4/site-packages/borg/locking.py", line 141, in acquire
Remote:     raise LockTimeout(self.path)
Remote: borg.locking.LockTimeout: /srv/borg/tiga/lock.exclusive
Remote: Platform: Linux len.mhochzwei.net 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64
Remote: Linux: CentOS Linux 7.3.1611 Core
Remote: Borg: 1.0.8  Python: CPython 3.4.5
Remote: PID: 6422  CWD: /srv/backup
Remote: sys.argv: ['/usr/bin/borg', 'serve', '--umask=077']
Remote: SSH_ORIGINAL_COMMAND: None
Remote:
('Remote Exception (see remote log for the traceback)', 'LockTimeout')
```

**Comment by rugk** [comment]
I think in case of the lock error (when lock.exclusive exists) you can surely just use "usual" error messages. I mean this error is well-known and does not need a traceback.

**Comment by ThomasWaldmann** [comment]
The current policy in borg is:

- if the cause of an exception is well-known and somehow expected, we use `Error` or a subclass of it and then borg produces a nice error message without a traceback.
- if that is not the case, we rather throw a full traceback - it can be useful for debugging and finding issues.
