### ISSUE TITLE
Error: "The 'borgbackup==1.0.9' distribution was not found and is required by the application"

### ISSUE THREAD

**Issue by busbauen** [borgbackup/borg#1998]
Hey,
my borg doesn't work anymore since I updated my arch this morning. Can you give me some advice?

root@pc> uname -a
Linux pc 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux
root@pc> pacman -Q borg
borg 1.0.9-2
root@pc> borg
Traceback (most recent call last):
  File "/usr/bin/borg", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'borgbackup==1.0.9' distribution was not found and is required by the application

Thank you!

**Comment by enkore** [comment]
Forgot to update python as well? The arch linux pkg 1.0.9-2 is built for Python 3.6

**Comment by busbauen** [comment]
urgh.I commented out the testing repo in pacman.conf..
Thank you for helping fixing it.
