### ISSUE TITLE
undefined symbol: EVP_aes_256_ctr

### ISSUE THREAD

**Issue by smaty1** [borgbackup/borg#2029]
Traceback (most recent call last):
  File "/home/work/.jumbo/bin/borg", line 11, in <module>
    load_entry_point('borgbackup==1.0.9', 'console_scripts', 'borg')()
  File "/home/work/.jumbo/lib/python3.4/site-packages/setuptools-33.0.0.post20170111-py3.4.egg/pkg_resources/__init__.py", line 561, in load_entry_point
  File "/home/work/.jumbo/lib/python3.4/site-packages/setuptools-33.0.0.post20170111-py3.4.egg/pkg_resources/__init__.py", line 2631, in load_entry_point
  File "/home/work/.jumbo/lib/python3.4/site-packages/setuptools-33.0.0.post20170111-py3.4.egg/pkg_resources/__init__.py", line 2291, in load
  File "/home/work/.jumbo/lib/python3.4/site-packages/setuptools-33.0.0.post20170111-py3.4.egg/pkg_resources/__init__.py", line 2297, in resolve
  File "/home/work/.jumbo/lib/python3.4/site-packages/borgbackup-1.0.9-py3.4-linux-x86_64.egg/borg/archiver.py", line 20, in <module>
    from .helpers import Error, location_validator, archivename_validator, format_line, format_time, format_file_size, \
  File "/home/work/.jumbo/lib/python3.4/site-packages/borgbackup-1.0.9-py3.4-linux-x86_64.egg/borg/helpers.py", line 34, in <module>
    from . import crypto
ImportError: /home/work/.jumbo/lib/python3.4/site-packages/borgbackup-1.0.9-py3.4-linux-x86_64.egg/borg/crypto.cpython-34m.so: undefined symbol: EVP_aes_256_ctr

**Comment by infectormp** [comment]
@smaty1 what operation you perform?

**Comment by smaty1** [comment]
LSB Version:	:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	CentOS
Description:	CentOS release 6.3 (Final)
Release:	6.3
Codename:	Final
@infectormp

**Comment by enkore** [comment]
If this is a new error: Check whether OpenSSL was updated in your OS (1.0 -> 1.1), if so, you probably have to reinstall Borg.

**Comment by ThomasWaldmann** [comment]
@smaty1 your centos6 is rather old, can't you at least go to a current 6.x version?

@enkore that stuff is so old that it is more likely it has openssl < 1.0.

**Comment by ThomasWaldmann** [comment]
see also: https://github.com/jborg/attic/issues/197

**Comment by ThomasWaldmann** [comment]
I am closing this. Likely it is just the openssl on that system that is broken (or at least not compatible with the binary).

In any case, it is way too old and not supported any more anyway.

I've frequently run borg tests (borg installed from source) on centos 6 and it worked.

Quite a while ago, I even tried to create the binaries on centos 6 (for lower glibc requirements), but the binaries were strangely slow (and we could not find out why), so I am creating the binaries now on wheezy.
