### ISSUE TITLE
add pip to requirements?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2030]
Just stumbled (again) over this:
```
(borg-env)tw@tux:~/w/borg$ pip install -e .
Obtaining file:///home/tw/w/borg
  Running setup.py (path:/home/tw/w/borg/setup.py) egg_info for package from file:///home/tw/w/borg
    your setuptools is too old (<12)
    setuptools_scm functionality is degraded
    
    warning: no previously-included files matching '*.pyo' found under directory 'src'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/home/tw/w/borg-env/lib/python3.5/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/tw/w/borg-env/lib/python3.5/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/tw/w/borg-env/lib/python3.5/site-packages/pip/req.py", line 1145, in prepare_files
    req_to_install.run_egg_info()
  File "/home/tw/w/borg-env/lib/python3.5/site-packages/pip/req.py", line 330, in run_egg_info
    "%(Name)s==%(Version)s" % self.pkg_info())
  File "/home/tw/w/borg-env/lib/python3.5/site-packages/pip/_vendor/pkg_resources.py", line 2667, in parse
    reqs = list(parse_requirements(s))
  File "/home/tw/w/borg-env/lib/python3.5/site-packages/pip/_vendor/pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/home/tw/w/borg-env/lib/python3.5/site-packages/pip/_vendor/pkg_resources.py", line 2583, in scan_list
    "Expected ',' or end-of-list in",line,"at",line[p:]
ValueError: ("Expected ',' or end-of-list in", 'borgbackup==1.0.10.dev39+ng9e692d4', 'at', '+ng9e692d4')

Storing debug log for failure in /home/tw/.pip/pip.log
```

It is caused by a too old pip that was installed into the virtualenv at creation time (here: 1.5.6) and can be resolved by `pip install -U pip`.

To avoid this, we could just add `pip` to `requirements.d/development.txt`.

**Comment by ThomasWaldmann** [comment]
We could also add `setuptools` to make sure we have a current version.

Note: virtualenv is already there, so we have a current one for new virtualenvs created (e.g. by tox) while the main virtualenv is active.

**Comment by enkore** [comment]
`pip>=9`?

**Comment by ThomasWaldmann** [comment]
guess we do not need >=9, it will use the latest release anyway.

we don't need wheel currently, do we?

**Comment by ThomasWaldmann** [comment]
Don't remember any llfuse wheel version connection.
