### ISSUE TITLE
openbsd, netbsd, solaris, illumos, cygwin: platform.posix module not built, but required

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2041]
due to a linux/freebsd/darwin only platform check, the posix module is not built on netbsd.

**Comment by ThomasWaldmann** [comment]
seen on master, todo: check 1.0-maint also.

**Comment by ThomasWaldmann** [comment]
```
(borg-env) -bash-4.4$ pip install -e .
Obtaining file:///vagrant/borg/borg
Collecting msgpack-python>=0.4.6 (from borgbackup==1.0.10.dev49+ng82fd84e)
Installing collected packages: msgpack-python, borgbackup
  Running setup.py develop for borgbackup
Successfully installed borgbackup msgpack-python-0.4.8
(borg-env) -bash-4.4$ py.test
Traceback (most recent call last):
  File "/vagrant/borg/borg-env/lib/python3.4/site-packages/_pytest/config.py", line 325, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/vagrant/borg/borg')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/vagrant/borg/borg-env/lib/python3.4/site-packages/_pytest/config.py", line 362, in _importconftest
    mod = conftestpath.pyimport()
  File "/vagrant/borg/borg-env/lib/python3.4/site-packages/py/_path/local.py", line 662, in pyimport
    __import__(modname)
  File "/vagrant/borg/borg-env/lib/python3.4/site-packages/_pytest/assertion/rewrite.py", line 216, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/vagrant/borg/borg/conftest.py", line 14, in <module>
    from borg.testsuite import has_lchflags, has_llfuse
  File "/vagrant/borg/borg/src/borg/testsuite/__init__.py", line 15, in <module>
    from ..platform import get_flags, umount
  File "/vagrant/borg/borg/src/borg/platform/__init__.py", line 13, in <module>
    from .posix import process_alive, get_process_id, local_pid_alive
ImportError: No module named 'borg.platform.posix'
ERROR: could not load /vagrant/borg/borg/conftest.py
```

**Comment by ThomasWaldmann** [comment]
```
-    if sys.platform.startswith(('linux', 'freebsd', 'darwin')):
+    if sys.platform.startswith(('linux', 'freebsd', 'darwin', 'netbsd')):
         ext_modules.append(Extension('borg.platform.posix', [platform_posix_source]))
```

**Comment by enkore** [comment]
Solaris seems to have the same problem: https://golem.enkore.de/job/borg-solaris/278/console

**Comment by enkore** [comment]
Since we're importing it unconditionally the if should just go away, or we need to add an if in platform/init:

from .posix import process_alive, get_process_id, local_pid_alive

**Comment by ThomasWaldmann** [comment]
@enkore "Maybe invert the condition, if not sys.platform.startswith(('win32', 'cygwin')) (also gnu0?)."

Shouldn't cygwin behave posixish?

**Comment by enkore** [comment]
Apt description of our cygwinish issues? :)
