### ISSUE TITLE
crc32.c (cythonized crc32.pyx) is missing from pypi package

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2052]

**Comment by ThomasWaldmann** [comment]
I suspect above is the root cause of this:
```
(env-temp)tw@tux:~/w/borg-clean/dist$ pip install borgbackup-1.1.0b3.tar.gz 
Unpacking ./borgbackup-1.1.0b3.tar.gz
  Running setup.py (path:/tmp/pip-a1otsf_7-build/setup.py) egg_info for package from file:///home/tw/w/borg-clean/dist/borgbackup-1.1.0b3.tar.gz
    Traceback (most recent call last):
      File "/tmp/pip-a1otsf_7-build/setup.py", line 74, in <module>
        from Cython.Distutils import build_ext
    ImportError: No module named 'Cython'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-a1otsf_7-build/setup.py", line 118, in <module>
        raise ImportError('The GIT version of Borg needs Cython. Install Cython or use a released version.')
    ImportError: The GIT version of Borg needs Cython. Install Cython or use a released version.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "/tmp/pip-a1otsf_7-build/setup.py", line 74, in <module>

    from Cython.Distutils import build_ext

ImportError: No module named 'Cython'



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-a1otsf_7-build/setup.py", line 118, in <module>

    raise ImportError('The GIT version of Borg needs Cython. Install Cython or use a released version.')

ImportError: The GIT version of Borg needs Cython. Install Cython or use a released version.

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-a1otsf_7-build
Storing debug log for failure in /home/tw/.pip/pip.log
```

**Comment by enkore** [comment]
Hmm, but where is it missing?

https://github.com/borgbackup/borg/blob/master/setup.py#L90
https://github.com/borgbackup/borg/blob/master/setup.py#L374
https://github.com/borgbackup/borg/blob/master/setup.py#L116

**Comment by ThomasWaldmann** [comment]
In cython_sources.

**Comment by enkore** [comment]
Interesting, when I do sdist I get a .tar.gz which *also* contains the binaries *and* the pyx files.

**Comment by ThomasWaldmann** [comment]
binaries?
