### ISSUE TITLE
borg create fails with version 1.0.9

### ISSUE THREAD

**Issue by elya5** [borgbackup/borg#2077]
borg create suddenly fails with this exception:

```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.5/site-packages/borg/archiver.py", line 2052, in main
    exit_code = archiver.run(args)
  File "/home/user/.local/lib/python3.5/site-packages/borg/archiver.py", line 1997, in run
    return func(args)
  File "/home/user/.local/lib/python3.5/site-packages/borg/archiver.py", line 90, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/borg/archiver.py", line 305, in do_create
    create_inner(archive, cache)
  File "/home/user/.local/lib/python3.5/site-packages/borg/archiver.py", line 278, in create_inner
    read_special=args.read_special, dry_run=dry_run)
  File "/home/user/.local/lib/python3.5/site-packages/borg/archiver.py", line 359, in _process
    read_special=read_special, dry_run=dry_run)
  File "/home/user/.local/lib/python3.5/site-packages/borg/archiver.py", line 333, in _process
    status = archive.process_file(path, st, cache, self.ignore_inode)
  File "/home/user/.local/lib/python3.5/site-packages/borg/archive.py", line 668, in process_file
    ids = cache.file_known_and_unchanged(path_hash, st, ignore_inode)
  File "/home/user/.local/lib/python3.5/site-packages/borg/cache.py", line 437, in file_known_and_unchanged
    self._read_files()
  File "/home/user/.local/lib/python3.5/site-packages/borg/cache.py", line 204, in _read_files
    item[0] += 1
TypeError: 'int' object is not subscriptable

Platform: Linux laptop 4.8.16-300.fc25.x86_64 #1 SMP Fri Jan 6 18:11:49 UTC 2017 x86_64 x86_64
Linux: Fedora 25 Twenty Five
Borg: 1.0.9  Python: CPython 3.5.2
PID: 28466  CWD: /home/user
sys.argv: ['/home/user/.local/bin/borg', 'create', '--stats', '--compression', 'zlib,5', 'backup:/mnt/disk/laptop::laptop-2017-01-17', '/home/user', '--exclude', '/home/user/.cache', '--exclude', '/home/user/jhbuild', '--exclude', '/home/user/Downloads/no_backup', '--exclude', '*.pyc']
SSH_ORIGINAL_COMMAND: None
```

**Comment by enkore** [comment]
Most likely a corrupted files cache.

**Comment by ThomasWaldmann** [comment]
@elya5 any feedback?

**Comment by elya5** [comment]
Sorry for the delay. Deleting the cache worked although I couldn't see any file system or SSD errors with dmesg/journalctl/smartctl.

**Comment by ThomasWaldmann** [comment]
@elya5 did you check the detailled SMART values or just the global "PASSED" status? The table is often more informative. Also check your RAM, memtest86+.

**Comment by enkore** [comment]
Sometimes these things can also be just bitrot, eg. the distance between an encoded array (which was expected here) and an encoded integer is just 1 flipped bit. That's why work was put forward to automatically recover from issues like these (although this one specifically wouldn't be caught ATM) and to use strong integrity protection for these files. (Doesn't help against bad RAM / bus though).

**Comment by elya5** [comment]
memtest and SMART values are ok (also in the table).

**Comment by ThomasWaldmann** [comment]
@elya5 strange.

something was flipping bits (and this does not look like a software bug, but rather a hw issue).
