### ISSUE TITLE
libreadline.so.6: no version information available?

### ISSUE THREAD

**Issue by maboxx** [borgbackup/borg#2118]
Hello,
Since two days I recieving an error message during my borg backup. Please see below.
I start the backup about a script........

Here is the output in my log file:

```
Start der Sicherung Wed Feb  1 17:51:57 CET 2017.
/bin/sh: /tmp/_MEIJTgqDx/libreadline.so.6: no version information available (required by /bin/sh)
/bin/sh: relocation error: /bin/sh: symbol rl_filename_stat_hook, version READLINE_6.3 not defined in file libreadline.so.6 with link time reference
Local Exception.
Traceback (most recent call last):
  File "borg/archiver.py", line 2052, in main
  File "borg/archiver.py", line 1997, in run
  File "borg/archiver.py", line 90, in wrapper
  File "borg/archiver.py", line 305, in do_create
  File "borg/archiver.py", line 278, in create_inner
  File "borg/archiver.py", line 359, in _process
  File "borg/archiver.py", line 359, in _process
  File "borg/archiver.py", line 359, in _process
  File "borg/archiver.py", line 359, in _process
  File "borg/archiver.py", line 333, in _process
  File "borg/archive.py", line 711, in process_file
  File "borg/archive.py", line 294, in add_item
  File "borg/archive.py", line 298, in write_checkpoint
  File "borg/archive.py", line 333, in save
  File "borg/repository.py", line 200, in commit
  File "borg/repository.py", line 303, in compact_segments
  File "borg/repository.py", line 794, in write_put
  File "borg/repository.py", line 665, in get_write_fd
  File "borg/repository.py", line 826, in close_segment
OSError: [Errno 5] Input/output error

Platform: Linux linux 4.4.36-8-default #1 SMP Fri Dec 9 16:18:38 UTC 2016 (3ec5648) x86_64 
Linux: openSUSE  42.2 x86_64
Borg: 1.0.9  Python: CPython 3.5.2
PID: 22735  CWD: /root/bin
sys.argv: ['borg', 'create', '--compression', 'lz4', '--exclude-caches', '--one-file-system', '-v', '--stats', '--progress', '/backup/borgbackups::DATA-{now:%Y-%m-%d-%H%M%S}', '/data/files/document', '/data/files/homes', '/data/files/photo', '/data/files/music/Favorites']
SSH_ORIGINAL_COMMAND: None
```

What does it matter about "libreadline.so.6"? Do you need more informations from me?

Thank you very much for any help.

Greetings maboxx

**Comment by enkore** [comment]
The /bin/sh warning is unrelated to the IO error, not sure what the warning is about. Doesn't seem to bother it much.

The IO error is your real problem here. Take a look at dmesg if there are error messages on the file system. Perhaps also check `smartctl -x /dev/sdBackupDrive`.

**Comment by maboxx** [comment]
The mount point /backup is on a remote NAS drive, not a local drive. 
I also have borgbackups on my local file system and there I am not recieving any errors. Could be the file system problems then on the remote NAS drive?

**Comment by enkore** [comment]
Yes, when using a network file system for a repository then this error could mean a network issue or a problem on the real file system on the other end.

**Comment by maboxx** [comment]
Ok it seemst that it was a network issue. The last two backups works.

**Comment by ThomasWaldmann** [comment]
This looks resolved, closing.
