### ISSUE TITLE
try borg as non-root, with capabilities

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2125]
See there, try it and document it how it works for borg:

https://blog.night-shade.org.uk/2015/04/linux-capabilities-and-rsync-from-presentation-to-practice/

**Comment by enkore** [comment]
[CAP_DAC_READ_SEARCH](https://github.com/borgbackup/borg/issues/36#issuecomment-266198848) would be the cap we're after. Would be worth trying if setcap(8) on the *script* (borg entrypoints *are* scripts, binaries *are not*) works. I assume they don't, for the same reason that suid doesn't work (scripts are not executed through exec*).

Anyhow, for most machines there's no big point, since you can get into eg. a running OpenSSH server with any user when you know the servers private key (and EC is enabled).

**Comment by mfiano** [comment]
You would need to use `setcap cap_dac_read_search+ep` for this to work, however, this needs to be done on the python3 binary, not borg, or borgmatic wrapper etc. An extremely bad wrapper script but which illustrates a working example would be something like

``` bash
#!/bin/bash
# figure out the real path to python - some distros link to hide it behind a couple recursive symlinks
PYTHON_BIN=$(readlink -f $(type -p python))
sudo setcap cap_dac_read_search+ep $PYTHON_BIN
borg <your params>
sudo setcap cap_dac_read_search-ep $PYTHON_BIN
```

**Comment by klausenbusk** [comment]
Another option worth considering is ACL, which is what I use.

```
setfacl -R -m "user:backup:rX" <dir>
setfacl -d -R -m "user:backup:rX" <dir>
```
Which allow the backup user read and exec (folder only) access to files in <dir>.

**Comment by puetzk** [comment]
You can set this up as an ambient capability for the backup run in systemd pretty easily, 
and (since it's using ambient capabilities) it stays despite the script-interpreter execs

One shortcoming is that it *also* stick through to borg's child processes like ssh that don't actually need it, but that's not *worse* than just running the whole thing as root :-P

### /etc/systemd/system/borgbackup@.service
```
[Unit]
Description=backup %i

Wants=network-online.target
Wants=local-fs.target
After=network-online.target
After=local-fs.target

[Service]
User=backup
AmbientCapabilities=CAP_DAC_READ_SEARCH
EnvironmentFile=/etc/borgbackup/%i
Type=oneshot

ExecStart=/usr/bin/borg create --stats ::%i-{now:%%Y-%%m-%%d} /
```

### /etc/borgbackup/mydomain
```
	BORG_REPO=<user>@<host>:<path>
	BORG_REMOTE_PATH=borg1
	BORG_RSH="ssh -i <key>"
```

Then turn run an individual backup with
`systemctl startborgbackup@mydomain.service`
or set up nightly runs with

### /etc/systemd/system/borgbackup@.timer
```
[Unit]
Description=nightly backups

[Timer]
# backup somewhere between 6AM and 2PM UTC
OnCalendar=*-*-* 10:00:00
AccuracySec=1h
RandomizedDelaySec=4h

Persistent=True
Unit=borgbackup@%i.service

[Install]
WantedBy=default.target
```

`systemctl enable borgbackup@mydomain.timer`

**Comment by elho** [comment]
`libcap` 2.26 added support for ambient capabilities and comes with the `capsh` tool that can be used to (more or less) directly invoke borg with CAP_DAC_READ_SEARCH. It unfortunately can not exec other programs directly, it can only invoke a shell with capabilities, but one can pass commands to that via `c`, albeit quite a bit akward to get right. Order of arguments matters, as `capsh` permorms the according actions in that order.

i'm using these shell functions for my backup scripts:
```
cap_shell ()
{
    local capabilities="$(capsh --print | sed --quiet --expression 's/^Current:[
[:space:]]\+=[[:space:]]\+//;T;s/cap_dac_read_search,\?//;p')"

    capsh --keep=1 \
          --caps='cap_setgid,cap_setuid,cap_setpcap=ep cap_dac_read_search=eip' 
\
          --user=borg --addamb='cap_dac_read_search' --drop="${capabilities}" \
          -- "$@"
}

cap_invoke ()
{
    local command="$1"

    shift
    cap_shell -c -- "${command} \"\$@\"" "${command}" "$@"
}
```

They allow one to `cap_invoke borg create "arguments with spaces" "being passed correctly"` as unprivileged user (`borg` in this case). Note: It will only change the user, not set `HOME` or anything like `su`/`sudo` would do, so you either do need to `export HOME` for the target user or use the according environment variables of borg like `BORG_BASE_DIR`.
And `cap_shell` can be used directly as well for debugging/manual interactive backup runs. You can invoke `capsh --print` instead of borg to verify the capabilites worked out as intended.

It does acquire `cap_setgid`, `cap_setuid` and `cap_setpcap` and keeps them through `setuid()` to change the user and set the capabilities, `cap_dac_read_search` is the only one set to be inherited through `execve()` to the shell and the Python interpreter invoked by it, hanks to being set ambient, as well.

Unlike with the `systemd` approach, its not only mor estraight-forward to invoke the backup script manually, at also allows to do some tasks as root, like taknig LVM/filesystem snapshots before and after invoking borg unprivileged.

**Comment by MorgothSauron** [comment]
I tried to set capabilties on the borg standalone binary (`cap_dac_read_search=+ep`) and it fails when I run borg:
```
Traceback (most recent call last):
  File "borg/archiver.py", line 38, in <module>
  File "/home/vagrant/.pyenv/versions/3.5.7/envs/borg-env/lib/python3.5/site-packages/PyInstaller-3.2.1-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "borg/helpers.py", line 75, in <module>
  File "/home/vagrant/.pyenv/versions/3.5.7/envs/borg-env/lib/python3.5/site-packages/PyInstaller-3.2.1-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 573, in load_module
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```

the borg binary will work again after removing the capabiltity (`cap_dac_read_search=-ep`)

**Comment by puetzk** [comment]
Like SUID permission bits, binaries with with capabilities set do not inherit various environment variables (including `LD_*`, so that an unprivileged user cannot use this to get a library of their choosing loaded by a privileged process.  See Secure-execution mode in the ld.so(8) manpage.

So you can't use persistent filesystem bits to set privilege, while also expecting it will find dependencies in a venv you've set in the unprivileged caller's environment; that would be a security hole if possible.

**Comment by MorgothSauron** [comment]
> Like SUID permission bits, binaries with with capabilities set do not inherit various environment variables (including `LD_*`, so that an unprivileged user cannot use this to get a library of their choosing loaded by a privileged process. See Secure-execution mode in the ld.so(8) manpage.
> 
> So you can't use persistent filesystem bits to set privilege, while also expecting it will find dependencies in a venv you've set in the unprivileged caller's environment; that would be a security hole if possible.

That makes sense. Thanks for the clarification. 

I think my best bet is to configure sudo for my user to temporarily change capabilties on the python binary (https://github.com/borgbackup/borg/issues/2125#issuecomment-303229506). I'm doing this because I could do it with restic: backup files owned by root without running it as root or with sudo.
