### ISSUE TITLE
hashindex read failed - possibly failing disk

### ISSUE THREAD

**Issue by andrewufrank** [borgbackup/borg#2129]
i cannot get list or info to work on a repository after a failure. the error messages is following. i assume that the issue was created by problems of the harddisk, but it could also be that i have two repositories with the same name (and id, i fear) - i am new to this...
is it possible to recover the data or the repository (minus the last partial create)? which files can i delete and they will be rebuild (on a new disk, likely)? 

thank you for advice!

andrew 
````
Platform: Linux oporto 4.8.0-2-amd64 #1 SMP Debian 4.8.11-1 (2016-12-02) x86_64 
Linux: debian 9.0 
Borg: 1.0.9  Python: CPython 3.5.3
PID: 25306  CWD: /media/frank/6f7b951d-abad-4dcd-a173-ca6c79676e43/borg
sys.argv: ['/usr/bin/borg', 'create', '-p', '-s', '-C', 'zlib,6', 'BigCollection1::fromOporto', '/media/frank/usa/fromOporto']
SSH_ORIGINAL_COMMAND: None

frank@oporto:/media/frank/6f7b951d-abad-4dcd-a173-ca6c79676e43/borg$  borg info BigCollection1::fromOporto
hashindex: /media/frank/6f7b951d-abad-4dcd-a173-ca6c79676e43/borg/BigCollection1/index.154657: fread buckets failed (expected 240314680, got 1257454) (Input/output error)
Local Exception.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 2052, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1997, in run
    return func(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 84, in wrapper
    kwargs['manifest'], kwargs['key'] = Manifest.load(repository)
  File "/usr/lib/python3/dist-packages/borg/helpers.py", line 114, in load
    cdata = repository.get(cls.MANIFEST_ID)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 515, in get
    self.index = self.open_index(self.get_transaction_id())
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 207, in open_index
    return NSIndex.read((os.path.join(self.path, 'index.%d') % transaction_id).encode('utf-8'))
  File "borg/hashindex.pyx", line 79, in borg.hashindex.IndexBase.read (borg/hashindex.c:1550)
  File "borg/hashindex.pyx", line 67, in borg.hashindex.IndexBase.__cinit__ (borg/hashindex.c:1353)
Exception: hashindex_read failed

Platform: Linux oporto 4.8.0-2-amd64 #1 SMP Debian 4.8.11-1 (2016-12-02) x86_64 
Linux: debian 9.0 
Borg: 1.0.9  Python: CPython 3.5.3
PID: 14243  CWD: /media/frank/6f7b951d-abad-4dcd-a173-ca6c79676e43/borg
sys.argv: ['/usr/bin/borg', 'info', 'BigCollection1::fromOporto']
SSH_ORIGINAL_COMMAND: None
````

**Comment by enkore** [comment]
Delete/rename repository/index.*N* and repository/hints.*N* (better rename)

**Comment by andrewufrank** [comment]
thank you for the help. are these files in the borg repository or in ~/.cache/borg? what does N stand for? (or can i see the numbers when i do ls?). what is the advantage of rename?
would borg check --repair help?

**Comment by enkore** [comment]
These are in the repository. N is some number; you'll have only one file starting with `index.` and one with `hints.`. Rename instead of delete means that one can later do forensics with the files if one likes.

borg check might make sense to see if something else is damaged, too, but Borg 1.0.x will not recover from this error automatically (this was added in 1.1.x beta).

**Comment by andrewufrank** [comment]
thank you!
