### ISSUE TITLE
Uncaught error while reading symlink

### ISSUE THREAD

**Issue by jast** [borgbackup/borg#2158]
In some slightly more exotic setups, specifically VirtualBox shared folders in my case, `readlink` calls can fail with an exception:

```
Local Exception.   
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/borg/archive.py", line 79, in backup_io
    yield
  File "/usr/lib/python3.6/site-packages/borg/archive.py", line 626, in process_symlink
    source = os.readlink(path)
OSError: [Errno 71] Protocol error: '/media/sf_C_DRIVE/ProgramData/Anwendungsdaten'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 2052, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 1997, in run
    return func(args)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 90, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 305, in do_create
    create_inner(archive, cache)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 278, in create_inner
    read_special=args.read_special, dry_run=dry_run)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 359, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 363, in _process
    status = archive.process_symlink(path, st)
  File "/usr/lib/python3.6/site-packages/borg/archive.py", line 626, in process_symlink
    source = os.readlink(path)
  File "/usr/lib/python3.6/contextlib.py", line 100, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3.6/site-packages/borg/archive.py", line 81, in backup_io
    raise BackupOSError(os_error) from os_error
borg.archive.BackupOSError: [Errno 71] Protocol error: '/media/sf_C_DRIVE/ProgramData/Anwendungsdaten'

Platform: Linux perceptron 4.9.8-1-ARCH #1 SMP PREEMPT Mon Feb 6 12:59:40 CET 2017 x86_64 
Linux: arch  
Borg: 1.0.9  Python: CPython 3.6.0
PID: 9062  CWD: [snip1]
sys.argv: ['/sbin/borg', 'create', '-p', '-C', 'lz4', '[snip1]/borg::[snip]-20170214-1711', '/media/sf_C_DRIVE/ProgramData', [snip2]]
```

I believe that VirtualBox stopped allowing symlink reads in shared folders altogether because they don't have a sensible security model for it.

Maybe this exception should be caught and the symlink skipped, similar to how permission errors are treated?

**Comment by ThomasWaldmann** [comment]
Strange, I thought we already do what you suggest.
