### ISSUE TITLE
borg key crashes

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2240]
```
$ BORG_REPO=abc borg key
Traceback (most recent call last):
  File "/home/tw/w/borg-env/bin/borg", line 11, in <module>
    load_entry_point('borgbackup', 'console_scripts', 'borg')()
  File "/home/tw/w/borg/src/borg/archiver.py", line 3423, in main
    args = archiver.get_args(sys.argv, os.environ.get('SSH_ORIGINAL_COMMAND'))
  File "/home/tw/w/borg/src/borg/archiver.py", line 3296, in get_args
    result = self.parse_args(argv[1:])
  File "/home/tw/w/borg/src/borg/archiver.py", line 3315, in parse_args
    if args.func == self.do_create:
AttributeError: 'Namespace' object has no attribute 'func'
```

**Comment by ThomasWaldmann** [comment]
same in 1.0-maint:
``` 
(borg-env)tw@tux:~/w/borg$ BORG_REPO=ccc BORG_PASSPHRASE=1 borg key
Traceback (most recent call last):
  File "/home/tw/w/borg-env/bin/borg", line 11, in <module>
    load_entry_point('borgbackup', 'console_scripts', 'borg')()
  File "/home/tw/w/borg/borg/archiver.py", line 2135, in main
    args = archiver.get_args(sys.argv, os.environ.get('SSH_ORIGINAL_COMMAND'))
  File "/home/tw/w/borg/borg/archiver.py", line 2046, in get_args
    result = self.parse_args(argv[1:])
  File "/home/tw/w/borg/borg/archiver.py", line 2065, in parse_args
    if args.func == self.do_create:
AttributeError: 'Namespace' object has no attribute 'func'
```

**Comment by enkore** [comment]
Didn't we fix this already once?
