### ISSUE TITLE
Permission error if server is killed, new backups fail

### ISSUE THREAD

**Issue by lightonflux** [borgbackup/borg#2276]
Had some long running prune process over the network. And i killed the serve process on the server. The client process stopped.

But after this the next backups failed because some permissions were not set correctly. Some data chunk files belonged to `root:root` not `borg:borg`. Manually changing the owner fixed this specific error. But it would be nice if the server could recover automatically.

authorized keys:

```
command="cd /home/borg/repos/client ; /usr/local/bin/borg serve --restrict-to-path=/home/borg/repos/dione",no-port-forwarding,no-X11-forwarding,no-pty,no-agent-forwarding,no-user-rc ssh-rsa <pubkey>
```

Error message:

```
Mär 09 02:17:22 client borg-backup.sh[29421]: Linux: debian 8.7
Mär 09 02:17:22 client borg-backup.sh[29421]: Borg: 1.0.9  Python: CPython 3.4.2
Mär 09 02:17:22 client borg-backup.sh[29421]: PID: 29450  CWD: /
Mär 09 02:17:22 client borg-backup.sh[29421]: sys.argv: ['/usr/bin/borg', 'create', '-vsC', 'lz4', 'atlas-borg:.::{now:%Y-%m-%d}-processwire', '/var/lib/lxc/processwire']
Mär 09 02:17:22 client borg-backup.sh[29421]: SSH_ORIGINAL_COMMAND: None
Mär 09 02:17:23 client borg-backup.sh[29421]: Remote: Borg 1.0.10: exception in RPC call:
Mär 09 02:17:23 client borg-backup.sh[29421]: Remote: Traceback (most recent call last):
Mär 09 02:17:23 client borg-backup.sh[29421]: Remote:   File "borg/remote.py", line 145, in serve
Mär 09 02:17:23 client borg-backup.sh[29421]: Remote:   File "borg/repository.py", line 516, in get
Mär 09 02:17:23 client borg-backup.sh[29421]: Remote:   File "borg/repository.py", line 151, in get_transaction_id
Mär 09 02:17:23 client borg-backup.sh[29421]: Remote:   File "borg/repository.py", line 613, in get_segments_transaction_id
Mär 09 02:17:23 client borg-backup.sh[29421]: Remote:   File "borg/repository.py", line 634, in is_committed_segment
Mär 09 02:17:23 client borg-backup.sh[29421]: Remote: PermissionError: [Errno 13] Permission denied: '/home/borg/repos/client/data/2/26352'
Mär 09 02:17:23 client borg-backup.sh[29421]: Remote: Platform: Linux atlas 3.14-0.bpo.1-amd64 #1 SMP Debian 3.14.12-1~bpo70+1 (2014-07-13) x86_64
Mär 09 02:17:23 client borg-backup.sh[29421]: Remote: Linux: debian 7.11
Mär 09 02:17:23 client borg-backup.sh[29421]: Remote: Borg: 1.0.10  Python: CPython 3.5.3
Mär 09 02:17:23 client borg-backup.sh[29421]: Remote: PID: 16494  CWD: /home/borg/repos/client
Mär 09 02:17:23 client borg-backup.sh[29421]: Remote: sys.argv: ['/usr/local/bin/borg', 'serve', '--restrict-to-path=/home/borg/repos/client']
Mär 09 02:17:23 client borg-backup.sh[29421]: Remote: SSH_ORIGINAL_COMMAND: 'borg serve --umask=077 --info'
Mär 09 02:17:23 client borg-backup.sh[29421]: Remote:
Mär 09 02:17:23 client borg-backup.sh[29421]: ('Remote Exception (see remote log for the traceback)', 'PermissionError')
Mär 09 02:17:23 client borg-backup.sh[29421]: Platform: Linux client 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u1 (2017-02-22) x86_64
Mär 09 02:17:23 client borg-backup.sh[29421]: Linux: debian 8.7
Mär 09 02:17:23 client borg-backup.sh[29421]: Borg: 1.0.9  Python: CPython 3.4.2
Mär 09 02:17:23 client borg-backup.sh[29421]: PID: 29455  CWD: /
Mär 09 02:17:23 client borg-backup.sh[29421]: sys.argv: ['/usr/bin/borg', 'create', '-vsC', 'lz4', 'atlas-borg:.::{now:%Y-%m-%d}-vim', '/var/lib/lxc/vim']
Mär 09 02:17:23 client borg-backup.sh[29421]: SSH_ORIGINAL_COMMAND: None

```

**Comment by lightonflux** [comment]
Forgot that i prune manually with root after killing the server. This is likely to change ownership right?

**Comment by ThomasWaldmann** [comment]
It is neither required to run borg on the repo server as the root user nor recommended.
You just get into trouble, as you just noticed.

**Comment by lightonflux** [comment]
A little warning like "This repo belongs to $USER, do you want to continue as root?" would be handy for clumsy people like me. :)

**Comment by ThomasWaldmann** [comment]
@lightonflux hardly doable in a fool proof way. it could be that some owners are right, that just some segment files are owned by root. so we'ld have to check all segment files.

besides that being slow, this is a very general problem and admins should be aware of it (you are now, too).
