### ISSUE TITLE
OSError: [Errno 117] Structure needs cleaning

### ISSUE THREAD

**Issue by lheckemann** [borgbackup/borg#2330]
After the connection to my external hard drive failed in the middle of a backup (faulty USB cable) and I tried to create a new one, I'm getting this error when I attempt any operation on the backup repo, including "check". How can I recover from this?

```
Local Exception.
Traceback (most recent call last):
  File "/nix/store/zg1lbc91w54mz5x5glmml4max3m52m66-borgbackup-1.0.9/lib/python3.4/site-packages/borg/repository.py", line 432, in check
    transaction_id = self.get_transaction_id()
  File "/nix/store/zg1lbc91w54mz5x5glmml4max3m52m66-borgbackup-1.0.9/lib/python3.4/site-packages/borg/repository.py", line 150, in get_transaction_id
    segments_transaction_id = self.io.get_segments_transaction_id()
  File "/nix/store/zg1lbc91w54mz5x5glmml4max3m52m66-borgbackup-1.0.9/lib/python3.4/site-packages/borg/repository.py", line 612, in get_segments_transaction_id
    if self.is_committed_segment(segment):
  File "/nix/store/zg1lbc91w54mz5x5glmml4max3m52m66-borgbackup-1.0.9/lib/python3.4/site-packages/borg/repository.py", line 633, in is_committed_segment
    with open(self.segment_filename(segment), 'rb') as fd:
OSError: [Errno 117] Structure needs cleaning: '/mnt/backup/linus/backup/data/3/31663'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/zg1lbc91w54mz5x5glmml4max3m52m66-borgbackup-1.0.9/lib/python3.4/site-packages/borg/archiver.py", line 2052, in main
    exit_code = archiver.run(args)
  File "/nix/store/zg1lbc91w54mz5x5glmml4max3m52m66-borgbackup-1.0.9/lib/python3.4/site-packages/borg/archiver.py", line 1997, in run
    return func(args)
  File "/nix/store/zg1lbc91w54mz5x5glmml4max3m52m66-borgbackup-1.0.9/lib/python3.4/site-packages/borg/archiver.py", line 90, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/nix/store/zg1lbc91w54mz5x5glmml4max3m52m66-borgbackup-1.0.9/lib/python3.4/site-packages/borg/archiver.py", line 168, in do_check
    if not repository.check(repair=args.repair, save_space=args.save_space):
  File "/nix/store/zg1lbc91w54mz5x5glmml4max3m52m66-borgbackup-1.0.9/lib/python3.4/site-packages/borg/repository.py", line 435, in check
    transaction_id = self.io.get_segments_transaction_id()
  File "/nix/store/zg1lbc91w54mz5x5glmml4max3m52m66-borgbackup-1.0.9/lib/python3.4/site-packages/borg/repository.py", line 612, in get_segments_transaction_id
    if self.is_committed_segment(segment):
  File "/nix/store/zg1lbc91w54mz5x5glmml4max3m52m66-borgbackup-1.0.9/lib/python3.4/site-packages/borg/repository.py", line 633, in is_committed_segment
    with open(self.segment_filename(segment), 'rb') as fd:
OSError: [Errno 117] Structure needs cleaning: '/mnt/backup/linus/backup/data/3/31663'

Platform: Linux computer 4.9.13 #1-NixOS SMP Sun Feb 26 10:11:18 UTC 2017 x86_64
Linux:
Borg: 1.0.9  Python: CPython 3.4.6
PID: 6034  CWD: /home/linus
sys.argv: ['/nix/store/zg1lbc91w54mz5x5glmml4max3m52m66-borgbackup-1.0.9/bin/borg', 'check', '/mnt/backup/linus/backup']
SSH_ORIGINAL_COMMAND: None

```

**Comment by enkore** [comment]
That's probably a case for `fsck`.

**Comment by lheckemann** [comment]
Whoops, I did try that but forgot to use the `-f` flag for fsck... Thanks for pointing me in that direction again!
