### ISSUE TITLE
Pip3: condor not listed as requirement

### ISSUE THREAD

**Issue by MPW1412** [borgbackup/borg#2345]
Hello,

I installed Borgbackup via pip3, but the requirements seem incomplete:

```
$ borg --version
Traceback (most recent call last):
  File "/usr/bin/borg", line 9, in <module>
    load_entry_point('borgbackup==1.0.10', 'console_scripts', 'borg')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.4/dist-packages/borg/__init__.py", line 9, in <module>
    import condor
ImportError: No module named 'condor'
```

Please name condor as dependy.

Regards,
Matthias

**Comment by ThomasWaldmann** [comment]
We do not require condor. You need to do `pip install borgbackup`.
