### ISSUE TITLE
CompressionSpec failed

### ISSUE THREAD

**Issue by LucasBartosch** [borgbackup/borg#2385]
```bash
borg  
```
inside virtualenv
gives
```
Traceback (most recent call last):
  File "/root/borg-dev/borg-env/bin/borg", line 11, in <module>
    load_entry_point('borgbackup', 'console_scripts', 'borg')()
  File "/root/borg-dev/borg-env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/root/borg-dev/borg-env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/root/borg-dev/borg-env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/root/borg-dev/borg-env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/root/borg-dev/borg/src/borg/archiver.py", line 34, in <module>
    from .archive import Archive, ArchiveChecker, ArchiveRecreater, Statistics, is_special
  File "/root/borg-dev/borg/src/borg/archive.py", line 24, in <module>
    from .compress import Compressor, CompressionSpec
ImportError: cannot import name 'CompressionSpec'
```

**Comment by ThomasWaldmann** [comment]
works for me

**Comment by ThomasWaldmann** [comment]
maybe you need to pip install it (again) into the venv?

**Comment by enkore** [comment]
Which installation instructions did you follow?

**Comment by LucasBartosch** [comment]
its directly cloned from github, so "using git".

**Comment by enkore** [comment]
The trace suggests that the extensions where not compiled; check if you installed cython first and if there were any errors.

**Comment by LucasBartosch** [comment]
Corrected malformed update script. Thanks for the tipps
