### ISSUE TITLE
v1.1.0b4 crashes with traceback if run on CentOS-6

### ISSUE THREAD

**Issue by awnz** [borgbackup/borg#2425]
Hi, first-time caller testing borg as a replacement for Areca at a couple of schools, some servers are CentOS-6.

I hit a snag, looks like glibc-2.12 backward compatibility broke with ~~v1.0.10~~ v1.1.0b4.

The precompiled borg-linux64 binary for ~~v1.0.10~~ v1.1.0b4 crashes on CentOS-6 with this traceback:

```
Traceback (most recent call last):
  File "borg/__main__.py", line 1, in <module>
  File "/home/vagrant/.pyenv/versions/3.5.3/envs/borg-env/lib/python3.5/site-packages/PyInstaller-3.2.1-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "borg/archiver.py", line 33, in <module>
  File "/home/vagrant/.pyenv/versions/3.5.3/envs/borg-env/lib/python3.5/site-packages/PyInstaller-3.2.1-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "borg/archive.py", line 22, in <module>
  File "/home/vagrant/.pyenv/versions/3.5.3/envs/borg-env/lib/python3.5/site-packages/PyInstaller-3.2.1-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "borg/cache.py", line 25, in <module>
  File "/home/vagrant/.pyenv/versions/3.5.3/envs/borg-env/lib/python3.5/site-packages/PyInstaller-3.2.1-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "borg/key.py", line 25, in <module>
  File "/home/vagrant/.pyenv/versions/3.5.3/envs/borg-env/lib/python3.5/site-packages/PyInstaller-3.2.1-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "borg/platform/__init__.py", line 21, in <module>
  File "/home/vagrant/.pyenv/versions/3.5.3/envs/borg-env/lib/python3.5/site-packages/PyInstaller-3.2.1-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 573, in load_module
  File "src/borg/platform/linux.pyx", line 3, in init borg.platform.linux (src/borg/platform/linux.c:7773)
  File "/home/vagrant/.pyenv/versions/3.5.3/envs/borg-env/lib/python3.5/site-packages/PyInstaller-3.2.1-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 573, in load_module
ImportError: /lib64/libc.so.6: version `GLIBC_2.13' not found (required by /tmp/_MEIVIf5q4/resource.so)
Failed to execute script __main__
```

v1.0.9 (edit: and v1.0.10) work fine.

**Comment by infectormp** [comment]
check your glibc version 

> version `GLIBC_2.13' not found

**Comment by infectormp** [comment]
dublicate of https://github.com/borgbackup/borg/issues/491

**Comment by awnz** [comment]
No I don't think it's a duplicate. As stated above, v1.0.9 works with glibc = 2.12 and only one module resource.so needs glibc 2.13 (and going from other comments in #491, that module isn't critical).

**Comment by infectormp** [comment]
https://borgbackup.readthedocs.io/en/stable/installation.html
> Linux: glibc >= 2.13 (ok for most supported Linux releases). Maybe older glibc versions also work, if they are compatible to 2.13.

**Comment by ThomasWaldmann** [comment]
Your traceback shows pyinstaller 3.2.1, so you used the "pyi321" binary that I made additionally available for the 1.0.10 release (but not for 1.0.9).

So, try the normal 1.0.10 binary (no "py321" in the filename)?

**Comment by ThomasWaldmann** [comment]
```
tw@tux:~/w/borg/bbb$ ./glibc_check.py 2.11 borg110_321me/*|grep 2.13
borg110_321me/resource.so 2.13

tw@tux:~/w/borg/bbb$ ./glibc_check.py 2.11 borg110me/*|grep 2.13
borg110me/resource.so 2.13

tw@tux:~/w/borg/bbb$ ./glibc_check.py 2.11 borg109me/*|grep 2.13
borg109me/resource.cpython-35m-x86_64-linux-gnu.so 2.13
```
It seems borg 1.0.9 and both borg 1.0.10 versions contain the "resource" lib which wants glibc 2.13.
Not sure why the .so name is different for borg 1.0.9.

**Comment by ThomasWaldmann** [comment]
That traceback looks strange:
```
Traceback (most recent call last):
  File "borg/__main__.py", line 1, in <module>
  File "/home/vagrant/.pyenv/versions/3.5.3/envs/borg-env/lib/python3.5/site-packages/PyInstaller-3.2.1-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "borg/archiver.py", line 33, in <module>
  File "/home/vagrant/.pyenv/versions/3.5.3/envs/borg-env/lib/python3.5/site-packages/PyInstaller-3.2.1-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "borg/archive.py", line 22, in <module>
  File "/home/vagrant/.pyenv/versions/3.5.3/envs/borg-env/lib/python3.5/site-packages/PyInstaller-3.2.1-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "borg/cache.py", line 25, in <module>
  File "/home/vagrant/.pyenv/versions/3.5.3/envs/borg-env/lib/python3.5/site-packages/PyInstaller-3.2.1-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "borg/key.py", line 25, in <module>
```
Above pathes look like borg 1.0.x - but somehow I can't make sense from the line numbers.

```
  File "/home/vagrant/.pyenv/versions/3.5.3/envs/borg-env/lib/python3.5/site-packages/PyInstaller-3.2.1-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "borg/platform/__init__.py", line 21, in <module>
  File "/home/vagrant/.pyenv/versions/3.5.3/envs/borg-env/lib/python3.5/site-packages/PyInstaller-3.2.1-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 573, in load_module
  File "src/borg/platform/linux.pyx", line 3, in init borg.platform.linux (src/borg/platform/linux.c:7773)
```
There is no platform package in borg 1.0, this looks like 1.1 / master branch.

**Comment by awnz** [comment]
Sorry you're right. I didn't look carefully enough at what I had downloaded, that was the 1.1.0b4 binary.

**Comment by ThomasWaldmann** [comment]
Ah, ok. I'll check what's the issue in 1.1.0b4.

**Comment by ThomasWaldmann** [comment]
Found it: linux.pyx uses the resource module for `resource.getpagesize`.

**Comment by ThomasWaldmann** [comment]
But considering 1.1.0 is not even available as a stable release (just beta) and centos6 is rather old, maybe we do not need to fix this. One can just use borg 1.0.x on centos6.

**Comment by ThomasWaldmann** [comment]
I updated the README for next binary release to tell that >= 2.13 is required and <= 2.12 won't work.

**Comment by awnz** [comment]
Thanks. Suggestion: Would it help to avoid future confusion to make a specific reference at https://borgbackup.readthedocs.io/en/stable/installation.html that versions only up to 1.0.10 will work on EL6 (RHEL6 and its derivatives like CentOS-6)?

EL6 is still alive and supported until November 2020 so probably deserves a mention :)

**Comment by ThomasWaldmann** [comment]
#2430 maybe we can solve it.

**Comment by ThomasWaldmann** [comment]
Also, likely all 1.0.x version will work on centos6, not just up to 1.0.10.

**Comment by awnz** [comment]
Thanks for the fix :)

**Comment by ThomasWaldmann** [comment]
@awnz 1.1.0b5 is released, the binary should work with glibc 2.13 and also slightly older ones.

**Comment by awnz** [comment]
Thanks. Can confirm borg --help works (but takes 27sec to run?) on Centos 6.8 with glibc-2.12.

I'm a bit time-poor atm so will test more extensively later, sorry.

**Comment by ThomasWaldmann** [comment]
@awnz hmm, 27s sounds a bit much. The binary unpacks itself into TMP dir and then runs from there.

Maybe that is slow if your machine is loaded and/or slow and TMP is not on in memory, but on disk?

**Comment by awnz** [comment]
Yeah probably something local. I'll look into it a bit more later, and if I don't put it down to something at my end I'll open a fresh issue.

Thanks :)
