### ISSUE TITLE
'borg serve' access to local repo: locking fails

### ISSUE THREAD

**Issue by ari-s** [borgbackup/borg#2435]
borg is unable to access a local repository via ssh+borg serve: locking fails:

```
# borg create $@ "backup@test2:/backup/::test /tmp/backup \

Remote: Borg 1.0.9: exception in RPC call:
Remote: Traceback (most recent call last):
Remote:   File "/usr/lib/python3/dist-packages/borg/remote.py", line 113, in serve
Remote:     res = f(*args)
Remote:   File "/usr/lib/python3/dist-packages/borg/remote.py", line 153, in open
Remote:     self.repository.__enter__()  # clean exit handled by serve() method
Remote:   File "/usr/lib/python3/dist-packages/borg/repository.py", line 82, in __enter__
Remote:     self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
Remote:   File "/usr/lib/python3/dist-packages/borg/repository.py", line 171, in open
Remote:     self.lock = Lock(os.path.join(path, 'lock'), exclusive, timeout=lock_wait).acquire()
Remote:   File "/usr/lib/python3/dist-packages/borg/locking.py", line 265, in acquire
Remote:     self._wait_for_readers_finishing(remove, sleep)
Remote:   File "/usr/lib/python3/dist-packages/borg/locking.py", line 278, in _wait_for_readers_finishing
Remote:     self._lock.acquire()
Remote:   File "/usr/lib/python3/dist-packages/borg/locking.py", line 143, in acquire
Remote:     raise LockFailed(self.path, str(err)) from None
Remote: borg.locking.LockFailed: ('/backup/', "[Errno 13] Permission denied: '/backup/'")
Remote: Platform: Linux test2 4.9.0-2-amd64 #1 SMP Debian 4.9.18-1 (2017-03-30) x86_64
Remote: Linux: debian 9.0 
Remote: Borg: 1.0.9  Python: CPython 3.5.3
Remote: PID: 4197  CWD: /backup
Remote: sys.argv: ['/usr/bin/borg', 'serve', '--append-only', '--restrict-to-path', '/backup/']
Remote: SSH_ORIGINAL_COMMAND: 'borg serve --umask=077'
Remote: 
('Remote Exception (see remote log for the traceback)', 'LockFailed')
Platform: Linux test2 4.9.0-2-amd64 #1 SMP Debian 4.9.18-1 (2017-03-30) x86_64 
Linux: debian 9.0 
Borg: 1.0.9  Python: CPython 3.5.3
PID: 4186  CWD: /root
sys.argv: ['/usr/bin/borg', 'create', 'backup-@test2:/backup::test', '/tmp/backup']
SSH_ORIGINAL_COMMAND: None
```

The script is generated from a template and of course it is possible to handle the localhost case specifically. So I don't really need this issue fixed, but I'd like to document this at least in issue-form

**Comment by ThomasWaldmann** [comment]
You have a permissions problem there:

Remote: borg.locking.LockFailed: ('/backup/', "[Errno 13] Permission denied: '/backup/'")

Easiest way to deal with users and permissions is to **always** use same user when accessing the borg repo files. If you do some stuff as root and some as user backup, you will run into problems naturally.

You may have to use `chown -R wanteduser.wantedgroup repo` once in case you had that mixup.

**Comment by ThomasWaldmann** [comment]
Could you solve it after my hint? Close?
