### ISSUE TITLE
OSError: [Errno 16] Device or resource busy

### ISSUE THREAD

**Issue by killua-eu** [borgbackup/borg#2441]
Hi, I moved to backing up small repos onto a 600GB beast. During the initial backup, something probably interrupted the process. Upon relaunching the backup, I get a device or resource busy.

```
# sudo /etc/borg/system.sh
Local Exception.
Traceback (most recent call last):
  File "borg/archiver.py", line 2089, in main
  File "borg/archiver.py", line 2025, in run
  File "borg/archiver.py", line 91, in wrapper
  File "borg/archiver.py", line 315, in do_create
  File "borg/archiver.py", line 288, in create_inner
  File "borg/archiver.py", line 369, in _process
  File "borg/archiver.py", line 369, in _process
  File "borg/archiver.py", line 369, in _process
  File "borg/archiver.py", line 343, in _process
  File "borg/archive.py", line 694, in process_file
  File "borg/cache.py", line 401, in add_chunk
  File "borg/repository.py", line 529, in put
  File "borg/repository.py", line 236, in prepare_txn
  File "borg/repository.py", line 623, in cleanup
OSError: [Errno 16] Device or resource busy: '/mnt/qnap/borg-repo/data/4/40332'

Platform: Linux blackspark 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64
Linux: debian stretch/sid
Borg: 1.0.10  Python: CPython 3.5.3
PID: 4552  CWD: /home/pavstra
sys.argv: ['/usr/local/bin/borg', 'create', '--compression', 'zlib,6', '/mnt/qnap/borg-repo::borgcl1-2017-04-25', '/etc', '/home', '/root', '/opt/data', '--exclude', 're:^/var/lib/apt', '--exclude', 're:^/var/[^/]+\\/cache/']
SSH_ORIGINAL_COMMAND: None
```

The repo is located on a NAS

```
cat /proc/mounts | grep qnap
//10.24.21.5/bkp-blackspark /mnt/qnap cifs rw,relatime,vers=1.0,cache=strict,username=borg,domain=NASBKP01,uid=0,noforceuid,gid=0,noforcegid,addr=10.24.21.5,file_mode=0755,dir_mode=0755,nounix,serverino,mapposix,rsize=61440,wsize=65536,actimeo=1 0 0
```
I tried unmounting and remounting the file, eventually found out that the file is locked on the NAS

```
lsof /share/MD0_DATA/bkp-blackspark/borg-repo/data/4/40332
COMMAND   PID  USER   FD   TYPE DEVICE SIZE/OFF     NODE NAME
smbd    31269 admin   30w   REG    9,0  3211264 77463885 /share/MD0_DATA/bkp-blackspark/borg-repo/data/4/40332
```
So i quickly resloved this by restarting samba on the qnap, but that wouldnt work well in production. I cannot install the borg binary on the NAS, so I'm stuck with mounting the backup path. Is there any way to avoid/minimize these problems?

**Comment by ThomasWaldmann** [comment]
Looks rather like a smbd problem, it just has the file still open.

The borg traceback you have posted above is likely because borg tried to cleanup the mess from the interrupted backup, but could not do it because the smbfs denied access to that file.

Guess this is rather a smbfs/smbd question and borg can't do anything about that.

**Comment by enkore** [comment]
Borg does not use file locking; not a Borg issue. Try sambda mailing lists.
