### ISSUE TITLE
borg.repository.ObjectNotFound on Mount

### ISSUE THREAD

**Issue by henfri** [borgbackup/borg#2461]
Hello,

I am having trouble restoring data from a backup that I mounted:
`borg mount borg@openmediavault:/srv/_dev_disk_by-id_ata-ST5000DM000-1FK178_W4J1K7R1/borgbackup /mnt/test2 --foreground`

after copying successfully a lot, I get:

```
Remote: Write failed: Broken pipe

Exception after kill:
Traceback (most recent call last):
  File "handlers.pxi", line 55, in llfuse.capi.fuse_forget (src/llfuse/capi_linux.c:2640)
  File "handlers.pxi", line 56, in llfuse.capi.fuse_forget (src/llfuse/capi_linux.c:2594)
  File "/usr/lib/python3/dist-packages/llfuse/pyapi.py", line 182, in forget
    def forget(self, inode_list):
  File "/usr/lib/python3/dist-packages/borg/helpers.py", line 1290, in handler
    raise exc_cls
borg.helpers.SigTerm

Exception after kill:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 500, in get_many
    yield self.caching_repo.get(key)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 520, in get
    raise self.ObjectNotFound(id_, self.path) from None
borg.repository.ObjectNotFound: (b'wT#\xef\x17\xf2\xdb5\xbeh\x9d\xe5l\xed\xf0\xe4\xbc\x9a\x19\xab\x15\x1f\xab@\xb9J\x1e\xc7$\x82\xbf\x0e', '/tmp/borg-tmph4furz7n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "handlers.pxi", line 298, in llfuse.capi.fuse_read (src/llfuse/capi_linux.c:8200)
  File "handlers.pxi", line 299, in llfuse.capi.fuse_read (src/llfuse/capi_linux.c:8152)
  File "/usr/lib/python3/dist-packages/borg/fuse.py", line 292, in read
    data = self.key.decrypt(id, self.repository.get(id))
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 469, in get
    return next(self.get_many([key]))
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 502, in get_many
    for key_, data in repository_iterator:
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 422, in get_many
    for resp in self.call_many('get', [(id_,) for id_ in ids], is_preloaded=is_preloaded):
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 345, in call_many
    raise ConnectionClosed()
borg.remote.ConnectionClosed

Exception after kill:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 500, in get_many
    yield self.caching_repo.get(key)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 520, in get
    raise self.ObjectNotFound(id_, self.path) from None
borg.repository.ObjectNotFound: (b'\xe8\xb8\x05\xd1\xfc\xbc\xbc\xf0\xcb\x9e\x18m\x05"\x159(\xb9\xe6\x806\xff\xc0B\x95\x0cX\x96q2h\xbf', '/tmp/borg-tmph4furz7n')

During handling of the above exception, another exception occurred:
```

I now cannot unmount, but just kill the process and after that, I cannot use the same mountpoint anymore.

After mounting this backup to a different mountpoint, I restart the copy process and after a while the same problem appears -but at a different file. 

After repeating this ~5x for 60GB, I have successfully restored the backup though. So the backup does seem to be complete.

What could be the reason for this? The backup is remote (WAN, 40Mbit/s: Here I have 100/40 (down/up, DSL) and remote it is 50/50 (Fiber)).

The borg versions (local / remote) are 1.0.9.

Regards,
Hendrik

**Comment by ThomasWaldmann** [comment]
ObjectNotFound means that an object (either a content data chunk or an archive metadata chunk) was expected to be in the repository, but was not found in the repository (the lookup is via the repository index, so could be also a missing index entry maybe).

Please give the borg version you use locally and on the repo server.

Maybe do another try and that time, just use borg extract. Does it always give the same object IDs as missing (the long strange looking string ObjectNotFound(b'id....' )?

Also a good idea: check RAM (memtest86+), disk (smartctl -a / -t long) and filesystem (fsck) on the repo server (and maybe also on the client).

50Gigabit/s symmetric? Or 50Megabit/s symmetric?

**Comment by henfri** [comment]
Mega, Unfortunately.
In fact it is 40: Here I have 100/40 (down/up, DSL) and remote it is 50/50 (Fiber) 
The borg versions are 1.0.9.

I can currently not run an extract, as I am running a backup, but I will do asap.

Regards,
Hendrik

**Comment by enkore** [comment]
Intermittent errors like this one typically turns out to be memory issues.

**Comment by ThomasWaldmann** [comment]
any news?

**Comment by enkore** [comment]
No update; posted data suggests hardware issue; closing. Feel free to reopen if you have new information.
