### ISSUE TITLE
null value in fuse

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [borgbackup/borg#2534]
```
$ borg mount manual_backup/borg_original/ mounted-backup/ --debug --foreground
using builtin fallback logging configuration
Enter passphrase for key /run/media/rpfannsc/backups/manual_backup/borg_original: 
TAM not found and not required
mount data cache capacity: 8 chunks
Mounting filesystem
Initializing llfuse
Calling fuse_mount
Calling fuse_lowlevel_new
Calling fuse_session_add_chan
Calling fuse_session_loop
handler raised <class 'TypeError'> exception (expected bytes, NoneType found), terminating main loop.
Terminated main loop because request handler raised exception, re-raising..
Calling fuse_session_remove_chan
Calling fuse_session_destroy
Local Exception.
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/borg/archiver.py", line 2089, in main
    exit_code = archiver.run(args)
  File "/usr/lib64/python3.5/site-packages/borg/archiver.py", line 2025, in run
    return func(args)
  File "/usr/lib64/python3.5/site-packages/borg/archiver.py", line 91, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib64/python3.5/site-packages/borg/archiver.py", line 566, in do_mount
    operations.mount(args.mountpoint, args.options, args.foreground)
  File "/usr/lib64/python3.5/site-packages/borg/fuse.py", line 101, in mount
    signal = fuse_main()
  File "/usr/lib64/python3.5/site-packages/borg/fuse.py", line 27, in fuse_main
    return llfuse.main(workers=1)
  File "src/fuse_api.pxi", line 343, in llfuse.main (src/llfuse.c:35968)
  File "src/handlers.pxi", line 624, in llfuse.fuse_getxattr (src/llfuse.c:22336)
TypeError: expected bytes, NoneType found

Platform: Linux ronny 4.10.15-200.fc25.x86_64 #1 SMP Mon May 8 18:46:06 UTC 2017 x86_64 x86_64
Linux: Fedora 25 Twenty Five
Borg: 1.0.10  Python: CPython 3.5.3
PID: 2051  CWD: /run/media/rpfannsc/backups
sys.argv: ['/usr/bin/borg', 'mount', 'manual_backup/borg_original/', 'mounted-backup/', '--debug', '--foreground']
SSH_ORIGINAL_COMMAND: None
```

**Comment by enkore** [comment]
Is this triggered by mounting it alone, or do you need to run some program on the mounted files?

**Comment by RonnyPfannschmidt** [comment]
Im running a borg import in the dataset it happpens when backing up certain files

**Comment by enkore** [comment]
These are two bugs in one:

(i) xattr.get_all returns None for an xattr value if the value had length zero (cf. https://github.com/borgbackup/borg/blob/1.0-maint/borg/xattr.py#L221 )
(ii) FUSE getxattr (and possibly other places) fail to handle this case (cf. https://github.com/borgbackup/borg/blob/1.0-maint/borg/fuse.py#L245 )
