### ISSUE TITLE
ssh_cmd() missing 1 required positional argument: 'location'

### ISSUE THREAD

**Issue by tgharold** [borgbackup/borg#255]
Could be PEBKAC... but I did install the lz4 libraries.

```
$ pip3 install git+https://github.com/borgbackup/borg.git@master
You are using pip version 7.1.0, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting git+https://github.com/borgbackup/borg.git@master
  Cloning https://github.com/borgbackup/borg.git (to master) to /tmp/pip-955x9xke-build
Requirement already satisfied (use --upgrade to upgrade): msgpack-python>=0.4.6 in /usr/lib/python3.4/site-packages (from borgbackup==0.26.2.dev100+ng8d529f9)
Installing collected packages: borgbackup
  Found existing installation: borgbackup 0.24.0+1.g8223790
    Uninstalling borgbackup-0.24.0+1.g8223790:
      Successfully uninstalled borgbackup-0.24.0+1.g8223790
  Running setup.py install for borgbackup
Successfully installed borgbackup-0.26.2.dev100+ng8d529f9
```

Running the check (even against two different repos)
```
$ borg check --archives-only ssh://backups.example.com/backup/thomast61p/borgs/borgmatic.borg
borg: Error: Local Exception.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/borg/archiver.py", line 1030, in main
    exit_code = archiver.run(sys.argv[1:])
  File "/usr/lib/python3.4/site-packages/borg/archiver.py", line 986, in run
    return args.func(args)
  File "/usr/lib/python3.4/site-packages/borg/archiver.py", line 79, in do_check
    repository = self.open_repository(args.repository, exclusive=args.repair)
  File "/usr/lib/python3.4/site-packages/borg/archiver.py", line 41, in open_repository
    repository = RemoteRepository(location, create=create)
  File "/usr/lib/python3.4/site-packages/borg/remote.py", line 137, in __init__
    args = self.ssh_cmd()
TypeError: ssh_cmd() missing 1 required positional argument: 'location'

borg: Exiting with failure status due to previous errors
```

**Comment by ThomasWaldmann** [comment]
oh, that seems to be some recent breakage (and not found by unit tests).

**Comment by anarcat** [comment]
ouch, my bad... this was pretty much the only place in this whole diff that wasn't tested, thanks to that hacking `__testsuite__:` URL stuff... i have tried to fix that tangled mess, but couldn't figure out a way to propagate an override to the ssh command down in the Archiver calls... oh well, sorry about that!
