### ISSUE TITLE
AssertionError: assert segments[segment] == 0

### ISSUE THREAD

**Issue by PhrozenByte** [borgbackup/borg#2567]
First of all: I :heart: Borg, absolutely amazing project, I'm using it on a daily basis for multiple devices and the stats are very impressive :+1:

I'm running `borg create` and `borg prune` (full commands below) on a daily basis for my home directory (`/home/daniel` is on my SSD, `/home/data` is the mountpoint of my HDD) of my Debian Jessie notebook (installed through the `borgbackup` package from Debian Jessie's repos, i.e. this is Borg 1.0.9).

Yesterday a random `AssertionError: assert segments[segment] == 0` appeared while running `borg prune` :

```
Keeping archive: Dell-Vostro-2017-05-24T10:13:44      Wed, 2017-05-24 10:13:45
Keeping archive: Dell-Vostro-2017-05-23T10:55:02      Tue, 2017-05-23 10:55:02
Keeping archive: Dell-Vostro-2017-05-22T09:04:52      Mon, 2017-05-22 09:04:53
Keeping archive: Dell-Vostro-2017-05-21T12:11:01      Sun, 2017-05-21 12:11:02
Keeping archive: Dell-Vostro-2017-05-20T09:17:55      Sat, 2017-05-20 09:17:57
Keeping archive: Dell-Vostro-2017-05-19T09:33:32      Fri, 2017-05-19 09:33:33
Keeping archive: Dell-Vostro-2017-05-18T11:49:43      Thu, 2017-05-18 11:49:47
Keeping archive: Dell-Vostro-2017-05-17T10:03:14      Wed, 2017-05-17 10:03:13
Keeping archive: Dell-Vostro-2017-05-16T23:37:36      Tue, 2017-05-16 23:37:37
Keeping archive: Dell-Vostro-2017-05-13T11:32:49      Sat, 2017-05-13 11:32:49
Keeping archive: Dell-Vostro-2017-05-12T09:48:25      Fri, 2017-05-12 09:48:25
Keeping archive: Dell-Vostro-2017-05-11T10:14:28      Thu, 2017-05-11 10:14:29
Keeping archive: Dell-Vostro-2017-05-10T12:03:34      Wed, 2017-05-10 12:03:34
Keeping archive: Dell-Vostro-2017-05-09T09:45:14      Tue, 2017-05-09 09:45:14
Keeping archive: Dell-Vostro-2017-05-07T12:25:27      Sun, 2017-05-07 12:25:27
Keeping archive: Dell-Vostro-2017-04-30T13:12:07      Sun, 2017-04-30 13:12:08
Keeping archive: Dell-Vostro-2017-04-23T12:15:55      Sun, 2017-04-23 12:15:56
Keeping archive: Dell-Vostro-2017-04-15T12:15:24      Sat, 2017-04-15 12:15:24
Keeping archive: Dell-Vostro-2017-04-09T11:54:26      Sun, 2017-04-09 11:54:27
Keeping archive: Dell-Vostro-2017-04-02T11:14:29      Sun, 2017-04-02 11:14:29
Keeping archive: Dell-Vostro-2017-03-31T09:02:29      Fri, 2017-03-31 09:23:25
Keeping archive: Dell-Vostro-2017-03-26T12:39:41      Sun, 2017-03-26 12:39:41
Keeping archive: Dell-Vostro-2017-03-19T12:02:40      Sun, 2017-03-19 12:24:18
Keeping archive: Dell-Vostro-2017-03-12T11:57:31      Sun, 2017-03-12 12:24:03
Keeping archive: Dell-Vostro-2017-03-05T12:08:58      Sun, 2017-03-05 12:31:45
Keeping archive: Dell-Vostro-2017-02-28T12:43:30      Tue, 2017-02-28 12:43:38
Keeping archive: Dell-Vostro-2017-02-26T08:01:58      Sun, 2017-02-26 08:01:59
Keeping archive: Dell-Vostro-2017-02-16T10:12:20      Thu, 2017-02-16 10:12:21
Keeping archive: Dell-Vostro-2017-02-12T11:30:52      Sun, 2017-02-12 13:25:58
Keeping archive: Dell-Vostro-2017-02-05T12:02:56      Sun, 2017-02-05 12:02:58
Keeping archive: Dell-Vostro-2017-01-31T08:05:02      Tue, 2017-01-31 08:05:03
Keeping archive: Dell-Vostro-2017-01-29T12:34:09      Sun, 2017-01-29 12:34:08
Keeping archive: Dell-Vostro-2017-01-22T12:02:30      Sun, 2017-01-22 12:02:31
Keeping archive: Dell-Vostro-2017-01-15T12:32:57      Sun, 2017-01-15 12:32:58
Keeping archive: Dell-Vostro-2017-01-08T12:05:05      Sun, 2017-01-08 12:41:11
Keeping archive: Dell-Vostro-2017-01-01T11:31:17      Sun, 2017-01-01 11:31:17
Keeping archive: Dell-Vostro-2016-12-31T12:02:02      Sat, 2016-12-31 12:02:03
Keeping archive: Dell-Vostro-2016-12-25T12:44:52      Sun, 2016-12-25 12:44:53
Keeping archive: Dell-Vostro-2016-12-18T13:11:31      Sun, 2016-12-18 13:11:31
Keeping archive: Dell-Vostro-2016-12-11T13:59:16      Sun, 2016-12-11 13:59:17
Keeping archive: Dell-Vostro-2016-12-04T12:39:50      Sun, 2016-12-04 12:39:50
Keeping archive: Dell-Vostro-2016-11-30T08:11:25      Wed, 2016-11-30 08:11:25
Keeping archive: Dell-Vostro-2016-11-27T12:50:06      Sun, 2016-11-27 12:50:07
Keeping archive: Dell-Vostro-2016-11-20T12:33:00      Sun, 2016-11-20 12:33:01
Keeping archive: Dell-Vostro-2016-11-13T16:06:08      Sun, 2016-11-13 16:06:09
Pruning archive: Dell-Vostro-2017-05-08T18:27:15      Mon, 2017-05-08 18:27:16
Pruning archive: Dell-Vostro-2016-11-06T15:56:18      Sun, 2016-11-06 15:56:18
Local Exception.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 2052, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1997, in run
    return func(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 90, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 717, in do_prune
    repository.commit(save_space=args.save_space)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 200, in commit
    self.compact_segments(save_space=save_space)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 353, in compact_segments
    assert segments[segment] == 0
AssertionError

Platform: Linux Dell-Vostro 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64
Linux: debian 8.8
Borg: 1.0.9  Python: CPython 3.4.2
PID: 22040  CWD: /home/daniel
sys.argv: ['/usr/bin/borg', 'prune', '-v', '--list', '/home/daniel/Backup/Borg', '--prefix', '{hostname}-', '--keep-within=2d', '--keep-daily=12', '--keep-weekly=26', '--keep-monthly=24', '--keep-yearly=10']
SSH_ORIGINAL_COMMAND: None
```

This is the output of `borg create` run right before `borg prune`:

``` 
------------------------------------------------------------------------------
Archive name: Dell-Vostro-2017-05-24T10:13:44
Archive fingerprint: 93e79d22154b2f1fc7ebdd3c6571767cd41715e40fba504c4e964662c2c56f92
Time (start): Wed, 2017-05-24 10:13:45
Time (end):   Wed, 2017-05-24 10:17:25
Duration: 3 minutes 39.68 seconds
Number of files: 353495
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               50.92 GB             40.87 GB             65.36 MB
All archives:                2.04 TB              1.65 TB             58.76 GB

                       Unique chunks         Total chunks
Chunk index:                  369068             17501818
------------------------------------------------------------------------------
```

I repeated the `borg prune` command, what *didn't* make the `AssertionError` show up again, so I moved on. Unfortunately I don't have the output of it anymore, but there were no errors and the messages looked fine, it just took longer than usual.

Today the (probably same) `AssertionError` appeared while running `borg create` (`borg create` obviously returned a non-zero status code, so my shell script didn't run `borg prune` afterwards):

```
Local Exception.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 2052, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1997, in run
    return func(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 90, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 305, in do_create
    create_inner(archive, cache)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 280, in create_inner
    archive.save(timestamp=args.timestamp)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 333, in save
    self.repository.commit()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 200, in commit
    self.compact_segments(save_space=save_space)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 353, in compact_segments
    assert segments[segment] == 0
AssertionError

Platform: Linux Dell-Vostro 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64
Linux: debian 8.8
Borg: 1.0.9  Python: CPython 3.4.2
PID: 3254  CWD: /home/daniel
sys.argv: ['/usr/bin/borg', 'create', '-v', '--stats', '--compression', 'lzma', '--exclude-caches', '--one-file-system', '/home/daniel/Backup/Borg::{hostname}-{now:%Y-%m-%dT%H:%M:%S}', '/home/daniel', '/home/data', '--exclude', '/home/daniel/.cache', '--exclude', '/home/daniel/.icedove/*/ImapMail', '--exclude', '/home/daniel/.local/share/Trash', '--exclude', '/home/daniel/.PlayOnLinux', '--exclude', '/home/daniel/.thumbnails', '--exclude', '/home/data/.cache', '--exclude', '/home/data/.Trash*', '--exclude', '/home/data/lost+found', '--exclude', '/home/data/Backup', '--exclude', '/home/data/Dropbox', '--exclude', '/home/data/JDownloader', '--exclude', '/home/data/ownCloud', '--exclude', '/home/data/Steam', '--exclude', '/home/data/Videos', '--exclude', '/home/data/VirtualBox']
SSH_ORIGINAL_COMMAND: None
```

`borg list` still works fine:

```
Dell-Vostro-2016-11-13T16:06:08      Sun, 2016-11-13 16:06:09
Dell-Vostro-2016-11-20T12:33:00      Sun, 2016-11-20 12:33:01
Dell-Vostro-2016-11-27T12:50:06      Sun, 2016-11-27 12:50:07
Dell-Vostro-2016-11-30T08:11:25      Wed, 2016-11-30 08:11:25
Dell-Vostro-2016-12-04T12:39:50      Sun, 2016-12-04 12:39:50
Dell-Vostro-2016-12-11T13:59:16      Sun, 2016-12-11 13:59:17
Dell-Vostro-2016-12-18T13:11:31      Sun, 2016-12-18 13:11:31
Dell-Vostro-2016-12-25T12:44:52      Sun, 2016-12-25 12:44:53
Dell-Vostro-2016-12-31T12:02:02      Sat, 2016-12-31 12:02:03
Dell-Vostro-2017-01-01T11:31:17      Sun, 2017-01-01 11:31:17
Dell-Vostro-2017-01-08T12:05:05      Sun, 2017-01-08 12:41:11
Dell-Vostro-2017-01-15T12:32:57      Sun, 2017-01-15 12:32:58
Dell-Vostro-2017-01-22T12:02:30      Sun, 2017-01-22 12:02:31
Dell-Vostro-2017-01-29T12:34:09      Sun, 2017-01-29 12:34:08
Dell-Vostro-2017-01-31T08:05:02      Tue, 2017-01-31 08:05:03
Dell-Vostro-2017-02-05T12:02:56      Sun, 2017-02-05 12:02:58
Dell-Vostro-2017-02-12T11:30:52      Sun, 2017-02-12 13:25:58
Dell-Vostro-2017-02-16T10:12:20      Thu, 2017-02-16 10:12:21
Dell-Vostro-2017-02-26T08:01:58      Sun, 2017-02-26 08:01:59
Dell-Vostro-2017-02-28T12:43:30      Tue, 2017-02-28 12:43:38
Dell-Vostro-2017-03-05T12:08:58      Sun, 2017-03-05 12:31:45
Dell-Vostro-2017-03-12T11:57:31      Sun, 2017-03-12 12:24:03
Dell-Vostro-2017-03-19T12:02:40      Sun, 2017-03-19 12:24:18
Dell-Vostro-2017-03-26T12:39:41      Sun, 2017-03-26 12:39:41
Dell-Vostro-2017-03-28T11:03:04.checkpoint Tue, 2017-03-28 11:03:05
Dell-Vostro-2017-03-31T09:02:29      Fri, 2017-03-31 09:23:25
Dell-Vostro-2017-04-02T11:14:29      Sun, 2017-04-02 11:14:29
Dell-Vostro-2017-04-09T11:54:26      Sun, 2017-04-09 11:54:27
Dell-Vostro-2017-04-15T12:15:24      Sat, 2017-04-15 12:15:24
Dell-Vostro-2017-04-16T10:29:51.checkpoint Sun, 2017-04-16 10:29:52
Dell-Vostro-2017-04-23T12:15:55      Sun, 2017-04-23 12:15:56
Dell-Vostro-2017-04-30T13:12:07      Sun, 2017-04-30 13:12:08
Dell-Vostro-2017-05-07T12:25:27      Sun, 2017-05-07 12:25:27
Dell-Vostro-2017-05-09T09:45:14      Tue, 2017-05-09 09:45:14
Dell-Vostro-2017-05-10T12:03:34      Wed, 2017-05-10 12:03:34
Dell-Vostro-2017-05-11T10:14:28      Thu, 2017-05-11 10:14:29
Dell-Vostro-2017-05-12T09:48:25      Fri, 2017-05-12 09:48:25
Dell-Vostro-2017-05-13T11:32:49      Sat, 2017-05-13 11:32:49
Dell-Vostro-2017-05-16T23:37:36      Tue, 2017-05-16 23:37:37
Dell-Vostro-2017-05-17T10:03:14      Wed, 2017-05-17 10:03:13
Dell-Vostro-2017-05-18T11:49:43      Thu, 2017-05-18 11:49:47
Dell-Vostro-2017-05-19T09:33:32      Fri, 2017-05-19 09:33:33
Dell-Vostro-2017-05-20T09:17:55      Sat, 2017-05-20 09:17:57
Dell-Vostro-2017-05-21T12:11:01      Sun, 2017-05-21 12:11:02
Dell-Vostro-2017-05-22T09:04:52      Mon, 2017-05-22 09:04:53
Dell-Vostro-2017-05-23T10:55:02      Tue, 2017-05-23 10:55:02
Dell-Vostro-2017-05-24T10:13:44      Wed, 2017-05-24 10:13:45
Dell-Vostro-2017-05-25T11:48:46      Thu, 2017-05-25 11:48:47
```

I tried running `borg check`, this is the result:

```
Index mismatch for key b'\xe8\xdaR(:r\x84\xe5\n\xc6\xa9B\x90\xdf\xf95T\xdaz\x87\x04\xe8\x9fy\xfa\x1b\xab<\x19\xb5\xaf~'. (28, 943192) != (-1, -1)
Completed repository check, errors found.
```

I didn't run `borg check --repair` yet, I wanted to open this issue first and wait what you guys are telling me to do next.

**Comment by enkore** [comment]
Does running `borg check` another time give the exact same error, or does it produce a different error?

General guidance (WIP): http://borgbackup.readthedocs.io/en/latest/faq.html#i-get-an-integrityerror-or-similar-what-now

**Comment by PhrozenByte** [comment]
Yes @enkore, running `borg check` yields the same error again:

```
Index mismatch for key b'\xe8\xdaR(:r\x84\xe5\n\xc6\xa9B\x90\xdf\xf95T\xdaz\x87\x04\xe8\x9fy\xfa\x1b\xab<\x19\xb5\xaf~'. (28, 943192) != (-1, -1)
Completed repository check, errors found.
```

I tried running `fsck -f`, no errors. I also executed `smartctl` and checked the mentioned attributes, all values are `0` (`Reported_Uncorrect` doesn't exist). Neither `/var/log/syslog` nor `dmesg` show up anything suspicious.

**Comment by enkore** [comment]
Ok. Both of these errors will be typically caused by some minor data corruption. The assertion error (perhaps I should change that one to have a message) is caused when a reference count (stored on disk) does not match the other data on the disk. This specific kind of index mismatch means that a key was corrupted in the on-disk index.

I'd wager that a `borg check --repair --repository-only` will fix these. Run `borg check` after that to ensure that no archives have been damaged.

**Comment by PhrozenByte** [comment]
Ok, I made a backup of the Borg repo and tried to run `borg check --repair --repository-only`, what seemed to work.

As instructed, I executed `borg check` afterwards. The segment check went to 100% and after that simply nothing happened - the "progress bar" disappeared and `borg check` consumed 100% of one CPU core for about 1,5 hours. Is this expected behavior (I wasn't sure, as said I've created a backup and can re-run it)? After terminating `borg check` using Ctrl + c the output looks as follows:

```
^CKeyboard interrupt.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 2052, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1997, in run
    return func(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 90, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 172, in do_check
    last=args.last, prefix=args.prefix, save_space=args.save_space):
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 865, in check
    self.rebuild_refcounts(archive=archive, last=last, prefix=prefix)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 1132, in rebuild_refcounts
    verify_file_chunks(item)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 993, in verify_file_chunks
    for chunk_current, chunk_healthy in zip(chunks_current, chunks_healthy):
  File "/usr/lib/python3/dist-packages/borg/helpers.py", line 1290, in handler
    raise exc_cls
KeyboardInterrupt

Platform: Linux Dell-Vostro 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 
Linux: debian 8.8 
Borg: 1.0.9  Python: CPython 3.4.2
PID: 9624  CWD: /home/daniel
sys.argv: ['/usr/bin/borg', 'check', '/home/daniel/Backup/Borg/']
SSH_ORIGINAL_COMMAND: None
```

**Comment by enkore** [comment]
In 1.0.x the second stage of check doesn't have a progress display per se. It prints some stuff with `-v`, though.

**Comment by PhrozenByte** [comment]
> In 1.0.x

I assume that this means I don't have to suggest adding a progress indicator 😆 😃 

---

I tried it again and curiously enough with `-v` it was *way* faster. After just 25 minutes (for all stages) it had finished (see output below). So there might be another problem that just didn't show up the second time I tried running `borg check`? 😕 

```
Starting repository check
Completed repository check, no problems found.
Starting archive consistency check...
Analyzing archive Dell-Vostro-2017-05-25T11:48:46 (48/48)
Analyzing archive Dell-Vostro-2017-05-24T10:13:44 (47/48)
Analyzing archive Dell-Vostro-2017-05-23T10:55:02 (46/48)
Analyzing archive Dell-Vostro-2017-05-22T09:04:52 (45/48)
Analyzing archive Dell-Vostro-2017-05-21T12:11:01 (44/48)
Analyzing archive Dell-Vostro-2017-05-20T09:17:55 (43/48)
Analyzing archive Dell-Vostro-2017-05-19T09:33:32 (42/48)
Analyzing archive Dell-Vostro-2017-05-18T11:49:43 (41/48)
Analyzing archive Dell-Vostro-2017-05-17T10:03:14 (40/48)
Analyzing archive Dell-Vostro-2017-05-16T23:37:36 (39/48)
Analyzing archive Dell-Vostro-2017-05-13T11:32:49 (38/48)
Analyzing archive Dell-Vostro-2017-05-12T09:48:25 (37/48)
Analyzing archive Dell-Vostro-2017-05-11T10:14:28 (36/48)
Analyzing archive Dell-Vostro-2017-05-10T12:03:34 (35/48)
Analyzing archive Dell-Vostro-2017-05-09T09:45:14 (34/48)
Analyzing archive Dell-Vostro-2017-05-07T12:25:27 (33/48)
Analyzing archive Dell-Vostro-2017-04-30T13:12:07 (32/48)
Analyzing archive Dell-Vostro-2017-04-23T12:15:55 (31/48)
Analyzing archive Dell-Vostro-2017-04-16T10:29:51.checkpoint (30/48)
Analyzing archive Dell-Vostro-2017-04-15T12:15:24 (29/48)
Analyzing archive Dell-Vostro-2017-04-09T11:54:26 (28/48)
Analyzing archive Dell-Vostro-2017-04-02T11:14:29 (27/48)
Analyzing archive Dell-Vostro-2017-03-31T09:02:29 (26/48)
Analyzing archive Dell-Vostro-2017-03-28T11:03:04.checkpoint (25/48)
Analyzing archive Dell-Vostro-2017-03-26T12:39:41 (24/48)
Analyzing archive Dell-Vostro-2017-03-19T12:02:40 (23/48)
Analyzing archive Dell-Vostro-2017-03-12T11:57:31 (22/48)
Analyzing archive Dell-Vostro-2017-03-05T12:08:58 (21/48)
Analyzing archive Dell-Vostro-2017-02-28T12:43:30 (20/48)
Analyzing archive Dell-Vostro-2017-02-26T08:01:58 (19/48)
Analyzing archive Dell-Vostro-2017-02-16T10:12:20 (18/48)
Analyzing archive Dell-Vostro-2017-02-12T11:30:52 (17/48)
Analyzing archive Dell-Vostro-2017-02-05T12:02:56 (16/48)
Analyzing archive Dell-Vostro-2017-01-31T08:05:02 (15/48)
Analyzing archive Dell-Vostro-2017-01-29T12:34:09 (14/48)
Analyzing archive Dell-Vostro-2017-01-22T12:02:30 (13/48)
Analyzing archive Dell-Vostro-2017-01-15T12:32:57 (12/48)
Analyzing archive Dell-Vostro-2017-01-08T12:05:05 (11/48)
Analyzing archive Dell-Vostro-2017-01-01T11:31:17 (10/48)
Analyzing archive Dell-Vostro-2016-12-31T12:02:02 (9/48)
Analyzing archive Dell-Vostro-2016-12-25T12:44:52 (8/48)
Analyzing archive Dell-Vostro-2016-12-18T13:11:31 (7/48)
Analyzing archive Dell-Vostro-2016-12-11T13:59:16 (6/48)
Analyzing archive Dell-Vostro-2016-12-04T12:39:50 (5/48)
Analyzing archive Dell-Vostro-2016-11-30T08:11:25 (4/48)
Analyzing archive Dell-Vostro-2016-11-27T12:50:06 (3/48)
Analyzing archive Dell-Vostro-2016-11-20T12:33:00 (2/48)
Analyzing archive Dell-Vostro-2016-11-13T16:06:08 (1/48)
Archive consistency check complete, no problems found.
```

I did run my daily backup script (i.e. `borg create` and `borg prune`) afterwards, what worked just fine (`borg create` just needed to synchronize the chunks cache before). So nevertheless my Borg repo seems to be fixed now, biggest thanks for your help @enkore! 🎉 ❤️ 

Are there any (known) circumstances under which things like this can happen? So that I might prevent it from happening in the future again...

**Comment by enkore** [comment]
Not that I'm aware of. Things like pulling an active drive (removing power/data cable, bad cable, system crash etc.) don't corrupt data in a way that interests Borg. (In some constellations during testing I managed to corrupt the file system but that's a different story).

**Comment by PhrozenByte** [comment]
Ok, so maybe some sort of a random bit flip or something. I'll keep an eye on it and will get back to you when something similar happens again (hopefully not 😆). Thanks again @enkore! 👍
