### ISSUE TITLE
Confusing exception when passing invalid --keep-within interval

### ISSUE THREAD

**Issue by edgewood** [borgbackup/borg#2610]
I made some changes to my borg wrapper scripts which impacted how borg prune was called, and in the process stopped adding a timespan to "--keep-within" without really meaning to.  In my tests I got a very confusing exception that took me a few minutes to decode.
```
borg prune --info --stats --list --prefix projects=loghyr --keep-within 5 --keep-daily 30 --keep-weekly 26 --keep-monthly 60 borg@cantard.lan:/srv/borg/ephemeral
Local Exception.
Traceback (most recent call last):
  File "/home/backups/borg/venv/lib/python3.5/site-packages/borg/helpers.py", line 190, in prune_within
    hours = int(within[:-1]) * multiplier[within[-1]]
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/backups/borg/venv/lib/python3.5/site-packages/borg/archiver.py", line 2089, in main
    exit_code = archiver.run(args)
  File "/home/backups/borg/venv/lib/python3.5/site-packages/borg/archiver.py", line 2025, in run
    return func(args)
  File "/home/backups/borg/venv/lib/python3.5/site-packages/borg/archiver.py", line 91, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/home/backups/borg/venv/lib/python3.5/site-packages/borg/archiver.py", line 698, in do_prune
    keep += prune_within(archives, args.within)
  File "/home/backups/borg/venv/lib/python3.5/site-packages/borg/helpers.py", line 193, in prune_within
    raise argparse.ArgumentTypeError('Unable to parse --within option: "%s"' % within)
argparse.ArgumentTypeError: Unable to parse --within option: "5"
```
There's a hint at the problem in that last line of the stack trace (note, not the last line of the output), but it's not very explicit, and I missed it entirely for a minute or two.

I'd suggest "Invalid interval "5", expected one of ["d", ... ]" with no stacktrace, either by adding a custom argparse validator for WITHIN, or by more granular parsing of the argument in prune_within.

I'd be willing to take a shot at fixing this, especially if the custom argparse validator is the preferred solution (which I think it should be, to catch errors as early as possible).

Here's the end of the exception output for completeness:
```
Platform: Linux loghyr 3.2.0-120-generic #163-Ubuntu SMP Tue Dec 20 15:13:12 UTC 2016 i686 i686
Linux: Ubuntu 12.04 precise
Borg: 1.0.10  Python: CPython 3.5.2
PID: 2809  CWD: /home/backups
sys.argv: ['/home/backups/borg/venv/bin/borg', 'prune', '--info', '--stats', '--list', '--prefix',
'projects=loghyr', '--keep-within', '5', '--keep-daily', '30', '--keep-weekly', '26',
'--keep-monthly', '60', 'borg@cantard.lan:/srv/borg/ephemeral']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment]
Good idea. :)

**Comment by ThomasWaldmann** [comment]
@edgewood you're on it?

**Comment by edgewood** [comment]
Sorry for the delay, I had a conference last weekend that I had to prepare for last week. I have some spare time this week though, so yes, I'm on it.
