### ISSUE TITLE
Error listing directory when mounting repo created with Cygwin in Linux

### ISSUE THREAD

**Issue by realityexists** [borgbackup/borg#2770]
I created a borg repository with some archive on Windows 7 x64 (under Cygwin, borg 1.0.10, Python 3.6.1). I then copied this repository to a VM running Ubuntu 14.04 (borg 1.0.10, Python 3.4.3) and tried mounting it:
```
$ borg mount -f --debug :: borgmount
using builtin fallback logging configuration
TAM-verified manifest
mount data cache capacity: 4 chunks
Mounting filesystem
Initializing llfuse
Calling fuse_mount
fusermount: failed to open /etc/fuse.conf: Permission denied
Calling fuse_lowlevel_new
Calling fuse_set_signal_handlers
Calling fuse_session_add_chan
Calling fuse_session_loop
```

The mount itself succeeds (despite the "permission denied" error). I can see the archives and the top-level directory in each ("cygdrive") and can list that directory. However, running

    ls /tmp/borgmount/daily6/cygdrive/e
	
fails with
```
ls: reading directory /tmp/borgmount/daily6/cygdrive/e: Input/output error
total 0
```
borg mount shows this error:
```
handler raised exception, sending SIGTERM to self.
Exception after kill:
Traceback (most recent call last):
  File "handlers.pxi", line 433, in llfuse.capi.fuse_releasedir (src/llfuse/capi_linux.c:11577)
  File "handlers.pxi", line 434, in llfuse.capi.fuse_releasedir (src/llfuse/capi_linux.c:11532)
  File "/usr/lib/python3/dist-packages/llfuse/pyapi.py", line 462, in releasedir
    def releasedir(self, fh):
  File "/usr/lib/python3/dist-packages/borg/helpers.py", line 1313, in handler
    raise exc_cls
Exception after kill:
Traceback (most recent call last):
  File "handlers.pxi", line 406, in llfuse.capi.fuse_readdir (src/llfuse/capi_linux.c:11057)
  File "handlers.pxi", line 411, in llfuse.capi.fuse_readdir (src/llfuse/capi_linux.c:10961)
  File "misc.pxi", line 33, in llfuse.capi.fill_c_stat (src/llfuse/capi_linux.c:16231)
OverflowError: can't convert negative value to gid_t
```

**Comment by enkore** [comment]
Thanks for the detailed report. This bug was reported previously (#2674) and a fix will be released in 1.0.11.
