### ISSUE TITLE
"Permission denied" error when listing or extracting from repo mounted read-only

### ISSUE THREAD

**Issue by realityexists** [borgbackup/borg#2771]
borg 1.0.10. When running "borg list" or "borg extract" on a repo that has been mounted as read-only I get a "Permission denied" error (example below). I would expect such commands to work with read-only access to the repository - after all, I'm not asking borg to change anything. Practical use cases might be restoring from a network share to which the current user doesn't have access or from optical media, for example.
```
$ borg list
Failed to create/acquire the lock /mnt/hgfs/borgrepo/lock.exclusive ([Errno 13] Permission denied: '/mnt/hgfs/borgrepo/lock.exclusive').
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 2089, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 2025, in run
    return func(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 83, in wrapper
    with repository:
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 83, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 172, in open
    self.lock = Lock(os.path.join(path, 'lock'), exclusive, timeout=lock_wait).acquire()
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 268, in acquire
    with self._lock:
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 120, in __enter__
    return self.acquire()
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 143, in acquire
    raise LockFailed(self.path, str(err)) from None
borg.locking.LockFailed: Failed to create/acquire the lock /mnt/hgfs/borgrepo/lock.exclusive ([Errno 13] Permission denied: '/mnt/hgfs/borgrepo/lock.exclusive').

Platform: Linux ubuntu 3.13.0-39-generic #66-Ubuntu SMP Tue Oct 28 13:30:27 UTC 2014 x86_64 x86_64
Linux: Ubuntu 14.04 trusty
Borg: 1.0.10  Python: CPython 3.4.3
PID: 9911  CWD: /tmp
sys.argv: ['/usr/bin/borg', 'list']
SSH_ORIGINAL_COMMAND: None
```

**Comment by enkore** [comment]
See #1035

**Comment by ThomasWaldmann** [comment]
Added the stuff to #1035 and closing this as duplicate now.
