### ISSUE TITLE
Prune fills the disk and crashes

### ISSUE THREAD

**Issue by varac** [borgbackup/borg#2803]
```
--- ~ » borg prune -v --list --keep-within=7d --keep-weekly=4 --keep-monthly=6 ${BORG_REPO}                                                                                                                    Keeping archive: box_home_2017-07-05T12:17:42+02:00 Wed, 2017-07-05 12:17:45
Keeping archive: box_home_2017-06-30T12:17:13+02:00 Fri, 2017-06-30 12:17:15
Keeping archive: box_home_2017-06-29T12:17:13+02:00 Thu, 2017-06-29 12:17:15
Keeping archive: box_home_2017-06-24T12:17:04+02:00 Sat, 2017-06-24 12:17:07
Keeping archive: box_home_2017-06-17T12:17:27+02:00 Sat, 2017-06-17 12:17:29
Keeping archive: box_home_2017-06-09T12:17:03+02:00 Fri, 2017-06-09 12:17:05
Keeping archive: box_home_2017-04-22T12:17:46+02:00 Sat, 2017-04-22 12:17:48
Keeping archive: box_home_2017-03-31T12:17:01+02:00 Fri, 2017-03-31 12:17:03
Keeping archive: box_home_2017-02-27T12:17:00+01:00 Mon, 2017-02-27 12:17:02
Keeping archive: box_home_2017-01-31T12:17:59+01:00 Tue, 2017-01-31 12:18:03
Keeping archive: box_home_2016-12-28T12:17:12+01:00 Wed, 2016-12-28 12:17:15
Keeping archive: box_home_2016-11-30T12:17:28+01:00 Wed, 2016-11-30 12:17:31
Keeping archive: box_home_2016-10-29T12:17:50+02:00 Sat, 2016-10-29 12:17:52
Pruning archive: box_home_2017-06-28T12:17:13+02:00 Wed, 2017-06-28 12:17:15
Pruning archive: box_home_2017-06-26T12:17:13+02:00 Mon, 2017-06-26 12:17:14
Pruning archive: box_home_2017-06-23T12:17:04+02:00 Fri, 2017-06-23 12:17:06
Pruning archive: box_home_2017-06-22T12:17:04+02:00 Thu, 2017-06-22 12:17:06
Pruning archive: box_home_2017-06-21T12:17:04+02:00 Wed, 2017-06-21 12:17:07
Pruning archive: box_home_2017-06-20T12:17:04+02:00 Tue, 2017-06-20 12:17:07
Pruning archive: box_home_2017-06-19T12:17:06+02:00 Mon, 2017-06-19 12:17:08
Pruning archive: box_home_2017-06-16T12:17:27+02:00 Fri, 2017-06-16 12:17:29
Pruning archive: box_home_2017-06-15T12:17:27+02:00 Thu, 2017-06-15 12:17:30
Pruning archive: box_home_2017-06-14T12:17:03+02:00 Wed, 2017-06-14 12:17:05
Pruning archive: box_home_2017-06-13T12:17:03+02:00 Tue, 2017-06-13 12:17:05
Pruning archive: box_home_2017-06-08T12:17:09+02:00 Thu, 2017-06-08 12:17:11
Pruning archive: box_home_2017-06-07T12:25:18+02:00 Wed, 2017-06-07 12:25:20
Pruning archive: box_home_2017-06-06T11:27:57+02:00 Tue, 2017-06-06 11:27:59
Pruning archive: box_home_2017-04-21T12:17:01+02:00 Fri, 2017-04-21 12:17:04
Pruning archive: box_home_2017-04-19T12:17:01+02:00 Wed, 2017-04-19 12:17:03
Pruning archive: box_home_2017-04-18T12:17:59+02:00 Tue, 2017-04-18 12:18:02
Pruning archive: box_home_2017-04-15T12:17:59+02:00 Sat, 2017-04-15 12:18:01
Pruning archive: box_home_2017-04-13T12:17:41+02:00 Thu, 2017-04-13 12:17:43
Pruning archive: box_home_2017-04-12T12:17:41+02:00 Wed, 2017-04-12 12:17:43
Pruning archive: box_home_2017-04-11T12:17:41+02:00 Tue, 2017-04-11 12:17:43
Pruning archive: box_home_2017-04-10T12:17:41+02:00 Mon, 2017-04-10 12:17:43
Pruning archive: box_home_2017-04-09T12:17:41+02:00 Sun, 2017-04-09 12:17:43
Pruning archive: box_home_2017-04-07T12:17:41+02:00 Fri, 2017-04-07 12:17:43
Pruning archive: box_home_2017-04-06T12:17:41+02:00 Thu, 2017-04-06 12:17:43
Pruning archive: box_home_2017-04-05T12:17:41+02:00 Wed, 2017-04-05 12:17:43
Pruning archive: box_home_2017-04-04T12:17:45+02:00 Tue, 2017-04-04 12:17:47
Pruning archive: box_home_2017-04-03T12:17:45+02:00 Mon, 2017-04-03 12:17:47
Pruning archive: box_home_2017-03-30T12:17:12+02:00 Thu, 2017-03-30 12:17:15
Pruning archive: box_home_2017-03-29T12:17:12+02:00 Wed, 2017-03-29 12:17:20
Pruning archive: box_home_2017-03-28T12:17:53+02:00 Tue, 2017-03-28 12:17:55
Pruning archive: box_home_2017-03-27T12:17:02+02:00 Mon, 2017-03-27 12:17:04
Pruning archive: box_home_2017-03-26T12:17:26+02:00 Sun, 2017-03-26 12:17:28
Pruning archive: box_home_2017-03-24T12:17:26+01:00 Fri, 2017-03-24 12:17:28
Pruning archive: box_home_2017-03-17T12:17:45+01:00 Fri, 2017-03-17 12:17:49
Pruning archive: box_home_2017-03-10T12:17:15+01:00 Fri, 2017-03-10 12:17:18
Pruning archive: box_home_2017-03-05T12:17:09+01:00 Sun, 2017-03-05 12:17:11
Pruning archive: box_home_2017-02-24T12:17:03+01:00 Fri, 2017-02-24 12:17:11
Remote: Borg 1.0.7: exception in RPC call:
Remote: Traceback (most recent call last):
Remote:   File "/usr/lib/python3/dist-packages/borg/remote.py", line 98, in serve
Remote:     res = f(*args)
Remote:   File "/usr/lib/python3/dist-packages/borg/repository.py", line 200, in commit
Remote:     self.compact_segments(save_space=save_space)
Remote:   File "/usr/lib/python3/dist-packages/borg/repository.py", line 303, in compact_segments
Remote:     new_segment, offset = self.io.write_put(key, data, raise_full=save_space)
Remote:   File "/usr/lib/python3/dist-packages/borg/repository.py", line 789, in write_put
Remote:     fd.write(b''.join((crc, header, id, data)))
Remote: OSError: [Errno 28] No space left on deviceRemote: 
Remote: Platform: Linux attic 3.2.0-4-amd64 #1 SMP Debian 3.2.84-1 x86_64
Remote: Linux: debian 8.6 
Remote: Borg: 1.0.7  Python: CPython 3.4.2
Remote: PID: 1860  CWD: /srv/home/th
Remote: sys.argv: ['/usr/bin/borg', 'serve', '--umask=077', '--info']
Remote: SSH_ORIGINAL_COMMAND: None
Remote: 
('Remote Exception (see remote log for the traceback)', 'OSError')
Platform: Linux box 4.10.0-24-generic #28-Ubuntu SMP Wed Jun 14 08:14:34 UTC 2017 x86_64 x86_64
Linux: Ubuntu 17.04 zesty
Borg: 1.0.10  Python: CPython 3.5.3
PID: 20346  CWD: /home/varac
sys.argv: ['/usr/bin/borg', 'prune', '-v', '--list', '--keep-within=7d', '--keep-weekly=4', '--keep-monthly=6', 'ssh://th@kabel.netropol.de/home/th/backup/borg/box']
SSH_ORIGINAL_COMMAND: None


varac@store:~$ df -h /srv
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda3       99G   94G     0 100% /srv

```

I didn't prune backups in quite a while, and I didn't look on the remote server how much disk space was available before the pruning started. But it was a couple of GBs at least.

**Comment by varac** [comment]
After this, I freed 13GB on the remote server, ran borg prune again, and it was successful - but the free space was still 13GB. 
So afterall, borg prune removed quite some sets, but increased the used disk space, which is bad.

**Comment by ThomasWaldmann** [comment]
next time: `--save-space`

**Comment by ThomasWaldmann** [comment]
As this is documented and also "out of space" handling has already been improved a bit in 1.1, I am closing this.

**Comment by varac** [comment]
@ThomasWaldmann Thx, I was not aware of the `--save-space` option to borg prune.

**Comment by ThomasWaldmann** [comment]
Usually it is for the rather desparate cases where almost no space is free. It is slower than without that option because of the space saving.

Your issue was a bit unexpected, usually some GB free should work fine. But likely it wanted to compact a huge amount of segments (due to the big amount of pruned data), so it wasn't enough for the normal, speed optimized mode.
