### ISSUE TITLE
can't run tests offline

### ISSUE THREAD

**Issue by anarcat** [borgbackup/borg#284]
i was wanting to work offline and got this:

```
(borg)[1025]anarcat@angela:borg$ fakeroot -u tox -e py34
GLOB sdist-make: /home/anarcat/src/borg/setup.py
py34 inst-nodeps: /home/anarcat/src/borg/.tox/dist/borgbackup-0.27.1.dev71-ng1b5f3af.d20151015.zip
ERROR: invocation failed (exit code 1), logfile: /home/anarcat/src/borg/.tox/py34/log/py34-8.log
ERROR: actionid: py34
msg: installpkg
cmdargs: [local('/home/anarcat/src/borg/.tox/py34/bin/pip'), 'install', '-U', '--no-deps', '/home/anarcat/src/borg/.tox/dist/borgbackup-0.27.1.dev71-ng1b5f3af.d20151015.zip']
env: *CENSORED*
The directory '/home/anarcat/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/anarcat/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing ./.tox/dist/borgbackup-0.27.1.dev71-ng1b5f3af.d20151015.zip
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/setuptools_scm/: [Errno -2] Name or service not known -- Some packages may not be found!
    Download error on https://pypi.python.org/simple/setuptools-scm/: [Errno -2] Name or service not known -- Some packages may not be found!
    Couldn't find index page for 'setuptools_scm' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [Errno -2] Name or service not known -- Some packages may not be found!
    No local packages or download links found for setuptools-scm>=1.7
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-x_vmhovk-build/setup.py", line 292, in <module>
        install_requires=install_requires,
      File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/anarcat/src/borg/.tox/py34/lib/python3.4/site-packages/setuptools/dist.py", line 268, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/home/anarcat/src/borg/.tox/py34/lib/python3.4/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/anarcat/src/borg/.tox/py34/lib/python3.4/site-packages/pkg_resources/__init__.py", line 836, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/home/anarcat/src/borg/.tox/py34/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1081, in best_match
        return self.obtain(req, installer)
      File "/home/anarcat/src/borg/.tox/py34/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1093, in obtain
        return installer(requirement)
      File "/home/anarcat/src/borg/.tox/py34/lib/python3.4/site-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/anarcat/src/borg/.tox/py34/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 623, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools-scm>=1.7')

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-x_vmhovk-build

py34 installed: Attic==0.16,borgbackup===0.27.1.dev70-ng256f89e.d20151013,cov-core==1.15.0,coverage==3.7.1,Cython==0.23.4,mock==1.3.0,msgpack-python==0.4.6,pbr==1.8.1,pluggy==0.3.1,py==1.4.30,pytest==2.8.2,pytest-cov==1.8.1,six==1.10.0,tox==2.1.1,virtualenv==13.1.2,wheel==0.24.0
_________________________________ summary _________________________________
ERROR:   py34: InvocationError: /home/anarcat/src/borg/.tox/py34/bin/pip install -U --no-deps /home/anarcat/src/borg/.tox/dist/borgbackup-0.27.1.dev71-ng1b5f3af.d20151015.zip (see /home/anarcat/src/borg/.tox/py34/log/py34-8.log)
```

i could have sworn i setup my virtualenv and all the good stuff before leaving, but maybe I missed something?

is it by design that tox fetches those packages from scratch all the time?

**Comment by ThomasWaldmann** [comment]
There is a virtualenv used for development (I usually use ../borg-env).
tox creates multiple virtual envs (with different python versions) inside ".tox/".
They are usually kept between runs except one gives --recreate option to tox.
Maybe it just wants to check for updates? See -U.

**Comment by anarcat** [comment]
so i ran it with `--recreate`, turned off networking, and then ran it without `--recreate` again, and got this:

```
(borg)[984]anarcat@angela:borg$ fakeroot -u tox -e py34
GLOB sdist-make: /home/anarcat/src/borg/setup.py
py34 inst-nodeps: /home/anarcat/src/borg/.tox/dist/borgbackup-0.27.1.dev141-ng0397501.zip
ERROR: invocation failed (exit code 1), logfile: /home/anarcat/src/borg/.tox/py34/log/py34-3.log
ERROR: actionid: py34
msg: installpkg
cmdargs: [local('/home/anarcat/src/borg/.tox/py34/bin/pip'), 'install', '-U', '--no-deps', '/home/anarcat/src/borg/.tox/dist/borgbackup-0.27.1.dev141-ng0397501.zip']
env: {'CHESSDIR': '/home/anarcat/chess', 'GDM_LANG': 'en_CA.utf8', 'WINDOWID': '65011725', 'HISTSIZE': '-1', 'WORDCHARS': '*?_-.[]~=&;!#$%^(){}<>', 'SHLVL': '2', 'VIRTUALENVWRAPPER_HOOK_DIR': '/home/anarcat/.virtualenvs', 'DIRSTACKSIZE': '8', 'VIRTUAL_ENV': '/home/anarcat/src/borg/.tox/py34', 'XDG_GREETER_DATA_DIR': '/var/lib/lightdm/data/anarcat', 'DISPLAY': ':0', 'LD_PRELOAD': 'libfakeroot-sysv.so', 'XDG_VTNR': '7', 'VIRTUALENVWRAPPER_SCRIPT': '/usr/share/virtualenvwrapper/virtualenvwrapper.sh', 'SSH_AUTH_SOCK': '/tmp/ssh-dVpR900D8Vjw/agent.1798', 'GDMSESSION': 'xmonad', 'XDG_SESSION_ID': '1', 'FAKED_MODE': 'unknown-is-real', 'XTERM_LOCALE': 'fr_CA.UTF-8', 'TERM': 'xterm', '_VIRTUALENVWRAPPER_API': ' mkvirtualenv rmvirtualenv lsvirtualenv showvirtualenv workon add2virtualenv cdsitepackages cdvirtualenv lssitepackages toggleglobalsitepackages cpvirtualenv setvirtualenvproject mkproject cdproject mktmpenv', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'MPD_HOST': 'awaitBootHey@radio.orangeseeds.org', 'WORKON_HOME': '/home/anarcat/.virtualenvs', 'HOME': '/home/anarcat', 'IRCNAME': 'Anar-cat. Get it? Ah-ah.', 'DEBFULLNAME': 'Antoine Beaupré', '_': '/home/anarcat/.virtualenvs/borg/bin/tox', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0', 'XDG_SEAT': 'seat0', 'BLOCKSIZE': 'K', 'PWD': '/home/anarcat/src/borg', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-Ul7uPU0roM,guid=5342142bd52267fd3b92fefe5623b4af', 'USER': 'anarcat', 'LOGNAME': 'anarcat', 'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session0', 'HISTFILESIZE': '1001', 'XTERM_SHELL': '/bin/bash', 'SHELL': '/bin/bash', 'SAVEHIST': '-1', 'IRCSERVER': 'irc.koumbit.net', 'PYTHONHASHSEED': '3781570968', 'XTERM_VERSION': 'XTerm(312)', 'DEBEMAIL': 'anarcat@debian.org', 'PAGER': 'less', 'SSH_AGENT_PID': '1836', 'EDITOR': '/home/anarcat/bin/e', 'CVS_RSH': 'ssh', 'XDG_RUNTIME_DIR': '/run/user/1000', '_JAVA_AWT_WM_NONREPARENTING': '1', 'XAUTHORITY': '/home/anarcat/.Xauthority', 'FAKEROOTKEY': '1924716501', 'VIRTUALENVWRAPPER_PROJECT_FILENAME': '.project', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:', 'IRCNICK': 'anarcat', 'FTP_PASSIVE_MODE': 'yes', 'GPG_AGENT_INFO': '/tmp/gpg-MbxUlP/S.gpg-agent:1837:1', 'HISTFILE': '/home/anarcat/.history', 'LD_LIBRARY_PATH': '/usr/lib/x86_64-linux-gnu/libfakeroot:/usr/lib64/libfakeroot:/usr/lib32/libfakeroot', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'DESKTOP_SESSION': 'xmonad', 'GPG_TTY': '/dev/pts/3', 'LANG': 'fr_CA.UTF-8', 'PATH': '/home/anarcat/src/borg/.tox/py34/bin:/home/anarcat/.virtualenvs/borg/bin:/home/anarcat/bin:/home/anarcat/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/sbin:/usr/sbin:/sbin', 'HISTCONTROL': 'ignoreboth', 'LESS': '-MeiRXF'}

The directory '/home/anarcat/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/anarcat/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing ./.tox/dist/borgbackup-0.27.1.dev141-ng0397501.zip
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/setuptools_scm/: [Errno -2] Name or service not known -- Some packages may not be found!
    Download error on https://pypi.python.org/simple/setuptools-scm/: [Errno -2] Name or service not known -- Some packages may not be found!
    Couldn't find index page for 'setuptools_scm' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [Errno -2] Name or service not known -- Some packages may not be found!
    No local packages or download links found for setuptools-scm>=1.7
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-0xycc961-build/setup.py", line 298, in <module>
        install_requires=install_requires,
      File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/anarcat/src/borg/.tox/py34/lib/python3.4/site-packages/setuptools/dist.py", line 268, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/home/anarcat/src/borg/.tox/py34/lib/python3.4/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/anarcat/src/borg/.tox/py34/lib/python3.4/site-packages/pkg_resources/__init__.py", line 836, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/home/anarcat/src/borg/.tox/py34/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1081, in best_match
        return self.obtain(req, installer)
      File "/home/anarcat/src/borg/.tox/py34/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1093, in obtain
        return installer(requirement)
      File "/home/anarcat/src/borg/.tox/py34/lib/python3.4/site-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/anarcat/src/borg/.tox/py34/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 623, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools-scm>=1.7')

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-0xycc961-build

py34 installed: Attic==0.16,borgbackup===0.27.1.dev141-ng0397501,cov-core==1.15.0,coverage==3.7.1,Cython==0.23.4,mock==1.3.0,msgpack-python==0.4.6,pbr==1.8.1,pluggy==0.3.1,py==1.4.30,pytest==2.8.2,pytest-benchmark==3.0.0b1,pytest-cov==1.8.1,six==1.10.0,tox==2.1.1,virtualenv==13.1.2,wheel==0.24.0
_______________________________________________________________________ summary _______________________________________________________________________
ERROR:   py34: InvocationError: /home/anarcat/src/borg/.tox/py34/bin/pip install -U --no-deps /home/anarcat/src/borg/.tox/dist/borgbackup-0.27.1.dev141-ng0397501.zip (see /home/anarcat/src/borg/.tox/py34/log/py34-3.log)
```

so it does look like tox is running pip with `-U`... can we turn that darn thing off? :)

**Comment by ThomasWaldmann** [comment]
While I see this is an annoyance for working offline, I don't see anything within the borg project causing this (seems rather like a tox / pip problem).

Also, I think this could be solved by using "devpi" (not just for borg, but for all python development).
