### ISSUE TITLE
crash with 1.1.0b6 on borg create with --no-cache-sync

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2853]
```
Local Exception
Traceback (most recent call last):
  File "borg/archiver.py", line 4063, in main
  File "borg/archiver.py", line 3991, in run
  File "borg/archiver.py", line 146, in wrapper
  File "borg/archiver.py", line 514, in do_create
  File "borg/archiver.py", line 479, in create_inner
  File "borg/archiver.py", line 579, in _process
  File "borg/archiver.py", line 579, in _process
  File "borg/archiver.py", line 579, in _process
  File "borg/archiver.py", line 579, in _process
  File "borg/archiver.py", line 579, in _process
  File "borg/archiver.py", line 579, in _process
  File "borg/archiver.py", line 579, in _process
  File "borg/archiver.py", line 557, in _process
  File "borg/archive.py", line 990, in process_file
  File "borg/archive.py", line 936, in chunk_file
  File "borg/cache.py", line 1005, in chunk_incref
  File "borg/archive.py", line 61, in update
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'

Platform: Linux server 4.8.0-58-generic #63~16.04.1-Ubuntu SMP Mon Jun 26 18:08:51 UTC 2017 x86_64 x86_64
Linux: debian stretch/sid
Borg: 1.1.0b6  Python: CPython 3.5.3
PID: 27736  CWD: /usr/local/bin
sys.argv: ['borg-1.1', 'create', '-v', '--list', '--filter=AME', '--compression', 'auto,lzma,6',
 '--stats', '--no-cache-sync', '--chunker-params', '17,23,20,4095',
 'ssh://borg@server/./repo::myserver-2017-07-22-00:13:07', '/mnt/rootfs/',
 '--exclude-caches', ...]
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment]
re-started the failing backup with code from #2860 - worked!
