### ISSUE TITLE
get_cache_dir crashes with bad symlink

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2878]
```
# borg mount repo mnt
Local Exception
Traceback (most recent call last):
  File "/home/tw/w/borg/src/borg/archiver.py", line 3956, in main
    exit_code = archiver.run(args)
  File "/home/tw/w/borg/src/borg/archiver.py", line 3884, in run
    return set_ec(func(args))
  File "/home/tw/w/borg/src/borg/archiver.py", line 1285, in do_mount
    return self._do_mount(args)
  File "/home/tw/w/borg/src/borg/archiver.py", line 140, in wrapper
    assert_secure(repository, kwargs['manifest'])
  File "/home/tw/w/borg/src/borg/cache.py", line 196, in assert_secure
    sm = SecurityManager(repository)
  File "/home/tw/w/borg/src/borg/cache.py", line 62, in __init__
    self.cache_dir = cache_dir(repository)
  File "/home/tw/w/borg/src/borg/cache.py", line 217, in cache_dir
    return path or os.path.join(get_cache_dir(), repository.id_str)
  File "/home/tw/w/borg/src/borg/helpers.py", line 510, in get_cache_dir
    os.makedirs(cache_dir)
  File "/home/tw/w/borg-env/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/root/.cache/borg'

Platform: Linux tux 4.11.9-tw1 #4 SMP Sat Jul 8 05:48:55 CEST 2017 x86_64 x86_64
Linux: Ubuntu 16.04 xenial
Borg: 1.1.0rc2.dev1+gb85076d  Python: CPython 3.4.5
PID: 28369  CWD: /home/tw/w/borg
sys.argv: ['/home/tw/w/borg-env/bin/borg', 'mount', 'repo', 'mnt']
SSH_ORIGINAL_COMMAND: None

# ls -l /root/.cache/borg
lrwxrwxrwx 1 root root 16 Sep 15  2015 /root/.cache/borg -> /cache/root/borg
```

Note: target of symlink does not exist.

**Comment by ThomasWaldmann** [comment]
Maybe it is better if it crashes in this case and leaves the decision about how to fix the issue to the admin.
