### ISSUE TITLE
Invoking "borg serve" compares None with int in version 1.0.11

### ISSUE THREAD

**Issue by smariot** [borgbackup/borg#2910]
```
$LOG ERROR Remote: Local Exception.
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/borg/archiver.py", line 2168, in main
    exit_code = archiver.run(args)
  File "/usr/lib64/python3.4/site-packages/borg/archiver.py", line 2104, in run
    return set_ec(func(args))
  File "/usr/lib64/python3.4/site-packages/borg/helpers.py", line 85, in set_ec
    exit_code = max(exit_code, ec)
TypeError: unorderable types: NoneType() > int()

Platform: REDACTED
Linux: Gentoo Base System 2.3 
Borg: 1.0.11  Python: CPython 3.4.5
PID: 11348  CWD: /var/lib/borg
sys.argv: ['/usr/lib/python-exec/python3.4/borg', 'serve', '--append-only', '--restrict-to-path', '/var/lib/borg/REDACTED']
```

It looks like **Archiver.run** is calling **Archiver.do_serve**, which is expecting a return value from **RepositoryServer.serve**, but **RepositoryServer.serve** doesn't return anything.

The actual backup is completed successfully, prior to the exception being raised.

**Comment by ThomasWaldmann** [comment]
Strange, I do not see that error when doing a remote backup (ssh:) from borg 1.0.11 (src install) to 1.0.11 (pyinstaller binary).
