### ISSUE TITLE
timestamp microseconds parsing issue

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2994]
Spurious failure seen in a unrelated 1.1-maint PR on py 3.4:
```
.tox/py34/lib/python3.4/site-packages/borg/archiver.py:1232: in _delete_archives
    manifest.write()
.tox/py34/lib/python3.4/site-packages/borg/helpers.py:393: in write
    prev_ts = self.last_timestamp
.tox/py34/lib/python3.4/site-packages/borg/helpers.py:321: in last_timestamp
    return datetime.strptime(self.timestamp, "%Y-%m-%dT%H:%M:%S.%f")

E           ValueError: time data '2017-09-02T16:16:34' does not match format '%Y-%m-%dT%H:%M:%S.%f'
```

Suspicion: crappy standard formatting behaviour of stdlib to only add `.uuu` for the microsecs if microsecs != 0, which then causes complications when trying to parse that.

**Comment by ThomasWaldmann** [comment]
https://docs.python.org/3/library/datetime.html#datetime.datetime.isoformat

Always remember: .isoformat() is evil.

When we require py36+, we can use it with timespec=... (and everything else than evil "auto"), but until then, we must use .strftime() with some sane format that does not vary depending on the value of microseconds.

**Comment by codenox** [comment]
I have them same issue with 1.0.11

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/borg/archiver.py", line 2168, in main
    exit_code = archiver.run(args)
  File "/usr/local/lib/python3.5/dist-packages/borg/archiver.py", line 2104, in run
    return set_ec(func(args))
  File "/usr/local/lib/python3.5/dist-packages/borg/archiver.py", line 107, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/borg/archiver.py", line 331, in do_create
    create_inner(archive, cache)
  File "/usr/local/lib/python3.5/dist-packages/borg/archiver.py", line 306, in create_inner
    archive.save(timestamp=args.timestamp)
  File "/usr/local/lib/python3.5/dist-packages/borg/archive.py", line 333, in save
    self.manifest.write()
  File "/usr/local/lib/python3.5/dist-packages/borg/helpers.py", line 311, in write
    prev_ts = datetime.strptime(self.timestamp, "%Y-%m-%dT%H:%M:%S.%f")
  File "/usr/lib/python3.5/_strptime.py", line 510, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.5/_strptime.py", line 343, in _strptime
    (data_string, format))
ValueError: time data '2017-09-22T20:07:03' does not match format '%Y-%m-%dT%H:%M:%S.%f'
```

Linux: Ubuntu 16.04 xenial
Borg: 1.0.11  Python: CPython 3.5.2


No backups possible on my machine right now :(

**Comment by enkore** [comment]
Fix will be included in next bug fix release (#3023).

For a temporary workaround, you can edit the ".%f" out of this line, and add it back after doing one backup.

```
  File "/usr/local/lib/python3.5/dist-packages/borg/helpers.py", line 311, in write
    prev_ts = datetime.strptime(self.timestamp, "%Y-%m-%dT%H:%M:%S.%f")
                                                                  ^^^
```

**Comment by codenox** [comment]
Perfect. Worked like a charm. Thanks!

**Comment by LocutusOfBorg** [comment]
hello, just a question: why hasn't this being caught by the testsuite?

**Comment by LocutusOfBorg** [comment]
I'm asking because I want to push .12 to Ubuntu xenial
https://bugs.launchpad.net/ubuntu/+source/borgbackup/+bug/1788829

**Comment by ThomasWaldmann** [comment]
@LocutusOfBorg likely because it only fails with a 1:1.000.000 probability.

**Comment by LocutusOfBorg** [comment]
lol ok :)
