### ISSUE TITLE
make html crashes (master)

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#3010]
```
(borg-env) tw@tux:~/w/borg/docs$ make clean
rm -rf _build/*

(borg-env) tw@tux:~/w/borg/docs$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.4.9
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 43 source files that are out of date
updating environment: 43 added, 0 changed, 0 removed
reading sources... [100%] usage/upgrade                                                                                 
usage/benchmark_crud.rst.inc:73: ERROR: Unexpected indentation.
usage_general.rst.inc:361: WARNING: duplicate label platforms, other instance in /home/tw/w/borg/docs/man_intro.rst
usage_general.rst.inc:125: WARNING: duplicate label env_vars, other instance in /home/tw/w/borg/docs/man_intro.rst
usage_general.rst.inc:223: WARNING: duplicate label file-systems, other instance in /home/tw/w/borg/docs/man_intro.rst
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/tw/w/borg/docs/book.rst:: WARNING: document isn't included in any toctree
/home/tw/w/borg/docs/man_intro.rst:: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [ 23%] index                                                                                          
Exception occurred:
  File "/home/tw/w/borg-env/lib/python3.5/site-packages/docutils/writers/_html_base.py", line 671, in depart_document
    assert not self.context, 'len(context) = %s' % len(self.context)
AssertionError: len(context) = 1
The full traceback has been saved in /tmp/sphinx-err-ek1twlc8.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:40: recipe for target 'html' failed
make: *** [html] Error 1
```

**Comment by ThomasWaldmann** [comment]
```
(borg-env) tw@tux:~/w/borg/docs$ cat /tmp/sphinx-err-ek1twlc8.log
# Sphinx version: 1.4.9
# Python version: 3.5.2 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.6
# Last messages:
#   writing output... [  2%] authors
#   writing output... [  4%] book
#   writing output... [  6%] changes
#   writing output... [  9%] deployment
#   writing output... [ 11%] deployment/automated-local
#   writing output... [ 13%] deployment/central-backup-server
#   writing output... [ 16%] deployment/hosting-repositories
#   writing output... [ 18%] development
#   writing output... [ 20%] faq
#   writing output... [ 23%] index
# Loaded extensions:
#   sphinx.ext.todo (1.4.9) from /home/tw/w/borg-env/lib/python3.5/site-packages/sphinx/ext/todo.py
#   sphinx.ext.coverage (1.4.9) from /home/tw/w/borg-env/lib/python3.5/site-packages/sphinx/ext/coverage.py
#   sphinx.ext.autodoc (1.4.9) from /home/tw/w/borg-env/lib/python3.5/site-packages/sphinx/ext/autodoc.py
#   sphinx.ext.viewcode (1.4.9) from /home/tw/w/borg-env/lib/python3.5/site-packages/sphinx/ext/viewcode.py
#   sphinx.ext.extlinks (1.4.9) from /home/tw/w/borg-env/lib/python3.5/site-packages/sphinx/ext/extlinks.py
#   alabaster (0.7.10) from /home/tw/w/borg-env/lib/python3.5/site-packages/alabaster/__init__.py
Traceback (most recent call last):
  File "/home/tw/w/borg-env/lib/python3.5/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/home/tw/w/borg-env/lib/python3.5/site-packages/sphinx/application.py", line 297, in build
    self.builder.build_update()
  File "/home/tw/w/borg-env/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/home/tw/w/borg-env/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/tw/w/borg-env/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 360, in write
    self._write_serial(sorted(docnames), warnings)
  File "/home/tw/w/borg-env/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 368, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/tw/w/borg-env/lib/python3.5/site-packages/sphinx/builders/html.py", line 448, in write_doc
    self.docwriter.write(doctree, destination)
  File "/home/tw/w/borg-env/lib/python3.5/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/home/tw/w/borg-env/lib/python3.5/site-packages/sphinx/writers/html.py", line 47, in translate
    self.document.walkabout(visitor)
  File "/home/tw/w/borg-env/lib/python3.5/site-packages/docutils/nodes.py", line 187, in walkabout
    visitor.dispatch_departure(self)
  File "/home/tw/w/borg-env/lib/python3.5/site-packages/docutils/nodes.py", line 1895, in dispatch_departure
    return method(node)
  File "/home/tw/w/borg-env/lib/python3.5/site-packages/docutils/writers/_html_base.py", line 671, in depart_document
    assert not self.context, 'len(context) = %s' % len(self.context)
AssertionError: len(context) = 1
```

**Comment by enkore** [comment]
Works fine with 1.5.3 (used by me and readthedocs)

**Comment by ThomasWaldmann** [comment]
hmm, guess that 1.4.9 was a relict of an experiment, usually I have latest.
