### ISSUE TITLE
Archive lost after one-byte change to data.

### ISSUE THREAD

**Issue by dseomn** [borgbackup/borg#3030]
After making a one-byte change to data from one of my archives, I lose the entire archive. The commands I ran are below, and the output from both `get-obj` calls is in [manifest.zip](https://github.com/borgbackup/borg/files/1304930/manifest.zip).

```
# ~/.local/bin/borg -V
borg 1.0.11
# cp -a /tmp/tmp.BwIGMQH0FT/dev/in-progress.2017-09-14T22\:09\:35Z/repos/borg/chusuk-root test
# ~/.local/bin/borg list test
static-chusuk-root-files-2017-09-05T19:53:31Z Wed, 2017-09-13 23:44:08
static-chusuk-root-dpkgselections-2017-09-05T19:53:31Z Wed, 2017-09-13 23:44:09
# ~/.local/bin/borg debug get-obj test 0000000000000000000000000000000000000000000000000000000000000000 test.manifest.pre-change
object 0000000000000000000000000000000000000000000000000000000000000000 fetched.
# sed -i 's/acpi-support/bcpi-support/' test/data/0/2
# ~/.local/bin/borg debug get-obj test 0000000000000000000000000000000000000000000000000000000000000000 test.manifest.post-change
object 0000000000000000000000000000000000000000000000000000000000000000 fetched.
# ~/.local/bin/borg list test
static-chusuk-root-files-2017-09-05T19:53:31Z Wed, 2017-09-13 23:44:08
```

**Comment by dseomn** [comment]
As discussed on IRC, the repository was created append-only.

**Comment by ThomasWaldmann** [comment]
```
borg-env) tw@tux:~/w/borg$ borg init -e none repo

(borg-env) tw@tux:~/w/borg$ echo foobar > xxx
(borg-env) tw@tux:~/w/borg$ borg create -C none repo::1 xxx

(borg-env) tw@tux:~/w/borg$ sed -i 's/foobar/foobaz/' repo/data/0/2 

(borg-env) tw@tux:~/w/borg$ borg list repo
Inconsistency detected. Please run "borg check /home/tw/w/borg/repo" - although likely this is "beyond repair".
Traceback (most recent call last):
  File "/home/tw/w/borg/borg/archiver.py", line 2172, in main
    exit_code = archiver.run(args)
  File "/home/tw/w/borg/borg/archiver.py", line 2108, in run
    return set_ec(func(args))
  File "/home/tw/w/borg/borg/archiver.py", line 101, in wrapper
    kwargs['manifest'], kwargs['key'] = Manifest.load(repository, compatibility)
  File "/home/tw/w/borg/borg/helpers.py", line 253, in load
    cdata = repository.get(cls.MANIFEST_ID)
  File "/home/tw/w/borg/borg/repository.py", line 528, in get
    self.index = self.open_index(self.get_transaction_id())
  File "/home/tw/w/borg/borg/repository.py", line 159, in get_transaction_id
    raise self.CheckNeeded(msg)
borg.repository.Repository.CheckNeeded: Inconsistency detected. Please run "borg check /home/tw/w/borg/repo" - although likely this is "beyond repair".

Platform: Linux tux 4.12.10-tw1 #1 SMP Sun Sep 3 06:56:01 CEST 2017 x86_64 x86_64
Linux: Ubuntu 16.04 xenial
Borg: 1.0.12.dev29+gf45f9fc  Python: CPython 3.5.2
PID: 19356  CWD: /home/tw/w/borg
sys.argv: ['/home/tw/w/borg-env/bin/borg', 'list', 'repo']
SSH_ORIGINAL_COMMAND: None

(borg-env) tw@tux:~/w/borg$ borg check --repair repo
'check --repair' is an experimental feature that might result in data loss.
Type 'YES' if you understand this and want to continue: YES
Data integrity error: Segment entry checksum mismatch [segment 2, offset 8]
Adding commit tag to segment 2
xxx: New missing file chunk detected (Byte 0-7). Replacing with all-zero chunk.
Archive consistency check complete, problems found.

(borg-env) tw@tux:~/w/borg$ borg list repo
1                                    Fri, 2017-09-15 02:57:35

(borg-env) tw@tux:~/w/borg$ borg create -C none repo::2 xxx

(borg-env) tw@tux:~/w/borg$ borg check --repair repo
'check --repair' is an experimental feature that might result in data loss.
Type 'YES' if you understand this and want to continue: YES
# should have invoked with -v to get the "healed" INFO msg

(borg-env) tw@tux:~/w/borg$ borg list repo
1                                    Fri, 2017-09-15 02:57:35
2                                    Fri, 2017-09-15 03:17:40

(borg-env) tw@tux:~/w/borg$ borg extract repo::1

(borg-env) tw@tux:~/w/borg$ cat xxx 
foobar
```

**Comment by ThomasWaldmann** [comment]
If there are multiple commits, I guess it would find a previous commit (one before the corrupted segment) and that explains the issue in the original post.

**Comment by ThomasWaldmann** [comment]
```
(borg-env) tw@tux:~/w/borg$ borg init -e none repo
(borg-env) tw@tux:~/w/borg$ vim repo/config   # append_only = 1
(borg-env) tw@tux:~/w/borg$ borg create -C none repo::1 xxx
(borg-env) tw@tux:~/w/borg$ borg create -C none repo::2 yyy
(borg-env) tw@tux:~/w/borg$ sed -i 's/blabla/blublu/' repo/data/0/2
(borg-env) tw@tux:~/w/borg$ borg list repo
1                                    Fri, 2017-09-15 03:52:30

(borg-env) tw@tux:~/w/borg$ vim repo/config   # append_only = 0
(borg-env) tw@tux:~/w/borg$ borg check --repair repo
'check --repair' is an experimental feature that might result in data loss.
Type 'YES' if you understand this and want to continue: YES
Local Exception.        
Traceback (most recent call last):
  File "/home/tw/w/borg/borg/archiver.py", line 1684, in main
    exit_code = archiver.run(args)
  File "/home/tw/w/borg/borg/archiver.py", line 1621, in run
    return args.func(args)
  File "/home/tw/w/borg/borg/archiver.py", line 85, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/home/tw/w/borg/borg/archiver.py", line 148, in do_check
    if not repository.check(repair=args.repair, save_space=args.save_space):
  File "/home/tw/w/borg/borg/repository.py", line 478, in check
    self.write_index()
  File "/home/tw/w/borg/borg/repository.py", line 252, in write_index
    assert transaction_id is not None
AssertionError

Platform: Linux tux 4.12.10-tw1 #1 SMP Sun Sep 3 06:56:01 CEST 2017 x86_64 x86_64
Linux: Ubuntu 16.04 xenial
Borg: 1.0.7  Python: CPython 3.5.2
PID: 20568  CWD: /home/tw/w/borg
sys.argv: ['/home/tw/w/borg-env/bin/borg', 'check', '--repair', 'repo']
SSH_ORIGINAL_COMMAND: None

(borg-env) tw@tux:~/w/borg$ borg check --repair repo
'check --repair' is an experimental feature that might result in data loss.
Type 'YES' if you understand this and want to continue: YES

(borg-env) tw@tux:~/w/borg$ borg list repo
1                                    Fri, 2017-09-15 03:52:30
```
Seems like archive 2 is gone...

**Comment by ThomasWaldmann** [comment]
```
(borg-env) tw@tux:~/w/borg$ git checkout 1.0.11
(borg-env) tw@tux:~/w/borg$ pip install -e .
(borg-env) tw@tux:~/w/borg$ borg init -e none repo
(borg-env) tw@tux:~/w/borg$ vim repo/config   # append_only = 1
(borg-env) tw@tux:~/w/borg$ borg create -C none repo::1 xxx
(borg-env) tw@tux:~/w/borg$ borg create -C none repo::2 yyy
(borg-env) tw@tux:~/w/borg$ grep blabla repo/data/0/2
Binary file repo/data/0/2 matches
(borg-env) tw@tux:~/w/borg$ sed -i 's/blabla/blublu/' repo/data/0/2
(borg-env) tw@tux:~/w/borg$ borg list repo
1                                    Fri, 2017-09-15 04:03:36
(borg-env) tw@tux:~/w/borg$ vim repo/config   # append_only = 0
(borg-env) tw@tux:~/w/borg$ borg check --repair repo
'check --repair' is an experimental feature that might result in data loss.
Type 'YES' if you understand this and want to continue: YES
Local Exception.        
Traceback (most recent call last):
  File "/home/tw/w/borg/borg/archiver.py", line 2168, in main
    exit_code = archiver.run(args)
  File "/home/tw/w/borg/borg/archiver.py", line 2104, in run
    return set_ec(func(args))
  File "/home/tw/w/borg/borg/archiver.py", line 107, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/home/tw/w/borg/borg/archiver.py", line 185, in do_check
    if not repository.check(repair=args.repair, save_space=args.save_space):
  File "/home/tw/w/borg/borg/repository.py", line 488, in check
    self.write_index()
  File "/home/tw/w/borg/borg/repository.py", line 259, in write_index
    assert transaction_id is not None
AssertionError

Platform: Linux tux 4.12.10-tw1 #1 SMP Sun Sep 3 06:56:01 CEST 2017 x86_64 x86_64
Linux: Ubuntu 16.04 xenial
Borg: 1.0.11  Python: CPython 3.5.2
PID: 20813  CWD: /home/tw/w/borg
sys.argv: ['/home/tw/w/borg-env/bin/borg', 'check', '--repair', 'repo']
SSH_ORIGINAL_COMMAND: None

(borg-env) tw@tux:~/w/borg$ borg check --repair repo
'check --repair' is an experimental feature that might result in data loss.
Type 'YES' if you understand this and want to continue: YES
(borg-env) tw@tux:~/w/borg$ borg list repo
1                                    Fri, 2017-09-15 04:03:36
```
Same for 1.0.11.

**Comment by ThomasWaldmann** [comment]
Idea: use code like in `recover_segment` for `is_committed_segment`, not raising `IntegrityError`, but just trying to re-sync to the next valid object?

**Comment by ThomasWaldmann** [comment]
I suspect this is a borg < 1.1 only issue.

Since 1.1, borg writes the final (non-intermediate) commit to a separate file, thus it won't iterate over non-commit segment entries in `is_committed_segment` and can't stumble over corrupted data in PUT/DEL entries (as there are none).

**Comment by ThomasWaldmann** [comment]
Using borg 1.2-maint code:
```
(borg-env) tw@mba2020 borg % borg init -e none repo-issue3030
(borg-env) tw@mba2020 borg % echo foobar > xxx
(borg-env) tw@mba2020 borg % borg create -C none repo-issue3030::arch xxx
(borg-env) tw@mba2020 borg % grep -r foobar repo-issue3030/data 
Binary file repo-issue3030/data/0/2 matches
(borg-env) tw@mba2020 borg % sed -i xxx 's/foobar/foobaz/' repo-issue3030/data/0/2
(borg-env) tw@mba2020 borg % grep -r foobar repo-issue3030/data               
Binary file repo-issue3030/data/0/2xxx matches
(borg-env) tw@mba2020 borg % rm repo-issue3030/data/0/2xxx
(borg-env) tw@mba2020 borg % borg list repo-issue3030 
arch                                 Mon, 2022-06-13 20:03:53 [eda8bff911600a34dc0ae810cdb5bd5e2e8cbcfcb6bfef6f563c83ffcee935ca]
(borg-env) tw@mba2020 borg % borg check --repair repo-issue3030
This is a potentially dangerous function.
check --repair might lead to data loss (for kinds of corruption it is not
capable of dealing with). BE VERY CAREFUL!

Type 'YES' if you understand this and want to continue: YES
Data integrity error: Segment entry checksum mismatch [segment 2, offset 8]
arch: xxx: New missing file chunk detected (Byte 0-7, Chunk aec070645fe53ee3b3763059376134f058cc337247c978add178b6ccdfb0019f). Replacing with all-zero chunk.
Archive consistency check complete, problems found.
(borg-env) tw@mba2020 borg % borg check --repair repo-issue3030
This is a potentially dangerous function.
check --repair might lead to data loss (for kinds of corruption it is not
capable of dealing with). BE VERY CAREFUL!

Type 'YES' if you understand this and want to continue: YES
(borg-env) tw@mba2020 borg % borg list repo-issue3030          
arch                                 Mon, 2022-06-13 20:03:53 [480a0d5bb7bda8b930976e41a1ad57c8ff2e51e4482e9d54c3b2771a29dbc2d8]
(borg-env) tw@mba2020 borg % borg list repo-issue3030::arch
-rw-r--r-- tw     staff         7 Mon, 2022-06-13 20:03:31 xxx
(borg-env) tw@mba2020 borg % borg extract repo-issue3030::arch
xxx: File has damaged (all-zero) chunks. Try running borg check --repair.
```

So, the crash does not happen any more, it "repairs" the file with an all-zero replacement chunk and it warns when extracting a file that has a replacement chunk.

This is as good as it gets, closing this as fixed.
