### ISSUE TITLE
py35 test failure on wheezy64

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#3066]
```
==> wheezy64: ============ 1257 passed, 115 skipped, 3 xpassed in 517.28 seconds =============

^^^ py 3.4

==> wheezy64: py35 create: /vagrant/borg/borg/.tox/py35
==> wheezy64: py35 installdeps: -rrequirements.d/development.txt, -rrequirements.d/fuse.txt
==> wheezy64: py35 inst: /vagrant/borg/borg/.tox/dist/borgbackup-1.1.0rc4.dev27+g248117d.zip
==> wheezy64: py35 installed: The directory '/home/vagrant/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.,apipkg==1.4,borgbackup==1.1.0rc4.dev27+g248117d,coverage==4.4.1,Cython==0.27,execnet==1.4.1,llfuse==1.3,msgpack-python==0.4.8,pluggy==0.5.2,py==1.4.34,py-cpuinfo==3.3.0,pytest==3.2.2,pytest-benchmark==3.1.1,pytest-cov==2.5.1,pytest-forked==0.2,pytest-xdist==1.20.0,setuptools-scm==1.15.6,tox==2.8.2,virtualenv==15.1.0
==> wheezy64: py35 runtests: PYTHONHASHSEED='3395329449'
==> wheezy64: py35 runtests: commands[0] | py.test -n 4 -rs --cov=borg --cov-config=.coveragerc --benchmark-skip --pyargs borg.testsuite
==> wheezy64: Traceback (most recent call last):
==> wheezy64:   File "/vagrant/borg/borg/.tox/py35/lib/python3.5/site-packages/_pytest/config.py", line 342, in _getconftestmodules
==> wheezy64:     return self._path2confmods[path]
==> wheezy64: KeyError: local('/vagrant/borg/borg')
==> wheezy64: 
==> wheezy64: During handling of the above exception, another exception occurred:
==> wheezy64: Traceback (most recent call last):
==> wheezy64:   File "/vagrant/borg/borg/.tox/py35/lib/python3.5/site-packages/_pytest/config.py", line 373, in _importconftest
==> wheezy64:     return self._conftestpath2mod[conftestpath]
==> wheezy64: KeyError: local('/vagrant/borg/borg/conftest.py')
==> wheezy64: 
==> wheezy64: During handling of the above exception, another exception occurred:
==> wheezy64: Traceback (most recent call last):
==> wheezy64:   File "/vagrant/borg/borg/.tox/py35/lib/python3.5/site-packages/_pytest/config.py", line 379, in _importconftest
==> wheezy64:     mod = conftestpath.pyimport()
==> wheezy64:   File "/vagrant/borg/borg/.tox/py35/lib/python3.5/site-packages/py/_path/local.py", line 662, in pyimport
==> wheezy64:     __import__(modname)
==> wheezy64:   File "/vagrant/borg/borg/.tox/py35/lib/python3.5/site-packages/_pytest/assertion/rewrite.py", line 212, in load_module
==> wheezy64:     py.builtin.exec_(co, mod.__dict__)
==> wheezy64:   File "/vagrant/borg/borg/conftest.py", line 18, in <module>
==> wheezy64:     import borg.cache
==> wheezy64:   File "/vagrant/borg/borg/.tox/py35/lib/python3.5/site-packages/borg/cache.py", line 16, in <module>
==> wheezy64:     from .hashindex import ChunkIndex, ChunkIndexEntry, CacheSynchronizer
==> wheezy64: ImportError: /vagrant/borg/borg/.tox/py35/lib/python3.5/site-packages/borg/hashindex.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _PyThreadState_UncheckedGet
==> wheezy64: ERROR: could not load /vagrant/borg/borg/conftest.py
==> wheezy64: ERROR: InvocationError: '/vagrant/borg/borg/.tox/py35/bin/py.test -n 4 -rs --cov=borg --cov-config=.coveragerc --benchmark-skip --pyargs borg.testsuite'
```

**Comment by ThomasWaldmann** [comment]
undefined symbol: _PyThreadState_UncheckedGet !?

**Comment by ThomasWaldmann** [comment]
https://github.com/pyenv/pyenv/issues/989

**Comment by ThomasWaldmann** [comment]
Maybe this is due to a change in Cython, it now generates code like this:
```
#if !CYTHON_FAST_THREAD_STATE || PY_VERSION_HEX < 0x02070000
  #define __Pyx_PyThreadState_Current PyThreadState_GET()
#elif PY_VERSION_HEX >= 0x03050200
  #define __Pyx_PyThreadState_Current _PyThreadState_UncheckedGet()
#elif PY_VERSION_HEX >= 0x03000000
  #define __Pyx_PyThreadState_Current PyThreadState_Get()
#else
  #define __Pyx_PyThreadState_Current _PyThreadState_Current
#endif
```

**Comment by ThomasWaldmann** [comment]
Suspicion:
do object files get generated with py 3.5.4 get picked up by the tox run with py 3.5.0?

**Comment by ThomasWaldmann** [comment]
https://github.com/cython/cython/issues/1880

Cython issue in 0.27 release. There is a 0.27.1b1 with the fix.

**Comment by ThomasWaldmann** [comment]
Workaround: requirements.d/development.txt: Cython!=0.27
