### ISSUE TITLE
borg crash during create (AssertionError: bug in code, exclusive lock should exist here)

### ISSUE THREAD

**Issue by FabioPedretti** [borgbackup/borg#3082]
Getting this error, apparently after working on a big (137 GB) file.

Note: I recently deleted the cache, moved it to a different disk (previous one was full) creating a symlink and run again all my borg create. Most create went OK, this one crashed with the following error.

Using borg 1.0.11, official 64 bit binary file downloaded from borg github.
Using updated Debian 9.

```
Exception ignored in: <bound method Repository.__del__ of <Repository /mnt/sshfs/borg_repository>>
Traceback (most recent call last):
  File "borg/repository.py", line 73, in __del__
  File "borg/repository.py", line 199, in close
  File "borg/locking.py", line 298, in release
  File "borg/locking.py", line 216, in modify
KeyError: (('borg', 6833, 0),)
Local Exception.
Traceback (most recent call last):
  File "borg/archiver.py", line 331, in do_create
  File "borg/archiver.py", line 304, in create_inner
  File "borg/archiver.py", line 380, in _process
  File "borg/archiver.py", line 380, in _process
  File "borg/archiver.py", line 380, in _process
  File "borg/archiver.py", line 380, in _process
  File "borg/archiver.py", line 380, in _process
  File "borg/archiver.py", line 380, in _process
  File "borg/archiver.py", line 361, in _process
  File "borg/archive.py", line 722, in process_file
  File "borg/archive.py", line 295, in add_item
  File "borg/archive.py", line 301, in write_checkpoint
  File "borg/cache.py", line 480, in chunk_decref
  File "borg/repository.py", line 552, in delete
  File "borg/repository.py", line 224, in prepare_txn
AssertionError: bug in code, exclusive lock should exist here

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "borg/archiver.py", line 107, in wrapper
  File "borg/archiver.py", line 331, in do_create
  File "borg/cache.py", line 113, in __exit__
  File "borg/cache.py", line 197, in close
  File "borg/locking.py", line 298, in release
  File "borg/locking.py", line 216, in modify
KeyError: ('borg', 6833, 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "borg/archiver.py", line 2168, in main
  File "borg/archiver.py", line 2104, in run
  File "borg/archiver.py", line 107, in wrapper
  File "borg/repository.py", line 95, in __exit__
  File "borg/repository.py", line 199, in close
  File "borg/locking.py", line 298, in release
  File "borg/locking.py", line 216, in modify
KeyError: ('borg', 6833, 0)

Platform: Linux borg 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64
Linux: debian 9.1
Borg: 1.0.11  Python: CPython 3.5.3
PID: 6833  CWD: /net/10.128.132.17/root_vdm_1/share01
sys.argv: ['borg', 'create', '-v', '--stats', '--show-rc', '--noatime', '-C', 'lzma', '::STORAGE-2017-10-02', 'AMM', 'AULE', 'DIP']
SSH_ORIGINAL_COMMAND: None

terminating with error status, rc 2
```

**Comment by ThomasWaldmann** [comment]
Looks a bit like it wanted to release a lock that was not there. Did you use `borg break-lock`?

**Comment by FabioPedretti** [comment]
Yes, I may have used `borg break-lock` in the previous run, but likely not the one where I got the crash.

**Comment by ThomasWaldmann** [comment]
And the sshfs mount where the repo resides in was still there, the ssh connection still working when this happened?

**Comment by ThomasWaldmann** [comment]
Hmm, had a look into the source, but it seems sane:
- write_checkpoint does save(), which does a repo commit
- last op in repo commit() is rollback(), which resets repo._active_txn to False
- write_checkpoint does cache.chunk_decref, which starts a new cache transaction, if needed and deletes the checkpoint archive object from the repo.
- repo.delete notices there is no active repo transaction and tries to start one (prepare_txn())
- prepare_txn then checks whether we have an exclusive lock (repo/lock.exclusive/hostname.pid-0 file must exist for our host and our pid)

Looks like the lock.exclusive path or hostname.pid-0 file in there was not there / not visible?

**Comment by FabioPedretti** [comment]
Hi, indeed I was debugging a couple issues, the first being the sshfs disk which kept the repo was not reachable sometime. At a first I thought the remote server was being restarted, now I just add a ssh ServerAliveInterval, hopefully that should keep the server always reachable (even when borg is locally processing a big file and not accessing the disk, so likely reaching the ssh timeout).

The second issue was that sometimes the repo is locked when I expected it not to be (e.g. after mounting and unmounting it). To workaround this I add in my script a "pgrep borg" and if borg is not running I force a break-lock before starting the prune + create. Hopefully the stale locking issue should be better managed in 1.1 in a similar way directly by the borg binary (BORG_HOSTNAME_IS_UNIQUE is default to yes).

So it might be indeed an issue related to the sshfs repo not being available or the use of break-lock, which should hopefully be fixed in my environment with the two workaround I explained.

I also tried making again a backup of the whole disk (including the big file) and this time it went OK.

So if the code is OK and this is not an issue, this can be closed, given that also the stale lock problem should already be managed in 1.1. If you need more info let me know.

Anyway thanks for your time and for developing this great tool!

**Comment by ThomasWaldmann** [comment]
OK, thanks for the info, closing...
