### ISSUE TITLE
Borg crashes due to "Error: hashindex: .cache/borg/$id/chunks: Incorrect file length"

### ISSUE THREAD

**Issue by module0x90** [borgbackup/borg#3140]
Hi,

I just want to run something quickly by you. I noticed that borg backup is crashing and just now I was finally able to find the cause for that:
```
Error: hashindex: /root/.cache/borg/$id/chunks: Incorrect file length (expected 188818054, got 58720256) Local Exception.
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 2168, in main exit_code = archiver.run(args) File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 2104, in run return set_ec(func(args))
File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 107, in wrapper return method(self, args, repository=repository, **kwargs) 
File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 325, in do_create with Cache(repository, key, manifest, do_files=args.cache_files, lock_wait=self.lock_wait) as cache: 
File "/usr/lib/python3.6/site-packages/borg/cache.py", line 73, in __init__ self.open(lock_wait=lock_wait) 
File "/usr/lib/python3.6/site-packages/borg/cache.py", line 193, in open self.rollback() 
File "/usr/lib/python3.6/site-packages/borg/cache.py", line 277, in rollback self._do_open() 
File "/usr/lib/python3.6/site-packages/borg/cache.py", line 186, in _do_open self.chunks = ChunkIndex.read(os.path.join(self.path, 'chunks').encode('utf-8')) 
File "borg/hashindex.pyx", line 79, in borg.hashindex.IndexBase.read 
File "borg/hashindex.pyx", line 67, in borg.hashindex.IndexBase.__cinit__
Exception: hashindex_read failed Platform: Linux blackhole 4.13.3-1-ARCH #1 SMP PREEMPT Thu Sep 21 20:33:16 CEST 2017 x86_64 
Linux: arch Borg: 1.0.11 Python: CPython 3.6.2
PID: 4263 CWD: /root sys.argv: ['/usr/bin/borg', 'create', '--stats', '--compression', 'none', '/mnt/Backup/borgbackup-repository::firewall-{now:%Y%m%d%H%M%S}', '/home/tomtom/mnt/firewall/conf/config.xml'] SSH_ORIGINAL_COMMAND: None
Fatal: Failed backuping up source
```
I am still on Borg 1.0.11. Is there a way to fix this file (I checked previous backups, the file is there but with yet another filesize), or is it just a matter of rm -rf the borg-cache and start afresh - and take the time penalty that the first backup takes longer?
This (central) server is pulling borg backups from 4 others (including itself).

Cheers

Thomas

**Comment by enkore** [comment]
borg delete --cache-only, or manually remove .cache/borg/$id directory.

**Comment by module0x90** [comment]
Thanks, working again.
October 11, 2017 12:36 PM, "enkore"  wrote:
	borg delete --cache-only, or manually remove .cache/borg/$id directory.
