### ISSUE TITLE
[cygwin] Borg 1.1.0 - ValueError: Location: parse failed

### ISSUE THREAD

**Issue by theChaosCoder** [borgbackup/borg#3141]
Seems like a cache and/or file:// path problem:

Steps:
`borg init  file:////synology/Backups/test/ -e none`

`borg info  file:////synology/Backups/test/`

```
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4024, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 3952, in run
    return set_ec(func(args))
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 141, in wrapper
    assert_secure(repository, kwargs['manifest'])
  File "/usr/lib/python3.6/site-packages/borg/cache.py", line 199, in assert_secure
    sm.assert_secure(manifest, manifest.key)
  File "/usr/lib/python3.6/site-packages/borg/cache.py", line 164, in assert_secure
    with cache_config:
  File "/usr/lib/python3.6/site-packages/borg/cache.py", line 231, in __enter__
    self.open()
  File "/usr/lib/python3.6/site-packages/borg/cache.py", line 255, in open
    self.load()
  File "/usr/lib/python3.6/site-packages/borg/cache.py", line 283, in load
    self.previous_location = recanonicalize_relative_location(previous_location, self.repository)
  File "/usr/lib/python3.6/site-packages/borg/cache.py", line 205, in recanonicalize_relative_location
    rl = Location(repo_location)
  File "/usr/lib/python3.6/site-packages/borg/helpers.py", line 1035, in __init__
    raise ValueError('Location: parse failed: %s' % self.orig)
ValueError: Location: parse failed: //synology/Backups/test

Platform: CYGWIN_NT-10.0 Chaos-PC 2.9.0(0.318/5/3) 2017-09-12 10:18 x86_64
Borg: 1.1.0  Python: CPython 3.6.1
PID: 12284  CWD: /home/anato
sys.argv: ['/usr/bin/borg', 'info', 'file:////synology/test/']
SSH_ORIGINAL_COMMAND: None
```

Then I remove the borg cache folder in home and the borg info command runs fine, but only once! The second time the same error is shown.

I happens only with file://... 
/cygdrive/e/test is OK.

I also noticed that borg complains about a **//synology** as  a archive-path , but NOT on --exclude-from or as a source folder wich I want to backup.

See also https://github.com/borgbackup/borg/issues/2186

**Comment by ThomasWaldmann** [comment]
Just mount the stuff instead of using unc path //server/share?

**Comment by theChaosCoder** [comment]
That is what I'm doing right now. 

But I think it is an error. Also the path check is not consistent between archive path, source path and exclude-from path.

**Comment by ThomasWaldmann** [comment]
Hmm, did this work in 1.0.x, but stopped working in 1.1.0?

**Comment by theChaosCoder** [comment]
I think it stopped working with borg 1.0.10. I used 1.0.9 until now :)

**Comment by ThomasWaldmann** [comment]
https://tools.ietf.org/html/rfc8089 looks like it took until 2017 to even write this mess down as a RFC.

**Comment by ThomasWaldmann** [comment]
Just as a minor update to my comment "Most times when the regex was touched, something else broke...
":

The regex got a bit simpler in master branch (in borg 2.0):
- `repo::archive` location (borg 1.x) was split into separate arguments for the repo and for the archive
-  scp syntax was dropped, which also helps a bit against bad matches

**Comment by ThomasWaldmann** [comment]
Checked this against current master (borg 2):

- The crash from the original report is gone. `file:////server/share/path` parses fine now and a full `repo-create` / `create` / `repo-info` / `list` round trip works, including the cache / security dir handling that blew up in 1.1. The regex simplification in borg 2 fixed that on its own.
- What is still not accepted is the bare `//server/share/path` form. Making it parse would be a small change: drop the `//` alternative from `local_path_re`, allow `//` in `abs_path_re` on Windows, and stop using `Path.as_uri()` for UNC paths (pathlib puts the server into the URL *authority* part - `file://server/share/path` - which borgstore's posixfs backend rejects, it only supports an empty host part).

But the parsing is the easy half, and it is not the half I am worried about.

The risky part is UNC semantics, and we can't verify those: `fcntl`/flock behaviour over SMB (that is what borgstore's posixfs locking relies on), atomic rename, fsync, and mtime granularity for the staleness / clock-skew checks. If any of that silently misbehaves on a network share, the failure mode is a repository that is corrupted or stuck locked - not a friendly parse error. CI can't cover a real UNC share either, so any tests we could add would only exercise the parser and would give a false sense of coverage for exactly the part that matters.

Also, on Linux and macOS a leading `//` is just `/`, so the feature would only ever mean something on Windows/cygwin - a very small target for that risk. Meanwhile there are workarounds that keep borg on a path whose semantics it can rely on (map a drive letter with `net use`, or a cygwin symlink, both mentioned above), and borg 2 has real network backends (sftp, s3, b2, rclone) for the "repository is not on local storage" case.

So: closing as not planned. If someone wants to pick it up anyway, the parser part is a few lines, but the burden of proof is on the locking / rename / fsync behaviour over SMB, not on the regex.
