### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by haslinger** [borgbackup/borg#3179]
In case you see an error message like this: 

```
borg.archiver Remote: Local Exception
borg.archiver Remote: Traceback (most recent call last):
Remote:   File "/home/stefan/.local/lib/python3.5/site-packages/borg/archiver.py", line 4024, in main
Remote:     exit_code = archiver.run(args)
Remote:   File "/home/stefan/.local/lib/python3.5/site-packages/borg/archiver.py", line 3952, in run
Remote:     return set_ec(func(args))
Remote:   File "/home/stefan/.local/lib/python3.5/site-packages/borg/archiver.py", line 238, in do_serve
Remote:     storage_quota=args.storage_quota,
Remote:   File "/home/stefan/.local/lib/python3.5/site-packages/borg/remote.py", line 227, in serve
Remote:     args = self.positional_to_named(method, args)
Remote:   File "/home/stefan/.local/lib/python3.5/site-packages/borg/remote.py", line 183, in positional_to_named
Remote:     return {name: argv[pos] for pos, name in enumerate(compatMap[method])}
Remote:   File "/home/stefan/.local/lib/python3.5/site-packages/borg/remote.py", line 183, in <dictcomp>
Remote:     return {name: argv[pos] for pos, name in enumerate(compatMap[method])}
Remote: IndexError: tuple index out of range
Remote: 
Remote: Platform: Linux nas.vorgarten.stefan-haslinger.at 4.4.0-1075-raspi2 #83-Ubuntu SMP Wed Sep 20 08:10:32 UTC 2017 armv7l armv7l
Remote: Linux: Ubuntu 16.04 xenial
Remote: Borg: 1.1.0  Python: CPython 3.5.2
Remote: PID: 29664  CWD: /home/stefan
Remote: sys.argv: ['/usr/local/bin/borg', 'serve', '--umask=077']
Remote: SSH_ORIGINAL_COMMAND: None
Remote: 
Connection closed by remote host 
```
you are probably running an old version of borgbackup on your clients, as I did. So, do upgrade!

I thought, I just leave the issue here for reference ;-)

**Comment by enkore** [comment]
For reference: What was the old version?

**Comment by haslinger** [comment]
I try to remember the string and believe it was 1.0.0-pre, but I don't see this in releases, so probably 1.0.0rc2
