### ISSUE TITLE
crash with relative BORG_KEY_FILE

### ISSUE THREAD

**Issue by kbabioch** [borgbackup/borg#3197]
Hi,

I'm backing up into multiple repositories, but I want to use a single keyfile for all of them. However I don't see a way to generate a keyfile with borg itself:

    [kbabioch@antares ~]$ BORG_KEY_FILE=keyfile borg init -e keyfile repo
    Enter new passphrase: 
    Enter same passphrase again: 
    Do you want your passphrase to be displayed for verification? [yN]: 
    Local Exception
    Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4024, in main
        exit_code = archiver.run(args)
      File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 3952, in run
        return set_ec(func(args))
      File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 148, in wrapper
        return method(self, args, repository=repository, **kwargs)
      File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 248, in do_init
        key = key_creator(repository, args)
      File "/usr/lib/python3.6/site-packages/borg/crypto/key.py", line 106, in key_creator
        return key.create(repository, args)
      File "/usr/lib/python3.6/site-packages/borg/crypto/key.py", line 657, in create
        key.save(target, passphrase)
      File "/usr/lib/python3.6/site-packages/borg/crypto/key.py", line 728, in save
        fd.write('\n')
      File "/usr/lib/python3.6/site-packages/borg/platform/base.py", line 175, in __exit__
        platform.sync_dir(os.path.dirname(self.path))
      File "/usr/lib/python3.6/site-packages/borg/platform/base.py", line 56, in sync_dir
        fd = os.open(path, os.O_RDONLY)
    FileNotFoundError: [Errno 2] No such file or directory: ''

    Platform: Linux antares 4.13.7-1-ARCH #1 SMP PREEMPT Sat Oct 14 20:13:26 CEST 2017 x86_64 
    Linux: arch Arch Linux
    Borg: 1.1.0  Python: CPython 3.6.2
    PID: 25811  CWD: /home/kbabioch
    sys.argv: ['/usr/bin/borg', 'init', '-e', 'keyfile', 'repo']
    SSH_ORIGINAL_COMMAND: None

I think either the use case mentioned above should work, or there should be some "borg --genkey" option, e.g. as with `openvpn(8)`.

**Comment by ThomasWaldmann** [comment]
So, your intention was to use an existing keyfile located in `./keyfile` to initialize a new repo in keyfile mode?

**Comment by kbabioch** [comment]
No, I want to create a new repo with a new keyfile at the given location (rather than using borg's internal logic to put keys somewhere within `.config/borg/keys`).

**Comment by ThomasWaldmann** [comment]
A general comment about using same key for different repos:

AES-CTR mode encryption is only secure if counter values are not repeated. If you use the same key for multiple independent repos, you can not be sure to avoid that.

**Comment by ThomasWaldmann** [comment]
TODO: check if borg init honors the env var.

**Comment by ThomasWaldmann** [comment]
Using an absolute path works.

**Comment by kbabioch** [comment]
Ok, thank you very much. Your explanation makes sense, so I won't do this and have to deal with multiple keys. Thanks for your fast fix.
