### ISSUE TITLE
Borg mount and utf-8 strings

### ISSUE THREAD

**Issue by jlorieau** [borgbackup/borg#3202]
First, thank you for making borg available and for working to fix it.

There appears to be a bug in converting filename paths to UTF-8 in borg mount.

Environment
-------------
- borg 1.1.0
- Python 3.5.2
- Linux 4.4.0-96-generic #119-Ubuntu SMP (Ubuntu 16.04)
- /usr/bin/python3 -c "import sys;print(sys.getfilesystemencoding())": ascii

Steps to reproduce
-------------------
1. Include a UTF-8 filename in the path of files backed up. For me, it was a filename containing a '?'
2. mount the borg backup 'borg mount ```<borg-dir>``` ```<mount-point>``` -f --debug
3. list a directory containing a UTF-8 string.

Result
------
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/borg/archiver.py", line 4024, in main
    exit_code = archiver.run(args)
  File "/usr/local/lib/python3.5/dist-packages/borg/archiver.py", line 3952, in run
    return set_ec(func(args))
  File "/usr/local/lib/python3.5/dist-packages/borg/archiver.py", line 1299, in do_mount
    return self._do_mount(args)
  File "/usr/local/lib/python3.5/dist-packages/borg/archiver.py", line 148, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/borg/archiver.py", line 1309, in _do_mount
    operations.mount(args.mountpoint, args.options, args.foreground)
  File "/usr/local/lib/python3.5/dist-packages/borg/fuse.py", line 303, in mount
    signal = fuse_main()
  File "/usr/local/lib/python3.5/dist-packages/borg/fuse.py", line 33, in fuse_main
    return llfuse.main(workers=1)
  File "src/fuse_api.pxi", line 343, in llfuse.main (src/llfuse.c:38933)
  File "src/handlers.pxi", line 39, in llfuse.fuse_lookup (src/llfuse.c:7933)
  File "src/handlers.pxi", line 40, in llfuse.fuse_lookup (src/llfuse.c:7849)
  File "/usr/local/lib/python3.5/dist-packages/borg/fuse.py", line 493, in lookup
    self._load_pending_archive(parent_inode)
  File "/usr/local/lib/python3.5/dist-packages/borg/fuse.py", line 490, in _load_pending_archive
    self.process_archive(archive_name, [os.fsencode(archive_name)])
  File "/usr/local/lib/python3.5/dist-packages/borg/fuse.py", line 330, in process_archive
    path = os.fsencode(item.path)
  File "/usr/lib/python3.5/os.py", line 860, in fsencode
    return filename.encode(encoding, errors)
UnicodeEncodeError: 'ascii' codec can't encode character '\xad' in position 132: ordinal not in range(128)
```

Fix
---
1. Encode the path string to UTF-8 (borg/fuse.py, line 330)
```
path = os.fsencode(item.path.encode('utf8'))
```

Note that I tried to issue this fix with a PR but opted to post the fix here for two reasons:
1. There are likely other places in which the path must be converted to 'UTF-8,' and these should be added to the tox and pytests.
2. I couldn't run the tox tests within a virtualenv. It appears that tox and the setup.py calls a python interpreter from the root path, rather than the python in the virtualenv. (I would consider this another bug)

**Comment by ThomasWaldmann** [comment]
Thanks for the report!

Please add borg version, python version, your OS and what `sys.getfilesystemencoding()` returns.

**Comment by jlorieau** [comment]
Thanks for the note.

I set the locale in the /etc/environment, and the filesystem encoding is utf-8 now. This was a stock and fresh ubuntu installation, which is a bit weird.

Perhaps the better approach to fixing this issue is to check the locale environment and print an error on mount with information on the current locale environment.

**Comment by ThomasWaldmann** [comment]
Well, having ascii filesystemencoding is not an issue per se as long as you only have ascii filenames.

OTOH, iirc we even check that for `borg extract` and warn that things might not work if one has non-ascii filenames.

**Comment by ThomasWaldmann** [comment]
https://docs.python.org/3/library/os.html#os.fsencode

So, it is the job of os.fsencode to encode unicode to the filesystem encoding.

So the proposed "fix" is not really a fix, just tweaking it so it works for the case when the fs encoding should be utf-8, but the system is configured for ascii.

The right fix is to correct the system configuration, so the fs encoding is utf-8 and the os.fsencode will work as expected (as you did meanwhile).

Maybe open a new issue to discuss the ascii warning.
Also I think we maybe could add the fs encoding to borg debug info.
