### ISSUE TITLE
Unusable repository due to KeyError after interrupted backup

### ISSUE THREAD

**Issue by AaronM04** [borgbackup/borg#3329]
Hi,

I was running a backup on my Fedora 26 system using Borg 1.1.0, when my system rebooted during the backup. I tried to check the interrupted backup, but got an error:

```
$ sudo borg check myrepo.borg::myarchive
[sudo] password for myuser: 
Killed stale lock myhostname@17603821839859.11425-0.
Local Exception
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/borg/locking.py", line 129, in acquire
    os.mkdir(self.path)
FileExistsError: [Errno 17] File exists: '/path/to/repo/myrepo.borg/lock.exclusive'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/borg/archiver.py", line 4024, in main
    exit_code = archiver.run(args)
  File "/usr/lib64/python3.6/site-packages/borg/archiver.py", line 3952, in run
    return set_ec(func(args))
  File "/usr/lib64/python3.6/site-packages/borg/archiver.py", line 135, in wrapper
    with repository:
  File "/usr/lib64/python3.6/site-packages/borg/repository.py", line 178, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/usr/lib64/python3.6/site-packages/borg/repository.py", line 366, in open
    self.lock = Lock(os.path.join(path, 'lock'), exclusive, timeout=lock_wait, kill_stale_locks=hostname_is_unique()).acquire()
  File "/usr/lib64/python3.6/site-packages/borg/locking.py", line 346, in acquire
    self._wait_for_readers_finishing(remove, sleep)
  File "/usr/lib64/python3.6/site-packages/borg/locking.py", line 359, in _wait_for_readers_finishing
    self._lock.acquire()
  File "/usr/lib64/python3.6/site-packages/borg/locking.py", line 133, in acquire
    self.kill_stale_lock()
  File "/usr/lib64/python3.6/site-packages/borg/locking.py", line 158, in kill_stale_lock
    for name in os.listdir(self.path):
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/repo/myrepo.borg/lock.exclusive'

Platform: Linux myhostname 4.13.10-200.fc26.x86_64 #1 SMP Fri Oct 27 15:34:40 UTC 2017 x86_64 x86_64
Linux: Fedora 26 Twenty Six
Borg: 1.1.0  Python: CPython 3.6.2
PID: 2970  CWD: /path/to/repo
sys.argv: ['/bin/borg', 'check', 'myrepo.borg::myarchive']
SSH_ORIGINAL_COMMAND: None
```
I then tried to get rid of the lock file by running `break-lock`, but I got a `KeyError` exception:

```
$ sudo borg break-lock myrepo.borg
Local Exception
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/borg/repository.py", line 1248, in get_fd
    return self.fds[segment]
  File "/usr/lib64/python3.6/site-packages/borg/lrucache.py", line 21, in __getitem__
    value = self._cache[key]  # raise KeyError if not found
KeyError: 59679

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/borg/archiver.py", line 4024, in main
    exit_code = archiver.run(args)
  File "/usr/lib64/python3.6/site-packages/borg/archiver.py", line 3952, in run
    return set_ec(func(args))
  File "/usr/lib64/python3.6/site-packages/borg/archiver.py", line 135, in wrapper
    with repository:
  File "/usr/lib64/python3.6/site-packages/borg/repository.py", line 178, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/usr/lib64/python3.6/site-packages/borg/repository.py", line 388, in open
    if segment is not None and self.io.get_segment_magic(segment) == ATTIC_MAGIC:
  File "/usr/lib64/python3.6/site-packages/borg/repository.py", line 1280, in get_segment_magic
    fd = self.get_fd(segment)
  File "/usr/lib64/python3.6/site-packages/borg/repository.py", line 1250, in get_fd
    fd = open(self.segment_filename(segment), 'rb')
OSError: [Errno 6] No such device or address: '/path/to/repo/myrepo.borg/data/5/59679'

Platform: Linux myhostname 4.13.10-200.fc26.x86_64 #1 SMP Fri Oct 27 15:34:40 UTC 2017 x86_64 x86_64
Linux: Fedora 26 Twenty Six
Borg: 1.1.0  Python: CPython 3.6.2
PID: 3042  CWD: /path/to/repo
sys.argv: ['/bin/borg', 'break-lock', 'myrepo.borg']
SSH_ORIGINAL_COMMAND: None
```

I get this same `KeyError` exception on just about every other command I have tried so far. This means my entire repository is unusable for backups or recovery until this is fixed. Does anybody know what went wrong, and how to fix it? Thank you!

**Comment by ThomasWaldmann** [comment]
```
FileExistsError: [Errno 17] File exists:                '/path/to/repo/myrepo.borg/lock.exclusive'
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/repo/myrepo.borg/lock.exclusive'
```
The first one would be normal IF the repo is locked.
But then the 2nd one should not happen, obviously.

**Comment by ThomasWaldmann** [comment]
```
OSError: [Errno 6] No such device or address: '/path/to/repo/myrepo.borg/data/5/59679'
```
Is that file on NFS or something?

BTW, borg 1.1.2 is out since quite a while, try to reproduce these issues with 1.1.2 please.
If your dist does not offer it, use the binary from github releases page.

**Comment by AaronM04** [comment]
This is an external hard drive, but not NFS. It's mounted the normal way. I think it's ext4.


And thanks, I'll try 1.1.2.

**Comment by ThomasWaldmann** [comment]
Any news? Check the filesystem, the errors look rather strange for ext4.

**Comment by AaronM04** [comment]
The filesystem is btrfs!

**Comment by ThomasWaldmann** [comment]
2 ideas:

- can you run a filesystem check on the external disk?
- is the external disk maybe going to sleep (or otherwise disconnecting, check kernel log) while borg is using it?

**Comment by AaronM04** [comment]
@ThomasWaldmann I just ran `btrfs check` on the device, and it looks okay:

```Checking filesystem on /dev/sdb1
UUID: 1f1b1a81-fb59-429c-85bb-830ada607bad
checking extents
checking free space cache
checking fs roots
checking csums
checking root refs
found 1047652364288 bytes used err is 0
total csum bytes: 1020206540
total tree bytes: 2701082624
total fs tree bytes: 1591951360
total extent tree bytes: 51380224
btree space waste bytes: 267634926
file data blocks allocated: 1044951281664
 referenced 1044950974464
```

I don't see any evidence of the disk going to sleep in `journalctl`. I'm pretty sure this error happened due to some kind of system crash. Interesting log entries just before the reboot: "mei_me 0000:00:16.0: : unsupported ioctl -2146933247." and "watchdog: watchdog0: watchdog did not stop!".

What I really want to know is how to fix this repository though. @ThomasWaldmann would you know how I can make it usable again?

**Comment by ThomasWaldmann** [comment]
Well, did you try to reproduce with borg 1.1.2?

It is a bit pointless hunting bugs in 1.1.0 when there are 2 newer versions out already that fixed quite some bugs. So, please try 1.1.2 and update the bug report with new tracebacks, if you have any.

**Comment by AaronM04** [comment]
Good news! I tried 1.1.2 using the git-install method at the bottom of the installation.rst, and I can create new backups without any errors.

FYI, 1.1.2 is not listed in the change log: https://github.com/borgbackup/borg/blob/1.1.1/docs/changes.rst

Thanks for your help!

**Comment by ThomasWaldmann** [comment]
\o/

If you refer to a tag in the URL (1.1.1), it will show precisely the files as they were at that (1.1.1) time. Of course they won't show any (by then) future stuff.

**Comment by AndreasBackx** [comment]
I've started facing a similar issue recently. The filesystem is ext4 and the mount is using samba over OpenVPN if that were to have anything to do with it. The error is correct that there is no `data/0/164` file and I consistently get the same error. Are there any things I could try?

Here is the full output:
```bash
Killed stale lock Hostname.localdomain@84440851429515.21510-0.
Removed stale exclusive roster lock for pid 21510.
Removed stale exclusive roster lock for pid 21510.
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 1259, in get_fd
    return self.fds[segment]
  File "/usr/lib/python3.6/site-packages/borg/lrucache.py", line 21, in __getitem__
    value = self._cache[key]  # raise KeyError if not found
KeyError: 164

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4175, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4107, in run
    return set_ec(func(args))
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 139, in wrapper
    kwargs['manifest'], kwargs['key'] = Manifest.load(repository, compatibility)
  File "/usr/lib/python3.6/site-packages/borg/helpers.py", line 330, in load
    cdata = repository.get(cls.MANIFEST_ID)
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 1034, in get
    self.index = self.open_index(self.get_transaction_id())
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 361, in get_transaction_id
    self.check_transaction()
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 358, in check_transaction
    self.replay_segments(replay_from, segments_transaction_id)
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 781, in replay_segments
    self.prepare_txn(index_transaction_id, do_cleanup=False)
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 514, in prepare_txn
    self._rebuild_sparse(segment)
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 846, in _rebuild_sparse
    for tag, key, offset, size in self.io.iter_objects(segment, read_data=False):
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 1304, in iter_objects
    fd = self.get_fd(segment)
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 1261, in get_fd
    fd = open(self.segment_filename(segment), 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/server/storage/Backups/data/0/164'

Platform: Linux Hostname 4.15.13-1-ARCH #1 SMP PREEMPT Sun Mar 25 11:27:57 UTC 2018 x86_64 
Linux: arch  
Borg: 1.1.4  Python: CPython 3.6.4
PID: 20054  CWD: /etc/systemd/network
sys.argv: ['/usr/bin/borg', 'create', '-v', '--stats', '/mnt/server/storage/Backups::{hostname}-{now:%Y-%m-%dT%H:%M:%S}', '/home/username', '/etc', '/var', '/Users', '/usr/local', '--exclude', '/mnt', '--exclude', '/home/*/.cache', '--exclude', '/var/cache', '--exclude', '/var/log', '--exclude', '/var/tmp', '--exclude', '/var/lock', '--exclude', '/var/run', '--exclude', '/var/spool', '--exclude', '*.pyc', '--exclude', '/home/username/Movies', '--exclude', '/home/username/Downloads']
SSH_ORIGINAL_COMMAND: None
```

**Comment by AndreasBackx** [comment]
I think I am upgrading to 1.1 now, it's been a while since I checked what the latest version of my borg install was when it worked.

**Comment by ThomasWaldmann** [comment]
Also it seems that your last repo op was interrupted between repo commit and index update...

**Comment by AndreasBackx** [comment]
That might be because of me shutting down my PC while it was backing up.

**Comment by ThomasWaldmann** [comment]
OK, something is going wrong there, not sure what it is.

One approach might be to do a borg 1.0 write operation to the repo and let it successfully finish and then try again with borg 1.1.

**Comment by ThomasWaldmann** [comment]
Before that, you could do a ls -lR on the repo dir and put it into a pastebin for further analysis, link it from here.

**Comment by ThomasWaldmann** [comment]
Same for the local cache dir that belongs to that repo id

**Comment by AndreasBackx** [comment]
[Here it is](https://gist.github.com/AndreasBackx/17adf19ef320a3e3ccd3ed862af8ce69), I assume with local cache dir the cache dir of the client which is `~/.cache/borg`?

**Comment by ThomasWaldmann** [comment]
~/.cache/borg/<repoid> (see repo/config file, id entry).

**Comment by AndreasBackx** [comment]
Alright, I've removed the data from the cache that was not from the my repo's id `2aca6e6d657830c138a992176fdaa1d4d346bb8539ba702d98ee4c4ee14afc98`.

**Comment by ThomasWaldmann** [comment]
OK, do a small "dummy" borg create to that repo with a few files and let it complete.
Then try 1.1 again as you did when you got the traceback.

**Comment by AndreasBackx** [comment]
I've specified only my `~/.bin` folder for the backup and it's been stuck on `playing segments  95%` for about 14 minutes now. I'll give it some more time.

**Comment by AndreasBackx** [comment]
Alright, I cancelled that backup and started a normal one that I left running overnight. It finished successfully and borg 1.1 backups are also no longer giving the exception. Thanks for the help!

**Comment by ThomasWaldmann** [comment]
try `borg check --repair`.

**Comment by elya5** [comment]
That worked. Thank you!
