### ISSUE TITLE
borg list fails with certain format keys 

### ISSUE THREAD

**Issue by jk-1** [borgbackup/borg#3399]
Following command runs fine:
```
jk@tiira:~$ borg list --format="{archive}{TAB}{time}  {comment}{NEWLINE}" /home/jk/tmp/bborgtest/testrepo
FOO	Wed, 2017-11-29 17:46:32  
FOO01	Wed, 2017-11-29 17:46:33  
FOO02	Wed, 2017-11-29 17:46:33  
FOO03	Wed, 2017-11-29 17:46:33  
FOO03b	Wed, 2017-11-29 17:50:58  
FOO04	Wed, 2017-11-29 18:04:02  
FOO05	Wed, 2017-11-29 18:04:02  
FOO06	Wed, 2017-11-29 18:04:03  
FOO07	Wed, 2017-11-29 18:04:04  
```
But following command fails:
```
borg list --format="{health} {NEWLINE}" /home/jk/tmp/bborgtest/testrepo
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4073, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4001, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 148, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1355, in do_list
    return self._list_repository(args, repository, manifest, key)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1398, in _list_repository
    sys.stdout.write(formatter.format_item(archive_info))
  File "/usr/lib/python3/dist-packages/borg/helpers.py", line 1635, in format_item
    return self.format.format_map(self.get_item_data(item))
KeyError: 'health'

Platform: Linux tiira 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 x86_64
Linux: Ubuntu 16.04 xenial
Borg: 1.1.2  Python: CPython 3.5.2
PID: 4292  CWD: /home/jk
sys.argv: ['/usr/bin/borg', 'list', '--format={health} {NEWLINE}', '/home/jk/tmp/bborgtest/testrepo']
SSH_ORIGINAL_COMMAND: None
```

Also at least these  other keys cause "borg list" to fail with same type of error message: type, mode, uid, gid, user, group, path, size, md5, all sha*-keys.

(I upgraded v1.0.7 to v1.1.2 and run borg upgrade --tam  <client> according to the Pre-1.0.9 manifest)

What's the problem?

**Comment by jk-1** [comment]
It fails also when repo is created with v1.1.2 so maybe not an upgrade issue.

**Comment by ThomasWaldmann** [comment]
You are doing a repo listing, so the items we are dealing with for the listing are **archives**.

The keys which fail apply to **files** only, so you can only use them with **archive listings** (when the items it deals with for the listing are **files**).

**Comment by ThomasWaldmann** [comment]
Failing with a traceback here is a bit ugly though, we could see if we can check that first and fail more prettily.

**Comment by jk-1** [comment]
OK, understood. Certain keys are only for repos and certain only for archives. This is nice feature.

**Comment by ThomasWaldmann** [comment]
borg 2.0 will have separate `list` (for archive contents) and `rlist` (for repo contents) commands, so it will be easier to see what's valid with what command.
