### ISSUE TITLE
Unexpected object integer error

### ISSUE THREAD

**Issue by NCNecros** [borgbackup/borg#3454]
In have some error when try do something with my repo (backup, check, etc.)

```
  Reading cached archive chunk index for bases-2017-11-01-00-00 ...
  Verified integrity of /root/.cache /borg/9660bd9e2642700c54baed49ffc57702b78714fd6e71a760f213befe7e607133/chunks.archive.d/76a67dc842e50b8a84bf26d66257b76834d874ba5da7e337dc7a505e92946c64.compact
Merging into master chunks index ...
Fetching and building archive index for data-2017-11-10-12-30 ...
Local Exception
Traceback (most recent call last):
  File "borg/archiver.py", line 4073, in main
  File "borg/archiver.py", line 4001, in run
  File "borg/archiver.py", line 148, in wrapper
  File "borg/archiver.py", line 1219, in do_delete
  File "borg/archiver.py", line 1261, in _delete_archives
  File "borg/cache.py", line 365, in __new__
  File "borg/cache.py", line 359, in local
  File "borg/cache.py", line 452, in __init__
  File "borg/cache.py", line 826, in sync
  File "borg/cache.py", line 780, in create_master_idx
  File "borg/cache.py", line 689, in fetch_and_build_idx
  File "src/borg/hashindex.pyx", line 524, in borg.hashindex.CacheSynchronizer.feed
ValueError: cache_sync_feed failed: Unexpected object: integer
```
Platform: Linux isida 3.12.67-64-pae #1 SMP Fri Dec 9 15:56:17 UTC 2016 (35c7b99) i686 i686
Linux: openSUSE  13.1 i586
Borg: 1.1.2  Python: CPython 3.5.4
PID: 1366  CWD: /1000GB/repo.attic/data
sys.argv: ['/home/necros/borg-linux32', 'delete', '--debug', '/1000GB/repo.attic::data-2017-11-09-12-30']
SSH_ORIGINAL_COMMAND: None
`

**Comment by ThomasWaldmann** [comment]
hmm, this needs some analysis...

could be:
- a bug in 1.1.2 (maybe upgrade to 1.1.latest, 1.1.3 is out since a while)
- a corrupt archive

Do NOT run `borg check --repair` using borg < 1.1.4. See #3444.

**Comment by ThomasWaldmann** [comment]
I had a look in the code, it seems to run into the problem there (unpack.h:135):
```
static inline int unpack_callback_uint64(unpack_user* u, int64_t d)
{
    switch(u->expect) {
        case expect_size:
            u->current.size = d;
            u->expect = expect_csize;
            break;
        case expect_csize:
            u->current.csize = d;
            u->expect = expect_entry_end;
            break;
        default:
            UNEXPECTED("integer");
    }
    return 0;
}
```
The chunks list it is processing has the format `[(chunkid, size, csize), ...]` (types: 32bytes, int, int) and it seem to encounter an int and is not in the state to accept the size or csize.

@enkore ^

**Comment by NCNecros** [comment]
With 1.1.3 I have same error. Need I waiting for 1.1.4 and check --repair ? Check --repair now show same error as any other action.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/pull/3445/commits/e09892caec8a63d59e909518c4e9c230dbd69774

You need a version that has this fix. It can be 1.1.4 (not released yet) or a fixed/patched older 1.1.x version.

**Comment by NCNecros** [comment]
OK thanks. Where can I find a fixed version, or when can I download 1.1.4?

**Comment by enkore** [comment]
> @enkore ^

For debugging it might be helpful to dump the current state in the UNEXPECTED macro. If I were a gambling man I'd put my money on a corrupted archive, though. Borg also had a bunch of metadata-corruption bugs in the past, though 2017-11 is rather recent for those.

**Comment by enkore** [comment]
> Borg check sussefully check all archibe but after last archive it throw error.

What error exactly?

**Comment by NCNecros** [comment]
@enkore 

```
Local Exception
    Traceback (most recent call last):
      File "borg/archiver.py", line 4073, in main
      File "borg/archiver.py", line 4001, in run
      File "borg/archiver.py", line 148, in wrapper
      File "borg/archiver.py", line 1219, in do_delete
      File "borg/archiver.py", line 1261, in _delete_archives
      File "borg/cache.py", line 365, in __new__
      File "borg/cache.py", line 359, in local
      File "borg/cache.py", line 452, in __init__
      File "borg/cache.py", line 826, in sync
      File "borg/cache.py", line 780, in create_master_idx
      File "borg/cache.py", line 689, in fetch_and_build_idx
      File "src/borg/hashindex.pyx", line 524, in borg.hashindex.CacheSynchronizer.feed
    ValueError: cache_sync_feed failed: Unexpected object: integer
```

**Comment by ThomasWaldmann** [comment]
@NCNecros that is not from borg check, but from borg delete. But as I said, do not run borg check --repair with an unfixed version.

1.1.4 will maybe come in later this month, if you need a quick solution, just apply the fix manually.
Some package maintainers might also distribute patched versions of the 1.1.3 package, read their changelog.

**Comment by ThomasWaldmann** [comment]
Any news here?

**Comment by ThomasWaldmann** [comment]
No reply, closing.
