### ISSUE TITLE
configure borg phase fails detecting lz4 compression library when 1.8.1 version is installed: utf8 code encountered

### ISSUE THREAD

**Issue by jjuanino** [borgbackup/borg#3550]
Hi,

when 1.8.1 lz4 version is installed, lz4.h file contains some utf8 character, and this breaks the configure phase of borg:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 172, in <module>
    liblz4_prefix = setup_lz4.lz4_system_prefix(possible_liblz4_prefixes)
  File "/wrkdirs/usr/ports/archivers/py-borgbackup/work-py36/borgbackup-1.1.4/setup_lz4.py", line 28, in lz4_system_prefix
    if 'LZ4_compress_default' in fd.read():  # requires lz4 >= 1.7.0 (r129)
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 13333: ordinal not in range(128)
*** Error code 1
```
setup_lz4.ph expects only us-ascii encoding, and thus crashes when it finds some utf8 character.

Could somebody else confirm this issue?

Regards

**Comment by bket** [comment]
Did you see #3544?

**Comment by ThomasWaldmann** [comment]
closing as duplicate.
