### ISSUE TITLE
bad files cache stops backup - instead of recreating cache

### ISSUE THREAD

**Issue by nealpalmer** [borgbackup/borg#3553]
Problem happened again.  I upgraded to 1.1.4, and it doesn't automatically re-create the "files" cache when I run "create".

How do I force Borg to recreate the files cache?  Shouldn't it automatically recreate it when it is found to be invalid?

See also: #3537 

> File failed integrity check: /home/pi/.cache/53f95bf25bdb1d96526e6de3ac66acb9b1e01a3d3bf30b184a4dab2f1057135b/files
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4175, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4107, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 150, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 545, in do_create
    create_inner(archive, cache)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 508, in create_inner
    read_special=args.read_special, dry_run=dry_run, st=st)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 619, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 596, in _process
    status = archive.process_file(path, st, cache, self.ignore_inode, self.files_cache_mode)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 988, in process_file
    ids = cache.file_known_and_unchanged(path_hash, st, ignore_inode, files_cache_mode)
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 917, in file_known_and_unchanged
    self._read_files()
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 523, in _read_files
    return
  File "/usr/lib/python3/dist-packages/borg/crypto/file_integrity.py", line 193, in __exit__
    self.hash_part('final', is_final=True)
  File "/usr/lib/python3/dist-packages/borg/crypto/file_integrity.py", line 188, in hash_part
    raise FileIntegrityError(self.path)
borg.crypto.file_integrity.FileIntegrityError: File failed integrity check: /home/pi/.cache/53f95bf25bdb1d96526e6de3ac66acb9b1e01a3d3bf30b184a4dab2f1057135b/files

**Comment by ThomasWaldmann** [comment]
Well, there are 2 "problems" here:
- the machine seems to have disk/fs/whatever problems, leading to frequent integrity issues
- borg does not automatically deal with that

The last one could be seen as a feature though as it is better to barf here than to continue working - who knows what else gets corrupt / does malfunction, if saving and reloading a cache file already gives different content.

**Comment by ThomasWaldmann** [comment]
I found some problems in the code:
- borg not ignoring a corrupt files cache (and continuing and finally writing a valid one)
- no easy way to get out of that situation, neither removing nor truncating the files cache helped
