### ISSUE TITLE
borg config does not validate values which prevent further operations against repository

### ISSUE THREAD

**Issue by MichaelDays** [borgbackup/borg#3566]
If additional_free_space is set to a value that cannot be converted to a float, further operations against the repo fail, including setting it to an appropriate value or deleting the config key with `borg config -d additional_free_space`.

(I encountered this because I set `additional_free_space` to `2Gb` not `2G`, with hilarious results).

To reproduce:

```
 $ brew cask install borgbackup
 $ borg init --encryption=repokey '/tmp/testrepo' 
 $ borg create '/tmp/testrepo'::archive1 ~/testfile
 $ borg config '/tmp/testrepo' additional_free_space splatvalue
 $ borg create '/tmp/testrepo'::archive2 ~/testfile
 
 Exception ignored in: <bound method Repository.__del__ of <Repository /tmp/testrepo>>
 Traceback (most recent call last):
   File "borg/repository.py", line 171, in __del__
 AssertionError: cleanup happened in Repository.__del__
 Local Exception
 Traceback (most recent call last):
   File "borg/archiver.py", line 4175, in main
   File "borg/archiver.py", line 4107, in run
   File "borg/archiver.py", line 137, in wrapper
   File "borg/repository.py", line 181, in __enter__
   File "borg/repository.py", line 387, in open
   File "borg/helpers.py", line 828, in parse_file_size
 ValueError: could not convert string to float: 'splatvalue'
 
 Platform: Darwin kyriarchy.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64 i386
 Borg: 1.1.4  Python: CPython 3.5.4
 PID: 40474  CWD: /Users/additional_free_space
 sys.argv: ['borg', 'create', 'splatvalue::2018-01-19-18-52', '/Users/days']
 SSH_ORIGINAL_COMMAND: None
 
 $borg config -d ''/tmp/testrepo' additional_free_space
Exception ignored in: <bound method Repository.__del__ of <Repository /tmp/test>>
Traceback (most recent call last):
  File "borg/repository.py", line 171, in __del__
AssertionError: cleanup happened in Repository.__del__
Local Exception
Traceback (most recent call last):
  File "borg/archiver.py", line 4175, in main
  File "borg/archiver.py", line 4107, in run
  File "borg/archiver.py", line 137, in wrapper
  File "borg/repository.py", line 181, in __enter__
  File "borg/repository.py", line 387, in open
  File "borg/helpers.py", line 828, in parse_file_size
ValueError: could not convert string to float: 'splat'

Platform: Darwin kyriarchy.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64 i386
Borg: 1.1.4  Python: CPython 3.5.4
PID: 40642  CWD: /Users/days
sys.argv: ['borg', 'config', '-d', '/tmp/test', 'additional_free_space']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment]
the main issue here is that it can't be undone using the same `borg config ...` method.

another issue is that there seems to be no validation (but otoh, the old method was to edit repo/config with an editor, that also does no validation - but at least same method can be used to fix the mishap then).

**Comment by MichaelDays** [comment]
Editing the repo config file directly still seems to work, thank goodness. :)

**Comment by Vertux** [comment]
I am sorry to use this issue ticket, but I did not want to open a new issue, because my issue seems to be related to this one.

**Environment a VM (xcp-ng)**
Debian 11, Mem: 2GB, 12GB free (local)
borg v1.2.2 (binary, no deb, everything default)

`borg init --encryption=repokey ssh://borg/mnt/borg`

It's a completely new and empty repository. When I do:

`borg config /mnt/borg/ additional-free-space 2G`

I get this Exception:

~~~
Local Exception
Traceback (most recent call last):
  File "borg/archiver.py", line 5159, in main
  File "borg/archiver.py", line 5090, in run
  File "borg/archiver.py", line 183, in wrapper
  File "borg/archiver.py", line 1954, in do_config
  File "borg/archiver.py", line 1882, in repo_validate
ValueError: Invalid name

Platform: Linux borg 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64
Linux: Unknown Linux
Borg: 1.2.2  Python: CPython 3.9.13 msgpack: 1.0.4 fuse: llfuse 1.4.2 [pyfuse3,llfuse]
PID: 4284  CWD: /home/borg
sys.argv: ['borg', 'config', '/mnt/borg/', 'additional-free-space', '2g']
SSH_ORIGINAL_COMMAND: None
~~~

**/mnt/borg/config**

~~~
[repository]
version = 1
segments_per_dir = 1000
max_segment_size = 524288000
append_only = 0
storage_quota = 0
additional_free_space = 0
~~~

**Hint:** `/mnt/borg` is a mounted NFS share with >2 TB free space

**Comment by ThomasWaldmann** [comment]
It should have underscores `_`, not minus `-`.

**Comment by Vertux** [comment]
Embarrassing, copy & paste sometimes plays a trick on you 🤭 Thank you, now it works like a charm.

**Comment by ThomasWaldmann** [comment]
@Vertux can you reproduce from where / how copy&paste went wrong exactly?

**Comment by Vertux** [comment]
> @Vertux can you reproduce from where / how copy&paste went wrong exactly?

@ThomasWaldmann Yes, it was [here](https://github.com/borgbackup/borg/issues/6288#issuecomment-1039494412)

**Comment by ThomasWaldmann** [comment]
That was just a vague idea about a borg init option we could have.

Better read the docs about what's actually there (and select the right version, so you read the docs matching the borg version you use).
