### ISSUE TITLE
Borg 1.1.4 fails to run with msgpack 0.5.2

### ISSUE THREAD

**Issue by herrbischoff** [borgbackup/borg#3586]
### Environment

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.3
BuildVersion:	17D47
```

```
$ pyenv -v
pyenv 1.2.0
```

```
$ python -V
Python 3.6.3
```

### Issue

When running Borg with msgpack 0.5.2 installed, it throws the following error:

```
Local Exception
Traceback (most recent call last):
  File "/Users/mbischoff/.pyenv/versions/3.6.3/lib/python3.6/site-packages/borg/archiver.py", line 4175, in main
    exit_code = archiver.run(args)
  File "/Users/mbischoff/.pyenv/versions/3.6.3/lib/python3.6/site-packages/borg/archiver.py", line 4107, in run
    return set_ec(func(args))
  File "/Users/mbischoff/.pyenv/versions/3.6.3/lib/python3.6/site-packages/borg/archiver.py", line 150, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/Users/mbischoff/.pyenv/versions/3.6.3/lib/python3.6/site-packages/borg/archiver.py", line 544, in do_create
    log_json=args.log_json)
  File "/Users/mbischoff/.pyenv/versions/3.6.3/lib/python3.6/site-packages/borg/archive.py", line 317, in __init__
    self.items_buffer = CacheChunkBuffer(self.cache, self.key, self.stats)
  File "/Users/mbischoff/.pyenv/versions/3.6.3/lib/python3.6/site-packages/borg/archive.py", line 261, in __init__
    super().__init__(key, chunker_params)
  File "/Users/mbischoff/.pyenv/versions/3.6.3/lib/python3.6/site-packages/borg/archive.py", line 225, in __init__
    self.packer = msgpack.Packer(unicode_errors='surrogateescape')
  File "msgpack/_packer.pyx", line 136, in msgpack._packer.Packer.__init__
TypeError: expected bytes, str found
```

Downgrading to 0.5.1 resolves it:

```sh
pip install --no-cache-dir msgpack==0.5.1
```

Downgrading to 0.5.0 gives some possibly interesting information:

```sh
pip install --no-cache-dir msgpack==0.5.0
```

```
/Users/mbischoff/.pyenv/versions/3.6.3/lib/python3.6/site-packages/msgpack/__init__.py:47: FutureWarning: use_bin_type option is not specified. Default value of the option will be changed in future version.
/Users/mbischoff/.pyenv/versions/3.6.3/lib/python3.6/site-packages/borg/archive.py:225: FutureWarning: use_bin_type option is not specified. Default value of the option will be changed in future version.
```

**Comment by ThomasWaldmann** [comment]
https://github.com/msgpack/msgpack-python/blob/master/ChangeLog.rst

is this the regression that was fixed in 0.5.3?

**Comment by herrbischoff** [comment]
Indeed, 0.5.3 fixes the issue.

**Comment by ThomasWaldmann** [comment]
Note: the msgpack-python package on pypi was not yet updated, so it still results in the broken 0.5.2 version.
Only msgpack is currently available in newer, not broken versions.

0.5.1 is ok, < 0.5.0 is also ok.
