### ISSUE TITLE
TypeError when running borg recreate

### ISSUE THREAD

**Issue by Catscrash** [borgbackup/borg#3588]
Hi,

I tried remove files from archives:

`borg --debug recreate --dry-run --list /mnt/backup/borg/hosting3::hosting3-2018-02-03-020017 -e 'relative/path/to/folder1' -e 'relative/path/to/folder2'`

or

`borg --debug recreate --dry-run --list /mnt/backup/borg/hosting3 -e 'relative/path/to/folder1' -e 'relative/path/to/folder2'`

but both won't work:

`
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/borg/archiver.py", line 4175, in main
    exit_code = archiver.run(args)
  File "/usr/local/lib/python3.4/dist-packages/borg/archiver.py", line 4107, in run
    return set_ec(func(args))
  File "/usr/local/lib/python3.4/dist-packages/borg/archiver.py", line 148, in wrapper
    return method(self, args, repository=repository, cache=cache_, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/borg/archiver.py", line 1665, in do_recreate
    if not recreater.recreate(name, args.comment, target):
  File "/usr/local/lib/python3.4/dist-packages/borg/archive.py", line 1635, in recreate
    target = self.create_target(archive, target_name)
  File "/usr/local/lib/python3.4/dist-packages/borg/archive.py", line 1786, in create_target
    target = self.create_target_archive(target_name)
  File "/usr/local/lib/python3.4/dist-packages/borg/archive.py", line 1797, in create_target_archive
    checkpoint_interval=self.checkpoint_interval)
  File "/usr/local/lib/python3.4/dist-packages/borg/archive.py", line 317, in __init__
    self.items_buffer = CacheChunkBuffer(self.cache, self.key, self.stats)
  File "/usr/local/lib/python3.4/dist-packages/borg/archive.py", line 261, in __init__
    super().__init__(key, chunker_params)
  File "/usr/local/lib/python3.4/dist-packages/borg/archive.py", line 225, in __init__
    self.packer = msgpack.Packer(unicode_errors='surrogateescape')
  File "msgpack/_packer.pyx", line 136, in msgpack._packer.Packer.__init__
TypeError: expected bytes, str found

Platform: Linux odroid 4.6.0+ #1 SMP PREEMPT Sun May 22 17:51:32 CEST 2016 armv7l armv7l
Linux: Ubuntu 15.10 wily
Borg: 1.1.4  Python: CPython 3.4.3+
PID: 28872  CWD: /mnt/backup/borg
sys.argv: ['/usr/local/bin/borg', '--debug', 'recreate', '--dry-run', '--list', '/mnt/backup/borg/hosting3::hosting3-2018-02-03-020017', '-e', 'relative/path/to/folder1/', '-e', 'relative/path/to/folder2/']
SSH_ORIGINAL_COMMAND: None

`

**Comment by Catscrash** [comment]
I just noticed, that this is the same issue as #3586 - fixed by downgrading as suggested in this issue.
