### ISSUE TITLE
Backup on davfs2 failed

### ISSUE THREAD

**Issue by smoneck** [borgbackup/borg#3594]
Do you have an idea what went wrong? `owncloud` is a mounted `davfs2` folder.
I can still copy files there and it should have 30 G of storage left.
 
```
Enter passphrase for key /home/user/owncloud/backup:
Local Exceptionents  33%
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 1259, in get_fd
    return self.fds[segment]
  File "/usr/lib/python3.6/site-packages/borg/lrucache.py", line 21, in __getitem__
    value = self._cache[key]  # raise KeyError if not found
KeyError: 24

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4175, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4107, in run
    return set_ec(func(args))
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 150, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 545, in do_create
    create_inner(archive, cache)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 508, in create_inner
    read_special=args.read_special, dry_run=dry_run, st=st)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 619, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 619, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 619, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 596, in _process
    status = archive.process_file(path, st, cache, self.ignore_inode, self.files_cache_mode)
  File "/usr/lib/python3.6/site-packages/borg/archive.py", line 1017, in process_file
    self.chunk_file(item, cache, self.stats, backup_io_iter(self.chunker.chunkify(fd, fh)))
  File "/usr/lib/python3.6/site-packages/borg/archive.py", line 956, in chunk_file
    from_chunk, part_number = self.write_part_file(item, from_chunk, part_number)
  File "/usr/lib/python3.6/site-packages/borg/archive.py", line 926, in write_part_file
    self.write_checkpoint()
  File "/usr/lib/python3.6/site-packages/borg/archive.py", line 440, in write_checkpoint
    self.save(self.checkpoint_name)
  File "/usr/lib/python3.6/site-packages/borg/archive.py", line 479, in save
    self.repository.commit()
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 423, in commit
    self.compact_segments()
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 698, in compact_segments
    for tag, key, offset, data in self.io.iter_objects(segment, include_data=True):
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 1304, in iter_objects
    fd = self.get_fd(segment)
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 1261, in get_fd
    fd = open(self.segment_filename(segment), 'rb')
PermissionError: [Errno 13] Permission denied: '/home/user/owncloud/backup/data/0/24'

Platform: Linux user 4.14.15-1-ARCH #1 SMP PREEMPT Tue Jan 23 21:49:25 UTC 2018 x86_64
Linux: arch
Borg: 1.1.4  Python: CPython 3.6.4
PID: 11581  CWD: /home/user
sys.argv: ['/usr/bin/borg', 'create', '--compression', 'auto,zlib,4', '--stats', '--progress', '/home/user/owncloud/backup::now-Init-Documents', '/home/user/Documents']
SSH_ORIGINAL_COMMAND: None
```

Thanks a lot!

**Comment by dimejo** [comment]
> PermissionError: [Errno 13] Permission denied: '/home/user/owncloud/backup/data/0/24'

Did you check the permissions of this file and the parent directories? Do you always use the same user for backups?

**Comment by smoneck** [comment]
Thank you for your answer!

> Did you check the permissions of this file and the parent directories?

```
~ $ ls -al ~/owncloud/backup/data/0
total 8799553
drwxr-xr-x 2 user users       960  4. Feb 22:14 ./
drwxr-xr-x 3 user users        96  4. Feb 22:14 ../ 
-rw-r--r-- 1 user users        17  4. Feb 14:53 1
-rw------- 1 user users 526179403  4. Feb 20:37 10
-rw------- 1 user users 145829525  4. Feb 20:42 11
-rw------- 1 user users        17  4. Feb 20:37 12
-rw------- 1 user users        17  4. Feb 20:42 13
-rw------- 1 user users        17  4. Feb 20:37 15
-rw------- 1 user users        17  4. Feb 20:37 17
-rw------- 1 user users 526636148  4. Feb 20:41 18
-rw------- 1 user users 525302730  4. Feb 21:41 19
-rw------- 1 user users 525002600  4. Feb 20:09 2
-rw------- 1 user users 524581068  4. Feb 21:45 20
-rw------- 1 user users 526838445  4. Feb 21:48 21
-rw------- 1 user users 443526406  4. Feb 21:51 22
-rw------- 1 user users        17  4. Feb 21:45 23
-rw------- 1 user users   4278784  4. Feb 21:51 24
-rw------- 1 user users        17  4. Feb 21:51 25
-rw------- 1 user users 524940409  4. Feb 21:56 26
-rw------- 1 user users 524683275  4. Feb 21:59 27
-rw------- 1 user users 526786774  4. Feb 22:03 28
-rw------- 1 user users 526691496  4. Feb 20:12 3
-rw------- 1 user users    432052  4. Feb 22:14 31
-rw------- 1 user users        17  4. Feb 22:14 32
-rw------- 1 user users 524305841  4. Feb 20:16 4
-rw------- 1 user users 525887839  4. Feb 20:19 5
-rw------- 1 user users 525381988  4. Feb 20:23 6
-rw------- 1 user users 524886377  4. Feb 20:26 7
-rw------- 1 user users 528067316  4. Feb 20:30 8
-rw------- 1 user users 530493414  4. Feb 20:34 9
```

> Do you always use the same user for backups?

Yes, this is a single user machine.

This is the first commit to a freshly created backup.
So, the full history is:
```
borg init -e repokey-blake2 ~/owncloud/backup
borg create --compression auto,zlib,4 --stats --progress ~/owncloud/backup::{now}-Init-Documents ~/Documents
```

The check failed with a different error. Maybe this is a hint ...

`borg check -v ~/owncloud/backup`
```
Starting repository check
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 1259, in get_fd
    return self.fds[segment]
  File "/usr/lib/python3.6/site-packages/borg/lrucache.py", line 21, in __getitem__
    value = self._cache[key]  # raise KeyError if not found
KeyError: 3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4175, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4107, in run
    return set_ec(func(args))
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 150, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 304, in do_check
    if not repository.check(repair=args.repair, save_space=args.save_space):
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 904, in check
    objects = list(self.io.iter_objects(segment))
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 1304, in iter_objects
    fd = self.get_fd(segment)
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 1261, in get_fd
    fd = open(self.segment_filename(segment), 'rb')
OSError: [Errno 5] Input/output error: '/home/user/owncloud/backup/data/0/3'

Platform: Linux userzen 4.14.15-1-ARCH #1 SMP PREEMPT Tue Jan 23 21:49:25 UTC 2018 x86_64
Linux: arch
Borg: 1.1.4  Python: CPython 3.6.4
PID: 20431  CWD: /home/user/owncloud
sys.argv: ['/usr/bin/borg', 'check', '-v', 'backup']
SSH_ORIGINAL_COMMAND: None
```

**Comment by smoneck** [comment]
Even deleting is problematic. There is something not going well with `borg` and `davfs2`:

```
borg list ~/owncloud/backup/
Enter passphrase for key /home/user/owncloud/backup: 
now-Init-Documents.checkpoint        Sun, 2018-02-04 20:06:04 [06b8e4ba9f0dfc108158cbf5b0b968162ac41625eb4cf4e2dffd9666907fd68e]
~/owncloud
```
```
~ $ borg delete ~/owncloud/backup::now-Init-Documents.checkpoint
Enter passphrase for key /home/user/owncloud/backup:
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 1259, in get_fd
    return self.fds[segment]
  File "/usr/lib/python3.6/site-packages/borg/lrucache.py", line 21, in __getitem__
    value = self._cache[key]  # raise KeyError if not found
KeyError: 10

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4175, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4107, in run
    return set_ec(func(args))
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 150, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 1221, in do_delete
    return self._delete_archives(args, repository)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 1268, in _delete_archives
    archive.delete(stats, progress=args.progress, forced=args.forced)
  File "/usr/lib/python3.6/site-packages/borg/archive.py", line 797, in delete
    chunk_decref(chunk_id, stats)
  File "/usr/lib/python3.6/site-packages/borg/archive.py", line 774, in chunk_decref
    self.cache.chunk_decref(id, stats, wait=False)
  File "/usr/lib/python3.6/site-packages/borg/cache.py", line 908, in chunk_decref
    self.repository.delete(id, wait=wait)
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 1089, in delete
    size = self.io.read(segment, offset, id, read_data=False)
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 1365, in read
    fd = self.get_fd(segment)
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 1261, in get_fd
    fd = open(self.segment_filename(segment), 'rb')
OSError: [Errno 5] Input/output error: '/home/user/owncloud/backup/data/0/10'

Platform: Linux user 4.14.15-1-ARCH #1 SMP PREEMPT Tue Jan 23 21:49:25 UTC 2018 x86_64
Linux: arch
Borg: 1.1.4  Python: CPython 3.6.4
PID: 22540  CWD: /home/user
sys.argv: ['/usr/bin/borg', 'delete', '/home/user/owncloud/backup::now-Init-Documents.checkpoint']
SSH_ORIGINAL_COMMAND: None
```
`davfs2` is mounted with options `_netdev,noauto,user,uid=user,gid=users` in `fstab`.

**Comment by ThomasWaldmann** [comment]
Maybe davfs2 does not work good enough for heavy usage?

I did not hear much good about DAV (in general) yet, but I do not have personal experiences with it.

When I see PermissionError, my first suspicion also always is that a mix up of user/group permissions happened, e.g. due to running backups or other repo ops sometimes as user and sometimes as root (or other user). But obviously this is not the case here.

IOError also should not happen. For a local disk, this would point to a problem with the hardware or the filesystem. For a network fs it could maybe also be a network issue.

Or just bugs in the davfs2 code?

**Comment by smoneck** [comment]
I too have the impression that DAV related things are unreliable -- whether this is DAV itself or the the wrappers around, I don't know.

The only things that come to my mind now are:

- Try again with [limited bandwidth](https://github.com/borgbackup/borg/issues/661#issuecomment-190120036) (nothing new there, right?)
 - Ask the storage administrators whether it can be accessed with other means (I actually don't expect anything here ...)
 - Do the full initial backup on a HDD, upload it manually and try if further (smaller) backups are stable.
 - Ask Werner Baumann

**Comment by smoneck** [comment]
P.s.: What let me ask this question here, is the `Permission denied` error. I still don't really grasp it.

**Comment by smoneck** [comment]
I just finished the first successful `borg create` by [limiting the bandwidth](http://borgbackup.readthedocs.io/en/stable/faq.html?highlight=BORG_RSH#is-there-a-way-to-limit-bandwidth-with-project-name) to roughly `0.7 x mean effective upload speed`¹ via `user@localhost`! Let's try some further commits ...

¹: `time rsync -a --progress /path/to/hugefile /path/to/davstorage/`

**Comment by smoneck** [comment]
Well ... since I needed all of my both usb ports last night, I carefully tried to make the third commit (towards an initial backup) using WiFi. And of course it broke. Now I can't access the backup anymore. :/

Do you have any ideas?

```
~ $ borg list ~/owncloud/backup
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 1259, in get_fd
    return self.fds[segment]
  File "/usr/lib/python3.6/site-packages/borg/lrucache.py", line 21, in __getitem__
    value = self._cache[key]  # raise KeyError if not found
KeyError: 88

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4175, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4107, in run 
    return set_ec(func(args))
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 139, in wrapper
    kwargs['manifest'], kwargs['key'] = Manifest.load(repository, compatibility)
  File "/usr/lib/python3.6/site-packages/borg/helpers.py", line 330, in load
    cdata = repository.get(cls.MANIFEST_ID)
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 1037, in get 
    return self.io.read(segment, offset, id) 
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 1365, in read
    fd = self.get_fd(segment)
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 1261, in get_fd
    fd = open(self.segment_filename(segment), 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/owncloud/backup/data/0/88'

Platform: Linux computername 4.14.15-1-ARCH #1 SMP PREEMPT Tue Jan 23 21:49:25 UTC 2018 x86_64 
Linux: arch  
Borg: 1.1.4  Python: CPython 3.6.4
PID: 8758  CWD: /home/user
sys.argv: ['/usr/bin/borg', 'list', '/home/user/owncloud/backup']
SSH_ORIGINAL_COMMAND: None
```
