### ISSUE TITLE
Data integrity error: Segment entry checksum mismatch.

### ISSUE THREAD

**Issue by DumbTomatoesQuestionPolitely** [borgbackup/borg#3602]
Since my last backup I get a `Data integrity error: Segment entry checksum mismatch.`

What I did to get rid of it:
Delete the archive during whose creation the problem first surfaced.
Run `borg check [REPOSITORY] ` and  `borg check --repair [REPOSITORY]`

I did a fsck (external HDD partition where borg repo lies is formatted NTFS) and it did not find any errors. Therefore I am not suspecting, but also not ruling out any filesystem issues.

```
ubuntu@ubuntu:\~$ borg check [REPOSITORY]
Data integrity error: Segment entry checksum mismatch [segment 2723, offset 8408808]
Index object count mismatch.
committed index: 223814 objects
rebuilt index:   223815 objects
ID                                                               rebuilt index    committed index
cd6876fa0c3433e89b04837184177711f79a68faf152cd4c9a8b3f727641f5cd (2638, 435512439) <not found>
Completed repository check, errors found.
ubuntu@ubuntu:~$ borg check --repair [REPOSITORY]
'check --repair' is an experimental feature that might result in data loss.
Type 'YES' if you understand this and want to continue: YES
Data integrity error: Segment entry checksum mismatch [segment 2723, offset 8408808]
Data integrity error: Segment entry checksum mismatch [segment 2615, offset 236726978]
Traceback (most recent call last):
  File "borg/archiver.py", line 4175, in main
  File "borg/archiver.py", line 4107, in run
  File "borg/archiver.py", line 150, in wrapper
  File "borg/archiver.py", line 304, in do_check
  File "borg/repository.py", line 946, in check
  File "borg/repository.py", line 698, in compact_segments
  File "borg/repository.py", line 1317, in iter_objects
  File "borg/repository.py", line 1404, in _read
borg.helpers.IntegrityError: Data integrity error: Segment entry checksum mismatch [segment 2615, offset 236726978]

Platform: Linux ubuntu 4.13.0-21-generic #24-Ubuntu SMP Mon Dec 18 17:29:16 UTC 2017 x86_64 x86_64
Linux: debian stretch/sid
Borg: 1.1.4  Python: CPython 3.5.4
PID: 5540  CWD: /home/ubuntu
sys.argv: ['borg', 'check', '--repair', '[REPOSITORY]']
SSH_ORIGINAL_COMMAND: None

ubuntu@ubuntu:~$ borg check [REPOSITORY]
Data integrity error: Segment entry checksum mismatch [segment 2615, offset 236726978]
Completed repository check, errors found.
```

**Comment by ThomasWaldmann** [comment]
Maybe analyze in this order:
- make sure your RAM is ok (at least one full pass of memtest86+), result must be 0 errors.
- make sure your hdd/ssd is ok (smartctl -t long ..., smartctl -a ...)

It's unfortunate that `borg check --repair` crashes, I'll check if I can fix that.

**Comment by ThomasWaldmann** [comment]
Also, can you please run with -v: `borg check -v --repair ...`

**Comment by ThomasWaldmann** [comment]
The crash is in compact_segments() which seems to be a non-essential component in check().

Strange:
- why does it count down segments (2723, 2615, see log above), the loop in the code looks rather like counting up.
- the first loop checks all segments and recovers all problematic segments, so they should be crc error free after that. finding a crc error at the same segment:offset later (in compact_segments) is rather unexpected.

**Comment by ThomasWaldmann** [comment]
Looks a bit like #2137.

**Comment by DumbTomatoesPolitelyQuestion** [comment]
Thank you for your fast and helpful comments! RAM seems to be the issue. Just wondering: I had the impression that borg was only appending. Guess that I was wrong and only if I use the specific mode this is the case? To me it seems as if an old block got corrupted while doing a new backup. Do I understand this correctly?

> make sure your RAM is ok (at least one full pass of memtest86+), result must be 0 errors.

**This seems to be the problem, got loads of errors (approx. 100) on the first pass**. Just for the sake of completeness the results of the other tests:

> check if HDD power supply is sufficient

Should be OK hopefully, USB powered on a 3.0 port.

> make sure your hdd/ssd is ok (smartctl -t long ..., smartctl -a ...)

Did that, no errors.

> check / exchange USB cables, remove any extensions or USB hubs, try a different USB port

Done.

> Also, can you please run with -v: `borg check -v --repair ...`

Had already done that before you asked, here are the results:

```
ubuntu@ubuntu:~$ borg check -v [REPOSITORY]/
Starting repository check
Data integrity error: Segment entry checksum mismatch [segment 2615, offset 236726978]
Starting repository index check
Completed repository check, errors found.

ubuntu@ubuntu:~$ borg check --repair -v [REPOSITORY]/
'check --repair' is an experimental feature that might result in data loss.
Type 'YES' if you understand this and want to continue: YES
Starting repository check
Data integrity error: Segment entry checksum mismatch [segment 2615, offset 236726978]
attempting to recover [REPOSITORY]/data/2/2615
Starting repository index check
Completed repository check, errors found and repaired.
Starting archive consistency check...
Enter passphrase for key [REPOSITORY]:
Analyzing archive [archivename] (1/52)
Analyzing archive [archivename] (2/52)
Analyzing archive [archivename] (3/52)
Analyzing archive [archivename] (4/52)
Analyzing archive [archivename] (5/52)
Analyzing archive [archivename] (6/52)
Analyzing archive [archivename] (7/52)
Analyzing archive [archivename] (8/52)
Analyzing archive [archivename] (9/52)
Analyzing archive [archivename] (10/52)
Analyzing archive [archivename] (11/52)
Analyzing archive [archivename] (12/52)
Analyzing archive [archivename] (13/52)
Analyzing archive [archivename] (14/52)
Analyzing archive [archivename] (15/52)
Analyzing archive [archivename] (16/52)
Analyzing archive [archivename] (17/52)
Analyzing archive [archivename] (18/52)
Analyzing archive [archivename] (19/52)
Analyzing archive [archivename] (20/52)
Analyzing archive [archivename] (21/52)
Analyzing archive [archivename] (22/52)
Analyzing archive [archivename] (23/52)
Analyzing archive [archivename] (24/52)
Analyzing archive [archivename] (25/52)
Analyzing archive [archivename] (26/52)
Analyzing archive [archivename] (27/52)
Analyzing archive [archivename] (28/52)
Analyzing archive [archivename] (29/52)
Analyzing archive [archivename] (30/52)
Analyzing archive [archivename] (31/52)
Analyzing archive [archivename] (32/52)
Analyzing archive [archivename] (33/52)
Analyzing archive [archivename] (34/52)
Analyzing archive [archivename] (35/52)
Analyzing archive [archivename] (36/52)
Analyzing archive [archivename] (37/52)
Analyzing archive [archivename] (38/52)
Analyzing archive [archivename] (39/52)
Analyzing archive [archivename] (40/52)
Analyzing archive [archivename] (41/52)
Analyzing archive [archivename] (42/52)
Analyzing archive [archivename] (43/52)
Analyzing archive [archivename] (44/52)
Analyzing archive [archivename] (45/52)
Analyzing archive [archivename] (46/52)
Analyzing archive [archivename] (47/52)
Analyzing archive [archivename] (48/52)
Analyzing archive [archivename] (49/52)
Analyzing archive [archivename] (50/52)
Analyzing archive [archivename] (51/52)
Analyzing archive [archivename] (52/52)
Archive consistency check complete, no problems found.

ubuntu@ubuntu:~$ borg check -v [REPOSITORY]/
Starting repository check
Data integrity error: Invalid segment entry size 1109923229 - too big [segment 663, offset 2925849]
Traceback (most recent call last):
  File "borg/archiver.py", line 4175, in main
  File "borg/archiver.py", line 4107, in run
  File "borg/archiver.py", line 150, in wrapper
  File "borg/archiver.py", line 304, in do_check
  File "borg/repository.py", line 911, in check
  File "borg/repository.py", line 826, in _update_index
  File "borg/repository.py", line 1368, in read
  File "borg/repository.py", line 1392, in _read
borg.helpers.IntegrityError: Data integrity error: Invalid segment entry size 1109923229 - too big [segment 663, offset 2925849]

Platform: Linux ubuntu 4.13.0-21-generic #24-Ubuntu SMP Mon Dec 18 17:29:16 UTC 2017 x86_64 x86_64
Linux: debian stretch/sid
Borg: 1.1.4  Python: CPython 3.5.4
PID: 12436  CWD: /home/ubuntu
sys.argv: ['borg', 'check', '-v', '[REPOSITORY]/']
SSH_ORIGINAL_COMMAND: None

ubuntu@ubuntu:~$ borg check --repair -v [REPOSITORY]/
'check --repair' is an experimental feature that might result in data loss.
Type 'YES' if you understand this and want to continue: YES
Starting repository check
Starting repository index check
Completed repository check, no problems found.
Starting archive consistency check...
Enter passphrase for key [REPOSITORY]:
Analyzing archive [archivename] (1/52)
Analyzing archive [archivename] (2/52)
Analyzing archive [archivename] (3/52)
Analyzing archive [archivename] (4/52)
Analyzing archive [archivename] (5/52)
Analyzing archive [archivename] (6/52)
Analyzing archive [archivename] (7/52)
Analyzing archive [archivename] (8/52)
Analyzing archive [archivename] (9/52)
Analyzing archive [archivename] (10/52)
Analyzing archive [archivename] (11/52)
Analyzing archive [archivename] (12/52)
Analyzing archive [archivename] (13/52)
Analyzing archive [archivename] (14/52)
Analyzing archive [archivename] (15/52)
Analyzing archive [archivename] (16/52)
Analyzing archive [archivename] (17/52)
Analyzing archive [archivename] (18/52)
Analyzing archive [archivename] (19/52)
Analyzing archive [archivename] (20/52)
Analyzing archive [archivename] (21/52)
Analyzing archive [archivename] (22/52)
Analyzing archive [archivename] (23/52)
Analyzing archive [archivename] (24/52)
Analyzing archive [archivename] (25/52)
Analyzing archive [archivename] (26/52)
Analyzing archive [archivename] (27/52)
Analyzing archive [archivename] (28/52)
Analyzing archive [archivename] (29/52)
Analyzing archive [archivename] (30/52)
Analyzing archive [archivename] (31/52)
Analyzing archive [archivename] (32/52)
Analyzing archive [archivename] (33/52)
Analyzing archive [archivename] (34/52)
Analyzing archive [archivename] (35/52)
Analyzing archive [archivename] (36/52)
Analyzing archive [archivename] (37/52)
Analyzing archive [archivename] (38/52)
Analyzing archive [archivename] (39/52)
Analyzing archive [archivename] (40/52)
Analyzing archive [archivename] (41/52)
Analyzing archive [archivename] (42/52)
Analyzing archive [archivename] (43/52)
Analyzing archive [archivename] (44/52)
Analyzing archive [archivename] (45/52)
Analyzing archive [archivename] (46/52)
Analyzing archive [archivename] (47/52)
Analyzing archive [archivename] (48/52)
Analyzing archive [archivename] (49/52)
Analyzing archive [archivename] (50/52)
Analyzing archive [archivename] (51/52)
Analyzing archive [archivename] (52/52)
Archive consistency check complete, no problems found.

ubuntu@ubuntu:~$ borg check --repair -v [REPOSITORY]/
'check --repair' is an experimental feature that might result in data loss.
Type 'YES' if you understand this and want to continue: YES
Starting repository check
Starting repository index check
Completed repository check, no problems found.
Starting archive consistency check...
Enter passphrase for key [REPOSITORY]:
Analyzing archive [archivename] (1/52)
Analyzing archive [archivename] (2/52)
Analyzing archive [archivename] (3/52)
Analyzing archive [archivename] (4/52)
Analyzing archive [archivename] (5/52)
Analyzing archive [archivename] (6/52)
Analyzing archive [archivename] (7/52)
Analyzing archive [archivename] (8/52)
Analyzing archive [archivename] (9/52)
Analyzing archive [archivename] (10/52)
Analyzing archive [archivename] (11/52)
Analyzing archive [archivename] (12/52)
Analyzing archive [archivename] (13/52)
Analyzing archive [archivename] (14/52)
Analyzing archive [archivename] (15/52)
Analyzing archive [archivename] (16/52)
Analyzing archive [archivename] (17/52)
Analyzing archive [archivename] (18/52)
Analyzing archive [archivename] (19/52)
Analyzing archive [archivename] (20/52)
Analyzing archive [archivename] (21/52)
Analyzing archive [archivename] (22/52)
Analyzing archive [archivename] (23/52)
Analyzing archive [archivename] (24/52)
Analyzing archive [archivename] (25/52)
Analyzing archive [archivename] (26/52)
Analyzing archive [archivename] (27/52)
Analyzing archive [archivename] (28/52)
Analyzing archive [archivename] (29/52)
Analyzing archive [archivename] (30/52)
Analyzing archive [archivename] (31/52)
Analyzing archive [archivename] (32/52)
Analyzing archive [archivename] (33/52)
Analyzing archive [archivename] (34/52)
Analyzing archive [archivename] (35/52)
Analyzing archive [archivename] (36/52)
Analyzing archive [archivename] (37/52)
Analyzing archive [archivename] (38/52)
Analyzing archive [archivename] (39/52)
Analyzing archive [archivename] (40/52)
Analyzing archive [archivename] (41/52)
Analyzing archive [archivename] (42/52)
Analyzing archive [archivename] (43/52)
Analyzing archive [archivename] (44/52)
Analyzing archive [archivename] (45/52)
Analyzing archive [archivename] (46/52)
Analyzing archive [archivename] (47/52)
Analyzing archive [archivename] (48/52)
Analyzing archive [archivename] (49/52)
Analyzing archive [archivename] (50/52)
Analyzing archive [archivename] (51/52)
Analyzing archive [archivename] (52/52)
Archive consistency check complete, no problems found.
```

**Comment by ThomasWaldmann** [comment]
As it executed compact_segments, it was not in append-only mode at that time.
When one runs `borg check --repair` one rather does not have the repo in append-only mode.

100 RAM errors: you need new RAM (and test that also). Even 1 error is too much.

The logs still look a bit weird...

**Comment by ThomasWaldmann** [comment]
Just to clarify: that log in https://github.com/borgbackup/borg/issues/3602#issuecomment-364754062 - was that made with the bad RAM or after exchanging the RAM with working RAM?

**Comment by DumbTomatoesPolitelyQuestion** [comment]
Good catch! 

> Had already done that before you asked, here are the results:

So everything done with bad RAM. Sorry for the noise and thank you again for the fast and efficient help!

**Comment by nealpalmer** [comment]
Makes you wonder if BORG should automatically do a memory test...  Wouldn't necessarily have to be a very good memory test, and wouldn't have to run all that long (especially if it ran EVERY time that borg runs).  You could even run it while waiting for HDD data...

**Comment by ThomasWaldmann** [comment]
We do some very simple / quick tests at startup, but not a good memory test - that would just take too long and need to much cpu / memory bandwith. Also it would need quite some code that does not belong into borg.

If you look at memtest86+, a full run often takes an hour (depends on speed and amount of memory of course).

See also #2281.

**Comment by i5513** [comment]
Running borgbackup from Debian SID, I'm getting this error

Please see two borg check output from my repo, the second check detect the same fails than the first, and another

I have realized a copy before running check --repair, so I can run again check if it is necessary.

This night I will run memtest and will report back. The disk is recently enough and not I/O error are being seen.

Thank you very much, I am using borgbackup from 2016 and this is the first time it is failing :(

[check-2018031302.txt](https://github.com/borgbackup/borg/files/1806901/check-2018031302.txt)
[check-2018031301.txt](https://github.com/borgbackup/borg/files/1806902/check-2018031301.txt)

**Comment by i5513** [comment]
Well, I have to wait until today to exec memtest. This was the output of check --repair:

> $ time borg check --repair /media/usb/fujitsu/backup-borg >>  check-repair-2018031301.txt
> 'check --repair' is an experimental feature that might result in data loss.
> Type 'YES' if you understand this and want to continue: YES
> Data integrity error: Segment entry checksum mismatch [segment 4, offset 445248019]
> Data integrity error: Segment entry checksum mismatch [segment 10, offset 254857228]
> 
> 
> 
> Data integrity error: Segment entry checksum mismatch [segment 13, offset 278377605]
> Data integrity error: Segment entry checksum mismatch [segment 16, offset 332991720]
> Data integrity error: Segment entry checksum mismatch [segment 19, offset 389244447]
> Data integrity error: Segment entry checksum mismatch [segment 19, offset 360338881]
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/borg/repository.py", line 904, in check
>     objects = list(self.io.iter_objects(segment))
>   File "/usr/lib/python3/dist-packages/borg/repository.py", line 1317, in iter_objects
>     read_data=read_data)
>   File "/usr/lib/python3/dist-packages/borg/repository.py", line 1404, in _read
>     segment, offset))
> borg.helpers.IntegrityError: Data integrity error: Segment entry checksum mismatch [segment 19, offset 389244447]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4175, in main
>     exit_code = archiver.run(args)
>   File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4107, in run
>     return set_ec(func(args))
>   File "/usr/lib/python3/dist-packages/borg/archiver.py", line 150, in wrapper
>     return method(self, args, repository=repository, **kwargs)
>   File "/usr/lib/python3/dist-packages/borg/archiver.py", line 304, in do_check
>     if not repository.check(repair=args.repair, save_space=args.save_space):
>   File "/usr/lib/python3/dist-packages/borg/repository.py", line 910, in check
>     objects = list(self.io.iter_objects(segment))
>   File "/usr/lib/python3/dist-packages/borg/repository.py", line 1317, in iter_objects
>     read_data=read_data)
>   File "/usr/lib/python3/dist-packages/borg/repository.py", line 1404, in _read
>     segment, offset))
> borg.helpers.IntegrityError: Data integrity error: Segment entry checksum mismatch [segment 19, offset 360338881]
> 
> Platform: Linux fideo 4.15.0-1-amd64 #1 SMP Debian 4.15.4-1 (2018-02-18) x86_64 
> Linux: debian buster/sid 
> Borg: 1.1.4  Python: CPython 3.6.4+
> PID: 24068  CWD: /home/javi/personal/backup/borgbackup
> sys.argv: ['/usr/bin/borg', 'check', '--repair', '/media/usb/fujitsu/backup-borg']
> SSH_ORIGINAL_COMMAND: None
> 
> 
> real	415m9,354s
> user	408m20,590s
> sys	0m23,248s
>

**Comment by i5513** [comment]
After check --repair, three check command returned the same output 

```
$ cat check-2018031401.txt 
Data integrity error: Segment entry checksum mismatch [segment 28, offset 284175153]
Data integrity error: Segment entry checksum mismatch [segment 31, offset 298854540]
Data integrity error: Segment entry checksum mismatch [segment 43, offset 348708548]
Data integrity error: Segment entry checksum mismatch [segment 45, offset 235063485]
Data integrity error: Segment entry checksum mismatch [segment 48, offset 476143619]
Data integrity error: Segment entry checksum mismatch [segment 51, offset 438344933]
Data integrity error: Segment entry checksum mismatch [segment 57, offset 371693003]
Data integrity error: Segment entry checksum mismatch [segment 60, offset 292661242]
Data integrity error: Segment entry checksum mismatch [segment 71, offset 400864222]
Data integrity error: Segment entry checksum mismatch [segment 77, offset 428044407]
Data integrity error: Segment entry checksum mismatch [segment 79, offset 433905915]
Data integrity error: Segment entry checksum mismatch [segment 91, offset 182551807]
Data integrity error: Segment entry checksum mismatch [segment 93, offset 192780179]
Data integrity error: Segment entry checksum mismatch [segment 97, offset 109327180]
Data integrity error: Segment entry checksum mismatch [segment 99, offset 87432781]
Data integrity error: Segment entry checksum mismatch [segment 103, offset 271163941]
Data integrity error: Segment entry checksum mismatch [segment 109, offset 248033705]
Data integrity error: Segment entry checksum mismatch [segment 116, offset 38459257]
Data integrity error: Segment entry checksum mismatch [segment 120, offset 505396713]
Data integrity error: Segment entry checksum mismatch [segment 124, offset 227598158]
Data integrity error: Segment entry checksum mismatch [segment 126, offset 197715058]
Data integrity error: Segment entry checksum mismatch [segment 128, offset 143833450]
Data integrity error: Segment entry checksum mismatch [segment 132, offset 53759286]
Data integrity error: Segment entry checksum mismatch [segment 135, offset 375004941]
Data integrity error: Segment entry checksum mismatch [segment 139, offset 130641378]
Data integrity error: Segment entry checksum mismatch [segment 143, offset 34174769]
Data integrity error: Segment entry checksum mismatch [segment 146, offset 445173685]
Data integrity error: Segment entry checksum mismatch [segment 154, offset 367980333]
Data integrity error: Segment entry checksum mismatch [segment 156, offset 405851885]
Data integrity error: Segment entry checksum mismatch [segment 160, offset 327521784]
Data integrity error: Segment entry checksum mismatch [segment 162, offset 324225158]
Data integrity error: Segment entry checksum mismatch [segment 164, offset 256815084]
Data integrity error: Segment entry checksum mismatch [segment 166, offset 275376282]
Data integrity error: Segment entry checksum mismatch [segment 172, offset 180921336]
Data integrity error: Segment entry checksum mismatch [segment 176, offset 102590719]
Data integrity error: Segment entry checksum mismatch [segment 180, offset 71247520]
Data integrity error: Segment entry checksum mismatch [segment 196, offset 59578393]
Data integrity error: Segment entry checksum mismatch [segment 198, offset 489918486]
Data integrity error: Segment entry checksum mismatch [segment 200, offset 179726403]
Data integrity error: Segment entry checksum mismatch [segment 203, offset 63422832]
Data integrity error: Segment entry checksum mismatch [segment 204, offset 288366808]
Data integrity error: Segment entry checksum mismatch [segment 208, offset 523900497]
Data integrity error: Segment entry checksum mismatch [segment 210, offset 249143452]
Data integrity error: Segment entry checksum mismatch [segment 213, offset 231465268]
Data integrity error: Segment entry checksum mismatch [segment 217, offset 382377602]
Data integrity error: Segment entry checksum mismatch [segment 220, offset 514204847]
Data integrity error: Segment entry checksum mismatch [segment 225, offset 234479843]
Completed repository check, errors found.
```

**Comment by i5513** [comment]
Is imposible to recover any backup of such repo ?

Thank you !

**Comment by ThomasWaldmann** [comment]
@i5513 that looks VERY corrupted (look at the numbers of the segment files, very frequent). Even after "successfully" running borg --repair on that, all affected chunks would be missing. So better fix your hardware first.

**Comment by i5513** [comment]
I will run memtest this nigth, I will report back.

But, md5sum work fine with a cp -a in the same device. I think disk is ok because there is not any I/O error, and the wire is ok (at least it seems).

How can we evidence that is  a hardware failure ?

Time ago I think there was an kernel which protected the system against memory errors, but now it is not ( I am not able to find any link about, so maybe I'm wrong?)

Thank you very much

**Comment by ThomasWaldmann** [comment]
Well, it is somehow unlikely that it is a issue within borg code because most people do not see corruption every few segment files.

Besides being an hardware issue, it could be of course also some other major malfunction (e.g. in the kernel, filesystem, or some OS library we use).

**Comment by i5513** [comment]
It is not good that you lost all backup snapshots when a backup goes wrong
:(

It is consecuence of how dedup works, i think.

Maybe I need to search an alternative backup method. Is it possible to
verify each write to disk after writting it ? so you can stop backup if
there is a wrong write ?

Thank you again !

**Comment by ThomasWaldmann** [comment]
@i5513 considering the amount and type of errors this doesn't look like "when a backup goes wrong".

When memtest86+ doesn't find issues, please run smartctl -a and -t long on all disks, see our docs.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/issues/3602#issuecomment-372970928 can you file that part as a new issue please?

While the root cause of your problem likely is below borg (in OS, in HW), `borg check --repair` maybe should not crash like that, but rather catch the exception and make the best of it.

**Comment by i5513** [comment]
Today I found time to exec memtest, and it showed me that my memory have error. I have to change the memory modules ... or change the laptop :(

Thank you very much

**Comment by fhaust** [comment]
I ran into the same problem. I have "Data integrity" errors that prevent new backups from happening. `borg check --repair` has crashed for me after several (10+) hours of processing. The long processing times might be due to working over NFS over Wifi, I think borg is just "replaying chunks" for hours there.

My question is: how do I remove the faulty segments. Possibly at the loss of data, but I means it's a backup and the next time I run a successful backup everything should be there again.
