### ISSUE TITLE
Borg data integrity error

### ISSUE THREAD

**Issue by ovalseven8** [borgbackup/borg#3701]
I am doing daily automatic backups using Borg. Everything worked fine so far, until yesterday there have been some problems executing the `prune` command. And today the backup process did not work. There seems to be something wrong and now I do not know what I should do or what's the reason for those errors. If it's a bug, perhaps we can find and solve it.

When I run `borg check` the ouput is:
`error: argument REPOSITORY_OR_ARCHIVE: Invalid location format: ""`

Why is that?
```
=====================================
2018-03-17 16:28:01,643 - INFO - Script started ...
2018-03-17 16:28:02,097 - INFO - 192.168.178.1/nas has been mounted.
2018-03-17 16:37:49,255 - INFO - Backup successful.
2018-03-17 16:39:35,549 - WARNING - Error while executing 'prune' command.Data integrity error: Segment entry checksum mismatch [segment 206, offset 68921368]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4175, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4107, in run
    return set_ec(func(args))
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 150, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 1568, in do_prune
    repository.commit(save_space=args.save_space)
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 423, in commit
    self.compact_segments()
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 698, in compact_segments
    for tag, key, offset, data in self.io.iter_objects(segment, include_data=True):
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 1317, in iter_objects
    read_data=read_data)
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 1404, in _read
    segment, offset))
borg.helpers.IntegrityError: Data integrity error: Segment entry checksum mismatch [segment 206, offset 68921368]

Platform: Linux rechner 4.15.9-1-ARCH #1 SMP PREEMPT Sun Mar 11 17:54:33 UTC 2018 x86_64 
Linux: arch  
Borg: 1.1.4  Python: CPython 3.6.4
PID: 3364  CWD: /
sys.argv: ['/sbin/borg', 'prune', '/mnt/nas', '--prefix', 'rechner-', '--keep-daily=7', '--keep-weekly=4', '--keep-monthly=12']
SSH_ORIGINAL_COMMAND: None


2018-03-17 16:39:35,631 - INFO - Umount successful.
2018-03-17 16:39:35,631 - INFO - Script has been completed.
=====================================
2018-03-18 10:37:01,381 - INFO - Script started ...
2018-03-18 10:37:02,259 - INFO - 192.168.178.1/nas has been mounted.
2018-03-18 10:39:26,323 - ERROR - Could not create backup.Data integrity error: Segment entry checksum mismatch [segment 206, offset 68921368]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4175, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4107, in run
    return set_ec(func(args))
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 150, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 545, in do_create
    create_inner(archive, cache)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 510, in create_inner
    archive.save(comment=args.comment, timestamp=args.timestamp)
  File "/usr/lib/python3.6/site-packages/borg/archive.py", line 479, in save
    self.repository.commit()
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 423, in commit
    self.compact_segments()
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 698, in compact_segments
    for tag, key, offset, data in self.io.iter_objects(segment, include_data=True):
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 1317, in iter_objects
    read_data=read_data)
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 1404, in _read
    segment, offset))
borg.helpers.IntegrityError: Data integrity error: Segment entry checksum mismatch [segment 206, offset 68921368]

Platform: Linux rechner 4.15.9-1-ARCH #1 SMP PREEMPT Sun Mar 11 17:54:33 UTC 2018 x86_64 
Linux: arch  
Borg: 1.1.4  Python: CPython 3.6.4
PID: 3650  CWD: /
sys.argv: ['/sbin/borg', 'create', '/mnt/nas::rechner-2018-03-18', '/home/user', '--exclude-from', '/tmp/tmp4ynlb03y', '--compression', 'lz4']
SSH_ORIGINAL_COMMAND: None


2018-03-18 10:39:44,596 - INFO - Prune successful.
2018-03-18 10:39:45,005 - INFO - Umount successful.
2018-03-18 10:39:45,006 - INFO - Script has been completed.
```

**Comment by ThomasWaldmann** [comment]
http://borgbackup.readthedocs.io/en/stable/faq.html#i-get-an-integrityerror-or-similar-what-now

**Comment by ovalseven8** [comment]
Mh, it's actually more complicated. My HDD does not support SMART capabilities and `borg check` recognized errors while `borg check --repair` was not able to fix all.

I'll set up a new repository. Thanks for your help! :)

**Comment by ThomasWaldmann** [comment]
did you check RAM also, with memtest86+?

**Comment by ovalseven8** [comment]
@ThomasWaldmann: I did `borg check` again and no errors have been reported suddenly. So I started my backup script again and the backup process was successful too. So, I will monitor the backups the coming days and look if everything is okay again.
