### ISSUE TITLE
borg check --repair crash

### ISSUE THREAD

**Issue by i5513** [borgbackup/borg#3737]
As requested at https://github.com/borgbackup/borg/issues/3602#issuecomment-373373538, I'm opening a new issue

I think we can close this issue because memtest detected that I have memory errors

Thank you

Well, I have to wait until today to exec memtest. This was the output of check --repair:

```
$ time borg check --repair /media/usb/fujitsu/backup-borg >>  check-repair-2018031301.txt
'check --repair' is an experimental feature that might result in data loss.
Type 'YES' if you understand this and want to continue: YES
Data integrity error: Segment entry checksum mismatch [segment 4, offset 445248019]
Data integrity error: Segment entry checksum mismatch [segment 10, offset 254857228]



Data integrity error: Segment entry checksum mismatch [segment 13, offset 278377605]
Data integrity error: Segment entry checksum mismatch [segment 16, offset 332991720]
Data integrity error: Segment entry checksum mismatch [segment 19, offset 389244447]
Data integrity error: Segment entry checksum mismatch [segment 19, offset 360338881]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 904, in check
    objects = list(self.io.iter_objects(segment))
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1317, in iter_objects
    read_data=read_data)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1404, in _read
    segment, offset))
borg.helpers.IntegrityError: Data integrity error: Segment entry checksum mismatch [segment 19, offset 389244447]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4175, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4107, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 150, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 304, in do_check
    if not repository.check(repair=args.repair, save_space=args.save_space):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 910, in check
    objects = list(self.io.iter_objects(segment))
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1317, in iter_objects
    read_data=read_data)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1404, in _read
    segment, offset))
borg.helpers.IntegrityError: Data integrity error: Segment entry checksum mismatch [segment 19, offset 360338881]

Platform: Linux fideo 4.15.0-1-amd64 #1 SMP Debian 4.15.4-1 (2018-02-18) x86_64 
Linux: debian buster/sid 
Borg: 1.1.4  Python: CPython 3.6.4+
PID: 24068  CWD: /home/javi/personal/backup/borgbackup
sys.argv: ['/usr/bin/borg', 'check', '--repair', '/media/usb/fujitsu/backup-borg']
SSH_ORIGINAL_COMMAND: None


real	415m9,354s
user	408m20,590s
sys	0m23,248s

```

**Comment by ThomasWaldmann** [comment]
> I think we can close this issue because memtest detected that I have memory errors
