### ISSUE TITLE
Exception when not run as root and repo has passphrase activated

### ISSUE THREAD

**Issue by IsaakGroepT** [borgbackup/borg#3752]
I have a repo with a passphrase activated and when I try to run a command like borg list repolocation and I do that without root privileges, as exception occurs:

```
Exception ignored in: <bound method Repository.__del__ of <Repository /mnt/2TBBTRFS/root-kde-raid1btrfs-encrypted>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 171, in __del__
    assert False, "cleanup happened in Repository.__del__"
AssertionError: cleanup happened in Repository.__del__
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 1259, in get_fd
    return self.fds[segment]
  File "/usr/lib/python3.6/site-packages/borg/lrucache.py", line 21, in __getitem__
    value = self._cache[key]  # raise KeyError if not found
KeyError: 22

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4175, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4107, in run
    return set_ec(func(args))
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 137, in wrapper
    with repository:
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 181, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 399, in open
    if segment is not None and self.io.get_segment_magic(segment) == ATTIC_MAGIC:
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 1291, in get_segment_magic
    fd = self.get_fd(segment)
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 1261, in get_fd
    fd = open(self.segment_filename(segment), 'rb')
PermissionError: [Errno 13] Permission denied: '/mnt/2TBBTRFS/root-kde-raid1btrfs-encrypted/data/0/22'

Platform: Linux Aardbol 4.15.14-1-ARCH #1 SMP PREEMPT Wed Mar 28 17:34:29 UTC 2018 x86_64 
Linux: Antergos Linux 18.2 ISO-Rolling
Borg: 1.1.4  Python: CPython 3.6.4
PID: 1512  CWD: /home/ik/PycharmProjects/BackupSysteem
sys.argv: ['/usr/bin/borg', 'list', '/mnt/2TBBTRFS/root-kde-raid1btrfs-encrypted']
SSH_ORIGINAL_COMMAND: None
```
This exception doesn't occur when I do that on a repo that doesn't have a passphrase activated

**Comment by ThomasWaldmann** [comment]
You have a permissions problem, see the faq about how to avoid that.

**Comment by IsaakGroepT** [comment]
I've gone through the FAQ multiple times but unfortunately I can't find what you mean

**Comment by infectormp** [comment]
@IsaakGroepT https://borgbackup.readthedocs.io/en/stable/quickstart.html#important-note-about-permissions
