### ISSUE TITLE
"borg serve" fails to run

### ISSUE THREAD

**Issue by bocajnotnef** [borgbackup/borg#376]
Hello,

I've been trying to set up borg on a remote server to back things up to and I've been running into an issue. If I try to launch the borg server so that it will daemon (e.g. `$ nohup borg serve &`) it errors out with:

```
borg: Error: Local Exception.                                                   
Traceback (most recent call last):                                              
  File "/vagrant/borg/borg/borg/archiver.py", line 1030, in main                
  File "/vagrant/borg/borg/borg/archiver.py", line 986, in run                  
  File "/vagrant/borg/borg/borg/archiver.py", line 63, in do_serve              
  File "/vagrant/borg/borg/borg/remote.py", line 67, in serve                   
OSError: [Errno 9] Bad file descriptor                                          
                                                                                
borg: Exiting with failure status due to previous errors 
```

If I run `$ borg serve` at the command line, it will just sit. If I attempt to connect to it from my laptop I get a "server immediately closed connection - is Borg installed and working" error.

If I run `$ borg serve` and hit enter a few times the server errors out:
```
$ borg serve -v


borg: Error: Local Exception.
Traceback (most recent call last):
  File "/vagrant/borg/borg/borg/archiver.py", line 1030, in main
  File "/vagrant/borg/borg/borg/archiver.py", line 986, in run
  File "/vagrant/borg/borg/borg/archiver.py", line 63, in do_serve
  File "/vagrant/borg/borg/borg/remote.py", line 73, in serve
Exception: Unexpected RPC data format.

borg: Exiting with failure status due to previous errors
```

Any guidance/suggestions would be very appreciated.

**Comment by ThomasWaldmann** [comment]
You do not need to start "borg serve" on your own.

If you use borg with a ssh: repo URL, it will ssh to the repo machine and start "borg serve" there automatically. So, on the repo machine, you just need a working ssh login and borg installed, nothing else.

**Comment by bocajnotnef** [comment]
Okay, then followup:

I can't get borg to init a repo across an ssh connection though I've verified the connection details are valid. 

```
OpenSSL version mismatch. Built against 1000204f, you have 1000105f
borg: Error: Local Exception.
Traceback (most recent call last):
  File "/vagrant/borg/borg/borg/remote.py", line 147, in __init__
  File "/vagrant/borg/borg/borg/remote.py", line 176, in call
  File "/vagrant/borg/borg/borg/remote.py", line 226, in call_many
borg.remote.ConnectionClosed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vagrant/borg/borg/borg/archiver.py", line 1030, in main
  File "/vagrant/borg/borg/borg/archiver.py", line 986, in run
  File "/vagrant/borg/borg/borg/archiver.py", line 68, in do_init
  File "/vagrant/borg/borg/borg/archiver.py", line 41, in open_repository
  File "/vagrant/borg/borg/borg/remote.py", line 149, in __init__
Exception: Server immediately closed connection - is Borg installed and working on the server?
```

Since my credentials are correct, borg is in the path on the remote machine and you say borg serve should be started automatically then there's another issue.

I assume borg supports publickey-only authentication? (Password login on the remote server is disabled, I use publickeys to log in )

**Comment by ThomasWaldmann** [comment]
See the first line you have posted. Is that the problem maybe?

You can also simply try that: ssh user@remote borg

**Comment by bocajnotnef** [comment]
Perhaps, I only get that error when running borg though.

The issue could be with the distribution package--I'll try installing from
another source.

**Comment by ThomasWaldmann** [comment]
BTW, you seem to run via vagrant? Our Vagrantfile is rather for testing / building, it is not intended as / tested as a way to setup a borg repo server.

**Comment by ThomasWaldmann** [comment]
See #514 for the OpenSSL version mismatch.
