### ISSUE TITLE
borg check stalls

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#3763]
(copied from the borgbackup mailing list Florian Lindner <mailinglists@xgm.de>)

Hello,

borg list or info, as well as the usual backups work just fine, e.g.

```
% borg --debug list
using builtin fallback logging configuration
35 self tests completed in 0.07 seconds
SSH command line: ['ssh', '-p', '23', 'u123@u123.your-storagebox.de', 'borg', 'serve', '--umask=077', '--debug']
TAM-verified manifest
security: read previous location 'ssh://u123@u123.your-storagebox.de:23/./Backup'
security: read manifest timestamp '2018-04-08T16:08:29.849300'
security: determined newest manifest timestamp as 2018-04-08T16:08:29.849300
security: repository checks ok, allowing access
horus-2018-02-25T00:00:58            Sun, 2018-02-25 00:01:01 [83890f623fd4d7e7bf4a6921564bead27bf1f0efd8a9f749a20c2f24c600901b]
[...]
```
but borg check stops at the SSH connection:
```
% borg --debug check
using builtin fallback logging configuration
35 self tests completed in 0.07 seconds
SSH command line: ['ssh', '-p', '23', 'u123@u123.your-storagebox.de', 'borg', 'serve', '--umask=077', '--debug']
```
After about 10 minutes with no output, I use Ctrl-C to cancel:
```
^CRemoteRepository: 148 B bytes sent, 66 B bytes received, 3 messages sent
Connection closed by remote host
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 152, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 306, in do_check
    if not repository.check(repair=args.repair, save_space=args.save_space):
  File "/usr/lib/python3.6/site-packages/borg/remote.py", line 476, in do_rpc
    return self.call(f.__name__, named, **extra)
  File "/usr/lib/python3.6/site-packages/borg/remote.py", line 707, in call
    for resp in self.call_many(cmd, [args], **kw):
  File "/usr/lib/python3.6/site-packages/borg/remote.py", line 800, in call_many
    r, w, x = select.select(self.r_fds, w_fds, self.x_fds, 1)
  File "/usr/lib/python3.6/site-packages/borg/helpers.py", line 2234, in handler
    raise exc_cls
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4253, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4185, in run
    return set_ec(func(args))
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 152, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.6/site-packages/borg/remote.py", line 630, in __exit__
    self.rollback()
  File "/usr/lib/python3.6/site-packages/borg/remote.py", line 476, in do_rpc
    return self.call(f.__name__, named, **extra)
  File "/usr/lib/python3.6/site-packages/borg/remote.py", line 707, in call
    for resp in self.call_many(cmd, [args], **kw):
  File "/usr/lib/python3.6/site-packages/borg/remote.py", line 807, in call_many
    raise ConnectionClosed()
borg.remote.ConnectionClosed: Connection closed by remote host

Platform: Linux horus 4.15.14-1-ARCH #1 SMP PREEMPT Wed Mar 28 17:34:29 UTC 2018 x86_64
Linux: arch  
Borg: 1.1.5  Python: CPython 3.6.4
PID: 11786  CWD: /home/florian
sys.argv: ['/bin/borg', '--debug', 'check']
SSH_ORIGINAL_COMMAND: None
```
Using borg check on the same server (different path albeit) works fine, with borg 1.0.9 from Debian stable.

Any idea what is going wrong with borg check here?

Thanks,
Florian

**Comment by floli** [comment]
OP here.

Works just fine:
```
% borg check -v --archives-only
Starting archive consistency check...
Analyzing archive horus-2018-02-26T07:34:59 (1/12)
[...]
Analyzing archive horus-2018-04-09T18:32:41 (12/12)
Archive consistency check complete, no problems found.
borg check -v --archives-only  111,51s user 1,55s system 95% cpu 1:57,97 total
```

Still, ```borg check``` just stalls.

**Comment by floli** [comment]
Well, I must apologize, everythink seems to work smooth, you just have to wait some more time and it went though
```
% borg check --debug
using builtin fallback logging configuration
35 self tests completed in 0.07 seconds
SSH command line: ['ssh', '-p', '23', 'u123@u123.your-storagebox.de', 'borg', 'serve', '--umask=077', '--debug']
Starting archive consistency check...
TAM-verified manifest                                                                                                                                                                                                                       
Analyzing archive horus-2018-02-26T07:34:59 (1/12)
[...]
Analyzing archive horus-2018-04-09T18:32:41 (12/12)
RepositoryCache: current items 6549, size 235.35 MB / 2.15 GB, 3686 hits, 6549 misses, 0 slow misses (+0.0s), 0 evictions, 0 ENOSPC hit
Archive consistency check complete, no problems found.
RemoteRepository: 348.21 kB bytes sent, 248.80 MB bytes received, 6577 messages sent
borg check --debug  119,11s user 1,88s system 9% cpu 20:17,61 total
```

**Comment by ThomasWaldmann** [comment]
Before checking the archives (involves client + server), it checks the repo on a lower level (server only).
