### ISSUE TITLE
borg check -v . (Crashed)

### ISSUE THREAD

**Issue by kcciti** [borgbackup/borg#3764]
user@solus ~/borg_backup $ borg break-lock .
user@solus ~/borg_backup $ borg check -v  .
Starting repository check
Starting repository index check
Completed repository check, no problems found.
Starting archive consistency check...
Analyzing archive 20180312 (1/6)
Exception ignored in: <bound method Repository.__del__ of <Repository /home/user/borg_backup>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 173, in __del__
    self.close()
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 415, in close
    self.lock.release()
  File "/usr/lib/python3.6/site-packages/borg/locking.py", line 379, in release
    self._roster.modify(EXCLUSIVE, REMOVE)
  File "/usr/lib/python3.6/site-packages/borg/locking.py", line 278, in modify
    elements.remove(self.id)
KeyError: (('solus@246965752663030', 16667, 0),)
Failed to release the lock /home/user/borg_backup/lock.exclusive (was/is locked, but not by me).
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 152, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 313, in do_check
    verify_data=args.verify_data, save_space=args.save_space):
  File "/usr/lib/python3.6/site-packages/borg/archive.py", line 1183, in check
    self.rebuild_refcounts(archive=archive, first=first, last=last, sort_by=sort_by, glob=glob)
  File "/usr/lib/python3.6/site-packages/borg/archive.py", line 1567, in rebuild_refcounts
    items_buffer.flush(flush=True)
  File "/usr/lib/python3.6/site-packages/borg/archive.py", line 256, in flush
    self.chunks.append(self.write_chunk(chunk))
  File "/usr/lib/python3.6/site-packages/borg/archive.py", line 1370, in add_callback
    cdata = self.key.encrypt(chunk)
  File "/usr/lib/python3.6/site-packages/borg/crypto/key.py", line 371, in encrypt
    self.nonce_manager.ensure_reservation(num_aes_blocks(len(data)))
  File "/usr/lib/python3.6/site-packages/borg/crypto/nonces.py", line 72, in ensure_reservation
    repo_free_nonce = self.get_repo_free_nonce()
  File "/usr/lib/python3.6/site-packages/borg/crypto/nonces.py", line 39, in get_repo_free_nonce
    return self.repository.get_free_nonce()
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 307, in get_free_nonce
    raise AssertionError("bug in code, exclusive lock should exist here")
AssertionError: bug in code, exclusive lock should exist here

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4253, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4185, in run
    return set_ec(func(args))
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 152, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 198, in __exit__
    self.close()
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 415, in close
    self.lock.release()
  File "/usr/lib/python3.6/site-packages/borg/locking.py", line 382, in release
    self._lock.release()
  File "/usr/lib/python3.6/site-packages/borg/locking.py", line 147, in release
    raise NotMyLock(self.path)
borg.locking.NotMyLock: Failed to release the lock /home/user/borg_backup/lock.exclusive (was/is locked, but not by me).

Platform: Linux solus 4.15.15-63.current #1 SMP PREEMPT Sat Apr 7 08:32:34 UTC 2018 x86_64
Linux:   
Borg: 1.1.5  Python: CPython 3.6.4
PID: 16667  CWD: /home/user/borg_backup
sys.argv: ['/usr/bin/borg', 'check', '-v', '.']
SSH_ORIGINAL_COMMAND: None

**Comment by ThomasWaldmann** [comment]
Did you check that there is no borg process running any more before invoking break-lock?

**Comment by kcciti** [comment]
Yes, it happened twice. After hitting the error the first time, I ran a borg break-lock. Then it hit the issue again. FYI, I'm running borg off of a cloud mounted partition - the internet did not disconnect and the total backup size excluding compression was only around 5-10 gigs.

**Comment by ThomasWaldmann** [comment]
Sometimes such cloud filesystems do weird things / malfunction. What fs exactly was it?

**Comment by kcciti** [comment]
I'm not sure what pCloud uses exactly. I believe it's webDAV but uses some sort of implementation that does some caching, uploading mgmt, etc to decrease delays. I use their electron app (https://www.pcloud.com/download-free-online-cloud-file-storage.html) that mount automatically on linux so I don't have to wait until all files get uploaded on there before I can work on them.
