### ISSUE TITLE
Error message in my log file

### ISSUE THREAD

**Issue by ovalseven8** [borgbackup/borg#3806]
In my log file I found this error message.

Just wanted to post it here, so perhaps it looks useful to someone here.
```
WARNING - Error while executing 'prune' command.
self test test_chunkify (borg.testsuite.chunker.ChunkerTestCase) FAILED:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/borg/testsuite/chunker.py", line 17, in test_chunkify
    self.assert_equal(b''.join(parts), data)
AssertionError: b'000[929920 chars]0000010000000000000000000000000000000000000000[11652940 chars]000Y' != b'000[929920 chars]0000000000000000000000000000000000000000000000[11652940 chars]000Y'

self test failed
This is a bug either in Borg or in the package / distribution you use.
```

In the next days, the backup script worked fine then. However, now I find this error every day:

```
Data integrity error: Segment entry checksum mismatch [segment 215, offset 141521471]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4253, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4185, in run
    return set_ec(func(args))
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 152, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 1574, in do_prune
    repository.commit(save_space=args.save_space)
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 430, in commit
    self.compact_segments()
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 705, in compact_segments
    for tag, key, offset, data in self.io.iter_objects(segment, include_data=True):
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 1324, in iter_objects
    read_data=read_data)
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 1411, in _read
    segment, offset))
borg.helpers.IntegrityError: Data integrity error: Segment entry checksum mismatch [segment 215, offset 141521471]

Platform: Linux rechner 4.16.6-1-ARCH #1 SMP PREEMPT Mon Apr 30 12:30:03 UTC 2018 x86_64
Linux: arch  
Borg: 1.1.5  Python: CPython 3.6.5
PID: 5069  CWD: /
sys.argv: ['/sbin/borg', 'prune', '/mnt/nas/backup-desktop', '--prefix', 'rechner-', '--keep-daily=7', '--keep-weekly=4', '--keep-monthly=12']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment]
If I had to bet, I'ld say your RAM is faulty.

**Comment by ovalseven8** [comment]
Ah, cool. I'll later post the whole test, thanks :)

```
sudo smartctl -dsat -a /dev/sdb -s on

smartctl 6.6 2017-11-05 r4594 [x86_64-linux-4.16.6-1-ARCH] (local build)
Copyright (C) 2002-17, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Device Model:     TOSHIBA MQ01ABD100M
Serial Number:    86F3S6WLS
LU WWN Device Id: 5 000039 73570534d
Firmware Version: AX101U
User Capacity:    1.000.204.886.016 bytes [1,00 TB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    5400 rpm
Form Factor:      2.5 inches
Device is:        Not in smartctl database [for details use: -P showall]
ATA Version is:   ATA8-ACS (minor revision not indicated)
SATA Version is:  SATA 2.6, 3.0 Gb/s (current: 3.0 Gb/s)
Local Time is:    Mon May  7 09:16:34 2018 CEST
SMART support is: Available - device has SMART capability.
SMART support is: Enabled

=== START OF ENABLE/DISABLE COMMANDS SECTION ===
SMART Enabled.

=== START OF READ SMART DATA SECTION ===
SMART Status not supported: Incomplete response, ATA output registers missing
SMART overall-health self-assessment test result: PASSED
Warning: This result is based on an Attribute check.

General SMART Values:
Offline data collection status:  (0x00)	Offline data collection activity
					was never started.
					Auto Offline Data Collection: Disabled.
Self-test execution status:      (   0)	The previous self-test routine completed
					without error or no self-test has ever 
					been run.
Total time to complete Offline 
data collection: 		(  120) seconds.
Offline data collection
capabilities: 			 (0x5b) SMART execute Offline immediate.
					Auto Offline data collection on/off support.
					Suspend Offline collection upon new
					command.
					Offline surface scan supported.
					Self-test supported.
					No Conveyance Self-test supported.
					Selective Self-test supported.
SMART capabilities:            (0x0003)	Saves SMART data before entering
					power-saving mode.
					Supports SMART auto save timer.
Error logging capability:        (0x01)	Error logging supported.
					General Purpose Logging supported.
Short self-test routine 
recommended polling time: 	 (   2) minutes.
Extended self-test routine
recommended polling time: 	 ( 247) minutes.
SCT capabilities: 	       (0x003d)	SCT Status supported.
					SCT Error Recovery Control supported.
					SCT Feature Control supported.
					SCT Data Table supported.

SMART Attributes Data Structure revision number: 16
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
  1 Raw_Read_Error_Rate     0x000b   100   100   050    Pre-fail  Always       -       0
  2 Throughput_Performance  0x0005   100   100   050    Pre-fail  Offline      -       0
  3 Spin_Up_Time            0x0027   100   100   001    Pre-fail  Always       -       2927
  4 Start_Stop_Count        0x0032   100   100   000    Old_age   Always       -       1011
  5 Reallocated_Sector_Ct   0x0033   100   100   050    Pre-fail  Always       -       0
  7 Seek_Error_Rate         0x000b   100   100   050    Pre-fail  Always       -       0
  8 Seek_Time_Performance   0x0005   100   100   050    Pre-fail  Offline      -       0
  9 Power_On_Hours          0x0032   067   067   000    Old_age   Always       -       13527
 10 Spin_Retry_Count        0x0033   120   100   030    Pre-fail  Always       -       0
 12 Power_Cycle_Count       0x0032   100   100   000    Old_age   Always       -       23
191 G-Sense_Error_Rate      0x0032   100   100   000    Old_age   Always       -       0
192 Power-Off_Retract_Count 0x0032   100   100   000    Old_age   Always       -       3
193 Load_Cycle_Count        0x0032   100   100   000    Old_age   Always       -       2432
194 Temperature_Celsius     0x0022   100   100   000    Old_age   Always       -       23 (Min/Max 11/35)
196 Reallocated_Event_Count 0x0032   100   100   000    Old_age   Always       -       0
197 Current_Pending_Sector  0x0032   100   100   000    Old_age   Always       -       0
198 Offline_Uncorrectable   0x0030   100   100   000    Old_age   Offline      -       0
199 UDMA_CRC_Error_Count    0x0032   200   200   000    Old_age   Always       -       0
220 Disk_Shift              0x0002   100   100   000    Old_age   Always       -       0
222 Loaded_Hours            0x0032   100   100   000    Old_age   Always       -       35
223 Load_Retry_Count        0x0032   100   100   000    Old_age   Always       -       0
224 Load_Friction           0x0022   100   100   000    Old_age   Always       -       0
226 Load-in_Time            0x0026   100   100   000    Old_age   Always       -       274
240 Head_Flying_Hours       0x0001   100   100   001    Pre-fail  Offline      -       0

SMART Error Log Version: 1
No Errors Logged

SMART Self-test log structure revision number 1
No self-tests have been logged.  [To run self-tests, use: smartctl -t]

SMART Selective self-test log data structure revision number 1
 SPAN  MIN_LBA  MAX_LBA  CURRENT_TEST_STATUS
    1        0        0  Not_testing
    2        0        0  Not_testing
    3        0        0  Not_testing
    4        0        0  Not_testing
    5        0        0  Not_testing
Selective self-test flags (0x0):
  After scanning selected spans, do NOT read-scan remainder of disk.
If Selective self-test is pending on power-up, resume after 0 minute delay.
```

**Comment by ThomasWaldmann** [comment]
The SMART data looks very good. You really should check your RAM with `memtest86+`.

**Comment by ovalseven8** [comment]
Overnight, I run `memcheck86`. The test took 7:32 h, 48/48 tests passed, 0 errors. So the RAM should be fine.

Thanks for your help :)

**Comment by ThomasWaldmann** [comment]
@ovalseven8 please check if you used `memtest86+` (mem-test-86-plus) from http://www.memtest.org/ and the latest version 5.01.

I use this for years and it finds memory errors, but I know there are other memory testers which are crap and don't find errors in some cases.
