### ISSUE TITLE
Borg hangs infinitely on backup to existing repo. Works for newly created one.

### ISSUE THREAD

**Issue by ybieri** [borgbackup/borg#3858]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue/Question

#### Your borg version (borg -V).
borg 1.1.5 (client and server)

#### Operating system (distribution) and version.
Client: Arch Linux 4.16.10-1, Server: Synology Nas DSM 6.1.7-15284

#### How much data is handled by borg?
~100 GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```
#!/bin/sh

# Setting this, so the repo does not need to be given on the commandline:
export BORG_REPO=ssh://backup@nas/~/backup/backup_arch

# Setting this, so you won't be asked for your repository passphrase:
export BORG_PASSPHRASE='mysupersecretpassword'

#Setting remote path
export BORG_REMOTE_PATH='/usr/local/bin/borg'


# some helpers and error handling:
info() { printf "\n%s %s\n\n" "$( date )" "$*" >&2; }
trap 'echo $( date ) Backup interrupted >&2; exit 2' INT TERM

notify-send "Starting backup"

# Backup the most important directories into an archive named after
# the machine this script is currently running on:

/usr/bin/borg create                \
    --verbose                       \
    --filter AME                    \
    --list                          \
    --stats                         \
    --show-rc                       \
    --compression lz4               \
    --exclude-caches                \
    --exclude '/home/*/.cache/*'    \
    --exclude /home/$USER/Movies    \
    --exclude /home/$USER/Downloads \
    --exclude /home/$USER/VirtualBox\ VMs \
    --exclude *.img                 \
    --exclude *.iso                 \
    ::'backup-{now:%Y-%m-%d}'       \
    /home/myusername/                     \

backup_exit=$?

info "Pruning repository"

# Use the `prune` subcommand to maintain 7 daily, 4 weekly and 6 monthly
# archives of THIS machine. The '{hostname}-' prefix is very important to
# limit prune's operation to this machine's archives and not apply to
# other machines' archives also:

/usr/bin/borg prune                          \
    --list                          \
    --prefix '{hostname}-'          \
    --show-rc                       \
    --keep-daily    7               \
    --keep-weekly   4               \
    --keep-monthly  6               \
    --keep-yearly   1               

prune_exit=$?

# use highest exit code as global exit code
global_exit=$(( backup_exit > prune_exit ? backup_exit : prune_exit ))


if [ ${global_exit} -eq 1 ];
then
    message="Backup and/or Prune finished with a warning"
    info $message
    notify-send "$message"
fi

if [ ${global_exit} -gt 1 ];
then
    message="Backup and/or Prune finished with an error"
    info $message
    notify-send "$message"
fi

notify-send "Backup finished"

exit ${global_exit}

```

## Describe the problem you're observing.
I'm running borg to backup my laptop to my nas using above script and cron. This all has been working fine. This week I noticed that I haven't been doing backups since March (added email notifications now). This was because of a bad change to my ssh config. Now that I fixed this, my backup hangs forever in the create phase. 

To verify that it is not a problem with my script or too many new data I created and initialized a new repo on my nas and can backup all my data to that without a problem using my script. But I cannot continue/increment my backup from March, meaning I cannot create new archives in that repository.  Journalctl does not show any errors, htop shows that the script is running but it is not using any resources at all.

I'm sorry that I can only post this vague of a description, but I'm not seeing any errors anywhere. 

Does anyone have an idea what other steps I could take to troubleshoot or has an idea, why the backup is not working on the existing repository? I'm glad for any help.

**Comment by ThomasWaldmann** [comment]
Please post the output of the script before it is "hanging". How long did you wait?

Also post a ls -lR of your client-side borg cache directory and of your server-side repo directory for the problematic repo (at a point in time when no borg is active). From the ls output of the repo, remove all ls output relating to files below the data/ subdirectory.

**Comment by ThomasWaldmann** [comment]
BTW, you need to use single quotes for `*.img` and `*.iso` or it will do something very different from what you intended IF there are such files in the current directory. See the other excludes with wildcards a few lines above.

**Comment by ThomasWaldmann** [comment]
I only wanted the cache listing of the problematic repo.

As you gave me all of them, I also need the repository id, see `borg config REPO id` output (or look manually into the config file in the repo).

**Comment by ybieri** [comment]
Oh language ambiguity. Here is the one of the corresponding repo:

```
8c20b2bbf3ac4be70d96f5850e9823df97a1b2ff49ffa0f8406a122d68dcc230:
total 52280
-rw------- 1 yves users 33334726 Mar  7 00:02 chunks
drwx------ 2 yves users     4096 Oct 17  2017 chunks.archive.d
-rw------- 1 yves users      597 Mar  7 00:02 config
-rw------- 1 yves users 20173920 Mar  7 00:02 files
drwx------ 2 yves users     4096 Mar 14 00:00 lock.exclusive
-rw------- 1 yves users       60 Mar 14 00:00 lock.roster
-rw------- 1 yves users       68 Oct 17  2017 README

8c20b2bbf3ac4be70d96f5850e9823df97a1b2ff49ffa0f8406a122d68dcc230/chunks.archive.d:
total 0

8c20b2bbf3ac4be70d96f5850e9823df97a1b2ff49ffa0f8406a122d68dcc230/lock.exclusive:
total 0
-rw------- 1 yves users 0 Mar 14 00:00 arch.mydomain@220295153851636.4362-0
```

Hope I got all the correct output this time.

**Comment by ThomasWaldmann** [comment]
OK, looks like there is an exclusive lock in the cache dir (but not in the repo).

Is the process with PID 4362 on that machine (see filename in lock.exclusive dir) still alive?

If not, use `borg break-lock REPO`.

**Comment by ybieri** [comment]
The process was not used anymore, so i broke the lock.

Now unfortunately I get an integrity check failure:

```
./borg_backup

Thu May 24 18:11:12 CEST 2018 Starting backup

Killed stale lock arch@220295153851636.28471-0.
Removed stale exclusive roster lock for pid 28471.
Removed stale exclusive roster lock for pid 28471.
File failed integrity check: /home/yves/.cache/borg/8c20b2bbf3ac4be70d96f5850e9823df97a1b2ff49ffa0f8406a122d68dcc230/chunks
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4253, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4185, in run
    return set_ec(func(args))
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 152, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 540, in do_create
    cache_mode=args.files_cache_mode, ignore_inode=args.ignore_inode) as cache:
  File "/usr/lib/python3.6/site-packages/borg/cache.py", line 379, in __new__
    return local()
  File "/usr/lib/python3.6/site-packages/borg/cache.py", line 373, in local
    lock_wait=lock_wait, cache_mode=cache_mode)
  File "/usr/lib/python3.6/site-packages/borg/cache.py", line 456, in __init__
    self.open()
  File "/usr/lib/python3.6/site-packages/borg/cache.py", line 504, in open
    self.rollback()
  File "/usr/lib/python3.6/site-packages/borg/cache.py", line 609, in rollback
    self._do_open()
  File "/usr/lib/python3.6/site-packages/borg/cache.py", line 494, in _do_open
    self.chunks = ChunkIndex.read(fd)
  File "/usr/lib/python3.6/site-packages/borg/crypto/file_integrity.py", line 193, in __exit__
    self.hash_part('final', is_final=True)
  File "/usr/lib/python3.6/site-packages/borg/crypto/file_integrity.py", line 188, in hash_part
    raise FileIntegrityError(self.path)
borg.crypto.file_integrity.FileIntegrityError: File failed integrity check: /home/yves/.cache/borg/8c20b2bbf3ac4be70d96f5850e9823df97a1b2ff49ffa0f8406a122d68dcc230/chunks

Platform: Linux arch 4.16.10-1-ARCH #1 SMP PREEMPT Mon May 21 07:57:23 UTC 2018 x86_64
Linux: arch  
Borg: 1.1.5  Python: CPython 3.6.5
PID: 4850  CWD: /home/yves/scripts
sys.argv: ['/usr/bin/borg', 'create', '--verbose', '--filter', 'AME', '--list', '--stats', '--show-rc', '--compression', 'lz4', '--exclude-caches', '--exclude', '/home/*/.cache/*', '--exclude', '/home/yves/Movies', '--exclude', '/home/yves/Downloads', '--exclude', '/home/yves/VirtualBox VMs', '--exclude', '*.img', '--exclude', '*.iso', '::backup-{now:%Y-%m-%d}', '/home/yves/']
SSH_ORIGINAL_COMMAND: None

terminating with error status, rc 2
```

I renamed the chunks file but then I get the error that the file does not exist. A quick google search did yield some similar results, but none that could help me resolve the issue. Any idea on how I can get around the integrity check?

**Comment by ThomasWaldmann** [comment]
OK, sounds like you maybe had some power issue or other fatal circumstances that led to that issue.
```
borg delete --cache-only REPO
```
This gets rid of the cache.

You may have to answer some questions when doing the first backup after that and it will be slow.

**Comment by ybieri** [comment]
Thank you. Could be a corruption of some kind.
I ran your command, but unfortunately encounter another error:

```
Thu May 24 21:44:28 CEST 2018 Starting backup

Synchronizing chunks cache...
Archives: 104, w/ cached Idx: 84, w/ outdated Idx: 0, w/o cached Idx: 20.
Reading cached archive chunk index for backup-2017-10-20 ...
Merging into master chunks index ...
Reading cached archive chunk index for backup-2017-10-29 ...
Merging into master chunks index ...
Reading cached archive chunk index for backup-2017-10-31 ...
Merging into master chunks index ...
Reading cached archive chunk index for backup-2017-11-01 ...
Merging into master chunks index ...
Reading cached archive chunk index for backup-2017-11-02 ...
Merging into master chunks index ...
.
.
.
Reading cached archive chunk index for backup-2018-02-13 ...
Merging into master chunks index ...
Reading cached archive chunk index for backup-2018-02-14 ...
Merging into master chunks index ...
Reading cached archive chunk index for backup-2018-02-15 ...
Merging into master chunks index ...
Fetching and building archive index for backup-2018-02-16 ...
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4253, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4185, in run
    return set_ec(func(args))
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 152, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 540, in do_create
    cache_mode=args.files_cache_mode, ignore_inode=args.ignore_inode) as cache:
  File "/usr/lib/python3.6/site-packages/borg/cache.py", line 379, in __new__
    return local()
  File "/usr/lib/python3.6/site-packages/borg/cache.py", line 373, in local
    lock_wait=lock_wait, cache_mode=cache_mode)
  File "/usr/lib/python3.6/site-packages/borg/cache.py", line 466, in __init__
    self.sync()
  File "/usr/lib/python3.6/site-packages/borg/cache.py", line 850, in sync
    self.chunks = create_master_idx(self.chunks)
  File "/usr/lib/python3.6/site-packages/borg/cache.py", line 804, in create_master_idx
    fetch_and_build_idx(archive_id, decrypted_repository, archive_chunk_idx)
  File "/usr/lib/python3.6/site-packages/borg/cache.py", line 713, in fetch_and_build_idx
    sync.feed(data)
  File "src/borg/hashindex.pyx", line 524, in borg.hashindex.CacheSynchronizer.feed
ValueError: cache_sync_feed failed: Unexpected object: integer

Platform: Linux arch 4.16.10-1-ARCH #1 SMP PREEMPT Mon May 21 07:57:23 UTC 2018 x86_64
Linux: arch  
Borg: 1.1.5  Python: CPython 3.6.5
PID: 18455  CWD: /home/yves/scripts
sys.argv: ['/usr/bin/borg', 'create', '--verbose', '--filter', 'AME', '--list', '--stats', '--show-rc', '--compression', 'lz4', '--exclude-caches', '--exclude', '/home/*/.cache/*', '--exclude', '/home/yves/Movies', '--exclude', '/home/yves/Downloads', '--exclude', '/home/yves/VirtualBox VMs', '--exclude', '*.img', '--exclude', '*.iso', '::backup-{now:%Y-%m-%d}', '/home/yves/']
SSH_ORIGINAL_COMMAND: None

terminating with error status, rc 2
```

Do you know by any chance what do to or should I have a look at the source code?

**Comment by ThomasWaldmann** [comment]
Looks like corruption happening somewhere. Check memory, disk, ... (see borg docs).

**Comment by ybieri** [comment]
Thanks that did the trick. 
```
borg check --repair REPO
```
Now the repository works again and my script has improved a lot. Thank you very much for your help!

**Comment by ThomasWaldmann** [comment]
I rather meant memtest86+ and smartctl.

Guess we are finished here, closing.
