### ISSUE TITLE
Borg files owned by root in user directory

### ISSUE THREAD

**Issue by cromoteca** [borgbackup/borg#3864]
## Have you checked borgbackup docs, FAQ, and open Github issues?

yes

## Is this a BUG / ISSUE report or a QUESTION?

question, maybe an issue

#### Your borg version (borg -V).
1.1.5
#### Operating system (distribution) and version.
Ubuntu 18.04 Desktop
#### Hardware / network configuration, and filesystems used.
lvm/luks/ext4
#### How much data is handled by borg?
300GB
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg init -e repokey borg-test

## Describe the problem you're observing.
I got the sample script suggested at https://borgbackup.readthedocs.io/en/stable/quickstart.html#automating-backups and customized it a bit. I use it to backup my laptop to a CentOS machine. So far so good. I run the script with sudo as I want to backup the full system.

Problem is: my dirs ~/.config/borg and ~/.cache/borg are owned by root. I tried to create a repo for a test in my home dir, but no way: I'm forced to keep using sudo. I expected sudo files to be created in /root.

#### Include any warning/errors/backtraces from the system logs

```
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4253, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4185, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 152, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 266, in do_init
    key = key_creator(repository, args)
  File "/usr/lib/python3/dist-packages/borg/crypto/key.py", line 111, in key_creator
    return key.create(repository, args)
  File "/usr/lib/python3/dist-packages/borg/crypto/key.py", line 676, in create
    key.init_ciphers()
  File "/usr/lib/python3/dist-packages/borg/crypto/key.py", line 420, in init_ciphers
    self.nonce_manager = NonceManager(self.repository, self.enc_cipher, manifest_nonce)
  File "/usr/lib/python3/dist-packages/borg/crypto/nonces.py", line 22, in __init__
    self.nonce_file = os.path.join(get_security_dir(self.repository.id_str), 'nonce')
  File "/usr/lib/python3/dist-packages/borg/helpers.py", line 502, in get_security_dir
    os.makedirs(security_dir)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/luciano/.config/borg/security'

Platform: Linux lvernaschi 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64
Linux: Ubuntu 18.04 bionic
Borg: 1.1.5  Python: CPython 3.6.5
PID: 14615  CWD: /home/luciano/Public
sys.argv: ['/usr/bin/borg', 'init', '-e', 'repokey', 'borg-test']
SSH_ORIGINAL_COMMAND: None



$ sudo ls -al ~/{.config,.cache}/borg
/home/luciano/.cache/borg:
total 20
drwx------  4 root    root    4096 mai   27 22:24 .
drwx------ 35 luciano luciano 4096 mai   27 13:25 ..
drwx------  3 root    root    4096 mai   28 02:47 4217bb56c8a00b08e077e1c011cbb4fceabb84b54058a936c26f594b6544735e
drwx------  4 root    root    4096 mai   27 10:33 5b4724cf6cd4ca0e3a3fb6a418ea94ec0cc7064a9ad12e437e24f6b220cb7e2a
-rw-------  1 root    root     194 mai   27 10:30 CACHEDIR.TAG

/home/luciano/.config/borg:
total 12
drwx------  3 root    root    4096 mai   27 10:30 .
drwx------ 35 luciano luciano 4096 mai   27 20:19 ..
drwx------  4 root    root    4096 mai   27 22:24 security
```

**Comment by jdchristensen** [comment]
Maybe you need this:

```    -H, --set-home
                 Request that the security policy set the HOME environment
                 variable to the home directory specified by the target user's
                 password database entry.  Depending on the policy, this may
                 be the default behavior.
```

**Comment by cromoteca** [comment]
Good to know, I will use that. Anyway, Ubuntu being so popular, maybe this should be taken into account, as creating root files into user dir is not ideal. I'm not going to close the issue, but I understand if you do.

**Comment by ThomasWaldmann** [comment]
What @jdchristensen says sounds like the correct solution for this issue. Or invoke your script directly from root (or via a root crontab entry).

What also helps here (and for quite some other use cases) is to `sudo -i` to get a root login shell:

```
tw@tux:~$ sudo -i env |grep HOME
HOME=/root
tw@tux:~$ sudo env |grep HOME
HOME=/home/tw
```

**Comment by ThomasWaldmann** [comment]
Guess this is solved.
