### ISSUE TITLE
Cannot mount backup for user (fuse)

### ISSUE THREAD

**Issue by blueyed** [borgbackup/borg#3885]
I am trying to mount the backup for a specific user.

I've tried the following in `/etc/fstab`:

```
/var/backup/bork/system /mnt/backup fuse.borgfs defaults,noauto,user,user_id=1000,group_id=1000,uid=1000 0 0
```

I can use `borg mount /var/backup/borg /mnt/backup` as a user, but it is owned then by root.

Using `--debug` emits:
```
using builtin fallback logging configuration
35 self tests completed in 0.11 seconds
Verified integrity of /var/backup/borg/index.179
TAM-verified manifest
security: read previous location '/var/backup/borg'
security: read manifest timestamp '2018-06-06T15:03:42.881134'
security: determined newest manifest timestamp as 2018-06-06T15:03:42.881134
security: repository checks ok, allowing access
mount data cache capacity: 4 chunks
Mounting filesystem
Initializing llfuse
Calling fuse_mount
Calling fuse_lowlevel_new
Calling fuse_session_add_chan
```

`/etc/mtab` contains `borgfs /mnt/backup fuse ro,nosuid,nodev,relatime,user_id=0,group_id=0 0 0` then (note `user_id` and `group_id` being 0 there).

btw: calling `mount /mnt/backup` directly emits: `Repository /var/backup/bork does not exist.`.

**Comment by ThomasWaldmann** [comment]
You use 1.1.5?

I recently added support for uid, gid and umask to borg mount.
It is in current 1.1-maint branch (and master), but not released yet. Will be in 1.1.6.

**Comment by ThomasWaldmann** [comment]
1.1.6 is released, see changelog for new borg mount options.

I am closing this now, if 1.1.6 doesn't fix your issue, please open a new ticket.

**Comment by blueyed** [comment]
Great news.

Just for the record this works for me:

> sudo borg mount -o uid=1000,allow_other /var/backup/borg /mnt/backup

`allow_other` is required since the filesystem owner is root.

Using `mount /mnt/backup` directly (via fstab) fails, because the repo is owned by root:

```
% mount /mnt/backup                                                                                                                                          🐍?
Failed to create/acquire the lock /var/backup/borg/lock.exclusive ([Errno 13] Permission denied: '/var/backup/borg/lock.exclusive').
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4312, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4244, in run
    return set_ec(func(args))
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 1342, in do_mount
    return self._do_mount(args)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 137, in wrapper
    with repository:
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 184, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 381, in open
    self.lock = Lock(os.path.join(path, 'lock'), exclusive, timeout=lock_wait, kill_stale_locks=hostname_is_unique()).acquire()
  File "/usr/lib/python3.6/site-packages/borg/locking.py", line 349, in acquire
    with self._lock:
  File "/usr/lib/python3.6/site-packages/borg/locking.py", line 113, in __enter__
    return self.acquire()
  File "/usr/lib/python3.6/site-packages/borg/locking.py", line 137, in acquire
    raise LockFailed(self.path, str(err)) from None
borg.locking.LockFailed: Failed to create/acquire the lock /var/backup/borg/lock.exclusive ([Errno 13] Permission denied: '/var/backup/borg/lock.exclusive').
```

This is reasonable.

And using `/var/backup/borg /mnt/backup fuse.borgfs defaults,noauto,user,uid=1000,allow_other 0 0` in `/etc/fstab` allows for `sudo mount /mnt/backup` and the directory being readable by the user.

Thanks!
