### ISSUE TITLE
"does not look like a Borg cache" error on pruning

### ISSUE THREAD

**Issue by dpantel** [borgbackup/borg#3912]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG / ISSUE

## System information. For client/server mode post info for both machines.

- Platform: Linux asylum 4.13.0-45-generic ~16.04.1-Ubuntu SMP x86_64
- Linux: LinuxMint 18.2 sonya
- Borg: 1.1.5  Python: CPython 3.5.2
- FS: source data on ext4, archive on btrfs
- All archives: 561.22 GB (orig) / 463.21 GB (compressed) / 9.46 GB (dedup)
- Chunk index: 32771 (unique) / 3701498 (total)

## Describe the problem you're observing.

Several days ago, my hourly borg/borgmatic script started throwing exceptions on purge.  I can execute both the borgmatic script and the cronjob manually (as root) without issue.  I can also run the prune command manually without issue.  But when it runs unattended, I get the following error:

```
Sun Jun 17 13:17:01 MDT 2018 - Starting a backup job.
/mnt/@snapshots/borg: Pruning archives
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4253, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4185, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 143, in wrapper
    assert_secure(repository, kwargs['manifest'])
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 206, in assert_secure
    sm.assert_secure(manifest, manifest.key)
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 171, in assert_secure
    with cache_config:
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 238, in __enter__
    self.open()
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 262, in open
    self.load()
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 267, in load
    self._check_upgrade(self.config_path)
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 326, in _check_upgrade
    raise Exception('%s does not look like a Borg cache.' % config_path) from None
Exception: /root/.cache/borg/eb1f9b3234podifvkspdoisabd81f/config does not look like a Borg cache.

Platform: Linux asylum 4.13.0-45-generic #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64
Linux: LinuxMint 18.2 sonya
Borg: 1.1.5  Python: CPython 3.5.2
PID: 18340  CWD: /
sys.argv: ['/usr/bin/borg', 'prune', '/mnt/@snapshots/borg', '--keep-within', '3H', '--keep-hourly', '48', '--keep-daily', '14', '--keep-weekly', '12', '--keep-monthly', '6', '--keep-yearly', '1', '--prefix', 'archive.', '--info', '--stats']
SSH_ORIGINAL_COMMAND: None

/etc/borgmatic/config.yaml: Running command for on-error hook
Sun Jun 17 13:17:01 MDT 2018 - Error while creating a backup.
Command '('borg', 'prune', '/mnt/@snapshots/borg', '--keep-within', '3H', '--keep-hourly', '48', '--keep-daily', '14', '--keep-weekly', '12', '--keep-monthly', '6', '--keep-yearly', '1', '--prefix', 'archive.', '--info', '--stats')' returned non-zero exit status 2
```

This is my cron script

```
#!/bin/sh

# tell borg to ignore the unknown/unencrypted repository issue
export BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK=yes

# run borg (via borgmatic) hourly
exec /usr/local/bin/borgmatic -v 1 >> /var/log/borg.log 2>&1
```

**Comment by ThomasWaldmann** [comment]
Maybe you use a different environment (environment variables, see output of `set` shell command) when using borg manually and from cron.

If. e.g. HOME or USER points to different values, it will use different places for storing the cache.

How does this file look like?: `/root/.cache/borg/eb1f9b3234podifvkspdoisabd81f/config`

Also, there could be a different PATH set up for your interactive use and for cron and you might even use different borg binaries (borg versions) for both cases, e.g. if you had installed one to /usr/bin and another to /usr/local/bin.

**Comment by dpantel** [comment]
The config file is zero-sized. 

Only one borg binary is installed.

I don't really run borg manually.  I've always run it with the same script and only recently started seeing issues.  I agree it's probably the environment.  As a test I can run borg as root without issues.  When I substitute the environment for the the cron one, it failes.

Any ideas on what I may be missing from the cron environment?

**Comment by ThomasWaldmann** [comment]
Hmm, zero sized cache config is definitely not good. Was there some incident leading to this (like power loss, sudden reboot, fs issues)? Guess killing the cache is easiest.

About cron: just have a look at the env vars and always use same user (same HOME, USER).

**Comment by dpantel** [comment]
Updates:

The cache in /root/.cache/borg was FUBAR; not sure if power outage or not.

However, I had a borg cache dir in /home/user/.cache/borg that was not only fine, but also had mod-times of the last working archive.  I copied that directory into the /root/... directory, et voilà -- it now works.

Now for some oddities (at least to me).

Running borg with `run-parts` from /etc/cron.hourly/runborg says it uses /root/.cache, /root/.config directories in the debug messages.  BUT; the file mod times in /home/user/.cache/borg also change with these runs, which makes no sense.

Running borg with sudo as user only changes the file in /home/user/... and not in /root/...

Does this behavior make sense to you?

**Comment by ThomasWaldmann** [comment]
`sudo -i` maybe?

**Comment by dpantel** [comment]
Ok, last question.

Where else might borg store its cache files?  Because both the /root/... and the /home/user/... locations show mod times from my last manual run (yesterday), but borg (via cron/run-parts) has created several more archives since then and they show differences.

**Comment by ThomasWaldmann** [comment]
if you do not tell it otherwise (via env var BORG_CACHE_DIR), it is in the home dir.

**Comment by mnpenner** [comment]
Well...what's the answer here? I also have a 0-byte cache file. Looks like I'm a little low on disk space, perhaps that's related. But regardless, how do I recover from this? Just delete the cache...?

**Comment by ThomasWaldmann** [comment]
A cache can always be recreated from original data (and this is automatically done if there is no cache).

So if your cache is corrupt, just delete it.

Also, read the FAQ about the trick to use less disk space for the cache or move the cache to some bigger filesystem.

**Comment by CyberShadow** [comment]
I also saw this when I accidentally let my filesystem fill up.

Ideally borg should not corrupt its state in case of disk-full conditions, but simply fail and exit. Even if the cache does not have any important data, this still puts borg into a state that it cannot recover from by itself, requiring manual intervention, which means missed backups.

**Comment by ThomasWaldmann** [comment]
@CyberShadow can you add the borg version you have seen this for?

**Comment by CyberShadow** [comment]
@ThomasWaldmann 1.2.0

**Comment by ThomasWaldmann** [comment]
Can you post the precise commands you used and the traceback you got?

**Comment by CyberShadow** [comment]
The command was

    borg create --sparse --chunker-params fixed,4194304 --compression=auto,zstd,9 --one-file-system -v --stats --progress ssh://hs1/./borg/home::"$prefix":"$(basename "$dir")"-"$date" "$dir"/

Regretfully I did not save a copy of the stack trace; however, the error message did end with `.../config does not look like a Borg cache.`, and the indicated file had zero bytes, and I did fill up my filesystem not too long before.

Naively I would suggest to write to `config.new`, sync, and rename over `config`; sorry if that's not very helpful.

**Comment by T-X** [comment]
Got the same issue here. Could have been caused by either the laptop battery running out of power or the local laptop's disk running full, both had happened to me in the last weeks I think. Also had to run "borg break-lock" to get borg running again at all (which I did after checking that systemd timers were stopped and that no borg process was running in the background). Trace looks like this for me:

```
Tue 14 Jun 11:30:39 CEST 2022 Starting backup

Remote: ssh: connect to host <ipv6-address> port 22: Network is unreachable
Connection closed by remote host. Is borg working on the server?
terminating with error status, rc 2

Tue 14 Jun 11:30:39 CEST 2022 Pruning repository

Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 5089, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 5020, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 174, in wrapper
    assert_secure(repository, kwargs['manifest'], self.lock_wait)
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 209, in assert_secure
    sm.assert_secure(manifest, manifest.key, lock_wait=lock_wait)
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 174, in assert_secure
    with cache_config:
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 246, in __enter__
    self.open()
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 269, in open
    self.load()
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 275, in load
    self._check_upgrade(self.config_path)
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 334, in _check_upgrade
    raise Exception('%s does not look like a Borg cache.' % config_path) from None
Exception: /home/<user>/.cache/borg/a8b392a0a74a74ce6f86ffb5157bc0ce4f12fca5a4e8e12726b933a8fa36131a/config does not look like a Borg cache.

Platform: Linux linus-work 5.17.0-3-amd64 #1 SMP PREEMPT Debian 5.17.11-1 (2022-05-26) x86_64
Linux: Unknown Linux  
Borg: 1.2.0  Python: CPython 3.10.4 msgpack: 1.0.3 fuse: pyfuse3 3.2.0 [pyfuse3,llfuse]
PID: 2829218  CWD: /home/linus
sys.argv: ['/usr/bin/borg', 'prune', '--list', '--prefix', '{hostname}-', '--show-rc', '--keep-daily', '7', '--keep-weekly', '4', '--keep-monthly', '6', '--keep-yearly', '10']
SSH_ORIGINAL_COMMAND: None

terminating with error status, rc 2

Tue 14 Jun 11:30:48 CEST 2022 Backup and/or Prune finished with an error
```

Borg version is as provided by Debian Sid, 1.2.0-1+b2.

This cache config file is empty / 0 bytes size:

```
$ file /home/<user>/.cache/borg/a8b392a0a74a74ce6f86ffb5157bc0ce4f12fca5a4e8e12726b933a8fa36131a/config
/home/<user>/.cache/borg/a8b392a0a74a74ce6f86ffb5157bc0ce4f12fca5a4e8e12726b933a8fa36131a/config: empty
```


> So if your cache is corrupt, just delete it.

So should I delete the whole borg folder in ~/.cache/borg or just ~/.cache/borg/a8b392a0a74a74ce6f86ffb5157bc0ce4f12fca5a4e8e12726b933a8fa36131a/ in that case?

**Comment by ThomasWaldmann** [comment]
The official way to delete the cache of a specific repo is:
```
borg delete --cache-only REPO
```

**Comment by prahal** [comment]
@comdtx did you run  `borg delete --cache-only REPO` as is?
Ie, you should replace REPO with the repository path.

**Comment by ThomasWaldmann** [comment]
We recently merged a PR that rebuilds the cache if corrupt.
