### ISSUE TITLE
borg upgrade fails: Exception: hashindex_read failed

### ISSUE THREAD

**Issue by Stunkymonkey** [borgbackup/borg#393]
I just wanted to upgrade my attic-backups to borg backups
I did the following steps:
```
borg upgrade /media/user/drive/Backup/attic/home.attic/
mv /media/user/drive/Backup/attic/ /media/user/drive/Backup/borg/
mv  /media/user/drive/Backup/attic/home.attic/  /media/user/drive/Backup/attic/home.borg/
borg list /media/user/drive/Backup/attic/home.borg/

hashindex: /media/user/drive/Backup/borg/home.borg/index.2982: Unknown MAGIC in header
borg: Error: Local Exception.
Traceback (most recent call last):
  File "/vagrant/borg/borg/borg/archiver.py", line 1030, in main
  File "/vagrant/borg/borg/borg/archiver.py", line 986, in run
  File "/vagrant/borg/borg/borg/archiver.py", line 367, in do_list
  File "/vagrant/borg/borg/borg/helpers.py", line 64, in load
  File "/vagrant/borg/borg/borg/repository.py", line 373, in get
  File "/vagrant/borg/borg/borg/repository.py", line 163, in open_index
  File "borg/hashindex.pyx", line 55, in borg.hashindex.IndexBase.read (borg/hashindex.c:1221)
  File "borg/hashindex.pyx", line 43, in borg.hashindex.IndexBase.__cinit__ (borg/hashindex.c:1021)
Exception: hashindex_read failed

borg: Exiting with failure status due to previous errors
```

Is there any fix? (borg create also fails)
I used the version: 0.27.0

**Comment by ThomasWaldmann** [comment]
Can you start from scratch with 0.28.1? Just in case the issue already was fixed.

**Comment by Stunkymonkey** [comment]
i forgot to copy the backup before is upgraded, sorry
the data is not very important, but it would be nice

**Comment by ThomasWaldmann** [comment]
Well, then it is too late...

You can try to delete index.NNNN and hints.NNNN and then run borg check on the repo.

**Comment by Stunkymonkey** [comment]
```$ borg check home.borg
Starting repository check...
Repository check complete, no problems found.
Starting archive consistency check...
Analyzing archive 2015_11_04_21_28_55 (9/9)
Analyzing archive 2015_10_30_19_22_42 (8/9)
Analyzing archive 2015_10_14_21_51_38 (7/9)
Analyzing archive 2015_10_11_01_51_40 (6/9)
Analyzing archive 2015_09_29_02_36_42 (5/9)
Analyzing archive 2015_09_26_03_31_42 (4/9)
Analyzing archive 2015_08_31_01_33_39 (3/9)
Analyzing archive 2015_07_23_01_24_38 (2/9)
Analyzing archive 2015_06_23_00_33_41 (1/9)
Archive consistency check complete, no problems found.```

still the same error

**Comment by ThomasWaldmann** [comment]
How can it be still the same error if you deleted the index.NNNN file?

**Comment by Stunkymonkey** [comment]
```
$ sudo borg create --stats --progress /media/user/drive/Backup/borg/home.borg::2015_11_09_02_02_19 /home/user/ --exclude /home/*/.cache --exclude '*.pyc'
hashindex: /home/user/.cache/borg/bb8d63186b5e961117052a1c8681fa9ce40269facf8cd5ae8b2ba6e60dd45d51/chunks: Unknown MAGIC in header
borg: Error: Local Exception.
Traceback (most recent call last):
  File "/vagrant/borg/borg/borg/archiver.py", line 1030, in main
  File "/vagrant/borg/borg/borg/archiver.py", line 986, in run
  File "/vagrant/borg/borg/borg/archiver.py", line 116, in do_create
  File "/vagrant/borg/borg/borg/cache.py", line 53, in __init__
  File "/vagrant/borg/borg/borg/cache.py", line 135, in open
  File "/vagrant/borg/borg/borg/cache.py", line 209, in rollback
  File "/vagrant/borg/borg/borg/cache.py", line 128, in _do_open
  File "borg/hashindex.pyx", line 55, in borg.hashindex.IndexBase.read (borg/hashindex.c:1221)
  File "borg/hashindex.pyx", line 43, in borg.hashindex.IndexBase.__cinit__ (borg/hashindex.c:1021)
Exception: hashindex_read failed

borg: Exiting with failure status due to previous errors
```

**Comment by ThomasWaldmann** [comment]
OK, now it is falling over the chunks cache. You can remove the whole cache directory. It will get rebuild:
/home/user/.cache/borg/bb8d63186b5e961117052a1c8681fa9ce40269facf8cd5ae8b2ba6e60dd45d51

**Comment by Stunkymonkey** [comment]
Ok now it works again.

I will redo the conversion part, but the other backup is not in my house right now.
If this will fails, I am going to commit again.

Thanks for your time.

**Comment by ThomasWaldmann** [comment]
Use 0.28.1 for that, hopefully less trouble then. :)
