### ISSUE TITLE
Borg fails to read repo in an external encrypted drive

### ISSUE THREAD

**Issue by fullofcaffeine** [borgbackup/borg#3992]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).

1.1.4

#### Operating system (distribution) and version.

Linux Mint 18.3 Cinnamon

#### Hardware / network configuration, and filesystems used.

Dell XPS 15, ext2

#### How much data is handled by borg?

Around 20gigs in this case

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

`borg list /media/veracrypt1/backups/system`

## Describe the problem you're observing.

I've created the borg repo in an external 2TB veracrypt-encrypted HD. Initiating the repo worked file (with `repokey`). I then proceeded to backup my files. At the end of the archive process, I got the following:

```
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               24.81 GB             10.43 GB              9.32 GB
All archives:               24.92 GB             10.51 GB              9.32 GB

                       Unique chunks         Total chunks
Chunk index:                  282521               418743
------------------------------------------------------------------------------
Local Exception
Traceback (most recent call last):
  File "borg/archiver.py", line 4175, in main
  File "borg/archiver.py", line 4107, in run
  File "borg/archiver.py", line 143, in wrapper
  File "borg/cache.py", line 206, in assert_secure
  File "borg/cache.py", line 171, in assert_secure
  File "borg/cache.py", line 238, in __enter__
  File "borg/cache.py", line 262, in open
  File "borg/cache.py", line 267, in load
  File "borg/cache.py", line 326, in _check_upgrade
Exception: /home/fullofcaffeine/.cache/borg/<hash>/config does not look like a Borg cache.

Platform: Linux fullofcaffeine-XPS-15-9550 4.15.0-29-generic #31~16.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018 x86_64 x86_64
Linux: debian stretch/sid 
Borg: 1.1.4  Python: CPython 3.5.4
PID: 26119  CWD: /home/fullofcaffeine/workspace/code/savemycoffee
sys.argv: ['borg', 'prune', '/media/veracrypt1/backups/system', '-v', '--list', '--keep-daily=7', '--keep-weekly=4']
SSH_ORIGINAL_COMMAND: None
```
So the actual archive was succesfull, but it failed when I tried to prune.

I then deleted the cache:

`borg delete --cache-only /media/veracrypt1/system`

And tried to list the snapshots:

`borg list /media/veracrypt1/backups/system`

And got:

```
fullofcaffeine@fullofcaffeine-XPS-15-9550 /media/veracrypt1/backups $ borg list system                                                                                                                                                [2.5.0]
Enter passphrase for key /media/veracrypt1/backups/system: 
Enter passphrase for key /media/veracrypt1/backups/system: 
Could not read previous location file: [Errno 13] Permission denied: '/home/fullofcaffeine/.config/borg/security/<hash>/location'
Could not read/parse key type file: [Errno 13] Permission denied: '/home/fullofcaffeine/.config/borg/security/<hash>/key-type'
```

_Where <hash> is a sha256 (?) hash, removed for privacy purposes here._

Is that a limitation related to storing the repo in an external encrypted drive?

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

I described above.

#### Include any warning/errors/backtraces from the system logs

Everything has been described above.

Thanks!

**Comment by ThomasWaldmann** [comment]
The first one looks like corruption, the second one like a permissions mixup.

So, make sure your fs is working ok (maybe fsck it) and also that permissions are rwx for borg directories.

**Comment by fullofcaffeine** [comment]
I'm not backuping my home directory in this case, but timeshift backups. The home directory is encrypted, but timeshift backups are not stored there. The external HD - which I use to store the borg repo - *is* encrypted using veracrypt. I'll try backup'ing from scratch again to see how it goes.

**Comment by fullofcaffeine** [comment]
OK, found out the issue. It was indeed a permission problem. I forgot that for this specific script I had to run `borg create` with sudo, because some folders and files copied by timeshift are only readable by root, so I had to run `sudo borg create ....`.

As a related question, is it okay to use this strategy of running `borg` commands (`create`, `list` and `extract`) with `sudo` to backup files readable only by root? There's no easy way for me to change the permission for timeshift, so this was the way I found to solve the issue.
