### ISSUE TITLE
create timeout 0.28.1

### ISSUE THREAD

**Issue by ClipperS87** [borgbackup/borg#405]
during the create process the computer crashed (not borg related)

after reboot the borg create hung.

Ctrl-C showed, that he could not hande a former lock file.
I recommend to have any timeout/report to the user

note: after removing the .cache/borg directory the create worked as expected.

Keyboard interrupt.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/borg/locking.py", line 121, in acquire
    os.mkdir(self.path)
FileExistsError: [Errno 17] File exists: '/home/p/.cache/borg/afaf900ae5d71129b170669909065293b8388b809281cba83e50905ae8f7af01/lock.exclusive'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/borg/archiver.py", line 1202, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.4/site-packages/borg/archiver.py", line 1156, in run
    return args.func(args)
  File "/usr/lib/python3.4/site-packages/borg/archiver.py", line 126, in do_create
    cache = Cache(repository, key, manifest, do_files=args.cache_files)
  File "/usr/lib/python3.4/site-packages/borg/cache.py", line 56, in __init__
    self.open()
  File "/usr/lib/python3.4/site-packages/borg/cache.py", line 143, in open
    self.lock = UpgradableLock(os.path.join(self.path, 'lock'), exclusive=True).acquire()
  File "/usr/lib/python3.4/site-packages/borg/locking.py", line 251, in acquire
    self._wait_for_readers_finishing(remove, sleep)
  File "/usr/lib/python3.4/site-packages/borg/locking.py", line 269, in _wait_for_readers_finishing
    self._lock.acquire()
  File "/usr/lib/python3.4/site-packages/borg/locking.py", line 126, in acquire
    if timer.timed_out_or_sleep():
  File "/usr/lib/python3.4/site-packages/borg/locking.py", line 73, in timed_out_or_sleep
    self.sleep()
  File "/usr/lib/python3.4/site-packages/borg/locking.py", line 64, in sleep
    time.sleep(self.sleep_interval)
KeyboardInterrupt

**Comment by ThomasWaldmann** [comment]
please fix the markup so it looks less crappy. see the "styling with markdown is supported" link in the edit box.

**Comment by ThomasWaldmann** [comment]
This is already dealt with in these tickets: #285, #210, #157, #136.
