### ISSUE TITLE
borg borks during extract (and mount)

### ISSUE THREAD

**Issue by gerroon** [borgbackup/borg#4052]
Hi

I am trying to extract some files but it crashes in the middle of it. I have the same problem with mount, copying similar folders causes the mount to fail.

```
borg --version
borg 1.1.6

uname -ra
Linux 4.17.0-1-amd64 #1 SMP Debian 4.17.8-1 (2018-07-20) x86_64 GNU/Linux
```

```
borg extract /media/DRIVEB/ETC_VAR::ETC_VAR-2018-06-28_04:30:02 media/DRIVEC/var/lib/media-server                                            

Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4312, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4244, in run                                                                                                                  
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 152, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 165, in wrapper
    return method(self, args, repository=repository, manifest=manifest, key=key, archive=archive, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 752, in do_extract
    stripped_components=strip_components, original_path=orig_path, pi=pi)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 602, in extract_item
    for data in self.pipeline.fetch_many(ids, is_preloaded=True):
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 222, in fetch_many
    for id_, data in zip(ids, self.repository.get_many(ids, is_preloaded=is_preloaded)):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1050, in get_many
    yield self.get(id_)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1044, in get
    return self.io.read(segment, offset, id)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1375, in read
    size, tag, key, data = self._read(fd, self.put_header_fmt, header, segment, offset, (TAG_PUT, ), read_data)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1405, in _read
    data = fd.read(length)
a

OSError: [Errno 5] Input/output error

Platform: Linux lydia-4c 4.17.0-1-amd64 #1 SMP Debian 4.17.8-1 (2018-07-20) x86_64
Linux: debian buster/sid
Borg: 1.1.6  Python: CPython 3.6.6
PID: 18086  CWD: /media/DRIVEA/BORG
sys.argv: ['/usr/bin/borg', 'extract', '/media/DRIVEB/ETC_VAR::ETC_VAR-2018-06-28_04:30:02', 'media/DRIVEC/var/lib/media-server']
SSH_ORIGINAL_COMMAND: None

```

**Comment by ThomasWaldmann** [comment]
There is an I/O error while it read from the repository.

Check the disk / filesystem where the repo is located.

**Comment by gerroon** [comment]
I am not surew how I can test that, the disk does not throw any error while reading and writing. 

I just did and let it write like 20gb and I am not seeing any error from the drive.

``` dd if=/dev/zero | pv > del.img```

```cat del.img |pv > /dev/null```

**Comment by ThomasWaldmann** [comment]
Maybe just copy the repo elsewhere and watch the kernel logs (dmesg).
After that, do a `smartctl -a` on it and check for suspicious values / smart log entries.
After that, do a `smartctl -t long` and check again after the test is over.
Maybe you need also the `-dsat` option, if it is a usb disk.

**Comment by gerroon** [comment]
@ThomasWaldmann 

Thanks, that is a really good idea, I will give it a go.
