### ISSUE TITLE
borg info throws borg.repository.Repository.ObjectNotFound

### ISSUE THREAD

**Issue by EdgyGoatsConsumeFinely** [borgbackup/borg#4054]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue/Question

## System information. For client/server mode post info for both machines.
Platform: Linux [hostname_second_machine] 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64

#### Your borg version (borg -V).
borg 1.1.7
#### Operating system (distribution) and version.
Platform: Linux [hostname_second_machine] 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64
#### Hardware / network configuration, and filesystems used.
Standalone PC doing the Backup (2.66 GHz Pentium 4, 1.5 GB RAM) NTFS
Laptop PC trying to get the info (i7, 8 GB RAM) NTFS
#### How much data is handled by borg?
1.5 TB sum of several different archives
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
sys.argv: ['borg', 'info', '[repositorypath_second_machine]']

## Describe the problem you're observing.
Borg info does not work on the repo and the last archive of it that I just produced.
Oddly enough it does work on the machine that I used to create the archives, but other machines throw the object not found error.
#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
After finishing a migration of my obnam backups to borg I tried to open them on my laptop and it threw the error from the title. They are on a NTFS partition of an external HDD.
#### Include any warning/errors/backtraces from the system logs
```
[username_original_machine]@[hostname_original_machine]:~$ borg -V
borg 1.1.6
[username_original_machine]@[hostname_original_machine]:~$ uname -a
Linux [hostname_original_machine] 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:49:15 UTC 2018 i686 i686 i686 GNU/Linux
[username_original_machine]@[hostname_original_machine]:~$ borg info [repositorypath_original_machine]
Enter passphrase for key [repositorypath_original_machine]: 
Repository ID: [repository_id]
Location: [repositorypath_original_machine]
Encrypted: Yes (repokey)
Cache: [cachepath_original_machine]/[repository_id]
Security dir: [cachepath_original_machine]/security/[repository_id]
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
All archives:                [original_size] TB            [compressed_size] GB            [deduplicated_size] GB

                       Unique chunks         Total chunks
Chunk index:                  [unique_chunks]              [total_chunks]
[username_original_machine]@[hostname_original_machine]:~$ borg info [repositorypath_original_machine]/ --last 1
Enter passphrase for key [repositorypath_original_machine]: 
Archive name: [last_archive_name]
Archive fingerprint: [last_archive_fingerprint]
Comment: 
Hostname: [hostname_original_machine]
Username: [username_original_machine]
Time (start): Tue, 2018-08-14 17:33:25
Time (end): Mon, 2018-08-20 06:01:19
Duration: 5 days 12 hours 27 minutes 54.10 seconds
Number of files: [number_of_files]
Command line: borg create --stats --progress --compression auto,zstd,3 [repositorypath_original_machine]::[last_archive_name] [last_archive_source_path]
Utilization of maximum supported archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:              [original_size1] GB            [compressed_size1] GB             [deduplicated_size1] GB
All archives:                [original_size] TB            [compressed_size] GB            [deduplicated_size] GB

                       Unique chunks         Total chunks
Chunk index:                  [unique_chunks]              [total_chunks]
[username_original_machine]@[hostname_original_machine]:~$ 
```

```
[username_second_machine]@[hostname_second_machine]:~$ borg -V
borg 1.1.7
[username_second_machine]@[hostname_second_machine]:~$ borg info [repositorypath_second_machine]
Enter passphrase for key [repositorypath_second_machine]: 
Object with key [longcrypticalphanumericstring] not found in repository [repositorypath_second_machine].
Traceback (most recent call last):
  File "borg/archiver.py", line 4434, in main
  File "borg/archiver.py", line 4366, in run
  File "borg/archiver.py", line 149, in wrapper
  File "borg/cache.py", line 379, in __new__
  File "borg/cache.py", line 373, in local
  File "borg/cache.py", line 466, in __init__
  File "borg/cache.py", line 850, in sync
  File "borg/cache.py", line 804, in create_master_idx
  File "borg/cache.py", line 709, in fetch_and_build_idx
  File "borg/remote.py", line 1074, in get_many
  File "borg/repository.py", line 1067, in get_many
  File "borg/repository.py", line 1063, in get
borg.repository.Repository.ObjectNotFound: Object with key [longcrypticalphanumericstring] not found in repository [repositorypath_second_machine].

Platform: Linux [hostname_second_machine] 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64
Linux: debian stretch/sid 
Borg: 1.1.7  Python: CPython 3.5.5
PID: 3450  CWD: /home/[username_second_machine]
sys.argv: ['borg', 'info', '[repositorypath_second_machine]']
SSH_ORIGINAL_COMMAND: None

[username_second_machine]@[hostname_second_machine]:~$ mv .cache/borg/ borgcache
[username_second_machine]@[hostname_second_machine]:~$ borg info [repositorypath_second_machine]
Enter passphrase for key [repositorypath_second_machine]: 
Object with key [longcrypticalphanumericstring] not found in repository [repositorypath_second_machine].
Traceback (most recent call last):
  File "borg/archiver.py", line 4434, in main
  File "borg/archiver.py", line 4366, in run
  File "borg/archiver.py", line 149, in wrapper
  File "borg/cache.py", line 379, in __new__
  File "borg/cache.py", line 373, in local
  File "borg/cache.py", line 466, in __init__
  File "borg/cache.py", line 850, in sync
  File "borg/cache.py", line 804, in create_master_idx
  File "borg/cache.py", line 709, in fetch_and_build_idx
  File "borg/remote.py", line 1074, in get_many
  File "borg/repository.py", line 1067, in get_many
  File "borg/repository.py", line 1063, in get
borg.repository.Repository.ObjectNotFound: Object with key [longcrypticalphanumericstring] not found in repository [repositorypath_second_machine].

Platform: Linux [hostname_second_machine] 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64
Linux: debian stretch/sid 
Borg: 1.1.7  Python: CPython 3.5.5
PID: 3583  CWD: /home/[username_second_machine]
sys.argv: ['borg', 'info', '[repositorypath_second_machine]']
SSH_ORIGINAL_COMMAND: None
```

**Comment by EdgyGoatsConsumeFinely** [comment]
Dear Thomas,

thank you for your suggestion. I did that. The repository copy seems to work now.
Yet, is there a way to verify that I can trust it again? The chunk index for total chunks is by 0.034% smaller that what it gave me right after the last backup. Also the archive fingerprint of the last archive is different.

Can you think of a reason how this has happened? I do not remember getting any warnings or errors when creating the archives. This bothers me a little.

Thank you!

**Comment by ThomasWaldmann** [comment]
Well, `borg check` is the best method to verify, optionally with `--verify-data` to make it more thorough (and more slow). You can also do a `borg extract --dry-run ...` on some archives.

If you ran `borg check --repair`, did it maybe repair the archive where the fp changed? Is it the same archive name as before?
