### ISSUE TITLE
backup to samba

### ISSUE THREAD

**Issue by ape364** [borgbackup/borg#4056]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

#### Your borg version (borg -V).

borg 1.1.6

#### Operating system (distribution) and version.

`Linux MiBook 4.18.3-arch1-1-ARCH #1 SMP PREEMPT Sat Aug 18 09:22:54 UTC 2018 x86_64 GNU/Linux`

#### Hardware / network configuration, and filesystems used.

```
 ~  cat /etc/systemd/system/mnt-wdsmb.mount 
[Unit]
Description=Mount WD Share at boot
Requires=systemd-networkd.service
After=network-online.target
Wants=network-online.target

[Mount]
What=//192.168.88.1/wd_share
Where=/mnt/wdsmb
Options=credentials=/home/ape364/.smb_cred,iocharset=utf8,file_mode=0777,dir_mode=0777,defaults,uid=1000,gid=985,ip=192.168.88.1,vers=2.0,rw,user,x-systemd.automount
Type=cifs
TimeoutSec=10

[Install]
WantedBy=multi-user.target

```

#### How much data is handled by borg?

none

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
 ~  ls -la /mnt/wdsmb/ | grep arch_backup
drwxrwxrwx 2 ape364 users       4096 Aug 22 00:44 arch_backup
 ~  whoami
ape364
 ~  borg init -e repokey /mnt/wdsmb/arch_backup
Enter new passphrase: 
Enter same passphrase again: 
Do you want your passphrase to be displayed for verification? [yN]: y 
Your passphrase (between double-quotes): "qwe"
Make sure the passphrase displayed above is exactly what you wanted.
Failed to securely erase old repository config file (hardlinks not supported>). Old repokey data, if any, might persist on physical storage.

By default repositories initialized with this version will produce security
errors if written to with an older version (up to and including Borg 1.0.8).

If you want to use these older versions, you can disable the check by running:
borg upgrade --disable-tam /mnt/wdsmb/arch_backup

See https://borgbackup.readthedocs.io/en/stable/changes.html#pre-1-0-9-manifest-spoofing-vulnerability for details about the security implications.
 ~  ls -la /home/ape364/backup_test/
total 12
drwxr-xr-x  2 ape364 users 4096 Aug 22 00:47 ./
drwx------ 33 ape364 users 4096 Aug 22 00:47 ../
-rw-r--r--  1 ape364 users    2 Aug 22 00:47 testfile1.txt
 ~  borg create -v --stats /mnt/wdsmb/arch_backup::test1 ~/backup_test/
No key entry found in the config of repository /mnt/wdsmb/arch_backup.
 ✘  ~  borg upgrade /mnt/wdsmb/arch_backup
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4312, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4244, in run
    return set_ec(func(args))
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 129, in wrapper
    return method(self, args, repository=None, **kwargs)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 1643, in do_upgrade
    repo.upgrade(args.dry_run, inplace=args.inplace, progress=args.progress)
  File "/usr/lib/python3.7/site-packages/borg/upgrader.py", line 42, in upgrade
    shutil.copytree(self.path, backup, copy_function=os.link)
  File "/usr/lib/python3.7/shutil.py", line 359, in copytree
    raise Error(errors)
shutil.Error: [('/mnt/wdsmb/arch_backup/README', '/mnt/wdsmb/arch_backup.before-upgrade-2018-08-22-00:48:44/README', "[Errno 95] Operation not supported: '/mnt/wdsmb/arch_backup/README' -> '/mnt/wdsmb/arch_backup.before-upgrade-2018-08-22-00:48:44/README'"), ('/mnt/wdsmb/arch_backup/config', '/mnt/wdsmb/arch_backup.before-upgrade-2018-08-22-00:48:44/config', "[Errno 95] Operation not supported: '/mnt/wdsmb/arch_backup/config' -> '/mnt/wdsmb/arch_backup.before-upgrade-2018-08-22-00:48:44/config'"), ('/mnt/wdsmb/arch_backup/config.tmp', '/mnt/wdsmb/arch_backup.before-upgrade-2018-08-22-00:48:44/config.tmp', "[Errno 95] Operation not supported: '/mnt/wdsmb/arch_backup/config.tmp' -> '/mnt/wdsmb/arch_backup.before-upgrade-2018-08-22-00:48:44/config.tmp'"), ('/mnt/wdsmb/arch_backup/data/0/0', '/mnt/wdsmb/arch_backup.before-upgrade-2018-08-22-00:48:44/data/0/0', "[Errno 95] Operation not supported: '/mnt/wdsmb/arch_backup/data/0/0' -> '/mnt/wdsmb/arch_backup.before-upgrade-2018-08-22-00:48:44/data/0/0'"), ('/mnt/wdsmb/arch_backup/data/0/1', '/mnt/wdsmb/arch_backup.before-upgrade-2018-08-22-00:48:44/data/0/1', "[Errno 95] Operation not supported: '/mnt/wdsmb/arch_backup/data/0/1' -> '/mnt/wdsmb/arch_backup.before-upgrade-2018-08-22-00:48:44/data/0/1'"), ('/mnt/wdsmb/arch_backup/hints.1', '/mnt/wdsmb/arch_backup.before-upgrade-2018-08-22-00:48:44/hints.1', "[Errno 95] Operation not supported: '/mnt/wdsmb/arch_backup/hints.1' -> '/mnt/wdsmb/arch_backup.before-upgrade-2018-08-22-00:48:44/hints.1'"), ('/mnt/wdsmb/arch_backup/index.1', '/mnt/wdsmb/arch_backup.before-upgrade-2018-08-22-00:48:44/index.1', "[Errno 95] Operation not supported: '/mnt/wdsmb/arch_backup/index.1' -> '/mnt/wdsmb/arch_backup.before-upgrade-2018-08-22-00:48:44/index.1'"), ('/mnt/wdsmb/arch_backup/integrity.1', '/mnt/wdsmb/arch_backup.before-upgrade-2018-08-22-00:48:44/integrity.1', "[Errno 95] Operation not supported: '/mnt/wdsmb/arch_backup/integrity.1' -> '/mnt/wdsmb/arch_backup.before-upgrade-2018-08-22-00:48:44/integrity.1'"), ('/mnt/wdsmb/arch_backup/nonce', '/mnt/wdsmb/arch_backup.before-upgrade-2018-08-22-00:48:44/nonce', "[Errno 95] Operation not supported: '/mnt/wdsmb/arch_backup/nonce' -> '/mnt/wdsmb/arch_backup.before-upgrade-2018-08-22-00:48:44/nonce'")]

Platform: Linux MiBook 4.18.3-arch1-1-ARCH #1 SMP PREEMPT Sat Aug 18 09:22:54 UTC 2018 x86_64
Linux: arch  
Borg: 1.1.6  Python: CPython 3.7.0
PID: 12141  CWD: /home/ape364
sys.argv: ['/usr/bin/borg', 'upgrade', '/mnt/wdsmb/arch_backup']
SSH_ORIGINAL_COMMAND: None

```

## Describe the problem you're observing.

cannot create repo on samba share

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

described above

#### Include any warning/errors/backtraces from the system logs

-

**Comment by ThomasWaldmann** [comment]
Running `borg upgrade` is never required expect if you are told otherwise by some of our docs.

```
$ borg init -e repokey /mnt/wdsmb/arch_backup
...
!!! Failed to securely erase old repository config file (hardlinks not supported>).
!!! Old repokey data, if any, might persist on physical storage.
...
$ borg create -v --stats /mnt/wdsmb/arch_backup::test1 ~/backup_test/
!!! No key entry found in the config of repository /mnt/wdsmb/arch_backup.
```

I marked the notable lines in the log output with `!!!`.

It seems that your repo filesystem is not working as expected. Can you reproduce that?

**Comment by ape364** [comment]
@ThomasWaldmann thanks for the reply. here is contents of config:

```
 ~  mkdir /mnt/wdsmb/testfolder
 ~  borg init -e repokey /mnt/wdsmb/testfolder/
Enter new passphrase: 
Enter same passphrase again: 
Do you want your passphrase to be displayed for verification? [yN]: Y
Your passphrase (between double-quotes): "q"
Make sure the passphrase displayed above is exactly what you wanted.
Failed to securely erase old repository config file (hardlinks not supported>). Old repokey data, if any, might persist on physical storage.

By default repositories initialized with this version will produce security
errors if written to with an older version (up to and including Borg 1.0.8).

If you want to use these older versions, you can disable the check by running:
borg upgrade --disable-tam /mnt/wdsmb/testfolder

See https://borgbackup.readthedocs.io/en/stable/changes.html#pre-1-0-9-manifest-spoofing-vulnerability for details about the security implications.
 ~  cat /mnt/wdsmb/testfolder/config
[repository]
version = 1
segments_per_dir = 1000
max_segment_size = 524288000
append_only = 0
storage_quota = 0
additional_free_space = 0
id = 55f43375d692b64b57f471c5fc624de89d304632591ec1770d5d29738f4cf88d

```

**Comment by ThomasWaldmann** [comment]
Hmm, as borg also noted: there is no key, but as you used `repokey`, there should be one.

This might be a bug in borg - triggered by not being able to use a hardlink for securely updating the repo config / erasing the old pre-update version of the repo config.

Maybe the fallback code for that case does not work as it should, I'll have a look.

Looks like nobody noticed this yet as most people use hardlink-capable filesystems (like any local linux filesystem or nfs).

**Comment by ThomasWaldmann** [comment]
I had a look into the code, but could not find an issue.

The warning is triggered if the fs is not hardlink capable, but it does not branch into a different path of processing except for emitting that warning.

There is also no other visible exception in borg, so my current assumption is that your filesystem (or smb server) is malfunctioning.

**Comment by ThomasWaldmann** [comment]
Can you please reproduce it once more and give me a `ls -l repo_dir` from after the `borg init -e repokey`?

**Comment by ThomasWaldmann** [comment]
I don't use a smb mounted repo myself, but I guess maybe some other borg users could comment about their success (or failure) in doing that.

**Comment by ape364** [comment]
```
 /m/w/testfolder  ls -l
total 72
-rwxrwxrwx 1 ape364 users   209 Aug 22 10:10 config*
-rwxrwxrwx 1 ape364 users   700 Aug 22 10:10 config.tmp*
drwxrwxrwx 2 ape364 users  4096 Aug 22 10:10 data/
-rwxrwxrwx 1 ape364 users    52 Aug 22 10:10 hints.1*
-rwxrwxrwx 1 ape364 users 41258 Aug 22 10:10 index.1*
-rwxrwxrwx 1 ape364 users   190 Aug 22 10:10 integrity.1*
-rwxrwxrwx 1 ape364 users    16 Aug 22 10:10 nonce*
-rwxrwxrwx 1 ape364 users    73 Aug 22 10:10 README*

```

**Comment by ThomasWaldmann** [comment]
OK, so it looks like it wrote the config *with* key to `config.tmp`, but did not manage to replace `config` (the previous config *without* key) with that.

In the code, this is just an `os.replace()` call and it should throw an exception if something is going wrong.
But we don't see that exception...

**Comment by ThomasWaldmann** [comment]
This is the contextmanager save_config is using around `config.write()`:

```
class SaveFile:
    """
    Update file contents atomically.

    Must be used as a context manager (defining the scope of the transaction).

    On a journaling file system the file contents are always updated
    atomically and won't become corrupted, even on power failures or
    crashes (for caveats see SyncFile).
    """

    SUFFIX = '.tmp'

    def __init__(self, path, binary=False):
        self.binary = binary
        self.path = path
        self.tmppath = self.path + self.SUFFIX

    def __enter__(self):
        from .. import platform
        try:
            truncate_and_unlink(self.tmppath)
        except FileNotFoundError:
            pass
        self.fd = platform.SyncFile(self.tmppath, self.binary)
        return self.fd

    def __exit__(self, exc_type, exc_val, exc_tb):
        from .. import platform
        self.fd.close()
        if exc_type is not None:
            truncate_and_unlink(self.tmppath)
            return
        os.replace(self.tmppath, self.path)
        platform.sync_dir(os.path.dirname(self.path))
```
From the observed behaviour (`config.tmp` being present), it has taken the non-exception exit path (also: no exception observed), which does `os.replace` (which did neither work nor throw an exception as it seems) and `sync_dir`.

**Comment by ape364** [comment]
it seems to be ok if i manually replacing `config` by `config.tmp` :

```
~  borg init -e repokey /mnt/wdsmb/testfolder/
Enter new passphrase: 
Enter same passphrase again: 
Do you want your passphrase to be displayed for verification? [yN]: 
Failed to securely erase old repository config file (hardlinks not supported>). Old repokey data, if any, might persist on physical storage.

By default repositories initialized with this version will produce security
errors if written to with an older version (up to and including Borg 1.0.8).

If you want to use these older versions, you can disable the check by running:
 ~  borg init -e repokey /mnt/wdsmb/testfolder/
Enter new passphrase: 
Enter same passphrase again: 
Do you want your passphrase to be displayed for verification? [yN]: 
Failed to securely erase old repository config file (hardlinks not supported>). Old repokey data, if any, might persist on physical storage.

By default repositories initialized with this version will produce security
errors if written to with an older version (up to and including Borg 1.0.8).

If you want to use these older versions, you can disable the check by running:
borg upgrade --disable-tam /mnt/wdsmb/testfolder

See https://borgbackup.readthedocs.io/en/stable/changes.html#pre-1-0-9-manifest-spoofing-vulnerability for details about the security implications.
 ~  rm /mnt/wdsmb/testfolder/config
 ~  mv /mnt/wdsmb/testfolder/config.tmp /mnt/wdsmb/testfolder/config
 ~  la /mnt/wdsmb/testfolder/
total 72K
drwxrwxrwx 2 ape364 users 4.0K Aug 23 14:47 ./
drwxrwxrwx 2 ape364 users    3 Aug 23 14:46 ../
-rwxrwxrwx 1 ape364 users  700 Aug 23 14:46 config*
drwxrwxrwx 2 ape364 users 4.0K Aug 23 14:46 data/
-rwxrwxrwx 1 ape364 users   52 Aug 23 14:46 hints.1*
-rwxrwxrwx 1 ape364 users  41K Aug 23 14:46 index.1*
-rwxrwxrwx 1 ape364 users  190 Aug 23 14:46 integrity.1*
-rwxrwxrwx 1 ape364 users   16 Aug 23 14:46 nonce*
-rwxrwxrwx 1 ape364 users   73 Aug 23 14:46 README*
 ~  borg create -v --stats /mnt/wdsmb/testfolder::test1 ~/backup_test/
------------------------------------------------------------------------------
Archive name: test1
Archive fingerprint: 1c41e43228883bf14b16d61101037edccfe851b8f25c1f03e639b10919ac722a
Time (start): Thu, 2018-08-23 14:47:09
Time (end):   Thu, 2018-08-23 14:47:09
Duration: 0.12 seconds
Number of files: 1
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                  790 B                809 B                809 B
All archives:                  790 B                809 B                809 B

                       Unique chunks         Total chunks
Chunk index:                       3                    3
------------------------------------------------------------------------------

```

**Comment by ThomasWaldmann** [comment]
Guess I rather would not use a backup repo filesystem that does not even get `borg init` right.

If you try the same commands on a local fs, I guess they work on that machine?

**Comment by ape364** [comment]
Right

**Comment by ThomasWaldmann** [comment]
@Ape did you find the root cause of the problem?

**Comment by ThomasWaldmann** [comment]
Can you add the version and origin of the smbd (samba server) you used?

**Comment by ape364** [comment]
> Can you add the version and origin of the smbd (samba server) you used?

I don't know the version, but I tried this on my router MikroTik hAP ac lite tower (RB952Ui-5ac2nD-TC) with RouterOS v6.44beta9 on

**Comment by John-Gee** [comment]
Hello,

I'm encountering the same issue when using gcsf as my FS.
I can see 2 files named "config", no tmp one here.
In my terminal I see them both at the same size, but in a browser on the provider I see one is 964b and one is 209b so similar as here with Samba.

**Comment by John-Gee** [comment]
Yeah it's a bit weird, there must be a difference somewhere that is not displayed.

I've switched to another FS with the same provider and no issue so far it seems.

**Comment by Kabouik** [comment]
I am having the same issue. The folder on the samba server is: `smb://domain;username@servername.fr/somefolder$/username/Backups_Travail`.

Since I was not sure how to deal with this syntax in Borg, I made a symlink to a local folder with [lns](https://www.chiark.greenend.org.uk/~sgtatham/utils/lns.html): `lns smb://domain;username@servername.fr/somefolder$/username/Backups_Travail /home/username/Documents/Backups_Travail`.

Then, I tried `borg init`:

```bash
username@xiaomimi-solus ~/Documents $ borg init --encryption=repokey-blake2 /home/username/Documents/Backups_Travail
Enter new passphrase: 
Enter same passphrase again: 
Do you want your passphrase to be displayed for verification? [yN]: N
Failed to securely erase old repository config file (hardlinks not supported>). Old repokey data, if any, might persist on physical storage.
Not enough free space to initialize repository at this location.
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4455, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4387, in run
    return set_ec(func(args))
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 154, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 275, in do_init
    repository.commit()
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 438, in commit
    self.check_free_space()
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 663, in check_free_space
    self.destroy()
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 344, in destroy
    shutil.rmtree(self.path)
  File "/usr/lib/python3.6/shutil.py", line 496, in rmtree
    onerror(os.path.islink, path, sys.exc_info())
  File "/usr/lib/python3.6/shutil.py", line 494, in rmtree
    raise OSError("Cannot call rmtree on a symbolic link")
OSError: Cannot call rmtree on a symbolic link

Platform: Linux xiaomimi-solus 4.9.163-127.lts #1 SMP PREEMPT Fri Mar 15 02:46:36 UTC 2019 x86_64
Linux:   
Borg: 1.1.9  Python: CPython 3.6.8
PID: 27422  CWD: /home/username/Documents
sys.argv: ['/usr/bin/borg', 'init', '--encryption=repokey-blake2', '/home/username/Documents/Backups_Travail']
SSH_ORIGINAL_COMMAND: None
```

(I just redacted my username everywhere, not that it's very sensible but why not.)

In the repository, I now have a `nonce` file and a `README` file, together with a `data` folder which contains a `0` subfolder, which contains a `0` file of 530 bytes. I guess the latter is an error log but I couldn't open it as plain text.

I didn't paste here the output of a `borg create`, but obviously it fails too because the repository was not properly initiated. 

Any ideas? I don't have much control over the Samba share, I am not the administrator, just a user in the company.

**Comment by fantasya-pbem** [comment]
I guess that borg init found that you do not have enough space in /home/username/Documents/Backups_Travail, so it aborts. It then tries to remove your symlink and fails ("Cannot call rmtree on a symbolic link"). The latter is considered a minor bug (#4365) because borg should not remove an empty repository directory if it did not create it, but that seems not to be the cause of your problem. Have a look at free space.

**Comment by Kabouik** [comment]
This is where I was looking too because I noticed in Nautlus as well as with `du` that the available space does not show up on the remote folder (in Nautilus, "Free space: unknown" is displayed). However, I know that there are several hundreds of free GB at the moment (and I can manually create files in Nautilus). 

I do not know where the issue is with the calculation of free space, but I assume Borg won't try anything unless it can confirm there is enough space. 

My guess is the issue is with smb. I have asked a colleague using a different Linux distribution and perhaps a different version of Samba, and he cannot show the available space either. He is not using Borg however, so the issue is minor for him.

I will try with mounting the samba share instead of connecting to it with `smb://`.

**Comment by Kabouik** [comment]
Yes, that's the issue. If I mount the remote server using:

```
sudo mount -t cifs -o username=username,domain=domain,uid=1000 //servername.fr/somefolder$/username /home/username/Documents/Datacenter_mountpoint/
```

And eventually go into the local mountpoint to browse the remote servers, then I can (1) see the free space in Nautilus or with `du`, (2) initialize the Borg repository, and (3) create a first Borg backup (well, it's still ongoing so we'll see if it actually works). 

Would there be a way to make Borg ignore the a priori check of available space if it fails to guess it (for reasons that probably are not related to Borg itself)? I guess it would just be necessary to add some configuration parameters on the Windows server for it to be correctly recognized by samba, but I have no control over this.

**Comment by Kabouik** [comment]
> Would there be a way to make Borg ignore the a priori check of available space when it fails (for reasons that probably are not related to Borg itself)? I guess it would just be necessary to add some configuration parameters on the Windows server for it to be correctly recognized by samba, but I have no control over this.

Replying to myself because I found that on the website, sorry for missing it earlier:

> *Can I disable checking for free disk space?*
> In some cases, the free disk space of the target volume is reported incorrectly. This can happen for CIFS- or FUSE shares. If you are sure that your target volume will always have enough disk space, you can use the following workaround to disable checking for free disk space:
> 
> `borg config -- $REPO_LOCATION additional_free_space -2T`

I haven't checked though, since now I have made scripts to circumvent the issue using `mount` instead of just the Samba path.
