### ISSUE TITLE
Backup fails randomly with KeyError

### ISSUE THREAD

**Issue by floli** [borgbackup/borg#4078]
Hello,

I use the borgmatic script and borg 1.0.9 at Debian Stable on the client side. Server side version is borg-1.0, though I don't know how to verify it or get the exact revision. I have SSH access, but no PTY allocation is possible.

Backups fails randomly with
```
A /home/xxx/yyy.sql
------------------------------------------------------------------------------
Archive name: venus-2018-09-18 15:24:32.045117
Archive fingerprint: b7319dda9794cc2035d31db813182a5dcfcad77c01db8fa6796f1c7af0b84626
Time (start): Tue, 2018-09-18 15:24:33
Time (end):   Tue, 2018-09-18 15:37:43
Duration: 13 minutes 10.30 seconds
Number of files: 908625
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               84.46 GB             57.24 GB              1.22 GB
All archives:              432.57 GB            291.62 GB             50.88 GB

                       Unique chunks         Total chunks
Chunk index:                  757768              4683540
------------------------------------------------------------------------------
Local Exception.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 2052, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1997, in run
    return func(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 90, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 305, in do_create
    create_inner(archive, cache)
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 107, in __exit__
    self.close()
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 189, in close
    self.lock.release()
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 298, in release
    self._roster.modify(EXCLUSIVE, REMOVE)
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 216, in modify
    elements.remove(self.id)
KeyError: ('venus', 1405, 0)

Platform: Linux venus 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 
Linux: debian 9.5 
Borg: 1.0.9  Python: CPython 3.5.3
PID: 1405  CWD: /etc/borgmatic
sys.argv: ['/usr/bin/borg', 'create', 'ssh://u123@u123.your-storagebox.de:23/./venus.centershock.net::{hostname}-{now}', '/root', '/etc', '/home', '--exclude-from', '/tmp/tmp3mw0wkha', '--exclude-caches', '--exclude-if-present', '.nobackup', '--checkpoint-interval', '1800', '--compression', 'zlib,6', '--one-file-system', '--remote-path', 'borg-1.0', '--list', '--filter', 'AME', '--info', '--stats']
SSH_ORIGINAL_COMMAND: None

/etc/borgmatic/config.yaml: Running command for on-error hook
Tue Sep 18 15:38:35 CEST 2018 - Error while creating a backup.
Command '('borg', 'create', 'ssh://u123@u1123.your-storagebox.de:23/./venus.centershock.net::{hostname}-{now}', '/root', '/etc', '/home', '--exclude-from', '/tmp/tmp3mw0wkha', '--exclude-caches', '--exclude-if-present', '.nobackup', '--checkpoint-interval', '1800', '--compression', 'zlib,6', '--one-file-system', '--remote-path', 'borg-1.0', '--list', '--filter', 'AME', '--info', '--stats')' returned non-zero exit status 2
```

The amount of data is well below 100GB.

Thanks!

**Comment by ThomasWaldmann** [comment]
This is an issue in the locking code. As it happens with the cache lock, it is clientside.

It would be good if you could reproduce it with a current version.

https://packages.debian.org/stretch-backports/borgbackup

**Comment by floli** [comment]
I have installed a recent client version of borg using pip. It seems to be running fine for the time being. I will report back.

**Comment by floli** [comment]
I was not able to reproduce it using the recent version. Seems to be fixed, I will close that issue.
