### ISSUE TITLE
[Errno 27] File too large

### ISSUE THREAD

**Issue by lapoigne** [borgbackup/borg#4079]
Backup on samba share reports OSError: [Errno 27] File too large

## Have you checked borgbackup docs, FAQ, and open Github issues?
Yes

## Is this a BUG / ISSUE report or a QUESTION?
ISSUE

#### Your borg version (borg -V).
1.1.7
Build with [https://github.com/lapoigne/borg-cygwin](https://github.com/lapoigne/borg-cygwin)

#### Operating system (distribution) and version.
Windows 7 32bit - CYGWIN_NT-6.1 PC-VINCENT-P 2.10.0(0.325/5/3) 2018-02-02 15:21 i686 Cygwin

NETGEAR ReadyNAS Pro 4 [X-RAID2] - Linux NAS 2.6.37.6.RNx86_64.2.4 #1 SMP Tue Nov 12 18:53:39 PST 2013 x86_64 GNU/Linux

#### Hardware / network configuration, and filesystems used.
Backup of files on NTFS partition on mounted samba share (mounted with NET USE), with ext4 filesystem

#### How much data is handled by borg?
~ 90GB, biggest file is ~ 13GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```borg create --list -s -p /w/Borg/myrepo::%date% /e /c/Users/User```
and after
```borg info  /w/Borg/myrepo
borg list  /w/Borg/myrepo
borg check  /w/Borg/myrepo
```

## Describe the problem you're observing.

After a borg create command, borg can't write the index file and get the file too large error.

Once I encounter this, all subsequent borg commands, like borg info, reports "File too large."

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Now for every borg subcommand, the error appear.

#### Include any warning/errors/backtraces from the system logs

```
$ borg info --debug /w/Borg/myrepo
using builtin fallback logging configuration
35 self tests completed in 0.40 seconds
Verified integrity of /w/Borg/myrepo/index.289
Verified integrity of /w/Borg/myrepo/hints.289
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4434, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 4366, in run
    return set_ec(func(args))
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 139, in wrapper
    kwargs['manifest'], kwargs['key'] = Manifest.load(repository, compatibility)
  File "/usr/lib/python3.6/site-packages/borg/helpers.py", line 330, in load
    cdata = repository.get(cls.MANIFEST_ID)
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 1058, in get
    self.index = self.open_index(self.get_transaction_id())
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 365, in get_transaction_id
    self.check_transaction()
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 362, in check_transaction
    self.replay_segments(replay_from, segments_transaction_id)
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 802, in replay_segments
    self.write_index()
  File "/usr/lib/python3.6/site-packages/borg/repository.py", line 577, in write_index
    self.index.write(fd)
  File "src/borg/hashindex.pyx", line 114, in borg.hashindex.IndexBase.write
  File "/usr/lib/python3.6/site-packages/borg/crypto/file_integrity.py", line 29, in write
    return self.fd.write(data)
  File "/usr/lib/python3.6/site-packages/borg/crypto/file_integrity.py", line 74, in write
    n = super().write(data)
  File "/usr/lib/python3.6/site-packages/borg/crypto/file_integrity.py", line 29, in write
    return self.fd.write(data)
OSError: [Errno 27] File too large

Platform: CYGWIN_NT-6.1 PC-VINCENT-P 2.10.0(0.325/5/3) 2018-02-02 15:21 i686
Borg: 1.1.7  Python: CPython 3.6.4
PID: 9020  CWD: /c/Users/User
sys.argv: ['/usr/bin/borg', 'info', '--debug', '/w/Borg/myrepo']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment]
It looks like it fails when writing the repo index. How big is it now? `repo_dir/index.<N>`

Is there a file size limitation on your samba share / due to your samba server version / configuration?

**Comment by ThomasWaldmann** [comment]
That 64kiB size of the tmp file looks very suspicious. Is it maybe the smbfs not being able to handle more than that *per write call*?

**Comment by ThomasWaldmann** [comment]
Also, could you please reproduce this on a linux or bsd system (not cygwin, not WSL) against the same samba server, just to see if it happens there also?

**Comment by lapoigne** [comment]
`du` show 64K for all small files, but explorer show a 18o file.

I've tried on ubuntu-server virtual machine with official `borg-linux64` binary and no problems here
My index file is now `index.300` with 29M size

**Comment by ThomasWaldmann** [comment]
OK, considering that, I suspect that either your smb mount on windows or cygwin is the culprit here.

Did you try fully updating your cygwin installation?

**Comment by lapoigne** [comment]
I upgraded cygwin to version 2.11.1 and make a new backup.
I got the same error at the moment of index write

**Comment by ThomasWaldmann** [comment]
Just to be clear: you ran setup-*.exe of cygwin, clicked through it, had all packages selected and it downloaded / installed recent versions of all of them?

**Comment by lapoigne** [comment]
Yes, I updated all available package (cygwin, openssl,...)

**Comment by lapoigne** [comment]
I just make a test:
Copy the smb backup dir to local hdd, and `borg info /c/mynewplace` and all was good with index write correctly
It's definitely a problem with cygwin32 and smb

**Comment by ThomasWaldmann** [comment]
Interesting. Could you bring up this issue on the cygwin support mailing list?

**Comment by lapoigne** [comment]
Issue reported https://cygwin.com/ml/cygwin/2018-09/msg00254.html

**Comment by ThomasWaldmann** [comment]
@lapoigne did you see the replies / questions on the cygwin mailing list?

**Comment by lapoigne** [comment]
No replies since my last message on 26 september

**Comment by ThomasWaldmann** [comment]
There are. Just click the link you gave and at the bottom on "follow-ups"...

**Comment by lapoigne** [comment]
No replies since https://cygwin.com/ml/cygwin/2018-09/msg00258.html

**Comment by ThomasWaldmann** [comment]
Ah, ok. Somehow the posts are not interlinked correctly...
