### ISSUE TITLE
Borg has issues writing to mounted davfs/webdav-share

### ISSUE THREAD

**Issue by mpw-wwu** [borgbackup/borg#4106]
Hello,

Borg can't create a repository on a locally mounted webdav share. It's been mounted with davfs2.

#### Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

#### Is this a BUG / ISSUE report or a QUESTION?

Bug

#### System information. For client/server mode post info for both machines.

Locally mounted davfs filesystem

#### Your borg version (borg -V).

borg 1.1.7

#### Operating system (distribution) and version.

Ubuntu 18.04

#### Hardware / network configuration, and filesystems used.

Webdav / davfs2 mounted share

#### How much data is handled by borg?

About 100 MB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
$ borgbackup init --encryption=repokey /path/to/backup
Enter new passphrase: 
Enter same passphrase again: 
Do you want your passphrase to be displayed for verification? [yN]: y
Your passphrase (between double-quotes): "[removed]"
Make sure the passphrase displayed above is exactly what you wanted.
Failed to securely erase old repository config file (hardlinks not supported>). Old repokey data, if any, might persist on physical storage.

By default repositories initialized with this version will produce security
errors if written to with an older version (up to and including Borg 1.0.8).

If you want to use these older versions, you can disable the check by running:
borg upgrade --disable-tam /path/to/backup

See https://borgbackup.readthedocs.io/en/stable/changes.html#pre-1-0-9-manifest-spoofing-vulnerability for details about the security implications.

IMPORTANT: you will need both KEY AND PASSPHRASE to access this repo!
Use "borg key export" to export the key, optionally in printable format.
Write down the passphrase. Store both at safe place(s).

Exception ignored in: <bound method Repository.__del__ of <Repository /path/to/backup>>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 173, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 415, in close
    self.lock.release()
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 383, in release
    self._roster.modify(EXCLUSIVE, REMOVE)
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 282, in modify
    elements.remove(self.id)
KeyError: (('[DNS/Hostname removed]@53447169073345', 3275, 0),)
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4434, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4366, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 152, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 198, in __exit__
    self.close()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 415, in close
    self.lock.release()
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 383, in release
    self._roster.modify(EXCLUSIVE, REMOVE)
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 282, in modify
    elements.remove(self.id)
KeyError: ('[DNS/Hostname removed]@53447169073345', 3275, 0)

Platform: Linux [Hostname removed] 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64
Linux: Ubuntu 18.04 bionic
Borg: 1.1.7  Python: CPython 3.6.6
PID: 3275  CWD: /home/[username removed]
sys.argv: ['/usr/bin/borgbackup', 'init', '--encryption=repokey', '/path/to/backup/']
SSH_ORIGINAL_COMMAND: None
```

#### Describe the problem you're observing.

Failure. See error message above.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes, happens every time.

#### Include any warning/errors/backtraces from the system logs

See above.

Best,
Matthias

**Comment by ThomasWaldmann** [comment]
Could be that davfs is not good enough as a filesystem.

**Comment by mpw-wwu** [comment]
Standard access works perfectly. Does Borg require special capabilities?

**Comment by ThomasWaldmann** [comment]
Likely the problem are rather consistency / racing issue (stuff just written does not read back) or the more heavy use than when manually copying some files.

**Comment by wioxjk** [comment]
Would it be possible to support webdav in the near future?

**Comment by RonnyPfannschmidt** [comment]
Excessively unlikely

**Comment by ThomasWaldmann** [comment]
issue outside of borg, closing.
