### ISSUE TITLE
borg backup always crashes with cygwin

### ISSUE THREAD

**Issue by borgbit** [borgbackup/borg#4108]
borg 1.1.7
Client: Windows 8, cygwin
Conenction: ssh
Repo: Ubuntu

Since half a year im gladly using borg backup to backup my environment. I never had any issues using cygwin (even with win7). But since a few days I have some problems.
I created a new borg repo on my server and on the client I installed cygwin with borg 1.1.7.
Then I run borg create in order to backup a 300 GB Share.
The backup run through the whole night and then at 200 GB interupted (error status 2). I guessed that the ssh connection to the repo failed. So I restarted the backup 4 times and it always failed at 90 GB. I exlcuded some directories. Again it failed. Sometimes at 6 GB or 90 GB. borg check --repair not helped.
I even created a new repo and run again. The same issue. 

Any similar story occured ? for me it appears that there is bug in borg or cygwin. Because why it failed even with a new repo ? the ssh connection is stable. Here is the error code. Thanks for any help.

```
Local Exception.21 GB C 196.09 GB D 647683 N cygdrive/z/Administrator
Traceback (most recent call last):
  File "/bin/borg-env/lib/python3.6/site-packages/borg/archiver.py", line 152, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/bin/borg-env/lib/python3.6/site-packages/borg/archiver.py", line 554, in do_create
    create_inner(archive, cache)
  File "/bin/borg-env/lib/python3.6/site-packages/borg/archiver.py", line 518, in create_inner
    read_special=args.read_special, dry_run=dry_run, st=st)
  File "/bin/borg-env/lib/python3.6/site-packages/borg/archiver.py", line 631, in _process
    read_special=read_special, dry_run=dry_run)
  File "/bin/borg-env/lib/python3.6/site-packages/borg/archiver.py", line 631, in _process
    read_special=read_special, dry_run=dry_run)
  File "/bin/borg-env/lib/python3.6/site-packages/borg/archiver.py", line 631, in _process
    read_special=read_special, dry_run=dry_run)
  [Previous line repeated 1 more times]
  File "/bin/borg-env/lib/python3.6/site-packages/borg/archiver.py", line 605, in _process
    status = archive.process_file(path, st, cache)
  File "/bin/borg-env/lib/python3.6/site-packages/borg/archive.py", line 1028, in process_file
    self.chunk_file(item, cache, self.stats, backup_io_iter(self.chunker.chunkify(fd, fh)))
  File "/bin/borg-env/lib/python3.6/site-packages/borg/archive.py", line 956, in chunk_file
    item.chunks.append(chunk_processor(data))
  File "/bin/borg-env/lib/python3.6/site-packages/borg/archive.py", line 944, in chunk_processor
    chunk_entry = cache.add_chunk(self.key.id_hash(data), data, stats, wait=False)
  File "/bin/borg-env/lib/python3.6/site-packages/borg/cache.py", line 898, in add_chunk
    self.repository.put(id, data, wait=wait)
  File "/bin/borg-env/lib/python3.6/site-packages/borg/remote.py", line 476, in do_rpc
    return self.call(f.__name__, named, **extra)
  File "/bin/borg-env/lib/python3.6/site-packages/borg/remote.py", line 707, in call
    for resp in self.call_many(cmd, [args], **kw):
  File "/bin/borg-env/lib/python3.6/site-packages/borg/remote.py", line 802, in call_many
    raise Exception('FD exception occurred')
Exception: FD exception occurred

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/borg-env/lib/python3.6/site-packages/borg/archiver.py", line 4434, in main
    exit_code = archiver.run(args)
  File "/bin/borg-env/lib/python3.6/site-packages/borg/archiver.py", line 4366, in run
    return set_ec(func(args))
  File "/bin/borg-env/lib/python3.6/site-packages/borg/archiver.py", line 152, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/bin/borg-env/lib/python3.6/site-packages/borg/remote.py", line 630, in __exit__
    self.rollback()
  File "/bin/borg-env/lib/python3.6/site-packages/borg/remote.py", line 476, in do_rpc
    return self.call(f.__name__, named, **extra)
  File "/bin/borg-env/lib/python3.6/site-packages/borg/remote.py", line 707, in call
    for resp in self.call_many(cmd, [args], **kw):
  File "/bin/borg-env/lib/python3.6/site-packages/borg/remote.py", line 802, in call_many
    raise Exception('FD exception occurred')
Exception: FD exception occurred

Platform: CYGWIN_NT-6.3 Lenovo-PC 2.11.1(0.329/5/3) 2018-09-05 10:24 x86_64
Borg: 1.1.7  Python: CPython 3.6.4
PID: 8188  CWD: /home/admin/borg
sys.argv: ['/bin/borg-env/bin/borg', 'create', '-v', '-p', '-s', '--show-rc', '-C', 'lz4', 'ssh://admin@192.168.1.20:22/~/backup/notebook::share {now:%Y-%m-%d_%H:%M}', '/cygdrive/z/']
SSH_ORIGINAL_COMMAND: None

terminating with error status, rc 2
```

**Comment by ThomasWaldmann** [comment]
Also check this issue tracker and the mailing list, iirc you are not the first with that problem.
