### ISSUE TITLE
KeyError during borg create

### ISSUE THREAD

**Issue by Mebus** [borgbackup/borg#4109]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

#### Your borg version (borg -V).

borg 1.1.7

#### Operating system (distribution) and version.

Ubuntu 18.04

#### Hardware / network configuration, and filesystems used.

 * from iSCSI with ext4
* to CIFS mounted network device

#### How much data is handled by borg?

1 TB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
borg create --progress --stats --compression lz4 /mnt/mebusHomecryptBORG/homecryptBORG_repo::altes-rdiff-backup /mnt/iSCSI/boxhomecryptbackup/box-home.box--rdiff-backup
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

I was trying to do the backup and it has written about 500 GB. When I got "KeyError: 4294950911" and the backup stopped.

What can I do to successfully finish the backup?

#### Include any warning/errors/backtraces from the system logs

```
Traceback (most recent call last):
  File "borg/archiver.py", line 4434, in main
  File "borg/archiver.py", line 4366, in run
  File "borg/archiver.py", line 152, in wrapper
  File "borg/archiver.py", line 554, in do_create
  File "borg/archiver.py", line 518, in create_inner
  File "borg/archiver.py", line 631, in _process
  File "borg/archiver.py", line 631, in _process
  File "borg/archiver.py", line 631, in _process
  File "borg/archiver.py", line 631, in _process
  File "borg/archiver.py", line 631, in _process
  File "borg/archiver.py", line 631, in _process
  File "borg/archiver.py", line 631, in _process
  File "borg/archiver.py", line 631, in _process
  File "borg/archiver.py", line 605, in _process
  File "borg/archive.py", line 1028, in process_file
  File "borg/archive.py", line 960, in chunk_file
  File "borg/archive.py", line 938, in write_part_file
  File "borg/archive.py", line 447, in write_checkpoint
  File "borg/archive.py", line 485, in save
  File "borg/helpers.py", line 411, in write
  File "borg/repository.py", line 1082, in put
KeyError: 4294950911

Platform: Linux hercules 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64
Linux: debian buster/sid
Borg: 1.1.7  Python: CPython 3.5.5
PID: 2005  CWD: /home/mebus/backup_scripts/HOSTS/box/homecryptBORG/_archiv
sys.argv: ['borg', 'create', '--progress', '--stats', '--compression', 'lz4', '/mnt/mebusHomecryptBORG/homecryptBORG_repo::altes-rdiff-backup', '/mnt/iSCSI/boxhomecryptbackup/box-home.box--rdiff-backup']
SSH_ORIGINAL_COMMAND: None
```

and on another try:

```
Fatal Python error: Segmentation fault28724 N mnt/iSCSI/boxhomecryptbackup/box-home.box--rdi..._12/bli/jgraph

Current thread 0x00007fb23e7ed740 (most recent call first):
  File "borg/cache.py", line 948 in file_known_and_unchanged
  File "borg/archive.py", line 1000 in process_file
  File "borg/archiver.py", line 605 in _process
  File "borg/archiver.py", line 631 in _process
  File "borg/archiver.py", line 631 in _process
  File "borg/archiver.py", line 631 in _process
  File "borg/archiver.py", line 631 in _process
  File "borg/archiver.py", line 631 in _process
  File "borg/archiver.py", line 631 in _process
  File "borg/archiver.py", line 631 in _process
  File "borg/archiver.py", line 631 in _process
  File "borg/archiver.py", line 631 in _process
  File "borg/archiver.py", line 631 in _process
  File "borg/archiver.py", line 631 in _process
  File "borg/archiver.py", line 631 in _process
  File "borg/archiver.py", line 518 in create_inner
  File "borg/archiver.py", line 554 in do_create
  File "borg/archiver.py", line 152 in wrapper
  File "borg/archiver.py", line 4366 in run
  File "borg/archiver.py", line 4434 in main
  File "borg/__main__.py", line 2 in <module>
./archiviere_rdiff-backup.sh: Zeile 3: 11062 Speicherzugriffsfehler  (Speicherabzug geschrieben) borg create --debug --progress --stats --compression lz4 /mnt/mebusHomecryptBORG/homecryptBORG_repo::altes-rdiff-backup /mnt/iSCSI/boxhomecryptbackup/box-home.box--rdiff-backup
```

**Comment by ThomasWaldmann** [comment]
Looks like a corrupted hints file or memory corruption.

Please do the following:
- run at least one full pass of `memtest86+` on the machine that runs borg
- run `smartctl -t long /dev/sdx` for the disk that stores the repository and check `smartctl -a /dev/sdx` afterwards
- if both is ok, try `borg check --repair ...`

**Comment by Mebus** [comment]
Hallo Thomas,

thank you for the tip! I ran memtest86+ and discovered after a few minutes, that one memory module is broken. I removed the module and deleted the whole borg repository to recreate it - just to be shure.

Mebus
