### ISSUE TITLE
unable to use "borg mount" command: UnicodeEncodeError: 'ascii' codec can't encode character '\xe0' in position 44: ordinal not in range(128)

### ISSUE THREAD

**Issue by roseswe** [borgbackup/borg#4112]
Tried with default locale (de_DE.UTF-8) and "C"
PASSPHRASE etc. is exported by variables
openSUSE Leap 15.0
```
openLEAP15:0:~/borg > borg umount ~/mnt
openLEAP15:0:~/borg > borg mount -f -p $PWD ~/mnt
Local Exception
Traceback (most recent call last):
  File "borg/archiver.py", line 4434, in main
  File "borg/archiver.py", line 4366, in run
  File "borg/archiver.py", line 1352, in do_mount
  File "borg/archiver.py", line 152, in wrapper
  File "borg/archiver.py", line 1362, in _do_mount
  File "borg/fuse.py", line 340, in mount
  File "borg/fuse.py", line 34, in fuse_main
  File "src/fuse_api.pxi", line 348, in llfuse.main
  File "src/handlers.pxi", line 39, in llfuse.fuse_lookup
  File "src/handlers.pxi", line 40, in llfuse.fuse_lookup
  File "borg/fuse.py", line 557, in lookup
  File "borg/fuse.py", line 554, in _load_pending_archive
  File "borg/fuse.py", line 380, in process_archive
  File "os.py", line 862, in fsencode
UnicodeEncodeError: 'ascii' codec can't encode character '\xe0' in position 44: ordinal not in range(128)

Platform: Linux openLEAP15 4.12.14-lp150.12.19-default #1 SMP Thu Oct 4 09:55:22 UTC 2018 (f0a4346) x86_64
Linux:
Borg: 1.1.7  Python: CPython 3.5.5
PID: 4243  CWD: /home/ralph/borg
sys.argv: ['borg', 'mount', '-f', '-p', '/home/ralph/borg', '/home/ralph/mnt']
SSH_ORIGINAL_COMMAND: None

openLEAP15:2:~/borg > borg --version
borg 1.1.7

```

**Comment by infectormp** [comment]
releated to https://github.com/borgbackup/borg/issues/3750

**Comment by ThomasWaldmann** [comment]
guess this is solved.
