### ISSUE TITLE
"ValueError: No lzma support found." but lzma is installed

### ISSUE THREAD

**Issue by Akito13** [borgbackup/borg#4200]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes, too often.

## Is this a BUG / ISSUE report or a QUESTION?

Bug

#### Your borg version (borg -V).

borg 1.1.7

#### Operating system (distribution) and version.

  Operating System: Raspbian GNU/Linux 9 (stretch)
            Kernel: Linux 4.14.79-v7+
      Architecture: arm

#### Hardware / network configuration, and filesystems used.

ZFS (6A898CC3-1DD2-11B2-99A6-080020736631)

Raspberry Pi 3 B Plus

#### How much data is handled by borg?

----------Original    |   Compressed   |     Deduplicated
This archive:          28.30 GB             14.65 GB              5.93 GB
All archives:          39.57 GB             22.84 GB             13.83 GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

`borg info . --last 1`

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Create borg backup with `auto,lzma,6` on machine B sending it over SSH to machine A and try to issue command `borg info . --last 1` on machine A to check the archive.

#### Include any warning/errors/backtraces from the system logs

Python version machine with backup files:
`Python 3.7.1`

Python version on machine creating the backup
`Python 3.6.7`

```Python
Local Exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/borg/archiver.py", line 4434, in main                                       
    exit_code = archiver.run(args)
  File "/usr/local/lib/python3.7/site-packages/borg/archiver.py", line 4366, in run                                        
    return set_ec(func(args))
  File "/usr/local/lib/python3.7/site-packages/borg/archiver.py", line 149, in wrapper                                     
    cache_mode=getattr(args, 'files_cache_mode', DEFAULT_FILES_CACHE_MODE)) as cache_:                                     
  File "/usr/local/lib/python3.7/site-packages/borg/cache.py", line 379, in __new__                                        
    return local()
  File "/usr/local/lib/python3.7/site-packages/borg/cache.py", line 373, in local                                          
    lock_wait=lock_wait, cache_mode=cache_mode)
  File "/usr/local/lib/python3.7/site-packages/borg/cache.py", line 466, in __init__                                       
    self.sync()
  File "/usr/local/lib/python3.7/site-packages/borg/cache.py", line 850, in sync                                           
    self.chunks = create_master_idx(self.chunks)
  File "/usr/local/lib/python3.7/site-packages/borg/cache.py", line 804, in create_master_idx                              
    fetch_and_build_idx(archive_id, decrypted_repository, archive_chunk_idx)                                               
  File "/usr/local/lib/python3.7/site-packages/borg/cache.py", line 703, in fetch_and_build_idx                            
    csize, data = decrypted_repository.get(archive_id)
  File "/usr/local/lib/python3.7/site-packages/borg/remote.py", line 1071, in get                                          
    return next(self.get_many([key], cache=False))
  File "/usr/local/lib/python3.7/site-packages/borg/remote.py", line 1075, in get_many                                     
    yield self.transform(key, data)
  File "/usr/local/lib/python3.7/site-packages/borg/remote.py", line 1227, in transform                                    
    decrypted = key.decrypt(id_, data)
  File "/usr/local/lib/python3.7/site-packages/borg/crypto/key.py", line 299, in decrypt                                   
    data = self.decompress(payload)
  File "src/borg/compress.pyx", line 385, in borg.compress.Compressor.decompress                                           
  File "src/borg/compress.pyx", line 186, in borg.compress.LZMA.__init__                                                   
ValueError: No lzma support found.
```

**Comment by ThomasWaldmann** [comment]
The python interpreter you use was compiled without lzma support, so the problem is located there. This is a frequent issue if no lzma header and lib files were present at compile time.

You could just use zstd compression, which is a more modern and often superior compression algorithm, which covers a very wide range of compression levels.

**Comment by Akito13** [comment]
> The python interpreter you use was compiled without lzma support, so the problem is located there. This is a frequent issue if no lzma header and lib files were present at compile time.
> 
> You could just use zstd compression, which is a more modern and often superior compression algorithm, which covers a very wide range of compression levels.

I read that Python ships with lzma since 3.3 without needing to specify the need for that, that's why I was wondering. Additionally, I tried the zstd,22 compression first and then switched to lzma,6 and to me it seemed like lzma did a better job on compressing. I did not check it thoroughly, but the compression size barely went up when I was using lzma as opposed to zstd it went up very quickly and stayed only about 10% below uncompressed size. Don't know why.

**Comment by ThomasWaldmann** [comment]
If you forget to install the lzma header files, python will be compiled without lzma. I've had that a lot of times when compiling my own python binary and I guess it happens to other people (including package maintainers), too.

High zstd levels should yield a high compression. Maybe try it again in a reproducable way.
Of course compression depends on the specific input data, so YMMV.
