### ISSUE TITLE
borg config crashing

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#4223]
From the mailing list:

Just trying out borg config command, and I get an error:

BACKUP/nbecker2 is the location of a (local) repo

```
$ borg config BACKUP/nbecker2

Local Exception
Traceback (most recent call last):
 File "/home/nbecker/.local/lib/python3.7/site-packages/borg/archiver.py", line 4436, in main
   exit_code = archiver.run(args)
 File "/home/nbecker/.local/lib/python3.7/site-packages/borg/archiver.py", line 4368, in run
   return set_ec(func(args))
 File "/home/nbecker/.local/lib/python3.7/site-packages/borg/archiver.py", line 152, in wrapper
   return method(self, args, repository=repository, **kwargs)
 File "/home/nbecker/.local/lib/python3.7/site-packages/borg/archiver.py", line 1811, in do_config
   section, name = args.name.split('.')
AttributeError: 'NoneType' object has no attribute 'split'

Platform: Linux nbecker7 4.19.9-300.fc29.x86_64 #1 SMP Thu Dec 13 17:25:01 UTC 2018 x86_64
Linux: Fedora 29 Twenty Nine
Borg: 1.1.8  Python: CPython 3.7.1
PID: 7987  CWD: /home/nbecker
sys.argv: ['/home/nbecker/.local/bin/borg', 'config', 'BACKUP/nbecker2']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment]
The command as given is invalid (it neither has `--list` nor `args.name` with a key name), so borg should terminate with an error message for this.

`args.name` is specified as an optional argument as `--list` does not need it.

**Comment by AyahRamahi** [comment]
Hello, I am a beginner, can I work on this ?

**Comment by ThomasWaldmann** [comment]
Sure, just make a pull request.

**Comment by AyahRamahi** [comment]
@ThomasWaldmann I am sorry, but can you guide me on what file I should make changes on ? I am confused with all these files.

**Comment by ThomasWaldmann** [comment]
It all starts in the borg.archiver module. Each `borg foo` command has a `do_foo` method there.
