### ISSUE TITLE
python-msgpack 0.6.0: ValueError: n exceeds max_map_len(32768)

### ISSUE THREAD

**Issue by Ape** [borgbackup/borg#4251]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG report

#### Your borg version (borg -V).

1.1.8

#### Operating system (distribution) and version.

Arch Linux

#### Hardware / network configuration, and filesystems used.

btrfs

#### How much data is handled by borg?

around 200 GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
borg create -C lzma -x ::$(date +%Y-%m-%d) /path/to/files --stats
```

## Describe the problem you're observing.

Borg crashes with an exception, see below.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

This occurs everytime I try since it started a few days ago.

#### Include any warning/errors/backtraces from the system logs

```
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4436, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4368, in run
    return set_ec(func(args))
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 152, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 555, in do_create
    create_inner(archive, cache)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 518, in create_inner
    read_special=args.read_special, dry_run=dry_run, st=st)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 632, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 632, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 632, in _process
    read_special=read_special, dry_run=dry_run)
  [Previous line repeated 2 more times]
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 606, in _process
    status = archive.process_file(path, st, cache)
  File "/usr/lib/python3.7/site-packages/borg/archive.py", line 1028, in process_file
    self.chunk_file(item, cache, self.stats, backup_io_iter(self.chunker.chunkify(fd, fh)))
  File "/usr/lib/python3.7/site-packages/borg/archive.py", line 956, in chunk_file
    item.chunks.append(chunk_processor(data))
  File "/usr/lib/python3.7/site-packages/borg/archive.py", line 944, in chunk_processor
    chunk_entry = cache.add_chunk(self.key.id_hash(data), data, stats, wait=False)
  File "/usr/lib/python3.7/site-packages/borg/cache.py", line 898, in add_chunk
    self.repository.put(id, data, wait=wait)
  File "/usr/lib/python3.7/site-packages/borg/repository.py", line 1076, in put
    self.prepare_txn(self.get_transaction_id())
  File "/usr/lib/python3.7/site-packages/borg/repository.py", line 504, in prepare_txn
    hints = msgpack.unpack(fd)
  File "/usr/lib/python3.7/site-packages/msgpack/__init__.py", line 57, in unpack
    return unpackb(data, **kwargs)
  File "msgpack/_unpacker.pyx", line 187, in msgpack._cmsgpack.unpackb
ValueError: 40357 exceeds max_map_len(32768)
```

**Comment by Ape** [comment]
I checked my pacman.log and noticed that I had upgraded `python-msgpack` from `0.5.6-2` to `0.6.0-1`. This is probably the reason for this issue.

**Comment by infectormp** [comment]
That version is not supported for borg 1.1.x 
https://github.com/borgbackup/borg/issues/4245

**Comment by ThomasWaldmann** [comment]
@Ape if you got msgpack from your distribution, you need to talk to the distribution's borgbackup and msgpack maintainers.

borg 1.1.x's `setup.py` is rather specific about supported msgpack versions and 0.6.0 is not allowed by it.

**Comment by Ape** [comment]
That's unfortunate. However, I was able to fix my issue by upgrading to the master branch of borg.

**Comment by ThomasWaldmann** [comment]
@ape using master branch is not recommended, except if you want to participate in development and pre-alpha testing (and you can live with / fix yourself any compatibility / data migration issue that might come from that).
