### ISSUE TITLE
exceeds max_str_len(1048576)

### ISSUE THREAD

**Issue by macrule** [borgbackup/borg#4255]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug

#### Your borg version (borg -V).

1.1.7

#### Operating system (distribution) and version.

macOS 10.12

#### How much data is handled by borg?

around 1 to 2 TB

## Describe the problem you're observing.

I'm getting the following exception during a prune operation. This started occurring recently, probably because the archive has started growing beyond a certain limit, and is now reproducible every time.

Inspired by #2139 I fixed the issue in Archive::delete by using get_limited_unpacker('client') instead of msgpack.Unpacker(use_list=False)

#### Include any warning/errors/backtraces from the system logs

```
Local Exception
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/borg/archiver.py", line 4434, in main
    exit_code = archiver.run(args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/borg/archiver.py", line 4366, in run
    return set_ec(func(args))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/borg/archiver.py", line 152, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/borg/archiver.py", line 1589, in do_prune
    Archive(repository, key, manifest, archive.name, cache).delete(stats, forced=args.forced)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/borg/archive.py", line 805, in delete
    for item in unpacker:
  File "msgpack/_unpacker.pyx", line 533, in msgpack._cmsgpack.Unpacker.__next__
  File "msgpack/_unpacker.pyx", line 464, in msgpack._cmsgpack.Unpacker._unpack
ValueError: 3880648 exceeds max_str_len(1048576)

Platform: Darwin jupiter.fritz.box 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64 x86_64
Borg: 1.1.7  Python: CPython 3.6.7
PID: 92483  CWD: /Volumes/Users/backup
sys.argv: ['/opt/local/bin/borg', 'prune', '--info', '--stats', '--list', '--keep-within', '24H', '--keep-daily', '7', '--keep-weekly', '4', '--keep-monthly', '12', '--keep-yearly', '5', '--prefix', 'Users', 'backup@server:/backup/archive.borg']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment]
you likely run a unsupported version of msgpack (like >= 0.6.0), the solution is to use < 0.6.0, see our setup.py.

**Comment by macrule** [comment]
my msgpack is 0.6.0. if that is unsupported as suggested, it's been an error in the macports package. I trusted it to install TheRightThing™.

However, looking at https://github.com/msgpack/msgpack-python/blob/master/ChangeLog.rst there don't seem to be unsurmountable issues preventing it to work with borg. Without being a borg or msgpack expert, it looks like consistent use of get_limited_unpacker() is the key to the main issue of smaller limits in the 0.6.0 version.

**Comment by infectormp** [comment]
https://github.com/borgbackup/borg/issues/4251
