### ISSUE TITLE
Borg mount fails

### ISSUE THREAD

**Issue by matclab** [borgbackup/borg#4256]
## Have you checked borgbackup docs, FAQ, and open Github issues?

yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).
borg 1.1.8

#### Operating system (distribution) and version.
Arch linux : 4.20.0-arch1-1-ARCH #1 SMP PREEMPT Mon Dec 24 03:00:40 UTC 2018 x86_64 GNU/Linux

#### Hardware / network configuration, and filesystems used.
local SSD, encrypted ext4

#### How much data is handled by borg?
```------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
All archives:              408.18 GB            280.28 GB             56.05 GB

                       Unique chunks         Total chunks
Chunk index:                  733404              4533793
```

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```
borg mount /run/media/clabaut/CryptT5/loriot/borg-homecrypt::loriot-2019-01-08T18:40:20 /tmp/m
```

## Describe the problem you're observing.
Exception is raised 

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

`borg list` on the same repo works flawlessly.

`borg extract /run/media/clabaut/CryptT5/loriot/borg-homecrypt::loriot-2019-01-08T18:40:20 path` works ok too.

#### Include any warning/errors/backtraces from the system logs
```
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4436, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4368, in run
    return set_ec(func(args))
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 1353, in do_mount
    return self._do_mount(args)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 152, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 1363, in _do_mount
    operations.mount(args.mountpoint, args.options, args.foreground)
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 323, in mount
    self._create_filesystem()
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 252, in _create_filesystem
    self.process_archive(self.args.location.archive)
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 377, in process_archive
    consider_part_files=self.args.consider_part_files):
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 160, in iter_archive_items
    item = unpacker.unpack(write_bytes)
TypeError: unpack() takes no arguments (1 given)

Platform: Linux loriot 4.20.0-arch1-1-ARCH #1 SMP PREEMPT Mon Dec 24 03:00:40 UTC 2018 x86_64
Linux: arch  
Borg: 1.1.8  Python: CPython 3.7.2
PID: 9482  CWD: /home/clabaut/
sys.argv: ['/usr/sbin/borg', 'mount', '/run/media/clabaut/CryptT5/loriot/borg-homecrypt::loriot-2019-01-08T18:40:20', '/tmp/m']
SSH_ORIGINAL_COMMAND: None
```

**Comment by infectormp** [comment]
https://github.com/borgbackup/borg/issues/4245

**Comment by matclab** [comment]
Closed as duplicate. Sorry for the noise.
