### ISSUE TITLE
borg mount gives error

### ISSUE THREAD

**Issue by hartmark** [borgbackup/borg#4277]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug

#### Your borg version (borg -V).
borg 1.1.8

#### Operating system (distribution) and version.

$> uname -a
Linux staropramen 4.20.3-arch1-1-ARCH #1 SMP PREEMPT Wed Jan 16 22:38:58 UTC 2019 x86_64 GNU/Linux

#### Hardware / network configuration, and filesystems used.

Intel(R) Pentium(R) CPU G4560 @ 3.50GHz
8GiB RAM
/data/backup/borg where the backups are saved is a xfs partition, I used btrfs for it before and had same issue.

#### How much data is handled by borg?
Aprox 450GB with daily backups totaling 8,5TB 

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg mount -f -v /data/backup/borg  ~/cloud/borg

## Describe the problem you're observing.

Running the command above. Starts another terminal and goes into the ~/cloud/borg folder and doing ls first all is good. But if I cd into a backup I get this error:
```

Mounting filesystem
handler raised <class 'TypeError'> exception (unpack() takes no arguments (1 given)), terminating main loop.                              
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4436, in main                                                                   
    exit_code = archiver.run(args)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4368, in run                                                                    
    return set_ec(func(args))
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 1353, in do_mount                                                               
    return self._do_mount(args)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 152, in wrapper                                                                 
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 1363, in _do_mount                                                              
    operations.mount(args.mountpoint, args.options, args.foreground)
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 340, in mount                                                                       
    signal = fuse_main()
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 34, in fuse_main                                                                    
    return llfuse.main(workers=1)
  File "src/fuse_api.pxi", line 330, in llfuse.main
  File "src/handlers.pxi", line 39, in llfuse.fuse_lookup
  File "src/handlers.pxi", line 40, in llfuse.fuse_lookup
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 557, in lookup                                                                      
    self._load_pending_archive(parent_inode)
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 554, in _load_pending_archive                                                       
    self.process_archive(archive_name, [os.fsencode(archive_name)])
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 377, in process_archive                                                             
    consider_part_files=self.args.consider_part_files):
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 160, in iter_archive_items                                                          
    item = unpacker.unpack(write_bytes)
TypeError: unpack() takes no arguments (1 given)

Platform: Linux staropramen 4.20.3-arch1-1-ARCH #1 SMP PREEMPT Wed Jan 16 22:38:58 UTC 2019 x86_64                                               
Linux: arch
Borg: 1.1.8  Python: CPython 3.7.2
PID: 19491  CWD: /home/markus/cloud
sys.argv: ['/usr/bin/borg', 'mount', '-f', '-v', '/data/backup/borg', '/home/markus/cloud/borg']                                                 
SSH_ORIGINAL_COMMAND: None
```

And if I tries to mount a backup directly using this command:
`borg mount -f -v /data/backup/borg::staropramen-documents-2019-01-29T01:00:09  ~/cloud/borg`

I get this error:
```
Mounting filesystem
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4436, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4368, in run
    return set_ec(func(args))
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 1353, in do_mount
    return self._do_mount(args)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 152, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 1363, in _do_mount
    operations.mount(args.mountpoint, args.options, args.foreground)
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 323, in mount
    self._create_filesystem()
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 252, in _create_filesystem
    self.process_archive(self.args.location.archive)
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 377, in process_archive
    consider_part_files=self.args.consider_part_files):
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 160, in iter_archive_items
    item = unpacker.unpack(write_bytes)
TypeError: unpack() takes no arguments (1 given)

Platform: Linux staropramen 4.20.3-arch1-1-ARCH #1 SMP PREEMPT Wed Jan 16 22:38:58 UTC 2019 x86_64
Linux: arch  
Borg: 1.1.8  Python: CPython 3.7.2
PID: 31271  CWD: /home/markus/cloud
sys.argv: ['/usr/bin/borg', 'mount', '-f', '-v', '/data/backup/borg::staropramen-documents-2019-01-29T01:00:09', '/home/markus/cloud/borg']
SSH_ORIGINAL_COMMAND: None
```

**Comment by hartmark** [comment]
Tried using --debug with this command:

`% borg mount -f --debug /data/backup/borg::staropramen-documents-`

and got this:

```
2019-01-29T01:00:09  ~/cloud/borg
using builtin fallback logging configuration
35 self tests completed in 0.08 seconds
Verified integrity of /data/backup/borg/index.1080
TAM-verified manifest
security: read previous location '/data/backup/borg'
security: read manifest timestamp '2019-01-30T00:03:07.728053'
security: determined newest manifest timestamp as 2019-01-30T00:03:07.728053
security: repository checks ok, allowing access
mount data cache capacity: 4 chunks
Mounting filesystem
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4436, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4368, in run
    return set_ec(func(args))
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 1353, in do_mount
    return self._do_mount(args)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 152, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 1363, in _do_mount
    operations.mount(args.mountpoint, args.options, args.foreground)
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 323, in mount
    self._create_filesystem()
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 252, in _create_filesystem
    self.process_archive(self.args.location.archive)
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 377, in process_archive
    consider_part_files=self.args.consider_part_files):
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 160, in iter_archive_items
    item = unpacker.unpack(write_bytes)
TypeError: unpack() takes no arguments (1 given)

Platform: Linux staropramen 4.20.3-arch1-1-ARCH #1 SMP PREEMPT Wed Jan 16 22:38:58 UTC 2019 x86_64
Linux: arch  
Borg: 1.1.8  Python: CPython 3.7.2
PID: 2402  CWD: /home/markus/cloud
sys.argv: ['/usr/bin/borg', 'mount', '-f', '--debug', '/data/backup/borg::staropramen-documents-2019-01-29T01:00:09', '/home/markus/cloud/borg']
SSH_ORIGINAL_COMMAND: None

```

**Comment by ThomasWaldmann** [comment]
this is an arch linux packaging / dependency management problem.

your msgpack version is not supported, you need 0.5.6.

**Comment by hartmark** [comment]
Thanks for the pointer, but it seems that I still get same error after installing msgpack 0.5.6.
```

% sudo pip install msgpack-python                                                                                 :(
Collecting msgpack-python                                                                                                                        
  Downloading https://files.pythonhosted.org/packages/8a/20/6eca772d1a5830336f84aca1d8198e5a3f4715cd1c7fc36d3cc7f7185091/msgpack-python-0.5.6.tar.
gz (138kB)
    100% |████████████████████████████████| 143kB 14.6MB/s
Installing collected packages: msgpack-python
  Running setup.py install for msgpack-python ... done
Successfully installed msgpack-python-0.5.6
sudo pip install msgpack-python  5.22s user 0.26s system 102% cpu 5.375 total
```

Is there anything else I need to do?

**Comment by hartmark** [comment]
Thank you! I'll try look into the ideas you outlined today after work.

**Comment by hartmark** [comment]
I have nothing else depending on msgpack so I used this command:
`pip install msgpack==0.5.6`
And now all is well.

**Comment by SR-G** [comment]
Thanks @hartmark for the solution, i had the same problem (also archlinux), solved in the same way.
It's because of that kind of situations / errors that i don't like the python ecosystem ...
