### ISSUE TITLE
borg mount fails with exception in archiver.py 

### ISSUE THREAD

**Issue by qupfer** [borgbackup/borg#4293]
Hi, I have trouble to mount my backups. 
Thanks for help.

## Have you checked borgbackup docs, FAQ, and open Github issues?

yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug

#### Your borg version (borg -V).
borg 1.1.8

#### Operating system (distribution) and version.

Arch Linux - 4.20.5-arch1-1-ARCH

#### Hardware / network configuration, and filesystems used.
- Intel Atom x5-Z8350
- 4 GB DDR3
- Arch-Root on ext4, boot vfat
- Repo on ext4 USB HDD

#### How much data is handled by borg?
~10 GB 

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg mount /media/WD/Backups/leipzig::leipzig.07q.de-2019-01-29-030625 /media/borg
## Describe the problem you're observing.

Mounting a borg Backup cause a Local exception in archiver.py.
So I think it may related to:https://github.com/borgbackup/borg/issues/4287 

#### Can you reproduce the problem? 
Just running the commandline reproduce the problem.
Its psossible to mount the repo itself and list its archives. But trying to go inside one of them fails too. 
Borg extract works as expected. 
```
root@leipzig /home/henning # borg mount /media/WD/Backups/leipzig /media/borg
Enter passphrase for key /media/WD/Backups/leipzig: 
root@leipzig /home/henning # ls /media/borg 
leipzig.07q.de-2019-01-29-030625  leipzig.07q.de-2019-01-30-032402  leipzig.07q.de-2019-01-31-033503
root@leipzig /home/henning # ls /media/borg/leipzig.07q.de-2019-01-29-030625 
ls: cannot open directory '/media/borg/leipzig.07q.de-2019-01-29-030625': Input/output error
2 root@leipzig /home/henning # ls /media/borg                                                                                            :(
ls: cannot open directory '/media/borg': Transport endpoint is not connected                                                                                       
```

#### Include any warning/errors/backtraces from the system logs

```
root@leipzig /home/qupfer # borg mount /media/WD/Backups/leipzig::leipzig.07q.de-2019-01-29-030625 /media/borg
Enter passphrase for key /media/WD/Backups/leipzig: 
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4436, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4368, in run
    return set_ec(func(args))
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 1353, in do_mount
    return self._do_mount(args)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 152, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 1363, in _do_mount
    operations.mount(args.mountpoint, args.options, args.foreground)
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 323, in mount
    self._create_filesystem()
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 252, in _create_filesystem
    self.process_archive(self.args.location.archive)
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 377, in process_archive
    consider_part_files=self.args.consider_part_files):
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 160, in iter_archive_items
    item = unpacker.unpack(write_bytes)
TypeError: unpack() takes no arguments (1 given)

Platform: Linux leipzig.07q.de 4.20.5-arch1-1-ARCH #1 SMP PREEMPT Sat Jan 26 12:59:18 UTC 2019 x86_64
Linux: arch  
Borg: 1.1.8  Python: CPython 3.7.2
PID: 10733  CWD: /home/henning
sys.argv: ['/usr/bin/borg', 'mount', '/media/WD/Backups/leipzig::leipzig.07q.de-2019-01-29-030625', '/media/borg']
SSH_ORIGINAL_COMMAND: None
```

**Comment by infectormp** [comment]
https://github.com/borgbackup/borg/issues/4256

**Comment by ThomasWaldmann** [comment]
#4245
