### ISSUE TITLE
flake8 (pyflakes) hangs all vagrant machines, fails on travis-ci

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#4311]
pyflakes 2.1.0 is broken, causing lots of issues.

we need to downgrade if they don't release a fix ASAP.

https://github.com/PyCQA/pyflakes/issues/422

**Comment by ThomasWaldmann** [comment]
```
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 429, in _handle_results
    task = get()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 251, in recv
    return ForkingPickler.loads(buf.getbuffer())
  File "/vagrant/borg/borg/.tox/flake8/lib/python3.5/site-packages/flake8/exceptions.py", line 86, in __init__
    self.original_exception = kwargs.pop("exception")
KeyError: 'exception'



^CERROR: KEYBOARDINTERRUPT
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 680, in next
    item = self._items.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vagrant/borg/borg/.tox/flake8/lib/python3.5/site-packages/flake8/checker.py", line 294, in run_parallel
    for ret in pool_map:
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 314, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 684, in next
    self._cond.wait(timeout)
  File "/usr/lib/python3.5/threading.py", line 293, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vagrant/borg/borg/.tox/flake8/bin/flake8", line 10, in <module>
    sys.exit(main())
  File "/vagrant/borg/borg/.tox/flake8/lib/python3.5/site-packages/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/vagrant/borg/borg/.tox/flake8/lib/python3.5/site-packages/flake8/main/application.py", line 393, in run
    self._run(argv)
  File "/vagrant/borg/borg/.tox/flake8/lib/python3.5/site-packages/flake8/main/application.py", line 381, in _run
    self.run_checks()
  File "/vagrant/borg/borg/.tox/flake8/lib/python3.5/site-packages/flake8/main/application.py", line 300, in run_checks
    self.file_checker_manager.run()
  File "/vagrant/borg/borg/.tox/flake8/lib/python3.5/site-packages/flake8/checker.py", line 330, in run
    self.run_parallel()
  File "/vagrant/borg/borg/.tox/flake8/lib/python3.5/site-packages/flake8/checker.py", line 303, in run_parallel
    pool.terminate()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 505, in terminate
    self._terminate()
  File "/usr/lib/python3.5/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 537, in _terminate_pool
    assert result_handler.is_alive() or len(cache) == 0
AssertionError
ERROR: keyboardinterrupt
```

**Comment by asottile** [comment]
this patch fixes your testsuite and pyflakes btw:

```diff
diff --git a/src/borg/testsuite/archiver.py b/src/borg/testsuite/archiver.py
index 8b8bcf03..845fcf01 100644
--- a/src/borg/testsuite/archiver.py
+++ b/src/borg/testsuite/archiver.py
@@ -2857,7 +2857,7 @@ def test_export_tar_strip_components_links(self):
 
     @requires_hardlinks
     @requires_gnutar
-    def test_extract_hardlinks(self):
+    def test_extract_hardlinks_gnutar(self):
         self._extract_hardlinks_setup()
         self.cmd('export-tar', self.repository_location + '::test', 'output.tar', 'input/dir1')
         with changedir('output'):
```

You have two tests which are clobbering each other (the first test _never ever runs_ due to this)

**Comment by ThomasWaldmann** [comment]
@asottile thanks for finding this! :)

nitpick: it does not fix pyflakes, it just removes the conditions where it crashes.

**Comment by asottile** [comment]
what was broken that needed fixing if not the crash?

**Comment by ThomasWaldmann** [comment]
well, while it is wrong and might be rare(?), a duplicate test method name should not crash pyflakes and make flake8 hang.

so, it does not trigger for us any more, but until a fixed pyflakes is released, it might cause troubles elsewhere.

**Comment by ThomasWaldmann** [comment]
but cool that we found the bug in our tests that way, hehe.

**Comment by asottile** [comment]
it's a lot rarer than that, it's a decorated duplicate function (and already fixed in pyflakes) -- I'm surprised you didn't find this error sooner though -- I suspect you're currently _ignoring_ that error

**Comment by asottile** [comment]
yeah, you're currently ignore F811 which would have prevented encounted this in the first place 😆

**Comment by ThomasWaldmann** [comment]
```
flake8 runtests: commands[0] | flake8 src scripts conftest.py
src/borg/testsuite/platform.py:197:24: F811 redefinition of unused 'free_pid' from line 13
src/borg/testsuite/benchmark.py:29:19: F811 redefinition of unused 'cmd' from line 13
src/borg/testsuite/benchmark.py:56:22: F811 redefinition of unused 'cmd' from line 13
src/borg/testsuite/benchmark.py:62:33: F811 redefinition of unused 'cmd' from line 13
src/borg/testsuite/benchmark.py:67:32: F811 redefinition of unused 'cmd' from line 13
src/borg/testsuite/benchmark.py:72:29: F811 redefinition of unused 'cmd' from line 13
src/borg/testsuite/benchmark.py:78:28: F811 redefinition of unused 'cmd' from line 13
src/borg/testsuite/benchmark.py:83:26: F811 redefinition of unused 'cmd' from line 13
src/borg/testsuite/benchmark.py:88:26: F811 redefinition of unused 'cmd' from line 13
src/borg/testsuite/benchmark.py:93:27: F811 redefinition of unused 'cmd' from line 13
src/borg/testsuite/benchmark.py:99:26: F811 redefinition of unused 'cmd' from line 13
src/borg/testsuite/archiver.py:70:17: F811 redefinition of unused 'borg' from line 33
src/borg/platform/__init__.py:19:5: F811 redefinition of unused 'process_alive' from line 14
src/borg/platform/__init__.py:19:5: F811 redefinition of unused 'local_pid_alive' from line 14
src/borg/platform/__init__.py:21:5: F811 redefinition of unused 'swidth' from line 13
src/borg/platform/__init__.py:27:5: F811 redefinition of unused 'listxattr' from line 9
src/borg/platform/__init__.py:27:5: F811 redefinition of unused 'getxattr' from line 9
src/borg/platform/__init__.py:27:5: F811 redefinition of unused 'setxattr' from line 9
src/borg/platform/__init__.py:28:5: F811 redefinition of unused 'acl_get' from line 10
src/borg/platform/__init__.py:28:5: F811 redefinition of unused 'acl_set' from line 10
src/borg/platform/__init__.py:29:5: F811 redefinition of unused 'set_flags' from line 11
src/borg/platform/__init__.py:29:5: F811 redefinition of unused 'get_flags' from line 11
src/borg/platform/__init__.py:30:5: F811 redefinition of unused 'SyncFile' from line 12
```
