### ISSUE TITLE
Crash when browsing mounted repo

### ISSUE THREAD

**Issue by benjamindaines** [borgbackup/borg#4320]
Thank you for reporting an issue.

#### Hardware / network configuration, and filesystems used.
repo is stored on a server mounted via sshfs, this has worked fine in the past 

## Describe the problem you're observing.
repo mounts, but borg crashes and repo is unavailable when trying to browse. 

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
yes, tried with two different repos 

#### Include any warning/errors/backtraces from the system logs

```
[ben@pluto Desktop]$ borg mount -f /run/media/ben/Hydra/Backups/pluto/ borg/
Enter passphrase for key /run/media/ben/Hydra/Backups/pluto: 
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4436, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4368, in run
    return set_ec(func(args))
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 1353, in do_mount
    return self._do_mount(args)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 152, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 1363, in _do_mount
    operations.mount(args.mountpoint, args.options, args.foreground)
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 340, in mount
    signal = fuse_main()
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 34, in fuse_main
    return llfuse.main(workers=1)
  File "src/fuse_api.pxi", line 330, in llfuse.main
  File "src/handlers.pxi", line 436, in llfuse.fuse_opendir
  File "src/handlers.pxi", line 437, in llfuse.fuse_opendir
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 581, in opendir
    self._load_pending_archive(inode)
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 554, in _load_pending_archive
    self.process_archive(archive_name, [os.fsencode(archive_name)])
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 377, in process_archive
    consider_part_files=self.args.consider_part_files):
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 160, in iter_archive_items
    item = unpacker.unpack(write_bytes)
TypeError: unpack() takes no arguments (1 given)

Platform: Linux pluto 4.19.18-1-MANJARO #1 SMP PREEMPT Sat Jan 26 17:24:40 UTC 2019 x86_64
Linux: arch Manjaro Linux
Borg: 1.1.8  Python: CPython 3.7.2
PID: 22013  CWD: /home/ben/Desktop
sys.argv: ['/usr/bin/borg', 'mount', '-f', '/run/media/ben/Hydra/Backups/pluto/', 'borg/']
SSH_ORIGINAL_COMMAND: None

```

**Comment by ThomasWaldmann** [comment]
see #4245.
