### ISSUE TITLE
Wifiphisher Starting error child_exception OSError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by cjviola0426** [borgbackup/borg#4439]
Please help me!!!!

Locale = en-US
CommCheck64 = 614971
UpdateCheckInterval = -1
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 693, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 497, in start
    self.fw.redirect_requests_localhost()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/firewall.py", line 50, in redirect_requests_localhost
    "--to-destination {}:{}".format(NETWORK_GW_IP, SSL_PORT)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/utilities.py", line 22, in execute_commands
    _, error = Popen(command.split(), stderr=PIPE, stdout=DN).communicate()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 5] Input/output error

**Comment by infectormp** [comment]
wifiphisher is here https://github.com/wifiphisher/wifiphisher
