### ISSUE TITLE
Contains utf-8 string, but not "# -*- coding: utf-8 -*-"

### ISSUE THREAD

**Issue by charliebrady** [borgbackup/borg#4451]
```
charlieb@localhost:~/Downloads/borg $ ls
AUTHORS      LICENSE         scripts            setup_docs.py  Vagrantfile
CHANGES.rst  MANIFEST.in     setup.cfg          setup.py
conftest.py  README.rst      setup_compress.py  src
docs         requirements.d  setup_crypto.py    tox.ini
charlieb@localhost:~/Downloads/borg $ python setup.py 
Traceback (most recent call last):
  File "setup.py", line 25, in <module>
    import setup_docs
  File "/home/charlieb/Downloads/borg/setup_docs.py", line 149
SyntaxError: Non-ASCII character '\xe2' in file /home/charlieb/Downloads/borg/setup_docs.py on line 149, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
charlieb@localhost:~/Downloads/borg $

charlieb@localhost:~/Downloads/borg $ sed -n 149p setup_docs.py 
                    group_header += ' — ' + group.description
charlieb@localhost:~/Downloads/borg $ ```

**Comment by ThomasWaldmann** [comment]
What does `python --version` say?

**Comment by ThomasWaldmann** [comment]
no reply, closing.
