### ISSUE TITLE
locking exeption

### ISSUE THREAD

**Issue by WCJLJZUBTSC** [borgbackup/borg#4453]
## Have you checked borgbackup docs, FAQ, and open Github issues?
Yes, there were some that were close, but not the same

## Is this a BUG / ISSUE report or a QUESTION?

bug

#### Your borg version (borg -V).
1.1.9

#### Operating system (distribution) and version.
ubuntu mate 18.04

#### Hardware / network configuration, and filesystems used.
borg over ssh to freenas using same version. zfs fs

#### How much data is handled by borg?
```
                       Original size      Compressed size    Deduplicated size
This archive:              124.42 GB            111.69 GB              7.53 MB
All archives:               15.32 TB             14.55 TB            369.97 GB

                       Unique chunks         Total chunks
Chunk index:                  286337             11379469
```

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```
/usr/bin/borg', 'create', '-s', '--list', '--filter', 'AME', '.................', '............',
  '--exclude-from', '.............', '--one-file-system'
```

## Describe the problem you're observing.
had a long running backup with file permission change. i think what happened was before it finished an automated borg diff ran.  ran the command to clear the lock and had same problem.  running check right now.

#### Include any warning/errors/backtraces from the system logs
```
----------------------docs------------------------------
A /...........
------------------------------------------------------------------------------
Archive name: ..............
Archive fingerprint: ................
Time (start): Mon, 2019-03-18 09:22:23
Time (end):   Mon, 2019-03-18 09:26:31
Duration: 4 minutes 8.93 seconds
Number of files: 61104
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:              124.42 GB            111.69 GB              7.53 MB
All archives:               15.32 TB             14.55 TB            369.97 GB

                       Unique chunks         Total chunks
Chunk index:                  286337             11379469
------------------------------------------------------------------------------
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4455, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4387, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 154, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 557, in do_create
    create_inner(archive, cache)
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 477, in __exit__
    self.close()
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 509, in close
    self.cache_config.close()
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 314, in close
    self.lock.release()
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 383, in release
    self._roster.modify(EXCLUSIVE, REMOVE)
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 282, in modify
    elements.remove(self.id)
KeyError: ('............', 2619, 0)

Platform: Linux media 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64
Linux: Ubuntu 18.04 bionic
Borg: 1.1.9  Python: CPython 3.6.7
PID: 2619  CWD: ..............
sys.argv: ['/usr/bin/borg', 'create', '-s', '--list', '--filter', 'AME', '.................', '............', '--exclude-from', '.............', '--one-file-system']
SSH_ORIGINAL_COMMAND: None
```

```
----------------------dev------------------------------
Failed to create/acquire the lock ...........lock.exclusive (timeout).
```

**Comment by ThomasWaldmann** [comment]
Looks like a normal lock acquisition problem (if the lock is already taken by sth else).

What do you mean by "docs" and "dev"?

**Comment by WCJLJZUBTSC** [comment]
> what exactly do you mean by "with file permission change
the changes were +w for the group

the problem is that after the lock was cleared.  I re-ran and it gave a locking error.  
I did not check, but I wonder if there was a process in the background still holding the lock.

borg check resulted in no issues

i'm running the backup today and no problems.  

looks like user error, sorry
