### ISSUE TITLE
windows maintainers / developers wanted

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#4466]
So, who wants to commit to develop, maintain, review windows related code?

There is some code already in master, more code is waiting in "windows" branch.

The main blockers to get more stuff into master are:
- there need to be (windows) devs reviewing the already existing code before it gets into master
- there need to be (windows) devs maintaining it in future and managing development of that part of borg - this is a long term thing, not a one time work.
- stuff must be tested on windows. automated and likely sometimes also manual.
- either windows branch must be brought into a better and reviewed state so it can be fully merged into master or smaller PRs could be made against master.
- there should be an extension to our Vagrantfile so we can use vagrant to provision a windows VM for testing / running the tests locally / debugging independent of developer's base OS.

So whoever wants to help, please add a comment below and state how you can help.

**Comment by ThomasWaldmann** [comment]
About myself:

I can help with generic borg advice, but not with anything that requires knowledge of windows / ntfs / win32 api specific stuff.

I can review PRs that are relatively generic / simple, but if it gets too deep into win32 / ntfs, there must be other reviewers.

**Comment by mrhut10** [comment]
I'm happy to test stuff, like person above I don't know win32 api off the to of my head. But would loved to use Borg on windows so please enlist my help to test when you can.

**Comment by Anakonda** [comment]
I'm windows dev and happy to help.

**Comment by jrast** [comment]
I started to poke around with windows 10 and borg. You can find my progress in the win10 branch: https://github.com/jrast/borg/tree/win10

I started with the borg master branch (not the windows branch which already had some windows related changes). As I just started the work, there is not much to see... But borg compiles and is installable. A simple `borg` does not crash.

**Comment by jrast** [comment]
Is the idea to run borg directly on windows or should cygwin / WSL be used to run borg and just improve the windows specific details? In my opinion WSL is to complex for new users, and even for users who can handle WSL it's not optimal as the backup system lives (more or less) in another system. Cygwin would be an option as all dependencies can be packed together in a single executable or distribution. Running borg on windows without WSL or cygwin is ambitious but would offer the greatest flexibility.

**Comment by Anakonda** [comment]
There is already cygwin build i don't know its status.
I understood this would be native build.

**Comment by ThomasWaldmann** [comment]
I tried cygwin now and then and at least the tests mostly worked (building and installing it on cygwin works / feels a lot like on linux). I don't use borg productively for windows though.

**Comment by jrast** [comment]
I'm currently working with the Cygwin build for personal backups. It's working fine so far but building new releases is not as easy as it seems.

A native build would be nice, even if it is a lot of (initial) work. But let's do this!

**Comment by henfri** [comment]
Hello,

how do we organize bugs in the windows variant?
Here an Example:
`c:\Program Files\Borg>borg init --encryption=repokey borg@homeserver:/media/22cd0c22-c75b-432a-b92b-73229607a8bd/Backups/borg/Windows

borg@homeserver's password:
Exception ignored in: <function RemoteRepository.__del__ at 0x000002132EAD1288>
Traceback (most recent call last):
  File "borg\remote.py", line 616, in __del__
AssertionError: cleanup happened in Repository.__del__
Local Exception
Traceback (most recent call last):
  File "borg\archiver.py", line 4434, in main
  File "borg\archiver.py", line 4366, in run
  File "borg\archiver.py", line 147, in wrapper
  File "borg\remote.py", line 558, in __init__
AttributeError: module 'os' has no attribute 'set_blocking'

Borg: 1.2.0a7.dev96+gd31afcb2  Python: CPython 3.7.4 msgpack: 0.6.1
PID: 12996  CWD: c:\Program Files\Borg
sys.argv: ['borg', 'init', '--encryption=repokey', 'borg@homeserver:/media/22cd0c22-c75b-432a-b92b-73229607a8bd/Backups/borg/Windows']
SSH_ORIGINAL_COMMAND: None`

Should we create a new issue with a "[Windows]" in the Title?
Or shall we collect all in this issue?

Greetings,
Hendrik

**Comment by ThomasWaldmann** [comment]
Please move that to a separate issue. There is a "os: windows" label for these.

**Comment by henfri** [comment]
ok

**Comment by ThomasWaldmann** [comment]
Update: we have windows-based testing in github action CI now.

**Comment by ThomasWaldmann** [comment]
Not sure if this is useful / gets read.

**Comment by henfri** [comment]
It is useful and does get read. :-)

**Comment by ThomasWaldmann** [comment]
Well, the goal here is to have some windows developer continuously caring for borg on windows.

While there were some contributions and improvements, this did not happen yet, although this issue is open for many years.

**Comment by henfri** [comment]
Hello,

@marcpope is maintaining a working and maintained (native Win32 + MSVC) fork here:
https://github.com/marcpope/borg-windows

Maybe it is worth to join forces?

Greetings,
Hendrik

**Comment by ThomasWaldmann** [comment]
The fork is based on borg 1.4-maint - that is good for current production usage, but for the not-too-far future, we will need borg master branch (borg 2).

**Comment by henfri** [comment]
Yes, I understand that. 
But looking at the status quo, I am wondering whether first a consolidation would be senseful in a sense of focusing on one variant
There is cygwin, WSL, a native port in the official repository (quite outdated I think) and Marcs fork. 

I have no way to judge which one is most promising. But is there a place for all of these variants?

**Comment by ThomasWaldmann** [comment]
The windows related planning should be done by a Windows developer - that's not me. :-)

**Comment by marcpope** [comment]
I am not a great windows developer, I have been using Claude Fable to help quite a bit, which has had some good success. What I've been doing is waiting for your release and then merging changes into the Windows branch. With Borg Backup Server gaining a lot of momentum, I am not sure I have enough free time to dedicate to ongoing development with borg2. I was hoping it would eventually be merged into borg's main branch and some eager developer would keep it going.

We do have quite a few users using borg-windows with success, and have had very little issues.

There's a few key differences:

- Windows doesn't have FUSE (Alternatives like WinFsp, Dokany, or Windows native ProjFS maybe).
- There's no root file system like in Linux/Mac. So I have Drive Letters encoded in the path like C/Windows or D/Backups etc and then when restoring, you have to cd to drive letter and restore with  `--strip-components 1` to remove the drive letter (if you want to over-write files in place).
- Windows SSH Bug:  My borg requires the **Git for Windows** version of SSH or borg will hang in some instances. 


Adding on: I am glad to look at borg2 the same way I am doing borg 1.4.x maint and see what we come up with, but since it's marked as alpha and not to use in production, I've been waiting until it's further along.

**Comment by ThomasWaldmann** [comment]
@marcpope Also using Claude a lot recently, also with good results. \o/

- "FUSE": since b23, we have WebDAV now. should be usable instead in quite some, but maybe not all, use cases.
- drive letters are also solved in master branch / b23 - in the same way as you did.
- ssh: maybe try to reproduce the ssh issue with b23+ - the RPC code got completely replaced (using rest-http over stdio over ssh now, the borg-rpc over stdio over ssh is only used for borg transfer --from-borg1)
