### ISSUE TITLE
CentOS 7 package missing dependencies

### ISSUE THREAD

**Issue by dtu-compute** [borgbackup/borg#4469]
When installing with `yum --enablerepo=epel install borgbackup` then one have to install `yum install python34-ruamel-yaml` afterwards as this dependency is not installed.

The problem then becomes that `pykwalify` is needed, as seen below, and no Python 3 package exist for CentOS 7. So Borg can't be installed.

```
# generate-borgmatic-config
Traceback (most recent call last):
  File "/usr/bin/generate-borgmatic-config", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pykwalify>=1.6.0' distribution was not found and is required by borgmatic
```

**Comment by ThomasWaldmann** [comment]
looks rather like a `borgmatic` issue, not a `borg` issue?

@witten ^^^

**Comment by witten** [comment]
Yes, this is a traceback from borgmatic and not Borg. Feel free to close. @dtu-compute, you can file a borgmatic ticket if you like here: https://torsion.org/borgmatic/#issues

However it sounds like this may be a problem with the CentOS/EPEL Borg or borgmatic package, which I don't maintain. You may also be interested in this borgmatic ticket: https://projects.torsion.org/witten/borgmatic/issues/151
