### ISSUE TITLE
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-3fzzpeqf/borgbackup

### ISSUE THREAD

**Issue by depresnak** [borgbackup/borg#4479]
Hello 
I use 
```
Distributor ID: Debian
Description:    Debian GNU/Linux 8.2 (jessie)
Release:        8.2
Codename:       jessie
```

I install the dependencies
```
python3python3-dev python3-pip python-virtualenv 
libssl-dev openssl 
libacl1-dev libacl1 
build-essential
libfuse-dev fuse pkg-config
``` 

I get an error:
```
 pip3 install borgbackup
Downloading/unpacking borgbackup
  Downloading borgbackup-1.1.9.tar.gz (3.5MB): 3.5MB downloaded
  Running setup.py (path:/tmp/pip-build-3fzzpeqf/borgbackup/setup.py) egg_info for package borgbackup
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-3fzzpeqf/borgbackup/setup.py", line 859, in <module>
        extras_require=extras_require,
      File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 266, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python3.4/distutils/dist.py", line 280, in __init__
        self.finalize_options()
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 301, in finalize_options
        ep.load()(self, ep.name, value)
      File "/tmp/pip-build-3fzzpeqf/borgbackup/setuptools_scm-3.2.0-py3.4.egg/setuptools_scm/integration.py", line 10, in version_keywor                d
      File "/tmp/pip-build-3fzzpeqf/borgbackup/setuptools_scm-3.2.0-py3.4.egg/setuptools_scm/version.py", line 66, in _warn_if_setuptool                s_outdated
    setuptools_scm.version.SetuptoolsOutdatedWarning: your setuptools is too old (<12)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-3fzzpeqf/borgbackup/setup.py", line 859, in <module>

    extras_require=extras_require,

  File "/usr/lib/python3.4/distutils/core.py", line 108, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 266, in __init__

    _Distribution.__init__(self,attrs)

  File "/usr/lib/python3.4/distutils/dist.py", line 280, in __init__

    self.finalize_options()

  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 301, in finalize_options

    ep.load()(self, ep.name, value)

  File "/tmp/pip-build-3fzzpeqf/borgbackup/setuptools_scm-3.2.0-py3.4.egg/setuptools_scm/integration.py", line 10, in version_keyword

  File "/tmp/pip-build-3fzzpeqf/borgbackup/setuptools_scm-3.2.0-py3.4.egg/setuptools_scm/version.py", line 66, in _warn_if_setuptools_ou                tdated

setuptools_scm.version.SetuptoolsOutdatedWarning: your setuptools is too old (<12)

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-3fzzpeqf/borgbackup
Storing debug log for failure in /root/.pip/pip.log

```
How it`s fix?

**Comment by infectormp** [comment]
> your setuptools is too old

**Comment by depresnak** [comment]
can I  upgrade setuptools?

**Comment by infectormp** [comment]
why not?

**Comment by depresnak** [comment]
what version is needed?

**Comment by infectormp** [comment]
12+

**Comment by infectormp** [comment]
just run `pip3 update setuptools`

**Comment by ThomasWaldmann** [comment]
maybe some related stuff is also rather old, like `pip` (maybe `wheel` also?).

in any case: not a borg issue, thus i am closing this.
