### ISSUE TITLE
borg mount gives Transport endpoint is not connected

### ISSUE THREAD

**Issue by greencopper** [borgbackup/borg#4496]
I am running with borg 1.1.8 on Arch Linux.

```
$ borg mount /home/foo/backup/ /home/foo/tmp
$ cd tmp
$ ls
ls: cannot open directory '.': Transport endpoint is not connected
$ mount
borgfs on /home/foo/tmp type fuse (ro,nosuid,nodev,relatime,user_id=1000,group_id=998)
```

So with "-f" and "--debug" I get:

```
 $ borg mount -f --debug /home/foo/backup/ /home/foo/tmp
using builtin fallback logging configuration
35 self tests completed in 0.06 seconds
Verified integrity of /home/foo/backup/index.4
TAM-verified manifest
security: read previous location '/home/foo/backup'
security: read manifest timestamp '2019-04-06T12:39:03.018005'
security: determined newest manifest timestamp as 2019-04-06T12:39:03.018005
security: repository checks ok, allowing access
mount data cache capacity: 8 chunks
Mounting filesystem
Initializing llfuse
Calling fuse_mount
Calling fuse_lowlevel_new
Calling fuse_session_add_chan
Calling fuse_session_loop
handler raised <class 'TypeError'> exception (unpack() takes no arguments (1 given)), terminating main loop.
Terminated main loop because request handler raised exception, re-raising..
Calling fuse_session_remove_chan
Calling fuse_session_destroy
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4436, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4368, in run
    return set_ec(func(args))
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 1353, in do_mount
    return self._do_mount(args)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 152, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 1363, in _do_mount
    operations.mount(args.mountpoint, args.options, args.foreground)
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 340, in mount
    signal = fuse_main()
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 34, in fuse_main
    return llfuse.main(workers=1)
  File "src/fuse_api.pxi", line 330, in llfuse.main
  File "src/handlers.pxi", line 436, in llfuse.fuse_opendir
  File "src/handlers.pxi", line 437, in llfuse.fuse_opendir
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 581, in opendir
    self._load_pending_archive(inode)
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 554, in _load_pending_archive
    self.process_archive(archive_name, [os.fsencode(archive_name)])
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 377, in process_archive
    consider_part_files=self.args.consider_part_files):
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 160, in iter_archive_items
    item = unpacker.unpack(write_bytes)
TypeError: unpack() takes no arguments (1 given)

Platform: Linux 5.0.6-arch1-1-ARCH x86_64
Linux: arch Arch Linux
Borg: 1.1.8  Python: CPython 3.7.3
PID: 19613  CWD: /home/foo
sys.argv: ['/usr/bin/borg', 'mount', '-f', '--debug', '/home/foo/backup/', '/home/foo/tmp']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment]
You're running an unsupported msgpack version.

**Comment by greencopper** [comment]
What are you talking about?

**Comment by ThomasWaldmann** [comment]
You can solve this by uninstalling the bad borgbackup package from arch and using the fat binary package from there:

https://github.com/borgbackup/borg/releases/tag/1.1.9

**Comment by ThomasWaldmann** [comment]
if you're interested in details, just search the tickets about msgpack (and arch linux) here, this has already been covered a lot and i am not willing to support a linux distribution that doesn't get dependencies right.

**Comment by greencopper** [comment]
I am sorry, but this is utter bogus!

I just found the problem discussed here: https://bugs.archlinux.org/task/61346?project=5&string=borg

This is clearly an upstream problem and not an Arch specific problem.

This makes Borg completely useless to me with such dependency issues. I'm gonna stick with rsync, at least I can access my files then.

**Comment by greencopper** [comment]
And also discussed here: https://bbs.archlinux.org/viewtopic.php?id=244846

**Comment by ThomasWaldmann** [comment]
arch linux at some time had a working borgbackup and installed it with a supported msgpack package.

then they broke it by:
- changing the msgpack dependency requirements in setup.py (given by borg development after a lot of compatibility testing with msgpack)
- upgrading the msgpack package to an unsupported version

thus: not my problem.
