### ISSUE TITLE
Testing the built binary itself (not just unit tests)

### ISSUE THREAD

**Issue by noplanman** [borgbackup/borg#4580]
@ThomasWaldmann Are there any / is there any testsuite around that @bauerj and I can use for the [borg-binary-builder](https://git.feneas.org/borg-binary-builder/borg-binaries/) project, to test the actual binaries that get built, to ensure that all features work?

Or do the unit tests in the given environment ensure that anyway, making it superfluous to test the binaries themselves?

**Comment by ThomasWaldmann** [comment]
The `borg.testsuite.archiver` tests run in misc. modes:
- local repo vs. remote repo
- python (same process) vs. calling an external `borg.exe`

I use this to test the pyinstaller-made borg binary, but it could be used to test any binary, just name it like that.

**Comment by noplanman** [comment]
Hi @ThomasWaldmann, thanks for that, perfect!

I've noticed that the testsuite takes quite some time, as it installs the whole virtual environment again in a dedicated folder. I've tried to reuse the same venv as when building the binary, but that doesn't seem to work :confused: 

What I've tried is to set the `envdir` in `tox.ini` like:
```
...
[testenv]
envdir=/borg-env
...
```

I've also removed the `--recreate` (`-r`) flag from the `commands` property, to prevent the venv from being reset.

Error I'm getting when running `tox -e py35 borg.testsuite.archiver`:
```
GLOB sdist-make: /borg/setup.py
py35 create: /borg-env
ERROR: invocation failed (exit code 2), logfile: /borg-env/log/py35-0.log
================================== log start ===================================

=================================== log end ====================================
ERROR: InvocationError for command /borg-env/bin/python3 -m virtualenv --no-download --python /borg-env/bin/python3 borg-env (exited with code 2)
___________________________________ summary ____________________________________
ERROR:   py35: InvocationError for command /borg-env/bin/python3 -m virtualenv --no-download --python /borg-env/bin/python3 borg-env (exited with code 2)
Traceback (most recent call last):
  File "/borg-env/bin/tox", line 10, in <module>
  File "/borg-env/lib/python3.5/site-packages/tox/session/__init__.py", line 42, in cmdline
  File "/borg-env/lib/python3.5/site-packages/tox/session/__init__.py", line 66, in main
  File "/borg-env/lib/python3.5/site-packages/tox/session/__init__.py", line 190, in runcommand
  File "/usr/local/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/borg-env/lib/python3.5/site-packages/tox/session/__init__.py", line 198, in cleanup
  File "/borg-env/lib/python3.5/site-packages/pluggy/hooks.py", line 289, in __call__
  File "/borg-env/lib/python3.5/site-packages/pluggy/manager.py", line 68, in _hookexec
  File "/borg-env/lib/python3.5/site-packages/pluggy/manager.py", line 62, in <lambda>
  File "/borg-env/lib/python3.5/site-packages/pluggy/callers.py", line 208, in _multicall
  File "/borg-env/lib/python3.5/site-packages/pluggy/callers.py", line 80, in get_result
  File "/borg-env/lib/python3.5/site-packages/pluggy/callers.py", line 187, in _multicall
  File "/borg-env/lib/python3.5/site-packages/tox/package/__init__.py", line 72, in tox_cleanup
  File "/borg-env/lib/python3.5/site-packages/py/_path/local.py", line 209, in remove
  File "/borg-env/lib/python3.5/site-packages/py/_path/local.py", line 384, in check
  File "/borg-env/lib/python3.5/site-packages/py/_path/common.py", line 235, in check
  File "/borg-env/lib/python3.5/site-packages/py/_path/common.py", line 102, in _evaluate
  File "/borg-env/lib/python3.5/site-packages/py/_vendored_packages/apipkg.py", line 148, in __makeattr
  File "/borg-env/lib/python3.5/site-packages/py/_vendored_packages/apipkg.py", line 69, in importobj
ImportError: No module named 'py._code'
```

It would be great if I could somehow reuse the venv to save time, any ideas?

**Comment by ThomasWaldmann** [comment]
Looks like a crash in pytest / apipkg. Didn't see that yet, so no idea. Can you just try `tox -e py35`?

**Comment by noplanman** [comment]
Same thing. It looks like tox does clear out the passed envdir anyway, so the python that's being executed gets deleted, which i "think" is why it suddenly dies like that.

As I'm building in docker, I'm now trying without any environment and just building an initial base with a duplicate env for now, to see if at least like that it can be reused.

Any tips on speeding up the tests? It seems to take quite some time until the actual testing starts, maybe there's a way of caching the "checking for all available tests" process?

**Comment by ThomasWaldmann** [comment]
The archiver tests are high-level and thus rather slow. Esp. the "remote" and "binary" ones.

There are also some benchmarks, but these are skipped with the default tox.ini.

No idea about your other questions, sorry.

**Comment by probinso** [comment]
Was there a solution to this problem? @noplanman

**Comment by noplanman** [comment]
@probinso Unfortunately not and i stopped looking.

My "test" now consists of `borg -V` to ensure the binary "works" and isn't corrupt in any way.

Not sure if that helps you in any way.
Why do you ask? Are you attempting something similar?

**Comment by probinso** [comment]
this looks to be a bug in tox.

**Comment by noplanman** [comment]
Thanks for explaining!
