### ISSUE TITLE
Borg create hangs silently on LV snapshot

### ISSUE THREAD

**Issue by balazsdukai** [borgbackup/borg#4590]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes. Seen [#3858](https://github.com/borgbackup/borg/issues/3858), [#3866](https://github.com/borgbackup/borg/issues/3866), [#4212](https://github.com/borgbackup/borg/issues/4212)

## Is this a BUG / ISSUE report or a QUESTION?

Issue

#### Your borg version (borg -V).
borg 1.1.9

#### Operating system (distribution) and version.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

#### Hardware / network configuration, and filesystems used.
ext4 with LVM

Tried to back up to:

+ external HD through usb 3
+ remote machine (ubuntu 16.04, ext4 with LVM) through ssh

#### How much data is handled by borg?
80GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```
'/usr/bin/borg', 'create', '--verbose', '--progress', '--debug', '--show-rc', '--stats', '--one-file-system', '--read-special', '--compression', 'lz4', '--checkpoint-interval', '86400', <excludes>, 'balazs@otthon:/home/balazs/backup/repos/balazslaptop::borg-home', '/mnt/home_snapshot/'
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

I create an LV snapshot of `/home` and mount it to `/mnt/home_snapshot`. Then run `borg create` on `/mnt/home_snapshot`.  Then borg create hangs after a specific amount of data, always 29.83GB with the configuration that I provided. If don't exclude any folders, then borg hangs at 48.05GB.

The borg create from snapshots of other LVs (incl. root) work without problems.

I tried to back up to both and external HD, and a remote machine.

I ran `fsck` on `/home` and its snapshot, didn't find any problems.

I moved, erased the file(s) where borg create hangs, but then it simply hangs at other files. But always after the given amount of data, and on `/home`.

I'm not certain that this is even a borg issue, but at this point I'm don't really know where else to look, what else to try. Thus any help would be appreciated.

#### Include any warning/errors/backtraces from the system logs
Log from borg create
```
using builtin fallback logging configuration
35 self tests completed in 0.08 seconds
SSH command line: ['ssh', 'balazs@otthon', 'borg', 'serve', '--umask=077', '--debug']
Remote: using builtin fallback logging configuration
Remote: 35 self tests completed in 0.13 seconds
Remote: using builtin fallback logging configuration
Remote: Initialized logging system for JSON-based protocol
Remote: Resolving repository path b'/home/balazs/backup/repos/balazslaptop'
Remote: Resolved repository path to '/home/balazs/backup/repos/balazslaptop'
Remote: Verified integrity of /home/balazs/backup/repos/balazslaptop/index.1
TAM-verified manifest
security: read previous location 'ssh://balazs@otthon/home/balazs/backup/repos/balazslaptop'
security: read manifest timestamp '2019-05-23T20:36:45.862475'
security: determined newest manifest timestamp as 2019-05-23T20:36:45.862475
security: repository checks ok, allowing access
Creating archive at "balazs@otthon:/home/balazs/backup/repos/balazslaptop::borg-home"
Verified integrity of /home/balazs/.cache/borg/4eccfaa32f8bacb354e22354f4ddec4ec8eb60ef273977f87d4c8632a93cda10/chunks
Reading files cache ...
security: read previous location 'ssh://balazs@otthon/home/balazs/backup/repos/balazslaptop'
security: read manifest timestamp '2019-05-23T20:36:45.862475'
security: determined newest manifest timestamp as 2019-05-23T20:36:45.862475
security: repository checks ok, allowing access
Processing files ...
/mnt/home_snapshot/lost+found: scandir: [Errno 13] Permission denied: '/mnt/home_snapshot/lost+found'
Remote: Cleaned up 6 uncommitted segment files (== everything after segment 1).            
Remote: Verified integrity of /home/balazs/backup/repos/balazslaptop/hints.1
/mnt/home_snapshot/balazs/.config/borg/security/3b85d174e2a73c2c0d0e796c4a85a6a0ba6cfb88506f5f13ef15af37d447d190: scandir: [Errno 13] Permission denied: '/mnt/home_snapshot/balazs/.config/borg/security/3b85d174e2a73c2c0d0e796c4a85a6a0ba6cfb88506f5f13ef15af37d447d190'
/mnt/home_snapshot/balazs/.config/borg/security/3dbc180c8fea5f886af08f6bc7655563efde62d60f04a0ef76a1dad3ce0a2d53: scandir: [Errno 13] Permission denied: '/mnt/home_snapshot/balazs/.config/borg/security/3dbc180c8fea5f886af08f6bc7655563efde62d60f04a0ef76a1dad3ce0a2d53'
/mnt/home_snapshot/balazs/.ansible: scandir: [Errno 13] Permission denied: '/mnt/home_snapshot/balazs/.ansible'
29.83 GB O 21.71 GB C 19.14 GB D 199451 N mnt/home_snapshot/bal...utorials/files/noise.json
```

traceback after ctrl+c
```
^CRemoteRepository: 19.15 GB bytes sent, 1.61 MB bytes received, 157749 messages sente.json
Connection closed by remote host
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 154, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 557, in do_create
    create_inner(archive, cache)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 520, in create_inner
    read_special=args.read_special, dry_run=dry_run, st=st)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 634, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 634, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 634, in _process
    read_special=read_special, dry_run=dry_run)
  [Previous line repeated 1 more time]
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 655, in _process
    status = archive.process_file(path, st, cache)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 1032, in process_file
    fh = Archive._open_rb(path)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 1058, in _open_rb
    return os.open(path, flags_noatime)
  File "/usr/lib/python3/dist-packages/borg/helpers.py", line 2245, in handler
    raise exc_cls
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4455, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4387, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 154, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 635, in __exit__
    self.rollback()
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 478, in do_rpc
    return self.call(f.__name__, named, **extra)
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 713, in call
    for resp in self.call_many(cmd, [args], **kw):
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 846, in call_many
    raise ConnectionClosed()
borg.remote.ConnectionClosed: Connection closed by remote host

Platform: Linux balazs-laptop 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64
Linux: Ubuntu 18.04 bionic
Borg: 1.1.9  Python: CPython 3.6.7
PID: 31548  CWD: /home/balazs
sys.argv: ['/usr/bin/borg', 'create', '--verbose', '--progress', '--debug', '--show-rc', '--stats', '--one-file-system', '--read-special', '--compression', 'lz4', '--checkpoint-interval', '86400', '--exclude', '/mnt/home_snapshot/balazs/Downloads', '--exclude', '/mnt/home_snapshot/balazs/Library', '--exclude', '/mnt/home_snapshot/balazs/Studies', '--exclude', '/mnt/home_snapshot/balazs/.cache', 'balazs@otthon:/home/balazs/backup/repos/balazslaptop::borg-home', '/mnt/home_snapshot/']
SSH_ORIGINAL_COMMAND: None

terminating with error status, rc 2
```

strace for borg create
```
stat("/usr/lib/python3/dist-packages/borg/helpers.py", {st_mode=S_IFREG|0644, st_size=87877, ...}) = 0
openat(AT_FDCWD, "/usr/lib/python3/dist-packages/borg/helpers.py", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=87877, ...}) = 0
ioctl(3, TCGETS, 0x7ffd143b8af0)        = -1 ENOTTY (Inappropriate ioctl for device)
lseek(3, 0, SEEK_CUR)                   = 0
read(3, "import argparse\nimport contextli"..., 4096) = 4096
lseek(3, 0, SEEK_CUR)                   = 4096
read(3, "BUFSIZE, MAX_OBJECT_SIZE),\n     "..., 8192) = 8192
read(3, " m.get('item_keys', []))\n\n      "..., 8192) = 8192
read(3, " no microsecs support.\n        f"..., 8192) = 8192
read(3, "on = isoformat\n\n\ndef format_file"..., 8192) = 8192
read(3, " re.compile(r\"\"\"\n        (\n     "..., 8192) = 8192
read(3, "    os.dup2(fd, 0)\n    os.dup2(f"..., 8192) = 8192
read(3, "SET with a logging config file,\n"..., 8192) = 8192
read(3, "ostname of host on which this ar"..., 8192) = 8192
read(3, "(source)\n            if item_typ"..., 8192) = 8192
read(3, "candir_keyfunc)\n\n\ndef clean_line"..., 8192) = 8192
read(3, ".\n        # thus we install the "..., 8192) = 1861
read(3, "", 8192)                       = 0
close(3)                                = 0
uname({sysname="Linux", nodename="balazs-laptop", ...}) = 0
openat(AT_FDCWD, "/etc/lsb-release", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=105, ...}) = 0
ioctl(3, TCGETS, 0x7ffd143ba180)        = -1 ENOTTY (Inappropriate ioctl for device)
lseek(3, 0, SEEK_CUR)                   = 0
ioctl(3, TCGETS, 0x7ffd143ba160)        = -1 ENOTTY (Inappropriate ioctl for device)
lseek(3, 0, SEEK_CUR)                   = 0
read(3, "DISTRIB_ID=Ubuntu\nDISTRIB_RELEAS"..., 8192) = 105
read(3, "", 8192)                       = 0
close(3)                                = 0
getpid()                                = 31548
getcwd("/home/balazs", 1024)            = 13
munmap(0x7f03feafb000, 262144)          = 0
munmap(0x7f03feabb000, 262144)          = 0
munmap(0x7f03fe8fb000, 262144)          = 0
...
```

**Comment by infectormp** [comment]
https://github.com/borgbackup/borg/issues/4590?

**Comment by balazsdukai** [comment]
Thanks for the pointer. But I have the same issue both with an external drive and a remote machine, so I don't believe it's related to connection/ssh/timeout. Or could it be?

**Comment by infectormp** [comment]
I see two problems here:
* `borg.remote.ConnectionClosed: Connection closed by remote host` so perhaps this is connection/ssh/timeout.
* `scandir: [Errno 13] Permission denied` perhaps the usual permission mix up by using different users, see https://github.com/borgbackup/borg/issues/3616

**Comment by balazsdukai** [comment]
I tried again with a plain local hard drive and borg hangs the same way as before.

I also tried initializing a new repo without `sudo`, just for my `home` dir (as [this](https://github.com/borgbackup/borg/issues/3616#issuecomment-365349720) suggests), but I get the same issue.

Traceback:
```
using builtin fallback logging configuration
35 self tests completed in 0.08 seconds
Verified integrity of /mnt/backup/borg-backups/backup.borg/index.121
TAM-verified manifest
security: read previous location '/mnt/backup/borg-backups/backup.borg'
security: read manifest timestamp '2019-05-19T13:23:51.720826'
security: determined newest manifest timestamp as 2019-05-19T13:23:51.720826
security: repository checks ok, allowing access
Creating archive at "/mnt/backup/borg-backups/backup.borg::2019-05-26-balazs-laptop-3359-home"
Verified integrity of /home/balazs/.cache/borg/3dbc180c8fea5f886af08f6bc7655563efde62d60f04a0ef76a1dad3ce0a2d53/chunks
Reading files cache ...
Verified integrity of /home/balazs/.cache/borg/3dbc180c8fea5f886af08f6bc7655563efde62d60f04a0ef76a1dad3ce0a2d53/files
security: read previous location '/mnt/backup/borg-backups/backup.borg'
security: read manifest timestamp '2019-05-19T13:23:51.720826'
security: determined newest manifest timestamp as 2019-05-19T13:23:51.720826
security: repository checks ok, allowing access
Processing files ...
Cleaned up 32 uncommitted segment files (== everything after segment 121).                                                                                                                          
Verified integrity of /mnt/backup/borg-backups/backup.borg/hints.121
^CKeyboard interruptC 12.32 GB D 193227 N mnt/home_snapshot/balazs/...on-website/_sass/labels.scssTraceback (most recent call last):s/sphinx/setup_command.py                                       
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4455, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4387, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 154, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 557, in do_create
    create_inner(archive, cache)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 520, in create_inner
    read_special=args.read_special, dry_run=dry_run, st=st)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 634, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 634, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 634, in _process
    read_special=read_special, dry_run=dry_run)
  [Previous line repeated 1 more time]
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 655, in _process
    status = archive.process_file(path, st, cache)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 1032, in process_file
    fh = Archive._open_rb(path)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 1058, in _open_rb
    return os.open(path, flags_noatime)
  File "/usr/lib/python3/dist-packages/borg/helpers.py", line 2245, in handler
    raise exc_cls
KeyboardInterrupt

Platform: Linux balazs-laptop 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64
Linux: Ubuntu 18.04 bionic
Borg: 1.1.9  Python: CPython 3.6.7
PID: 7430  CWD: /home/balazs
sys.argv: ['/usr/bin/borg', 'create', '--verbose', '--progress', '--debug', '--show-rc', '--stats', '--one-file-system', '--read-special', '--compression', 'lz4', '--checkpoint-interval', '86400', '--exclude', '/mnt/home_snapshot/balazs/Library', '--exclude', '/mnt/home_snapshot/balazs/Studies', '--exclude', '/mnt/home_snapshot/balazs/Pictures', '--exclude', '/mnt/home_snapshot/balazs/Documents', '--exclude', '/mnt/home_snapshot/balazs/Downloads', '--exclude', '/mnt/home_snapshot/balazs/Dropbox', '--exclude', '/mnt/home_snapshot/balazs/.cache', '/mnt/backup/borg-backups/backup.borg::2019-05-26-balazs-laptop-3359-home', '/mnt/home_snapshot/']
SSH_ORIGINAL_COMMAND: None

terminating with error status, rc 2
```

strace:
```
...
stat("/usr/lib/python3/dist-packages/borg/helpers.py", {st_mode=S_IFREG|0644, st_size=87877, ...}) = 0
openat(AT_FDCWD, "/usr/lib/python3/dist-packages/borg/helpers.py", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=87877, ...}) = 0
ioctl(3, TCGETS, 0x7ffe2a995610)        = -1 ENOTTY (Inappropriate ioctl for device)
lseek(3, 0, SEEK_CUR)                   = 0
read(3, "import argparse\nimport contextli"..., 4096) = 4096
lseek(3, 0, SEEK_CUR)                   = 4096
read(3, "BUFSIZE, MAX_OBJECT_SIZE),\n     "..., 8192) = 8192
read(3, " m.get('item_keys', []))\n\n      "..., 8192) = 8192
read(3, " no microsecs support.\n        f"..., 8192) = 8192
read(3, "on = isoformat\n\n\ndef format_file"..., 8192) = 8192
read(3, " re.compile(r\"\"\"\n        (\n     "..., 8192) = 8192
mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7feeebb27000
read(3, "    os.dup2(fd, 0)\n    os.dup2(f"..., 8192) = 8192
read(3, "SET with a logging config file,\n"..., 8192) = 8192
read(3, "ostname of host on which this ar"..., 8192) = 8192
read(3, "(source)\n            if item_typ"..., 8192) = 8192
read(3, "candir_keyfunc)\n\n\ndef clean_line"..., 8192) = 8192
read(3, ".\n        # thus we install the "..., 8192) = 1861
read(3, "", 8192)                       = 0
close(3)                                = 0
uname({sysname="Linux", nodename="balazs-laptop", ...}) = 0
openat(AT_FDCWD, "/etc/lsb-release", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=105, ...}) = 0
ioctl(3, TCGETS, 0x7ffe2a996be0)        = -1 ENOTTY (Inappropriate ioctl for device)
lseek(3, 0, SEEK_CUR)                   = 0
ioctl(3, TCGETS, 0x7ffe2a996bc0)        = -1 ENOTTY (Inappropriate ioctl for device)
lseek(3, 0, SEEK_CUR)                   = 0
read(3, "DISTRIB_ID=Ubuntu\nDISTRIB_RELEAS"..., 8192) = 105
read(3, "", 8192)                       = 0
close(3)                                = 0
getpid()                                = 7430
getcwd("/home/balazs", 1024)            = 13
munmap(0x7feeeb731000, 262144)          = 0
munmap(0x7feeeb6f1000, 262144)          = 0
munmap(0x7feeeb671000, 262144)          = 0
...
```

**Comment by infectormp** [comment]
I see only stack trace caused by `Keyboard interrupt` in your logs. 
Btw version 1.1.10 is released.

**Comment by ThomasWaldmann** [comment]
@balazsdukai the traceback shows that you interrupted the borg client when it was just opening some file - that doesn't look like "hanging".

**Comment by ThomasWaldmann** [comment]
@balazsdukai i just have noticed that you give `--read-special` - that will open and read the contents of any device file, fifo, etc. it will encounter. as you are saving a mounted snapshot (== doing a normal file backup), i guess this is not what you want.

**Comment by balazsdukai** [comment]
Indeed, the problem was that tried to backup a mounted snapshot with `borg create --read-special`. Backing up the snapshot without mounting works as expected.

I clearly don't understand enough about filesystems/LV and got confused by various examples that I found online for backing up LV snapshots.

Thanks for your help!
