### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 

### ISSUE THREAD

**Issue by chrissound** [borgbackup/borg#4610]
Probably not passing the correct command but it'd be nice not to run into an exception.

```
sudo borg list ~/mount/raid18t
beepboop:1: permission denied: .directory_history
Exception ignored in: <function Repository.__del__ at 0x7fc238d1f048>
Traceback (most recent call last):
  File "/nix/store/49cky7mfi9b6hx0yfrfx2bsmy6f8wil8-borgbackup-1.1.9/lib/python3.7/site-packages/borg/repository.py", line 179, in __del__
    assert False, "cleanup happened in Repository.__del__"
AssertionError: cleanup happened in Repository.__del__
Local Exception
Traceback (most recent call last):
  File "/nix/store/49cky7mfi9b6hx0yfrfx2bsmy6f8wil8-borgbackup-1.1.9/lib/python3.7/site-packages/borg/archiver.py", line 4455, in main
    exit_code = archiver.run(args)
  File "/nix/store/49cky7mfi9b6hx0yfrfx2bsmy6f8wil8-borgbackup-1.1.9/lib/python3.7/site-packages/borg/archiver.py", line 4387, in run
    return set_ec(func(args))
  File "/nix/store/49cky7mfi9b6hx0yfrfx2bsmy6f8wil8-borgbackup-1.1.9/lib/python3.7/site-packages/borg/archiver.py", line 139, in wrapper
    with repository:
  File "/nix/store/49cky7mfi9b6hx0yfrfx2bsmy6f8wil8-borgbackup-1.1.9/lib/python3.7/site-packages/borg/repository.py", line 189, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/nix/store/49cky7mfi9b6hx0yfrfx2bsmy6f8wil8-borgbackup-1.1.9/lib/python3.7/site-packages/borg/repository.py", line 396, in open
    with open(os.path.join(self.path, 'config')) as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/home/chris/mount/raid18t/config'

Platform: Linux nixos 5.1.7 #1-NixOS SMP Tue Jun 4 05:59:45 UTC 2019 x86_64
Linux:   
Borg: 1.1.9  Python: CPython 3.7.3
PID: 14874  CWD: /home/chris/mount/raidBackup
sys.argv: ['/nix/store/49cky7mfi9b6hx0yfrfx2bsmy6f8wil8-borgbackup-1.1.9/bin/borg', 'list', '/home/chris/mount/raid18t']
SSH_ORIGINAL_COMMAND: None
```

```
borg --version
borg 1.1.9
```

**Comment by ThomasWaldmann** [comment]
Can you reproduce with 1.1.10? See #4411.

**Comment by ThomasWaldmann** [comment]
No reply...
