### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: borgrepo/data/4/4234

### ISSUE THREAD

**Issue by jrichterpowell** [borgbackup/borg#4626]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

## System information. For client/server mode post info for both machines.
```
Platform: Linux HOSTNAME 4.19.49-1-MANJARO #1 SMP PREEMPT Sun Jun 9 20:24:20 UTC 2019 x86_64
Linux: arch Manjaro Linux
Borg: 1.1.10  Python: CPython 3.7.3 msgpack: 0.5.6
PID: 12103  CWD: /home/USER
sys.argv: ['/usr/bin/borg', 'check', '/mnt/backupnas/borgrepo/']
SSH_ORIGINAL_COMMAND: None

USER@HOSTNAME
------------------ 
OS: Manjaro Linux x86_64 
Host: All Series 
Kernel: 4.19.49-1-MANJARO 
Uptime: 2 days, 3 hours, 38 mins 
Packages: 1100 (pacman) 
Shell: bash 5.0.7 
Terminal: /dev/pts/1 
CPU: Intel i7-4770K (8) @ 3.900GHz 
GPU: NVIDIA GeForce RTX 2060 Rev. A 
GPU: NVIDIA GeForce GTX 760 
Memory: 6579MiB / 32105MiB 
```

#### Your borg version (borg -V).
1.1.10
#### Hardware / network configuration, and filesystems used.
PC as above, borg repo is on a NAS device mounted as cifs via samba.
#### How much data is handled by borg?
~ 5tb
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```
(base) [USER@HOSTNAME ~]$ sudo borg check /mnt/backupnas/borgrepo/
Exception ignored in: <function Repository.__del__ at 0x7f4c0a690a60>
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/borg/repository.py", line 179, in __del__
    assert False, "cleanup happened in Repository.__del__"
AssertionError: cleanup happened in Repository.__del__
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/borg/repository.py", line 1317, in get_fd
    ts, fd = self.fds[segment]
  File "/usr/lib/python3.7/site-packages/borg/lrucache.py", line 21, in __getitem__
    value = self._cache[key]  # raise KeyError if not found
KeyError: 4234

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4501, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4433, in run
    return set_ec(func(args))
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 151, in wrapper
    with repository:
  File "/usr/lib/python3.7/site-packages/borg/repository.py", line 189, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/usr/lib/python3.7/site-packages/borg/repository.py", line 418, in open
    if segment is not None and self.io.get_segment_magic(segment) == ATTIC_MAGIC:
  File "/usr/lib/python3.7/site-packages/borg/repository.py", line 1352, in get_segment_magic
    fd = self.get_fd(segment)
  File "/usr/lib/python3.7/site-packages/borg/repository.py", line 1319, in get_fd
    fd = open_fd()
  File "/usr/lib/python3.7/site-packages/borg/repository.py", line 1300, in open_fd
    fd = open(self.segment_filename(segment), 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/backupnas/borgrepo/data/4/4234'

Platform: Linux HOSTNAME 4.19.49-1-MANJARO #1 SMP PREEMPT Sun Jun 9 20:24:20 UTC 2019 x86_64
Linux: arch Manjaro Linux
Borg: 1.1.10  Python: CPython 3.7.3 msgpack: 0.5.6
PID: 12144  CWD: /home/USER
sys.argv: ['/usr/bin/borg', 'check', '/mnt/backupnas/borgrepo/']
SSH_ORIGINAL_COMMAND: None
```
## Describe the problem you're observing.
Running any borg command seems to result in the above error. The file in question, however, exists. 

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
The backup source is too large to try to reproduce this. I've tried breaking the lock on the repo and checking it with `borg check` but both result in the same. I interrupted a backup which may have caused this, but according to the docs should be fine.

**Comment by jrichterpowell** [comment]
Seems to have been an issue with hanging borg processes. Using SIGKILL (SIGTERM did not actually kill them) on them seems to resolve this. Sorry for cluttering the issue tracker.

**Comment by ThomasWaldmann** [comment]
Well, `[Errno 2] No such file or directory: '/mnt/backupnas/borgrepo/data/4/4234'` is rather clear.

It tried to open a file and it was not there.

Check if the file is there, check if the filesystem is actually mounted at `/mnt/backupnas` and works.

Also, a `borg check` seems a good idea - it could be that you've somehow lost a segment file in the repository.
