### ISSUE TITLE
[Errno 13] Permission denied for CIFS mounted volume

### ISSUE THREAD

**Issue by papanito** [borgbackup/borg#4839]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes.

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).

`borg 1.1.10`

#### Operating system (distribution) and version.

`5.3.11-1-MANJARO`

#### How much data is handled by borg?

N/A

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

`borg init --encryption=repokey /mnt/mysmbdevice/backup` 

## Describe the problem you're observing.

I want to do a backup on a mounted smb volume:
```
//192.168.1.1/Elements /mnt/sunrise cifs file_mode=0777,dir_mode=0777,rw,uid=1000,gid=1000,sec=none,vers=1.0,nounix 0 0
```
 I was facing issue #4086, so I added `nounix` mount option to `fstab` as mentioned in one of the comments. Now I get the following error

```bash
PermissionError: [Errno 13] Permission denied: '/mnt/mysmbdevice/backup/config' -> '/mnt/mysmbdevice/backup/config.old'
```
Me as a user I however can create and delete folders. Also `borg` does create initial file and structure:
```bash
ls -l /mnt/mysmbdevice/backup
total 2.0M
-rwxrwxrwx 1 me me 209 17. Nov 16:51 config*
drwxrwxrwx 2 me me   0 17. Nov 16:51 data/
-rwxrwxrwx 1 me me  73 17. Nov 16:51 README*
```

#### Include any warning/errors/backtraces from the system logs

```bash
borg init --encryption=repokey /mnt/mysmbdevice/backup`
Enter new passphrase: 
Enter same passphrase again: 
Do you want your passphrase to be displayed for verification? [yN]: 
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4501, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4433, in run
    return set_ec(func(args))
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 166, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 280, in do_init
    key = key_creator(repository, args)
  File "/usr/lib/python3.7/site-packages/borg/crypto/key.py", line 110, in key_creator
    return key.create(repository, args)
  File "/usr/lib/python3.7/site-packages/borg/crypto/key.py", line 690, in create
    key.save(target, passphrase)
  File "/usr/lib/python3.7/site-packages/borg/crypto/key.py", line 800, in save
    target.save_key(key_data)
  File "/usr/lib/python3.7/site-packages/borg/repository.py", line 310, in save_key
    self.save_config(self.path, self.config)
  File "/usr/lib/python3.7/site-packages/borg/repository.py", line 292, in save_config
    os.link(config_path, old_config_path)
PermissionError: [Errno 13] Permission denied: '/mnt/mysmbdevice/backup/config' -> '/mnt/mysmbdevice/backup/config.old'

Platform: Linux hostname 5.3.11-1-MANJARO #1 SMP PREEMPT Wed Nov 13 12:21:14 UTC 2019 x86_64
Linux: arch Manjaro Linux
Borg: 1.1.10  Python: CPython 3.7.4 msgpack: 0.5.6
PID: 4124  CWD: /mnt/mysmbdevice/
sys.argv: ['/usr/bin/borg', 'init', '--encryption=repokey', '/mnt/mysmbdevice/backup']
SSH_ORIGINAL_COMMAND: None
```

**Comment by papanito** [comment]
May be duplicate of #4730

**Comment by ThomasWaldmann** [comment]
Guess so. Closing this as duplicate.
