### ISSUE TITLE
Backup and prune fails, object with key not found

### ISSUE THREAD

**Issue by w-Oeps** [borgbackup/borg#4863]
_Sorry, long post!_
## Have you checked borgbackup docs, FAQ, and open Github issues?
Yes

## Is this a BUG / ISSUE report or a QUESTION?
Bug/Issue

## System information. For client/server mode post info for both machines.
Ubuntu server at home, Cloud TransIP stackstorage connected using mount using webdav

#### Your borg version (borg -V).
borg 1.1.10

#### Operating system (distribution) and version.
Ubuntu 18.04.3 LTS (Desktop version used as server)
#### Hardware / network configuration, and filesystems used.
Intel DH77EB motherboard, 128GB OS disk, 4x4TB data disks, Wired network, Internet 250Mbit/s down, 25Mbit/s up

#### How much data is handled by borg?
Space in use on the Cloud drive about 1TB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
`borg create   --verbose --filter AME --list --stats --show-rc --compression lz4 --exclude-caches --exclude '/home/*/.cache/*'  --exclude '/var/cache/*'   --exclude '/var/tmp/*' $REPOSITORY::'foto-{now:%Y-%m-%d_%H:%M}'  /media/data/fileserver/foto`

## Describe the problem you're observing.
The backup ends with an error rc 2 with backtrace info below. There is one incomplete backup with a checkpoint suffix which _seems_ to break things. I tried to delete the backup with checkpoint suffix with the prune but this fails too. See backtrace info below.

With borg list I get this:
```
home-2019-05-16_20:30                Thu, 2019-05-16 20:31:27 [long key made short here]
foto-2019-05-26_07:05                Sun, 2019-05-26 07:05:46 [long key made short here]
home-2019-05-26_07:14                Sun, 2019-05-26 07:14:42 [long key made short here]
home-2019-06-02_07:14                Sun, 2019-06-02 07:14:06 [long key made short here]
foto-2019-06-09_07:05                Sun, 2019-06-09 07:05:17 [long key made short here]
home-2019-06-09_07:06                Sun, 2019-06-09 07:06:07 [long key made short here]
foto-2019-06-16_07:05                Sun, 2019-06-16 07:05:24 [long key made short here]
home-2019-06-16_07:13                Sun, 2019-06-16 07:13:51 [long key made short here]
foto-2019-07-21_01:00.checkpoint     Sun, 2019-07-21 01:01:05 [long key made short here]
```
#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yes, Every backup made fails since July (made a temp backup to another cloud drive, found just now time time troubleshoot).

- Backup fails
- Tried a arbritrary prune with dry-run, fails too: `borg prune --dry-run --list --keep-last 3 /media/stack/BorgBackupsHomeD`

Some questions:
- Is there a way to delete a "checkpoint" backup manually?
- Is there a way stop borg looking for an ID which does not exist (and hopefully have a working backup again).
- Is it worth to troubleshoot this problem?, does it help borg community? Otherwise I can delete this backup set and start over and save the community some time :-)

Thanks!!

The 'checkpoint' backup was created 2019-07-21_01:00, I included the log of that backup at the end of this post, seems a network failure occurred.

#### Include any warning/errors/backtraces from the system logs

ERROR in log file when performing **backup** with above command line. The key mentioned in the error is indeed not shown in the list above (where I deleted the keys for readability).
```

Creating archive at "/media/stack/BorgBackupsHomeD::foto-{now:%Y-%m-%d_%H:%M}"
Synchronizing chunks cache...
Archives: 9, w/ cached Idx: 3, w/ outdated Idx: 0, w/o cached Idx: 6.
Reading cached archive chunk index for foto-2019-05-26_07:05 ...
Merging into master chunks index ...
Reading cached archive chunk index for foto-2019-06-09_07:05 ...
Merging into master chunks index ...
Reading cached archive chunk index for foto-2019-06-16_07:05 ...
Merging into master chunks index ...
Fetching and building archive index for foto-2019-07-21_01:00.checkpoint ...
Object with key b897548c4ffc69f0e1230045c2d9e0af934444af0ea1c4ab1731b00681d66952 not found in repository /media/stack/BorgBackupsHomeD.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4501, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4433, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 166, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 566, in do_create
    cache_mode=args.files_cache_mode, ignore_inode=args.ignore_inode) as cache:
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 379, in __new__
    return local()
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 373, in local
    lock_wait=lock_wait, cache_mode=cache_mode)
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 466, in __init__
    self.sync()
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 850, in sync
    self.chunks = create_master_idx(self.chunks)
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 804, in create_master_idx
    fetch_and_build_idx(archive_id, decrypted_repository, archive_chunk_idx)
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 709, in fetch_and_build_idx
    for item_id, (csize, data) in zip(archive.items, decrypted_repository.get_many(archive.items)):
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 1083, in get_many
    for key, data in zip(keys, self.repository.get_many(keys)):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1079, in get_many
    yield self.get(id_)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1075, in get
    raise self.ObjectNotFound(id, self.path) from None
borg.repository.Repository.ObjectNotFound: Object with key b897548c4ffc69f0e1230045c2d9e0af934444af0ea1c4ab1731b00681d66952 not found in repository /media/stack/BorgBackupsHomeD.

Platform: Linux server 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64
Linux: Ubuntu 18.04 bionic
Borg: 1.1.10  Python: CPython 3.6.9 msgpack: 0.5.6
PID: 19175  CWD: /home/me
sys.argv: ['/usr/bin/borg', 'create', '--verbose', '--filter', 'AME', '--list', '--stats', '--show-rc', '--compression', 'lz4', '--exclude-caches', '--exclude', '/home/*/.cache/*', '--exclude', '/var/cache/*', '--exclude', '/var/tmp/*', '/media/stack/BorgBackupsHomeD::foto-{now:%Y-%m-%d_%H:%M}', '/media/data/fileserver/foto']
SSH_ORIGINAL_COMMAND: None

terminating with error status, rc 2
```
=====================
Error of **prune** command shown above:
```
Object with key b897548c4ffc69f0e1230045c2d9e0af934444af0ea1c4ab1731b00681d66952 not found in repository /media/stack/BorgBackupsHomeD.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4501, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4433, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 166, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1591, in do_prune
    with Cache(repository, key, manifest, lock_wait=self.lock_wait) as cache:
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 379, in __new__
    return local()
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 373, in local
    lock_wait=lock_wait, cache_mode=cache_mode)
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 466, in __init__
    self.sync()
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 850, in sync
    self.chunks = create_master_idx(self.chunks)
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 804, in create_master_idx
    fetch_and_build_idx(archive_id, decrypted_repository, archive_chunk_idx)
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 709, in fetch_and_build_idx
    for item_id, (csize, data) in zip(archive.items, decrypted_repository.get_many(archive.items)):
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 1083, in get_many
    for key, data in zip(keys, self.repository.get_many(keys)):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1079, in get_many
    yield self.get(id_)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1075, in get
    raise self.ObjectNotFound(id, self.path) from None
borg.repository.Repository.ObjectNotFound: Object with key b897548c4ffc69f0e1230045c2d9e0af934444af0ea1c4ab1731b00681d66952 not found in repository /media/stack/BorgBackupsHomeD.

Platform: Linux server 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64
Linux: Ubuntu 18.04 bionic
Borg: 1.1.10  Python: CPython 3.6.9 msgpack: 0.5.6
PID: 30161  CWD: /home/me/scripts/Borg
sys.argv: ['/usr/bin/borg', 'prune', '--dry-run', '--list', '--keep-last', '3', '/media/stack/BorgBackupsHomeD']
SSH_ORIGINAL_COMMAND: None
```
Part of the log file of 2019-07-21_01:00 when the checkpoint was created:
```
A /media/data/fileserver/foto/Raw Pictures/2019/20190610/DSC03549.ARW
A /media/data/fileserver/foto/Raw Pictures/2019/20190610/DSC03541.ARW
Exception ignored in: <bound method Repository.__del__ of <Repository /media/stack/BorgBackupsHomeD>>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 178, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 425, in close
    self.io.close()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1177, in close
    self.fds.clear()
  File "/usr/lib/python3/dist-packages/borg/lrucache.py", line 44, in clear
    self._dispose(value)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1182, in close_fd
    fd.close()
OSError: [Errno 107] Transport endpoint is not connected
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 154, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 557, in do_create
    create_inner(archive, cache)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 520, in create_inner
    read_special=args.read_special, dry_run=dry_run, st=st)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 634, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 634, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 634, in _process
    read_special=read_special, dry_run=dry_run)
  [Previous line repeated 1 more time]
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 608, in _process
    status = archive.process_file(path, st, cache)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 1034, in process_file
    self.chunk_file(item, cache, self.stats, backup_io_iter(self.chunker.chunkify(fd, fh)))
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 962, in chunk_file
    item.chunks.append(chunk_processor(data))
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 950, in chunk_processor
    chunk_entry = cache.add_chunk(self.key.id_hash(data), data, stats, wait=False)
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 899, in add_chunk
    self.repository.put(id, data, wait=wait)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1101, in put
    segment, offset = self.io.write_put(id, data)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1482, in write_put
    fd.write(b''.join((crc, header, id, data)))
  File "src/borg/platform/linux.pyx", line 279, in borg.platform.linux.SyncFile.write
OSError: [Errno 107] Transport endpoint is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/platform/base.py", line 136, in close
    self.sync()
  File "src/borg/platform/linux.pyx", line 292, in borg.platform.linux.SyncFile.sync
OSError: [Errno 107] Transport endpoint is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4455, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4387, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 154, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 203, in __exit__
    self.close()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 425, in close
    self.io.close()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1176, in close
    self.close_segment()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1307, in close_segment
    fd.close()
  File "/usr/lib/python3/dist-packages/borg/platform/base.py", line 138, in close
    self.fd.close()
OSError: [Errno 107] Transport endpoint is not connected

Platform: Linux server 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64
Linux: Ubuntu 18.04 bionic
Borg: 1.1.9  Python: CPython 3.6.8
PID: 13504  CWD: /home/me
sys.argv: ['/usr/bin/borg', 'create', '--verbose', '--filter', 'AME', '--list', '--stats', '--show-rc', '--compression', 'lz4', '--exclude-caches', '--exclude', '/home/*/.cache/*', '--exclude', '/var/cache/*', '--exclude', '/var/tmp/*', '/media/stack/BorgBackupsHomeD::foto-{now:%Y-%m-%d_%H:%M}', '/media/data/fileserver/foto']
SSH_ORIGINAL_COMMAND: None

terminating with error status, rc 2
```

**Comment by infectormp** [comment]
https://borgbackup.readthedocs.io/en/stable/faq.html?highlight=checkpoint#if-a-backup-stops-mid-way-does-the-already-backed-up-data-stay-there
> If a backup was interrupted, you normally do not need to do anything special, just invoke borg create as you always do. If the repository is still locked, you may need to run borg break-lock before the next backup. You may use the same archive name as in previous attempt or a different one (e.g. if you always include the current datetime), it does not matter.

**Comment by ThomasWaldmann** [comment]
The .checkpoint archive is not your problem.

Your problem likely is one of these:
- the remote filesystem (webdav fs) you use for repo storage is not working good enough
- the remote underlying fs or storage device is not working good enough
- you have a corruption issue so the contents of the repository index (which chunks do we have in the repo?) and the real repo contents are not consistent. this can be caused e.g. if some of your hardware, usually RAM, is malfunctioning.

Additionally, but this is usually no problem, you may have connection issues: if the fuse filesystem says "transport endpoint not connected", it is maybe simply the connection to the remote side which broke away. Or the fuse fs had some issue and crashed. This is usually no big issue as borg will just rollback uncommitted stuff when you access the repo next time.

The repo index can be made consistent with the repo contents by running `borg check --repair`. But if there is a hw issue, better fix that **first** or it might get worse.

**Comment by w-Oeps** [comment]
@ThomasWaldmann; @infectormp 
Thanks for the replies!
Forgot to mention that I have a second borg backup set which is stored on the same webdav drive which runs fine. For me this rules out hw/network. My local backup using rdiff-backup with the same data runs fine, rules out more or less source data corruption.
There is no lock file within the backup set.
The Borg check `--repair failes` with an error too unfortunately.

I can mount the older backupsets and tried a test restore. no problem. Just can't add new backups.

**Comment by ThomasWaldmann** [comment]
Your conclusions only work for high-probability faults, but not for rarer events.

I need the traceback for the `borg check --repair` failure, please.

**Comment by w-Oeps** [comment]
Tried --repair and then --repair --debug (output when I ran these commands in October)

check --repair output:
```
borg check --repair --info /media/stack/BorgBackupsHomeD --last 1
'check --repair' is an experimental feature that might result in data loss.
Type 'YES' if you understand this and want to continue: YES
Starting repository check
Exception ignored in: <bound method Repository.__del__ of <Repository /media/stack/BorgBackupsHomeD>>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 179, in __del__
    assert False, "cleanup happened in Repository.__del__"
AssertionError: cleanup happened in Repository.__del__
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1317, in get_fd
    ts, fd = self.fds[segment]
  File "/usr/lib/python3/dist-packages/borg/lrucache.py", line 21, in __getitem__
    value = self._cache[key]  # raise KeyError if not found
KeyError: 3266

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 166, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 327, in do_check
    if not repository.check(repair=args.repair, save_space=args.save_space):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 923, in check
    objects = list(self.io.iter_objects(segment))
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1365, in iter_objects
    fd = self.get_fd(segment)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1319, in get_fd
    fd = open_fd()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1300, in open_fd
    fd = open(self.segment_filename(segment), 'rb')
OSError: [Errno 5] Input/output error: '/media/stack/BorgBackupsHomeD/data/3/3266'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4501, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4433, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 166, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 203, in __exit__
    self.close()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 427, in close
    self.lock.release()
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 383, in release
    self._roster.modify(EXCLUSIVE, REMOVE)
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 274, in modify
    roster = self.load()
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 233, in load
    with open(self.path) as f:
OSError: [Errno 5] Input/output error: '/media/stack/BorgBackupsHomeD/lock.roster'

Platform: Linux server 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64
Linux: Ubuntu 18.04 bionic
Borg: 1.1.10  Python: CPython 3.6.8 msgpack: 0.5.6
PID: 11737  CWD: /home/me/scripts/Borg
sys.argv: ['/usr/bin/borg', 'check', '--repair', '--info', '/media/stack/BorgBackupsHomeD', '--last', '1']
SSH_ORIGINAL_COMMAND: None
```

check --repair --debug output 
```
borg check --repair  --debug /media/stack/BorgBackupsHomeD --last 1
using builtin fallback logging configuration
35 self tests completed in 0.13 seconds
'check --repair' is an experimental feature that might result in data loss.
Type 'YES' if you understand this and want to continue: YES
Starting repository check
Verified integrity of /media/stack/BorgBackupsHomeD/index.4409
Read committed index of transaction 4409
Cleaned up 0 uncommitted segment files (== everything after segment 4409).
Segment transaction is    4409
Determined transaction is 4409
Found 3187 segments
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1317, in get_fd
    ts, fd = self.fds[segment]
  File "/usr/lib/python3/dist-packages/borg/lrucache.py", line 21, in __getitem__
    value = self._cache[key]  # raise KeyError if not found
KeyError: 3041

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4501, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4433, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 166, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 327, in do_check
    if not repository.check(repair=args.repair, save_space=args.save_space):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 923, in check
    objects = list(self.io.iter_objects(segment))
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1365, in iter_objects
    fd = self.get_fd(segment)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1319, in get_fd
    fd = open_fd()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1300, in open_fd
    fd = open(self.segment_filename(segment), 'rb')
OSError: [Errno 5] Input/output error: '/media/stack/BorgBackupsHomeD/data/3/3041'

Platform: Linux server 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64
Linux: Ubuntu 18.04 bionic
Borg: 1.1.10  Python: CPython 3.6.8 msgpack: 0.5.6
PID: 20302  CWD: /home/me/scripts/Borg
sys.argv: ['/usr/bin/borg', 'check', '--repair', '--debug', '/media/stack/BorgBackupsHomeD', '--last', '1']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment]
Input/Output error is an issue below borg (fs or storage device).

**Comment by w-Oeps** [comment]
Hi Thomas, thanks!
I wil just throw away the backup set and start over.
