### ISSUE TITLE
borg delete repo::archive nonexistingarchive

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#4868]
```
# borg delete -v --show-rc --progress --stats ::20191112L213957_WRONG_PATH .
Deleting archive: 20191112L213957_WRONG_PATH           Wed, 2019-11-13 00:54:45 [988119b298e628e9f00ee45298f8dc70fc1cdc56be0987b268393c3adedcda8e] (1/2)
Decrementing references  30%

Local Exception
Traceback (most recent call last):
  File "borg/archiver.py", line 4501, in main
  File "borg/archiver.py", line 4433, in run
  File "borg/archiver.py", line 166, in wrapper
  File "borg/archiver.py", line 1257, in do_delete
  File "borg/archiver.py", line 1304, in _delete_archives
  File "borg/helpers.py", line 244, in __getitem__
KeyError

Platform: Darwin REDACTED 17.7.0 Darwin Kernel Version 17.7.0: Fri Jul  6 19:54:51 PDT 2018; root:xnu-4570.71.3~2/RELEASE_X86_64 x86_64
Borg: 1.1.10  Python: CPython 3.5.7 msgpack: 0.5.6
PID: 92649  CWD: /REDACTED/00CLONE2BORG
sys.argv: ['borg', 'delete', '-v', '--show-rc', '--progress', '--stats', '::20191112L213957_WRONG_PATH', '.']
SSH_ORIGINAL_COMMAND: None

terminating with error status, rc 2
```

This is due to the (unintended) `.` at the end, which is interpreted as another archive name to delete. Then borg does not find that archive in the archives list and throws a KeyError.

It should just say "archive . does not exist" or so.

We recently fixed another similar issue.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/pull/4818/files hmm, seems like this is fixed already.
