### ISSUE TITLE
ImportError: dlopen failed: cannot locate symbol "PyBaseObject_Type" referenced by "/data/.../low_level.cpython-38-x86_64-linux-gnu.so"

### ISSUE THREAD

**Issue by amaramrahul** [borgbackup/borg#4872]
I am trying to run [borg in termux](https://github.com/amaramrahul/termux-packages). I was able to successfully build and run borg 1.1.10 when termux was using python3.7. However, with termux upgrading to python 3.8, I am facing the below issue after recompiling and running borg.
```
$ borg
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/borgbackup-1.1.10-py3.8-linux-x86_64.egg/borg/archiver.py", line 38, in <module>
    from . import helpers
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/borgbackup-1.1.10-py3.8-linux-x86_64.egg/borg/helpers.py", line 75, in <module>
    import borg.crypto.low_level
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/borgbackup-1.1.10-py3.8-linux-x86_64.egg/borg/crypto/low_level.py", line 7, in <module>
    __bootstrap__()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/borgbackup-1.1.10-py3.8-linux-x86_64.egg/borg/crypto/low_level.py", line 6, in __bootstrap__
    imp.load_dynamic(__name__,__file__)
  File "/data/data/com.termux/files/usr/lib/python3.8/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen failed: cannot locate symbol "PyBaseObject_Type" referenced by "/data/data/com.termux/files/usr/lib/python3.8/site-packages/borgbackup-1.1.10-py3.8-linux-x86_64.egg/borg/crypto/low_level.cpython-38-x86_64-linux-gnu.so"...
```
Just curious if there are known compatibility issues of borg 1.1.10 with python 3.8 or if I could be given any pointers on what could be the potential issue.

**Comment by ThomasWaldmann** [comment]
Did you try just reinstalling borg with py38?

**Comment by amaramrahul** [comment]
This issue is resolved. I pointed to the termux libraries and include files while building borgback. Will mostly be rasing a PR to include borgbackup in termux upstream.
