### ISSUE TITLE
Borg init from ssh : permissionError 

### ISSUE THREAD

**Issue by Fr3d-P** [borgbackup/borg#4898]
borg 1.1.9 for raspbian (raspberry pi)

I have two pi, each one with the same version of Borg.

One of them is connected to a drive, so I launched it's backup, it worked.
I can ssh from one pi to the other without problem.

I wanted to backup the second one via ssh, and even `init` doesn't work.

I did
```
sudo borg init --encryption=none ssh://pi@192.168.1.21/media/piRaidDrive/Borg/octoPi
```
it asked me the password, then I got this messages
```
root Remote: PermissionError Exception in RPC call
root Remote: Traceback (most recent call last):
Remote:   File "/usr/lib/python3/dist-packages/borg/remote.py", line 248, in serve
Remote:     res = f(**args)
Remote:   File "/usr/lib/python3/dist-packages/borg/remote.py", line 376, in open
Remote:     self.repository.__enter__()  # clean exit handled by serve() method
Remote:   File "/usr/lib/python3/dist-packages/borg/repository.py", line 187, in __enter__
Remote:     self.create(self.path)
Remote:   File "/usr/lib/python3/dist-packages/borg/repository.py", line 262, in create
Remote:     os.mkdir(path)
Remote: PermissionError: [Errno 13] Permission denied: '/media/piRaidDrive/Borg/octoPi'
Remote: 
Remote: Platform: Linux piCloud 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l
Remote: Linux: debian 10.2 
Remote: Borg: 1.1.9  Python: CPython 3.7.3
Remote: PID: 1196  CWD: /home/pi
Remote: sys.argv: ['/usr/bin/borg', 'serve', '--umask=077']
Remote: SSH_ORIGINAL_COMMAND: None
Remote: 
('Remote Exception (see remote log for the traceback)', 'PermissionError')
Platform: Linux octopi 4.19.66+ #1253 Thu Aug 15 11:37:30 BST 2019 armv6l 
Linux: debian 9.11 
Borg: 1.0.9  Python: CPython 3.5.3
PID: 751  CWD: /home/pi
sys.argv: ['/usr/bin/borg', 'init', '--encryption=none', 'ssh://pi@192.168.1.21/media/piRaidDrive/Borg/octoPi']
SSH_ORIGINAL_COMMAND: None
```
I understand it claims a permission problem, but I can't see what to do.

I think the problem is: the user can't create borg's commands locally without sudo'ing.

With ssh, I don' know if I can sudo (I tried sudo borg init, but it didn't change anything).

**Comment by ThomasWaldmann** [comment]
I'ld say the user `pi` does not have permissions to write to the filesystem at location `/media/piRaidDrive/Borg/octoPi`. Use `chmod` and `chown` to adjust fs permissions accordingly.

**Comment by Fr3d-P** [comment]
Hello,
Thanks for your answer and sorry for this noob's question. With the good owner it worked!
