### ISSUE TITLE
No decompressor for this data found

### ISSUE THREAD

**Issue by FreddieOliveira** [borgbackup/borg#4956]
Whichever command I run on my backup I get the following error message:

```
Local Exception.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 2181, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 2117, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 590, in do_mount
    return self._do_mount(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 101, in wrapper
    kwargs['manifest'], kwargs['key'] = Manifest.load(repository, compatibility)
  File "/usr/lib/python3/dist-packages/borg/helpers.py", line 259, in load
    data = key.decrypt(None, cdata)
  File "/usr/lib/python3/dist-packages/borg/key.py", line 282, in decrypt
    data = self.compressor.decompress(self.dec_cipher.decrypt(data[41:]))
  File "borg/compress.pyx", line 210, in borg.compress.Compressor.decompress (borg/compress.c:4825)
ValueError: ('No decompressor for this data found: %r.', b'\x03\x00')

Platform: Linux notebook 4.15.0-66-generic #75~16.04.1-Ubuntu SMP Tue Oct 1 14:01:08 UTC 2019 x86_64
Linux: Ubuntu 16.04 xenial
Borg: 1.0.12  Python: CPython 3.5.2
```

I suppose it has to do with the compression method I used when creating the backup, the problem is I can't remember which one I used, since it's been a long time. All I remember is that I created the backup on a different computer with Ubuntu 19.08

**Comment by ThomasWaldmann** [comment]
borg 1.0.12 is a rather old version, usually people use 1.1.x these days.

So likely you try to access a repo made with a much newer borg (and with zstd or lz4 compression) by a very old borg (which does not know these compressions).

Just use borg 1.1.10? It is available from the maintainers PPA:

https://launchpad.net/~costamagnagianfranco/+archive/ubuntu/borgbackup

**Comment by FreddieOliveira** [comment]
Thank you, that was exactly the problem! I created the backup with `zstd` which is unsupported by the version `1.0.12` I'm using now. Upgrading it with the PPA solved the issue.
