### ISSUE TITLE
borg init: Operation not permitted on sshfs remote storage

### ISSUE THREAD

**Issue by Fensterbank** [borgbackup/borg#4966]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes
## Is this a BUG / ISSUE report or a QUESTION?

BUG / ISSUE

#### Your borg version (borg -V).
Server: 1.1.5
Client: 1.1.10

#### Operating system (distribution) and version.
Server: Ubuntu 18.04.4 LTS
Client: Ubuntu 19.10

#### Hardware / network configuration, and filesystems used.
Server in home network (10.13.37.100) with ext4.
Mounting Strato HiDrive (cloud storage) with sshfs into /home/borg/repos.

The cloud storage does not support hard links:
```
$ ln test.tmp test
ln: failed to create hard link 'test' => 'test.tmp': Function not implemented
```

**/etc/fstab:**
```
sshfs#hidrive-username@sftp.hidrive.strato.com:/users/hidrive-username/borg/repos /home/borg/repos fuse uid=1001,gid=1001,allow_other,_netdev,ServerAliveInterval=45,ServerAliveCountMax=2,reconnect 0 0
```
![grafik](https://user-images.githubusercontent.com/1684826/75626846-4ad23400-5bcb-11ea-87c4-7567d6329100.png)

So the backups should be initialized and created from clients over ssh to the server in the home network and the server itself has a cloud storage mounted where the actual backup should be saved.

#### How much data is handled by borg?
None yet

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```
borg init -e repokey --debug borg@10.13.37.100:repos/T490-linux
```

## Describe the problem you're observing.

When I try to init a new repository from the client, I'll end up with an error message.
The repository is non-functional, so I cannot create backups ("Repository has no manifest.").

This issue maybe connected with https://github.com/borgbackup/borg/issues/3107, but I'm not sure.

```
$ borg init -e repokey --debug borg@10.13.37.100:repos/T490-linux
using builtin fallback logging configuration
35 self tests completed in 0.08 seconds
SSH command line: ['ssh', 'borg@10.13.37.100', 'borg', 'serve', '--umask=077', '--debug']
Remote: using builtin fallback logging configuration
Remote: 35 self tests completed in 0.07 seconds
Remote: using builtin fallback logging configuration
Remote: Initialized logging system for JSON-based protocol
Remote: Resolving repository path b'repos/T490-linux'
Remote: Resolved repository path to '/home/borg/repos/T490-linux'
Initializing repository at "ssh://borg@10.13.37.100/./repos/T490-linux"
Enter new passphrase: 
Enter same passphrase again: 
Do you want your passphrase to be displayed for verification? [yN]: 
Remember your passphrase. Your data will be inaccessible without it.
Remote: Failed to securely erase old repository config file (hardlinks not supported>). Old repokey data, if any, might persist on physical storage.
Remote: Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/borg/remote.py", line 248, in serve
    res = f(**args)

  File "/usr/lib/python3/dist-packages/borg/repository.py", line 299, in save_key
    self.save_config(self.path, self.config)

  File "/usr/lib/python3/dist-packages/borg/repository.py", line 290, in save_config
    config.write(fd)

  File "/usr/lib/python3/dist-packages/borg/platform/base.py", line 176, in __exit__
    os.replace(self.tmppath, self.path)

PermissionError: [Errno 1] Operation not permitted: '/home/borg/repos/T490-linux/config.tmp' -> '/home/borg/repos/T490-linux/config'

RemoteRepository: 663 B bytes sent, 3.05 kB bytes received, 4 messages sent
Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/borg/remote.py", line 248, in serve
    res = f(**args)

  File "/usr/lib/python3/dist-packages/borg/repository.py", line 299, in save_key
    self.save_config(self.path, self.config)

  File "/usr/lib/python3/dist-packages/borg/repository.py", line 290, in save_config
    config.write(fd)

  File "/usr/lib/python3/dist-packages/borg/platform/base.py", line 176, in __exit__
    os.replace(self.tmppath, self.path)

PermissionError: [Errno 1] Operation not permitted: '/home/borg/repos/T490-linux/config.tmp' -> '/home/borg/repos/T490-linux/config'

Borg server: Platform: Linux heimserver 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64
Borg server: Linux: Ubuntu 18.04 bionic
Borg server: Borg: 1.1.5  Python: CPython 3.6.9
Borg server: PID: 3756  CWD: /home/borg
Borg server: sys.argv: ['/usr/bin/borg', 'serve', '--umask=077', '--debug']
Borg server: SSH_ORIGINAL_COMMAND: None
Platform: Linux Codebox-Budgie 5.3.0-40-generic #32-Ubuntu SMP Fri Jan 31 20:24:34 UTC 2020 x86_64
Linux: Ubuntu 19.10 eoan
Borg: 1.1.10  Python: CPython 3.7.5 msgpack: 0.5.6
PID: 18221  CWD: /home/fred
sys.argv: ['/usr/bin/borg', 'init', '-e', 'repokey', '--debug', 'borg@10.13.37.100:repos/T490-linux']
SSH_ORIGINAL_COMMAND: None
```

I have no clue how to solve this problem or if Borg just not work with cloud storages like this.

**Comment by ThomasWaldmann** [comment]
It does not let you rename the `config.tmp` file to `config`.

Can you check the permissions of these files? Did you sometimes run as root and sometimes not?

**Comment by Fensterbank** [comment]
Great hint!
I thought it has something to do with hardlinks generation, but indeed in the sshfs filesystem I cannot rename any file with the `mv` command if it would result in an overwritten file.
```
borg@heimserver:~/repos$ touch test.txt test2.txt
borg@heimserver:~/repos$ mv test.txt test2.txt
mv: cannot move 'test.txt' to 'test2.txt': Operation not permitted
```
I will investigate that issue further, but it's definitely not a Borg issue, therefore I will close this issue.
Thank you!
