### ISSUE TITLE
pip is broken on ubuntu focal64

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5131]
master branch:
```
py38 installdeps: -rrequirements.d/development.txt, -rrequirements.d/fuse.txt                                                                                                                            [52/18353]
ERROR: invocation failed (exit code 1), logfile: /vagrant/borg/borg/.tox/py38/log/py38-1.log
==================================================================================================== log start ====================================================================================================Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main                                                                                          
    return _run_code(code, main_globals, None,         
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)                            
  File "/vagrant/borg/borg/.tox/py38/lib/python3.8/site-packages/pip/__main__.py", line 16, in <module>
    from pip._internal.cli.main import main as _main  # isort:skip # noqa
  File "/vagrant/borg/borg/.tox/py38/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/vagrant/borg/borg/.tox/py38/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/vagrant/borg/borg/.tox/py38/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions   
  File "/vagrant/borg/borg/.tox/py38/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
    from pip._internal.exceptions import CommandError
  File "/vagrant/borg/borg/.tox/py38/lib/python3.8/site-packages/pip/_internal/exceptions.py", line 10, in <module>
    from pip._vendor.six import iteritems             
ModuleNotFoundError: No module named 'pip._vendor.six' 
```

The bionic64, stretch64, buster64 boxes provisioned from same Vagrantfile section do not run into this.

**Comment by ThomasWaldmann** [comment]
trying again with an updated box now...

**Comment by ThomasWaldmann** [comment]
Nope, same thing with latest box.

**Comment by ThomasWaldmann** [comment]
There is no `python-virtualenv` package, but `virtualenv` and `python3-virtualenv`.

**Comment by ThomasWaldmann** [comment]
above stuff was fixed by my PR, but now it runs into this:
```
py38 installdeps: -rrequirements.d/development.txt, -rrequirements.d/fuse.txt                                                                                                                            [52/18353]
ERROR: invocation failed (exit code 1), logfile: /vagrant/borg/borg/.tox/py38/log/py38-1.log
==================================================================================================== log start ====================================================================================================Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main                                                                                          
    return _run_code(code, main_globals, None,         
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)                            
  File "/vagrant/borg/borg/.tox/py38/lib/python3.8/site-packages/pip/__main__.py", line 16, in <module>
    from pip._internal.cli.main import main as _main  # isort:skip # noqa
  File "/vagrant/borg/borg/.tox/py38/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/vagrant/borg/borg/.tox/py38/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/vagrant/borg/borg/.tox/py38/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions   
  File "/vagrant/borg/borg/.tox/py38/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
    from pip._internal.exceptions import CommandError
  File "/vagrant/borg/borg/.tox/py38/lib/python3.8/site-packages/pip/_internal/exceptions.py", line 10, in <module>
    from pip._vendor.six import iteritems             
ModuleNotFoundError: No module named 'pip._vendor.six' 
```

**Comment by ThomasWaldmann** [comment]
@LocutusOfBorg ^^^ any idea? did that get broken by unbundling six from pip?

**Comment by ThomasWaldmann** [comment]
The issue can be reproduced like:
- clone the borg repo, checkout master branch
- vagrant up focal64  # crashes (see above)
- vagrant up bionic64  # works

**Comment by ThomasWaldmann** [comment]
Does not happen any more since yesterday.

Thanks for whoever has fixed it!

**Comment by LocutusOfBorg** [comment]
thanks for opening, unfortunately I never had a clue on this...
