### ISSUE TITLE
Python Exception Unknown integrity data version None in integrity.643

### ISSUE THREAD

**Issue by mikehaertl** [borgbackup/borg#5143]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).

borg 1.1.5

#### Operating system (distribution) and version.

LinuxMint 19.3 tricia

#### Hardware / network configuration, and filesystems used.

Not relevant.

#### How much data is handled by borg?

None.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
#!/bin/bash
set -e
REPO=/media/mike/Backup/borg_nilar
read -s -p "Repository passphrase: " BORG_PASSPHRASE
export BORG_PASSPHRASE
info() { printf "\n%s %s\n\n" "$( date )" "$*" >&2; }
trap 'echo $( date ) Backup interrupted >&2; exit 2' INT TERM
info "Starting backup"
borg create \
    --verbose \
    --filter AME \
    --stats \
    --show-rc \
    --compression lz4 \
    --exclude-caches \
    --exclude '/home/*/.cache/*' \
    \
    $REPO::'{now}' \
    /etc \
    /home \
    /root
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes.

Borg was working for months, now it throws an exception.

The only relevant change I did was to install the `pynvim` python package. I'm no python expert but it's possible that this caused some dependend packages to be installed or updated.

#### Include any warning/errors/backtraces from the system logs

```
Unknown integrity data version None in integrity.643
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4253, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4185, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 139, in wrapper
    kwargs['manifest'], kwargs['key'] = Manifest.load(repository, compatibility)
  File "/usr/lib/python3/dist-packages/borg/helpers.py", line 334, in load
    key = key_factory(repository, cdata)
  File "/usr/lib/python3/dist-packages/borg/crypto/key.py", line 135, in key_factory
    return identify_key(manifest_data).detect(repository, manifest_data)
  File "/usr/lib/python3/dist-packages/borg/crypto/key.py", line 593, in detect
    if not key.load(target, passphrase):
  File "/usr/lib/python3/dist-packages/borg/crypto/key.py", line 779, in load
    success = self._load(key_data, passphrase)
  File "/usr/lib/python3/dist-packages/borg/crypto/key.py", line 608, in _load
    data = self.decrypt_key_file(cdata, passphrase)
  File "/usr/lib/python3/dist-packages/borg/crypto/key.py", line 629, in decrypt_key_file
    assert enc_key.algorithm == 'sha256'
  File "src/borg/item.pyx", line 101, in borg.item.PropDict._make_property._get
TypeError: descriptor 'decode' requires a 'bytes' object but received a 'str'

Platform: Linux Nilar 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64
Linux: LinuxMint 19.3 tricia
Borg: 1.1.5  Python: CPython 3.6.9
PID: 6118  CWD: /home/mike
sys.argv: ['/usr/bin/borg', 'create', '--verbose', '--filter', 'AME', '--stats', '--show-rc', '--compression', 'lz4', '--exclude-caches', '--exclude', '/home/*/.cache/*', '/media/mike/Backup/borg_nilar::{now}', '/etc', '/home', '/root']
SSH_ORIGINAL_COMMAND: None
```

**Comment by infectormp** [comment]
You use outdated version of borg, please update to the latest version and try to reproduce this issue again.

**Comment by mikehaertl** [comment]
Oh, right, thanks. I found that I was using the default distribution packages which seemed a bit outdated. I've now switched to the borg PPA wich fixed the issue indeed. For the record:

```
sudo add-apt-repository ppa:costamagnagianfranco/borgbackup
sudo apt-get update
```

**Comment by ThomasWaldmann** [comment]
Still interesting that this suddenly popped up "after months".

**Comment by mikehaertl** [comment]
@ThomasWaldmann Let me know if I you want to investigate this more. I've used borg on a weekly basis to do a backup of my system for at least half a year and it worked fine. According to the apt logs it also wasn't updated recently.

As I said I've used `pip install pynvim` (and I think also `pip2 install pynvim`). I don't know if there's a history of updated packages, but here's the list of packages with current versions on my system:

```
# pip list
configobj (5.0.6)
futures (3.3.0)
greenlet (0.4.15)
lxml (4.2.1)
msgpack (0.6.2)
pip (9.0.1)
pycairo (1.16.2)
pycrypto (2.6.1)
pygobject (3.26.1)
pynvim (0.4.0)
pyparted (3.11.1)
python-apt (1.6.5+ubuntu0.2)
python-xlib (0.20)
pyxdg (0.25)
setproctitle (1.1.10)
setuptools (41.6.0)
six (1.11.0)
trollius (2.2.post1)
wxPython (3.0.2.0)
wxPython-common (3.0.2.0)

# pip2 list
configobj (5.0.6)
futures (3.3.0)
greenlet (0.4.15)
lxml (4.2.1)
msgpack (0.6.2)
pip (9.0.1)
pycairo (1.16.2)
pycrypto (2.6.1)
pygobject (3.26.1)
pynvim (0.4.0)
pyparted (3.11.1)
python-apt (1.6.5+ubuntu0.2)
python-xlib (0.20)
pyxdg (0.25)
setproctitle (1.1.10)
setuptools (41.6.0)
six (1.11.0)
trollius (2.2.post1)
wxPython (3.0.2.0)
wxPython-common (3.0.2.0)
```

**Comment by ThomasWaldmann** [comment]
msgpack (0.6.2) == not compatible with borg 1.1.x.

borg 1.1.11 might have (depending on actual packaging) a built-in, compatible msgpack 0.5.6.
