### ISSUE TITLE
Getting a "file exists" error

### ISSUE THREAD

**Issue by samteezy** [borgbackup/borg#5190]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug

## System information. For client/server mode post info for both machines.
The host system is Solus Linux 4.1, the server I'm writing to is a Synology NAS.
```
Platform: Linux tributo 5.6.13-153.current #1 SMP PREEMPT Thu May 14 20:38:48 UTC 2020 x86_64
Linux:   
Borg: 1.1.11  Python: CPython 3.7.6 msgpack: 0.5.6
```

#### How much data is handled by borg?
~300GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
I'm executing it from Vorta, not sure the command itself.

## Describe the problem you're observing.
Vorta/Borg stopped running backups about a day ago, and I'm not sure why. It has been writing to a mounted NFS share without any issue.
The issue at the end says the "File Exists", but when I browse the share, the latest file is '2060'.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yep, I cannot run any backups to this repo whether automated or scheduled. I've rebooted all devices to no avail.

#### Include any warning/errors/backtraces from the system logs

```
2020-05-19 08:50:00,001 - apscheduler.executors.default - INFO - Running job "VortaScheduler.create_backup (trigger: cron[hour='*/1', minute='50'], next run at: 2020-05-19 08:50:00 EDT)" (scheduled at 2020-05-19 08:50:00-04:00)
2020-05-19 08:50:00,005 - vorta.scheduler - INFO - Starting background backup for Default
2020-05-19 08:50:00,006 - vorta.notifications - DEBUG - success notifications suppressed
2020-05-19 08:50:00,006 - vorta.borg.borg_thread - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2020-05-19 08:50:00,007 - asyncio - DEBUG - Using selector: EpollSelector
2020-05-19 08:50:00,009 - root - DEBUG - Found 1 passwords matching repo URL.
2020-05-19 08:50:00,041 - vorta.scheduler - INFO - Preparation for backup successful.
2020-05-19 08:50:00,062 - vorta.borg.borg_thread - INFO - Running command /usr/bin/borg create --list --info --log-json --json --filter=AM -C zstd,3 --exclude-from /tmp/tmpe7vzh7u5 /run/user/1000/gvfs/nfs:host=10.10.1.21,prefix=%2Fvolume1%2FBorgBackup/tributo::tributo-default-2020-05-19T08:50:00 /home/sam
2020-05-19 08:50:06,176 - vorta.borg.borg_thread - INFO - Creating archive at "/run/user/1000/gvfs/nfs:host=10.10.1.21,prefix=%2Fvolume1%2FBorgBackup/tributo::tributo-default-2020-05-19T08:50:00"
2020-05-19 08:50:08,401 - vorta.borg.borg_thread - ERROR - Local Exception
2020-05-19 08:50:08,402 - vorta.borg.borg_thread - ERROR - Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4529, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4461, in run
    return set_ec(func(args))
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 166, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 574, in do_create
    create_inner(archive, cache)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 537, in create_inner
    read_special=args.read_special, dry_run=dry_run, st=st)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 651, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 651, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 625, in _process
    status = archive.process_file(path, st, cache)
  File "/usr/lib/python3.7/site-packages/borg/archive.py", line 1071, in process_file
    self.chunk_file(item, cache, self.stats, backup_io_iter(self.chunker.chunkify(fd, fh)))
  File "/usr/lib/python3.7/site-packages/borg/archive.py", line 999, in chunk_file
    item.chunks.append(chunk_processor(data))
  File "/usr/lib/python3.7/site-packages/borg/archive.py", line 987, in chunk_processor
    chunk_entry = cache.add_chunk(self.key.id_hash(data), data, stats, wait=False)
  File "/usr/lib/python3.7/site-packages/borg/cache.py", line 899, in add_chunk
    self.repository.put(id, data, wait=wait)
  File "/usr/lib/python3.7/site-packages/borg/repository.py", line 1131, in put
    segment, offset = self.io.write_put(id, data)
  File "/usr/lib/python3.7/site-packages/borg/repository.py", line 1532, in write_put
    fd = self.get_write_fd(raise_full=raise_full)
  File "/usr/lib/python3.7/site-packages/borg/repository.py", line 1313, in get_write_fd
    self._write_fd = SyncFile(self.segment_filename(self.segment), binary=True)
  File "/usr/lib/python3.7/site-packages/borg/platform/base.py", line 106, in __init__
    self.fd = open(path, mode)
FileExistsError: [Errno 17] File exists: '/run/user/1000/gvfs/nfs:host=10.10.1.21,prefix=%2Fvolume1%2FBorgBackup/tributo/data/2/2061'
```

**Comment by ThomasWaldmann** [comment]
Well, if you are sure that file does not exist, it would mean that your fs does not work correctly.

**Comment by ThomasWaldmann** [comment]
Guess we can't do anything about this, looks like a fs issue below borg.
