### ISSUE TITLE
Backup crashing after some hours; Reason unknown.

### ISSUE THREAD

**Issue by ho1ger** [borgbackup/borg#523]
I run borg on a Raspberry Pi. Yesterday I wanted to do the (first) backup of a large (200GB) set of data to a remote server mounted as webdav. This morning I found the following stacktrace:

    Object with key b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' not found in repository /media/1und1/backup/photo.
    Traceback (most recent call last):
      File "/root/scripts/photobackup/borg-env/lib/python3.2/site-packages/borg/repository.py", line 417, in get
        segment, offset = self.index[id_]
      File "borg/hashindex.pyx", line 106, in borg.hashindex.NSIndex.__getitem__ (borg/hashindex.c:2329)
    KeyError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/root/scripts/photobackup/borg-env/lib/python3.2/site-packages/borg/archiver.py", line 1261, in main
        exit_code = archiver.run(args)
      File "/root/scripts/photobackup/borg-env/lib/python3.2/site-packages/borg/archiver.py", line 1215, in run
        return args.func(args)
      File "/root/scripts/photobackup/borg-env/lib/python3.2/site-packages/borg/archiver.py", line 134, in do_create
        manifest, key = Manifest.load(repository)
      File "/root/scripts/photobackup/borg-env/lib/python3.2/site-packages/borg/helpers.py", line 92, in load
        cdata = repository.get(cls.MANIFEST_ID)
      File "/root/scripts/photobackup/borg-env/lib/python3.2/site-packages/borg/repository.py", line 420, in get
        raise self.ObjectNotFound(id_, self.path)
    borg.repository.ObjectNotFound: (b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '/media/1und1/backup/photo')

    Platform: Linux backuppi 4.1.7+ #817 PREEMPT Sat Sep 19 15:25:36 BST 2015 armv6l 
    Linux: debian 7.8   LibC: glibc 2.9
    Python: CPython 3.2.3

I called borg as follows:

    borg create --progress --stats --compression none $DESTINATION::$date $SOURCES

Also listing the incomplete backup fails with the same trace.

I do not really understand what caused this issue but I wanted to let you know. If there is anything I can do to provide further insight, let me know.
 
Furthermore: is there anything I can do to recover from this issue? Or do I have to start over?

**Comment by ThomasWaldmann** [comment]
It seems like the manifest (object 0) is missing from your repo. You can use `borg check` to fix that, but it will take a while (depending on machine speed and repo size).

The root cause is unclear, the above traceback does not show it. So, without more information, I guess we can't work on that.

**Comment by ho1ger** [comment]
I run `borg check -v` right at the moment. I'll post the outcome of this operation when done. Maybe this provides further insight.

**Comment by ThomasWaldmann** [comment]
Any news?

**Comment by ho1ger** [comment]
Excuse me, I forgot to post an update.

I was unable to complete the check procedure. After entering the password, borg started to rebuild the manifest (I hope I use the right terms). Some time later I got an exception, which was as meaningful as the one I posted above. I tried a second time and got a different (!) exception.

I wiped the unfinished backup. Before starting a new backup, I tried to find issues with the machine itself. Indeed I found numerous warnings concerning the davfs2 cache. I fixed the problem, no more warnings, and started a new backup. Result as described in my first post. *shrug*

I give it a new shot, I just saw that there is the option to enable debug output while creating a backup. I'll keep you posted.

**Comment by ThomasWaldmann** [comment]
If it doesn't work with davfs2, try ext4, so you see whether the trouble comes from borg or the fs.

**Comment by ho1ger** [comment]
Uhm, I can't. The storage space I want to use is on a machine I do not administer. I only have access via webdav.

I just checked what the Raspberry Pi is doing. The process stopped. No exception. But the last lines of output are:

    A /media/safe/Photo/JPEG/2008/2008-10-19 -- FooBarBaz/2008-10-25 -- 052.JPG 052.JPG
    /media/safe/Photo/JPEG/2008/2008-10-19 -- FooBarBaz/2008-10-25 -- 053.JPG: [Errno 2] No such file or directory
    E /media/safe/Photo/JPEG/2008/2008-10-19 -- FooBarBaz/2008-10-25 -- 053.JPG
    Archive 2016_01_14_21_07_25.checkpoint already existslder...008-10-25 -- 054.JPG


I tried to resume the backup process and got 

    using builtin fallback logging configuration
    Local Exception.
    Traceback (most recent call last):
      File "/root/scripts/photobackup/borg-env/lib/python3.2/site-packages/borg/repository.py", line 559, in get_fd
        return self.fds[segment]
      File "/root/scripts/photobackup/borg-env/lib/python3.2/site-packages/borg/lrucache.py", line 18, in __getitem__
        value = self._cache[key]  # raise KeyError if not found
    KeyError: 3395

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/root/scripts/photobackup/borg-env/lib/python3.2/site-packages/borg/archiver.py", line 1261, in main
        exit_code = archiver.run(args)
      File "/root/scripts/photobackup/borg-env/lib/python3.2/site-packages/borg/archiver.py", line 1215, in run
        return args.func(args)
      File "/root/scripts/photobackup/borg-env/lib/python3.2/site-packages/borg/archiver.py", line 134, in do_create
        manifest, key = Manifest.load(repository)
      File "/root/scripts/photobackup/borg-env/lib/python3.2/site-packages/borg/helpers.py", line 92, in load
        cdata = repository.get(cls.MANIFEST_ID)
      File "/root/scripts/photobackup/borg-env/lib/python3.2/site-packages/borg/repository.py", line 418, in get
        return self.io.read(segment, offset, id_)
      File "/root/scripts/photobackup/borg-env/lib/python3.2/site-packages/borg/repository.py", line 616, in read
        fd = self.get_fd(segment)
      File "/root/scripts/photobackup/borg-env/lib/python3.2/site-packages/borg/repository.py", line 561, in get_fd
        fd = open(self.segment_filename(segment), 'rb')
    IOError: [Errno 2] No such file or directory: '/media/1und1/backup/photobackup/data/0/3395'

    Platform: Linux backuppi 4.1.7+ #817 PREEMPT Sat Sep 19 15:25:36 BST 2015 armv6l 
    Linux: debian 7.8   LibC: glibc 2.9
    Python: CPython 3.2.3

**Comment by ho1ger** [comment]
Update: I found that the davfs was not mounted anymore. Reason: unclear. Remounting and resuming the backup fails. Maybe davfs + borg is no good combination... =)

**Comment by ThomasWaldmann** [comment]
ok, thanks for updating us.
