### ISSUE TITLE
"KeyError: 4237" "FileNotFoundError: [Errno 2] No such file or directory: '/$REPO/lm/data/4/4237'" (zero lenght file)

### ISSUE THREAD

**Issue by tpo** [borgbackup/borg#5233]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).

At the time when the problem first appeared:

client: 1.1.5
server: 1.1.9-2

* I have meanwhile updated the server to 1.1.11
* but the problem also occurs when using 1.1.13 on both server and client

#### Operating system (distribution) and version.

client: Ubuntu bionic or Debian buster
server: Debian buster

#### Hardware / network configuration, and filesystems used.

backing up over network (ssh) to server that has a Hetzner storagebox attached/mounted

#### How much data is handled by borg?

0.5 TB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg check  # both on server and client
borg check --repair
borg create --compression zlib,6 -v --stats ssh://$BORGREPO/lm::lm-2020-06-18_17:05:42 . --exclude mnt/ --exclude var/cache/apt/archives/ --exclude var/lib/libvirt/images/ --exclude proc/ --exclude dev/ --exclude run/ --exclude sys/ --exclude tmp/ --exclude media/

## Describe the problem you're observing.

```
Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1347, in get_fd
    ts, fd = self.fds[segment]

  File "/usr/lib/python3/dist-packages/borg/lrucache.py", line 21, in __getitem__
    value = self._cache[key]  # raise KeyError if not found

KeyError: 4237


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/borg/remote.py", line 247, in serve
    res = f(**args)

  File "/usr/lib/python3/dist-packages/borg/remote.py", line 375, in open
    self.repository.__enter__()  # clean exit handled by serve() method

  File "/usr/lib/python3/dist-packages/borg/repository.py", line 190, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)

  File "/usr/lib/python3/dist-packages/borg/repository.py", line 437, in open
    if segment is not None and self.io.get_segment_magic(segment) == ATTIC_MAGIC:

  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1382, in get_segment_magic
    fd = self.get_fd(segment)

  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1349, in get_fd
    fd = open_fd()

  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1330, in open_fd
    fd = open(self.segment_filename(segment), 'rb')

FileNotFoundError: [Errno 2] No such file or directory: '/mnt/backup/borg/lm/data/4/4237'

Borg server: Platform: Linux borg 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64
Borg server: Linux: debian 10.4 
Borg server: Borg: 1.1.11  Python: CPython 3.7.3 msgpack: 0.5.6
Borg server: PID: 1868  CWD: /home/borg
Borg server: sys.argv: ['/usr/bin/borg', 'serve', '--umask=077']
Borg server: SSH_ORIGINAL_COMMAND: None
Platform: Linux hier 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64
Linux: debian 10.4 
Borg: 1.1.13  Python: CPython 3.5.9 msgpack: 0.5.6
PID: 7855  CWD: /tmp/foo.H2FbFI
sys.argv: ['/tmp/borg-linux64', 'check']
SSH_ORIGINAL_COMMAND: None
```

The `check` command on the server looks like this:

```
Exception ignored in: <function Repository.__del__ at 0x7f19b69bbd08>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 180, in __del__
    assert False, "cleanup happened in Repository.__del__"
AssertionError: cleanup happened in Repository.__del__
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1347, in get_fd
    ts, fd = self.fds[segment]
  File "/usr/lib/python3/dist-packages/borg/lrucache.py", line 21, in __getitem__
    value = self._cache[key]  # raise KeyError if not found
KeyError: 4237

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4529, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4461, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 151, in wrapper
    with repository:
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 190, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 437, in open
    if segment is not None and self.io.get_segment_magic(segment) == ATTIC_MAGIC:
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1382, in get_segment_magic
    fd = self.get_fd(segment)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1349, in get_fd
    fd = open_fd()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1330, in open_fd
    fd = open(self.segment_filename(segment), 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/backup/borg/lm/data/4/4237'

Platform: Linux borg 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64
Linux: debian 10.4 
Borg: 1.1.11  Python: CPython 3.7.3 msgpack: 0.5.6
PID: 1900  CWD: /tmp
sys.argv: ['/usr/bin/borg', 'check']
SSH_ORIGINAL_COMMAND: None
```

However:

```
# ls -l /mnt/backup/borg/lm/data/4/4237
-rw-rw---- 0 borg borg 0 Jun 18 03:29 /mnt/backup/borg/lm/data/4/4237
```

So that file **does** indeed exist, but has zero length.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes, the problem is reproducible, see above.

#### Include any warning/errors/backtraces from the system logs

See above.

It's noteworthy that this is the second client we are seeing this exact problem with. We solved the problem on the first occurence by deleting the repository and recreating the backup. However with this backup repository I'd prefer to keep the history if at all possible.

What is also noteworthy is that there apparently was a timeout issue with the CIFS storage when the problem started:

```
Jun 17 03:33:35 borg kernel: [2968849.001279] CIFS VFS: sends on sock 00000000e92e426b stuck for 15 seconds
Jun 17 03:33:35 borg kernel: [2968849.002040] CIFS VFS: Error -11 sending data on socket to server
Jun 17 03:33:50 borg kernel: [2968864.360873] CIFS VFS: sends on sock 00000000e92e426b stuck for 15 seconds
Jun 17 03:33:50 borg kernel: [2968864.362171] CIFS VFS: Error -11 sending data on socket to server
Jun 17 03:34:49 borg kernel: [2968923.220881] Status code returned 0xc0000128 STATUS_FILE_CLOSED
Jun 17 03:34:49 borg kernel: [2968923.221960] Status code returned 0xc0000128 STATUS_FILE_CLOSED
Jun 17 03:34:49 borg kernel: [2968923.221982] CIFS VFS: Send error in read = -9
Jun 17 03:34:49 borg kernel: [2968923.223425] CIFS VFS: Send error in read = -9
Jun 17 03:34:49 borg kernel: [2968923.235297] Status code returned 0xc0000128 STATUS_FILE_CLOSED
Jun 17 03:34:49 borg kernel: [2968923.235879] CIFS VFS: Send error in read = -9
Jun 17 03:35:13 borg kernel: [2968947.046718] CIFS VFS: sends on sock 00000000e92e426b stuck for 15 seconds
Jun 17 03:35:13 borg kernel: [2968947.058023] CIFS VFS: Error -11 sending data on socket to server
Jun 17 03:35:28 borg kernel: [2968962.406179] CIFS VFS: sends on sock 00000000e92e426b stuck for 15 seconds
Jun 17 03:35:28 borg kernel: [2968962.406807] CIFS VFS: Error -11 sending data on socket to server
Jun 17 03:36:38 borg kernel: [2969031.780423] CIFS VFS: sends on sock 000000005653428f stuck for 15 seconds
Jun 17 03:36:38 borg kernel: [2969031.781849] CIFS VFS: Error -11 sending data on socket to server
Jun 17 03:36:53 borg kernel: [2969047.139962] CIFS VFS: sends on sock 000000005653428f stuck for 15 seconds
Jun 17 03:36:53 borg kernel: [2969047.141050] CIFS VFS: Error -11 sending data on socket to server
Jun 17 03:37:34 borg kernel: [2969088.098768] CIFS VFS: sends on sock 00000000775ced49 stuck for 15 seconds
Jun 17 03:37:34 borg kernel: [2969088.099415] CIFS VFS: Error -11 sending data on socket to server
Jun 17 03:37:49 borg kernel: [2969103.458419] CIFS VFS: sends on sock 00000000775ced49 stuck for 15 seconds
Jun 17 03:37:49 borg kernel: [2969103.459948] CIFS VFS: Error -11 sending data on socket to server
```

Note the very similar timestamp of the file and of the kernel log entry, differing by **one day**. So I suppose the problem happened on the 17th but borg only noticed on the following day when cron reran the backup.

**Comment by ThomasWaldmann** [comment]
These CIFS VFS error messages pretty much point to a filesystem/network issue below borg.

There's nothing borg can do about that, you need to have a working filesystem for your repo.

**Comment by ThomasWaldmann** [comment]
Also, why do you use CIFS anyway?

borg can directly talk to the storagebox (which has borg installed) by using a ssh:// repo url.

**Comment by ThomasWaldmann** [comment]
Side note: did you follow the advisory at the top of the changelog after upgrading to 1.1.11/1.1.13?

**Comment by tpo** [comment]
> These CIFS VFS error messages pretty much point to a filesystem/network issue below borg.
> 
> There's nothing borg can do about that, you need to have a working filesystem for your repo.

```
root@borg ~ # ls -l /mnt/backup/borg/lm/data/4/4237
-rw-rw---- 0 borg borg 0 Jun 18 03:29 /mnt/backup/borg/lm/data/4/4237
root@borg ~ # cat /mnt/backup/borg/lm/data/4/4237
cat: /mnt/backup/borg/lm/data/4/4237: No such file or directory
```

Your diagnosis is spot on. Thanks a lot!

**Comment by tpo** [comment]
> Side note: did you follow the advisory at the top of the changelog after upgrading to 1.1.11/1.1.13?

I did not, thanks.

**Comment by tpo** [comment]
> Also, why do you use CIFS anyway?
> 
> borg can directly talk to the storagebox (which has borg installed) by using a ssh:// repo url.

I'll investigate, thanks.
