### ISSUE TITLE
How to find cause of a stale file handle?

### ISSUE THREAD

**Issue by Nuube** [borgbackup/borg#5311]
For a while when running Borg I get persistently a "stale file handle" message. 

I am aware that this is unlikely a Borg issue. But how I can find the file which causes the error and what would be the best way to repair the archive?

```
Local Exceptionents  99%
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4529, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4461, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 166, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 574, in do_create
    create_inner(archive, cache)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 539, in create_inner
    archive.save(comment=args.comment, timestamp=args.timestamp)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 517, in save
    self.repository.commit()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 461, in commit
    self.compact_segments()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 742, in compact_segments
    for tag, key, offset, data in self.io.iter_objects(segment, include_data=True):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1401, in iter_objects
    if fd.read(MAGIC_LEN) != MAGIC:
OSError: [Errno 116] Stale file handle

Platform: Linux desktop 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64
Linux: Unknown Linux  
Borg: 1.1.11  Python: CPython 3.8.2 msgpack: 0.5.6
PID: 219415  CWD: /mnt/server2
sys.argv: ['/usr/bin/borg', 'create', '--stats', '--exclude-caches', '--exclude-from', '/home/michael/bin/exclude.dir', '--compression', 'zstd', '-v', '--progress', '--one-file-system', '/mnt/server2/backups/borg::{hostname}-{now:%Y-%m-%d}', '/home/michael', '/home/michael/server1/michael', '/home/michael/.gocryptfs/decrpyted', '/etc']
SSH_ORIGINAL_COMMAND: None

Synchronizing chunks cache...
Archives: 28, w/ cached Idx: 38, w/ outdated Idx: 13, w/o cached Idx: 3.
Reading cached archive chunk index for E7450-2019-05-16 ...
Merging into master chunks index ...
Reading cached archive chunk index for VirtualBoxes-2019-10-27 ...

```

or

```Pruning archive: desktop-2019-10-27                   Sun, 2019-10-27 16:05:14 [86c80148b9268b1fc68e369dc0647ee078d0a8922093c8b165c3fc3aee8d4176] (1/1)
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4529, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4461, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 166, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1624, in do_prune
    Archive(repository, key, manifest, archive.name, cache).delete(stats, forced=args.forced)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 852, in delete
    chunk_decref(chunk_id, stats)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 829, in chunk_decref
    self.cache.chunk_decref(id, stats, wait=False)
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 926, in chunk_decref
    self.repository.delete(id, wait=wait)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1155, in delete
    size = self.io.read(segment, offset, id, read_data=False)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1469, in read
    header = fd.read(self.put_header_fmt.size)
OSError: [Errno 116] Stale file handle

Platform: Linux desktop 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64
Linux: Unknown Linux  
Borg: 1.1.11  Python: CPython 3.8.2 msgpack: 0.5.6
PID: 219785  CWD: /mnt/server2
sys.argv: ['/usr/bin/borg', 'prune', '-v', '--list', '/mnt/server2/backups/borg', '--prefix', '{hostname}-', '--keep-daily=3', '--keep-weekly=3', '--keep-monthly=6', '--keep-yearly=2']
SSH_ORIGINAL_COMMAND: None```

**Comment by ThomasWaldmann** [comment]
Stale file handle usually means that the server decided to close the file while borg had still open file handles to it.

Some servers allow to configure some sort of timeout when this happens. There were also changes in recent borg releases to reduce this kind of issue, see changelog.

**Comment by ThomasWaldmann** [comment]
See also: #3265 (fixed since borg 1.1.10)

**Comment by brando90** [comment]
I also can't find the cause of the stale file handle. Did you find it?

**Comment by infectormp** [comment]
maybe this helps https://www.baeldung.com/linux/stale-file-handles

**Comment by ThomasWaldmann** [comment]
Guess this can be closed. Not a borg problem, but a problem of the filesystem.
