### ISSUE TITLE
os.replace errors with: FileExistsError: [Errno 17]

### ISSUE THREAD

**Issue by kalsan** [borgbackup/borg#5319]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug

#### Your borg version (borg -V).

borg 1.1.9
borg 1.1.11

#### Operating system (distribution) and version.

Debian Buster

#### Hardware / network configuration, and filesystems used.

Mounted SMB-Share

#### How much data is handled by borg?

Between 200 and 500 GB

#### Full borg command

```
export BORG_REPO=/path/to/share

read -sp "Borg password?" pw
export BORG_PASSPHRASE=$pw

borg create                         \
    --verbose                       \
    --filter AME                    \
    --progress                      \
    --stats                         \
    --show-rc                       \
    --compression lz4               \
    --exclude-caches                \
    --exclude '/home/*/.cache/*'    \
    --exclude '/var/cache/*'        \
    --exclude '/var/tmp/*'          \
                                    \
    ::'{hostname}-{now}'            \
    /etc                            \
    /home                           \
    /root                           \
    /var                            \
    /opt                            \
    /snap                           \
    /media/otherhdd               \

```

## Describe the problem you're observing.

A backup script that used to work fine has stopped working. borg create would start crashing with the error message below, with increasing frequency. It now occurs at every execution, always at the same spot (between 4 and 5 GB deduplicated content, independently of what file is being copied). Borg prune stopped working with the same error message, however removing the indicated files manually allowed me to prune once. The backup still won't work.

Free space is not the issue. I successfully created a 10 GB file on the SMB share. The backup has worked for months and was never modified.

Here's the error message:

```
Creating archive at "/media/my-smb-share/borgrepo::my-pc-2020-09-02T15:56:24"
Local Exception.02 GB C 4.29 GB D 200705 N home/me/some-file-but-not-always-same
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4529, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4461, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 166, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 574, in do_create
    create_inner(archive, cache)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 537, in create_inner
    read_special=args.read_special, dry_run=dry_run, st=st)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 651, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 651, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 651, in _process
    read_special=read_special, dry_run=dry_run)
  [Previous line repeated 4 more times]
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 625, in _process
    status = archive.process_file(path, st, cache)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 1071, in process_file
    self.chunk_file(item, cache, self.stats, backup_io_iter(self.chunker.chunkify(fd, fh)))
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 999, in chunk_file
    item.chunks.append(chunk_processor(data))
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 987, in chunk_processor
    chunk_entry = cache.add_chunk(self.key.id_hash(data), data, stats, wait=False)
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 897, in add_chunk
    data = self.key.encrypt(chunk)
  File "/usr/lib/python3/dist-packages/borg/crypto/key.py", line 370, in encrypt
    self.nonce_manager.ensure_reservation(num_aes_blocks(len(data)))
  File "/usr/lib/python3/dist-packages/borg/crypto/nonces.py", line 85, in ensure_reservation
    self.commit_repo_nonce_reservation(reservation_end, repo_free_nonce)
  File "/usr/lib/python3/dist-packages/borg/crypto/nonces.py", line 48, in commit_repo_nonce_reservation
    self.repository.commit_nonce_reservation(next_unreserved, start_nonce)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 346, in commit_nonce_reservation
    fd.write(bin_to_hex(next_unreserved.to_bytes(8, byteorder='big')))
  File "/usr/lib/python3/dist-packages/borg/platform/base.py", line 176, in __exit__
    os.replace(self.tmppath, self.path)
FileExistsError: [Errno 17] File exists: '/media/my-smb-share/borgrepo/nonce.tmp' -> '/media/my-smb-share/borgrepo/nonce'

Platform: Linux my-pc 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64
Linux: debian 10.5 
Borg: 1.1.11  Python: CPython 3.7.3 msgpack: 0.5.6
PID: 21996  CWD: /home/me
sys.argv: ['/usr/bin/borg', 'create', '--verbose', '--filter', 'AME', '--progress', '--stats', '--show-rc', '--compression', 'lz4', '--exclude-caches', '--exclude', '/home/*/.cache/*', '--exclude', '/var/cache/*', '--exclude', '/var/tmp/*', '::{hostname}-{now}', '/etc', '/home', '/root', '/var', '/opt', '/snap', '/media/sda1_crypt']
SSH_ORIGINAL_COMMAND: None

terminating with error status, rc 2
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

By now, every insance of the backup produces the problem as described above.

#### Include any warning/errors/backtraces from the system logs

Done above

**Comment by ThomasWaldmann** [comment]
IIRC we already had that, did you search old issues?

In short: your filesystem does not work correctly, `os.replace` is documented to replace existing target files.

**Comment by ThomasWaldmann** [comment]
duplicate of #5253?

**Comment by kalsan** [comment]
Hello and thank you for pointing out the issue! Evidently I did not do my homework well enough after all. The error behavior is identical and it's almost certainly an exact duplicate. Closing.
