### ISSUE TITLE
FileExistsError when trying to delete a backup

### ISSUE THREAD

**Issue by neunenak** [borgbackup/borg#5331]
I'm running borg version 1.1.13. I accidentally ran a normal backup that happened to include a bunch of large files that I didn't want to backup. When I realized this (because the backup was taking a lot longer than it should have), I killed the still-ongoing `borg create` process with Ctrl-C, leaving me with a `.checkpoint` backup. I didn't want any of those files to persist in the repo, so I ran:

`borg -v delete -s <path to backup>::backup-2020-09-08T18:10:32.checkpoint`

and in turn got the following error:
```
Deleting archive: backup-2020-09-08T18:10:32.checkpoint Tue, 2020-09-08 18:10:36 [60bc91b5ed5408065c4e002ebac04b575c510de8846f919ce4c8fb93a02f0488] (1/1)
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/borg/archiver.py", line 4565, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.8/site-packages/borg/archiver.py", line 4497, in run
    return set_ec(func(args))
  File "/usr/lib/python3.8/site-packages/borg/archiver.py", line 176, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.8/site-packages/borg/archiver.py", line 1275, in do_delete
    return self._delete_archives(args, repository)
  File "/usr/lib/python3.8/site-packages/borg/archiver.py", line 1332, in _delete_archives
    archive.delete(stats, progress=args.progress, forced=args.forced)
  File "/usr/lib/python3.8/site-packages/borg/archive.py", line 846, in delete
    chunk_decref(items_id, stats)
  File "/usr/lib/python3.8/site-packages/borg/archive.py", line 829, in chunk_decref
    self.cache.chunk_decref(id, stats, wait=False)
  File "/usr/lib/python3.8/site-packages/borg/cache.py", line 926, in chunk_decref
    self.repository.delete(id, wait=wait)
  File "/usr/lib/python3.8/site-packages/borg/repository.py", line 1172, in delete
    segment, size = self.io.write_delete(id)
  File "/usr/lib/python3.8/site-packages/borg/repository.py", line 1556, in write_delete
    fd = self.get_write_fd(raise_full=raise_full)
  File "/usr/lib/python3.8/site-packages/borg/repository.py", line 1327, in get_write_fd
    self._write_fd = SyncFile(self.segment_filename(self.segment), binary=True)
  File "/usr/lib/python3.8/site-packages/borg/platform/base.py", line 106, in __init__
    self.fd = open(path, mode)
FileExistsError: [Errno 17] File exists: '<path to backup>/data/1/1124'
```

This happens repeatedly whenever I try to run the above `borg delete` command, and I can still see the checkpoint backup when I run `borg list`.

**Comment by ThomasWaldmann** [comment]
Can you still reproduce this? Does the file really exist?

**Comment by ThomasWaldmann** [comment]
What filesystem is your repo on? How is it mounted?

**Comment by ThomasWaldmann** [comment]
Maybe related: #5190, #5253

**Comment by neunenak** [comment]
> Can you still reproduce this? Does the file really exist?

Yes I can consistently reproduce this. I can see that the file at that path (`'<path to backup>/data/1/1124'`) does exist in the filesystem, it's one of many files in that `1` directory. The filesystem is wasabi s3 storage being mounted locally with `rclone mount`.

**Comment by neunenak** [comment]
I tried running `borg check` on the repository and it did reveal that the repository had errors. This took a while to run because of the size of the repo, and I haven't tried to pass the flag to fix them yet. Not sure if this is related.

**Comment by ThomasWaldmann** [comment]
It could be that the filesystem has problems in general, leading to repo corruption / strange behaviour.

**Comment by ThomasWaldmann** [comment]
Any news?
