### ISSUE TITLE
Borg Repair: Data integrity error: Invalid segment entry size - too big

### ISSUE THREAD

**Issue by starcraft66** [borgbackup/borg#5350]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes
## Is this a BUG / ISSUE report or a QUESTION?

BUG /ISSUE report
## System information. For client/server mode post info for both machines.

client: borg 1.1.13 on redhat 
server: borg 1.1.11

#### Your borg version (borg -V).

borg 1.1.11

#### Operating system (distribution) and version.

RHEL 7 on the client

Ubuntu 20.04 on the server

#### Hardware / network configuration, and filesystems used.

The backup repo is on an EXT4 hard drive

#### How much data is handled by borg?

~1.5TB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
borg check --repair
```

## Describe the problem you're observing.

While doing a nightly backup, I ran into the following error:

```
Remote: segment 855 not found, but listed in compaction data
Remote: segment 859 not found, but listed in compaction data
Data integrity error: Segment entry checksum mismatch [segment 896, offset 243873743]
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/borg/archiver.py", line 4565, in main
    exit_code = archiver.run(args)
  File "/usr/lib64/python3.6/site-packages/borg/archiver.py", line 4497, in run
    return set_ec(func(args))
  File "/usr/lib64/python3.6/site-packages/borg/archiver.py", line 176, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib64/python3.6/site-packages/borg/archiver.py", line 584, in do_create
    create_inner(archive, cache)
  File "/usr/lib64/python3.6/site-packages/borg/archiver.py", line 549, in create_inner
    archive.save(comment=args.comment, timestamp=args.timestamp)
  File "/usr/lib64/python3.6/site-packages/borg/archive.py", line 517, in save
    self.repository.commit()
  File "/usr/lib64/python3.6/site-packages/borg/remote.py", line 477, in do_rpc
    return self.call(f.__name__, named, **extra)
  File "/usr/lib64/python3.6/site-packages/borg/remote.py", line 712, in call
    for resp in self.call_many(cmd, [args], **kw):
  File "/usr/lib64/python3.6/site-packages/borg/remote.py", line 780, in call_many
    handle_error(unpacked)
  File "/usr/lib64/python3.6/site-packages/borg/remote.py", line 740, in handle_error
    raise IntegrityError(args[0].decode())
borg.helpers.IntegrityError: Data integrity error: Segment entry checksum mismatch [segment 896, offset 243873743]
```

This prompted me to run a `borg check` which found errors in the repo followed by a `borg check --repair`.

When running the repair, I got the stacktrace below.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes, it happens every time I try to back up.

#### Include any warning/errors/backtraces from the system logs

borg check:

```
ID: a3339ee847608c641947553f9b00edf0800a16aa7577f64c0544a8e6119ce50c rebuilt index: <not found>      committed index: (1652, 172215085)
ID: c4d70ed299ff2326aca303e2612ee24cb6c21db492d8ec2ddb2a549b6e61cffd rebuilt index: <not found>      committed index: (429, 312610491)
ID: 192803053d8a074aa0e2076b6651c5498709f2f98e3045ce048494951fa06fe3 rebuilt index: <not found>      committed index: (429, 386676356)
ID: fc341f2eea67b3b7e5d335528cee44e80eb6d320c1ccb88e46f557f896cdbee0 rebuilt index: <not found>      committed index: (429, 312718258)
ID: 93cfe18f75db212527a6bd2689112f650422f44a81ca016ddaf7bc2f52af2d41 rebuilt index: <not found>      committed index: (429, 312548773)
ID: 5af991d663775eebbf2f1f3e736ac5ee88c3d293bbd28a41fb4f56ed5cc23025 rebuilt index: <not found>      committed index: (332, 8)
ID: 2ff79ee924b0e1c7a728e0260c8021355879d4aeebe791b6a5d4615bcf4641c4 rebuilt index: <not found>      committed index: (429, 360218347)
ID: f60f87c6c4752d844a681c15e281bb463e28831bd335bc2a6f16b34e61c0ce7e rebuilt index: <not found>      committed index: (429, 300328789)
ID: 0f817db8c014ec680491457352deec3e79f8ad980a33765e21b4d221a2b59391 rebuilt index: <not found>      committed index: (429, 312708302)
ID: c745bc580050cd998a15e144b8164d1ea159ce13d7ade881c46495ac4b27a1ce rebuilt index: <not found>      committed index: (1652, 513126170)
ID: 460c080c5e29e39f08964102f6c2311f903a6c88ef24e5dcf0184febf027520f rebuilt index: <not found>      committed index: (429, 387543725)
ID: 992c17de44e4305bf7bde17036dd70f74507e4c389f40ee5fbf3866941b97efd rebuilt index: <not found>      committed index: (429, 351258409)
ID: 8c544a6d21a4f6a944f945786d6670de09076cbc57ce84db6da61737423d2609 rebuilt index: <not found>      committed index: (1652, 301765787)
ID: d9ac1e2d5efdfa9a85d7bea7307cea1b8fd5ea79ba3f9758de9441ea1573d1f0 rebuilt index: <not found>      committed index: (429, 307700599)
ID: b14b17de6840970c5ffdb96066f7588ad939a9888620af796fc00833c4678e0d rebuilt index: <not found>      committed index: (429, 300434743)
```

borg check --repair:

```
'check --repair' is an experimental feature that might result in data loss.
Type 'YES' if you understand this and want to continue: YES
Data integrity error: Segment entry checksum mismatch [segment 47, offset 68522067]
Data integrity error: Segment entry checksum mismatch [segment 298, offset 52155976]
Data integrity error: Segment entry checksum mismatch [segment 332, offset 124022343]
Data integrity error: Segment entry checksum mismatch [segment 411, offset 69912843]
Data integrity error: Segment entry checksum mismatch [segment 896, offset 243873743]
Data integrity error: Segment entry checksum mismatch [segment 1265, offset 460763770]
Data integrity error: Segment entry checksum mismatch [segment 1652, offset 168451229]
Data integrity error: Invalid segment entry size 706195599 - too big [segment 1207, offset 16203227]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4529, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4461, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 166, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 328, in do_check
    if not repository.check(repair=args.repair, save_space=args.save_space):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 964, in check
    self._update_index(segment, objects, report_error)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 870, in _update_index
    size = self.io.read(s, offset, key, read_data=False)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1470, in read
    size, tag, key, data = self._read(fd, self.put_header_fmt, header, segment, offset, (TAG_PUT, ), read_data)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1493, in _read
    raise IntegrityError('Invalid segment entry size {} - too big [segment {}, offset {}]'.format(
borg.helpers.IntegrityError: Data integrity error: Invalid segment entry size 706195599 - too big [segment 1207, offset 16203227]

Platform: Linux bunker 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64
Linux: Unknown Linux
Borg: 1.1.11  Python: CPython 3.8.2 msgpack: 0.5.6
PID: 188752  CWD: /var/backup
sys.argv: ['/usr/bin/borg', 'check', '--repair', 'Trixie']
SSH_ORIGINAL_COMMAND: None
```

**Comment by infectormp** [comment]
Check https://github.com/borgbackup/borg/issues/5181

**Comment by starcraft66** [comment]
Ok thanks, I just built 1.1.13 from source with pip because the ubuntu
package isn't up to date. I am running a new repair operation now.

-Tristan

**Comment by starcraft66** [comment]
I was able to repair the backup repository using borg 1.1.13!
