### ISSUE TITLE
borg check on smbfs crashes with errno 22 invalid argument

### ISSUE THREAD

**Issue by bardok** [borgbackup/borg#5423]
Hello,

Sorry for my english i'm french.

I have an error while i check my repository after the first create, i use Vorta gui.
This is my third repository on a NAS DNS-320 with alt-f, and it's the first time i want to use it.
I've got two other repository, one on my pc and one a smb share behind a raspberry with omv, no problem with them while one years.

Thanks for your help.
```
2020-10-15 19:14:30,406 - vorta.borg.borg_thread - INFO - Running command /usr/bin/borg check --info --log-json /run/user/1000/gvfs/smb-share:server=dns-320,share=users/Sauvegarde/Test3
2020-10-15 19:14:31,096 - vorta.borg.borg_thread - INFO - Starting repository check
2020-10-15 19:17:03,552 - vorta.borg.borg_thread - ERROR - Local Exception
2020-10-15 19:17:03,556 - vorta.borg.borg_thread - ERROR - Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/borg/archiver.py", line 4565, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.8/site-packages/borg/archiver.py", line 4497, in run
    return set_ec(func(args))
  File "/usr/lib/python3.8/site-packages/borg/archiver.py", line 176, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.8/site-packages/borg/archiver.py", line 338, in do_check
    if not repository.check(repair=args.repair, save_space=args.save_space):
  File "/usr/lib/python3.8/site-packages/borg/repository.py", line 971, in check
    objects = list(self.io.iter_objects(segment))
  File "/usr/lib/python3.8/site-packages/borg/repository.py", line 1420, in iter_objects
    size, tag, key, data = self._read(fd, self.header_fmt, header, segment, offset,
  File "/usr/lib/python3.8/site-packages/borg/repository.py", line 1514, in _read
    data = fd.read(length)
OSError: [Errno 22] Invalid argument

Platform: Linux Gustave 5.8.11-1-MANJARO #1 SMP PREEMPT Wed Sep 23 14:35:40 UTC 2020 x86_64
Linux: Unknown Linux  
Borg: 1.1.13  Python: CPython 3.8.5 msgpack: 0.5.6
PID: 65762  CWD: /home/chris
sys.argv: ['/usr/bin/borg', 'check', '--info', '--log-json', '/run/user/1000/gvfs/smb-share:server=dns-320,share=users/Sauvegarde/Test3']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment]
I suspect that this issue has its cause in smbfs.

The place where it is crashing is just a normal read command, so not sure what could be "invalid" there...

There are some other issues open/closed on this issue tracker with people having smbfs / cifs problems, maybe check if you can find some hints there.

**Comment by ThomasWaldmann** [comment]
did you find out anything you could add here?
