### ISSUE TITLE
reopen #4112 - UnicodeEncodeError: 'ascii' codec can't encode character '\xe0' in position 44: ordinal not in range(128)

### ISSUE THREAD

**Issue by roseswe** [borgbackup/borg#5460]
$ borg mount -f $PWD ~/drv/mnt/
Local Exception
Traceback (most recent call last):
  File "borg/archiver.py", line 4591, in main
  File "borg/archiver.py", line 4523, in run
  File "borg/archiver.py", line 1399, in do_mount
  File "borg/archiver.py", line 176, in wrapper
  File "borg/archiver.py", line 1409, in _do_mount
  File "borg/fuse.py", line 364, in mount
  File "borg/fuse.py", line 38, in fuse_main
  File "src/fuse_api.pxi", line 330, in llfuse.main
  File "src/handlers.pxi", line 39, in llfuse.fuse_lookup
  File "src/handlers.pxi", line 40, in llfuse.fuse_lookup
  File "borg/fuse.py", line 594, in lookup
  File "borg/fuse.py", line 591, in _load_pending_archive
  File "borg/fuse.py", line 404, in process_archive
  File "os.py", line 862, in fsencode
UnicodeEncodeError: 'ascii' codec can't encode character '\xe0' in position 44: ordinal not in range(128)

Platform: Linux p5520 4.12.14-lp151.28.75-default #1 SMP Thu Oct 15 12:09:20 UTC 2020 (3577f5a) x86_64
Linux:   
Borg: 1.1.14  Python: CPython 3.5.10 msgpack: 0.5.6
PID: 28628  CWD: /home/ralph/drv/borg
sys.argv: ['borg', 'mount', '-f', '/home/ralph/drv/borg', '/home/ralph/drv/mnt/']
SSH_ORIGINAL_COMMAND: None

$ lsb_release -a
LSB Version:	core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-x86_64:core-3.2-x86_64:core-4.0-x86_64:desktop-4.0-amd64:desktop-4.0-noarch:graphics-2.0-amd64:graphics-2.0-noarch:graphics-3.2-amd64:graphics-3.2-noarch:graphics-4.0-amd64:graphics-4.0-noarch
Distributor ID:	openSUSE
Description:	openSUSE Leap 15.1
Release:	15.1
Codename:	n/a

$ uname -a
Linux p5520 4.12.14-lp151.28.75-default #1 SMP Thu Oct 15 12:09:20 UTC 2020 (3577f5a) x86_64 x86_64 x86_64 GNU/Linux

**Comment by roseswe** [comment]
A workaround that works for me is:
    $ export LC_ALL=de_DE.UTF-8
then do the mount

**Comment by infectormp** [comment]
https://borgbackup.readthedocs.io/en/stable/faq.html#if-it-crashes-with-a-unicodeerror-what-can-i-do

**Comment by ThomasWaldmann** [comment]
Documented / known / not a borg issue.

If you want to deal with non-ascii file names, you need to configure your OS (your locale) for that.
