### ISSUE TITLE
Traceback when borg is not installed on remote machine

### ISSUE THREAD

**Issue by rumpelsepp** [borgbackup/borg#56]
I tried to init a borg repo via ssh on a remote machine. I forgot to install borg there; the command failed with a traceback. An error message would be prettier:

```
zsh:1: command not found: borg
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/borg/archiver.py", line 857, in main
    exit_code = archiver.run(sys.argv[1:])
  File "/usr/lib/python3.4/site-packages/borg/archiver.py", line 813, in run
    return args.func(args)
  File "/usr/lib/python3.4/site-packages/borg/archiver.py", line 62, in do_init
    repository = self.open_repository(args.repository, create=True, exclusive=True)
  File "/usr/lib/python3.4/site-packages/borg/archiver.py", line 35, in open_repository
    repository = RemoteRepository(location, create=create)
  File "/usr/lib/python3.4/site-packages/borg/remote.py", line 144, in __init__
    version = self.call('negotiate', 1)
  File "/usr/lib/python3.4/site-packages/borg/remote.py", line 153, in call
    for resp in self.call_many(cmd, [args], **kw):
  File "/usr/lib/python3.4/site-packages/borg/remote.py", line 203, in call_many
    raise ConnectionClosed()
borg.remote.ConnectionClosed
borg: Error: Connection closed by remote host
```

**Comment by ThomasWaldmann** [comment]
fixed by 2743ab1593e919291fd40bff187e4a6980b0535c
