### ISSUE TITLE
better logging for borg check

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5601]
even with `--debug`, it did not show the current segment file name:

```
dietmar@haubenpinguin:~$ borg-1.2 check --debug -v -p zwergpinguin-test:borg12test
Remote: Starting repository check
Traceback (most recent call last):
  File "borg/remote.py", line 239, in serve
  File "borg/repository.py", line 1008, in check
  File "borg/repository.py", line 1470, in iter_objects
  File "borg/repository.py", line 1560, in _read
OSError: [Errno 5] Input/output error
```

**Comment by ThomasWaldmann** [comment]
note: there is already `--progress` for this, to see some progress indication (but that does not include the segment filename).

i now added debug log output indicating the segment filename before that file is checked.
