### ISSUE TITLE
backup aborted KeyError

### ISSUE THREAD

**Issue by thob** [borgbackup/borg#5613]
## Is this a BUG / ISSUE report or a QUESTION?

Error, issue

#### Your borg version
borg 1.1.9

#### Operating system (distribution) and version.
Debian 10.7

#### Hardware / network configuration, and filesystems used.
Linux OSMC 3.14.29-160-osmc aarch64

#### How much data is handled by borg?
50GB (in theory), this is the 1st attempt

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borgmatic with the default settings

## Describe the problem you're observing.

```Traceback (most recent call last):

  File "/opt/venvs/borg-LATEST/lib/python3.6/site-packages/borg/repository.py", line 1361, in get_fd
    ts, fd = self.fds[segment]

  File "/opt/venvs/borg-LATEST/lib/python3.6/site-packages/borg/lrucache.py", line 21, in __getitem__
    value = self._cache[key]  # raise KeyError if not found

KeyError: 44


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/opt/venvs/borg-LATEST/lib/python3.6/site-packages/borg/remote.py", line 247, in serve
    res = f(**args)

  File "/opt/venvs/borg-LATEST/lib/python3.6/site-packages/borg/repository.py", line 1139, in put
    size = self.io.read(segment, offset, id, read_data=False)

  File "/opt/venvs/borg-LATEST/lib/python3.6/site-packages/borg/repository.py", line 1479, in read
    fd = self.get_fd(segment)

  File "/opt/venvs/borg-LATEST/lib/python3.6/site-packages/borg/repository.py", line 1363, in get_fd
    fd = open_fd()

  File "/opt/venvs/borg-LATEST/lib/python3.6/site-packages/borg/repository.py", line 1344, in open_fd
    fd = open(self.segment_filename(segment), 'rb')

FileNotFoundError: [Errno 2] No such file or directory: '/srv/repos/xxxxxxx/repo/data/0/44'

Borg server: Platform: Linux box-eu4 4.18.0-147.3.1.el8_1.x86_64 #1 SMP Fri Jan 3 23:55:26 UTC 2020 x86_64
Borg server: Linux: CentOS Linux 8.1.1911 Core
Borg server: Borg: 1.1.14  Python: CPython 3.6.8 msgpack: 0.5.6
Borg server: PID: 8505  CWD: /srv/repos/xxxxxxx
Borg server: sys.argv: ['/opt/venvs/borg-LATEST/bin/borg', 'serve', '--restrict-to-repository', '/srv/repos/xxxxxxx/repo', '--storage-quota', '60000M']
Borg server: SSH_ORIGINAL_COMMAND: 'borg serve --umask=077'
Platform: Linux osmc 3.14.29-160-osmc #1 SMP Sun Sep 13 13:55:21 UTC 2020 aarch64
Linux: debian 10.7 
Borg: 1.1.9  Python: CPython 3.7.3
PID: 8798  CWD: /media/xxxxIBA EXT/Videos
sys.argv: ['/usr/bin/borg', 'create', 'xxxxxxx@xxxxxxx.repo.borgbase.com:repo::{hostname}-{now}', '/media/xxxxIBA EXT/Fotos', '/media/xxxxIBA EXT/Videos', '--exclude-from', '/tmp/tmp1lw2zlni', '--exclude-caches', '--exclude-if-present', '.nobackup', '--compression', 'auto,zstd', '--one-file-system']
SSH_ORIGINAL_COMMAND: None

Command '('borg', 'create', 'xxxxxxx@xxxxxxx.repo.borgbase.com:repo::{hostname}-{now}', '/media/xxxxIBA EXT/Fotos', '/media/xxxxIBA EXT/Videos', '--exclude-from', '/tmp/tmp1lw2zlni', '--exclude-caches', '--exclude-if-present', '.nobackup', '--compression', 'auto,zstd', '--one-file-system')' returned non-zero exit status 2.```

**Comment by ThomasWaldmann** [comment]
You need to use a more recent borg version, 1.1.9 has known and severe bugs, see the changelog and the advisory at the top of the changelog.

**Comment by ThomasWaldmann** [comment]
In debian, see backports, for ubuntu see the maintainer ppa.

**Comment by thob** [comment]
I upgrade to the latest via backports but still get

```
Do 7. Jan 10:08:14 CET 2021 - Starting backup
Data integrity error: Invalid segment entry header [segment 48, offset 373063990]: unpack requires a buffer of 41 bytes
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4591, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4523, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 163, in wrapper
    kwargs['manifest'], kwargs['key'] = Manifest.load(repository, compatibility)
  File "/usr/lib/python3/dist-packages/borg/helpers.py", line 373, in load
    cdata = repository.get(cls.MANIFEST_ID)
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 933, in get
    for resp in self.get_many([id]):
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 937, in get_many
    for resp in self.call_many('get', [{'id': id} for id in ids], is_preloaded=is_preloaded):
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 780, in call_many
    handle_error(unpacked)
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 740, in handle_error
    raise IntegrityError(args[0].decode())
borg.helpers.IntegrityError: Data integrity error: Invalid segment entry header [segment 48, offset 373063990]: unpack requires a buffer of 41 bytes

Platform: Linux osmc 3.14.29-160-osmc #1 SMP Sun Sep 13 13:55:21 UTC 2020 aarch64
Linux: debian 10.7 
Borg: 1.1.14  Python: CPython 3.7.3 msgpack: 0.5.6
PID: 7109  CWD: /home/osmc
sys.argv: ['/usr/bin/borg', 'prune', 'xxxx@xxxxx.repo.borgbase.com:repo', '--keep-daily', '3', '--keep-weekly', '4', '--keep-monthly', '12', '--keep-yearly', '2', '--prefix', '{hostname}-']
SSH_ORIGINAL_COMMAND: None

Command '('borg', 'prune', 'xxxx@xxxxx.repo.borgbase.com:repo', '--keep-daily', '3', '--keep-weekly', '4', '--keep-monthly', '12', '--keep-yearly', '2', '--prefix', '{hostname}-')' returned non-zero exit status 2.

Need some help? https://torsion.org/borgmatic/#issues
```
Should I just init a new repo or is this something bigger

**Comment by ThomasWaldmann** [comment]
You need to run borg check correctly. See the advisory at the top of the changelog.

The label does not matter.

**Comment by thob** [comment]
OK, I did check an got back a very long list of ID lines
```
Remote: Index object count mismatch.
Remote: committed index: 6208 objects
Remote: rebuilt index:   6030 objects
Remote: ID: 0000000000000000000000000000000000000000000000000000000000000000 rebuilt index: (38, 460111692)  committed index: (48, 373063990) 
```
What does this mean?

--
I also created and init a new repo which works fine up to now.

**Comment by ThomasWaldmann** [comment]
did you read the advisory?

**Comment by ThomasWaldmann** [comment]
https://borgbackup.readthedocs.io/en/stable/changes.html#pre-1-1-11-potential-index-corruption-data-loss-issue

**Comment by thob** [comment]
Thanks for the pointer, not sure I'm able to follow but I'll try
