### ISSUE TITLE
Exception after updating python

### ISSUE THREAD

**Issue by akyag** [borgbackup/borg#5667]
Python was recently updated I think to 3.9 I was today just checking my backups and saw this exception occur. happens on every repo - 
```
borg list ./photos
Exception ignored in: <function Repository.__del__ at 0x7f594f52ca60>
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/borg/repository.py", line 180, in __del__
    assert False, "cleanup happened in Repository.__del__"
AssertionError: cleanup happened in Repository.__del__
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/borg/archiver.py", line 4591, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.9/site-packages/borg/archiver.py", line 4523, in run
    return set_ec(func(args))
  File "/usr/lib/python3.9/site-packages/borg/archiver.py", line 161, in wrapper
    with repository:
  File "/usr/lib/python3.9/site-packages/borg/repository.py", line 190, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/usr/lib/python3.9/site-packages/borg/repository.py", line 427, in open
    self.config.read_file(fd)
  File "/usr/lib/python3.9/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/lib/python3.9/configparser.py", line 1017, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb9 in position 3: invalid start byte

Platform: Linux quady 5.10.7-3-MANJARO #1 SMP PREEMPT Fri Jan 15 21:11:34 UTC 2021 x86_64
Linux: Unknown Linux  
Borg: 1.1.14  Python: CPython 3.9.1 msgpack: 0.5.6
PID: 103619  CWD: /run/media/akya/backup/backup
sys.argv: ['/usr/bin/borg', 'list', './photos']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment]
That doesn't look like python related, but there is an invalid byte 0xb9 in your repo config (see `repo_directory/config`).

**Comment by akyag** [comment]
my bad. I mixed up restic repo with borg. All good now. Really sorry for the trouble...
