### ISSUE TITLE
dry-run fail with --keep-tag-files

### ISSUE THREAD

**Issue by infectormp** [borgbackup/borg#570]
Hello.

I run command: 
```borg create -n -s -v -C lz4 --exclude-if-present debug.txt --keep-tag-files --exclude-caches /backup/site.repo::site.(date +%d-%m-%Y_%H-%M-%S) /xxx/site```

and get error: 
```
/bin/sh: symbol lookup error: /bin/sh: undefined symbol: rl_signal_event_hook
Local Exception.
Traceback (most recent call last):
  File "/vagrant/borg/borg/borg/archiver.py", line 1261, in main
  File "/vagrant/borg/borg/borg/archiver.py", line 1215, in run
  File "/vagrant/borg/borg/borg/archiver.py", line 183, in do_create
  File "/vagrant/borg/borg/borg/archiver.py", line 247, in _process
  File "/vagrant/borg/borg/borg/archiver.py", line 247, in _process
  File "/vagrant/borg/borg/borg/archiver.py", line 247, in _process
  File "/vagrant/borg/borg/borg/archiver.py", line 229, in _process
AttributeError: 'NoneType' object has no attribute 'process_dir'

Platform: Linux www 4.4.0-gentoo #4 SMP Fri Jan 15 00:21:41 MSK 2016 x86_64
Linux: Gentoo Base System 2.2   LibC: glibc 2.3
Python: CPython 3.5.1
```
borg 0.29.0

dry-run work as expected if run command without --keep-tag-files

**Comment by ThomasWaldmann** [comment]
thanks for reporting, I'll have a look.
