### ISSUE TITLE
Any borg command on ssh repo just hangs.

### ISSUE THREAD

**Issue by simolev** [borgbackup/borg#5754]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes, found similar issues but they that were solved by removing locks and clearing cache.

## Is this a BUG / ISSUE report or a QUESTION?

BUG / ISSUE report.

#### Your borg version (borg -V).
    borg 1.1.15
#### Operating system (distribution) and version.
    Ubuntu 20.04.2 LTS
#### Hardware / network configuration, and filesystems used.
VMware virtual machines in two different datacenters, Ext4
#### How much data is handled by borg?
```
                       Original size      Compressed size    Deduplicated size
All archives:                5.29 TB              4.67 TB            406.86 GB
```
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
    borg list

## Describe the problem you're observing.
Ran backups with `borg` for three weeks. Since March 23rd any borg command just hangs, and timeouts in two hours.

```
$ time borg --debug list
using builtin fallback logging configuration
35 self tests completed in 0.11 seconds
SSH command line: ['ssh', '-i', '/path/to/ssh/key', 'user@server', 'borg', 'serve', '--umask=077', '--debug']
Remote: using builtin fallback logging configuration
Remote: 35 self tests completed in 0.09 seconds
Remote: using builtin fallback logging configuration
Remote: Initialized logging system for JSON-based protocol
Remote: Resolving repository path b'/path/to/repo'
Remote: Resolved repository path to '/path/to/repo'
Remote: Verified integrity of /path/to/repo/index.1386
Remote: client_loop: send disconnect: Broken pipe
RemoteRepository: 192 B bytes sent, 1.06 kB bytes received, 3 messages sent
Connection closed by remote host
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 164, in wrapper
    kwargs['manifest'], kwargs['key'] = Manifest.load(repository, compatibility)
  File "/usr/lib/python3/dist-packages/borg/helpers.py", line 374, in load
    cdata = repository.get(cls.MANIFEST_ID)
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 933, in get
    for resp in self.get_many([id]):
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 937, in get_many
    for resp in self.call_many('get', [{'id': id} for id in ids], is_preloaded=is_preloaded):
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 814, in call_many
    raise ConnectionClosed()
borg.remote.ConnectionClosed: Connection closed by remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4621, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4553, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 177, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 634, in __exit__
    self.rollback()
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 477, in do_rpc
    return self.call(f.__name__, named, **extra)
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 712, in call
    for resp in self.call_many(cmd, [args], **kw):
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 814, in call_many
    raise ConnectionClosed()
borg.remote.ConnectionClosed: Connection closed by remote host

Platform: Linux hostname 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64
Linux: Unknown Linux
Borg: 1.1.15  Python: CPython 3.8.5 msgpack: 0.5.6
PID: 7685  CWD: /tmp
sys.argv: ['/usr/bin/borg', '--debug', 'list']
SSH_ORIGINAL_COMMAND: None


real    121m15.436s
user    0m0.608s
sys     0m0.249s
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
These actions didn't change the outcome:
* Running `borg break-lock` on the client.
* Running `borg delete --cache-only` on the client.
* Employing the standalone 1.1.16 binary on the client.
* Employing the standalone 1.1.16 binary on the server.
* Deleting `/home/user/.cache/borg` and `/home/user/.config/borg` on the client.
* Running the `borg 1.1.15` client from a FreeBSD 12.2 VM on the same VMware cluster and network.
* Running the `borg 1.1.15` client from a different Ubuntu 20.04 VM on the same VMware cluster and network.

These scenarios worked:
* Running the `borg 1.1.15` client from the server, pointing to the repository both via local filesystem and via ssh.
* Running the `borg 1.1.15` client from inside a WSL Ubuntu 20.04 environment on a physical Windows 10 workstation, in the same datacenter and network as the original client.
* Running the `borg 1.1.15` client from a different Ubuntu 20.04 VM on the same VMware cluster and network as the **server**.

#### Include any warning/errors/backtraces from the system logs

* This is `/path/to/repo/` on the server:
```
drwxrwxr-x+ 3 user user 4.0K Apr  6 18:53 .
drwxrwxr-x+ 5 root root 4.0K Apr  6 15:58 ..
drwxrwxr-x+ 4 user user 4.0K Mar 12 11:28 data
-rw-rw-r--+ 1 user user   73 Mar  2 16:06 README
-rw-rw-r--+ 1 user user  964 Mar  2 16:06 config
-rw-rw-r--+ 1 user user 4.0K Mar 23 02:04 hints.1386
-rw-rw-r--+ 1 user user  18M Mar 23 02:04 index.1386
-rw-rw-r--+ 1 user user  190 Mar 23 02:04 integrity.1386
-rw-rw-r--+ 1 user user   16 Mar 23 02:04 nonce
```

* `tcpdump` detects some traffic when the command is run, then nothing else.
* While the command is running, and appears to hang, the server shows this process:
```
user      5521  5.4  4.9  67564 47900 ?        Ss   22:06   0:00 /usr/bin/python3 /usr/bin/borg serve --umask=077
```
* SSH between the client and the server seems to work flawlessly.
* Network speed between the datacenters is 1Gbps, performance is good and has been tested with `iperf3` at different hours.
* `ping` from client to server is `rtt min/avg/max/mdev = 1.085/1.349/4.492/0.579 ms`.

**Comment by simolev** [comment]
This is the first time I use borg at work, in production. I've been advocating borg over alternative backup solutions, and my main goal here is understanding whether it is indeed a good fit for this scenario. Maybe I'm just doing something wrong or have failed to grasp its workings and requirements. Possibly, I aim to learn something in the process.

**Comment by infectormp** [comment]
Did you check these issues?
https://github.com/borgbackup/borg/issues?q=is%3Aissue+is%3Aopen+Connection+closed+by+remote+host

**Comment by simolev** [comment]
Might just be a network issue, will close for now.
