### ISSUE TITLE
upgrade fails without ~/.attic/keys

### ISSUE THREAD

**Issue by Profpatsch** [borgbackup/borg#576]
I moved to a new system, but wish to upgrade an old attic repository on an external drive; I don’t have any keys in `~/.attic/keys`, so borg throws:

```
Local Exception.
Traceback (most recent call last):
  File "/nix/store/2smxfpi0kiz5lqzy3j6pqkvpkwhmxmf8-borgbackup-0.29.0/lib/python3.4/site-packages/borg/archiver.py", line 1261, in main
    exit_code = archiver.run(args)
  File "/nix/store/2smxfpi0kiz5lqzy3j6pqkvpkwhmxmf8-borgbackup-0.29.0/lib/python3.4/site-packages/borg/archiver.py", line 1215, in run
    return args.func(args)
  File "/nix/store/2smxfpi0kiz5lqzy3j6pqkvpkwhmxmf8-borgbackup-0.29.0/lib/python3.4/site-packages/borg/archiver.py", line 515, in do_upgrade
    repo.upgrade(args.dry_run, inplace=args.inplace)
  File "/nix/store/2smxfpi0kiz5lqzy3j6pqkvpkwhmxmf8-borgbackup-0.29.0/lib/python3.4/site-packages/borg/upgrader.py", line 45, in upgrade
    keyfile = self.find_attic_keyfile()
  File "/nix/store/2smxfpi0kiz5lqzy3j6pqkvpkwhmxmf8-borgbackup-0.29.0/lib/python3.4/site-packages/borg/upgrader.py", line 128, in find_attic_keyfile
    return AtticKeyfileKey.find_key_file(self)
  File "/nix/store/2smxfpi0kiz5lqzy3j6pqkvpkwhmxmf8-borgbackup-0.29.0/lib/python3.4/site-packages/borg/upgrader.py", line 268, in find_key_file
    for name in os.listdir(keys_dir):
FileNotFoundError: [Errno 2] No such file or directory: '/home/philip/.attic/keys'

Platform: Linux katara 4.1.13 #1-NixOS SMP Thu Jan 1 00:00:01 UTC 1970 x86_64 
Linux:     LibC: glibc 2.2.5
Python: CPython 3.4.4
```

Update: It’s actually pretty minor, since it will work with an empty `~/.attic/keys`.

**Comment by ThomasWaldmann** [comment]
yeah, but it shouldn't blow up without the dir.
