### ISSUE TITLE
create throws exception "No module named '_strptime'"

### ISSUE THREAD

**Issue by philipkozeny** [borgbackup/borg#5794]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug

#### Your borg version (borg -V).

1.1.16

#### Operating system (distribution) and version.

macOS 11.3.1 (20E241)

#### Hardware / network configuration, and filesystems used.

* MacBook Pro with Intel, Backup to LimaLabs (which has some issues right now, could be related)
* Using Vorta (0.7.5) with borg installed via homebrew

#### How much data is handled by borg?

Original Size: 58.6 TB
Deduplicated Size: 1.1 TB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
sys.argv: ['/usr/local/bin/borg', 'create', '--remote-path=/home/xyz/borg', '--list', '--progress', '--info', '--log-json', '--json', '--filter=AM', '-C', 'zstd,8', 'xyz@scpuk1.cdn.lima-labs.com:mbp/repo::xyz-macbook-pro-2021-05-06T08:00:00', ....]
```

## Describe the problem you're observing.

```create``` threw a local exception 

```
2021-05-06 09:10:27,508 - vorta.borg.borg_thread - ERROR - Local Exception
2021-05-06 09:10:27,510 - vorta.borg.borg_thread - ERROR - Traceback (most recent call last):
  File "/usr/local/Cellar/borgbackup/1.1.16/libexec/lib/python3.9/site-packages/borg/archiver.py", line 4690, in main
    exit_code = archiver.run(args)
  File "/usr/local/Cellar/borgbackup/1.1.16/libexec/lib/python3.9/site-packages/borg/archiver.py", line 4622, in run
    return set_ec(func(args))
  File "/usr/local/Cellar/borgbackup/1.1.16/libexec/lib/python3.9/site-packages/borg/archiver.py", line 177, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/local/Cellar/borgbackup/1.1.16/libexec/lib/python3.9/site-packages/borg/archiver.py", line 595, in do_create
    create_inner(archive, cache)
  File "/usr/local/Cellar/borgbackup/1.1.16/libexec/lib/python3.9/site-packages/borg/archiver.py", line 560, in create_inner
    archive.save(comment=args.comment, timestamp=args.timestamp)
  File "/usr/local/Cellar/borgbackup/1.1.16/libexec/lib/python3.9/site-packages/borg/archive.py", line 529, in save
    self.manifest.write()
  File "/usr/local/Cellar/borgbackup/1.1.16/libexec/lib/python3.9/site-packages/borg/helpers.py", line 442, in write
    prev_ts = self.last_timestamp
  File "/usr/local/Cellar/borgbackup/1.1.16/libexec/lib/python3.9/site-packages/borg/helpers.py", line 370, in last_timestamp
    return parse_timestamp(self.timestamp, tzinfo=None)
  File "/usr/local/Cellar/borgbackup/1.1.16/libexec/lib/python3.9/site-packages/borg/helpers.py", line 602, in parse_timestamp
    dt = datetime.strptime(timestamp, fmt)
ModuleNotFoundError: No module named '_strptime'

Platform: Darwin Philips-MacBook-Pro.local 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64
Borg: 1.1.16  Python: CPython 3.9.4 msgpack: 0.5.6.+borg1
PID: 18103  CWD: /
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Was not able to reproduce it until now

#### Include any warning/errors/backtraces from the system logs

**Comment by RonnyPfannschmidt** [comment]
at first glance this looks like a broken python build, python should have a `_strptime` module - so its down to homebrew

**Comment by ThomasWaldmann** [comment]
BTW, python 3.9.5 is out, guess it will land in homebrew soon.

**Comment by philipkozeny** [comment]
I am running python 3.9.5 now, but even with 3.9.4 I was not able to reproduce it. Any specifics how I could try to trigger the module call from borg?

**Comment by teemue** [comment]
Any updates?

**Comment by ThomasWaldmann** [comment]
@teemue i don't think this is a borg issue.

so, if you see this, it is likely that you have a broken python installation, so try updating your python or, if that is the latest, talk to whoever made that python package.

**Comment by ThomasWaldmann** [comment]
guess i'll close this. if someone has evidence this is somehow related to borg, please add it / reopen.
