### ISSUE TITLE
docs: Advisory when running borg within a Docker container

### ISSUE THREAD

**Issue by thannaske** [borgbackup/borg#5818]
There are multiple issues here on GitHub regarding a closed connection by the remote host when running borg against a remote repository. I'm running borg within a Docker container and faced this issue as well, however my problem could not be fixed by any solutions that have been brought up in those issues.

```	
"$DOCKER_BIN" run --rm -i \
-v "$SSH_KEY_PATH":/ssh/id_rsa:ro \
-v ~/.cache/borg:/root/.cache/borg \
-v ~/.config/borg:/root/.config/borg \
-e BORG_RSH="ssh -vvv -i /ssh/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ServerAliveInterval=10 -o ServerAliveCountMax=30 -o TCPKeepAlive=yes" \
-e BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK=yes \
-e BORG_PASSPHRASE="$BACKUP_PASSPHRASE" \
ghcr.io/rescaled/borg:latest \
prune \
--debug \
--list \
--keep-hourly 24 \
--keep-daily 31 \
--keep-monthly 12 \
--keep-yearly 10 \
"$BORG_REPOSITORY"
```

A typical error in this scenario looks like this (The SSH agent is put into verbose mode, that's why you can see the keepalive packages (packet type 80) in the log):

```
TAM-verified manifest
security: read previous location 'ssh://redacted@redacted.your-storagebox.de:23/./repository'
security: read manifest timestamp '2021-05-30T10:18:31.381434'
security: determined newest manifest timestamp as 2021-05-30T10:18:31.381434
security: repository checks ok, allowing access
Verified integrity of /root/.cache/borg/c53bcfe4134906b3617388eab89040671272680f4a0aa2f0c5a4eead32f88616/chunks
security: read previous location 'ssh://redacted@redacted.your-storagebox.de:23/./repository'
security: read manifest timestamp '2021-05-30T10:18:31.381434'
security: determined newest manifest timestamp as 2021-05-30T10:18:31.381434
security: repository checks ok, allowing access
Keeping archive: 2021-05-30_10:18:29                  Sun, 2021-05-30 10:18:31 [7ad1e849ec1c987ff2355ff1b407f097eb09ae393eb955a405217ae971b4a3ba]
Pruning archive: 2021-05-30_10:12:36                  Sun, 2021-05-30 10:12:38 [9c31d7a9e736983ca3fdfcb55e1a4c707cfae039c24308943b7a2156b87729da] (1/3)
Remote: debug3: send packet: type 80
Remote: debug3: send packet: type 80
Remote: debug3: send packet: type 80
Remote: debug3: send packet: type 80
Remote: debug3: send packet: type 80
Remote: debug3: send packet: type 80
Remote: debug3: send packet: type 80
Remote: debug3: send packet: type 80
Remote: debug3: send packet: type 80
Remote: debug3: send packet: type 80
Remote: debug3: send packet: type 80
Remote: debug3: send packet: type 80
Remote: debug3: send packet: type 80
Remote: debug3: send packet: type 80
Remote: debug3: send packet: type 80
RemoteRepository: 321 B bytes sent, 11.43 kB bytes received, 7 messages sent
Connection closed by remote host
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 154, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1592, in do_prune
    Archive(repository, key, manifest, archive.name, cache).delete(stats, forced=args.forced)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 804, in delete
    for (i, (items_id, data)) in enumerate(zip(items_ids, self.repository.get_many(items_ids))):
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 938, in get_many
    for resp in self.call_many('get', [{'id': id} for id in ids], is_preloaded=is_preloaded):
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 815, in call_many
    raise ConnectionClosed()
borg.remote.ConnectionClosed: Connection closed by remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4455, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4387, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 154, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 635, in __exit__
    self.rollback()
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 478, in do_rpc
    return self.call(f.__name__, named, **extra)
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 713, in call
    for resp in self.call_many(cmd, [args], **kw):
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 815, in call_many
    raise ConnectionClosed()
borg.remote.ConnectionClosed: Connection closed by remote host

Platform: Linux 6b234ca8b5ff 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64
Linux: debian 10.9 
Borg: 1.1.9  Python: CPython 3.7.3
PID: 1  CWD: /
sys.argv: ['/usr/bin/borg', 'prune', '--debug', '--list', '--keep-hourly', '24', '--keep-daily', '31', '--keep-monthly', '12', '--keep-yearly', '10', 'ssh://redacted@redacted.your-storagebox.de:23/./repository']
SSH_ORIGINAL_COMMAND: None
```

This issue is indeed **no borg issue** at all. After looking through virtually every issue I could find in this GitHub repository I had an idea that may be worth adding to the documentation.

The connectivity problems when running borg within Docker are most likely caused by Docker's networking layer.

**Adding `--network host` to the Docker command line resolves this issue.** 

Maybe someone has a similar issue and can benefit from this advise, maybe it's worth adding it to the documentation.

**Comment by ThomasWaldmann** [comment]
Considering borgmatic already provides a docker container and I personally do not use docker at all, guess it is better if borgmatic deals with docker issues.
