### ISSUE TITLE
Getting KeyError when I try to use `borg list` with any `--format` option

### ISSUE THREAD

**Issue by ckp95** [borgbackup/borg#5833]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug

#### Your borg version (borg -V).

`borg 1.1.15`

#### Operating system (distribution) and version.

Ubuntu 20.04.2 LTS

#### Hardware / network configuration, and filesystems used.

Lenovo ThinkCentre, using 6tb external HDD, ext4.

#### How much data is handled by borg?

About 150 GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
borg list backups --format="{mode} {user:6} {group:6} {size:8d} {isomtime} {path}{extra}{NEWLINE}"
```

## Describe the problem you're observing.

Never used borg before. I SSHed into my home server, installed borg, and set up a new repository named `backups` and created a single archive named `initial` of about 150 GB. Seemed to work okay. I wanted to check the actual size borg reported just in case. I used the [command in the documentation for `borg list`](https://borgbackup.readthedocs.io/en/stable/usage/list.html). It prompts me for my repo password, which I enter. Then it gives a traceback rather than the expected output.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Using even a single formatting option breaks it:

```
borg list backups --format="{size}"
```

It works when I don't use `--format`:

```
$ borg list backups
Enter passphrase for key /home/cameron/6tb/backups: 
initial                              Mon, 2021-06-14 19:07:10 [817c16cfbc531b884d882b7831285393d464befdf524baa31d3873dc8fd70b55]
```

However this output does not match the stated default formatting of `{mode} {user:6} {group:6} {size:8d} {mtime} {path}{extra}{NL}”` in the docs.

I am able to mount the repository and look around at the files inside it, so the repository itself does not seem to be corrupted.

#### Include any warning/errors/backtraces from the system logs

```
$ borg list backups --format="{mode} {user:6} {group:6} {size:8d} {isomtime} {path}{extra}{NEWLINE}"
Enter passphrase for key /home/cameron/6tb/backups: 
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4621, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4553, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 177, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1437, in do_list
    return self._list_repository(args, repository, manifest, key)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1480, in _list_repository
    sys.stdout.write(formatter.format_item(archive_info))
  File "/usr/lib/python3/dist-packages/borg/helpers.py", line 1744, in format_item
    return self.format.format_map(self.get_item_data(item))
KeyError: 'mode'

Platform: Linux cameron-homeserver 5.8.0-55-generic #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021 x86_64
Linux: Unknown Linux  
Borg: 1.1.15  Python: CPython 3.8.5 msgpack: 0.5.6
PID: 4379  CWD: /home/cameron/6tb
sys.argv: ['/usr/bin/borg', 'list', 'backups', '--format={mode} {user:6} {group:6} {size:8d} {isomtime} {path}{extra}{NEWLINE}']
SSH_ORIGINAL_COMMAND: None
```

```
$ borg list backups --format="{size}"
Enter passphrase for key /home/cameron/6tb/backups: 
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4621, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4553, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 177, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1437, in do_list
    return self._list_repository(args, repository, manifest, key)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1480, in _list_repository
    sys.stdout.write(formatter.format_item(archive_info))
  File "/usr/lib/python3/dist-packages/borg/helpers.py", line 1744, in format_item
    return self.format.format_map(self.get_item_data(item))
KeyError: 'size'

Platform: Linux cameron-homeserver 5.8.0-55-generic #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021 x86_64
Linux: Unknown Linux  
Borg: 1.1.15  Python: CPython 3.8.5 msgpack: 0.5.6
PID: 4389  CWD: /home/cameron/6tb
sys.argv: ['/usr/bin/borg', 'list', 'backups', '--format={size}']
SSH_ORIGINAL_COMMAND: None

```

**Comment by ckp95** [comment]
Nevermind, I misread the documentation and didn't realize `list` was for archvies, not repositories. I needed to use `borg info backups`.
