### ISSUE TITLE
ubuntu 21.04, ubuntu 21 and ubuntu 20.10 crashing

### ISSUE THREAD

**Issue by GameTec-live** [borgbackup/borg#5934]
## Have you checked borgbackup docs, FAQ, and open Github issues?

yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

## System information. For client/server mode post info for both machines.
```
server:
            .-/+oossssoo+/-.               server@homserver
        `:+ssssssssssssssssss+:`           ----------------
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 20.04.2 LTS x86_64
    .ossssssssssssssssssdMMMNysssso.       Host: ProLiant DL120 G6
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.4.0-77-generic
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 3 hours, 25 mins
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 953 (dpkg), 4 (snap)
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.0.17
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1024x768
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Terminal: /dev/pts/0
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   CPU: Intel Xeon X3430 (4) @ 2.394GHz
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   GPU: 24:00.0 Matrox Electronics Systems Ltd. MGA G200e [Pilot]ServerEngines .ssssssssdMMMNhsssssssssshNMMMdssssssss.   Memory: 292MiB / 16005MiB
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/
  +sssssssssdmydMMMMMMMMddddyssssssss+
   /ssssssssssshdmNNNNmyNMMMMhssssss/
    .ossssssssssssssssssdMMMNysssso.
      -+sssssssssssssssssyyyssss+-
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.
```
```
Client:
            .-/+oossssoo+/-.               werner-web@werner-web-laptop-0001
        `:+ssssssssssssssssss+:`           ---------------------------------
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 20.10 x86_64
    .ossssssssssssssssssdMMMNysssso.       Host: Swift SF314-54 V1.16
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.8.0-59-generic
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 3 mins
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 3065 (dpkg), 13 (snap)
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.0.17
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1080
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Terminal: /dev/pts/2
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   CPU: Intel i7-8550U (8) @ 4.000GHz
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   GPU: Intel UHD Graphics 620
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Memory: 1288MiB / 7840MiB
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/
  +sssssssssdmydMMMMMMMMddddyssssssss+
   /ssssssssssshdmNNNNmyNMMMMhssssss/
    .ossssssssssssssssssdMMMNysssso.
      -+sssssssssssssssssyyyssss+-
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.
```
client2:
identical except ubuntu 21.04
#### Your borg version (borg -V).
server:
borg 1.1.15
client:
borg 1.1.15
client2:
borg 1.1.15
#### Operating system (distribution) and version.
server:
Ubuntu 20.04.2 LTS x86_64
client1:
Ubuntu 20.10 x86_64
client2:
Ubuntu 21.04 x86_64
#### Hardware / network configuration, and filesystems used.
server:
```
filesystem: ext4
drive: 1TB sata
ens2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.100  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 fe80::9e8e:99ff:fec4:44d8  prefixlen 64  scopeid 0x20<link>
        ether 9c:8e:99:c4:44:d8  txqueuelen 1000  (Ethernet)
        RX packets 16254  bytes 20551812 (20.5 MB)
        RX errors 0  dropped 18  overruns 0  frame 0
        TX packets 9442  bytes 822105 (822.1 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 16

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 38807  bytes 3277814 (3.2 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 38807  bytes 3277814 (3.2 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
clients:
```
network: dhcp
filesystem: ext4 (ubuntu)
drive: unknown
```
#### How much data is handled by borg?
30GB as far as i know
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
BORG_RHS="ssh -v -i /home/xxxx/.ssh/id_rsa" BORG_PASSPHRASE="xxxxxx" borg create -v -s -p -C lz4 --list server@xxxx:/media/backup/borg/::laptop-0001-{now:%Y-%m-%d-%T} /

## Describe the problem you're observing.
After entering the SSH password, wich is starnge becuase the specified key works, when used with ssh -i
Python tries to catch an exception and crashes. I have observed, that linux is apperently unknown, wich is strange because neofetch reports it, as it is as ubuntu 21.04

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

i can reproduce it and how is simple: Install ubuntu 21.04 or in my case uprade from ubuntu 20.04 via sudo do-dist-upgrade and install borg via apt install. Try making a backup and it will fail.

#### Include any warning/errors/backtraces from the system logs

```
Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1361, in get_fd
    ts, fd = self.fds[segment]

  File "/usr/lib/python3/dist-packages/borg/lrucache.py", line 21, in __getitem__
    value = self._cache[key]  # raise KeyError if not found

KeyError: 871


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/borg/remote.py", line 247, in serve
    res = f(**args)

  File "/usr/lib/python3/dist-packages/borg/remote.py", line 375, in open
    self.repository.__enter__()  # clean exit handled by serve() method

  File "/usr/lib/python3/dist-packages/borg/repository.py", line 190, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)

  File "/usr/lib/python3/dist-packages/borg/repository.py", line 451, in open
    if segment is not None and self.io.get_segment_magic(segment) == ATTIC_MAGIC:

  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1396, in get_segment_magic
    fd = self.get_fd(segment)

  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1363, in get_fd
    fd = open_fd()

  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1344, in open_fd
    fd = open(self.segment_filename(segment), 'rb')

PermissionError: [Errno 13] Permission denied: '/media/backup/borg/data/0/871'

Borg server: Platform: Linux homserver 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64
Borg server: Linux: Unknown Linux
Borg server: Borg: 1.1.15  Python: CPython 3.8.10 msgpack: 0.5.6
Borg server: PID: 4000  CWD: /home/server
Borg server: sys.argv: ['/usr/bin/borg', 'serve', '--umask=077', '--info']
Borg server: SSH_ORIGINAL_COMMAND: None
Platform: Linux werner-web-laptop-0001 5.8.0-59-generic #66-Ubuntu SMP Thu Jun 17 00:46:01 UTC 2021 x86_64
Linux: Unknown Linux
Borg: 1.1.15  Python: CPython 3.8.10 msgpack: 0.5.6
PID: 6144  CWD: /home/werner-web
sys.argv: ['/usr/bin/borg', 'create', '-v', '-s', '-p', '-C', 'lz4', '--list', '-e', 're:^/dev/', '-e', 're:^/var/temp', '-e', 're:^.*/.local/share/Trash/', '-e', 're:^/proc/', '-e', 're:^.*.pids$', '-e', 're:^.cache/', '-e', 're:^/usr/src/linux.*/', '-e', 're:^/var/temp/portage/', '-e', 're:^/sys/', '-e', 're:^/usr/portage/', '-e', 're:^/run/user/1000/gvfs/', 'server@xxxx:/media/backup/borg/::laptop-0001-{now:%Y-%m-%d-%T}', '/']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment]
Typo: BORG_RHS instead of (correct) `BORG_RSH` - guess this is why it does not use your key.

**Comment by ThomasWaldmann** [comment]
```
PermissionError: [Errno 13] Permission denied: '/media/backup/borg/data/0/871'
```

You need to fix permissions there, so that the user you use can access (rwx) that data.

**Comment by GameTec-live** [comment]
> Typo: BORG_RHS instead of (correct) `BORG_RSH` - guess this is why it does not use your key.

Welk that was just a classic pebcak but the secund one: thanks!!!! Any idea how to make sure, that the 777 permission stays?

**Comment by ThomasWaldmann** [comment]
@GameTec-live if the repo files are just owned by the user you use for the borg ssh login, you won't have owner or mode issues. Some people like to add a "borg" user (and group) just for that.

And never use 777 for anything except if you know what you do.

**Comment by GameTec-live** [comment]
> @GameTec-live if the repo files are just owned by the user you use for the borg ssh login, you won't have owner or mode issues. Some people like to add a "borg" user (and group) just for that.
> 
> And never use 777 for anything except if you know what you do.
> 

Ok thx
