### ISSUE TITLE
AttributeError: 'Repository' object has no attribute 'lock' when I try to do anything with a borg repo

### ISSUE THREAD

**Issue by jeffreymeng** [borgbackup/borg#5948]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

## System information. For client/server mode post info for both machines.
Macbook Pro, MacOS Big Sur 11.4

#### Your borg version (borg -V).
borg 1.1.17

#### Operating system (distribution) and version.
Macbook Pro, MacOS Big Sur 11.4

#### Hardware / network configuration, and filesystems used.
I have an external hard drive connected to my MacBook via USB C. The hard drive uses APFS.

#### How much data is handled by borg?

The backup folder is slightly less than a terabyte after deduplication.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
➜ Backup B $ borg list borgbackups
Removed stale exclusive roster lock for host jeffreys-mbp.lan@190070690681122 pid 29572 thread 0.
Removed stale exclusive roster lock for host jeffreys-mbp.lan@190070690681122 pid 29572 thread 0.
mbp2013_2018-03-03-010134_usersonly  Sun, 2021-08-01 19:32:06 [0c3c3121db9caaf00ee4adbe4c532e1ba728dd0bb793cf49b498814aff4a9d7d]
mbp2013_2018-03-11-204726_usersonly  Sun, 2021-08-01 20:02:57 [99e21a24c3a209d0f1c2b72a87bcc7b854245f13195a89c794267d0d9c382a1e]
mbp2013_2018-03-21-012833_usersonly  Sun, 2021-08-01 23:31:00 [08ddc50e036ed0aa2eab20d67c6836344fb49ec9fc6b495ebcee729e0c50f746]

... (there are like 20 more that I omitted to save space)

➜ Backup B $ borg delete borgbackups::mbp2018_2019-10-16-052806_users

➜ Backup B $ borg mount borgbackups
usage: borg mount [-h] [--critical] [--error] [--warning] [--info] [--debug] [--debug-topic TOPIC] [-p] [--log-json] [--lock-wait SECONDS] [--bypass-lock] [--show-version] [--show-rc] [--umask M] [--remote-path PATH] [--remote-ratelimit RATE] [--consider-part-files]
                  [--debug-profile FILE] [--rsh RSH] [-f] [-o OPTIONS] [-P PREFIX | -a GLOB] [--sort-by KEYS] [--first N | --last N] [-e PATTERN] [--exclude-from EXCLUDEFILE] [--pattern PATTERN] [--patterns-from PATTERNFILE] [--strip-components NUMBER]
                  REPOSITORY_OR_ARCHIVE MOUNTPOINT [PATH ...]
borg mount: error: the following arguments are required: MOUNTPOINT, PATH

➜ Backup B $ borg mount borgbackups /Users/jmeng/Downloads/borgmount 
Traceback (most recent call last):
  File "/usr/local/Cellar/borgbackup-fuse/1.1.17/libexec/lib/python3.9/site-packages/borg/archiver.py", line 4703, in main
    exit_code = archiver.run(args)
  File "/usr/local/Cellar/borgbackup-fuse/1.1.17/libexec/lib/python3.9/site-packages/borg/archiver.py", line 4635, in run
    return set_ec(func(args))
  File "/usr/local/Cellar/borgbackup-fuse/1.1.17/libexec/lib/python3.9/site-packages/borg/archiver.py", line 1433, in do_mount
    return self._do_mount(args)
  File "/usr/local/Cellar/borgbackup-fuse/1.1.17/libexec/lib/python3.9/site-packages/borg/archiver.py", line 159, in wrapper
    repository = Repository(location.path, create=create, exclusive=argument(args, exclusive),
  File "/usr/local/Cellar/borgbackup-fuse/1.1.17/libexec/lib/python3.9/site-packages/borg/repository.py", line 155, in __init__
    self.path = os.path.abspath(path)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/posixpath.py", line 379, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/borg", line 33, in <module>
    sys.exit(load_entry_point('borgbackup==1.1.17', 'console_scripts', 'borg')())
  File "/usr/local/Cellar/borgbackup-fuse/1.1.17/libexec/lib/python3.9/site-packages/borg/archiver.py", line 4725, in main
    tb = '%s\n%s' % (traceback.format_exc(), sysinfo())
  File "/usr/local/Cellar/borgbackup-fuse/1.1.17/libexec/lib/python3.9/site-packages/borg/helpers.py", line 1727, in sysinfo
    info.append('PID: %d  CWD: %s' % (os.getpid(), os.getcwd()))
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <function Repository.__del__ at 0x10da2e700>
Traceback (most recent call last):
  File "/usr/local/Cellar/borgbackup-fuse/1.1.17/libexec/lib/python3.9/site-packages/borg/repository.py", line 178, in __del__
    if self.lock:
AttributeError: 'Repository' object has no attribute 'lock'

➜ Backup B $ borg list borgbackups
Traceback (most recent call last):
  File "/usr/local/Cellar/borgbackup-fuse/1.1.17/libexec/lib/python3.9/site-packages/borg/archiver.py", line 4703, in main
    exit_code = archiver.run(args)
  File "/usr/local/Cellar/borgbackup-fuse/1.1.17/libexec/lib/python3.9/site-packages/borg/archiver.py", line 4635, in run
    return set_ec(func(args))
  File "/usr/local/Cellar/borgbackup-fuse/1.1.17/libexec/lib/python3.9/site-packages/borg/archiver.py", line 159, in wrapper
    repository = Repository(location.path, create=create, exclusive=argument(args, exclusive),
  File "/usr/local/Cellar/borgbackup-fuse/1.1.17/libexec/lib/python3.9/site-packages/borg/repository.py", line 155, in __init__
    self.path = os.path.abspath(path)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/posixpath.py", line 379, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/borg", line 33, in <module>
    sys.exit(load_entry_point('borgbackup==1.1.17', 'console_scripts', 'borg')())
  File "/usr/local/Cellar/borgbackup-fuse/1.1.17/libexec/lib/python3.9/site-packages/borg/archiver.py", line 4725, in main
    tb = '%s\n%s' % (traceback.format_exc(), sysinfo())
  File "/usr/local/Cellar/borgbackup-fuse/1.1.17/libexec/lib/python3.9/site-packages/borg/helpers.py", line 1727, in sysinfo
    info.append('PID: %d  CWD: %s' % (os.getpid(), os.getcwd()))
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <function Repository.__del__ at 0x10f3d2700>
Traceback (most recent call last):
  File "/usr/local/Cellar/borgbackup-fuse/1.1.17/libexec/lib/python3.9/site-packages/borg/repository.py", line 178, in __del__
    if self.lock:
AttributeError: 'Repository' object has no attribute 'lock'
```
## Describe the problem you're observing.

After a failed borg mount, it looks like the entire repo has been corrupted. Whenever I try to run anything on the repo, I get `AttributeError: 'Repository' object has no attribute 'lock'`

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

The problem still occurs whenever I try to run a borg command on the repo, such as borg list.

#### Include any warning/errors/backtraces from the system logs
See the command line history

**Comment by jeffreymeng** [comment]
Actually, I now get the error even if I try to use borg to create a new repo.

**Comment by ThomasWaldmann** [comment]
```
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
```

Huh? What's your current working directory at that moment?

**Comment by jeffreymeng** [comment]
It's the external hard drive, the parent directory of the backup directory

**Comment by jeffreymeng** [comment]
if you look at the history, brog list worked at the beginning, but then after the failed mount it stopped working.

**Comment by ThomasWaldmann** [comment]
The getcwd issue is inside stdlib. Guess the OS should never say "no such file" when asked for the cwd, except if the directory is really gone (like hdd unplugged / defect) or some other process killed the directory in parallel.

**Comment by jeffreymeng** [comment]
I just replugged in my external hdd and it worked, so I'll close this issue. Thank you for your help.

It might be nice if there was a nicer error message though.

**Comment by ThomasWaldmann** [comment]
yeah, the attributeerror is a bit dirty as it is only a secondary error happening while tearing down objects.
