### ISSUE TITLE
ValueError: Could not read header (expected 18, but read 0 bytes)

### ISSUE THREAD

**Issue by margau** [borgbackup/borg#5954]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug

#### Your borg version (borg -V).

1.1.17

#### Operating system (distribution) and version.

Debian Buster

#### Hardware / network configuration, and filesystems used.

btrfs raid1 used inside Proxmox LXC Container on both sides

#### How much data is handled by borg?

Log from last successful backup:
```
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                4.03 TB              3.77 TB            233.71 kB
All archives:              290.33 TB            272.31 TB              3.39 TB

                       Unique chunks         Total chunks
Chunk index:                 2182253            177241823
------------------------------------------------------------------------------

```

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

`sys.argv: ['/usr/local/bin/borg', 'create', '--show-rc', '-v', '--stats', '--progress', '--debug', 'ssh://borg@remote/storage/borgrepo::{now:%Y-%m-%d_%H:%M}', '/storage/smb']`

## Describe the problem you're observing.

Running a certain backup creates the given value error. Running `borg check` does not show any error. Cleaning the clientside cache doesn't help also. The repository has a bunch of older backups created without problems.

Pruning the repository works fine.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Only on this certain repository.

#### Include any warning/errors/backtraces from the system logs

```
[...]
Creating archive at "ssh://borg@remote/storage/borgrepo::{now:%Y-%m-%d_%H:%M}"
RemoteRepository: 226 B bytes sent, 2.89 kB bytes received, 4 messages sent
Local Exception
Traceback (most recent call last):
  File "borg/archiver.py", line 4703, in main
  File "borg/archiver.py", line 4635, in run
  File "borg/archiver.py", line 177, in wrapper
  File "borg/archiver.py", line 591, in do_create
  File "borg/cache.py", line 387, in __new__
  File "borg/cache.py", line 381, in local
  File "borg/cache.py", line 464, in __init__
  File "borg/cache.py", line 512, in open
  File "borg/cache.py", line 629, in rollback
  File "borg/cache.py", line 502, in _do_open
  File "src/borg/hashindex.pyx", line 113, in borg.hashindex.IndexBase.read
  File "src/borg/hashindex.pyx", line 100, in borg.hashindex.IndexBase.__cinit__
ValueError: Could not read header (expected 18, but read 0 bytes)

Platform: Linux smb-share 5.4.128-1-pve #1 SMP PVE 5.4.128-1 (Wed, 21 Jul 2021 18:32:02 +0200) x86_64
Linux: debian 10.10 
Borg: 1.1.17  Python: CPython 3.7.11 msgpack: 0.5.6.+borg1

```

**Comment by ThomasWaldmann** [comment]
That sounds like you have a zero-length segment file in your repo. Guess you could just try to remove that.

That 18-bytes header is at the start of each segment file, so if it reads 0 bytes there, it means the whole file is 0 bytes long.

**Comment by ThomasWaldmann** [comment]
It looks like the clientside chunks index for that repo is defect (0 bytes).

**Comment by margau** [comment]
Hi, where is the clientside chunk index located?
On the server side, I already forced a rebuild of the index (index.(id)-File in the repository root, this did not help.

`borg check` has no `-f`-Switch in the 1.1.17? I also ran borg check on the repository without finding.

**Comment by ThomasWaldmann** [comment]
Sorry, used fsck too much these days - i meant `--repair`.

The chunks index is in `~/.cache/borg/REPOID/` and is rebuilt from scratch when running borg check in repair mode.

**Comment by margau** [comment]
Hello,
i both repaired the repository, as well as deleted the cache on server and client side:
```
borg check --repair --progress -v . | tee ~/repair.log
This is a potentially dangerous function.
check --repair might lead to data loss (for kinds of corruption it is not
capable of dealing with). BE VERY CAREFUL!

Type 'YES' if you understand this and want to continue: YES
Starting repository check
Starting repository index check
Completed repository check, no problems found.
Starting archive consistency check...
Analyzing archive 2020-07-31_23:16 (1/24)
Analyzing archive 2020-08-31_23:16 (2/24)
Analyzing archive 2020-09-30_23:16 (3/24)
Analyzing archive 2020-10-31_23:16 (4/24)
Analyzing archive 2020-11-30_23:16 (5/24)
Analyzing archive 2020-12-31_23:16 (6/24)
Analyzing archive 2021-01-31_23:16 (7/24)
Analyzing archive 2021-02-28_23:16 (8/24)
Analyzing archive 2021-03-31_23:16 (9/24)
Analyzing archive 2021-04-30_23:16 (10/24)
Analyzing archive 2021-05-31_23:16 (11/24)
Analyzing archive 2021-06-20_23:16 (12/24)
Analyzing archive 2021-06-27_23:16 (13/24)
Analyzing archive 2021-06-30_23:16 (14/24)
Analyzing archive 2021-07-04_23:16 (15/24)
Analyzing archive 2021-07-11_23:16 (16/24)
Analyzing archive 2021-07-18_23:16 (17/24)
Analyzing archive 2021-07-22_23:16 (18/24)
Analyzing archive 2021-07-23_23:16 (19/24)
Analyzing archive 2021-07-24_21:16 (20/24)
Analyzing archive 2021-07-25_23:16 (21/24)
Analyzing archive 2021-07-26_23:16 (22/24)
Analyzing archive 2021-07-27_23:16 (23/24)
Analyzing archive 2021-07-28_16:16 (24/24)
Writing Manifest.
Committing repo (may take a while, due to compact_segments)...
Finished committing repo.
Archive consistency check complete, no problems found.

```

However, I still get the ValueError when trying to create a backup. Other commands (prune, list) are working fine.

Thanks!

**Comment by ThomasWaldmann** [comment]
Are you running all these commands as the same clientside user?
The clientside caches / indexes are per user, in their home directory.

**Comment by margau** [comment]
Yes, all commands are executed as "borg" on the remote machine. The client machine is allowed to connect using `command="borg serve --restrict-to-path /storage/borgrepo --append-only"` in `authorized_keys` of the user borg. All data in the repository and the cache is owned by the user borg:
```
 ls -l ~/.cache/borg/(repoid)/
total 131720
-rw------- 1 borg borg        68 Aug 15 18:46 README
-rw------- 1 borg borg 134870710 Aug 15 18:49 chunks
drwx------ 1 borg borg      7392 Aug 15 18:48 chunks.archive.d
-rw------- 1 borg borg       520 Aug 15 18:49 config
-rw------- 1 borg borg         0 Aug 15 18:46 files
```

**Comment by ThomasWaldmann** [comment]
```
cat ~/.cache/borg/(repoid)/config
wc -c ~/.cache/borg/(repoid)/config
ls -l ~/.cache/borg/(repoid)/chunks.archive.de/
```

**Comment by ThomasWaldmann** [comment]
BTW, when I suggested repairing I meant that you run the command from the client, not directly on the server.

**Comment by ThomasWaldmann** [comment]
/usr/local/bin/borg - what's that / where does this come from?

Please update your top post with what borg code exactly you are running.

**Comment by margau** [comment]
The binary is called from the absolute path in `/usr/local/bin`, thats why it is called with leading `/`.

Running repair on the client side did not help anythin.

Server Side (Hosting the Repo):
```
> cat ~/.cache/borg/cad82cca4ebbe4729a0f6e83305eee3aff151585453191cd8da33c0ee2463da0/config
[cache]
version = 1
repository = cad82cca4ebbe4729a0f6e83305eee3aff151585453191cd8da33c0ee2463da0
manifest = 29c65b7d058cbdeeffcf9f8dc3da077d7de19d2c36071426fb9ad2acee76e3e6
previous_location = /storage/rem_backup/(repo_name)
timestamp = 2021-08-17T14:43:15.612781
ignored_features = 
mandatory_features = 
key_type = 2

[integrity]
manifest = 29c65b7d058cbdeeffcf9f8dc3da077d7de19d2c36071426fb9ad2acee76e3e6
chunks = {"algorithm": "XXH64", "digests": {"HashHeader": "7472203bd849b95c", "final": "fd900bdbdcbeab28"}}

> wc -c ~/.cache/borg/cad82cca4ebbe4729a0f6e83305eee3aff151585453191cd8da33c0ee2463da0/config
520 /storage/rem_backup/.cache/borg/cad82cca4ebbe4729a0f6e83305eee3aff151585453191cd8da33c0ee2463da0/config

> ls -l ~/.cache/borg/(repoid)/chunks.archive.d/
ls -l ~/.cache/borg/cad82cca4ebbe4729a0f6e83305eee3aff151585453191cd8da33c0ee2463da0/chunks.archive.d/
total 1798856
-rw------- 1 borg borg 58640710 Aug 15 18:46 04de987d81a3173aefc5cc2c310f0c7041c8dae5c854b9b29d11e26d3fb8a25d.compact
-rw------- 1 borg borg       98 Aug 15 18:46 04de987d81a3173aefc5cc2c310f0c7041c8dae5c854b9b29d11e26d3fb8a25d.compact.integrity
-rw------- 1 borg borg 83080950 Aug 15 18:48 10fead9f1dc69a472e55f92d472027fbd5783712555b493639cb098dfcb9fcc1.compact
-rw------- 1 borg borg       98 Aug 15 18:48 10fead9f1dc69a472e55f92d472027fbd5783712555b493639cb098dfcb9fcc1.compact.integrity
-rw------- 1 borg borg 88344186 Aug 15 18:46 1dd43c35304fe85b23ccdcc88bd2e06c563826cee98e78b209ccaac01ec718c5.compact
-rw------- 1 borg borg       98 Aug 15 18:46 1dd43c35304fe85b23ccdcc88bd2e06c563826cee98e78b209ccaac01ec718c5.compact.integrity
-rw------- 1 borg borg 57516070 Aug 15 18:46 2c801a5a8fe95cd16d8e39baeefdde0927111941b1372c4dc05bbc46cca061f2.compact
-rw------- 1 borg borg       98 Aug 15 18:46 2c801a5a8fe95cd16d8e39baeefdde0927111941b1372c4dc05bbc46cca061f2.compact.integrity
-rw------- 1 borg borg 83082094 Aug 15 18:48 3a39bf58f06fa3bd245a2ebf38f934c8ade3d19f9dd59ae415014ea9cce3fe52.compact
-rw------- 1 borg borg       98 Aug 15 18:48 3a39bf58f06fa3bd245a2ebf38f934c8ade3d19f9dd59ae415014ea9cce3fe52.compact.integrity
-rw------- 1 borg borg 83080290 Aug 15 18:48 519469f00b21c11785a54afd5aa3260cdc10883d48ff894d04c4ddb1a438ce31.compact
-rw------- 1 borg borg       98 Aug 15 18:48 519469f00b21c11785a54afd5aa3260cdc10883d48ff894d04c4ddb1a438ce31.compact.integrity
-rw------- 1 borg borg 57311162 Aug 15 18:46 554fc6b779ef55735171f1b39232f882c9126d9548d6e951f946f01802ac3415.compact
-rw------- 1 borg borg       98 Aug 15 18:46 554fc6b779ef55735171f1b39232f882c9126d9548d6e951f946f01802ac3415.compact.integrity
-rw------- 1 borg borg 83080510 Aug 15 18:48 5642b82ad2df9990e8e29dbc0d7eac89eb33fe626c9e9ff44e9e8b29affbed36.compact
-rw------- 1 borg borg       98 Aug 15 18:48 5642b82ad2df9990e8e29dbc0d7eac89eb33fe626c9e9ff44e9e8b29affbed36.compact.integrity
-rw------- 1 borg borg 83081390 Aug 15 18:48 5d4166595396da401bcd15b6cc279a8505214c5ea6020169441274c0f20227ff.compact
-rw------- 1 borg borg       98 Aug 15 18:48 5d4166595396da401bcd15b6cc279a8505214c5ea6020169441274c0f20227ff.compact.integrity
-rw------- 1 borg borg 57537850 Aug 15 18:46 5e0337f09e7c505d370c5246349b7fcfd0469b74d68d6a191a2692b7b39428b9.compact
-rw------- 1 borg borg       98 Aug 15 18:46 5e0337f09e7c505d370c5246349b7fcfd0469b74d68d6a191a2692b7b39428b9.compact.integrity
-rw------- 1 borg borg 81345106 Aug 15 18:46 70f77f135cc180841f374e46857ad91ae086b328405fbc952e46494d908bb0a0.compact
-rw------- 1 borg borg       98 Aug 15 18:46 70f77f135cc180841f374e46857ad91ae086b328405fbc952e46494d908bb0a0.compact.integrity
-rw------- 1 borg borg 57488746 Aug 15 18:46 75be0dae3bdf7fc815de40d2c679a5deb745e8616bed3c8fc70cab9bf06635de.compact
-rw------- 1 borg borg       98 Aug 15 18:46 75be0dae3bdf7fc815de40d2c679a5deb745e8616bed3c8fc70cab9bf06635de.compact.integrity
-rw------- 1 borg borg 82456062 Aug 15 18:47 7db34d2cf986f9eda4ba9aff80ace571259ca625da9baff5326c336e815d3033.compact
-rw------- 1 borg borg       98 Aug 15 18:47 7db34d2cf986f9eda4ba9aff80ace571259ca625da9baff5326c336e815d3033.compact.integrity
-rw------- 1 borg borg 82457074 Aug 15 18:47 90e13c64dffae49c4e886143b6d8fb7e29d82848ac0cb8ef9211fbca9f794561.compact
-rw------- 1 borg borg       98 Aug 15 18:47 90e13c64dffae49c4e886143b6d8fb7e29d82848ac0cb8ef9211fbca9f794561.compact.integrity
-rw------- 1 borg borg 82976670 Aug 15 18:47 9776770280bf271dff101c7ae9ed6b85c963c16abc48fc7420effbb0d525a667.compact
-rw------- 1 borg borg       98 Aug 15 18:47 9776770280bf271dff101c7ae9ed6b85c963c16abc48fc7420effbb0d525a667.compact.integrity
-rw------- 1 borg borg 82455490 Aug 15 18:47 a9cdd2f55aad386b6079555682ca62055ec518bf54a0b08f32970ffcf9e3a363.compact
-rw------- 1 borg borg       98 Aug 15 18:47 a9cdd2f55aad386b6079555682ca62055ec518bf54a0b08f32970ffcf9e3a363.compact.integrity
-rw------- 1 borg borg 83080422 Aug 15 18:48 aea624c8833964a970f407cca20c4b37251a560cbea0a38705d25cf23e051bc7.compact
-rw------- 1 borg borg       98 Aug 15 18:48 aea624c8833964a970f407cca20c4b37251a560cbea0a38705d25cf23e051bc7.compact.integrity
-rw------- 1 borg borg 83082270 Aug 15 18:48 b257eeba245e99f09bbad4bff900f230f3cb8bbcdc440c6c2e5fc6520f1eb742.compact
-rw------- 1 borg borg       98 Aug 15 18:48 b257eeba245e99f09bbad4bff900f230f3cb8bbcdc440c6c2e5fc6520f1eb742.compact.integrity
-rw------- 1 borg borg 81355930 Aug 15 18:47 b4bbe6843ca2498cc3204551835a9db067178ab85100d5447a0715490362bafa.compact
-rw------- 1 borg borg       98 Aug 15 18:47 b4bbe6843ca2498cc3204551835a9db067178ab85100d5447a0715490362bafa.compact.integrity
-rw------- 1 borg borg 83080906 Aug 15 18:48 c0b4765ee8cae8b8aa473bb06136cabfde4a3c2e24cdec343248c1f088445225.compact
-rw------- 1 borg borg       98 Aug 15 18:48 c0b4765ee8cae8b8aa473bb06136cabfde4a3c2e24cdec343248c1f088445225.compact.integrity
-rw------- 1 borg borg 82385618 Aug 15 18:47 e5e3bb2d737207ad74e906c24ba8d2962e0e83a9c7e4054ab09d48d7290b08de.compact
-rw------- 1 borg borg       98 Aug 15 18:47 e5e3bb2d737207ad74e906c24ba8d2962e0e83a9c7e4054ab09d48d7290b08de.compact.integrity
-rw------- 1 borg borg 60526814 Aug 15 18:46 eca78cb1d52861ff6f848976eb2f1af34754c682e99f1c19a5e1b8a026edbd8f.compact
-rw------- 1 borg borg       98 Aug 15 18:46 eca78cb1d52861ff6f848976eb2f1af34754c682e99f1c19a5e1b8a026edbd8f.compact.integrity
-rw------- 1 borg borg 81354478 Aug 15 18:47 f8e9163fd36a3d67b0808551067cfcc22da89bcd3d1d003575ef1ed2569421a3.compact
-rw------- 1 borg borg       98 Aug 15 18:47 f8e9163fd36a3d67b0808551067cfcc22da89bcd3d1d003575ef1ed2569421a3.compact.integrity
-rw------- 1 borg borg 83081214 Aug 15 18:47 fd54efe9ca44ee1770cd7e05770fc9c179fbf90f898a2e772ea31e69bebde31a.compact
-rw------- 1 borg borg       98 Aug 15 18:47 fd54efe9ca44ee1770cd7e05770fc9c179fbf90f898a2e772ea31e69bebde31a.compact.integrity

```

Client Side (Pushing the Backup:

```
> cat ~/.cache/borg/cad82cca4ebbe4729a0f6e83305eee3aff151585453191cd8da33c0ee2463da0/config
[cache]
version = 1
repository = cad82cca4ebbe4729a0f6e83305eee3aff151585453191cd8da33c0ee2463da0
manifest = ba1ff940c28571287e48341525f81cb831d040231983cfd509bb76d6f7e6dad6
previous_location = ssh://borg@remote/storage/rem_backup/(repo_name)
timestamp = 2021-08-15T18:00:53.426166
ignored_features = 
mandatory_features = 
key_type = 2

[integrity]
manifest = ba1ff940c28571287e48341525f81cb831d040231983cfd509bb76d6f7e6dad6
chunks = {"algorithm": "XXH64", "digests": {"HashHeader": "7472203bd849b95c", "final": "fd900bdbdcbeab28"}}


> wc -c ~/.cache/borg/cad82cca4ebbe4729a0f6e83305eee3aff151585453191cd8da33c0ee2463da0/config
553 /root/.cache/borg/cad82cca4ebbe4729a0f6e83305eee3aff151585453191cd8da33c0ee2463da0/config

>  ls -l ~/.cache/borg/cad82cca4ebbe4729a0f6e83305eee3aff151585453191cd8da33c0ee2463da0/chunks.archive.d/
total 1801304
-rw------- 1 root root 58640710 Aug 16 14:59 04de987d81a3173aefc5cc2c310f0c7041c8dae5c854b9b29d11e26d3fb8a25d.compact
-rw------- 1 root root       98 Aug 16 14:59 04de987d81a3173aefc5cc2c310f0c7041c8dae5c854b9b29d11e26d3fb8a25d.compact.integrity
-rw------- 1 root root 83080950 Aug 16 15:24 10fead9f1dc69a472e55f92d472027fbd5783712555b493639cb098dfcb9fcc1.compact
-rw------- 1 root root       98 Aug 16 15:24 10fead9f1dc69a472e55f92d472027fbd5783712555b493639cb098dfcb9fcc1.compact.integrity
-rw------- 1 root root 88344186 Aug 16 15:00 1dd43c35304fe85b23ccdcc88bd2e06c563826cee98e78b209ccaac01ec718c5.compact
-rw------- 1 root root       98 Aug 16 15:00 1dd43c35304fe85b23ccdcc88bd2e06c563826cee98e78b209ccaac01ec718c5.compact.integrity
-rw------- 1 root root 57516070 Aug 16 14:59 2c801a5a8fe95cd16d8e39baeefdde0927111941b1372c4dc05bbc46cca061f2.compact
-rw------- 1 root root       98 Aug 16 14:59 2c801a5a8fe95cd16d8e39baeefdde0927111941b1372c4dc05bbc46cca061f2.compact.integrity
-rw------- 1 root root 83082094 Aug 16 15:18 3a39bf58f06fa3bd245a2ebf38f934c8ade3d19f9dd59ae415014ea9cce3fe52.compact
-rw------- 1 root root       98 Aug 16 15:18 3a39bf58f06fa3bd245a2ebf38f934c8ade3d19f9dd59ae415014ea9cce3fe52.compact.integrity
-rw------- 1 root root 83080290 Aug 16 15:26 519469f00b21c11785a54afd5aa3260cdc10883d48ff894d04c4ddb1a438ce31.compact
-rw------- 1 root root       98 Aug 16 15:26 519469f00b21c11785a54afd5aa3260cdc10883d48ff894d04c4ddb1a438ce31.compact.integrity
-rw------- 1 root root 57311162 Aug 16 14:59 554fc6b779ef55735171f1b39232f882c9126d9548d6e951f946f01802ac3415.compact
-rw------- 1 root root       98 Aug 16 14:59 554fc6b779ef55735171f1b39232f882c9126d9548d6e951f946f01802ac3415.compact.integrity
-rw------- 1 root root 83080510 Aug 16 15:20 5642b82ad2df9990e8e29dbc0d7eac89eb33fe626c9e9ff44e9e8b29affbed36.compact
-rw------- 1 root root       98 Aug 16 15:20 5642b82ad2df9990e8e29dbc0d7eac89eb33fe626c9e9ff44e9e8b29affbed36.compact.integrity
-rw------- 1 root root 83081390 Aug 16 15:28 5d4166595396da401bcd15b6cc279a8505214c5ea6020169441274c0f20227ff.compact
-rw------- 1 root root       98 Aug 16 15:28 5d4166595396da401bcd15b6cc279a8505214c5ea6020169441274c0f20227ff.compact.integrity
-rw------- 1 root root 57537850 Aug 16 14:59 5e0337f09e7c505d370c5246349b7fcfd0469b74d68d6a191a2692b7b39428b9.compact
-rw------- 1 root root       98 Aug 16 14:59 5e0337f09e7c505d370c5246349b7fcfd0469b74d68d6a191a2692b7b39428b9.compact.integrity
-rw------- 1 root root 81345106 Aug 16 15:01 70f77f135cc180841f374e46857ad91ae086b328405fbc952e46494d908bb0a0.compact
-rw------- 1 root root       98 Aug 16 15:01 70f77f135cc180841f374e46857ad91ae086b328405fbc952e46494d908bb0a0.compact.integrity
-rw------- 1 root root 57488746 Aug 16 14:59 75be0dae3bdf7fc815de40d2c679a5deb745e8616bed3c8fc70cab9bf06635de.compact
-rw------- 1 root root       98 Aug 16 14:59 75be0dae3bdf7fc815de40d2c679a5deb745e8616bed3c8fc70cab9bf06635de.compact.integrity
-rw------- 1 root root 82456062 Aug 16 15:09 7db34d2cf986f9eda4ba9aff80ace571259ca625da9baff5326c336e815d3033.compact
-rw------- 1 root root       98 Aug 16 15:09 7db34d2cf986f9eda4ba9aff80ace571259ca625da9baff5326c336e815d3033.compact.integrity
-rw------- 1 root root 82457074 Aug 16 15:11 90e13c64dffae49c4e886143b6d8fb7e29d82848ac0cb8ef9211fbca9f794561.compact
-rw------- 1 root root       98 Aug 16 15:11 90e13c64dffae49c4e886143b6d8fb7e29d82848ac0cb8ef9211fbca9f794561.compact.integrity
-rw------- 1 root root 82976670 Aug 16 15:12 9776770280bf271dff101c7ae9ed6b85c963c16abc48fc7420effbb0d525a667.compact
-rw------- 1 root root       98 Aug 16 15:12 9776770280bf271dff101c7ae9ed6b85c963c16abc48fc7420effbb0d525a667.compact.integrity
-rw------- 1 root root 82455490 Aug 16 15:07 a9cdd2f55aad386b6079555682ca62055ec518bf54a0b08f32970ffcf9e3a363.compact
-rw------- 1 root root       98 Aug 16 15:07 a9cdd2f55aad386b6079555682ca62055ec518bf54a0b08f32970ffcf9e3a363.compact.integrity
-rw------- 1 root root 83080422 Aug 16 15:22 aea624c8833964a970f407cca20c4b37251a560cbea0a38705d25cf23e051bc7.compact
-rw------- 1 root root       98 Aug 16 15:22 aea624c8833964a970f407cca20c4b37251a560cbea0a38705d25cf23e051bc7.compact.integrity
-rw------- 1 root root 83082270 Aug 16 15:30 b257eeba245e99f09bbad4bff900f230f3cb8bbcdc440c6c2e5fc6520f1eb742.compact
-rw------- 1 root root       98 Aug 16 15:30 b257eeba245e99f09bbad4bff900f230f3cb8bbcdc440c6c2e5fc6520f1eb742.compact.integrity
-rw------- 1 root root 81355930 Aug 16 15:04 b4bbe6843ca2498cc3204551835a9db067178ab85100d5447a0715490362bafa.compact
-rw------- 1 root root       98 Aug 16 15:04 b4bbe6843ca2498cc3204551835a9db067178ab85100d5447a0715490362bafa.compact.integrity
-rw------- 1 root root 83080906 Aug 16 15:16 c0b4765ee8cae8b8aa473bb06136cabfde4a3c2e24cdec343248c1f088445225.compact
-rw------- 1 root root       98 Aug 16 15:16 c0b4765ee8cae8b8aa473bb06136cabfde4a3c2e24cdec343248c1f088445225.compact.integrity
-rw------- 1 root root 82385618 Aug 16 15:06 e5e3bb2d737207ad74e906c24ba8d2962e0e83a9c7e4054ab09d48d7290b08de.compact
-rw------- 1 root root       98 Aug 16 15:06 e5e3bb2d737207ad74e906c24ba8d2962e0e83a9c7e4054ab09d48d7290b08de.compact.integrity
-rw------- 1 root root 60526814 Aug 16 15:00 eca78cb1d52861ff6f848976eb2f1af34754c682e99f1c19a5e1b8a026edbd8f.compact
-rw------- 1 root root       98 Aug 16 15:00 eca78cb1d52861ff6f848976eb2f1af34754c682e99f1c19a5e1b8a026edbd8f.compact.integrity
-rw------- 1 root root 81354478 Aug 16 15:02 f8e9163fd36a3d67b0808551067cfcc22da89bcd3d1d003575ef1ed2569421a3.compact
-rw------- 1 root root       98 Aug 16 15:02 f8e9163fd36a3d67b0808551067cfcc22da89bcd3d1d003575ef1ed2569421a3.compact.integrity
-rw------- 1 root root 83081214 Aug 16 15:14 fd54efe9ca44ee1770cd7e05770fc9c179fbf90f898a2e772ea31e69bebde31a.compact
-rw------- 1 root root       98 Aug 16 15:14 fd54efe9ca44ee1770cd7e05770fc9c179fbf90f898a2e772ea31e69bebde31a.compact.integrity

```

**Comment by ThomasWaldmann** [comment]
OK, config and `chunks.archives.d` contents looks sane.

I still don't know where you got your `borg` binary from.

Also, I need the `wc -c` run against the `chunks` file (sorry, that was a c&p mistake of mine).

**Comment by margau** [comment]
The /usr/local/bin/borg file is exactly https://github.com/borgbackup/borg/releases/download/1.1.17/borg-linux64 (placed there by configuration management).

The chunks file on client side:
```
> wc -c ~/.cache/borg/cad82cca4ebbe4729a0f6e83305eee3aff151585453191cd8da33c0ee2463da0/chunks
134870710 /root/.cache/borg/cad82cca4ebbe4729a0f6e83305eee3aff151585453191cd8da33c0ee2463da0/chunks
```

Server Side:
```
> wc -c ~/.cache/borg/cad82cca4ebbe4729a0f6e83305eee3aff151585453191cd8da33c0ee2463da0/chunks
134870710 /storage/rem_backup/.cache/borg/cad82cca4ebbe4729a0f6e83305eee3aff151585453191cd8da33c0ee2463da0/chunks
```

Both chunks files are also identical (tested using sha256sum).

**Comment by ThomasWaldmann** [comment]
OK, so the chunks file is likely valid. That makes it even more strange, because the error msg says, it can't read its header bytes.

Can you verify whether the borg binary is valid, e.g. by checking it against the GPG signature?

**Comment by margau** [comment]
I checked it against the sha256sum of a fresh download, just in this moment.
All three instances (client, server and fresh download) have `21484d30271478d4a01aad1b286973443b50afc5379e4a6aef40da3379e21ddf  /usr/local/bin/borg`

**Comment by margau** [comment]
Another Update: I've switched to the pip3 installation method, and getting this (little bit more verbose) output:
```
Local Exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/borg/archiver.py", line 4703, in main
    exit_code = archiver.run(args)
  File "/usr/local/lib/python3.7/dist-packages/borg/archiver.py", line 4635, in run
    return set_ec(func(args))
  File "/usr/local/lib/python3.7/dist-packages/borg/archiver.py", line 177, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/borg/archiver.py", line 591, in do_create
    cache_mode=args.files_cache_mode, ignore_inode=args.ignore_inode) as cache:
  File "/usr/local/lib/python3.7/dist-packages/borg/cache.py", line 387, in __new__
    return local()
  File "/usr/local/lib/python3.7/dist-packages/borg/cache.py", line 381, in local
    lock_wait=lock_wait, cache_mode=cache_mode)
  File "/usr/local/lib/python3.7/dist-packages/borg/cache.py", line 464, in __init__
    self.open()
  File "/usr/local/lib/python3.7/dist-packages/borg/cache.py", line 512, in open
    self.rollback()
  File "/usr/local/lib/python3.7/dist-packages/borg/cache.py", line 629, in rollback
    self._do_open()
  File "/usr/local/lib/python3.7/dist-packages/borg/cache.py", line 502, in _do_open
    self.chunks = ChunkIndex.read(fd)
  File "src/borg/hashindex.pyx", line 113, in borg.hashindex.IndexBase.read
  File "src/borg/hashindex.pyx", line 100, in borg.hashindex.IndexBase.__cinit__
ValueError: Could not read header (expected 18, but read 0 bytes)
```

**Comment by ThomasWaldmann** [comment]
I guess I need to debug this as I currently can't make sense of that issue.

First try could be you giving me the correct (that produces such a traceback) `chunks` and cache `config` file so I can try it locally.

There is no private data in the `chunks` file, it is just chunk IDs, refcounts and chunk size information.

With that I would try to reproduce the issue locally on my machine.

**Comment by ThomasWaldmann** [comment]
Thanks for offering the files!

I downloaded them, checked sha256sums (correct) and wrote this code:

```
## issue5954.py

from borg.crypto.file_integrity import IntegrityCheckedFile
from borg.hashindex import ChunkIndex

from borg.logger import setup_logging
setup_logging()

ci_path = '/tmp/margau/chunks'

# this is taken from the config file:
integrity_data = """\
{
    "algorithm": "XXH64",
    "digests": {"HashHeader": "7472203bd849b95c", "final": "fd900bdbdcbeab28"}
}
"""

# same code as where it crashes:
with IntegrityCheckedFile(path=ci_path, write=False, integrity_data=integrity_data) as fd:
    chunks = ChunkIndex.read(fd)

print(len(chunks))
```

Ran this using a fresh install of the 1.1.17 codebase:
```
$ python3 issue5954.py
2175158
```

So, works fine for me. Are we sure these are the "problematic" files?

**Comment by ThomasWaldmann** [comment]
Made another try with this, replicating also the relevant parts of the config parsing:
```
import configparser

from borg.crypto.file_integrity import IntegrityCheckedFile
from borg.hashindex import ChunkIndex

from borg.logger import setup_logging
setup_logging()

ci_path = '/tmp/margau/chunks'
cfg_path = '/tmp/margau/config'

config = configparser.ConfigParser(interpolation=None)
with open(cfg_path) as fd:
    config.read_file(fd)
integrity = dict(config.items('integrity'))
print(repr(integrity))
assert config.get('cache', 'manifest') == integrity.pop('manifest')

with IntegrityCheckedFile(path=ci_path, write=False, integrity_data=integrity.get('chunks')) as fd:
    chunks = ChunkIndex.read(fd)

print(len(chunks))
```

Same here: works for me, all as expected.

**Comment by ThomasWaldmann** [comment]
When replacing the chunks file by a 0 bytes file, I get this (as expected):
```
$ python3 issue5954.py
{'manifest': 'ba1ff940c28571287e48341525f81cb831d040231983cfd509bb76d6f7e6dad6', 'chunks': '{"algorithm": "XXH64", "digests": {"HashHeader": "7472203bd849b95c", "final": "fd900bdbdcbeab28"}}'}
Traceback (most recent call last):
  File "issue5954.py", line 20, in <module>
    chunks = ChunkIndex.read(fd)
  File "src/borg/hashindex.pyx", line 113, in borg.hashindex.IndexBase.read
    return cls(path=path, permit_compact=permit_compact)
  File "src/borg/hashindex.pyx", line 100, in borg.hashindex.IndexBase.__cinit__
    self.index = hashindex_read(path, permit_compact)
ValueError: Could not read header (expected 18, but read 0 bytes)
```

**Comment by margau** [comment]
I tried the same example on the affected machine, and can exactly reproduce this. The scripts are working/failing as expected while using the "real" cache.

**Comment by margau** [comment]
Another update: While playing around, I think i found the issue on my side. 
There was a hidden "export BORG_CACHE_DIR=" in an environment triggering the backup itself, causing it to use another cache directory. Probably, the volume containing the cache dir could have exceeded the quota leading to that situation.
That, however, did not became clear, because the repair steps created the default cache, which seemed to be intact, and I did not see that borg was actually trying to use another cache.

Well, what could have helped with this issue? I'd consider adding an explicit output like "Try to check/delete the cache under $path" to those caching-related exceptions, giving the user the exact path to look into. Alternatively, a "0 byte" chunks-file could be rebuild automatically or triggering a full cache check?

**Comment by ThomasWaldmann** [comment]
I am not much a fan of auto-fixing stuff, considering that only hides some other issue.

But we need to log full paths to make issues like this easier to solve, see #5963.
