### ISSUE TITLE
"OSError: [Errno 5] Input/output error" on WSL with UNC-Mounted Paths

### ISSUE THREAD

**Issue by miridigital** [borgbackup/borg#5974]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes. It seems WSL is currently not fully supported by BorgBackup so my issue may be invalid. But I try anyway...

## Is this a BUG / ISSUE report or a QUESTION?

Issue.

## System information. For client/server mode post info for both machines

Only one Windows 10 system with a "local" repository on a mounted UNC-path with WSL.

#### Your borg version (borg -V)
```borg 1.1.17```

#### Operating system (distribution) and version

Microsoft Windows 10 Professional 64 Bit 20H2 [Version 10.0.19042.1165]
with WSL ("Windows Subsystem for Linux") Ubuntu

```
cmd.exe:
C:\>wsl --list --verbose
  NAME      STATE           VERSION
* Ubuntu    Running         2

bash:
# cat /proc/version
Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Oct 28 23:40:43 UTC 2020
```

#### Hardware / network configuration, and filesystems used
* CPU: Prozessor Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz, 3601 MHz, 4 Kern(e), 8 logische(r) Prozessor(en) Intel64 Family 6 Model 60 Stepping 3
* RAM: 32,0 GB
* Harddisk: Samsung SSD 860 EVO 1TB (1x SATA6 NTFS C: and 1x USB3 NTFS A:)
* Network: Intel(R) Ethernet Connection I217-LM LAN 1 GBit/s
* UNC on the same machine or UNC over Network (produces the same result)

#### How much data is handled by borg?
Only a couple of kilobytes (for repository init and backup testing)

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

If I try to create (or use an existing) borg repository over an UNC-mounted path, there is an exception every time:

```
root@WIN10PC:/mnt# mkdir test
root@WIN10PC:/mnt# mount -t drvfs //localhost/c$ test
root@WIN10PC:/mnt# cd test
root@WIN10PC:/mnt/test# mkdir borgtest
root@WIN10PC:/mnt/test# borg init --encryption=repokey borgtest/
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4703, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4635, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 162, in wrapper
    with repository:
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 188, in __enter__
    self.create(self.path)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 287, in create
    self.save_config(path, config)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 313, in save_config
    config.write(fd)
  File "/usr/lib/python3/dist-packages/borg/platform/base.py", line 172, in __exit__
    self.fd.close()
  File "/usr/lib/python3/dist-packages/borg/platform/base.py", line 140, in close
    platform.sync_dir(dirname)
  File "/usr/lib/python3/dist-packages/borg/platform/base.py", line 60, in sync_dir
    os.fsync(fd)
OSError: [Errno 5] Input/output error

Platform: Linux WIN10PC 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64
Linux: Unknown Linux
Borg: 1.1.17  Python: CPython 3.8.10 msgpack: 0.5.6.+borg1
PID: 1761  CWD: /mnt/test
sys.argv: ['/usr/bin/borg', 'init', '--encryption=repokey', 'borgtest/']
SSH_ORIGINAL_COMMAND: None

root@WIN10PC:/mnt/test# cd borgtest/
root@WIN10PC:/mnt/test/borgtest# ls -lah borgtest/
total 0
drwxrwxrwx 1 root root 512 Aug 31 15:35 .
drwxrwxrwx 1 root root 512 Aug 31 15:28 ..
-rwxrwxrwx 1 root root  73 Aug 31 15:35 README
-rwxrwxrwx 1 root root 209 Aug 31 15:35 config.tmp
drwxrwxrwx 1 root root 512 Aug 31 15:35 data
```

If I try the same thing but with a local USB drive (shows a drive A: under Windows and it is automaticly mounted under /mnt/a on WSL Ubuntu) it is working fine:

```
root@WIN10PC:/mnt# cd a
root@WIN10PC:/mnt/a# mkdir borgtest
root@WIN10PC:/mnt/a# borg init --encryption=repokey borgtest/
Enter new passphrase:
Enter same passphrase again:
Do you want your passphrase to be displayed for verification? [yN]:

By default repositories initialized with this version will produce security
errors if written to with an older version (up to and including Borg 1.0.8).

If you want to use these older versions, you can disable the check by running:
borg upgrade --disable-tam borgtest

See https://borgbackup.readthedocs.io/en/stable/changes.html#pre-1-0-9-manifest-spoofing-vulnerability for details about the security implications.

IMPORTANT: you will need both KEY AND PASSPHRASE to access this repo!
If you used a repokey mode, the key is stored in the repo, but you should back it up separately.
Use "borg key export" to export the key, optionally in printable format.
Write down the passphrase. Store both at safe place(s).

root@WIN10PC:/mnt/a# ls -lah borgtest/
total 45K
drwxrwxrwx 1 user user 512 Sep  2 10:16 .
drwxrwxrwx 1 user user 512 Sep  2 10:16 ..
-rwxrwxrwx 1 user user  73 Sep  2 10:16 README
-rwxrwxrwx 1 user user 700 Sep  2 10:16 config
drwxrwxrwx 1 user user 512 Sep  2 10:16 data
-rwxrwxrwx 1 user user  52 Sep  2 10:16 hints.1
-rwxrwxrwx 1 user user 41K Sep  2 10:16 index.1
-rwxrwxrwx 1 user user 190 Sep  2 10:16 integrity.1
-rwxrwxrwx 1 user user  16 Sep  2 10:16 nonce
root@WIN10PC:/mnt/a#
```

I can use the same drive/path (local USB drive mit NTFS) and use it first "local" (it's working fine) or then via UNC (error message):

```
root@WIN10PC:/mnt/a_unc# borg init --encryption=repokey borgtest/
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4703, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4635, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 162, in wrapper
    with repository:
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 188, in __enter__
    self.create(self.path)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 287, in create
    self.save_config(path, config)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 313, in save_config
    config.write(fd)
  File "/usr/lib/python3/dist-packages/borg/platform/base.py", line 172, in __exit__
    self.fd.close()
  File "/usr/lib/python3/dist-packages/borg/platform/base.py", line 140, in close
    platform.sync_dir(dirname)
  File "/usr/lib/python3/dist-packages/borg/platform/base.py", line 60, in sync_dir
    os.fsync(fd)
OSError: [Errno 5] Input/output error

Platform: Linux WIN10PC 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64
Linux: Unknown Linux
Borg: 1.1.17  Python: CPython 3.8.10 msgpack: 0.5.6.+borg1
PID: 2391  CWD: /mnt/a_unc
sys.argv: ['/usr/bin/borg', 'init', '--encryption=repokey', 'borgtest/']
SSH_ORIGINAL_COMMAND: None

root@WIN10PC:/mnt/a_unc# rm -rv borgtest/*
removed 'borgtest/README'
removed 'borgtest/config.tmp'
removed directory 'borgtest/data'
root@WIN10PC:/mnt/a_unc# cd ..
root@WIN10PC:/mnt# cd a
root@WIN10PC:/mnt/a# borg init --encryption=repokey borgtest/
Enter new passphrase:
Enter same passphrase again:
Do you want your passphrase to be displayed for verification? [yN]:

By default repositories initialized with this version will produce security
errors if written to with an older version (up to and including Borg 1.0.8).

If you want to use these older versions, you can disable the check by running:
borg upgrade --disable-tam borgtest

See https://borgbackup.readthedocs.io/en/stable/changes.html#pre-1-0-9-manifest-spoofing-vulnerability for details about the security implications.

IMPORTANT: you will need both KEY AND PASSPHRASE to access this repo!
If you used a repokey mode, the key is stored in the repo, but you should back it up separately.
Use "borg key export" to export the key, optionally in printable format.
Write down the passphrase. Store both at safe place(s).

root@WIN10PC:/mnt/a# ls -lah borgtest/
total 45K
drwxrwxrwx 1 user user 512 Sep  2 10:40 .
drwxrwxrwx 1 user user 512 Sep  2 10:16 ..
-rwxrwxrwx 1 user user  73 Sep  2 10:40 README
-rwxrwxrwx 1 user user 700 Sep  2 10:40 config
drwxrwxrwx 1 user user 512 Sep  2 10:40 data
-rwxrwxrwx 1 user user  52 Sep  2 10:40 hints.1
-rwxrwxrwx 1 user user 41K Sep  2 10:40 index.1
-rwxrwxrwx 1 user user 190 Sep  2 10:40 integrity.1
-rwxrwxrwx 1 user user  16 Sep  2 10:40 nonce

root@WIN10PC:/mnt/a# mount | grep '/mnt/a'
A:\ on /mnt/a type 9p (rw,noatime,dirsync,aname=drvfs;path=A:\;uid=1000;gid=1000;symlinkroot=/mnt/,mmap,access=client,msize=65536,trans=fd,rfd=8,wfd=8)
//localhost/a on /mnt/a_unc type 9p (rw,relatime,dirsync,aname=drvfs;path=UNC\localhost/a;symlinkroot=/mnt/,mmap,access=client,msize=65536,trans=fd,rfd=3,wfd=3)
```

## Describe the problem you're observing

I try to backup an UNC path via BorgBackup. My goal is to mount two UNC paths: one is the backup source and one is the backup destination with the borg repository. After mounting both paths under /mnt I want to use borg for the backup.
If the repository is mounted on a local drive (USB drive for example) it is working fine but if the repository is mounted on the same drive but mounted via UNC path there is an error.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue

Yes I can reproduce the problem via repository init or if I'm using an exisiting and working repository, mount it via UNC and want to backup to this destination. So something is different with an UNC mounted path versus a mounted local drive. But what? I tried a normal user and root but there is no difference.

#### Include any warning/errors/backtraces from the system logs

I have no other logfiles or error message besides the command output errors.

**Comment by ThomasWaldmann** [comment]
Well, it looks like fsync on a file descriptor is not working. That rather looks like a bug in WSL or the fs you use than in borg.

**Comment by miridigital** [comment]
Wow - I've got a very simple and working workaround! Downgrade Ubuntu from WSL2 to WSL1 ! Works without any data loss in a couple of minutes. Thats all I had to do:

```
Microsoft Windows [Version 10.0.19042.1202]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

C:\>wsl -l -v
  NAME      STATE           VERSION
* Ubuntu    Running         2

C:\> wsl --set-version Ubuntu 1
Die Konvertierung wird ausgeführt. Dieser Vorgang kann einige Minuten dauern...
Die Konvertierung ist beendet.

C:\>wsl -l -v
  NAME      STATE           VERSION
* Ubuntu    Stopped         1
```

After that, everything is working fine (init and create)! :-)

I'm wondering what's the reason/difference in file handling between WSL Version 1 and WSL Version 2 ?

**Comment by enkore** [comment]
iirc - WSL1 is a re-implementation of Linux syscalls, WSL2 is a Linux kernel in a VM. I'd expect the filesystem implementations to be largely different codebases, even if the exposed feature / control command has the same name (for compatibility most likely).

**Comment by ThomasWaldmann** [comment]
Obviously, the difference is that they have different bugs. :-)

**Comment by miridigital** [comment]
Maybe Microsoft will read this and fix the WSL2 bug :-) In the meantime WSL1 is working fine for me => close.

**Comment by sintayehuCSE** [comment]
I changed from WLS1 to WSL2 and that solved the issue for me. Command used: wsl --set-version {Distro} {Version}

**Comment by ThomasWaldmann** [comment]
@sintayehuCSE Interesting, considering there are other comments above reporting success for the opposite direction (WLS2 -> WSL1).
