### ISSUE TITLE
Borg demands a BORG_CONFIG_DIR even if SECURITY and KEYS dirs are both set

### ISSUE THREAD

**Issue by dechamps** [borgbackup/borg#5979]
On Borg 1.1.16, the following used to work:

```
$ mkdir security cache
$ BORG_SECURITY_DIR=security BORG_CACHE_DIR=cache BORG_CONFIG_DIR=/dev/null borg init -e none borg
```

But on Borg 1.1.17 it doesn't:

```
Error: File exists
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/helpers.py", line 528, in ensure_dir
    os.makedirs(path, mode=mode, exist_ok=True)
  File "/usr/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/dev/null'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4703, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4635, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 177, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 301, in do_init
    with Cache(repository, key, manifest, warn_if_unencrypted=False):
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 387, in __new__
    return local()
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 379, in local
    return LocalCache(repository=repository, key=key, manifest=manifest, path=path, sync=sync,
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 456, in __init__
    self.security_manager = SecurityManager(repository)
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 64, in __init__
    self.dir = get_security_dir(repository.id_str)
  File "/usr/lib/python3/dist-packages/borg/helpers.py", line 564, in get_security_dir
    security_dir = os.environ.get('BORG_SECURITY_DIR', os.path.join(get_config_dir(), 'security'))
  File "/usr/lib/python3/dist-packages/borg/helpers.py", line 604, in get_config_dir
    ensure_dir(config_dir)
  File "/usr/lib/python3/dist-packages/borg/helpers.py", line 531, in ensure_dir
    raise Error(e.args[1])
borg.helpers.Error: Error: File exists
```

I suspect the culprit is aa7a76cf3597be951508a87273e90df8720221c3.

Borg should not demand a valid `BORG_CONFIG_DIR` when it doesn't actually need one (in this case, because `BORG_SECURITY_DIR` and `BORG_CACHE_DIR` have both been set). Perhaps the `get_config_dir()` call should occur after the `os.environ.get()` check.

**Comment by ThomasWaldmann** [comment]
these _DIR env vars need to point to a directory, `/dev/null` is a file, not a directory.

also, although the security dir is inside the config dir, it is not necessarily (now or forever) the only directory in there.

that said, I'll have a look at the code now to check whether something can be improved...

**Comment by ThomasWaldmann** [comment]
@dechamps see #5985.

**Comment by ThomasWaldmann** [comment]
BTW, this seems totally unrelated to the CACHE dir, but **is also related** to the KEYS dir.
