### ISSUE TITLE
Local exception during archive creation

### ISSUE THREAD

**Issue by symetryczny** [borgbackup/borg#5990]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue

#### Your borg version (borg -V).

1.1.15

#### Operating system (distribution) and version.

Linux unraid 5.10.28-Unraid (6.9.2)

#### Hardware / network configuration, and filesystems used.

XFS, USB-HDD

#### How much data is handled by borg?

Single archive size ~ 1.6 TB, all archive sizes ~ 26 TB, ~200k files per archive

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

export BORG_REPO='/mnt/disks/ST2000LM003_HN-M201RAD_S00RJ9FG500000/borg/'
export BORG_PASSPHRASE='passphrase
borg create --stats ::{now} /mnt/user/{appdata/nextcloud-appdata_xxxxx,nextcloud,backup/{appdata_backup,flashdrive_backup}} --exclude '/mnt/user/appdata/nextcloud-appdata_xxxxx/preview/' >> /var/log/borg 2>&1 '

## Describe the problem you're observing.

I receive the following error:
```
Local Exception.68 GB C 0 B D 123798 N mnt/user/nextcloud/cloud/user/files/Photos/2018-08-16/RAW/JS-1873.NEF 
Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/borg/archiver.py", line 4621, in main
    exit_code = archiver.run(args)
  File "/usr/lib64/python3.9/site-packages/borg/archiver.py", line 4553, in run
    return set_ec(func(args))
  File "/usr/lib64/python3.9/site-packages/borg/archiver.py", line 177, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib64/python3.9/site-packages/borg/archiver.py", line 590, in do_create
    create_inner(archive, cache)
  File "/usr/lib64/python3.9/site-packages/borg/archiver.py", line 551, in create_inner
    self._process(archive, cache, matcher, args.exclude_caches, args.exclude_if_present,
  File "/usr/lib64/python3.9/site-packages/borg/archiver.py", line 665, in _process
    self._process(archive, cache, matcher, exclude_caches, exclude_if_present,
  File "/usr/lib64/python3.9/site-packages/borg/archiver.py", line 665, in _process
    self._process(archive, cache, matcher, exclude_caches, exclude_if_present,
  File "/usr/lib64/python3.9/site-packages/borg/archiver.py", line 665, in _process
    self._process(archive, cache, matcher, exclude_caches, exclude_if_present,
  [Previous line repeated 5 more times]
  File "/usr/lib64/python3.9/site-packages/borg/archiver.py", line 641, in _process
    status = archive.process_file(path, st, cache)
  File "/usr/lib64/python3.9/site-packages/borg/archive.py", line 1086, in process_file
    self.chunk_file(item, cache, self.stats, backup_io_iter(self.chunker.chunkify(fd, fh)))
  File "/usr/lib64/python3.9/site-packages/borg/archive.py", line 1008, in chunk_file
    from_chunk, part_number = self.write_part_file(item, from_chunk, part_number)
  File "/usr/lib64/python3.9/site-packages/borg/archive.py", line 986, in write_part_file
    self.write_checkpoint()
  File "/usr/lib64/python3.9/site-packages/borg/archive.py", line 480, in write_checkpoint
    self.save(self.checkpoint_name)
  File "/usr/lib64/python3.9/site-packages/borg/archive.py", line 526, in save
    self.manifest.write()
  File "/usr/lib64/python3.9/site-packages/borg/helpers.py", line 455, in write
    self.repository.put(self.MANIFEST_ID, self.key.encrypt(data))
  File "/usr/lib64/python3.9/site-packages/borg/repository.py", line 1138, in put
    self.segments[segment] -= 1
KeyError: 7622

Platform: Linux unraid 5.10.28-Unraid #1 SMP Wed Apr 7 08:23:18 PDT 2021 x86_64
Linux: Unknown Linux  
Borg: 1.1.15  Python: CPython 3.9.0 msgpack: 0.5.6
PID: 26799  CWD: /root
sys.argv: ['/usr/bin/borg', 'create', '--progress', '--stats', '::{now}', '/mnt/user/nextcloud-appdata_xxxxx/', '/mnt/user/nextcloud', '/mnt/user/backup/appdata_backup', '/mnt/user/backup/flashdrive_backup', '--exclude', '/mnt/user/nextcloud-appdata_xxxxx/preview/']
SSH_ORIGINAL_COMMAND: None
```
#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

I can reproduce the problem each time by running the same command. The problem does not occur when I change what is to be archived by removing some of the directories/paths. Maybe there is a limit of number of files or total repository size?

I checked the repository integrity and is passed with no errors.

**Comment by ThomasWaldmann** [comment]
It looks like your repo index is corrupted.

I suggest you first make sure your hw is working correctly, run memtest86+ and smartctl to do a SMART long test on your disk.

If hw works correctly, run `borg check --repair ...` on your repo.

**Comment by symetryczny** [comment]
Thanks for your suggestion @ThomasWaldmann.

I ran `borg check` already and it shows no errors, passes without issues.

What is weird is that I purged some old archives, re-ran the initial `org create` command and it completed without errors now. I guess this ticket can be closed. issue got resolved by itself.

**Comment by jdchristensen** [comment]
It sounds like an intermittent hardware error.  Borg is very good at revealing those.  You should definitely check the ram and the disk, as TW suggested.

**Comment by ThomasWaldmann** [comment]
Guess this is solved.
