### ISSUE TITLE
Connection closed by remote host. Is borg working on the server?

### ISSUE THREAD

**Issue by alidasomi** [borgbackup/borg#6013]
I use rsync.net as storage for my borgbackup.
sometimes it throw this error:

```
Remote:   File "inspect.py", line 725, in getmodule
Remote:   File "inspect.py", line 708, in getabsfile
Remote:   File "inspect.py", line 696, in getsourcefile
Remote:   File "inspect.py", line 725, in getmodule
Remote:   File "inspect.py", line 709, in getabsfile
Remote:   File "posixpath.py", line 383, in abspath
Remote: PermissionError: [Errno 13] Permission denied
Connection closed by remote host. Is borg working on the server?
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/borg/archiver.py", line 4621, in main
    exit_code = archiver.run(args)
  File "/usr/local/lib/python3.8/dist-packages/borg/archiver.py", line 4553, in run
    return set_ec(func(args))
  File "/usr/local/lib/python3.8/dist-packages/borg/archiver.py", line 155, in wrapper
    repository = RemoteRepository(location, create=create, exclusive=argument(args, exclusive),
  File "/usr/local/lib/python3.8/dist-packages/borg/remote.py", line 576, in __init__
    raise ConnectionClosedWithHint('Is borg working on the server?') from None
borg.remote.ConnectionClosedWithHint: Connection closed by remote host. Is borg working on the server?
Platform: Linux AF-SHD-MAAS28 5.4.0-67-generic #75-Ubuntu SMP Fri Feb 19 18:03:38 UTC 2021 x86_64
Linux: Unknown Linux
Borg: 1.1.15  Python: CPython 3.8.10 msgpack: 0.5.6
PID: 306233  CWD: /root
sys.argv: ['/usr/local/bin/borg', 'check', '--archives-only', '--last', '1', '--prefix', '20', '--debug', '--show-rc', 'zh1111@zh1111.rsync.net:backup/test/database']
SSH_ORIGINAL_COMMAND: None
terminating with error status, rc 2

```

This not happened always. Its random.

**Comment by tuxick** [comment]
In my experience it's never been a problem with borg on the server. In many cases i could trace it back to temporary network issues.
I suggest changing the message to "try borg --debug".

**Comment by ThomasWaldmann** [comment]
Guess this was solved.
