### ISSUE TITLE
Poor error reporting

### ISSUE THREAD

**Issue by pjoc** [borgbackup/borg#6018]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue

## System information. For client/server mode post info for both machines.
Intel x86_64
#### Your borg version (borg -V).
1.1.17
#### Operating system (distribution) and version.
Fedora 34
#### Hardware / network configuration, and filesystems used.
Local (not network), BTRFS on source and destination.
#### How much data is handled by borg?
1TB approx.
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg --verbose prune --dry-run --keep-daily 7 /raid/Backups/Borg

## Describe the problem you're observing.
Borg often produces a stack trace instead of an intelligible error message. Two recent examples:
1) Running as normal user rather than root. Should just report the error directly.
2) Running a regular backup when there's a problem with the cache. This took several days and a Fedora Bugzilla report to understand. Fixed by deleting the cache.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
100% reproducible.
#### Include any warning/errors/backtraces from the system logs

Killed stale lock Bree@88230071515343.79358-0.
Removed stale exclusive roster lock for host Bree@88230071515343 pid 79358 thread 0.
Removed stale exclusive roster lock for host Bree@88230071515343 pid 79358 thread 0.
Local Exception
Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/borg/archiver.py", line 4703, in main
    exit_code = archiver.run(args)
  File "/usr/lib64/python3.9/site-packages/borg/archiver.py", line 4635, in run
    return set_ec(func(args))
  File "/usr/lib64/python3.9/site-packages/borg/archiver.py", line 177, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib64/python3.9/site-packages/borg/archiver.py", line 1652, in do_prune
    with Cache(repository, key, manifest, lock_wait=self.lock_wait) as cache:
  File "/usr/lib64/python3.9/site-packages/borg/cache.py", line 387, in __new__
    return local()
  File "/usr/lib64/python3.9/site-packages/borg/cache.py", line 379, in local
    return LocalCache(repository=repository, key=key, manifest=manifest, path=path, sync=sync,
  File "/usr/lib64/python3.9/site-packages/borg/cache.py", line 464, in __init__
    self.open()
  File "/usr/lib64/python3.9/site-packages/borg/cache.py", line 512, in open
    self.rollback()
  File "/usr/lib64/python3.9/site-packages/borg/cache.py", line 629, in rollback
    self._do_open()
  File "/usr/lib64/python3.9/site-packages/borg/cache.py", line 500, in _do_open
    with IntegrityCheckedFile(path=os.path.join(self.path, 'chunks'), write=False,
  File "/usr/lib64/python3.9/site-packages/borg/crypto/file_integrity.py", line 129, in __init__
    self.file_fd = override_fd or open(path, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/borg/fdef744d1c0e14810c75f47f54ffae8f5c4b1ae3bff6481f3fd2ed9a0c11913f/chunks'

Platform: Linux Bree 5.14.11-200.fc34.x86_64 #1 SMP Sun Oct 10 14:39:31 UTC 2021 x86_64
Linux: Unknown Linux  
Borg: 1.1.17  Python: CPython 3.9.7 msgpack: 0.5.6.+borg1
PID: 86810  CWD: /root
sys.argv: ['/usr/bin/borg', '--verbose', 'prune', '--dry-run', '--keep-daily', '7', '/raid/Backups/Borg']
SSH_ORIGINAL_COMMAND: None

**Comment by ThomasWaldmann** [comment]
Maybe #7513 fixes this, but guess it will need some testing in practice.

Just reopen a new ticket if it doesn't.
