### ISSUE TITLE
darwin64 vagrant box fails to build borg binary

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#6252]
```
    darwin64: 32389 INFO: Removing signature(s) from EXE                                                                                            [300/15469]
    darwin64: 33847 INFO: Appending PKG archive to EXE                                                                                                         
    darwin64: 33869 INFO: Fixing EXE headers for code signing                                                                                                  
    darwin64: Traceback (most recent call last):                                                                                                               
    darwin64:   File "/Users/vagrant/.pyenv/versions/3.9.10/envs/borg-env/bin/pyinstaller", line 33, in <module>                                               
    darwin64:     sys.exit(load_entry_point('pyinstaller==4.7', 'console_scripts', 'pyinstaller')())                                                           
    darwin64:   File "/Users/vagrant/.pyenv/versions/3.9.10/envs/borg-env/lib/python3.9/site-packages/pyinstaller-4.7-py3.9.egg/PyInstaller/__main__.py", line 
124, in run                                                                                                                                                    
    darwin64:     run_build(pyi_config, spec_file, **vars(args))                                                                                               
    darwin64:   File "/Users/vagrant/.pyenv/versions/3.9.10/envs/borg-env/lib/python3.9/site-packages/pyinstaller-4.7-py3.9.egg/PyInstaller/__main__.py", line 
58, in run_build                                                                                                                                               
    darwin64:     PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)                                                                        
    darwin64:   File "/Users/vagrant/.pyenv/versions/3.9.10/envs/borg-env/lib/python3.9/site-packages/pyinstaller-4.7-py3.9.egg/PyInstaller/building/build_main
.py", line 782, in main                                                                                                                                        
    darwin64:     build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))                                                               
    darwin64:   File "/Users/vagrant/.pyenv/versions/3.9.10/envs/borg-env/lib/python3.9/site-packages/pyinstaller-4.7-py3.9.egg/PyInstaller/building/build_main
.py", line 714, in build                                                                                                                                       
    darwin64:     exec(code, spec_namespace)                                                                                                                   
    darwin64:   File "scripts/borg.exe.spec", line 42, in <module>                                                                                             
    darwin64:     exe = EXE(pyz,                                                                                                                               
    darwin64:   File "/Users/vagrant/.pyenv/versions/3.9.10/envs/borg-env/lib/python3.9/site-packages/pyinstaller-4.7-py3.9.egg/PyInstaller/building/api.py", l
ine 507, in __init__                                                                                                                                           
    darwin64:     self.__postinit__()                                                                                                                          
    darwin64:   File "/Users/vagrant/.pyenv/versions/3.9.10/envs/borg-env/lib/python3.9/site-packages/pyinstaller-4.7-py3.9.egg/PyInstaller/building/datastruct
.py", line 155, in __postinit__                                                                                                                                
    darwin64:     self.assemble()                                                                                                                              
    darwin64:   File "/Users/vagrant/.pyenv/versions/3.9.10/envs/borg-env/lib/python3.9/site-packages/pyinstaller-4.7-py3.9.egg/PyInstaller/building/api.py", l
ine 715, in assemble                                                                                                                                           
    darwin64:     osxutils.fix_exe_for_code_signing(self.name)                                                                                                 
    darwin64:   File "/Users/vagrant/.pyenv/versions/3.9.10/envs/borg-env/lib/python3.9/site-packages/pyinstaller-4.7-py3.9.egg/PyInstaller/utils/osx.py", line
 178, in fix_exe_for_code_signing                                                                                                                              
    darwin64:     assert len(sign_sec) == 0, "Executable contains code signature!"                                                                             
    darwin64: AssertionError: Executable contains code signature!                                                                                              
```

**Comment by ThomasWaldmann** [comment]
Strange: this worked for 1.2.0b4 and now fails for 1.2.0rc1.

**Comment by ThomasWaldmann** [comment]
https://github.com/pyinstaller/pyinstaller/pull/6398 not sure whether that is related. guess we don't do universal2 binaries (yet).

**Comment by ThomasWaldmann** [comment]
https://github.com/pyinstaller/pyinstaller/issues/6430 guess it is that. Also noticable: "Sometimes ..." - so just retry?

**Comment by ThomasWaldmann** [comment]
workaround: just **retrying until it works**. wtf?

**Comment by ThomasWaldmann** [comment]
last time i tried it worked. closing for now.
