### ISSUE TITLE
borg create crashes if parent dir of recursion root can not be opened

### ISSUE THREAD

**Issue by skibbipl** [borgbackup/borg#6374]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug?

#### Your borg version (borg -V).
borg 1.2.0

#### Operating system (distribution) and version.
Linux xxxx 5.16.0-1-amd64 #1 SMP PREEMPT Debian 5.16.7-2 (2022-02-09) x86_64 GNU/Linux

#### Hardware / network configuration, and filesystems used.
ext4, nothing fancy

## Describe the problem you're observing.
After upgrading to 1.2 borg crashes when it cannot find file from the configuration. In 1.1.x version it skipped it with warning.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Add non exisiting file to backup script.

#### Include any warning/errors/backtraces from the system logs

```
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 264, in OsOpen
    fd = os_open(path=path, parent_fd=parent_fd, name=name, flags=flags, noatime=noatime)
  File "/usr/lib/python3/dist-packages/borg/helpers/fs.py", line 290, in os_open
    fd = os.open(fname, _flags_noatime, dir_fd=parent_fd)
FileNotFoundError: [Errno 2] No such file or directory: '/etc/dnsmasq.d'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 5089, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 5020, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 183, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 668, in do_create
    create_inner(archive, cache, fso)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 595, in create_inner
    with OsOpen(path=parent_dir, flags=flags_root, noatime=True, op='open_root') as parent_fd:
  File "/usr/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 264, in OsOpen
    fd = os_open(path=path, parent_fd=parent_fd, name=name, flags=flags, noatime=noatime)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 218, in __exit__
    raise BackupOSError(self.op, exc_val) from exc_val
borg.archive.BackupOSError: open_root: [Errno 2] No such file or directory: '/etc/dnsmasq.d'

Platform: Linux xxxxx 5.16.0-1-amd64 #1 SMP PREEMPT Debian 5.16.7-2 (2022-02-09) x86_64
Linux: Unknown Linux
Borg: 1.2.0  Python: CPython 3.9.10 msgpack: 1.0.3 fuse: pyfuse3 3.2.0 [pyfuse3,llfuse]
```

**Comment by ThomasWaldmann** [comment]
Please give the precise command that led to that traceback.

**Comment by skibbipl** [comment]
Standard `borg create`:
```
borg create                                             \
    --verbose                                           \
    --filter=AME                                        \
    --list                                              \
    --stats                                             \
    --show-rc                                           \
    --compression=lzma,9                                \
    --exclude 'lost+found/*'                            \
    --exclude '*.git/'                                  \
    --exclude '*~'                                      \
                                                        \
    ::'{hostname}-{now}'                                \
    ...                                                 \
    /etc/dnsmasq.d/`hostname`.conf                      \
    ...
```

**Comment by ThomasWaldmann** [comment]
Thanks for reporting this issue, I could reproduce and fix it.

Just a hint (unrelated to this bug):

You use lzma,9 - that is super slow and likely wastes a lot of cpu cycles for nothing.

See our docs about the maximum recommended lzma level and maybe even better: consider using zstd (much more modern and likely better/faster than lzma).

**Comment by skibbipl** [comment]
Great news. About that lzma, you're absolutely right. This is just an old server and the backup script was configured long time ago. I use zstd on other boxes with borgbackup.
