### ISSUE TITLE
Exception('Could not find OpenSSL lib/headers)

### ISSUE THREAD

**Issue by vincenzogianfelice** [borgbackup/borg#6390]
```
root@debian:~# pip3 install borgbackup                             
Collecting borgbackup
  Downloading borgbackup-1.2.0.tar.gz (4.0 MB)
     |████████████████████████████████| 4.0 MB 2.1 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1bk9k427/borgbackup_c6e7b3f5fc444c53a6556db616e3dc39/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1bk9k427/borgbackup_c6e7b3f5fc444c53a6556db616e3dc39/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-e2ds4rdh                                      
         cwd: /tmp/pip-install-1bk9k427/borgbackup_c6e7b3f5fc444c53a6556db616e3dc39/                    
    Complete output (8 lines):                                                                          
    Traceback (most recent call last):                                                                  
      File "<string>", line 1, in <module>                                                              
      File "/tmp/pip-install-1bk9k427/borgbackup_c6e7b3f5fc444c53a6556db616e3dc39/setup.py", line 185, in <module>                                                                                              
        setup_crypto.crypto_ext_kwargs(pc, system_prefix_openssl),                                      
      File "/tmp/pip-install-1bk9k427/borgbackup_c6e7b3f5fc444c53a6556db616e3dc39/setup_crypto.py", line 32, in crypto_ext_kwargs
        raise Exception('Could not find OpenSSL lib/headers, please set BORG_OPENSSL_PREFIX')
    Exception: Could not find OpenSSL lib/headers, please set BORG_OPENSSL_PREFIX
    Warning: can not import pkgconfig python package.
    ----------------------------------------
```

- Debian 11(x64)
- **libssl-dev** (**1.1.1k-1+deb11u1**)

**Comment by ThomasWaldmann** [comment]
You need to read the docs (either `pip install pkgconfig` first or if that does not help, use env var `BORG_OPENSSL_PREFIX`).

**Comment by ThomasWaldmann** [comment]
I usually need this (check the path, yours may vary):
```
export BORG_OPENSSL_PREFIX=/opt/homebrew/opt/openssl@1.1
```

**Comment by nijel** [comment]
Why is `pkgconfig` not listed as [build system requirement](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#build-system-requirement)? `pip install borgbackup` would then work just fine without need of additional installation (which is annoying).

**Comment by ThomasWaldmann** [comment]
I once tried `setup_requires` (in `setup.py`) and that did not work, because `pkgconfig` is already needed at import time.

Also, there is no `pyproject.toml` in 1.2-maint branch (but we recently added it to master for other reasons, so we could try it there).

**Comment by nijel** [comment]
Yes, `setup_requires` can be late (and that's one of the reasons it is deprecated). Is there any plan to introduce `pyproject.toml` to 1.2 maintenance release?

**Comment by ThomasWaldmann** [comment]
A PR for a **minimal** change improving this issue would be welcome.

== take only minimum from master needed to fix the problem.
