### ISSUE TITLE
installation by pip3 fails due to missing header

### ISSUE THREAD

**Issue by lfam** [borgbackup/borg#64]
Debian 8.1, running on armv7. It seems that GCC can't find ```pyconfig.h```. Let me know what other information you need.

By the way, I am not well-versed in python package management. I could be making a very basic error.

```
$ pip3 install borgbackup 
Downloading/unpacking borgbackup
  Getting page https://pypi.python.org/simple/borgbackup/
  URLs to search for versions for borgbackup:
  * https://pypi.python.org/simple/borgbackup/
  Analyzing links from page https://pypi.python.org/simple/borgbackup/
    Found link https://pypi.python.org/packages/source/b/borgbackup/borgbackup-0.23.0.tar.gz#md5=77fba21ce1d2bdedd7945f2f58ee1b4f (from https://pypi.python.org/simple/borgbackup/), version: 0.23.0
  Downloading from URL https://pypi.python.org/packages/source/b/borgbackup/borgbackup-0.23.0.tar.gz#md5=77fba21ce1d2bdedd7945f2f58ee1b4f (from https://pypi.python.org/simple/borgbackup/)
  Running setup.py (path:/tmp/pip-build-1n22fxxk/borgbackup/setup.py) egg_info for package borgbackup
    running egg_info
    creating pip-egg-info/borgbackup.egg-info
    writing requirements to pip-egg-info/borgbackup.egg-info/requires.txt
    writing pip-egg-info/borgbackup.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/borgbackup.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/borgbackup.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/borgbackup.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'pip-egg-info/borgbackup.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
    no previously-included directories found matching 'docs/_build'
    writing manifest file 'pip-egg-info/borgbackup.egg-info/SOURCES.txt'
  Source in /tmp/pip-build-1n22fxxk/borgbackup has version 0.23.0, which satisfies requirement borgbackup
Downloading/unpacking msgpack-python>=0.4.6 (from borgbackup)
  Getting page https://pypi.python.org/simple/msgpack-python/
  URLs to search for versions for msgpack-python>=0.4.6 (from borgbackup):
  * https://pypi.python.org/simple/msgpack-python/
  Analyzing links from page https://pypi.python.org/simple/msgpack-python/
    Skipping link https://pypi.python.org/packages/2.7/m/msgpack-python/msgpack-python-0.3.0.win-amd64-py2.7.exe#md5=d482b1169ac997c1d34b817d3c85ccbd (from https://pypi.python.org/simple/msgpack-python/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/2.7/m/msgpack-python/msgpack-python-0.3.0.win32-py2.7.exe#md5=25d5b77a7dcb6f4ee655a6f5d88313b6 (from https://pypi.python.org/simple/msgpack-python/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/2.7/m/msgpack-python/msgpack_python-0.2.0-py2.7-win-amd64.egg#md5=a8d0d3ce2b02fdc0b053e835c14726c5 (from https://pypi.python.org/simple/msgpack-python/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/2.7/m/msgpack-python/msgpack_python-0.2.0-py2.7-win32.egg#md5=d52bd856ca8c8d9a6ee86937e1b4c644 (from https://pypi.python.org/simple/msgpack-python/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/2.7/m/msgpack-python/msgpack_python-0.3.0-py2.7-win-amd64.egg#md5=b2015ad4316ddbd8688693542769413d (from https://pypi.python.org/simple/msgpack-python/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/2.7/m/msgpack-python/msgpack_python-0.3.0-py2.7-win32.egg#md5=d9fee3a6bb8aec510dbec5a55fbc3d16 (from https://pypi.python.org/simple/msgpack-python/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/3.2/m/msgpack-python/msgpack_python-0.2.0-py3.2-win-amd64.egg#md5=4ac6e179b3dfe9a919e98e72fbe62965 (from https://pypi.python.org/simple/msgpack-python/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/3.2/m/msgpack-python/msgpack_python-0.2.0-py3.2-win32.egg#md5=985a37940d2bb87637f851e614f3b96e (from https://pypi.python.org/simple/msgpack-python/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/3.3/m/msgpack-python/msgpack-python-0.3.0.win-amd64-py3.3.exe#md5=327350979a89422556a94902fa982885 (from https://pypi.python.org/simple/msgpack-python/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/3.3/m/msgpack-python/msgpack-python-0.3.0.win32-py3.3.exe#md5=7df5d4b72621f5c5f5a40177f953fa94 (from https://pypi.python.org/simple/msgpack-python/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/3.3/m/msgpack-python/msgpack_python-0.2.3-py3.3-win-amd64.egg#md5=ff6fbd6170874140f76d9ac077ec4fef (from https://pypi.python.org/simple/msgpack-python/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/3.3/m/msgpack-python/msgpack_python-0.2.3-py3.3-win32.egg#md5=011a6114a3f377dd4d1869d3237cf935 (from https://pypi.python.org/simple/msgpack-python/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/3.3/m/msgpack-python/msgpack_python-0.3.0-py3.3-win-amd64.egg#md5=9bcfca39afa8219d12048f97a5d2a2df (from https://pypi.python.org/simple/msgpack-python/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/3.3/m/msgpack-python/msgpack_python-0.3.0-py3.3-win32.egg#md5=b7032156929c5f424e583ec97a11521b (from https://pypi.python.org/simple/msgpack-python/); unknown archive format: .egg
    Skipping https://pypi.python.org/packages/3.4/m/msgpack-python/msgpack_python-0.4.2-cp34-none-win32.whl#md5=dda44ef5bd9dc0458fc3805507526e2b (from https://pypi.python.org/simple/msgpack-python/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/3.4/m/msgpack-python/msgpack_python-0.4.2-cp34-none-win_amd64.whl#md5=dcb0ee896c2f1ea5c09b1af8b3bb8901 (from https://pypi.python.org/simple/msgpack-python/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/cp27/m/msgpack-python/msgpack_python-0.4.3-cp27-none-win32.whl#md5=7d91f8e5e40bd6823a7477ce24670363 (from https://pypi.python.org/simple/msgpack-python/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/cp27/m/msgpack-python/msgpack_python-0.4.3-cp27-none-win_amd64.whl#md5=37ab6db5247b2f8730615cd59fa6cb33 (from https://pypi.python.org/simple/msgpack-python/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/cp27/m/msgpack-python/msgpack_python-0.4.6-cp27-none-win32.whl#md5=f1ddd501644867049836225ecc4b1198 (from https://pypi.python.org/simple/msgpack-python/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/cp27/m/msgpack-python/msgpack_python-0.4.6-cp27-none-win_amd64.whl#md5=73b9b22edd0a42637afb5963585b8d5e (from https://pypi.python.org/simple/msgpack-python/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/cp34/m/msgpack-python/msgpack_python-0.4.3-cp34-none-win32.whl#md5=07c2c9bbe330b7515a8f0b4316c2d03e (from https://pypi.python.org/simple/msgpack-python/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/cp34/m/msgpack-python/msgpack_python-0.4.3-cp34-none-win_amd64.whl#md5=cb936061a79dee07657bf2eaaa7179fc (from https://pypi.python.org/simple/msgpack-python/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/cp34/m/msgpack-python/msgpack_python-0.4.6-cp34-none-win32.whl#md5=d95ea9552d5d7767bc1c017120abeee3 (from https://pypi.python.org/simple/msgpack-python/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/cp34/m/msgpack-python/msgpack_python-0.4.6-cp34-none-win_amd64.whl#md5=0947fb08fc6d2116220e7e93424464b7 (from https://pypi.python.org/simple/msgpack-python/) because it is not compatible with this Python
    Found link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.1.10.tar.gz#md5=a31f16d20ea8ec79cc8cba1103f951d8 (from https://pypi.python.org/simple/msgpack-python/), version: 0.1.10
    Found link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.1.11.tar.gz#md5=900cfc1b085c0a4058bc67fae617415a (from https://pypi.python.org/simple/msgpack-python/), version: 0.1.11
    Found link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.1.12.tar.gz#md5=121a203e961b566f2039f527f3556a5d (from https://pypi.python.org/simple/msgpack-python/), version: 0.1.12
    Found link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.1.13.tar.gz#md5=a6781bf2b670963c0ff1316976e66b14 (from https://pypi.python.org/simple/msgpack-python/), version: 0.1.13
    Found link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.1.3.tar.gz#md5=d9b486424706ba422ac1199898829263 (from https://pypi.python.org/simple/msgpack-python/), version: 0.1.3
    Found link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.1.4.tar.gz#md5=f50410aca1ef48cd2181f9885feaf3d2 (from https://pypi.python.org/simple/msgpack-python/), version: 0.1.4
    Found link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.1.6.tar.gz#md5=d4c9e0c6d03542659e8980cc011cb32e (from https://pypi.python.org/simple/msgpack-python/), version: 0.1.6
    Found link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.1.7.tar.gz#md5=95750dae8f4ee2a365fd548fd5308908 (from https://pypi.python.org/simple/msgpack-python/), version: 0.1.7
    Found link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.1.8.tar.gz#md5=bd1e2d8a755b38a808a6c8edbd6c32ba (from https://pypi.python.org/simple/msgpack-python/), version: 0.1.8
    Found link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.1.9.tar.gz#md5=fea360812fd4bd485c07b03239f1ddd0 (from https://pypi.python.org/simple/msgpack-python/), version: 0.1.9
    Found link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.2.0.tar.gz#md5=cdac1d250cf9c0f0bd36abdfe2c96f8b (from https://pypi.python.org/simple/msgpack-python/), version: 0.2.0
    Found link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.2.1.tar.gz#md5=dbaf026487da6c5302c51a715e36a4e0 (from https://pypi.python.org/simple/msgpack-python/), version: 0.2.1
    Found link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.2.2.tar.gz#md5=5a74289d5c57ec52b54bed440453e5e9 (from https://pypi.python.org/simple/msgpack-python/), version: 0.2.2
    Found link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.2.3.tar.gz#md5=5d6b1c6b2f3dc7dc514f14a67ad75cec (from https://pypi.python.org/simple/msgpack-python/), version: 0.2.3
    Found link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.2.4.tar.gz#md5=c4bb313cd35b57319f588491b1614289 (from https://pypi.python.org/simple/msgpack-python/), version: 0.2.4
    Found link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.3.0.tar.gz#md5=10dec96c90992b0f6e38bdf0cc5a8e79 (from https://pypi.python.org/simple/msgpack-python/), version: 0.3.0
    Found link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.4.0.tar.gz#md5=8b9ce43619fd1428bf7baddf57e38d1a (from https://pypi.python.org/simple/msgpack-python/), version: 0.4.0
    Found link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.4.1.tar.gz#md5=3ff478e75e783f4e69c1a8d5ca63dea4 (from https://pypi.python.org/simple/msgpack-python/), version: 0.4.1
    Found link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.4.2.tar.gz#md5=e3a0fdfd864c72c958bb501d39b39caf (from https://pypi.python.org/simple/msgpack-python/), version: 0.4.2
    Found link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.4.3.tar.gz#md5=f3cc76a0653bffa19bf2b359783ad8a9 (from https://pypi.python.org/simple/msgpack-python/), version: 0.4.3
    Found link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.4.4.tar.gz#md5=86187bcd95b01753a5975424fe42ca81 (from https://pypi.python.org/simple/msgpack-python/), version: 0.4.4
    Found link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.4.5.tar.gz#md5=3b82bc542d5599896695512e7c32f42d (from https://pypi.python.org/simple/msgpack-python/), version: 0.4.5
    Found link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.4.6.tar.gz#md5=8b317669314cf1bc881716cccdaccb30 (from https://pypi.python.org/simple/msgpack-python/), version: 0.4.6
  Ignoring link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.1.10.tar.gz#md5=a31f16d20ea8ec79cc8cba1103f951d8 (from https://pypi.python.org/simple/msgpack-python/), version 0.1.10 doesn't match >=0.4.6
  Ignoring link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.1.11.tar.gz#md5=900cfc1b085c0a4058bc67fae617415a (from https://pypi.python.org/simple/msgpack-python/), version 0.1.11 doesn't match >=0.4.6
  Ignoring link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.1.12.tar.gz#md5=121a203e961b566f2039f527f3556a5d (from https://pypi.python.org/simple/msgpack-python/), version 0.1.12 doesn't match >=0.4.6
  Ignoring link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.1.13.tar.gz#md5=a6781bf2b670963c0ff1316976e66b14 (from https://pypi.python.org/simple/msgpack-python/), version 0.1.13 doesn't match >=0.4.6
  Ignoring link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.1.3.tar.gz#md5=d9b486424706ba422ac1199898829263 (from https://pypi.python.org/simple/msgpack-python/), version 0.1.3 doesn't match >=0.4.6
  Ignoring link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.1.4.tar.gz#md5=f50410aca1ef48cd2181f9885feaf3d2 (from https://pypi.python.org/simple/msgpack-python/), version 0.1.4 doesn't match >=0.4.6
  Ignoring link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.1.6.tar.gz#md5=d4c9e0c6d03542659e8980cc011cb32e (from https://pypi.python.org/simple/msgpack-python/), version 0.1.6 doesn't match >=0.4.6
  Ignoring link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.1.7.tar.gz#md5=95750dae8f4ee2a365fd548fd5308908 (from https://pypi.python.org/simple/msgpack-python/), version 0.1.7 doesn't match >=0.4.6
  Ignoring link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.1.8.tar.gz#md5=bd1e2d8a755b38a808a6c8edbd6c32ba (from https://pypi.python.org/simple/msgpack-python/), version 0.1.8 doesn't match >=0.4.6
  Ignoring link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.1.9.tar.gz#md5=fea360812fd4bd485c07b03239f1ddd0 (from https://pypi.python.org/simple/msgpack-python/), version 0.1.9 doesn't match >=0.4.6
  Ignoring link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.2.0.tar.gz#md5=cdac1d250cf9c0f0bd36abdfe2c96f8b (from https://pypi.python.org/simple/msgpack-python/), version 0.2.0 doesn't match >=0.4.6
  Ignoring link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.2.1.tar.gz#md5=dbaf026487da6c5302c51a715e36a4e0 (from https://pypi.python.org/simple/msgpack-python/), version 0.2.1 doesn't match >=0.4.6
  Ignoring link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.2.2.tar.gz#md5=5a74289d5c57ec52b54bed440453e5e9 (from https://pypi.python.org/simple/msgpack-python/), version 0.2.2 doesn't match >=0.4.6
  Ignoring link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.2.3.tar.gz#md5=5d6b1c6b2f3dc7dc514f14a67ad75cec (from https://pypi.python.org/simple/msgpack-python/), version 0.2.3 doesn't match >=0.4.6
  Ignoring link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.2.4.tar.gz#md5=c4bb313cd35b57319f588491b1614289 (from https://pypi.python.org/simple/msgpack-python/), version 0.2.4 doesn't match >=0.4.6
  Ignoring link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.3.0.tar.gz#md5=10dec96c90992b0f6e38bdf0cc5a8e79 (from https://pypi.python.org/simple/msgpack-python/), version 0.3.0 doesn't match >=0.4.6
  Ignoring link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.4.0.tar.gz#md5=8b9ce43619fd1428bf7baddf57e38d1a (from https://pypi.python.org/simple/msgpack-python/), version 0.4.0 doesn't match >=0.4.6
  Ignoring link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.4.1.tar.gz#md5=3ff478e75e783f4e69c1a8d5ca63dea4 (from https://pypi.python.org/simple/msgpack-python/), version 0.4.1 doesn't match >=0.4.6
  Ignoring link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.4.2.tar.gz#md5=e3a0fdfd864c72c958bb501d39b39caf (from https://pypi.python.org/simple/msgpack-python/), version 0.4.2 doesn't match >=0.4.6
  Ignoring link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.4.3.tar.gz#md5=f3cc76a0653bffa19bf2b359783ad8a9 (from https://pypi.python.org/simple/msgpack-python/), version 0.4.3 doesn't match >=0.4.6
  Ignoring link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.4.4.tar.gz#md5=86187bcd95b01753a5975424fe42ca81 (from https://pypi.python.org/simple/msgpack-python/), version 0.4.4 doesn't match >=0.4.6
  Ignoring link https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.4.5.tar.gz#md5=3b82bc542d5599896695512e7c32f42d (from https://pypi.python.org/simple/msgpack-python/), version 0.4.5 doesn't match >=0.4.6
  Downloading from URL https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.4.6.tar.gz#md5=8b317669314cf1bc881716cccdaccb30 (from https://pypi.python.org/simple/msgpack-python/)
  Running setup.py (path:/tmp/pip-build-1n22fxxk/msgpack-python/setup.py) egg_info for package msgpack-python
    running egg_info
    creating pip-egg-info/msgpack_python.egg-info
    writing pip-egg-info/msgpack_python.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/msgpack_python.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/msgpack_python.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/msgpack_python.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'pip-egg-info/msgpack_python.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/msgpack_python.egg-info/SOURCES.txt'
  Source in /tmp/pip-build-1n22fxxk/msgpack-python has version 0.4.6, which satisfies requirement msgpack-python>=0.4.6 (from borgbackup)
Installing collected packages: borgbackup, msgpack-python
  Running setup.py install for borgbackup
    Running command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-1n22fxxk/borgbackup/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-xrel06ah-record/install-record.txt --single-version-externally-managed --compile
    running install
    running build
    got version from file /tmp/pip-build-1n22fxxk/borgbackup/borg/_version.py {'version': '0.23.0', 'full': 'c7da105fd0a75eec0454762df1dcc84510a2d813'}
    running build_py
    creating build
    creating build/lib.linux-armv7l-3.4
    creating build/lib.linux-armv7l-3.4/borg
    copying borg/xattr.py -> build/lib.linux-armv7l-3.4/borg
    copying borg/archive.py -> build/lib.linux-armv7l-3.4/borg
    copying borg/remote.py -> build/lib.linux-armv7l-3.4/borg
    copying borg/cache.py -> build/lib.linux-armv7l-3.4/borg
    copying borg/key.py -> build/lib.linux-armv7l-3.4/borg
    copying borg/fuse.py -> build/lib.linux-armv7l-3.4/borg
    copying borg/lrucache.py -> build/lib.linux-armv7l-3.4/borg
    copying borg/archiver.py -> build/lib.linux-armv7l-3.4/borg
    copying borg/__init__.py -> build/lib.linux-armv7l-3.4/borg
    copying borg/helpers.py -> build/lib.linux-armv7l-3.4/borg
    copying borg/repository.py -> build/lib.linux-armv7l-3.4/borg
    copying borg/platform.py -> build/lib.linux-armv7l-3.4/borg
    copying borg/_version.py -> build/lib.linux-armv7l-3.4/borg
    creating build/lib.linux-armv7l-3.4/borg/testsuite
    copying borg/testsuite/xattr.py -> build/lib.linux-armv7l-3.4/borg/testsuite
    copying borg/testsuite/archive.py -> build/lib.linux-armv7l-3.4/borg/testsuite
    copying borg/testsuite/key.py -> build/lib.linux-armv7l-3.4/borg/testsuite
    copying borg/testsuite/run.py -> build/lib.linux-armv7l-3.4/borg/testsuite
    copying borg/testsuite/lrucache.py -> build/lib.linux-armv7l-3.4/borg/testsuite
    copying borg/testsuite/crypto.py -> build/lib.linux-armv7l-3.4/borg/testsuite
    copying borg/testsuite/archiver.py -> build/lib.linux-armv7l-3.4/borg/testsuite
    copying borg/testsuite/__init__.py -> build/lib.linux-armv7l-3.4/borg/testsuite
    copying borg/testsuite/helpers.py -> build/lib.linux-armv7l-3.4/borg/testsuite
    copying borg/testsuite/repository.py -> build/lib.linux-armv7l-3.4/borg/testsuite
    copying borg/testsuite/platform.py -> build/lib.linux-armv7l-3.4/borg/testsuite
    copying borg/testsuite/chunker.py -> build/lib.linux-armv7l-3.4/borg/testsuite
    copying borg/testsuite/hashindex.py -> build/lib.linux-armv7l-3.4/borg/testsuite
    copying borg/testsuite/mock.py -> build/lib.linux-armv7l-3.4/borg/testsuite
    running build_ext
    building 'borg.crypto' extension
    creating build/temp.linux-armv7l-3.4
    creating build/temp.linux-armv7l-3.4/borg
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/include/python3.4m -c borg/crypto.c -o build/temp.linux-armv7l-3.4/borg/crypto.o
    borg/crypto.c:8:22: fatal error: pyconfig.h: No such file or directory
     #include "pyconfig.h"
                          ^
    compilation terminated.
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    Complete output from command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-1n22fxxk/borgbackup/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-xrel06ah-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

got version from file /tmp/pip-build-1n22fxxk/borgbackup/borg/_version.py {'version': '0.23.0', 'full': 'c7da105fd0a75eec0454762df1dcc84510a2d813'}

running build_py

creating build

creating build/lib.linux-armv7l-3.4

creating build/lib.linux-armv7l-3.4/borg

copying borg/xattr.py -> build/lib.linux-armv7l-3.4/borg

copying borg/archive.py -> build/lib.linux-armv7l-3.4/borg

copying borg/remote.py -> build/lib.linux-armv7l-3.4/borg

copying borg/cache.py -> build/lib.linux-armv7l-3.4/borg

copying borg/key.py -> build/lib.linux-armv7l-3.4/borg

copying borg/fuse.py -> build/lib.linux-armv7l-3.4/borg

copying borg/lrucache.py -> build/lib.linux-armv7l-3.4/borg

copying borg/archiver.py -> build/lib.linux-armv7l-3.4/borg

copying borg/__init__.py -> build/lib.linux-armv7l-3.4/borg

copying borg/helpers.py -> build/lib.linux-armv7l-3.4/borg

copying borg/repository.py -> build/lib.linux-armv7l-3.4/borg

copying borg/platform.py -> build/lib.linux-armv7l-3.4/borg

copying borg/_version.py -> build/lib.linux-armv7l-3.4/borg

creating build/lib.linux-armv7l-3.4/borg/testsuite

copying borg/testsuite/xattr.py -> build/lib.linux-armv7l-3.4/borg/testsuite

copying borg/testsuite/archive.py -> build/lib.linux-armv7l-3.4/borg/testsuite

copying borg/testsuite/key.py -> build/lib.linux-armv7l-3.4/borg/testsuite

copying borg/testsuite/run.py -> build/lib.linux-armv7l-3.4/borg/testsuite

copying borg/testsuite/lrucache.py -> build/lib.linux-armv7l-3.4/borg/testsuite

copying borg/testsuite/crypto.py -> build/lib.linux-armv7l-3.4/borg/testsuite

copying borg/testsuite/archiver.py -> build/lib.linux-armv7l-3.4/borg/testsuite

copying borg/testsuite/__init__.py -> build/lib.linux-armv7l-3.4/borg/testsuite

copying borg/testsuite/helpers.py -> build/lib.linux-armv7l-3.4/borg/testsuite

copying borg/testsuite/repository.py -> build/lib.linux-armv7l-3.4/borg/testsuite

copying borg/testsuite/platform.py -> build/lib.linux-armv7l-3.4/borg/testsuite

copying borg/testsuite/chunker.py -> build/lib.linux-armv7l-3.4/borg/testsuite

copying borg/testsuite/hashindex.py -> build/lib.linux-armv7l-3.4/borg/testsuite

copying borg/testsuite/mock.py -> build/lib.linux-armv7l-3.4/borg/testsuite

running build_ext

building 'borg.crypto' extension

creating build/temp.linux-armv7l-3.4

creating build/temp.linux-armv7l-3.4/borg

arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/include/python3.4m -c borg/crypto.c -o build/temp.linux-armv7l-3.4/borg/crypto.o

borg/crypto.c:8:22: fatal error: pyconfig.h: No such file or directory

 #include "pyconfig.h"

                      ^

compilation terminated.

error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-1n22fxxk/borgbackup/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-xrel06ah-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-1n22fxxk/borgbackup
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 295, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 707, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/usr/lib/python3/dist-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-1n22fxxk/borgbackup/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-xrel06ah-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-1n22fxxk/borgbackup
```

**Comment by ThomasWaldmann** [comment]
Guess you forgot to install python3-dev package with the python header files?

**Comment by ThomasWaldmann** [comment]
Can you retry (see comment above)?

**Comment by lfam** [comment]
After defeating my package management puzzle, I can report that it passes all the unit tests and successfully initializes an encrypted repository, and creates and extracts archives.

Remote operations are not working but I think that is because I am not sourcing the virtualenv on the remote side. I'm not sure how to do that.

**Comment by ThomasWaldmann** [comment]
ok, so as this is resolved, I am closing this now.

you could simply symlink env/bin/borg into /usr/local/bin/ on both sides, so it gets found.
