### ISSUE TITLE
borg 1.2.0 crashes on non-existing directory/file inside non-existing directory

### ISSUE THREAD

**Issue by pete-dawgg** [borgbackup/borg#6440]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG (probably)

## System information. For client/server mode post info for both machines.
gentoo ~amd64 (unstable) main python-version: 3.9.10

#### Your borg version (borg -V).
1.2.0
#### Operating system (distribution) and version.
gentoo linux ~amd64
#### Hardware / network configuration, and filesystems used.
SUN-Server Intel; LAN only, btrfs
this server mounts other servers with sshfs and copies their data into borg-repos on local hdds. one "generic" patternfile is used for all of them
#### How much data is handled by borg?
~500GB in 12 repos all in different subvolumes 
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg create --info -v --progress --compression zstd,15 --files-cache ctime,size --exclude-caches  ::BEASTIE-'{now:%Y-%m-%d--%H-%M-%S}' /mnt/1/blabla/123

/mnt/1: host beastie (FreeBSD) mounted with sshfs
/mnt/1/blabla: does not exist
/mnt/1/blabla/123: does not exist either

## Describe the problem you're observing.
borg 1.2.0 crashes (1.1.17 did not crash):

```
phobos ~/borg # borg create --info -v --progress --compression zstd,15 --files-cache ctime,size --exclude-caches  ::BEASTIE-'{now:%Y-%m-%d--%H-%M-%S}' /mnt/1/blabla/123          
Creating archive at "/mnt/borg/BEASTIE/::BEASTIE-2022-03-11--11-39-41"
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/borg/archive.py", line 264, in OsOpen
    fd = os_open(path=path, parent_fd=parent_fd, name=name, flags=flags, noatime=noatime)
  File "/usr/lib/python3.9/site-packages/borg/helpers/fs.py", line 290, in os_open
    fd = os.open(fname, _flags_noatime, dir_fd=parent_fd)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/1/blabla'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/borg/archiver.py", line 5089, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.9/site-packages/borg/archiver.py", line 5020, in run
    return set_ec(func(args))
  File "/usr/lib/python3.9/site-packages/borg/archiver.py", line 183, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.9/site-packages/borg/archiver.py", line 668, in do_create
    create_inner(archive, cache, fso)
  File "/usr/lib/python3.9/site-packages/borg/archiver.py", line 595, in create_inner
    with OsOpen(path=parent_dir, flags=flags_root, noatime=True, op='open_root') as parent_fd:
  File "/usr/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.9/site-packages/borg/archive.py", line 264, in OsOpen
    fd = os_open(path=path, parent_fd=parent_fd, name=name, flags=flags, noatime=noatime)
  File "/usr/lib/python3.9/site-packages/borg/archive.py", line 218, in __exit__
    raise BackupOSError(self.op, exc_val) from exc_val
borg.archive.BackupOSError: open_root: [Errno 2] No such file or directory: '/mnt/1/blabla'

Platform: Linux phobos 5.16.12-gentoo #1 SMP Tue Mar 8 15:28:57 CET 2022 x86_64
Linux: Unknown Linux  
Borg: 1.2.0  Python: CPython 3.9.10 msgpack: 1.0.3 fuse: pyfuse3 3.2.1 [pyfuse3,llfuse]
PID: 16895  CWD: /root/borg
sys.argv: ['/usr/lib/python-exec/python3.9/borg', 'create', '--info', '-v', '--progress', '--compression', 'zstd,15', '--files-cache', 'ctime,size', '--exclude-caches', '::BEASTIE-{now:%Y-%m-%d--%H-%M-%S}', '/mnt/1/blabla/123']
SSH_ORIGINAL_COMMAND: None
```
same result with  /mnt/1/blabla/123/

also happens with patternfile (i use a generic one for all hosts; /usr/portage exists only on gentoo-hosts)
```
P sh
R /mnt/1/usr/portage/packages/
+ /mnt/1/usr/portage/packages/
```
causes borg to fail if dir (mounted with sshfs) that do not have these dirs
same phenomenon on non-existing dirs "outside" of sshfs:

error caught:
```
phobos ~/borg # borg create --info -v --progress --compression zstd,15 --files-cache ctime,size --exclude-caches  ::BEASTIE-'{now:%Y-%m-%d--%H-%M-%S}' /NO
Creating archive at "/mnt/borg/BEASTIE/::BEASTIE-2022-03-11--12-26-06"
/NO: [Errno 2] No such file or directory: 'NO'
```
crash caused:
```
phobos ~/borg # borg create --info -v --progress --compression zstd,15 --files-cache ctime,size --exclude-caches  ::BEASTIE-'{now:%Y-%m-%d--%H-%M-%S}' /NO/THING/HERE
Creating archive at "/mnt/borg/BEASTIE/::BEASTIE-2022-03-11--12-26-26"
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/borg/archive.py", line 264, in OsOpen
    fd = os_open(path=path, parent_fd=parent_fd, name=name, flags=flags, noatime=noatime)
  File "/usr/lib/python3.9/site-packages/borg/helpers/fs.py", line 290, in os_open
    fd = os.open(fname, _flags_noatime, dir_fd=parent_fd)
FileNotFoundError: [Errno 2] No such file or directory: '/NO/THING'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/borg/archiver.py", line 5089, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.9/site-packages/borg/archiver.py", line 5020, in run
    return set_ec(func(args))
  File "/usr/lib/python3.9/site-packages/borg/archiver.py", line 183, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.9/site-packages/borg/archiver.py", line 668, in do_create
    create_inner(archive, cache, fso)
  File "/usr/lib/python3.9/site-packages/borg/archiver.py", line 595, in create_inner
    with OsOpen(path=parent_dir, flags=flags_root, noatime=True, op='open_root') as parent_fd:
  File "/usr/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.9/site-packages/borg/archive.py", line 264, in OsOpen
    fd = os_open(path=path, parent_fd=parent_fd, name=name, flags=flags, noatime=noatime)
  File "/usr/lib/python3.9/site-packages/borg/archive.py", line 218, in __exit__
    raise BackupOSError(self.op, exc_val) from exc_val
borg.archive.BackupOSError: open_root: [Errno 2] No such file or directory: '/NO/THING'

Platform: Linux phobos 5.16.12-gentoo #1 SMP Tue Mar 8 15:28:57 CET 2022 x86_64
Linux: Unknown Linux  
Borg: 1.2.0  Python: CPython 3.9.10 msgpack: 1.0.3 fuse: pyfuse3 3.2.1 [pyfuse3,llfuse]
PID: 20655  CWD: /root/borg
sys.argv: ['/usr/lib/python-exec/python3.9/borg', 'create', '--info', '-v', '--progress', '--compression', 'zstd,15', '--files-cache', 'ctime,size', '--exclude-caches', '::BEASTIE-{now:%Y-%m-%d--%H-%M-%S}', '/NO/THING/HERE']
SSH_ORIGINAL_COMMAND: None
```

#### Can you reproduce the problem?
Always
(borg 1.1.17 catches this error)
####
also posted on [gentoo-forums ](https://forums.gentoo.org/viewtopic-p-8694452.html)

**Comment by ThomasWaldmann** [comment]
duplicate of #6374?

**Comment by pete-dawgg** [comment]
@ThomasWaldmann
you are right. sorry i couldn't find it.
