### ISSUE TITLE
libdeflate on fedora 34 does not support pkg-config

### ISSUE THREAD

**Issue by hexagonrecursion** [borgbackup/borg#6467]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).
borg 1.2.1.dev104+gdfd7ea81.d20220319

#### Operating system (distribution) and version.
Fedora release 34 (Thirty Four)

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```
pip install -e .
```

## Describe the problem you're observing.
Installation fails:
```
Exception: Could not find deflate lib/headers, please set BORG_LIBDEFLATE_PREFIX
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
```sh
sudo dnf install -y python3 python3-devel python3-pip python3-virtualenv \
libacl-devel libacl \
openssl-devel \
lz4-devel libzstd-devel xxhash-devel \
pkgconf python3-pkgconfig \
gcc gcc-c++ redhat-rpm-config \
fuse-devel fuse \
fuse3-devel fuse3
git clone https://github.com/borgbackup/borg.git
cd borg
pip install -r requirements.d/development.txt
pip install -e .
```

#### Include any warning/errors/backtraces from the system logs
```
Obtaining file:///home/user/borg-master
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Detected OpenSSL [via pkg-config]
      Detected and preferring liblz4 [via pkg-config]
      Detected and preferring libzstd [via pkg-config]
      Detected and preferring libxxhash [via pkg-config]
      Traceback (most recent call last):
        File "/home/user/borg-master/.direnv/python-3.9.10/lib64/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/user/borg-master/.direnv/python-3.9.10/lib64/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/user/borg-master/.direnv/python-3.9.10/lib64/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-dwwlceuq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/tmp/pip-build-env-dwwlceuq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-dwwlceuq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 200, in <module>
          setup_checksums.deflate_ext_kwargs(pc, system_prefix_libdeflate),
        File "/home/user/borg-master/setup_checksums.py", line 31, in deflate_ext_kwargs
          raise Exception('Could not find deflate lib/headers, please set BORG_LIBDEFLATE_PREFIX')
      Exception: Could not find deflate lib/headers, please set BORG_LIBDEFLATE_PREFIX
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

## Workaround
 
```
BORG_LIBDEFLATE_PREFIX=/usr/ pip install -e .
```

## Additional info
[It looks like fedora 34 currently ships libdeflate 1.8, but pkg-conf was added to libdeflate in 1.9](https://bugzilla.redhat.com/show_bug.cgi?id=2065895)

**Comment by hexagonrecursion** [comment]
Note: fedora 35 ships libdeflate 1.9 and borg builds without issue. Note: [editable installs without a virtual env still fail, but for a different reason](https://github.com/pypa/setuptools/pull/3151).

**Comment by hexagonrecursion** [comment]
[Progress on the fedora end]( https://bodhi.fedoraproject.org/updates/FEDORA-2022-57dc8352d4): we have built libdeflate 1.9 for fedora 34, but it is not yet available from the repositories. Not even in fedora-testing. You can help us test it by installing it from koji.

**Comment by ThomasWaldmann** [comment]
Nice to see progress. Guess there is nothing to do for borgbackup project here, so I am closing this again.

Note that this is also covered by #6458.
