### ISSUE TITLE
Packaging in Haiku

### ISSUE THREAD

**Issue by Begasus** [borgbackup/borg#6510]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug/issue

#### Your borg version (borg -V).

1.2-maint checkout

#### Operating system (distribution) and version.

Haiku, 32bit, hrev55964

#### Hardware / network configuration, and filesystems used.

VirtualBox, BeFS

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg -V

## Describe the problem you're observing.

Building from Terminal and packaging works fine, in Terminal after install `borg -V` is OK, when packaged and running `borg -V` it gives an error on version string

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
 
Yes

#### Include any warning/errors/backtraces from the system logs

If this complaint relates to borg performance, please include CRUD benchmark
results and any steps you took to troubleshoot.
How to run benchmark: http://borgbackup.readthedocs.io/en/stable/usage/benchmark.html

*IMPORTANT* - Please mark logs and text output from terminal commands 
or else Github will not display them correctly. 
An example is provided below.

Terminal log (first version check in Terminal with `python3.8 setup.py install`, second check in Terminal after packaging):
```
/Opslag/sandbox> borg -V
borg 1.2.1.dev69+ge5e360d5
/Opslag/sandbox> borg -V
Traceback (most recent call last):
  File "/packages/python38_x86-3.8.12-1/.self/lib/python3.8/vendor-packages/borg/archiver.py", line 40, in <module>
    from .archive import Archive, ArchiveChecker, ArchiveRecreater, Statistics, is_special
  File "/packages/python38_x86-3.8.12-1/.self/lib/python3.8/vendor-packages/borg/archive.py", line 23, in <module>
    from .cache import ChunkListEntry
  File "/packages/python38_x86-3.8.12-1/.self/lib/python3.8/vendor-packages/borg/cache.py", line 32, in <module>
    from .crypto.key import PlaintextKey
  File "/packages/python38_x86-3.8.12-1/.self/lib/python3.8/vendor-packages/borg/crypto/key.py", line 29, in <module>
    from .nonces import NonceManager
  File "/packages/python38_x86-3.8.12-1/.self/lib/python3.8/vendor-packages/borg/crypto/nonces.py", line 8, in <module>
    from ..remote import InvalidRPCMethod
  File "/packages/python38_x86-3.8.12-1/.self/lib/python3.8/vendor-packages/borg/remote.py", line 40, in <module>
    BORG_VERSION = parse_version(__version__)
  File "/packages/python38_x86-3.8.12-1/.self/lib/python3.8/vendor-packages/borg/version.py", line 24, in parse_version
    raise ValueError('Invalid version string %s' % version)
ValueError: Invalid version string 0.1.dev1+g3901a82
```

**Comment by Begasus** [comment]
Related to: https://github.com/borgbackup/borg/issues/4117

**Comment by Begasus** [comment]
So far I've pushed the recipes to my github account at: https://github.com/Begasus/haikuports/commit/f963f30e5ecdb79b7edead397ead156b3478327b

**Comment by Begasus** [comment]
There's borg/version.py which seems correct from build in Terminal, from what I see is that not everything gets installed when packaging it, install stops then at: 
```
byte-compiling /packages/borgbackup_master_x86-1.2.0-1/.self/lib/python3.8/vendor-packages/borg/version.py to version.cpython-38.pyc
byte-compiling /packages/borgbackup_master_x86-1.2.0-1/.self/lib/python3.8/vendor-packages/borg/xattr.py to xattr.cpython-38.pyc
running install_egg_info
Copying src/borgbackup.egg-info to /packages/borgbackup_master_x86-1.2.0-1/.self/lib/python3.8/vendor-packages/borgbackup-0.1.dev1+gfdc84fa-py3.8.egg-info
running install_scripts
Installing borg script to /packages/borgbackup_master_x86-1.2.0-1/.self/bin
Installing borgfs script to /packages/borgbackup_master_x86-1.2.0-1/.self/bin
```
Where in Terminal it continues (maybe I'm missing something there?):
```
byte-compiling build/bdist.haiku-1-BePC/egg/borg/version.py to version.cpython-38.pyc
byte-compiling build/bdist.haiku-1-BePC/egg/borg/xattr.py to xattr.cpython-38.pyc
creating stub loader for borg/crypto/low_level.cpython-38.so
creating stub loader for borg/compress.cpython-38.so
creating stub loader for borg/hashindex.cpython-38.so
creating stub loader for borg/item.cpython-38.so
creating stub loader for borg/chunker.cpython-38.so
creating stub loader for borg/checksums.cpython-38.so
creating stub loader for borg/platform/posix.cpython-38.so
byte-compiling build/bdist.haiku-1-BePC/egg/borg/crypto/low_level.py to low_level.cpython-38.pyc
byte-compiling build/bdist.haiku-1-BePC/egg/borg/compress.py to compress.cpython-38.pyc
byte-compiling build/bdist.haiku-1-BePC/egg/borg/hashindex.py to hashindex.cpython-38.pyc
byte-compiling build/bdist.haiku-1-BePC/egg/borg/item.py to item.cpython-38.pyc
byte-compiling build/bdist.haiku-1-BePC/egg/borg/chunker.py to chunker.cpython-38.pyc
byte-compiling build/bdist.haiku-1-BePC/egg/borg/checksums.py to checksums.cpython-38.pyc
byte-compiling build/bdist.haiku-1-BePC/egg/borg/platform/posix.py to posix.cpython-38.pyc
creating build/bdist.haiku-1-BePC/egg/EGG-INFO
copying src/borgbackup.egg-info/PKG-INFO -> build/bdist.haiku-1-BePC/egg/EGG-INFO
copying src/borgbackup.egg-info/SOURCES.txt -> build/bdist.haiku-1-BePC/egg/EGG-INFO
copying src/borgbackup.egg-info/dependency_links.txt -> build/bdist.haiku-1-BePC/egg/EGG-INFO
copying src/borgbackup.egg-info/entry_points.txt -> build/bdist.haiku-1-BePC/egg/EGG-INFO
copying src/borgbackup.egg-info/not-zip-safe -> build/bdist.haiku-1-BePC/egg/EGG-INFO
copying src/borgbackup.egg-info/requires.txt -> build/bdist.haiku-1-BePC/egg/EGG-INFO
copying src/borgbackup.egg-info/top_level.txt -> build/bdist.haiku-1-BePC/egg/EGG-INFO
writing build/bdist.haiku-1-BePC/egg/EGG-INFO/native_libs.txt
creating 'dist/borgbackup-1.2.1.dev174+gb9ea17da-py3.8-haiku-1-BePC.egg' and adding 'build/bdist.haiku-1-BePC/egg' to it
removing 'build/bdist.haiku-1-BePC/egg' (and everything under it)
Processing borgbackup-1.2.1.dev174+gb9ea17da-py3.8-haiku-1-BePC.egg
creating /boot/system/non-packaged/lib/python3.8/site-packages/borgbackup-1.2.1.dev174+gb9ea17da-py3.8-haiku-1-BePC.egg
Extracting borgbackup-1.2.1.dev174+gb9ea17da-py3.8-haiku-1-BePC.egg to /boot/system/non-packaged/lib/python3.8/site-packages
Adding borgbackup 1.2.1.dev174+gb9ea17da to easy-install.pth file
Installing borg script to /packages/python38_x86-3.8.12-1/.self/non-packaged/bin
Installing borgfs script to /packages/python38_x86-3.8.12-1/.self/non-packaged/bin

Installed /boot/system/non-packaged/lib/python3.8/site-packages/borgbackup-1.2.1.dev174+gb9ea17da-py3.8-haiku-1-BePC.egg
Processing dependencies for borgbackup==1.2.1.dev174+gb9ea17da
Searching for argon2-cffi
Reading https://pypi.org/simple/argon2-cffi/
Downloading https://files.pythonhosted.org/packages/a8/07/946d5a9431bae05a776a59746ec385fbb79b526738d25e4202d3e0bbf7f4/argon2_cffi-21.3.0-py3-none-any.whl#sha256=8c976986f2c5c0e5000919e6de187906cfd81fb1c72bf9d88c01177e77da7f80
Best match: argon2-cffi 21.3.0
Processing argon2_cffi-21.3.0-py3-none-any.whl
Installing argon2_cffi-21.3.0-py3-none-any.whl to /boot/system/non-packaged/lib/python3.8/site-packages
Adding argon2-cffi 21.3.0 to easy-install.pth file

Installed /boot/system/non-packaged/lib/python3.8/site-packages/argon2_cffi-21.3.0-py3.8.egg
Searching for packaging==21.3
Best match: packaging 21.3
Adding packaging 21.3 to easy-install.pth file

Using /boot/system/lib/python3.8/vendor-packages
Searching for msgpack==1.0.3
Best match: msgpack 1.0.3
Adding msgpack 1.0.3 to easy-install.pth file

Using /boot/system/lib/python3.8/vendor-packages
Searching for argon2-cffi-bindings==0.1.dev1+g6db6787.d20220330
Best match: argon2-cffi-bindings 0.1.dev1+g6db6787.d20220330
Adding argon2-cffi-bindings 0.1.dev1+g6db6787.d20220330 to easy-install.pth file

Using /boot/system/lib/python3.8/vendor-packages
Searching for pyparsing==3.0.7
Best match: pyparsing 3.0.7
Adding pyparsing 3.0.7 to easy-install.pth file

Using /boot/system/lib/python3.8/vendor-packages
Searching for cffi==1.15.0
Best match: cffi 1.15.0
Adding cffi 1.15.0 to easy-install.pth file

Using /boot/system/lib/python3.8/vendor-packages
Searching for pycparser==2.20
Best match: pycparser 2.20
Adding pycparser 2.20 to easy-install.pth file

Using /boot/system/lib/python3.8/vendor-packages
Finished processing dependencies for borgbackup==1.2.1.dev174+gb9ea17da
```

**Comment by ThomasWaldmann** [comment]
If you want a sdist, try `python setup.py sdist` and use the result you'll get under `dist/...`.

**Comment by ThomasWaldmann** [comment]
Guess master branch will also show 1.2.0.... as I did not yet set any 1.3 tag, guess I should do that soon...

**Comment by Begasus** [comment]
> If you want a sdist, try `python setup.py sdist` and use the result you'll get under `dist/...`.

Content of that archive is the same as packaging it with our tool

**Comment by ThomasWaldmann** [comment]
BTW, if you clone the repo, do a full / normal clone, not a "shallow" clone. `setuptools_scm` needs more than the latest stuff in the git repo to work correctly.

**Comment by Begasus** [comment]
> Then you should have a `borg/_setup.py`, right?

I don't see it in installed version(s)?
Not sure what you mean by a full/shallow clone, in the recipe this is what we mostly use to pull a commit hash?

**Comment by ThomasWaldmann** [comment]
```
git clone repo
```
this does a full clone.

**Comment by Begasus** [comment]
Took some time to look into this again.
Used the official release https://github.com/borgbackup/borg/archive/refs/tags/1.2.0.tar.gz , added argon2-cffi source in ./src
Rebuild the package with our package manager, argon2 is included.

Version string is still an issue, I do have _version.py with the following content:
```
# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = '0.1.dev1+g55d237f'
version_tuple = (0, 1, 'dev1', 'g55d237f')
```

**Comment by Begasus** [comment]
Succes!!! packaged and running now :) @mmuman, now it's your turn for the rest ;)
PR created here: https://github.com/haikuports/haikuports/pull/6921

**Comment by ThomasWaldmann** [comment]
version = '0.1.dev1+gedcff4f'

guess that is `setuptools_scm` not being able to determine the right version number.

possible reasons:
- you did not do a full git clone, but only fetched the latest state (thus it has not enough history information). a shallow clone will **not** work.
- you also need to check out the correct tag, e.g. `git checkout 1.2.0`
- the run `pip install -e .` and `borg -V` and it should tell `1.2.0`.

**Comment by Begasus** [comment]
`borg -V` reports `1.2.0` now :)

**Comment by ThomasWaldmann** [comment]
All done, thanks to @Begasus for porting / packaging!
