### ISSUE TITLE
txn.active config file missing?

### ISSUE THREAD

**Issue by clickwir** [borgbackup/borg#6640]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

#### Your borg version (borg -V).
1.2.0

#### Operating system (distribution) and version.
Kubuntu 22.04 5.15.0-25-generic
#### Hardware / network configuration, and filesystems used.
Asus B550, AMD 5600X, AMD RX560, Seagate Firecuda 520 (OS) btrfs, 2 8TB drives for Data btrfs RAID1.

#### How much data is handled by borg?
2.5TB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
sudo borg info /Data/backup/user/

## Describe the problem you're observing.
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/borg/7d2f67ff29753ac8facd07831600b75e9fc7a18259e0962d3dd9df38d09995fc/txn.active/config'

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yes. For the local repo this error happens every time. Borgmatic is set to use 2 remote and 1 local. The 2 remote work fine.

#### Include any warning/errors/backtraces from the system logs
```
user@system:~$ sudo borg info /Data/backup/system/
Enter passphrase for key /Data/backup/system: 
Killed stale lock system@17212028877171.60737-0.
Removed stale exclusive roster lock for host system@17212028877171 pid 60737 thread 0.
Removed stale exclusive roster lock for host system@17212028877171 pid 60737 thread 0.
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 5089, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 5020, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 176, in wrapper
    with Cache(repository, kwargs['key'], kwargs['manifest'],
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 383, in __new__
    return local()
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 374, in local
    return LocalCache(repository=repository, key=key, manifest=manifest, path=path, sync=sync,
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 483, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 538, in open
    self.rollback()
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 651, in rollback
    shutil.copy(os.path.join(txn_dir, 'config'), self.path)
  File "/usr/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/borg/7d2f67ff29753ac8facd07831600b75e9fc7a18259e0962d3dd9df38d09995fc/txn.active/config'

Platform: Linux system 5.15.0-25-generic #25-Ubuntu SMP Wed Mar 30 15:54:22 UTC 2022 x86_64
Linux: Unknown Linux  
Borg: 1.2.0  Python: CPython 3.10.4 msgpack: 1.0.3 fuse: pyfuse3 3.2.0 [pyfuse3,llfuse]
PID: 60760  CWD: /home/clickwir
sys.argv: ['/usr/bin/borg', 'info', '/Data/backup/system/']
SSH_ORIGINAL_COMMAND: None

user@system:~$ sudo ls -lah /root/.cache/borg/7d2f67ff29753ac8facd07831600b75e9fc7a18259e0962d3dd9df38d09995fc/txn.active/
total 0
drwx------ 1 root root   0 Apr 20 22:08 .
drwx------ 1 root root 148 Apr 20 22:08 ..

user@system:~$ sudo ls -lah /root/.cache/borg/7d2f67ff29753ac8facd07831600b75e9fc7a18259e0962d3dd9df38d09995fc/
total 108M
drwx------ 1 root root  148 Apr 20 22:08 .
drwx------ 1 root root  408 Apr 29  2021 ..
-rw------- 1 root root  55M Mar 29 10:12 chunks
drwx------ 1 root root 4.3K Apr 29  2021 chunks.archive.d
-rw------- 1 root root  577 Mar 30 00:34 config
-rw------- 1 root root  54M Mar 29 10:12 files
drwx------ 1 root root   54 Apr 20 22:08 lock.exclusive
-rw------- 1 root root   50 Apr 20 22:08 lock.roster
-rw------- 1 root root   68 Apr 29  2021 README
drwx------ 1 root root    0 Apr 20 22:08 txn.active
```

**Comment by ThomasWaldmann** [comment]
Try this:
- make sure no borg operation is and will be running
- `borg break-lock REPO`
- `borg delete --cache-only REPO`

Guess that will fix it. Next operation will take a while as it will rebuild the clientside cache.

**Comment by clickwir** [comment]
Worked. Thanks.

```
borg info REPO
````
Took 2-3 minutes to run and gave normal output. 

Also running 'borgmatic info' works normally now also. Thank you!
