### ISSUE TITLE
Traceback after aborted backup due to network outage

### ISSUE THREAD

**Issue by JuergenBS** [borgbackup/borg#6729]
Hi!

I'm currently confronted with a broken repository after an network outage.
The repo resided on a mounted SMB share and borgbackup 1.1.9 was in use when the network outage occurred.
Now when accessing the repo the following tracebacks are thrown. This happens with 1.1.9 and 1.1.15 and also with local ext4 filesystem with a fresh user that has never used borgbackup before (→ no local cache).

a) is there any chance to repair this repo?
b) if it's not an obscure data corruption, shouldn't borgbackup catch this error and offer some help for repairing this issue?

Greetings

 JuergenBS

```
root@vm05:~# export BORG_PASSPHRASE=extremely_random_password
root@vm05:~# export BORG_REPO=/root/backup/client1
root@vm05:~# borgbackup info ::
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4621, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4553, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 164, in wrapper
    kwargs['manifest'], kwargs['key'] = Manifest.load(repository, compatibility)
  File "/usr/lib/python3/dist-packages/borg/helpers.py", line 374, in load
    cdata = repository.get(cls.MANIFEST_ID)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1114, in get
    self.index = self.open_index(self.get_transaction_id())
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 496, in open_index
    integrity_data = self._read_integrity(transaction_id, b'index')
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 484, in _read_integrity
    integrity = msgpack.unpack(fd)
  File "/usr/lib/python3/dist-packages/borg/algorithms/msgpack/__init__.py", line 58, in unpack
    return unpackb(data, **kwargs)
  File "src/borg/algorithms/msgpack/_unpacker.pyx", line 211, in borg.algorithms.msgpack._unpacker.unpackb
borg.algorithms.msgpack.exceptions.UnpackValueError: Unpack failed: error = 0

Platform: Linux vm05 5.8.0-43-generic #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021 x86_64
Linux: Unknown Linux
Borg: 1.1.15  Python: CPython 3.8.10 msgpack: 0.5.6
PID: 340430  CWD: /root
sys.argv: ['/usr/bin/borgbackup', 'info', '::']
SSH_ORIGINAL_COMMAND: None

root@vm05:~# borgbackup check -vp --repository-only ::
Starting repository check
Starting repository index check
Completed repository check, no problems found.

root@vm05:~# borgbackup check -vp ::
Starting repository check
Starting repository index check
Completed repository check, no problems found.
Starting archive consistency check...
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4621, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4553, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 177, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 345, in do_check
    if not args.repo_only and not ArchiveChecker().check(
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 1225, in check
    self.init_chunks()
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 1259, in init_chunks
    capacity = int(len(self.repository) / ChunkIndex.MAX_LOAD_FACTOR * 1.1)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1053, in __len__
    self.index = self.open_index(self.get_transaction_id())
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 496, in open_index
    integrity_data = self._read_integrity(transaction_id, b'index')
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 484, in _read_integrity
    integrity = msgpack.unpack(fd)
  File "/usr/lib/python3/dist-packages/borg/algorithms/msgpack/__init__.py", line 58, in unpack
    return unpackb(data, **kwargs)
  File "src/borg/algorithms/msgpack/_unpacker.pyx", line 211, in borg.algorithms.msgpack._unpacker.unpackb
borg.algorithms.msgpack.exceptions.UnpackValueError: Unpack failed: error = 0

Platform: Linux vm05 5.8.0-43-generic #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021 x86_64
Linux: Unknown Linux
Borg: 1.1.15  Python: CPython 3.8.10 msgpack: 0.5.6
PID: 340435  CWD: /root
sys.argv: ['/usr/bin/borgbackup', 'check', '-vp', '::']
SSH_ORIGINAL_COMMAND: None
root@vm05:~#
```

**Comment by ThomasWaldmann** [comment]
Hmm, looks like your integrity.* file is defect. What does this show?
```
ls -l repo_dir/integrity.*
```

Is `borgbackup` a wrapper or is it the same as `borg` is usually?

**Comment by ThomasWaldmann** [comment]
BTW, did you use `borg break-lock` or `--bypass-lock`?

**Comment by JuergenBS** [comment]
Debian + Ubuntu name the usual borg executable `borgbackup` → no wrapper.
```
-rwxr-xr-x 1 foobar root       700 Apr 27  2019 config
drwxr-xr-x 2 foobar root         0 Apr 20 13:12 data
-rwxr-xr-x 1 foobar root      8164 Mai 12 17:16 hints.9634
-rwxr-xr-x 1 foobar root 171652778 Mai 12 17:16 index.9634
-rwxr-xr-x 1 foobar root         0 Mai 12 17:16 integrity.9634
-rwxr-xr-x 1 foobar root        16 Mai 12 17:03 nonce
-rwxr-xr-x 1 foobar root        73 Apr 27  2019 README
```
No, I did not use `break-lock` or `--bypass-lock`.

**Comment by ThomasWaldmann** [comment]
The state seen in that directory should not be possible as a direct outcome of borg's fs actions even if the network or server or ... breaks down unexpectedly:

https://github.com/borgbackup/borg/blob/1.1.15/src/borg/repository.py#L626

So, maybe that fileserver is not working reliably in some respects.

You can try removing the `integrity.9634` file. Maybe also try `borg check -v --progress --repair ...`.

**Comment by JuergenBS** [comment]
Thx. At least the `borg list` is now working again. `borg check -v --progress` is currently running.

**Comment by JuergenBS** [comment]
* `borg check -v --progress` returned no error
* listing and mounting archives worked
* creating a new archive also worked

From my point of view, the issue can be closed.
