### ISSUE TITLE
failing with  borg.repository.Repository.ObjectNotFound 

### ISSUE THREAD

**Issue by pmoreypc** [borgbackup/borg#6904]
```
borg create --stats user@hostname:/mnt/abc/misc_data/remote_backup/automated/auto_data_backedup_remotely_from_source.borg::manual-cvv-2022-07-29-074756 /mnt/abc/misc_data/dir_to_be_auto_backed_up_remotely
Remote: Borg 1.0.9: exception in RPC call:
Remote: Traceback (most recent call last):
Remote:   File "/usr/lib/python3/dist-packages/borg/remote.py", line 113, in serve
Remote:     res = f(*args)
Remote:   File "/usr/lib/python3/dist-packages/borg/repository.py", line 520, in get
Remote:     raise self.ObjectNotFound(id_, self.path) from None
Remote: borg.repository.Repository.ObjectNotFound: (b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '/mnt/abc/misc_data/remote_backup/automated/auto_data_backedup_remotely_from_source.borg')
Remote: Platform: Linux hdf43 4.9.0-16-amd64 #1 SMP Debian 4.9.272-2 (2021-07-19) x86_64
Remote: Linux: debian 9.5 
Remote: Borg: 1.0.9  Python: CPython 3.5.3
Remote: PID: 177880  CWD: /home/sdf
Remote: sys.argv: ['/usr/bin/borg', 'serve', '--umask=077']
Remote: SSH_ORIGINAL_COMMAND: None
Remote: 
Repository has no manifest.
```
Can you help me with this?

**Comment by ThomasWaldmann** [comment]
- borg 1.0.9 is very old, current version is 1.1.18 (oldstable) or 1.2.1 (stable)
- the repository manifest (== directory of archives) is usually always present, so it not being found hints to some repository corruption, you can carefully try `borg check --repair`.

**Comment by ThomasWaldmann** [comment]
Guess this is solved.
