### ISSUE TITLE
not a str object, but None during transfer

### ISSUE THREAD

**Issue by remyabel2** [borgbackup/borg#6993]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug

#### Your borg version (borg -V).

borg 2.0.0b1, installed with pip in a virtualenv

#### Operating system (distribution) and version.

Fedora 36

#### Hardware / network configuration, and filesystems used.

128GB SSD BTRFS Source drive
1TB HDD BTRFS Backup drive

#### How much data is handled by borg?

The original backup repository is:
```
                       Original size      Compressed size    Deduplicated size
All archives:              112.34 GB             37.37 GB              9.10 GB
                       Unique chunks         Total chunks
Chunk index:                  457286              2227208
```

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
borg rcreate --repo /home/remyabel/second_drive/backups/backup-borg2-root --encryption repokey-blake2-aes-ocb \
    --other-repo /home/tom/remyabel/backups/backup-borg-root
borg --info -p --show-rc \
    --repo /home/remyabel/second_drive/backups/backup-borg2-root transfer --upgrader=From12To20 \
    --other-repo /home/remyabel/second_drive/backups/backup-borg-root
```

## Describe the problem you're observing.

I get a stacktrace during transfer.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

I cannot reproduce this using a test repo that was created using Borg 1.2.2 and using archive names of `{hostname}-{now}`. My backup-borg-root directory, which I can reproduce this with, was created with Borg < 1.2.2 and uses archive names created by borgmatic.

#### Include any warning/errors/backtraces from the system logs

```
Enter passphrase for key /home/remyabel/second_drive/backups/backup-borg-root:
Enter passphrase for key /home/remyabel/second_drive/backups/backup-borg2-root:
localhost-2022-08-21T17:02:42.995082: copying archive to destination repo...
Local Exception
Traceback (most recent call last):
  File "/root/.borgbackup-2.0.0b1/lib64/python3.10/site-packages/borg/archiver/__init__.py", line 580, in main
    exit_code = archiver.run(args)
  File "/root/.borgbackup-2.0.0b1/lib64/python3.10/site-packages/borg/archiver/__init__.py", line 508, in run
    return set_ec(func(args))
  File "/root/.borgbackup-2.0.0b1/lib64/python3.10/site-packages/borg/archiver/common.py", line 242, in wrapper
    return method(self, args, **kwargs)
  File "/root/.borgbackup-2.0.0b1/lib64/python3.10/site-packages/borg/archiver/common.py", line 173, in wrapper
    return method(self, args, repository=repository, cache=cache_, **kwargs)
  File "/root/.borgbackup-2.0.0b1/lib64/python3.10/site-packages/borg/archiver/transfer.py", line 63, in do_transfer
    for item in other_archive.iter_items():
  File "/root/.borgbackup-2.0.0b1/lib64/python3.10/site-packages/borg/archive.py", line 607, in iter_items
    for item in self.pipeline.unpack_many(
  File "/root/.borgbackup-2.0.0b1/lib64/python3.10/site-packages/borg/archive.py", line 283, in unpack_many
    items = [Item(internal_dict=item) for item in unpacker]
  File "/root/.borgbackup-2.0.0b1/lib64/python3.10/site-packages/borg/archive.py", line 283, in <listcomp>
    items = [Item(internal_dict=item) for item in unpacker]
  File "src/borg/item.pyx", line 143, in borg.item.PropDict.__init__
  File "src/borg/item.pyx", line 369, in borg.item.Item.update_internal
  File "src/borg/item.pyx", line 32, in borg.item.fix_str_value
  File "src/borg/item.pyx", line 110, in borg.item.want_str
AssertionError: not a str object, but None
```

**Comment by ThomasWaldmann** [comment]
What it does there is to iterate over path, source, user, group metadata.

The values should be str in the end (this is why it calls `want_str`).

Old borg worked a bit strange (see #6908) and wrote `None` in some cases instead of leaving away the key/value pair completely if it is not known.

So, e.g. if the lookup uid -> user did not find a username, it wrote `user=None` to the metadata (same for group).

Guess this will be fixed by solving #6908, thus I am closing this as a duplicate.
