### ISSUE TITLE
2.0.0b3: attribute nfiles not found

### ISSUE THREAD

**Issue by pgerber** [borgbackup/borg#7072]
## Have you checked borgbackup docs, FAQ, and open Github issues?

yes

## Is this a BUG / ISSUE report or a QUESTION?

bug

#### Your borg version (borg -V).

```
$ borg -V
borg 2.0.0b3
```

#### Operating system (distribution) and version.

Debian 11

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
user@tmp-borg:~$ BORG_PASSPHRASE=abc borg rcreate -e repokey-blake2-chacha20-poly1305 -r test

IMPORTANT: you will need both KEY AND PASSPHRASE to access this repo!
If you used a repokey mode, the key is stored in the repo, but you should back it up separately.
Use "borg key export" to export the key, optionally in printable format.
Write down the passphrase. Store both at safe place(s).

user@tmp-borg:~$ tar -C /etc -c fstab | BORG_PASSPHRASE=abc borg -r test import-tar test -
user@tmp-borg:~$ BORG_PASSPHRASE=abc borg info -r test -a test
Local Exception
Traceback (most recent call last):
  File "borg/archiver/__init__.py", line 594, in main
  File "borg/archiver/__init__.py", line 522, in run
  File "borg/archiver/_common.py", line 155, in wrapper
  File "borg/archiver/info_cmd.py", line 34, in do_info
  File "borg/archive.py", line 558, in info
  File "borg/archive.py", line 714, in calc_stats
  File "src/borg/item.pyx", line 219, in borg.item.PropDictProperty.__get__
AttributeError: attribute nfiles not found

Platform: Linux tmp-borg 5.19.9-1.fc32.qubes.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Sep 16 14:54:56 CEST 2022 x86_64
Linux: Unknown Linux  
Borg: 2.0.0b3  Python: CPython 3.9.14 msgpack: 1.0.4 fuse: llfuse 1.4.2 [pyfuse3,llfuse]
PID: 121613  CWD: /home/user
sys.argv: ['borg', 'info', '-r', 'test', '-a', 'test']
SSH_ORIGINAL_COMMAND: None
```

## Describe the problem you're observing.

`borg info` fails on archives created via `borg import-tar`.

**Comment by ThomasWaldmann** [comment]
At least they are all there in `items.pyx` (which also got a bigger change recently):
```
    size = PropDictProperty(int)
    nfiles = PropDictProperty(int)
    size_parts = PropDictProperty(int)
    nfiles_parts = PropDictProperty(int)
```

**Comment by ThomasWaldmann** [comment]
Looks like this is an issue in borg 1.2 also, but borg 1.2 does not crash when using `borg info` because it does not require this metadata.

But it needs to get fixed to put the metadata into the archive for checkpoints and import-tar.
