### ISSUE TITLE
Connection closed by remote host `BrokenPipeError: [Errno 32] Broken pipe`

### ISSUE THREAD

**Issue by auroraanna** [borgbackup/borg#7111]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).
1.2.2

#### Operating system (distribution) and version.
NixOS 22.11.20221027.2001e2b (Raccoon) x86_64

#### Hardware / network configuration, and filesystems used.
- CPU: Intel i5-8350U (8) @ 3.6GHz
- GPU: Intel UHD Graphics 620
- Memory: 16 GB
- Disk: 915 GB SSD
- Filesystem: btrfs inside of LUKS
- Network access: Wi-Fi

#### How much data is handled by borg?
~100 GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```console
> borg create --progress --stats --compression zstd,22 --exclude-caches --patterns-from ~/.borgpatterns  ssh://annaaurora@borg.artemislena.eu:2222/./::2022-10-13 ~/
Enter passphrase for key ssh://annaaurora@borg.artemislena.eu:2222/./: 
Remote: client_loop: send disconnect: Broken pipeaaurora/projects/nixpkgs/.git/objects/p.../pack-b07281a0b4fceafb219fea9c05c98393dff88fa3.pack
Local Exception
Traceback (most recent call last):
  File "/nix/store/n80wdj3jmp9a8w07iqbmqr9lnawxxydn-borgbackup-1.2.2/lib/python3.10/site-packages/borg/archiver.py", line 183, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/nix/store/n80wdj3jmp9a8w07iqbmqr9lnawxxydn-borgbackup-1.2.2/lib/python3.10/site-packages/borg/archiver.py", line 675, in do_create
    create_inner(archive, cache, fso)
  File "/nix/store/n80wdj3jmp9a8w07iqbmqr9lnawxxydn-borgbackup-1.2.2/lib/python3.10/site-packages/borg/archiver.py", line 608, in create_inner
    self._rec_walk(path=path, parent_fd=parent_fd, name=name,
  File "/nix/store/n80wdj3jmp9a8w07iqbmqr9lnawxxydn-borgbackup-1.2.2/lib/python3.10/site-packages/borg/archiver.py", line 820, in _rec_walk
    self._rec_walk(
  File "/nix/store/n80wdj3jmp9a8w07iqbmqr9lnawxxydn-borgbackup-1.2.2/lib/python3.10/site-packages/borg/archiver.py", line 820, in _rec_walk
    self._rec_walk(
  File "/nix/store/n80wdj3jmp9a8w07iqbmqr9lnawxxydn-borgbackup-1.2.2/lib/python3.10/site-packages/borg/archiver.py", line 820, in _rec_walk
    self._rec_walk(
  [Previous line repeated 3 more times]
  File "/nix/store/n80wdj3jmp9a8w07iqbmqr9lnawxxydn-borgbackup-1.2.2/lib/python3.10/site-packages/borg/archiver.py", line 786, in _rec_walk
    status = self._process_any(path=path, parent_fd=parent_fd, name=name, st=st, fso=fso, cache=cache,
  File "/nix/store/n80wdj3jmp9a8w07iqbmqr9lnawxxydn-borgbackup-1.2.2/lib/python3.10/site-packages/borg/archiver.py", line 688, in _process_any
    return fso.process_file(path=path, parent_fd=parent_fd, name=name, st=st, cache=cache)
  File "/nix/store/n80wdj3jmp9a8w07iqbmqr9lnawxxydn-borgbackup-1.2.2/lib/python3.10/site-packages/borg/archive.py", line 1434, in process_file
    self.process_file_chunks(item, cache, self.stats, self.show_progress, backup_io_iter(self.chunker.chunkify(None, fd)))
  File "/nix/store/n80wdj3jmp9a8w07iqbmqr9lnawxxydn-borgbackup-1.2.2/lib/python3.10/site-packages/borg/archive.py", line 1261, in process_file_chunks
    item.chunks.append(chunk_processor(chunk))
  File "/nix/store/n80wdj3jmp9a8w07iqbmqr9lnawxxydn-borgbackup-1.2.2/lib/python3.10/site-packages/borg/archive.py", line 1249, in chunk_processor
    chunk_entry = cache.add_chunk(chunk_id, data, stats, wait=False)
  File "/nix/store/n80wdj3jmp9a8w07iqbmqr9lnawxxydn-borgbackup-1.2.2/lib/python3.10/site-packages/borg/cache.py", line 951, in add_chunk
    self.repository.put(id, data, wait=wait)
  File "/nix/store/n80wdj3jmp9a8w07iqbmqr9lnawxxydn-borgbackup-1.2.2/lib/python3.10/site-packages/borg/remote.py", line 476, in do_rpc
    return self.call(f.__name__, named, **extra)
  File "/nix/store/n80wdj3jmp9a8w07iqbmqr9lnawxxydn-borgbackup-1.2.2/lib/python3.10/site-packages/borg/remote.py", line 711, in call
    for resp in self.call_many(cmd, [args], **kw):
  File "/nix/store/n80wdj3jmp9a8w07iqbmqr9lnawxxydn-borgbackup-1.2.2/lib/python3.10/site-packages/borg/remote.py", line 828, in call_many
    raise ConnectionClosed()
borg.remote.ConnectionClosed: Connection closed by remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/n80wdj3jmp9a8w07iqbmqr9lnawxxydn-borgbackup-1.2.2/lib/python3.10/site-packages/borg/archiver.py", line 5159, in main
    exit_code = archiver.run(args)
  File "/nix/store/n80wdj3jmp9a8w07iqbmqr9lnawxxydn-borgbackup-1.2.2/lib/python3.10/site-packages/borg/archiver.py", line 5090, in run
    return set_ec(func(args))
  File "/nix/store/n80wdj3jmp9a8w07iqbmqr9lnawxxydn-borgbackup-1.2.2/lib/python3.10/site-packages/borg/archiver.py", line 168, in wrapper
    with repository:
  File "/nix/store/n80wdj3jmp9a8w07iqbmqr9lnawxxydn-borgbackup-1.2.2/lib/python3.10/site-packages/borg/remote.py", line 636, in __exit__
    self.rollback()
  File "/nix/store/n80wdj3jmp9a8w07iqbmqr9lnawxxydn-borgbackup-1.2.2/lib/python3.10/site-packages/borg/remote.py", line 476, in do_rpc
    return self.call(f.__name__, named, **extra)
  File "/nix/store/n80wdj3jmp9a8w07iqbmqr9lnawxxydn-borgbackup-1.2.2/lib/python3.10/site-packages/borg/remote.py", line 711, in call
    for resp in self.call_many(cmd, [args], **kw):
  File "/nix/store/n80wdj3jmp9a8w07iqbmqr9lnawxxydn-borgbackup-1.2.2/lib/python3.10/site-packages/borg/remote.py", line 781, in call_many
    send_buffer()  # Try to send data, as some cases (async_response) will never try to send data otherwise.
  File "/nix/store/n80wdj3jmp9a8w07iqbmqr9lnawxxydn-borgbackup-1.2.2/lib/python3.10/site-packages/borg/remote.py", line 721, in send_buffer
    written = self.ratelimit.write(self.stdin_fd, self.to_send.peek_front())
  File "/nix/store/n80wdj3jmp9a8w07iqbmqr9lnawxxydn-borgbackup-1.2.2/lib/python3.10/site-packages/borg/remote.py", line 417, in write
    written = os.write(fd, to_send)
BrokenPipeError: [Errno 32] Broken pipe

Platform: Linux LenOwO 5.15.71 #1-NixOS SMP Wed Sep 28 09:11:58 UTC 2022 x86_64
Linux: Unknown Linux  
Borg: 1.2.2  Python: CPython 3.10.7 msgpack: 1.0.4 fuse: pyfuse3 3.2.2 [pyfuse3,llfuse]
PID: 40569  CWD: /home/annaaurora
sys.argv: ['/nix/store/n80wdj3jmp9a8w07iqbmqr9lnawxxydn-borgbackup-1.2.2/bin/borg', 'create', '--progress', '--stats', '--compression', 'zstd,22', '--exclude-caches', '--patterns-from', '/home/annaaurora/.borgpatterns', 'ssh://annaaurora@borg.artemislena.eu:2222/./::2022-10-13', '/home/annaaurora/']
SSH_ORIGINAL_COMMAND: None
```

## Describe the problem you're observing.
Borg fails to backup (some?) git pack files.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
It it reproducable with the command from the commandline output every time.

**Comment by infectormp** [comment]
Your problem is here - `Connection closed by remote host`. Did you already check [FAQ](https://borgbackup.readthedocs.io/en/stable/faq.html#common-issues)?

**Comment by abulka** [comment]
Am getting this problem too. The FAQ leads to an issue page which has some steps to try, with associated official doco seemingly at https://borgbackup.readthedocs.io/en/stable/usage/serve.html?highlight=lock-wait#examples. 

Possibly also related to #636

**Comment by auroraanna** [comment]
Hmm, I'm not getting the error anymore…

**Comment by tuxick** [comment]
In one case i found out a borg instance got shot by OOM killer, too many active clients for the memory on the borg server.
