### ISSUE TITLE
Bad File Descriptor

### ISSUE THREAD

**Issue by Buckelpiste** [borgbackup/borg#7131]
## Have you checked borgbackup docs, FAQ, and open Github issues?
Yes

## Is this a BUG / ISSUE report or a QUESTION?
Question

#### Your borg version (borg -V).
Borg 1.2.2
#### Operating system (distribution) and version.
Manjaro 
Kernel 6.0.2-2
#### Hardware / network configuration, and filesystems used.
Single-User machine (Thinkpad X220) in a home environment. Borg repository on a external HDD attached to the local router as a NAS. 
Mount command of the NAS (run via script before running borg)
```
mount -t cifs -o noserverino -o credentials=$CIFSCREDENTIALS $NETSHARE $MNTFOLDER
```
#### How much data is handled by borg?
Single machine with SSD of 149 GiB. Repo in total ~ 109GB. Last succesful Log (August 23th):
```
Number of files: 820682
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               88.83 GB             64.47 GB            353.94 MB
All archives:                1.75 TB              1.27 TB            100.78 GB
                       Unique chunks         Total chunks
Chunk index:                 1014929             16606174
------------------------------------------------------------------------------
```

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```
export BORG_PASSPHRASE="`cat $PWFILE`"
borg break-lock $REPOSITORY
borg create -v --stats					\
	--compression zlib,9				\
	--show-rc					\
	--exclude-caches				\
	--exclude-from $EXCLUDEFILE			\
	$REPOSITORY::`hostname`-`date +%Y-%m-%d`	
borg prune -v $REPOSITORY --prefix '{hostname}-' \
    --keep-daily=7 --keep-weekly=4 --keep-monthly=6 --keep-yearly=10 
unset BORG_PASSPHRASE	
```
Problem also appears when running borg prune or borg list on the repository.

## Describe the problem you're observing.
Since end of August borg is unable to access (list, info, check, create, prune, extract) the repository and returns ``OSError: [Errno 9] Bad file descriptor``.

- The issue started after one regular backup (borg create) on August 24th returned ``OSError: [Errno 112] Host is down`` (see first entry below). 
- In the next regular backup on September 04th borg returned ``OSError: [Errno 9] Bad file descriptor`` (see second entry below). 
- The Bad File Descriptor is the output since then, albeit during the next backups the traceback changed/evolved (see third entry below). 

I guess that this is not a bug/issue/problem of borg, but rather of my setting, namely I did something bad to my repository. I'd appreciate if you could help me anyway. My guess is that the repository files somehow have the wrong attributes. 

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
I can reproduce it by running any borg command on the repository (list, info, check, create, prune, extract).

#### Include any warning/errors/backtraces from the system logs
First error on August 24th: 
```
Creating archive at "/media/PATH::REPO-2022-08-24"
/var/SOME_FILE: read: [Errno 112] Host is down
/usr/bin/eapol_test: read: [Errno 112] Host is down
/usr/bin/wpa_supplicant: read: [Errno 112] Host is down
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 183, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 673, in do_create
    create_inner(archive, cache, fso)
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 606, in create_inner
    self._rec_walk(path=path, parent_fd=parent_fd, name=name,
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 818, in _rec_walk
    self._rec_walk(
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 818, in _rec_walk
    self._rec_walk(
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 818, in _rec_walk
    self._rec_walk(
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 784, in _rec_walk
    status = self._process_any(path=path, parent_fd=parent_fd, name=name, st=st, fso=fso, cache=cache,
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 686, in _process_any
    return fso.process_file(path=path, parent_fd=parent_fd, name=name, st=st, cache=cache)
  File "/usr/lib/python3.10/site-packages/borg/archive.py", line 1392, in process_file
    with self.create_helper(path, st, None) as (item, status, hardlinked, hardlink_master):  # no status yet
  File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/usr/lib/python3.10/site-packages/borg/archive.py", line 1317, in create_helper
    self.add_item(item, stats=self.stats)
  File "/usr/lib/python3.10/site-packages/borg/archive.py", line 600, in add_item
    self.items_buffer.add(item)
  File "/usr/lib/python3.10/site-packages/borg/archive.py", line 357, in add
    self.flush()
  File "/usr/lib/python3.10/site-packages/borg/archive.py", line 385, in flush
    self.chunks.append(self.write_chunk(chunk))
  File "/usr/lib/python3.10/site-packages/borg/archive.py", line 401, in write_chunk
    id_, _, _ = self.cache.add_chunk(self.key.id_hash(chunk), chunk, self.stats, wait=False)
  File "/usr/lib/python3.10/site-packages/borg/cache.py", line 951, in add_chunk
    self.repository.put(id, data, wait=wait)
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 1224, in put
    segment, offset = self.io.write_put(id, data)
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 1638, in write_put
    fd.write(b''.join((crc, header, id, data)))
  File "/usr/lib/python3.10/site-packages/borg/platform/base.py", line 176, in write
    self.f.write(data)
OSError: [Errno 112] Host is down

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/borg/platform/base.py", line 196, in close
    self.sync()
  File "/usr/lib/python3.10/site-packages/borg/platform/base.py", line 184, in sync
    self.f.flush()
OSError: [Errno 112] Host is down

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 5115, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 5046, in run
    return set_ec(func(args))
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 168, in wrapper
    with repository:
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 214, in __exit__
    self.close()
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 476, in close
    self.io.close()
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 1307, in close
    self.close_segment()
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 1463, in close_segment
    fd.close()
  File "/usr/lib/python3.10/site-packages/borg/platform/base.py", line 198, in close
    self.f.close()
OSError: [Errno 112] Host is down

Platform: Linux NAME_MACHINE 5.19.1-3-MANJARO #1 SMP PREEMPT_DYNAMIC Sat Aug 13 06:34:52 UTC 2022 x86_64
Linux: Unknown Linux
Borg: 1.2.1  Python: CPython 3.10.5 msgpack: 1.0.3 fuse: None [pyfuse3,llfuse]
PID: 3703  CWD: /
sys.argv: ['/usr/bin/borg', 'create', '-v', '--stats', '--compression', 'zlib,9', '--show-rc', '--exclude-caches', '--exclude-from', '/home/FILE', '/media/PATH::REPO-2022-08-24', '/']
SSH_ORIGINAL_COMMAND: None

terminating with error status, rc 2

Exception ignored in: <function Repository.__del__ at 0x7f332a6ada20>
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 189, in __del__
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 478, in close
  File "/usr/lib/python3.10/site-packages/borg/locking.py", line 417, in release
  File "/usr/lib/python3.10/site-packages/borg/locking.py", line 308, in modify
  File "/usr/lib/python3.10/site-packages/borg/locking.py", line 267, in load
NameError: name 'open' is not defined

Pruning Borg archive
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 5115, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 5046, in run
    return set_ec(func(args))
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 168, in wrapper
    with repository:
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 200, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 426, in open
    st = os.stat(path)
OSError: [Errno 112] Host is down: '/media/PATH'

Platform: Linux NAME_MACHINE 5.19.1-3-MANJARO #1 SMP PREEMPT_DYNAMIC Sat Aug 13 06:34:52 UTC 2022 x86_64
Linux: Unknown Linux
Borg: 1.2.1  Python: CPython 3.10.5 msgpack: 1.0.3 fuse: None [pyfuse3,llfuse]
PID: 5320  CWD: /
sys.argv: ['/usr/bin/borg', 'prune', '-v', '/media/PATH', '--prefix', '{hostname}-', '--keep-daily=7', '--keep-weekly=4', '--keep-monthly=6', '--keep-yearly=10']
SSH_ORIGINAL_COMMAND: None

```

Second error on September 4th:
```
Creating archive at "/media/PATH::REPO-2022-09-04"
/var/SOME_FILE: read: [Errno 9] Bad file descriptor
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 183, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 673, in do_create
    create_inner(archive, cache, fso)
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 606, in create_inner
    self._rec_walk(path=path, parent_fd=parent_fd, name=name,
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 818, in _rec_walk
    self._rec_walk(
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 818, in _rec_walk
    self._rec_walk(
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 818, in _rec_walk
    self._rec_walk(
  [Previous line repeated 4 more times]
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 784, in _rec_walk
    status = self._process_any(path=path, parent_fd=parent_fd, name=name, st=st, fso=fso, cache=cache,
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 686, in _process_any
    return fso.process_file(path=path, parent_fd=parent_fd, name=name, st=st, cache=cache)
  File "/usr/lib/python3.10/site-packages/borg/archive.py", line 1392, in process_file
    with self.create_helper(path, st, None) as (item, status, hardlinked, hardlink_master):  # no status yet
  File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/usr/lib/python3.10/site-packages/borg/archive.py", line 1317, in create_helper
    self.add_item(item, stats=self.stats)
  File "/usr/lib/python3.10/site-packages/borg/archive.py", line 600, in add_item
    self.items_buffer.add(item)
  File "/usr/lib/python3.10/site-packages/borg/archive.py", line 357, in add
    self.flush()
  File "/usr/lib/python3.10/site-packages/borg/archive.py", line 385, in flush
    self.chunks.append(self.write_chunk(chunk))
  File "/usr/lib/python3.10/site-packages/borg/archive.py", line 401, in write_chunk
    id_, _, _ = self.cache.add_chunk(self.key.id_hash(chunk), chunk, self.stats, wait=False)
  File "/usr/lib/python3.10/site-packages/borg/cache.py", line 951, in add_chunk
    self.repository.put(id, data, wait=wait)
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 1224, in put
    segment, offset = self.io.write_put(id, data)
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 1638, in write_put
    fd.write(b''.join((crc, header, id, data)))
  File "/usr/lib/python3.10/site-packages/borg/platform/base.py", line 176, in write
    self.f.write(data)
OSError: [Errno 9] Bad file descriptor
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/borg/platform/base.py", line 196, in close
    self.sync()
  File "/usr/lib/python3.10/site-packages/borg/platform/base.py", line 184, in sync
    self.f.flush()
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 5115, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 5046, in run
    return set_ec(func(args))
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 168, in wrapper
    with repository:
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 214, in __exit__
    self.close()
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 476, in close
    self.io.close()
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 1307, in close
    self.close_segment()
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 1463, in close_segment
    fd.close()
  File "/usr/lib/python3.10/site-packages/borg/platform/base.py", line 198, in close
    self.f.close()
OSError: [Errno 9] Bad file descriptor

Platform: Linux NAME_MACHINE 5.19.1-3-MANJARO #1 SMP PREEMPT_DYNAMIC Sat Aug 13 06:34:52 UTC 2022 x86_64
Linux: Unknown Linux
Borg: 1.2.1  Python: CPython 3.10.5 msgpack: 1.0.3 fuse: None [pyfuse3,llfuse]
PID: 2778  CWD: /
sys.argv: ['/usr/bin/borg', 'create', '-v', '--stats', '--compression', 'zlib,9', '--show-rc', '--exclude-caches', '--exclude-from', '/home/FILE', '/media/PATH::REPO-2022-09-04', '/']
SSH_ORIGINAL_COMMAND: None

terminating with error status, rc 2

Exception ignored in: <function Repository.__del__ at 0x7f8650569a20>
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 189, in __del__
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 478, in close
  File "/usr/lib/python3.10/site-packages/borg/locking.py", line 417, in release
  File "/usr/lib/python3.10/site-packages/borg/locking.py", line 308, in modify
  File "/usr/lib/python3.10/site-packages/borg/locking.py", line 267, in load
NameError: name 'open' is not defined

Pruning Borg archive
Killed stale lock REPO@17642269732576.2778-0.
Removed stale exclusive roster lock for host REPO@17642269732576 pid 2778 thread 0.
Removed stale exclusive roster lock for host REPO@17642269732576 pid 2778 thread 0.
Repository index missing or corrupted, trying to recover from: [Errno 9] Bad file descriptor
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 526, in open_index
    return NSIndex.read(fd)
  File "src/borg/hashindex.pyx", line 114, in borg.hashindex.IndexBase.read
  File "src/borg/hashindex.pyx", line 99, in borg.hashindex.IndexBase.__cinit__
  File "/usr/lib/python3.10/site-packages/borg/crypto/file_integrity.py", line 32, in read
    return self.fd.read(n)
  File "/usr/lib/python3.10/site-packages/borg/crypto/file_integrity.py", line 82, in read
    data = super().read(n)
  File "/usr/lib/python3.10/site-packages/borg/crypto/file_integrity.py", line 32, in read
    return self.fd.read(n)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 5115, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 5046, in run
    return set_ec(func(args))
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 170, in wrapper
    kwargs['manifest'], kwargs['key'] = Manifest.load(repository, compatibility)
  File "/usr/lib/python3.10/site-packages/borg/helpers/manifest.py", line 183, in load
    cdata = repository.get(cls.MANIFEST_ID)
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 1195, in get
    self.index = self.open_index(self.get_transaction_id())
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 532, in open_index
    self.prepare_txn(self.get_transaction_id())
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 412, in get_transaction_id
    self.check_transaction()
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 393, in check_transaction
    segments_transaction_id = self.io.get_segments_transaction_id()
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 1348, in get_segments_transaction_id
    if self.is_committed_segment(segment):
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 1388, in is_committed_segment
    tag, key, offset, _ = next(iterator)
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 1502, in iter_objects
    if fd.read(MAGIC_LEN) != MAGIC:
OSError: [Errno 9] Bad file descriptor

Platform: Linux NAME_MACHINE 5.19.1-3-MANJARO #1 SMP PREEMPT_DYNAMIC Sat Aug 13 06:34:52 UTC 2022 x86_64
Linux: Unknown Linux
Borg: 1.2.1  Python: CPython 3.10.5 msgpack: 1.0.3 fuse: None [pyfuse3,llfuse]
PID: 3657  CWD: /
sys.argv: ['/usr/bin/borg', 'prune', '-v', '/media/PATH', '--prefix', '{hostname}-', '--keep-daily=7', '--keep-weekly=4', '--keep-monthly=6', '--keep-yearly=10']
SSH_ORIGINAL_COMMAND: None

```

There have been variations of the traceback in between, all leading to a ``bad file descriptor``. I can post them if necessary.
Last error on October 28th:
```
Creating Borg-backup
task:borg            state:D stack:    0 pid: 3908 ppid:  3861 flags:0x00000006
task:borg            state:D stack:    0 pid: 3908 ppid:  3861 flags:0x00000006
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 5159, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 5090, in run
    return set_ec(func(args))
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 170, in wrapper
    kwargs['manifest'], kwargs['key'] = Manifest.load(repository, compatibility)
  File "/usr/lib/python3.10/site-packages/borg/helpers/manifest.py", line 183, in load
    cdata = repository.get(cls.MANIFEST_ID)
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 1200, in get
    self.index = self.open_index(self.get_transaction_id())
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 412, in get_transaction_id
    self.check_transaction()
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 409, in check_transaction
    self.replay_segments(replay_from, segments_transaction_id)
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 902, in replay_segments
    self._update_index(segment, objects)
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 912, in _update_index
    for tag, key, offset, size in objects:
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 1512, in iter_objects
    size, tag, key, data = self._read(fd, self.header_fmt, header, segment, offset,
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 1606, in _read
    data = fd.read(length)
OSError: [Errno 9] Bad file descriptor

Platform: Linux NAME_MACHINE 6.0.2-2-MANJARO #1 SMP PREEMPT_DYNAMIC Sat Oct 15 13:31:58 UTC 2022 x86_64
Linux: Unknown Linux
Borg: 1.2.2  Python: CPython 3.10.7 msgpack: 1.0.4 fuse: None [pyfuse3,llfuse]
PID: 3908  CWD: /
sys.argv: ['/usr/bin/borg', 'create', '-v', '--stats', '--compression', 'zlib,9', '--show-rc', '--exclude-caches', '--exclude-from', '/home/FILE', '/media/PATH::REPO-2022-10-28', '/']
SSH_ORIGINAL_COMMAND: None

terminating with error status, rc 2

Pruning Borg archive
Warning: "--prefix" has been deprecated. Use "--glob-archives 'yourprefix*'" (-a) instead.
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 5159, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 5090, in run
    return set_ec(func(args))
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 170, in wrapper
    kwargs['manifest'], kwargs['key'] = Manifest.load(repository, compatibility)
  File "/usr/lib/python3.10/site-packages/borg/helpers/manifest.py", line 183, in load
    cdata = repository.get(cls.MANIFEST_ID)
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 1200, in get
    self.index = self.open_index(self.get_transaction_id())
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 412, in get_transaction_id
    self.check_transaction()
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 409, in check_transaction
    self.replay_segments(replay_from, segments_transaction_id)
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 902, in replay_segments
    self._update_index(segment, objects)
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 912, in _update_index
    for tag, key, offset, size in objects:
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 1512, in iter_objects
    size, tag, key, data = self._read(fd, self.header_fmt, header, segment, offset,
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 1606, in _read
    data = fd.read(length)
OSError: [Errno 9] Bad file descriptor

Platform: Linux NAME_MACHINE 6.0.2-2-MANJARO #1 SMP PREEMPT_DYNAMIC Sat Oct 15 13:31:58 UTC 2022 x86_64
Linux: Unknown Linux
Borg: 1.2.2  Python: CPython 3.10.7 msgpack: 1.0.4 fuse: None [pyfuse3,llfuse]
PID: 5220  CWD: /
sys.argv: ['/usr/bin/borg', 'prune', '-v', '/media/PATH', '--prefix', '{hostname}-', '--keep-daily=7', '--keep-weekly=4', '--keep-monthly=6', '--keep-yearly=10']
SSH_ORIGINAL_COMMAND: None

```

**Comment by infectormp** [comment]
You are right these errors (`OSError`) related to network and FS on target device. You need to use [borg check](https://borgbackup.readthedocs.io/en/stable/usage/check.html#borg-check) command to repair repository but before that you need to check your FS for errors and repair them.

**Comment by ThomasWaldmann** [comment]
Your network file system looks rather unreliable (see also "host is down"), I guess you should first fix that before doing **anything** with it.

Especially, I would **not** recommend running `borg check --repair` as long as it is not stable.

**Comment by ThomasWaldmann** [comment]
Guess this is solved?

**Comment by Buckelpiste** [comment]
Solved, sorry for not replying. 

I did a workaround by performing a backup with the external HDD connected directly to my laptop. Afterwards Borg worked again via NAS. I expect to buy new hardware of all kind soon, therefore I wouldn't spend any more time on this.
