### ISSUE TITLE
master branch / 2.0.0b3: crash in borg transfer

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#7156]
reported by @mbo77 there: https://github.com/borgbackup/borg/discussions/7070#discussioncomment-4234898

```
Local Exception
Traceback (most recent call last):
  File "/usr/local/lib64/python3.10/site-packages/borg/archiver/__init__.py", line 594, in main
    exit_code = archiver.run(args)
  File "/usr/local/lib64/python3.10/site-packages/borg/archiver/__init__.py", line 522, in run
    return set_ec(func(args))
  File "/usr/local/lib64/python3.10/site-packages/borg/archiver/_common.py", line 223, in wrapper
    return method(self, args, **kwargs)
  File "/usr/local/lib64/python3.10/site-packages/borg/archiver/_common.py", line 155, in wrapper
    return method(self, args, repository=repository, cache=cache_, **kwargs)
  File "/usr/local/lib64/python3.10/site-packages/borg/archiver/transfer_cmd.py", line 66, in do_transfer
    for item in other_archive.iter_items():
  File "/usr/local/lib64/python3.10/site-packages/borg/archive.py", line 610, in iter_items
    for item in self.pipeline.unpack_many(
  File "/usr/local/lib64/python3.10/site-packages/borg/archive.py", line 282, in unpack_many
    for data in self.fetch_many(ids):
  File "/usr/local/lib64/python3.10/site-packages/borg/archive.py", line 313, in fetch_many
    _, data = self.repo_objs.parse(id_, cdata)
  File "/usr/local/lib64/python3.10/site-packages/borg/repoobj.py", line 157, in parse
    meta["csize"] = len(data_compressed)
TypeError: 'NoneType' object does not support item assignment

Platform: Linux ds9 6.0.8-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Nov 11 15:03:58 UTC 2022 x86_64
Linux: Unknown Linux
Borg: 2.0.0b3  Python: CPython 3.10.8 msgpack: 1.0.3 fuse: llfuse 1.4.2 [pyfuse3,llfuse]
PID: 3759256  CWD: /datapool
sys.argv: ['/usr/local/bin/borg', 'transfer', '--other-repo', '/mnt/backup/bDISK/borg', '--repo', '/datapool/borg2', '--upgrader=From12To20', '--dry-run']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment]
see #7157.
