### ISSUE TITLE
Recovery from a incomplete repository (Unraid cache lost)

### ISSUE THREAD

**Issue by xLogiiCx** [borgbackup/borg#7238]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

## System information. For client/server mode post info for both machines.
Tower PC

#### Your borg version (borg -V).
borg 1.2.2

#### Operating system (distribution) and version.
Client: Linux 6.1.1-zen1-1-zen
Server: Linux 5.19.17-Unraid x86_64 

#### Hardware / network configuration, and filesystems used.
btrfs (encrypted)

#### How much data is handled by borg?
about 200GB

## Describe the problem you're observing.

Hi, i hope this is the right Place for this Question.
I am using borg to Backup from my Home PC to my Home NAS which is running UnRAID.
The UnRAID Server uses "cache" Disks so the "normal" Disk Array does not have to be spun up.
Every Day at a given time the Data is moved of the Cache Disk onto the Array. That means all files sent from borg to nas during the day are on the cache disk until say 12 o'clock.
the array is protected against the failure of a hard drive, the cache disk is not. 

I just run a Backup (prune,compact,create) to test and following files are now on my Cache Disk:
```
.
├── data
│   └── 13
│       ├── 13095
│       ├── 13097
│       ├── 13098
│       ├── 13099
│       ├── 13100
│       ├── 13101
│       └── 13102
├── hints.13102
├── index.13102
└── integrity.13102

2 directories, 10 files
```
all the other files of the Repo are on the Protected Array. 

How 'bad' would it be if the Cache Disk would die before moving the data to the Array? Would i just loose the Backup for the day or would it corrupt the archive unrecoverable?

**Comment by ThomasWaldmann** [comment]
If you still have a complete, valid state of the repo (as it was at some time in the past) after the cache disk failure, you can use that repo state to recover from backup archives contained in that state. That would be the case if the repo has all the files like the first n-1 backups have create, but misses all the files created/modified by the n-th backup.

Whether that is the case is not a borg, but rather a unraid question.

**Comment by xLogiiCx** [comment]
as far as i am concerned when the cache disk fails  following files would be completely gone:
```
.
├── data
│   └── 13
│       ├── 13095
│       ├── 13097
│       ├── 13098
│       ├── 13099
│       ├── 13100
│       ├── 13101
│       └── 13102
├── hints.13102
├── index.13102
└── integrity.13102
```

**Comment by ThomasWaldmann** [comment]
The data files look like what borg appended for the latest backup.

index/hints/integrity are also from the latest transaction and either you have these files with a lower number still on disk or they could be recreated by `borg check --repair` if lost.

**Comment by xLogiiCx** [comment]
Okay, so it looks like my repo would survive a cache disk failure. Just to make sure ill test this :D.

**Comment by ThomasWaldmann** [comment]
BTW, you could just make some experimental repo and try out what happens...

**Comment by xLogiiCx** [comment]
I created a test Repo to check if this is the case.
Commands:
`borg init -e repokey-blake2 ssh://root@unraid:22/mnt/user/Backup/test.borg`
`borg create ssh://root@unraid:22/mnt/user/Backup/test.borg::1 Downloads/`
Files on Cache:
```
test.borg/
├── README
├── config
├── data
│   └── 0
│       ├── 0
│       ├── 1
│       ├── 2
│       ├── 3
│       ├── 4
│       ├── 5
│       └── 6
├── hints.6
├── index.6
├── integrity.6
└── nonce

2 directories, 13 files
```
Files on Array:
none

After starting the mover to get all the files of the Cache Disk onto the Array it looks like following:

Files on Cache:
none

Files on Array:
```
test.borg/
├── README
├── config
├── data
│   └── 0
│       ├── 0
│       ├── 1
│       ├── 2
│       ├── 3
│       ├── 4
│       ├── 5
│       └── 6
├── hints.6
├── index.6
├── integrity.6
└── nonce

2 directories, 13 files
```

Now if i create another Archive (deleting 1 adding 1 file) it looks like this:
`borg create ssh://root@unraid:22/mnt/user/Backup/test.borg::2 Downloads/`
Files on Cache:
```
test.borg/
├── data
│   └── 0
│       ├── 10
│       ├── 7
│       ├── 8
│       └── 9
├── hints.10
├── index.10
├── integrity.10
└── nonce

2 directories, 8 files
```
Files on Array:
```
test.borg/
├── README
├── config
└── data
    └── 0
        ├── 0
        ├── 1
        ├── 2
        ├── 3
        ├── 4
        ├── 5
        └── 6

2 directories, 9 files
```

Now i am going to delete all Data on the Cache drive:
```
borg list ssh://root@192.168.179.2:22/mnt/user/Backup/test.borg
Enter passphrase for key ssh://root@192.168.179.2:22/mnt/user/Backup/test.borg: 
Cache, or information obtained from the security directory is newer than repository - this is either an attack or unsafe (multiple repos with same ID)
```
seems broken, so ill try a check:
```
borg check --debug --repository-only ssh://root@192.168.179.2:22/mnt/user/Backup/test.borg
using builtin fallback logging configuration
33 self tests completed in 0.04 seconds
SSH command line: ['ssh', '-p', '22', 'root@192.168.179.2', 'borg', 'serve', '--debug']
Remote: using builtin fallback logging configuration
Remote: 33 self tests completed in 0.07 seconds
Remote: using builtin fallback logging configuration
Remote: Initialized logging system for JSON-based protocol
Remote: Resolving repository path b'/mnt/user/Backup/test.borg'
Remote: Resolved repository path to '/mnt/user/Backup/test.borg'
Remote: Traceback (most recent call last):

  File "borg/remote.py", line 240, in serve

  File "borg/remote.py", line 368, in open

  File "borg/repository.py", line 200, in __enter__

  File "borg/repository.py", line 426, in open

OSError: [Errno 107] Transport endpoint is not connected: '/mnt/user/Backup/test.borg'

Traceback (most recent call last):

  File "borg/remote.py", line 240, in serve

  File "borg/remote.py", line 368, in open

  File "borg/repository.py", line 200, in __enter__

  File "borg/repository.py", line 426, in open

OSError: [Errno 107] Transport endpoint is not connected: '/mnt/user/Backup/test.borg'

Borg server: Platform: Linux UnRAID 5.19.17-Unraid #2 SMP PREEMPT_DYNAMIC Wed Nov 2 11:54:15 PDT 2022 x86_64
Borg server: Linux: Unknown Linux  
Borg server: Borg: 1.2.2  Python: CPython 3.9.13 msgpack: 1.0.4 fuse: llfuse 1.4.2 [pyfuse3,llfuse]
Borg server: PID: 26595  CWD: /root
Borg server: sys.argv: ['borg', 'serve', '--debug']
Borg server: SSH_ORIGINAL_COMMAND: None
Platform: Linux ppc 6.1.1-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Wed, 21 Dec 2022 22:27:59 +0000 x86_64
Linux: Unknown Linux  
Borg: 1.2.2  Python: CPython 3.10.9 msgpack: 1.0.4 fuse: llfuse 1.4.2 [pyfuse3,llfuse]
PID: 746457  CWD: /home/user
sys.argv: ['/usr/bin/borg', 'check', '--debug', '--repository-only', 'ssh://root@192.168.179.2:22/mnt/user/Backup/test.borg']
SSH_ORIGINAL_COMMAND: None
```
seems like a bigger issue here borg repair also has problems with the data loss:
```
borg check --debug --repair ssh://root@192.168.179.2:22/mnt/user/Backup/test.borg
using builtin fallback logging configuration
33 self tests completed in 0.04 seconds
SSH command line: ['ssh', '-p', '22', 'root@192.168.179.2', 'borg', 'serve', '--debug']
Remote: using builtin fallback logging configuration
Remote: 33 self tests completed in 0.07 seconds
Remote: using builtin fallback logging configuration
Remote: Initialized logging system for JSON-based protocol
Remote: Resolving repository path b'/mnt/user/Backup/test.borg'
Remote: Resolved repository path to '/mnt/user/Backup/test.borg'
Remote: Traceback (most recent call last):

  File "borg/remote.py", line 240, in serve

  File "borg/remote.py", line 368, in open

  File "borg/repository.py", line 200, in __enter__

  File "borg/repository.py", line 426, in open

OSError: [Errno 107] Transport endpoint is not connected: '/mnt/user/Backup/test.borg'

Traceback (most recent call last):

  File "borg/remote.py", line 240, in serve

  File "borg/remote.py", line 368, in open

  File "borg/repository.py", line 200, in __enter__

  File "borg/repository.py", line 426, in open

OSError: [Errno 107] Transport endpoint is not connected: '/mnt/user/Backup/test.borg'

Borg server: Platform: Linux UnRAID 5.19.17-Unraid #2 SMP PREEMPT_DYNAMIC Wed Nov 2 11:54:15 PDT 2022 x86_64
Borg server: Linux: Unknown Linux  
Borg server: Borg: 1.2.2  Python: CPython 3.9.13 msgpack: 1.0.4 fuse: llfuse 1.4.2 [pyfuse3,llfuse]
Borg server: PID: 29685  CWD: /root
Borg server: sys.argv: ['borg', 'serve', '--debug']
Borg server: SSH_ORIGINAL_COMMAND: None
Platform: Linux ppc 6.1.1-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Wed, 21 Dec 2022 22:27:59 +0000 x86_64
Linux: Unknown Linux  
Borg: 1.2.2  Python: CPython 3.10.9 msgpack: 1.0.4 fuse: llfuse 1.4.2 [pyfuse3,llfuse]
PID: 749311  CWD: /home/user
sys.argv: ['/usr/bin/borg', 'check', '--debug', '--repair', 'ssh://root@192.168.179.2:22/mnt/user/Backup/test.borg']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment]
Guess this can be closed.
