### ISSUE TITLE
Corruption not handled on non hex digits

### ISSUE THREAD

**Issue by poelzi** [borgbackup/borg#7266]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

No

## Is this a BUG / ISSUE report or a QUESTION?

Bug

#### Your borg version (borg -V).

borg 1.2.2

#### Operating system (distribution) and version.

Nixos 22.11

#### Hardware / network configuration, and filesystems used.

ext4

#### How much data is handled by borg?

200 GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

sudo BORG_PASSCOMMAND='cat /etc/nixos/borg/rootbackup.key' borg check --verify-data -v --repair .

## Describe the problem you're observing.

Crashes with corruption. Repair does not handle problem. Check even did not report corruption.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
```
#### Include any warning/errors/backtraces from the system logs
 sudo BORG_PASSCOMMAND='cat /etc/nixos/borg/rootbackup.key' borg check --verify-data -v --repair .
[sudo] password for poelzi: 
This is a potentially dangerous function.
check --repair might lead to data loss (for kinds of corruption it is not
capable of dealing with). BE VERY CAREFUL!

Type 'YES' if you understand this and want to continue: YES
Starting repository check
finished segment check at segment 8580
Starting repository index check
Finished full repository check, no problems found.
Starting archive consistency check...
Starting cryptographic data integrity verification...
Finished cryptographic data integrity verification, verified 2716200 chunks with 0 integrity errors.
Analyzing archive galaxy-root-2020-10-31T00:00:09 (1/14)
Local Exception
Traceback (most recent call last):
  File "/nix/store/k1l607brycl3lrwxmfvvawlffqcklgvh-borgbackup-1.2.2/lib/python3.10/site-packages/borg/archiver.py", line 5159, in main
    exit_code = archiver.run(args)
  File "/nix/store/k1l607brycl3lrwxmfvvawlffqcklgvh-borgbackup-1.2.2/lib/python3.10/site-packages/borg/archiver.py", line 5090, in run
    return set_ec(func(args))
  File "/nix/store/k1l607brycl3lrwxmfvvawlffqcklgvh-borgbackup-1.2.2/lib/python3.10/site-packages/borg/archiver.py", line 183, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/nix/store/k1l607brycl3lrwxmfvvawlffqcklgvh-borgbackup-1.2.2/lib/python3.10/site-packages/borg/archiver.py", line 347, in do_check
    if not args.repo_only and not ArchiveChecker().check(
  File "/nix/store/k1l607brycl3lrwxmfvvawlffqcklgvh-borgbackup-1.2.2/lib/python3.10/site-packages/borg/archive.py", line 1630, in check
    self.rebuild_refcounts(archive=archive, first=first, last=last, sort_by=sort_by, glob=glob)
  File "/nix/store/k1l607brycl3lrwxmfvvawlffqcklgvh-borgbackup-1.2.2/lib/python3.10/site-packages/borg/archive.py", line 2042, in rebuild_refcounts
    items_buffer.add(item)
  File "/nix/store/k1l607brycl3lrwxmfvvawlffqcklgvh-borgbackup-1.2.2/lib/python3.10/site-packages/borg/archive.py", line 357, in add
    self.flush()
  File "/nix/store/k1l607brycl3lrwxmfvvawlffqcklgvh-borgbackup-1.2.2/lib/python3.10/site-packages/borg/archive.py", line 385, in flush
    self.chunks.append(self.write_chunk(chunk))
  File "/nix/store/k1l607brycl3lrwxmfvvawlffqcklgvh-borgbackup-1.2.2/lib/python3.10/site-packages/borg/archive.py", line 1829, in add_callback
    cdata = self.key.encrypt(chunk)
  File "/nix/store/k1l607brycl3lrwxmfvvawlffqcklgvh-borgbackup-1.2.2/lib/python3.10/site-packages/borg/crypto/key.py", line 370, in encrypt
    next_iv = self.nonce_manager.ensure_reservation(self.cipher.next_iv(),
  File "/nix/store/k1l607brycl3lrwxmfvvawlffqcklgvh-borgbackup-1.2.2/lib/python3.10/site-packages/borg/crypto/nonces.py", line 79, in ensure_reservation
    repo_free_nonce = self.get_repo_free_nonce()
  File "/nix/store/k1l607brycl3lrwxmfvvawlffqcklgvh-borgbackup-1.2.2/lib/python3.10/site-packages/borg/crypto/nonces.py", line 38, in get_repo_free_nonce
    return self.repository.get_free_nonce()
  File "/nix/store/k1l607brycl3lrwxmfvvawlffqcklgvh-borgbackup-1.2.2/lib/python3.10/site-packages/borg/repository.py", line 352, in get_free_nonce
    return int.from_bytes(unhexlify(fd.read()), byteorder='big')
binascii.Error: Non-hexadecimal digit found

Platform: Linux galaxy 5.15.81 #1-NixOS SMP PREEMPT Fri Dec 2 16:41:12 UTC 2022 x86_64
Linux: Unknown Linux  
Borg: 1.2.2  Python: CPython 3.10.8 msgpack: 1.0.4 fuse: pyfuse3 3.2.2 [pyfuse3,llfuse]
PID: 234835  CWD: /run/media/poelzi/backup-2/borg-galaxy
sys.argv: ['/nix/store/k1l607brycl3lrwxmfvvawlffqcklgvh-borgbackup-1.2.2/bin/borg', 'check', '--verify-data', '-v', '--repair', '.']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment]
Check the `nonce` file in your repo directory. IIRC, it should contain a 256bit hex value.

**Comment by ThomasWaldmann** [comment]
Any news?

**Comment by poelzi** [comment]
The nonce file has 16 bytes and looks all hex.
something like '00000006d1b13ac7'

**Comment by ThomasWaldmann** [comment]
Did you find out what the problem was?
