### ISSUE TITLE
mount crashes on some dirs/files

### ISSUE THREAD

**Issue by ipha** [borgbackup/borg#732]
borg version: 1.0.0
llfuse version: 0.43 and 1.0

I have a directory that crashes borg when I try to list files or read files in that directory. The rest of the backup works and can read everything else just not `sort/Video`

`cd ~/tmp/sort/Video`: works
`ls ~/tmp/sort/Video`: fails
-restart borg-
`file ~/tmp/sort/Video/Video02052048.3gp`: fails
-restart borg-
`borg extract ... sort/Video/Video02052048.3gp`: works

Contents of ~/sort/Video:
```
% ls -la ~/sort/Video
total 14952
drwxr-xr-x 1 mitch mitch     204 Oct 30  2014 .
drwxr-xr-x 1 mitch mitch     752 Feb 11 14:52 ..
-rw-r--r-- 1 mitch mitch  799806 Feb  5  2014 Video02052048.3gp
-rw-r--r-- 1 mitch mitch 1565200 Feb 11  2014 Video02112138.3gp
-rw-r--r-- 1 mitch mitch 9191179 Feb 11  2014 Video02112158.3gp
-rw-r--r-- 1 mitch mitch   92925 Mar 17  2014 Video03171931.3gp
-rw-r--r-- 1 mitch mitch 2243317 May  4  2014 Video05041457.3gp
-rw-r--r-- 1 mitch mitch 1405895 Aug  7  2014 Video08071802.3gp
```

Debug log:
```
using builtin fallback logging configuration
Mounting filesystem
Initializing llfuse
Calling fuse_mount
Calling fuse_lowlevel_new
Calling fuse_session_add_chan
Calling fuse_session_loop
handler raised <class 'TypeError'> exception (unsupported operand type(s) for /: 'bytes' and 'int'), terminating main loop.
Terminated main loop because request handler raised exception, re-raising..
Calling fuse_session_remove_chan
Calling fuse_session_destroy
Local Exception.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 1466, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 1420, in run
    return args.func(args)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 427, in do_mount
    operations.mount(args.mountpoint, args.options, args.foreground)
  File "/usr/lib/python3.5/site-packages/borg/fuse.py", line 253, in mount
    signal = fuse_main()
  File "/usr/lib/python3.5/site-packages/borg/fuse.py", line 20, in fuse_main
    return llfuse.main(workers=1)
  File "src/fuse_api.pxi", line 343, in llfuse.main (src/llfuse.c:35968)
  File "src/handlers.pxi", line 459, in llfuse.fuse_readdir (src/llfuse.c:18635)
  File "src/handlers.pxi", line 460, in llfuse.fuse_readdir (src/llfuse.c:18404)
  File "/usr/lib/python3.5/site-packages/borg/fuse.py", line 232, in readdir
    yield name, self.getattr(inode), i + 1
  File "/usr/lib/python3.5/site-packages/borg/fuse.py", line 167, in getattr
    entry.st_atime_ns = item.get(b'atime') or item[b'mtime']
  File "src/misc.pxi", line 471, in llfuse.EntryAttributes.st_atime_ns.__set__ (src/llfuse.c:30591)
TypeError: unsupported operand type(s) for /: 'bytes' and 'int'

Platform: Linux ginger 4.4.4-1-ARCH #1 SMP PREEMPT Fri Mar 4 15:40:05 CET 2016 x86_64
Linux: arch    LibC: glibc 2.3.4
Borg: 1.0.0  Python: CPython 3.5.1
PID: 27132  CWD: /home/mitch
sys.argv: ['/usr/bin/borg', 'mount', '-f', '-v', '--debug', '/mnt/storage/backup_local::home_2016-03-10', '/home/mitch/tmp']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ipha** [comment]
I'm guessing the files having an access time in the year 4446007 may have something to do with it.

```
% stat sort/Video/Video02052048.3gp
  File: 'sort/Video/Video02052048.3gp'
  Size: 799806          Blocks: 1568       IO Block: 4096   regular file
Device: 2ch/44d Inode: 3894079     Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/   mitch)   Gid: ( 1000/   mitch)
Access: 4446007-12-28 06:17:55.000000000 -0500
Modify: 2014-02-05 19:48:00.000000000 -0500
Change: 2015-12-10 19:18:09.855585407 -0500
 Birth: -
```
