### ISSUE TITLE
debian/ubuntu vagrant VMs: under tox, it can't find setup_docs

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#7391]
Since recently, there is a strange effect:
- first it builds borg without a problem into the virtual env
- then it invokes `fakeroot -u tox`, tries to build/install borg and fails due to not finding `setup_docs` module
- tox without fakeroot works

This had already worked, something got broken, not sure what it is.

Quickest way to test is to use the `jammy64` vagrant machine (master branch as of 2.0.0b5).

It happens also in the 3 debian VMs, but their startup is much slower as they use pyenv to build misc. pythons first.

**Comment by ThomasWaldmann** [comment]
```
(borg-clean-env) tw@ubuntu-desktop:~/w/borg-clean$ fakeroot -u tox
.pkg: _optional_hooks> python /home/tw/w/borg-clean-env/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: get_requires_for_build_sdist> python /home/tw/w/borg-clean-env/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: prepare_metadata_for_build_wheel> python /home/tw/w/borg-clean-env/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: build_sdist> python /home/tw/w/borg-clean-env/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta
py310-none: install_package> python -I -m pip install --force-reinstall --no-deps /home/tw/w/borg-clean/.tox/.tmp/package/2/borgbackup-2.0.0b6.dev153+g4d7c7b0f.d20230516.tar.gz
Processing ./.tox/.tmp/package/2/borgbackup-2.0.0b6.dev153+g4d7c7b0f.d20230516.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... error

WARNING: The directory '/home/tw/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "/home/tw/w/borg-clean/.tox/py310-none/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/tw/w/borg-clean/.tox/py310-none/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/tw/w/borg-clean/.tox/py310-none/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-nurbtwmv/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-nurbtwmv/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-nurbtwmv/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 23, in <module>
      ModuleNotFoundError: No module named 'setup_docs'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
py310-none: exit 1 (4.64 seconds) /home/tw/w/borg-clean> python -I -m pip install --force-reinstall --no-deps /home/tw/w/borg-clean/.tox/.tmp/package/2/borgbackup-2.0.0b6.dev153+g4d7c7b0f.d20230516.tar.gz pid=82302
py310-none: FAIL ✖ in 6.16 seconds
```
