### ISSUE TITLE
"Too many open files" after KeyError

### ISSUE THREAD

**Issue by Penaz91** [borgbackup/borg#7594]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Possible bug (May be due to a corrupted database)

#### Your borg version (borg -V).

borg 1.2.4

#### Operating system (distribution) and version.

(Output of `inxi -GSC -xx`)

```
System:
  Host: PenazMW2 Kernel: 6.1.28-1-lts arch: x86_64 bits: 64 compiler: gcc
    v: 13.1.1 Desktop: Openbox v: 3.6.1 dm: LightDM Distro: Artix Linux
    base: Arch Linux
CPU:
  Info: 6-core model: Intel Core i7-8750H bits: 64 type: MT MCP
    arch: Coffee Lake rev: A cache: L1: 384 KiB L2: 1.5 MiB L3: 9 MiB
  Speed (MHz): avg: 1532 high: 2200 min/max: 800/4100 cores: 1: 842 2: 2200
    3: 897 4: 900 5: 899 6: 2200 7: 832 8: 2200 9: 2200 10: 817 11: 2200
    12: 2200 bogomips: 52815
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: AMD Baffin [Radeon Pro WX 4130/4150] vendor: Dell driver: amdgpu
    v: kernel arch: GCN-4 pcie: speed: 8 GT/s lanes: 8 ports: active: eDP-1
    empty: DP-1, DP-2, DP-3, HDMI-A-1 bus-ID: 01:00.0 chip-ID: 1002:67e8
    temp: 48.0 C
  Device-2: Realtek Integrated Webcam HD driver: uvcvideo type: USB rev: 2.0
    speed: 480 Mb/s lanes: 1 bus-ID: 1-11:3 chip-ID: 0bda:568c
  Display: x11 server: X.Org v: 21.1.8 with: Xwayland v: 23.1.1
    compositor: Compton driver: X: loaded: amdgpu
    unloaded: fbdev,modesetting,vesa dri: radeonsi gpu: amdgpu display-ID: :0
    screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 96
  Monitor-1: eDP-1 mapped: eDP model: AU Optronics 0x139d res: 1920x1080
    dpi: 128 diag: 437mm (17.2")
  API: OpenGL v: 4.6 Mesa 23.0.3 renderer: AMD Radeon Pro WX Series
    (polaris11 LLVM 15.0.7 DRM 3.49 6.1.28-1-lts) direct-render: Yes
```

#### Hardware / network configuration, and filesystems used.

EXT4 home directory being backed up  (excluding hidden files) on a Samba-mounted NTFS Hard Disk

#### How much data is handled by borg?

About 250GB of deduplicated data, Vorta was showing an "original size" of about 6.7TB.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

Happens on both the following commands (generated by the Vorta frontend):

```
/usr/bin/borg create --list --progress --info --log-json --json --filter=AM -C lz4 /mnt/READYSHARE/Borg_Backup::PenazMW2-default-2023-05-19T19:57:43 /home/penaz
```

and

```
/usr/bin/borg check --info --log-json --progress /mnt/READYSHARE/Borg_Backup
```

## Describe the problem you're observing.

After trying to do an incremental backup I have been having issues where Borg crashes after about an hour into the backup.

I'm not sure if this is due to a corrupted backup.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

I thought this was a problem that originated from an old version bug with cache files, so I performed the following commands:

```
borg delete --cache-only /mnt/READYSHARE/Borg_Backup

borg check --repair /mnt/READYSHARE/Borg_Backup
```

With the second command crashing with the same error.

I can't really give much more information, since I deleted the old repository and I'm remaking the backup from scratch, but I thought this could be a bigger issue and preferred issuing a warning.

#### Include any warning/errors/backtraces from the system logs

```
2023-05-19 20:42:26,117 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
2023-05-19 20:57:26,108 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-05-19 20:57:26,117 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
2023-05-19 21:09:47,720 - vorta.borg.borg_job - ERROR - Local Exception
2023-05-19 21:09:47,720 - vorta.borg.borg_job - ERROR - Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/borg/repository.py", line 1453, in get_fd
    ts, fd = self.fds[segment]
             ~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/borg/lrucache.py", line 21, in __getitem__
    value = self._cache[key]  # raise KeyError if not found
            ~~~~~~~~~~~^^^^^
KeyError: 677

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/borg/archiver.py", line 5213, in main
    exit_code = archiver.run(args)
                ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/borg/archiver.py", line 5144, in run
    return set_ec(func(args))
                  ^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/borg/archiver.py", line 183, in wrapper
    return method(self, args, repository=repository, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/borg/archiver.py", line 675, in do_create
    create_inner(archive, cache, fso)
  File "/usr/lib/python3.11/site-packages/borg/archiver.py", line 633, in create_inner
    json_print(basic_json_data(manifest, cache=cache, extra={
  File "/usr/lib/python3.11/site-packages/borg/helpers/parseformat.py", line 1014, in json_print
    print(json_dump(obj))
          ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/borg/helpers/parseformat.py", line 1010, in json_dump
    return json.dumps(obj, sort_keys=True, indent=4, cls=BorgJsonEncoder)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.11/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/borg/helpers/parseformat.py", line 980, in default
    'stats': o.stats(),
             ^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/borg/cache.py", line 435, in stats
    archive = Archive(self.repository, self.key, self.manifest, archive_name,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/borg/archive.py", line 486, in __init__
    self.load(info.id)
  File "/usr/lib/python3.11/site-packages/borg/archive.py", line 497, in load
    self.metadata = self._load_meta(self.id)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/borg/archive.py", line 489, in _load_meta
    data = self.key.decrypt(id, self.repository.get(id))
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/borg/repository.py", line 1204, in get
    return self.io.read(segment, offset, id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/borg/repository.py", line 1569, in read
    fd = self.get_fd(segment)
         ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/borg/repository.py", line 1455, in get_fd
    fd = open_fd()
         ^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/borg/repository.py", line 1436, in open_fd
    fd = open(self.segment_filename(segment), 'rb')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 24] Too many open files: '/mnt/READYSHARE/Borg_Backup/data/0/677'
```

Thank you very much for your attention.

**Comment by infectormp** [comment]
This message came from OS. Please post here output from `ulimit -n -H`

**Comment by Penaz91** [comment]
> This message came from OS. Please post here output from `ulimit -n -H`

Thank you for your response, here's the output

```
[penaz@PenazMW2 ~]$ ulimit -n -H
4096
```

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/blob/1.2.4/src/borg/repository.py#L1304

Borg does not keep open more than 90 repository files. Additionally it has some other files open, so I'ld expect approximately 100, which usually is not a problem.

Maybe also check the limits on the samba server and whether something else opens a lot of files in parallel to borg.

**Comment by Penaz91** [comment]
Sadly I can't have any information about the Samba server (it's one of those "consumer electronics" routers that features Samba sharing, I really need to get a true NAS at some point).

After a quick

`lsof | grep -F ' REG ' | awk '{ print $1 " " $2; }' | sort -rn | uniq -c | sort -rn | head -50`

I can confirm that Borg doesn't seem to open more than 70-ish regular files on its own, but the Vorta GUI executing has almost 700.

I just remade the repository without much issue and I'm still having the same issue, now I'm trying to do a check of the new Borg repository by using just the Command Line tool. I will keep you informed.

**Comment by ThomasWaldmann** [comment]
@Penaz91 that sounds strange - I see no reason why vorta should have hundreds of files open.

can you `lsof` them and check the filenames to find out what they are?

**Comment by Penaz91** [comment]
> @Penaz91 that sounds strange - I see no reason why vorta should have hundreds of files open.
> 
> can you `lsof` them and check the filenames to find out what they are?

Sure thing, seems the biggest number are actually related to Python itself and Qt, plus a couple settings files. I think it was a red herring. I'm attaching the output of `lsof | grep -F ' REG ' | sort -rn | uniq -c | sort -rn | grep "vorta"` while Vorta is idle.

[lsof_vorta.txt](https://github.com/borgbackup/borg/files/11528552/lsof_vorta.txt)

----

On account of the file limit on the Samba share, I went and kind of brute-forced a number out of it with the following Python code:

```
x = []
for i in range(10000):
     try:
         x.append(open("/mnt/READYSHARE/testimage.jpg", "rb"))
     except Exception as ex:
         print(i)
         print(ex)
         for item in x:
             item.close()
         break
```

And this is the result

```
1012
[Errno 24] Too many open files: '/mnt/READYSHARE/testimage.jpg'
```

**Comment by ThomasWaldmann** [comment]
The real (filesystem) files opened by vorta are just a few.

**Comment by Penaz91** [comment]
It seems that after creating a new repository I can back up files without much trouble, but using the "compact" functionality (from Vorta) causes the same error.

```
2023-06-07 21:55:49,695 - vorta.borg.borg_job - INFO - Running command /usr/bin/borg --info --log-json compact --progress file:///mnt/READYSHARE/Borg_Backup
2023-06-07 21:55:52,565 - vorta.borg.borg_job - WARNING - segment 296 not found, but listed in compaction data
2023-06-07 21:55:52,571 - vorta.borg.borg_job - WARNING - segment 297 not found, but listed in compaction data
2023-06-07 21:55:52,576 - vorta.borg.borg_job - WARNING - segment 298 not found, but listed in compaction data
2023-06-07 21:55:52,582 - vorta.borg.borg_job - WARNING - segment 299 not found, but listed in compaction data
2023-06-07 21:55:52,591 - vorta.borg.borg_job - WARNING - segment 300 not found, but listed in compaction data
2023-06-07 21:55:52,597 - vorta.borg.borg_job - WARNING - segment 301 not found, but listed in compaction data
2023-06-07 21:55:52,603 - vorta.borg.borg_job - WARNING - segment 302 not found, but listed in compaction data
2023-06-07 21:55:52,609 - vorta.borg.borg_job - WARNING - segment 303 not found, but listed in compaction data
2023-06-07 21:55:52,615 - vorta.borg.borg_job - WARNING - segment 304 not found, but listed in compaction data
2023-06-07 21:55:52,621 - vorta.borg.borg_job - WARNING - segment 305 not found, but listed in compaction data
2023-06-07 21:55:52,627 - vorta.borg.borg_job - WARNING - segment 306 not found, but listed in compaction data
2023-06-07 21:55:52,633 - vorta.borg.borg_job - WARNING - segment 307 not found, but listed in compaction data
2023-06-07 21:55:52,639 - vorta.borg.borg_job - WARNING - segment 308 not found, but listed in compaction data
2023-06-07 21:55:52,645 - vorta.borg.borg_job - WARNING - segment 309 not found, but listed in compaction data
2023-06-07 21:55:52,651 - vorta.borg.borg_job - WARNING - segment 311 not found, but listed in compaction data
2023-06-07 21:55:52,656 - vorta.borg.borg_job - WARNING - segment 312 not found, but listed in compaction data
2023-06-07 21:55:52,661 - vorta.borg.borg_job - WARNING - segment 313 not found, but listed in compaction data
2023-06-07 21:55:52,666 - vorta.borg.borg_job - WARNING - segment 315 not found, but listed in compaction data
2023-06-07 21:55:52,671 - vorta.borg.borg_job - WARNING - segment 316 not found, but listed in compaction data
2023-06-07 21:55:52,677 - vorta.borg.borg_job - WARNING - segment 317 not found, but listed in compaction data
2023-06-07 21:55:52,682 - vorta.borg.borg_job - WARNING - segment 319 not found, but listed in compaction data
2023-06-07 21:55:52,690 - vorta.borg.borg_job - WARNING - segment 322 not found, but listed in compaction data
2023-06-07 21:55:52,695 - vorta.borg.borg_job - WARNING - segment 324 not found, but listed in compaction data
2023-06-07 21:55:52,956 - vorta.borg.borg_job - ERROR - Local Exception
2023-06-07 21:55:52,957 - vorta.borg.borg_job - ERROR - Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/borg/archiver.py", line 5213, in main
    exit_code = archiver.run(args)
                ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/borg/archiver.py", line 5144, in run
    return set_ec(func(args))
                  ^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/borg/archiver.py", line 183, in wrapper
    return method(self, args, repository=repository, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/borg/archiver.py", line 1855, in do_compact
    repository.commit(compact=True, threshold=threshold, cleanup_commits=args.cleanup_commits)
  File "/usr/lib/python3.11/site-packages/borg/repository.py", line 502, in commit
    self.compact_segments(threshold)
  File "/usr/lib/python3.11/site-packages/borg/repository.py", line 881, in compact_segments
    complete_xfer(intermediate=False)
  File "/usr/lib/python3.11/site-packages/borg/repository.py", line 758, in complete_xfer
    segment = self.io.write_commit(intermediate=intermediate)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/borg/repository.py", line 1658, in write_commit
    fd = self.get_write_fd(want_new=not intermediate, no_new=intermediate)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/borg/repository.py", line 1419, in get_write_fd
    self._write_fd = SyncFile(self.segment_filename(self.segment), binary=True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/borg/platform/base.py", line 162, in __init__
    self.f = open(path, mode=mode)  # python file object
             ^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 24] Too many open files: '/mnt/READYSHARE/Borg_Backup/data/0/325'

Platform: Linux PenazMW2 6.1.30-1-lts #1 SMP PREEMPT_DYNAMIC Mon, 29 May 2023 00:07:58 +0000 x86_64
Linux: Unknown Linux  
Borg: 1.2.4  Python: CPython 3.11.3 msgpack: 1.0.5 fuse: llfuse 1.4.2 [pyfuse3,llfuse]
PID: 13330  CWD: /home/penaz
sys.argv: ['/usr/bin/borg', '--info', '--log-json', 'compact', '--progress', 'file:///mnt/READYSHARE/Borg_Backup']
SSH_ORIGINAL_COMMAND: None

2023-06-07 21:55:53,155 - vorta.borg.jobs_manager - DEBUG - Finish job for site: 1
2023-06-07 21:55:53,157 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: 1
2023-06-07 21:55:53,159 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
```

**Comment by ThomasWaldmann** [comment]
I think you will need to **fix** this issue in the OS / filesystem you use.

borg using ~100 files should never cause an issue.

A **workaround** might be lowering the LRU cache size borg keeps of open files, e.g. from 100 to 20, see `repository.py`.
