### ISSUE TITLE
unexpected backslash(es) in path

### ISSUE THREAD

**Issue by phpcitizen** [borgbackup/borg#7692]
`/home/user/.local/bin/borg2 create --compression auto,lz4 --one-file-system --repo /mnt/external_disk/borg_backups/system {hostname}-system-{now:%Y-%m-%dT%H:%M:%S.%f} /boot /boot/efi /etc /opt /root /srv /usr/local/bin /usr/local/sbin /var --stats --progress`

**Got this error below with the command above:**

sys.argv: ['/home/user/.local/bin/borg2', 'create', '--compression', 'auto,lz4', '--one-file-system', '--repo', '/mnt/external_disk/borg_backups/system', '{hostname}-system-{now:%Y-%m-%dT%H:%M:%S.%f}', '/boot', '/boot/efi', '/etc', '/opt', '/root', '/srv', '/usr/local/bin', '/usr/local/sbin', '/var', '--stats', '--progress']

**ValueError: unexpected backslash(es) in path 'etc/systemd/system/dev-virtio\\\x2dports-org.qemu.guest_agent.0.device.wants'**

If reporting bugs, please include the following:

Traceback (most recent call last):
  File "borg/archiver/__init__.py", line 630, in main
  File "borg/archiver/__init__.py", line 536, in run
  File "borg/archiver/_common.py", line 157, in wrapper
  File "borg/archiver/create_cmd.py", line 282, in do_create
  File "borg/archiver/create_cmd.py", line 174, in create_inner
  File "borg/archiver/create_cmd.py", line 517, in _rec_walk
  File "borg/archiver/create_cmd.py", line 517, in _rec_walk
  File "borg/archiver/create_cmd.py", line 517, in _rec_walk
  File "borg/archiver/create_cmd.py", line 509, in _rec_walk
  File "borg/archive.py", line 1397, in process_dir_with_fd
  File "contextlib.py", line 137, in __enter__
  File "borg/archive.py", line 1375, in create_helper
  File "src/borg/item.pyx", line 158, in borg.item.PropDict.__cinit__
  File "src/borg/item.pyx", line 164, in borg.item.PropDict.update
  File "src/borg/item.pyx", line 232, in borg.item.PropDictProperty.__set__
  File "borg/helpers/fs.py", line 262, in assert_sanitized_path
  File "borg/helpers/fs.py", line 233, in make_path_safe
ValueError: unexpected backslash(es) in path 'etc/systemd/system/dev-virtio\\\x2dports-org.qemu.guest_agent.0.device.wants'

Platform: Linux asuspc 6.3.8-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jun 15 02:15:40 UTC 2023 x86_64
Linux: Unknown Linux
**Borg: 2.0.0b6**  Python: CPython 3.11.2 msgpack: 1.0.5 fuse: llfuse 1.4.4 [pyfuse3,llfuse]

**Comment by ThomasWaldmann** [comment]
Yeah, known and already fixed in master. Closing as a duplicate.
