### ISSUE TITLE
benchmark cpu bugreport

### ISSUE THREAD

**Issue by magf** [borgbackup/borg#7703]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug Report

## System information. For client/server mode post info for both machines.

Client

### Description

Benchmark fails at `msgpack` after Compression testing.

Full log follows.

#### Your borg version (borg -V).

Borg: 2.0.0b6

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

`borg benchmark cpu`

#### Output

```
Traceback (most recent call last):
  File "borg/archiver/__init__.py", line 630, in main
  File "borg/archiver/__init__.py", line 536, in run
  File "borg/archiver/benchmark_cmd.py", line 207, in do_benchmark_cpu
  File "src/borg/item.pyx", line 158, in borg.item.PropDict.__cinit__
  File "src/borg/item.pyx", line 164, in borg.item.PropDict.update
  File "src/borg/item.pyx", line 232, in borg.item.PropDictProperty.__set__
  File "borg/helpers/fs.py", line 263, in assert_sanitized_path
ValueError: path '/foo/bar/baz' is not sanitized

Platform: Linux magnet-notebook 5.4.0-153-generic #170-Ubuntu SMP Fri Jun 16 13:43:31 UTC 2023 x86_64
Linux: Unknown Linux  
Borg: 2.0.0b6  Python: CPython 3.11.2 msgpack: 1.0.5 fuse: llfuse 1.4.4 [pyfuse3,llfuse]
PID: 8736  CWD: /home/magnet
sys.argv: ['borg', 'benchmark', 'cpu']
SSH_ORIGINAL_COMMAND: None
```

#### Full output

```bash
~$ borg benchmark cpu
Chunkers =======================================================
buzhash,19,23,21,4095    1GB        1.008s
fixed,1048576            1GB        0.140s
Non-cryptographic checksums / hashes ===========================
xxh64                    1GB        0.105s
crc32 (zlib)             1GB        0.777s
Cryptographic hashes / MACs ====================================
hmac-sha256              1GB        0.561s
blake2b-256              1GB        1.476s
Encryption =====================================================
aes-256-ctr-hmac-sha256  1GB        1.075s
aes-256-ctr-blake2b      1GB        2.642s
aes-256-ocb              1GB        0.302s
chacha20-poly1305        1GB        1.025s
KDFs (slow is GOOD, use argon2!) ===============================
pbkdf2                   5          0.180s
argon2                   5          0.414s
Compression ====================================================
lz4          0.1GB      0.014s
zstd,1       0.1GB      0.067s
zstd,3       0.1GB      0.076s
zstd,5       0.1GB      0.639s
zstd,10      0.1GB      1.610s
zstd,16      0.1GB      13.570s
zstd,22      0.1GB      17.061s
zlib,0       0.1GB      0.067s
zlib,6       0.1GB      2.951s
zlib,9       0.1GB      3.001s
lzma,0       0.1GB      15.320s
lzma,6       0.1GB      38.707s
lzma,9       0.1GB      31.550s
msgpack ========================================================
Local Exception

Error:

ValueError: path '/foo/bar/baz' is not sanitized

If reporting bugs, please include the following:

Traceback (most recent call last):
  File "borg/archiver/__init__.py", line 630, in main
  File "borg/archiver/__init__.py", line 536, in run
  File "borg/archiver/benchmark_cmd.py", line 207, in do_benchmark_cpu
  File "src/borg/item.pyx", line 158, in borg.item.PropDict.__cinit__
  File "src/borg/item.pyx", line 164, in borg.item.PropDict.update
  File "src/borg/item.pyx", line 232, in borg.item.PropDictProperty.__set__
  File "borg/helpers/fs.py", line 263, in assert_sanitized_path
ValueError: path '/foo/bar/baz' is not sanitized

Platform: Linux magnet-notebook 5.4.0-153-generic #170-Ubuntu SMP Fri Jun 16 13:43:31 UTC 2023 x86_64
Linux: Unknown Linux  
Borg: 2.0.0b6  Python: CPython 3.11.2 msgpack: 1.0.5 fuse: llfuse 1.4.4 [pyfuse3,llfuse]
PID: 8736  CWD: /home/magnet
sys.argv: ['borg', 'benchmark', 'cpu']
SSH_ORIGINAL_COMMAND: None

```

**Comment by ThomasWaldmann** [comment]
Already fixed in master, will be in 2.0.0b7.
