### ISSUE TITLE
check --repair: Uncaught Exception on file i/o error

### ISSUE THREAD

**Issue by datamaan** [borgbackup/borg#772]
I set up my external HDD with my RaspberryPi and started a backup over ssh. Then I canceled the backup with `Ctrl+C`. Now the new chunks give me `cp: error reading ‘data/1/13472’: Input/output error` when trying to copy them.

The repository is unusable:
```
$ borg list .
Local Exception.
Traceback (most recent call last):
  File "borg/archiver.py", line 1466, in main
  File "borg/archiver.py", line 1420, in run
  File "borg/archiver.py", line 438, in do_list
  File "borg/helpers.py", line 93, in load
  File "borg/repository.py", line 416, in get
  File "borg/repository.py", line 121, in get_transaction_id
  File "borg/repository.py", line 513, in get_segments_transaction_id
  File "borg/repository.py", line 538, in is_committed_segment
OSError: [Errno 5] Input/output error

Platform: Linux suse 4.1.15-8-default #1 SMP PREEMPT Wed Jan 20 16:41:00 UTC 2016 (0e3b3ab) x86_64 x86_64
Linux: openSUSE  42.1 x86_64  LibC: glibc 2.3
Borg: 1.0.0  Python: CPython 3.5.1
PID: 2530  CWD: /run/media/dataman/dataman_ext/borgbackup_broken
sys.argv: ['borg', 'list', '.']
SSH_ORIGINAL_COMMAND: None
```

I tried to repair the repository with and got:
```
$ borg check --repair --verbose borgbackup_broken
'check --repair' is an experimental feature that might result in data loss.
Type 'YES' if you understand this and want to continue: YES
Starting repository check
Local Exception.
Traceback (most recent call last):
  File "borg/repository.py", line 336, in check
  File "borg/repository.py", line 121, in get_transaction_id
  File "borg/repository.py", line 513, in get_segments_transaction_id
  File "borg/repository.py", line 538, in is_committed_segment
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "borg/archiver.py", line 1466, in main
  File "borg/archiver.py", line 1420, in run
  File "borg/archiver.py", line 113, in do_check
  File "borg/repository.py", line 339, in check
  File "borg/repository.py", line 513, in get_segments_transaction_id
  File "borg/repository.py", line 538, in is_committed_segment
OSError: [Errno 5] Input/output error

Platform: Linux suse 4.1.15-8-default #1 SMP PREEMPT Wed Jan 20 16:41:00 UTC 2016 (0e3b3ab) x86_64 x86_64
Linux: openSUSE  42.1 x86_64  LibC: glibc 2.3
Borg: 1.0.0  Python: CPython 3.5.1
PID: 673  CWD: /run/media/dataman/dataman_ext
sys.argv: ['borg', 'check', '--repair', '--verbose', 'borgbackup_broken']
SSH_ORIGINAL_COMMAND: None
```

I think this Exception is something that should be caught, shouldn't it?

EDIT:
Since fsck found no errors, I solved my problem by deleting all unreadable files. This made the repair work and the only broken archive was the checkpoint of the cancelled `create`. But this issue is about the Exception being caught.

**Comment by ThomasWaldmann** [comment]
if reading a file with cp gives you an input/output error, that means that your storage media is defect (or filesystem is corrupted). That's not a borg issue.
