### ISSUE TITLE
borg.remote.InvalidRPCMethod: RPC method close is not valid

### ISSUE THREAD

**Issue by sayem314** [borgbackup/borg#7768]
```shell
root@borg-test:~# export BORG_REPO=ssh://...
root@borg-test:~# borg rcreate --encryption=repokey-blake2-aes-ocb
Exception ignored in: <function RemoteRepository.__del__ at 0x7f2ebfcb4360>
Traceback (most recent call last):
  File "borg/remote.py", line 631, in __del__
  File "borg/remote.py", line 986, in close
  File "borg/remote.py", line 720, in call
  File "borg/remote.py", line 790, in call_many
  File "borg/remote.py", line 768, in handle_error
borg.remote.InvalidRPCMethod: RPC method close is not valid
RPC method close is not valid
root@borg-test:~# borg --version
borg 2.0.0b6
```

**Comment by ThomasWaldmann** [comment]
@sayem314 hmm, do you have borg2 beta6 on both sides, client and server?

**Comment by sayem314** [comment]
> @sayem314 hmm, do you have borg2 beta6 on both sides, client and server?

Actually, that was indeed the issue. The server had b5. Now fixed after updating but still, it should work with minor version mismatch.

**Comment by ThomasWaldmann** [comment]
There is **no** compatibility assertion for betas.

**Comment by henfri** [comment]
Hello,

I have the same issue, however, I use the same version on client and server, however different glibc versions:
Source (where borg is invoked) wget https://github.com/borgbackup/borg/releases/download/2.0.0b17/borg-linux-glibc236
Target: wget https://github.com/borgbackup/borg/releases/download/2.0.0b17/borg-linux-glibc231

```
root@homeserveralt:~/.ssh#  /usr/local/bin/borg2 --version
borg2 2.0.0b17

root@homeserver:/etc/borgmatic# /usr/local/bin/borg2 --version
borg2 2.0.0b17

```

borg command and error:
```
/usr/local/bin/borg2 create  --exclude-caches --exclude-if-present .nobackup --compression zstd --one-file-system --remote-path /usr/local/bin/borg2 --umask 77 --repo ssh://borg@homeserveralt//srv/dev-disk-by-uuid-7da6ad7d-5a69-4a31-b652-f8de81c5d228/borg {hostname}-documents-{now} .
Exception ignored in: <function RemoteRepository.__del__ at 0x7fbcf8be9da0>
Traceback (most recent call last):
  File "borg/remote.py", line 637, in __del__
  File "borg/remote.py", line 999, in close
  File "borg/remote.py", line 720, in call
  File "borg/remote.py", line 819, in call_many
  File "borg/remote.py", line 780, in handle_error
borg.remote.InvalidRPCMethod: RPC method close is not valid
RPC method close is not valid

```

**Comment by sayem314** [comment]
It’s best to open new issue. Then you can reference this one in your new issue and then developers will be notified. @henfri
