### ISSUE TITLE
"Cache, or information obtained from the security directory is newer than repository" after temporary I/O error

### ISSUE THREAD

**Issue by mnalis** [borgbackup/borg#7853]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes, and FAQ does mention it, and https://github.com/borgbackup/borg/issues/3428 looks somewhat similar, but see below.

## Is this a BUG / ISSUE report or a QUESTION?

Maybe an ISSUE, or at least request for updated FAQ entry.

#### Your borg version (borg -V).

borg 1.2.4

#### Operating system (distribution) and version.
Debian Bookworm

#### Hardware / network configuration, and filesystems used.

One laptop machine with external HDD.
Source was MTP FUSE mounted android phone (via aft-mtp-mount, but probably not important). 
Destination is ext4 (external USB HDD partition)

#### How much data is handled by borg?

repository is about 850 GB (zstd compressed), the phone being backed up is about 130 GB of files.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

`sudo -- borg create --stats --progress --noflags --noacls --noxattrs --compression zstd --exclude-caches --exclude-from /tmp/rsync_android.exclude  /media/ladica/backup/borg::HuaweiP30-{now} ~mnalis/mnt/`

## Describe the problem you're observing.

At some point during creating backup the borg  failed, likely because the repository filesystem become read-only. Looking into dmesg revealed I/O error on external USB HDD; possibly/probably caused by slightly kinking the disk or USB cable due to operator slightly moving hardware while in operation (it is a laptop on top of a lap, so...) 
 
Unmounting the external disk seemed to succeed (at least the umount did not return error), and after disconnecting and reconnecting USB cable e2fsck did not force disk check as it appeared clean to it. However, trying to reinitiate borg backup failed with `Cache, or information obtained from the security directory is newer than repository - this is either an attack or unsafe (multiple repos with same ID)`. Any further attempt to backup to that repository failed.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

I haven't tried, as I'd like to avoid risking damage to hardware. I did look it up in [FAQ](https://borgbackup.readthedocs.io/en/stable/faq.html#this-is-either-an-attack-or-unsafe-warning), and the suggested ("unsupported") method there seems to solve the case (i.e. new backup is currently running seemingly fine; I'll try restoring some random things when it finishes). 

However, the explanations given in FAQ about "unsafe" and "attack" do not really match the problem that happened here, so maybe they should be updated to explain this use case, or perhaps even the borg might be modified (if possible) so such crashes due to temporary I/O errors do not leave backup repository in broken state?

#### Include any warning/errors/backtraces from the system logs

borg failed with this error after running for dozens of minutes:
```
% sudo -- borg create --stats --progress --noflags --noacls --noxattrs --compression zstd --exclude-caches --exclude-from /tmp/rsync_android.exclude  /media/ladica/backup/borg::HuaweiP30-{now} ~mnalis/mnt/
[sudo] password for mnalis:
Enter passphrase for key /media/ladica/backup/borg:
Exception ignored in: <function Repository.__del__ at 0x7f9a499594e0>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 189, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 478, in close
    self.lock.release()
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 417, in release
    self._roster.modify(EXCLUSIVE, REMOVE)
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 320, in modify
    self.save(roster)
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 291, in save
    with open(self.path, "w") as f:
         ^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/media/ladica/backup/borg/lock.roster'
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 183, in wrapper
    return method(self, args, repository=repository, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 675, in do_create
    create_inner(archive, cache, fso)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 629, in create_inner
    archive.save(comment=args.comment, timestamp=args.timestamp)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 662, in save
    self.manifest.write()
  File "/usr/lib/python3/dist-packages/borg/helpers/manifest.py", line 264, in write
    self.repository.put(self.MANIFEST_ID, self.key.encrypt(data))
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1229, in put
    self._delete(id, segment, offset, update_shadow_index=False)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1263, in _delete
    size = self.io.read(segment, offset, id, read_data=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1571, in read
    header = fd.read(self.put_header_fmt.size)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/platform/base.py", line 194, in close
    self.sync()
  File "/usr/lib/python3/dist-packages/borg/platform/base.py", line 183, in sync
    platform.fdatasync(self.fd)
OSError: [Errno 30] Read-only file system

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 5213, in main
    exit_code = archiver.run(args)
                ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 5144, in run
    return set_ec(func(args))
                  ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 168, in wrapper
    with repository:
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 214, in __exit__
    self.close()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 476, in close
    self.io.close()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1313, in close
    self.close_segment()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1468, in close_segment
    fd.close()
  File "/usr/lib/python3/dist-packages/borg/platform/base.py", line 198, in close
    platform.sync_dir(dirname)
  File "/usr/lib/python3/dist-packages/borg/platform/base.py", line 104, in sync_dir
    os.fsync(fd)
OSError: [Errno 30] Read-only file system

Platform: Linux leia 6.1.0-12-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.52-1 (2023-09-07) x86_64
Linux: Unknown Linux
Borg: 1.2.4  Python: CPython 3.11.2 msgpack: 1.0.3 fuse: llfuse 1.4.1 [pyfuse3,llfuse]
PID: 26981  CWD: /home/mnalis
sys.argv: ['/usr/bin/borg', 'create', '--stats', '--progress', '--noflags', '--noacls', '--noxattrs', '--compression', 'zstd', '--exclude-caches', '--exclude-from', '/tmp/rsync_android.exclude', '/media/ladica/backup/borg::HuaweiP30-{now}', '/home/mnalis/mnt/']
SSH_ORIGINAL_COMMAND: None
```

The cause seems to be I/O error, which propagated to ext4 remounting filesystem R/O to prevent further damage:

```
[349179.948272] sd 2:0:0:0: [sdb] tag#0 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_OK cmd_age=0s
[349179.948277] sd 2:0:0:0: [sdb] tag#0 Sense Key : Aborted Command [current]
[349179.948279] sd 2:0:0:0: [sdb] tag#0 Add. Sense: Information unit iuCRC error detected
[349179.948281] sd 2:0:0:0: [sdb] tag#0 CDB: Read(16) 88 00 00 00 00 00 cb 90 28 08 00 00 00 08 00 00
[349179.948282] I/O error, dev sdb, sector 3415222280 op 0x0:(READ) flags 0x80700 phys_seg 1 prio class 2
[350635.125747] INFO: task jbd2/sdb2-8:20212 blocked for more than 120 seconds.
[350635.125752]       Not tainted 6.1.0-12-amd64 #1 Debian 6.1.52-1
[350635.125754] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[350635.125755] task:jbd2/sdb2-8     state:D stack:0     pid:20212 ppid:2      flags:0x00004000
[350635.125758] Call Trace:
[350635.125759]  <TASK>
[350635.125762]  __schedule+0x351/0xa20
[350635.125768]  schedule+0x5d/0xe0
[350635.125770]  io_schedule+0x42/0x70
[350635.125772]  bit_wait_io+0xd/0x60
[350635.125774]  __wait_on_bit+0x48/0x140
[350635.125777]  ? bit_wait+0x60/0x60
[350635.125779]  out_of_line_wait_on_bit+0x91/0xb0
[350635.125782]  ? sugov_init+0x350/0x350
[350635.125786]  jbd2_journal_commit_transaction+0x11b2/0x1a70 [jbd2]
[350635.125795]  ? _raw_spin_unlock+0x15/0x30
[350635.125798]  ? finish_task_switch.isra.0+0x9b/0x300
[350635.125801]  ? __switch_to+0x106/0x410
[350635.125804]  kjournald2+0xa9/0x280 [jbd2]
[350635.125811]  ? cpuusage_read+0x10/0x10
[350635.125813]  ? jbd2_fc_wait_bufs+0xa0/0xa0 [jbd2]
[350635.125819]  kthread+0xe6/0x110
[350635.125835]  ? kthread_complete_and_exit+0x20/0x20
[350635.125837]  ret_from_fork+0x1f/0x30
[350635.125841]  </TASK>
[350639.006381] sd 2:0:0:0: [sdb] tag#0 timing out command, waited 180s
[350639.006391] sd 2:0:0:0: [sdb] tag#0 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_OK cmd_age=180s
[350639.006394] sd 2:0:0:0: [sdb] tag#0 Sense Key : Hardware Error [current]
[350639.006396] sd 2:0:0:0: [sdb] tag#0 ASC=0x44 <<vendor>>ASCQ=0x81
[350639.006398] sd 2:0:0:0: [sdb] tag#0 CDB: Write(16) 8a 00 00 00 00 00 ef 04 2e e0 00 00 00 10 00 00
[350639.006400] I/O error, dev sdb, sector 4010028768 op 0x1:(WRITE) flags 0x800 phys_seg 2 prio class 2
[350639.006425] Aborting journal on device sdb2-8.
[350644.085586] EXT4-fs error (device sdb2): ext4_journal_check_start:83: comm kworker/u16:1: Detected aborted journal
[350819.023201] sd 2:0:0:0: [sdb] tag#0 timing out command, waited 180s
[350819.023209] sd 2:0:0:0: [sdb] tag#0 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_OK cmd_age=180s
[350819.023211] sd 2:0:0:0: [sdb] tag#0 Sense Key : Hardware Error [current]
[350819.023213] sd 2:0:0:0: [sdb] tag#0 ASC=0x44 <<vendor>>ASCQ=0x81
[350819.023214] sd 2:0:0:0: [sdb] tag#0 CDB: Write(16) 8a 00 00 00 00 00 ef 04 08 00 00 00 00 08 00 00
[350819.023215] I/O error, dev sdb, sector 4010018816 op 0x1:(WRITE) flags 0x800 phys_seg 1 prio class 2
[350819.023218] Buffer I/O error on dev sdb2, logical block 475037696, lost sync page write
[350819.023235] JBD2: I/O error when updating journal superblock for sdb2-8.
[350926.584489] EXT4-fs error (device sdb2): ext4_journal_check_start:83: comm borg: Detected aborted journal
[350997.628268] INFO: task kworker/u16:1:23937 blocked for more than 120 seconds.
[350997.628279]       Not tainted 6.1.0-12-amd64 #1 Debian 6.1.52-1
[350997.628283] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[350997.628286] task:kworker/u16:1   state:D stack:0     pid:23937 ppid:2      flags:0x00004000
[350997.628295] Workqueue: writeback wb_workfn (flush-8:16)
[350997.628307] Call Trace:
[350997.628310]  <TASK>
[350997.628315]  __schedule+0x351/0xa20
[350997.628327]  schedule+0x5d/0xe0
[350997.628334]  io_schedule+0x42/0x70
[350997.628341]  bit_wait_io+0xd/0x60
[350997.628348]  __wait_on_bit+0x48/0x140
[350997.628354]  ? bit_wait+0x60/0x60
[350997.628364]  out_of_line_wait_on_bit+0x91/0xb0
[350997.628371]  ? sugov_init+0x350/0x350
[350997.628378]  ext4_commit_super+0xf5/0x140 [ext4]
[350997.628450]  ext4_handle_error+0x1e6/0x200 [ext4]
[350997.628505]  __ext4_error+0x125/0x1b0 [ext4]
[350997.628557]  ext4_journal_check_start+0x82/0x90 [ext4]
[350997.628597]  __ext4_journal_start_sb+0x2f/0x120 [ext4]
[350997.628637]  ext4_writepages+0x514/0x1120 [ext4]
[350997.628686]  ? ext4_inode_csum+0x20b/0x290 [ext4]
[350997.628732]  ? select_task_rq_fair+0x180/0x1730
[350997.628742]  do_writepages+0xbd/0x1c0
[350997.628748]  ? sched_clock_cpu+0xb/0xc0
[350997.628754]  __writeback_single_inode+0x3d/0x360
[350997.628760]  writeback_sb_inodes+0x1ed/0x4a0
[350997.628767]  __writeback_inodes_wb+0x4c/0xf0
[350997.628772]  wb_writeback+0x204/0x2f0
[350997.628778]  wb_workfn+0x318/0x4f0
[350997.628784]  process_one_work+0x1c4/0x380
[350997.628793]  worker_thread+0x4d/0x380
[350997.628801]  ? rescuer_thread+0x3a0/0x3a0
[350997.628807]  kthread+0xe6/0x110
[350997.628813]  ? kthread_complete_and_exit+0x20/0x20
[350997.628819]  ret_from_fork+0x1f/0x30
[350997.628830]  </TASK>
[350999.029438] sd 2:0:0:0: [sdb] tag#0 timing out command, waited 180s
[350999.029452] sd 2:0:0:0: [sdb] tag#0 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_OK cmd_age=180s
[350999.029457] sd 2:0:0:0: [sdb] tag#0 Sense Key : Hardware Error [current]
[350999.029462] sd 2:0:0:0: [sdb] tag#0 ASC=0x44 <<vendor>>ASCQ=0x81
[350999.029466] sd 2:0:0:0: [sdb] tag#0 CDB: Write(16) 8a 00 00 00 00 00 0c 80 08 00 00 00 00 08 00 00
[350999.029468] I/O error, dev sdb, sector 209717248 op 0x1:(WRITE) flags 0x3800 phys_seg 1 prio class 2
[350999.029476] Buffer I/O error on dev sdb2, logical block 0, lost sync page write
[350999.029502] EXT4-fs (sdb2): I/O error while writing superblock
[350999.029518] EXT4-fs (sdb2): Remounting filesystem read-only
[350999.029522] EXT4-fs (sdb2): ext4_writepages: jbd2_start: 1024 pages, ino 100141494; err -30
[351179.033798] sd 2:0:0:0: [sdb] tag#0 timing out command, waited 180s
[351179.033815] sd 2:0:0:0: [sdb] tag#0 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_OK cmd_age=180s
[351179.033820] sd 2:0:0:0: [sdb] tag#0 Sense Key : Hardware Error [current]
[351179.033826] sd 2:0:0:0: [sdb] tag#0 ASC=0x44 <<vendor>>ASCQ=0x81
[351179.033830] sd 2:0:0:0: [sdb] tag#0 CDB: Write(16) 8a 00 00 00 00 00 0c 80 08 00 00 00 00 08 00 00
[351179.033834] I/O error, dev sdb, sector 209717248 op 0x1:(WRITE) flags 0x3800 phys_seg 1 prio class 2
[351179.033843] Buffer I/O error on dev sdb2, logical block 0, lost sync page write
[351179.033948] EXT4-fs (sdb2): I/O error while writing superblock
[351359.071622] sd 2:0:0:0: [sdb] tag#0 timing out command, waited 180s
[351359.071639] sd 2:0:0:0: [sdb] tag#0 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_OK cmd_age=180s
[351359.071644] sd 2:0:0:0: [sdb] tag#0 Sense Key : Hardware Error [current]
[351359.071650] sd 2:0:0:0: [sdb] tag#0 ASC=0x44 <<vendor>>ASCQ=0x81
[351359.071655] sd 2:0:0:0: [sdb] tag#0 CDB: Read(16) 88 00 00 00 00 00 cb 90 28 30 00 00 00 10 00 00
[351359.071659] I/O error, dev sdb, sector 3415222320 op 0x0:(READ) flags 0x80700 phys_seg 1 prio class 2
[351539.088452] sd 2:0:0:0: [sdb] tag#0 timing out command, waited 180s
[351539.088468] sd 2:0:0:0: [sdb] tag#0 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_OK cmd_age=180s
[351539.088473] sd 2:0:0:0: [sdb] tag#0 Sense Key : Hardware Error [current]
[351539.088478] sd 2:0:0:0: [sdb] tag#0 ASC=0x44 <<vendor>>ASCQ=0x81
[351539.088483] sd 2:0:0:0: [sdb] tag#0 CDB: Read(16) 88 00 00 00 00 00 cb 90 28 30 00 00 00 08 00 00
[351539.088486] I/O error, dev sdb, sector 3415222320 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 2
[351546.964401] kauditd_printk_skb: 56 callbacks suppressed

```

I've unmounted `/media/ladica` then, disconnect and reconnect the cable and e2fsck / mount again, but running `borg create` failed with the error from this issue title. Trying it again just failed again, of course:

```
% sudo umount /media/ladica
% mnalis@leia> sudo e2fsck -r -C0 /dev/sdb2
e2fsck 1.47.0 (5-Feb-2023)
ts_ladica34: clean, 2489/237633536 files, 239596295/950531579 blocks
% mount /media/ladica
%  sudo -- borg create --stats --progress --noflags --noacls --noxattrs --compression zstd --exclude-caches --exclude-from /tmp/rsync_android.exclude  /media/ladica/backup/borg::HuaweiP30-{now} ~mnalis/mnt/
Enter passphrase for key /media/ladica/backup/borg:
Cache, or information obtained from the security directory is newer than repository - this is either an attack or unsafe (multiple repos with same ID)
```

**Comment by ThomasWaldmann** [comment]
Yeah, looks like a crash can also get one into that state, not just unsafe operations or attacks.

**Comment by akostadinov** [comment]
How do I recover from such condition? Using borg 1.2.8

**Comment by ThomasWaldmann** [comment]
Did you try that?:

https://borgbackup.readthedocs.io/en/1.2.8/faq.html#this-is-either-an-attack-or-unsafe-warning
