### ISSUE TITLE
borg init shows traceback when repository already exists

### ISSUE THREAD

**Issue by avacariu** [borgbackup/borg#792]
```
Remote: Borg 1.0.0: exception in RPC call:
Remote: Traceback (most recent call last):
Remote:   File "/usr/lib/python3/dist-packages/borg/remote.py", line 94, in serve
Remote:     res = f(*args)
Remote:   File "/usr/lib/python3/dist-packages/borg/remote.py", line 119, in open
Remote:     self.repository = Repository(path, create, lock_wait=lock_wait, lock=lock)
Remote:   File "/usr/lib/python3/dist-packages/borg/repository.py", line 63, in __init__
Remote:     self.create(self.path)
Remote:   File "/usr/lib/python3/dist-packages/borg/repository.py", line 76, in create
Remote:     raise self.AlreadyExists(path)
Remote: borg.repository.AlreadyExists: /repository
Remote: Platform: Linux computer 4.2.0-34-generic #39~14.04.1-Ubuntu SMP Fri Mar 11 11:38:02 UTC 2016 x86_64 x86_64
Remote: Linux: Ubuntu 14.04 trusty  LibC: glibc 2.9
Remote: Borg: 1.0.0  Python: CPython 3.4.3
Remote: PID: 5778  CWD: /home/username
Remote: sys.argv: ['/usr/bin/borg', 'serve', '--umask=077']
Remote: SSH_ORIGINAL_COMMAND: None
Remote: 
Repository computer:/repository already exists.
```

The error message is at the end, but for some reason the traceback is shown too.

**Comment by enkore** [comment]
Fixed in 1.0-maint; scheduled for 1.0.1. Will be merged back into master
