### ISSUE TITLE
UnicodeDecodeError in get_free_nonce

### ISSUE THREAD

**Issue by NDahlem** [borgbackup/borg#7933]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).
borg 1.1.15

#### Operating system (distribution) and version.
cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

#### Hardware / network configuration, and filesystems used.
Local backup from zfs to usb-disk with ext4

#### How much data is handled by borg?
In this repo:
```
                       Original size      Compressed size    Deduplicated size
All archives:                1.16 TB              1.12 TB             74.68 GB

                       Unique chunks         Total chunks
Chunk index:                   59792              1058932
```

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
/usr/local/bin/borg check --verify-data --progress /backup_path/home

## Describe the problem you're observing.
My daily backup reported an error:

```
/usr/local/bin/borg create -s /backup_path/home::{now:%Y-%m-%d_%H:%M:%S} /data_path/home
------------------------------------------------------------------------------
Archive name: 2023-11-10_02:00:16
Archive fingerprint: 146bd8b31a5d1e71c49a1b88cf18f348683a56034d1a16197ad5ef8cf5fc5f69
Time (start): Fri, 2023-11-10 02:00:17
Time (end):   Fri, 2023-11-10 02:01:14
Duration: 57.49 seconds
Number of files: 28256
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               73.22 GB             68.45 GB              1.34 GB
All archives:                1.16 TB              1.12 TB             74.68 GB

                       Unique chunks         Total chunks
Chunk index:                   59792              1058932
------------------------------------------------------------------------------
Exception ignored in: <function Repository.__del__ at 0x7f902b563290>
Traceback (most recent call last):
  File "borg/repository.py", line 179, in __del__
  File "borg/repository.py", line 460, in close
  File "borg/locking.py", line 383, in release
  File "borg/locking.py", line 282, in modify
KeyError: (('host.domain@158445873807042', 457626, 0),)
Local Exception
Traceback (most recent call last):
  File "borg/archiver.py", line 4621, in main
  File "borg/archiver.py", line 4553, in run
  File "borg/archiver.py", line 177, in wrapper
  File "borg/repository.py", line 204, in __exit__
  File "borg/repository.py", line 460, in close
  File "borg/locking.py", line 383, in release
  File "borg/locking.py", line 282, in modify
KeyError: ('host.domain@158445873807042', 457626, 0)

Platform: Linux host 6.2.16-4-pve #1 SMP PREEMPT_DYNAMIC PVE 6.2.16-4 (2023-07-07T04:22Z) x86_64
Linux: debian 12.2
Borg: 1.1.15  Python: CPython 3.7.9 msgpack: 0.5.6
PID: 457626  CWD: /root
sys.argv: ['/usr/local/bin/borg', 'create', '-s', '/backup_path/home::{now:%Y-%m-%d_%H:%M:%S}', '/data_path/home']
SSH_ORIGINAL_COMMAND: None
```

I assume this was du to some kind of HW glitch. I tried to repair the repo with check --repair.
Now check --verify-data outputs:

```
/usr/local/bin/borg check --verify-data --progress /backup_path/home
Local Exception                                                                                                                                                                    
Traceback (most recent call last):
  File "borg/archiver.py", line 4621, in main
  File "borg/archiver.py", line 4553, in run
  File "borg/archiver.py", line 177, in wrapper
  File "borg/archiver.py", line 348, in do_check
  File "borg/archive.py", line 1244, in check
  File "borg/archive.py", line 1634, in rebuild_refcounts
  File "borg/archive.py", line 268, in add
  File "borg/archive.py", line 285, in flush
  File "borg/archive.py", line 1435, in add_callback
  File "borg/crypto/key.py", line 370, in encrypt
  File "borg/crypto/nonces.py", line 72, in ensure_reservation
  File "borg/crypto/nonces.py", line 39, in get_repo_free_nonce
  File "borg/repository.py", line 341, in get_free_nonce
  File "/home/vagrant/.pyenv/versions/3.7.9/lib/python3.7/codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 9: invalid continuation byte

Platform: Linux host 6.2.16-4-pve #1 SMP PREEMPT_DYNAMIC PVE 6.2.16-4 (2023-07-07T04:22Z) x86_64
Linux: debian 12.2 
Borg: 1.1.15  Python: CPython 3.7.9 msgpack: 0.5.6
PID: 1194887  CWD: /root/
sys.argv: ['/usr/local/bin/borg', 'check', '--verify-data', '--progress', '/backup_path/home']
SSH_ORIGINAL_COMMAND: None
```

Similar output when it try to create or prune backups. Is there any way to fix this?

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
/usr/local/bin/borg check --verify-data --progress /backup_path/home

**Comment by ThomasWaldmann** [comment]
borg 1.1.15 is rather old and debian bookworm has 1.2.4, so you could just try that more recent version.

you seem to have 2 issues there:
- once related to locking
- another related to the `nonce` file's content being garbage (check `REPO/nonce` files, that should be just a text file with a hex number)

**Comment by NDahlem** [comment]
nonce file is 502 MB that doesn't look right:
```
head nonce
BORG_SEGk� �Qw(�kq�v�\Q���ǂA߲'p(z�
```

I see no stale lock files.

I tried using the latest version. There seems to be no difference:
```
/usr/local/bin/borg-new --version
borg-new 1.2.6

/usr/local/bin/borg-new check --repair -v /backup_path/home/
This is a potentially dangerous function.
check --repair might lead to data loss (for kinds of corruption it is not
capable of dealing with). BE VERY CAREFUL!

Type 'YES' if you understand this and want to continue: YES
Starting repository check
finished segment check at segment 7141
Starting repository index check
Finished full repository check, no problems found.
Starting archive consistency check...
Analyzing archive 2022-11-30_02:00:11 (1/24)
Local Exception
Traceback (most recent call last):
  File "borg/archiver.py", line 5324, in main
  File "borg/archiver.py", line 5255, in run
  File "borg/archiver.py", line 183, in wrapper
  File "borg/archiver.py", line 347, in do_check
  File "borg/archive.py", line 1651, in check
  File "borg/archive.py", line 2086, in rebuild_refcounts
  File "borg/archive.py", line 358, in add
  File "borg/archive.py", line 386, in flush
  File "borg/archive.py", line 1863, in add_callback
  File "borg/crypto/key.py", line 442, in encrypt
  File "borg/crypto/nonces.py", line 79, in ensure_reservation
  File "borg/crypto/nonces.py", line 38, in get_repo_free_nonce
  File "borg/repository.py", line 352, in get_free_nonce
  File "codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 9: invalid continuation byte

Platform: Linux host 6.2.16-4-pve #1 SMP PREEMPT_DYNAMIC PVE 6.2.16-4 (2023-07-07T04:22Z) x86_64
Linux: Unknown Linux  
Borg: 1.2.6  Python: CPython 3.9.18 msgpack: 1.0.5 fuse: llfuse 1.5.0 [pyfuse3,llfuse]
PID: 2249032  CWD: /root
sys.argv: ['/usr/local/bin/borg-new', 'check', '--repair', '-v', '/backup_path/home/']
SSH_ORIGINAL_COMMAND: None
```

Is there a way to reset/restore the nonce?

**Comment by ThomasWaldmann** [comment]
BORG_SEG is the magic used for borg segment files (not for the nonce file).

So it seems your filesystem is confused, guess you need a `fsck`.

**Comment by NDahlem** [comment]
I completely forgot about a fsck first. Sorry to bother you with this.
After fsck the nonce file was gone and check reported 5 missing chunks that it zeroed out. Now everything looks good (backup-wise, need to investigate the filesystem and harddisk)

Maybe it would be helpfull to add a check for a healthy nonce file.

**Comment by ThomasWaldmann** [comment]
It might be possible to repair the all-zero replacement chunks - **if** they get re-created by your backups:
- run all your usual backups
- run `borg check --repair` again

**Comment by NDahlem** [comment]
All-zero chunks repaired. Thank you very much.
