### ISSUE TITLE
repository list 'command_line' fails,  1.1.16

### ISSUE THREAD

**Issue by Blobbel** [borgbackup/borg#8007]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug / question

#### Your borg version (borg -V).

borg 1.1.16

#### Operating system (distribution) and version.

Raspbian GNU/Linux 11 (bullseye), both client and server. 
Client uname -m: armv7l
Server uname -m: aarch64

#### Hardware / network configuration, and filesystems used.

ext4 on both client and server. 

#### How much data is handled by borg?

The repository in question is 316 GB in size

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
borg --debug list --format '{archive}{TAB}{time}{TAB}{id}{TAB}{command_line}{NL}' borg@192.168.x.xx:/mnt/usb1/borg/pers_cr
```

## Describe the problem you're observing.

I get an error message if I try to specify 'command_line' in a listing of archives (see below). Curiously, if I try the same operation with a newer version of borg locally on the server (borg-1.2.7-arm64) it works. I'm a bit scared to add information using this setup until I understand what is going on. I am not so experienced, sorry if this is a newbie question!

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes

#### Include any warning/errors/backtraces from the system logs

```
client [~] > borg info borg@192.168.8.36:/mnt/usb1/borg/pers_cr
Enter passphrase for key ssh://borg@192.168.8.36/mnt/usb1/borg/pers_cr: 
Repository ID: a0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Location: ssh://borg@192.168.8.36/mnt/usb1/borg/pers_cr
Encrypted: Yes (repokey BLAKE2b)
Cache: /home/pi/.cache/borg/a0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Security dir: /home/pi/.config/borg/security/a0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
All archives:              875.32 GB            718.36 GB            338.34 GB

                       Unique chunks         Total chunks
Chunk index:                  153059               340438
client [~] > borg list --format '{archive}{TAB}{time}{TAB}{id}{NL}' borg@192.168.x.xx:/mnt/usb1/borg/pers_cr
Enter passphrase for key ssh://borg@192.168.8.36/mnt/usb1/borg/pers_cr: 
202202.1        Fri, 2022-02-11 18:37:03        21xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
202202.5        Tue, 2022-02-15 01:32:16        f2xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
202202.6        Wed, 2022-02-16 21:59:37        b6xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
202202.WD4TB_bu Sat, 2022-03-19 00:33:39        28xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
client [~] > borg --debug list --format '{archive}{TAB}{time}{TAB}{id}{TAB}{command_line}{NL}' borg@192.168.x.xx:/mnt/usb1/borg/pers_cr
using builtin fallback logging configuration
35 self tests completed in 0.45 seconds
SSH command line: ['ssh', 'borg@192.168.x.xx', 'borg', 'serve', '--umask=077', '--debug']
Remote: using builtin fallback logging configuration
Remote: 35 self tests completed in 0.31 seconds
Remote: using builtin fallback logging configuration
Remote: Initialized logging system for JSON-based protocol
Remote: Resolving repository path b'/mnt/usb1/borg/pers_cr'
Remote: Resolved repository path to '/mnt/usb1/borg/pers_cr'
Remote: Verified integrity of /mnt/usb1/borg/pers_cr/index.731
Enter passphrase for key ssh://borg@192.168.x.xx/mnt/usb1/borg/pers_cr: 
TAM-verified manifest
security: read previous location 'ssh://borg@192.168.x.xx/mnt/usb1/borg/pers_cr'
security: read manifest timestamp '2022-03-18T23:51:31.227824'
security: determined newest manifest timestamp as 2022-03-18T23:51:31.227824
security: repository checks ok, allowing access
RemoteRepository: 267 B bytes sent, 4.03 kB bytes received, 7 messages sent
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4690, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4622, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 177, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1461, in do_list
    return self._list_repository(args, repository, manifest, key)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1504, in _list_repository
    sys.stdout.write(formatter.format_item(archive_info))
  File "/usr/lib/python3/dist-packages/borg/helpers.py", line 1749, in format_item
    return self.format.format_map(self.get_item_data(item))
KeyError: 'command_line'

Platform: Linux rpi8 5.10.92-v7l+ #1514 SMP Mon Jan 17 17:38:03 GMT 2022 armv7l
Linux: Unknown Linux  
Borg: 1.1.16  Python: CPython 3.9.2 msgpack: 0.5.6.+borg1
PID: 24215  CWD: /home/pi
sys.argv: ['/usr/bin/borg', '--debug', 'list', '--format', '{archive}{TAB}{time}{TAB}{id}{TAB}{command_line}{NL}', 'borg@192.168.x.xx:/mnt/usb1/borg/pers_cr']
SSH_ORIGINAL_COMMAND: None
rpi8 [~] > borg --debug check --repository-only borg@192.168.x.xx:/mnt/usb1/borg/pers_cr
using builtin fallback logging configuration
35 self tests completed in 0.45 seconds
SSH command line: ['ssh', 'borg@192.168.8.36', 'borg', 'serve', '--umask=077', '--debug']
Remote: using builtin fallback logging configuration
Remote: 35 self tests completed in 0.27 seconds
Remote: using builtin fallback logging configuration
Remote: Initialized logging system for JSON-based protocol
Remote: Resolving repository path b'/mnt/usb1/borg/pers_cr'
Remote: Resolved repository path to '/mnt/usb1/borg/pers_cr'
Remote: Starting repository check
Remote: Verified integrity of /mnt/usb1/borg/pers_cr/index.731
Remote: Read committed index of transaction 731
Remote: Segment transaction is    731
Remote: Determined transaction is 731
Remote: Found 706 segments
Remote: checking segment file /mnt/usb1/borg/pers_cr/data/0/1...
[..........................]
Remote: checking segment file /mnt/usb1/borg/pers_cr/data/0/727...
Remote: checking segment file /mnt/usb1/borg/pers_cr/data/0/729...
Remote: checking segment file /mnt/usb1/borg/pers_cr/data/0/730...
Remote: checking segment file /mnt/usb1/borg/pers_cr/data/0/731...
Remote: Starting repository index check
Remote: Index object count match.
Remote: Completed repository check, no problems found.
RemoteRepository: 179 B bytes sent, 267.81 kB bytes received, 3 messages sent
client [~] > 

```

**Comment by ThomasWaldmann** [comment]
Well, if you say it works with a newer borg version, but not with that `1.1.16`, maybe it was added after `1.1.16`. You could check if there is something in the changelog.

**Comment by Blobbel** [comment]
Aha. I am an idiot... sorry. It seems it was added as a format key in "version 1.2.0b4 (2022-01-23)"; 

New features -> list --format: Add command_line to format keys

https://github.com/borgbackup/borg/blob/1432f547fe4fe13386b245dcc0d9c2a0880ddfe6/docs/changes_1.x.rst

I knew I had seen the command line info before, and that it was somehow stored already by 1.1.16 -- but I had only seen it in the output of 'borg info'. Closing with "error PEBKAC", thank you, sorry, good night
