### ISSUE TITLE
Exception: Could not find xxhash lib/headers, please set BORG_LIBXXHASH_PREFIX or ensure libxxhash.pc is in PKG_CONFIG_PATH.

### ISSUE THREAD

**Issue by lamyergeier** [borgbackup/borg#8037]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue

#### Your borg version (borg -V). 

Unable to install

#### Operating system (distribution) and version. 

Fedora 39
 
#### Hardware / network configuration, and filesystems used.

Ext4

# Issue

Any suggestions please? 

```
$ pip --version
pip 23.3.2 from /mnt/Data/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/pip (python 3.11)

$ pipx --version
1.3.3

$ pip install xxhash
Requirement already satisfied: xxhash in /home/lamy/.local/lib/python3.11/site-packages (3.4.1)

$ sudo dnf install xxhash
Place your right ring finger on the fingerprint reader
Last metadata expiration check: 0:18:38 ago on Mon 08 Jan 2024 21:12:40 CET.
Dependencies resolved.
=============================================================================================================
 Package                 Architecture            Version                       Repository               Size
=============================================================================================================
Installing:
 xxhash                  x86_64                  0.8.2-1.fc39                  fedora                   56 k

Transaction Summary
=============================================================================================================
Install  1 Package

Total download size: 56 k
Installed size: 117 k
Is this ok [y/N]: y
Downloading Packages:
xxhash-0.8.2-1.fc39.x86_64.rpm                                               322 kB/s |  56 kB     00:00    
-------------------------------------------------------------------------------------------------------------
Total                                                                        204 kB/s |  56 kB     00:00     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                     1/1 
  Installing       : xxhash-0.8.2-1.fc39.x86_64                                                          1/1 
  Running scriptlet: xxhash-0.8.2-1.fc39.x86_64                                                          1/1 
  Verifying        : xxhash-0.8.2-1.fc39.x86_64                                                          1/1 

Installed:
  xxhash-0.8.2-1.fc39.x86_64                                                                                 

Complete!
```

```
$ pipx install "borgbackup==2.0.0b7"
Fatal error from pip prevented installation. Full pip output in file:
    /mnt/Data/.local/pipx/logs/cmd_2024-01-08_21.11.20_pip_errors.log

pip seemed to fail to build package:
    borgbackup==2.0.0b7

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    Exception: Could not find xxhash lib/headers, please set BORG_LIBXXHASH_PREFIX or ensure libxxhash.pc is in PKG_CONFIG_PATH.

Error installing borgbackup from spec 'borgbackup==2.0.0b7'.
```

```
cat /mnt/Data/.local/pipx/logs/cmd_2024-01-08_21.11.20_pip_errors.log

PIP STDOUT
----------
Collecting borgbackup==2.0.0b7
  Downloading borgbackup-2.0.0b7.tar.gz (3.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 3.4 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

PIP STDERR
----------
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Detected and preferring libcrypto [via pkg-config]
      Detected and preferring liblz4 [via pkg-config]
      Detected and preferring libzstd [via pkg-config]
      Traceback (most recent call last):
        File "/mnt/Data/.local/pipx/shared/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/mnt/Data/.local/pipx/shared/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/mnt/Data/.local/pipx/shared/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-r1glzvyp/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-r1glzvyp/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-r1glzvyp/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 185, in <module>
        File "<string>", line 152, in lib_ext_kwargs
      Exception: Could not find xxhash lib/headers, please set BORG_LIBXXHASH_PREFIX or ensure libxxhash.pc is in PKG_CONFIG_PATH.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

# Installing using pip

```
$ type pip
pip is a function
pip () 
{ 
    if [[ "${1}" == "install" ]]; then
        command pip install --user "${@:2}";
    else
        command pip "$@";
    fi
}
pip is /home/linuxbrew/.linuxbrew/bin/pip
pip is /usr/bin/pip
$ /home/linuxbrew/.linuxbrew/bin/pip install "borgbackup==2.0.0b7"
Collecting borgbackup==2.0.0b7
  Using cached borgbackup-2.0.0b7.tar.gz (3.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Detected and preferring libcrypto [via pkg-config]
      Detected and preferring liblz4 [via pkg-config]
      Detected and preferring libzstd [via pkg-config]
      Traceback (most recent call last):
        File "/mnt/Data/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/mnt/Data/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/mnt/Data/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-n3aakhqm/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-n3aakhqm/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-n3aakhqm/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 185, in <module>
        File "<string>", line 152, in lib_ext_kwargs
      Exception: Could not find xxhash lib/headers, please set BORG_LIBXXHASH_PREFIX or ensure libxxhash.pc is in PKG_CONFIG_PATH.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

- Installing using another pip installation

```
$ /usr/bin/pip install "borgbackup==2.0.0b7"
Defaulting to user installation because normal site-packages is not writeable
Collecting borgbackup==2.0.0b7
  Downloading borgbackup-2.0.0b7.tar.gz (3.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 8.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Detected and preferring libcrypto [via pkg-config]
      Detected and preferring liblz4 [via pkg-config]
      Detected and preferring libzstd [via pkg-config]
      Traceback (most recent call last):
        File "/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-nwakw4bs/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-nwakw4bs/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-nwakw4bs/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 185, in <module>
        File "<string>", line 152, in lib_ext_kwargs
      Exception: Could not find xxhash lib/headers, please set BORG_LIBXXHASH_PREFIX or ensure libxxhash.pc is in PKG_CONFIG_PATH.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by ThomasWaldmann** [comment]
As you maybe have found out, you need to follow the install docs and install all the crypto, compression, etc. libraries and header files borg needs, e.g. via rpm or apt.
