### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by warlordattack** [borgbackup/borg#8206]
Hello i recently installed Nextcloud AIO on a Ubuntu VM in Proxmox, i used recommended AIO install of Nextcloud 28.
I have borg backup fail error 104.

The backup dir is : /mnt/x/px-nextcloud
It goes to a disk shared by Windows, my fstab : 
```
doge@d0ge:~$ cat /etc/fstab
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
# / was on /dev/ubuntu-vg/ubuntu-lv during curtin installation
/dev/disk/by-id/dm-uuid-LVM-aJiTfS5e2SYIvEVHigwaR1T9IMH98ShnfkRWwCfOBscslpkZOYAzSxaic0c6bde1 / ext4 defaults 0 1
# /boot was on /dev/sda2 during curtin installation
/dev/disk/by-uuid/47b22e65-6a6b-4a2c-ae4b-98bcbd335b6d /boot ext4 defaults 0 1
/swap.img       none    swap    sw      0       0

//192.168.50.114/x      /mnt/x  cifs    credentials=/mnt/ant.smbcred,uid=1000,gid=1000,rw,mfsymlinks,seal,iocharset=utf8,file_mode=0777,dir_mode=0777       0       0
//192.168.50.114/y      /mnt/y  cifs    credentials=/mnt/ant.smbcred,uid=1000,gid=1000,rw,mfsymlinks,seal,iocharset=utf8,file_mode=0777,dir_mode=0777       0       0
//192.168.50.114/z      /mnt/z  cifs    credentials=/mnt/ant.smbcred,uid=1000,gid=1000,rw,mfsymlinks,seal,iocharset=utf8,file_mode=0777,dir_mode=0777       0       0
UUID=525eaf7a-24cb-4c77-8999-9ed9d2a1821f /mnt/mydocker auto nofail 0 0

```

Best regards :)

Borg log : 
```
Initializing repository...
using builtin fallback logging configuration
33 self tests completed in 0.18 seconds
Initializing repository at "/mnt/borgbackup/borg"
Key in "<Repository /mnt/borgbackup/borg>" created.
Keep this key safe. Your data will be inaccessible without it.
check_free_space: few segments, not requiring a full free segment
check_free_space: calculated working space for compact as 0 bytes
check_free_space: required bytes 169138, free bytes 15460683923456
security: previous location file /root/.config/borg/security/cb140e94a184c22def047a3542ad9fef4dff8d12c5eeb7881697d1e5a47057e7/location not found
security: manifest timestamp file /root/.config/borg/security/cb140e94a184c22def047a3542ad9fef4dff8d12c5eeb7881697d1e5a47057e7/manifest-timestamp not found
security: determined newest manifest timestamp as 
security: remembering previously unknown repository
security: saving state for cb140e94a184c22def047a3542ad9fef4dff8d12c5eeb7881697d1e5a47057e7 to /root/.config/borg/security/cb140e94a184c22def047a3542ad9fef4dff8d12c5eeb7881697d1e5a47057e7
security: current location   /mnt/borgbackup/borg
security: key type           5
security: manifest timestamp 2024-04-28T14:47:31.376795
security: repository checks ok, allowing access
Synchronizing chunks cache...
Archives: 0, w/ cached Idx: 0, w/ outdated Idx: 0, w/o cached Idx: 0.
Verified integrity of /mnt/borgbackup/borg/index.1
Done.
security: saving state for cb140e94a184c22def047a3542ad9fef4dff8d12c5eeb7881697d1e5a47057e7 to /root/.config/borg/security/cb140e94a184c22def047a3542ad9fef4dff8d12c5eeb7881697d1e5a47057e7
security: current location   /mnt/borgbackup/borg
security: key type           5
security: manifest timestamp 2024-04-28T14:47:31.376795

By default repositories initialized with this version will produce security
errors if written to with an older version (up to and including Borg 1.0.8).

If you want to use these older versions, you can disable the check by running:
borg upgrade --disable-tam /mnt/borgbackup/borg

See https://borgbackup.readthedocs.io/en/stable/changes.html#pre-1-0-9-manifest-spoofing-vulnerability for details about the security implications.

IMPORTANT: you will need both KEY AND PASSPHRASE to access this repo!
If you used a repokey mode, the key is stored in the repo, but you should back it up separately.
Use "borg key export" to export the key, optionally in printable format.
Write down the passphrase. Store both at safe place(s).

Repository successfully initialized.
Performing backup...
Starting the backup...
Creating archive at "/mnt/borgbackup/borg::20240428_144733-nextcloud-aio"
0 B O 0 B C 0 B D 0 N nextcloud_aio_volumes                                     
zing cache transaction: Reading config
zing cache transaction: Reading chunks
zing cache transaction: Reading files
294 B C 294 B D 1 N nextcloud_aio_volumes/n...o_nextcloud_data/.htaccess
O 1.97 MB C 1.97 MB D 6 N nextcloud_aio_volume...les/Photos/Vineyard.jpg
O 5.47 MB C 5.47 MB D 10 N nextcloud_aio_volum...Nextcloud community.jpg
O 7.60 MB C 7.60 MB D 15 N nextcloud_aio_volum...nts/Nextcloud flyer.pdf
O 9.35 MB C 9.35 MB D 18 N nextcloud_aio_volum...es/Nextcloud Manual.pdf
 O 23.19 MB C 23.19 MB D 18 N nextcloud_aio_volu.../Nextcloud Manual.pdf
 O 24.96 MB C 24.96 MB D 22 N nextcloud_aio_volu...plates/Photo book.odt
 O 28.57 MB C 28.57 MB D 28 N nextcloud_aio_volu.../Templates/Simple.odp
 O 33.00 MB C 33.00 MB D 31 N nextcloud_aio_volu...tes/Gotong royong.odp
 O 33.11 MB C 33.11 MB D 36 N nextcloud_aio_volu...Templates/Invoice.odt
 O 33.85 MB C 33.85 MB D 42 N nextcloud_aio_volu...ates/Mother's day.odt
 O 36.46 MB C 36.46 MB D 46 N nextcloud_aio_volu...s/Nextcloud intro.mp4
 O 37.33 MB C 37.33 MB D 51 N nextcloud_aio_volu...x1/appstore/apps.json
 O 38.04 MB C 38.04 MB D 57 N nextcloud_aio_volu...fonts/Caveat-wght.ttf
 O 39.10 MB C 39.10 MB D 63 N nextcloud_aio_volu...s/Montserrat-wght.ttf
 O 39.77 MB C 39.77 MB D 69 N nextcloud_aio_volu...s/Oswald-wght.ttf.png
 O 39.79 MB C 39.79 MB D 78 N nextcloud_aio_volu...omfortaa-wght.ttf.png
 O 39.84 MB C 39.84 MB D 85 N nextcloud_aio_volu...4/49/256-256-crop.jpg
 O 39.86 MB C 39.86 MB D 90 N nextcloud_aio_volu...qwtx1/preview/d/6/4/5
 O 39.94 MB C 39.94 MB D 94 N nextcloud_aio_volu.../e/37/396-512-max.png
 O 40.05 MB C 40.05 MB D 101 N nextcloud_aio_vol...vIcon-settings#0082c9
 O 40.10 MB C 40.10 MB D 110 N nextcloud_aio_vol.../admin/avatar.128.png
 O 40.23 MB C 40.23 MB D 121 N nextcloud_aio_vol...stercontainer/session
 O 40.79 MB C 40.79 MB D 443 N nextcloud_aio_vol...-php/src/CodeArtifact
 O 41.00 MB C 41.00 MB D 742 N nextcloud_aio_vol...on/KafkaException.php
 O 41.26 MB C 41.26 MB D 1041 N nextcloud_aio_vol...SMContactsClient.php
 O 41.67 MB C 41.67 MB D 1301 N nextcloud_aio_vol...01-11/api-2.json.php
 O 42.26 MB C 42.26 MB D 1561 N nextcloud_aio_vol...1/waiters-1.json.php
 O 42.98 MB C 42.98 MB D 1773 N nextcloud_aio_vol...aginators-1.json.php
 O 43.50 MB C 43.50 MB D 1990 N nextcloud_aio_vol...data/mwaa/2020-07-01
 O 43.93 MB C 43.93 MB D 2161 N nextcloud_aio_vol...03-01/api-2.json.php
 O 44.53 MB C 44.53 MB D 2407 N nextcloud_aio_vol...th/src/BigNumber.php
 O 45.05 MB C 45.05 MB D 2724 N nextcloud_aio_vol...andCompatibility.php
 O 45.27 MB C 45.27 MB D 3007 N nextcloud_aio_vol...umberMetadata_CD.php
 O 45.62 MB C 45.62 MB D 3303 N nextcloud_aio_vol.../psr7/src/Header.php
 O 46.18 MB C 46.17 MB D 3643 N nextcloud_aio_vol...zle7-adapter/LICENSE
 O 46.97 MB C 46.97 MB D 3934 N nextcloud_aio_vol...rc/data/cs/units.php
 O 48.33 MB C 48.05 MB D 4142 N nextcloud_aio_vol...hi/timeZoneNames.php
 O 49.75 MB C 49.31 MB D 4365 N nextcloud_aio_vol.../sk/subdivisions.php
B O 50.87 MB C 50.43 MB D 4593 N nextcloud_aio_vo...rgumentException.php
B O 51.46 MB C 51.01 MB D 4956 N nextcloud_aio_vo...ponent/VCalendar.php
B O 51.98 MB C 51.54 MB D 5310 N nextcloud_aio_vo...bstractExtension.php
B O 52.52 MB C 52.07 MB D 5663 N nextcloud_aio_vo...er/MatcherDumper.php
B O 53.03 MB C 52.58 MB D 6029 N nextcloud_aio_vo...Key/SymmetricKey.php
B O 54.98 MB C 54.53 MB D 6174 N nextcloud_aio_vo...ger-YHHKXmsa.mjs.map
B O 55.76 MB C 55.28 MB D 6506 N nextcloud_aio_vo...udit/l10n/es_MX.json
B O 56.80 MB C 56.29 MB D 6842 N nextcloud_aio_vo...circles/l10n/bg.json
B O 57.50 MB C 56.94 MB D 7201 N nextcloud_aio_vo...otFoundException.php
B O 58.02 MB C 57.43 MB D 7565 N nextcloud_aio_vo...s/appinfo/routes.php
B O 58.35 MB C 57.72 MB D 7958 N nextcloud_aio_vo...hboard/l10n/ka_GE.js
B O 59.20 MB C 58.53 MB D 8294 N nextcloud_aio_vo...rdDAV/PhotoCache.php
B O 59.85 MB C 59.12 MB D 8667 N nextcloud_aio_vo...tion/l10n/pt_BR.json
B O 60.45 MB C 59.65 MB D 9048 N nextcloud_aio_vo...eration/l10n/oc.json
B O 61.41 MB C 60.55 MB D 9346 N nextcloud_aio_vo...iles/l10n/pt_PT.json
B O 62.11 MB C 61.21 MB D 9655 N nextcloud_aio_vo...rnal/l10n/es_MX.json
B O 63.76 MB C 62.82 MB D 9899 N nextcloud_aio_vo...d/pdf.sandbox.js.map
B O 66.49 MB C 65.56 MB D 10103 N nextcloud_aio_vo...tton-selectTool.svg
B O 69.25 MB C 68.32 MB D 10269 N nextcloud_aio_vo...fviewer-main.js.map
B O 71.99 MB C 71.06 MB D 10348 N nextcloud_aio_vo...r/package-lock.json
B O 72.90 MB C 71.92 MB D 10632 N nextcloud_aio_vo...ing/l10n/zh_HK.json
B O 73.44 MB C 72.43 MB D 11038 N nextcloud_aio_vo...sions/l10n/es_SV.js
B O 78.98 MB C 77.96 MB D 11203 N nextcloud_aio_vo...nwizard-main.js.map
B O 81.08 MB C 80.04 MB D 11411 N nextcloud_aio_vo...reader-main.mjs.map
B O 81.73 MB C 80.67 MB D 11785 N nextcloud_aio_vo...ments/l10n/es_PY.js
B O 84.24 MB C 83.16 MB D 11911 N nextcloud_aio_vo...ents_-304b96.js.map
B O 86.24 MB C 85.15 MB D 12065 N nextcloud_aio_vo...ations/l10n/oc.json
B O 87.76 MB C 86.64 MB D 12343 N nextcloud_aio_vo...ker-cOp1W5mL_mjs.js
B O 89.90 MB C 88.77 MB D 12544 N nextcloud_aio_vo...y/lists/list-11.php
B O 93.34 MB C 92.20 MB D 12578 N nextcloud_aio_vo...cy/lists/list-8.php
B O 97.00 MB C 95.85 MB D 12597 N nextcloud_aio_vo.../photos-main.js.map
B O 100.23 MB C 99.08 MB D 12626 N nextcloud_aio_v...hotos-public.js.map
B O 102.72 MB C 101.56 MB D 12717 N nextcloud_aio_v.../photos/l10n/el.js
B O 106.30 MB C 105.11 MB D 12986 N nextcloud_aio_v...rivacy-main.js.map
B O 108.29 MB C 107.11 MB D 13096 N nextcloud_aio_v...dminController.php
B O 109.63 MB C 108.42 MB D 13347 N nextcloud_aio_v...tions/package.json
B O 110.44 MB C 109.21 MB D 13627 N nextcloud_aio_v.../package-lock.json
B O 112.21 MB C 110.95 MB D 13928 N nextcloud_aio_v...ettings/l10n/es.js
B O 114.24 MB C 112.91 MB D 14081 N nextcloud_aio_v...eRenderedEvent.php
B O 114.91 MB C 113.53 MB D 14460 N nextcloud_aio_v...support/l10n/sk.js
B O 116.33 MB C 114.90 MB D 14734 N nextcloud_aio_v...ogin/l10n/pt_PT.js
B O 117.11 MB C 115.67 MB D 15102 N nextcloud_aio_v...oSetVisibility.php
B O 117.57 MB C 116.13 MB D 15497 N nextcloud_aio_v...rs/FuzzyCMeans.php
B O 117.96 MB C 116.52 MB D 15896 N nextcloud_aio_v...izers/AdamTest.php
B O 118.43 MB C 116.97 MB D 16280 N nextcloud_aio_v...ring/composer.json
B O 120.58 MB C 119.05 MB D 16576 N nextcloud_aio_v...utohotkey-js-js.js
B O 121.35 MB C 119.82 MB D 16910 N nextcloud_aio_v.../livecodeserver.js
B O 122.09 MB C 120.56 MB D 17174 N nextcloud_aio_v...s/highlight/sqf.js
B O 124.13 MB C 122.60 MB D 17348 N nextcloud_aio_v...ext-editors.js.map
B O 127.81 MB C 126.28 MB D 17357 N nextcloud_aio_v...text-public.js.map
B O 130.92 MB C 129.39 MB D 17366 N nextcloud_aio_v...t-me-01b328.js.map
B O 134.82 MB C 133.29 MB D 17386 N nextcloud_aio_v...extc-dbda74.js.map
B O 137.79 MB C 136.19 MB D 17414 N nextcloud_aio_v...ps/text/l10n/bg.js
B O 139.70 MB C 138.06 MB D 17688 N nextcloud_aio_v...lion-rock-hill.jpg
B O 156.51 MB C 154.87 MB D 17716 N nextcloud_aio_v...t-highcontrast.jpg
B O 157.54 MB C 155.86 MB D 18048 N nextcloud_aio_v...codes/lib/Listener
B O 159.50 MB C 157.80 MB D 18280 N nextcloud_aio_v...platform_check.php
B O 160.85 MB C 158.96 MB D 18553 N nextcloud_aio_v..._ldap/l10n/su.json
B O 162.40 MB C 160.50 MB D 18848 N nextcloud_aio_v...r-filerobot.js.map
B O 166.06 MB C 164.16 MB D 18859 N nextcloud_aio_v...BGB1Rec_mjs.js.map
B O 166.72 MB C 164.78 MB D 19236 N nextcloud_aio_v...ne/l10n/de_DE.json
B O 167.33 MB C 165.36 MB D 19628 N nextcloud_aio_v...core/css/fixes.css
B O 175.60 MB C 173.64 MB D 19778 N nextcloud_aio_v...9-upgrade-page.png
B O 180.21 MB C 178.25 MB D 19988 N nextcloud_aio_v...l_storage/ftp.html
B O 184.38 MB C 182.42 MB D 20168 N nextcloud_aio_v..._images/circle.png
B O 196.39 MB C 194.42 MB D 20298 N nextcloud_aio_v...talk-grid-view.png
B O 205.34 MB C 200.46 MB D 20429 N nextcloud_aio_v.../NotoSans-Bold.ttf
B O 209.19 MB C 204.32 MB D 20564 N nextcloud_aio_v...aldav/location.png
B O 211.01 MB C 206.13 MB D 20784 N nextcloud_aio_v.../core/l10n/sr.json
B O 247.85 MB C 206.50 MB D 20875 N nextcloud_aio_v...emplates/tags.html
B O 250.96 MB C 209.62 MB D 20927 N nextcloud_aio_v...ist/core-common.js
B O 253.74 MB C 212.39 MB D 20943 N nextcloud_aio_v...gin.js.LICENSE.txt
B O 257.36 MB C 216.02 MB D 20996 N nextcloud_aio_v...les-sidebar.js.map
B O 259.89 MB C 218.55 MB D 21074 N nextcloud_aio_v...sharebymail.js.map
B O 261.55 MB C 220.19 MB D 21295 N nextcloud_aio_v...d/lib/l10n/ta.json
B O 262.25 MB C 220.89 MB D 21674 N nextcloud_aio_v...yOptimizerStep.php
B O 262.91 MB C 221.56 MB D 22063 N nextcloud_aio_v...e/User/Session.php
B O 263.47 MB C 222.12 MB D 22470 N nextcloud_aio_v...e/IObjectStore.php
B O 263.89 MB C 222.54 MB D 22888 N nextcloud_aio_v...b/public/ITags.php
B O 268.62 MB C 227.12 MB D 22945 N nextcloud_aio_v...arch64/notify_push
B O 275.70 MB C 234.21 MB D 22946 N nextcloud_aio_v.../armv7/notify_push
B O 280.62 MB C 239.13 MB D 22947 N nextcloud_aio_v...x86_64/notify_push
B O 284.51 MB C 243.00 MB D 22984 N nextcloud_aio_v...tasks-dashboard.js
B O 287.32 MB C 245.81 MB D 22987 N nextcloud_aio_v...s/js/tasks-main.js
B O 290.09 MB C 248.59 MB D 22990 N nextcloud_aio_v...s/js/tasks-talk.js
B O 292.50 MB C 250.97 MB D 23118 N nextcloud_aio_v...s/tasks/l10n/nl.js
B O 295.40 MB C 253.86 MB D 23204 N nextcloud_aio_v...tes-commons.js.map
B O 298.84 MB C 257.18 MB D 23214 N nextcloud_aio_v...notes/l10n/ar.json
B O 301.02 MB C 259.35 MB D 23481 N nextcloud_aio_v...s/contacts-main.js
B O 303.92 MB C 262.25 MB D 23502 N nextcloud_aio_v...tacts/l10n/ca.json
B O 305.79 MB C 264.08 MB D 23775 N nextcloud_aio_v...ck/js/deck-main.js
B O 309.08 MB C 267.24 MB D 23777 N nextcloud_aio_v...s/deck-main.js.map
B O 312.35 MB C 270.40 MB D 23802 N nextcloud_aio_v...ck/js/deck-talk.js
B O 315.84 MB C 273.77 MB D 23807 N nextcloud_aio_v...e_mo-dee90d.js.map
B O 318.96 MB C 276.77 MB D 23824 N nextcloud_aio_v...index_module_js.js
B O 320.70 MB C 278.36 MB D 24018 N nextcloud_aio_v...ck/l10n/zh_CN.json
B O 323.42 MB C 281.04 MB D 24286 N nextcloud_aio_v...nts-booking.js.map
B O 326.85 MB C 284.47 MB D 24295 N nextcloud_aio_v...ts-overview.js.map
B O 330.04 MB C 287.66 MB D 24304 N nextcloud_aio_v...lendar-main.js.map
B O 333.32 MB C 290.94 MB D 24336 N nextcloud_aio_v...ct_d-732246.js.map
B O 336.57 MB C 294.07 MB D 24348 N nextcloud_aio_v...Dial-e0595f.js.map
B O 338.99 MB C 296.47 MB D 24452 N nextcloud_aio_v...endar/l10n/hu.json
B O 340.00 MB C 297.44 MB D 24816 N nextcloud_aio_v...tivirus/l10n/th.js
B O 345.78 MB C 300.77 MB D 25025 N nextcloud_aio_v...ments-admin.js.map
B O 348.93 MB C 303.92 MB D 25038 N nextcloud_aio_v...ments-reference.js
O 352.22 MB C 307.22 MB D 25045 N nextcloud_aio_vo..._Dial-7228d0.js.map
O 355.40 MB C 310.40 MB D 25048 N nextcloud_aio_vo...ments-viewer.js.map
O 357.07 MB C 312.03 MB D 25342 N nextcloud_aio_vo...search/l10n/an.json
O 361.82 MB C 316.56 MB D 25685 N nextcloud_aio_vo...kgrounds/5_park.jpg
O 368.12 MB C 322.86 MB D 25757 N nextcloud_aio_vo...-collections.js.map
O 371.25 MB C 325.98 MB D 25774 N nextcloud_aio_vo...st_cjs_js-48bdaa.js
O 374.58 MB C 329.32 MB D 25787 N nextcloud_aio_vo...iles-sidebar.js.map
O 377.66 MB C 332.40 MB D 25790 N nextcloud_aio_vo...eed/js/talk-main.js
O 380.76 MB C 335.49 MB D 25791 N nextcloud_aio_vo...js/talk-main.js.map
O 384.49 MB C 339.23 MB D 25799 N nextcloud_aio_vo...auth-sidebar.js.map
O 387.97 MB C 342.60 MB D 25800 N nextcloud_aio_vo...ic-share-sidebar.js
O 392.23 MB C 346.75 MB D 25802 N nextcloud_aio_vo...s/talk-recording.js
O 395.60 MB C 350.00 MB D 25804 N nextcloud_aio_vo...js/tflite-simd.wasm
O 398.18 MB C 352.56 MB D 25908 N nextcloud_aio_vo...spreed/l10n/nb.json
O 399.39 MB C 353.77 MB D 25961 N nextcloud_aio_vo...undJob/Reminder.php
O 399.99 MB C 354.37 MB D 26347 N nextcloud_aio_vo...sponses/DialOut.php
O 400.51 MB C 354.89 MB D 26692 N nextcloud_aio_vo...spreed/package.json
O 401.06 MB C 355.39 MB D 27107 N nextcloud_aio_vo...icsearch/l10n/ca.js
O 401.29 MB C 355.61 MB D 27585 N nextcloud_aio_vo...cce1920a06.asciidoc
O 404.17 MB C 358.48 MB D 27819 N nextcloud_aio_vo...0010000000000000001
O 405.70 MB C 360.01 MB D 27891 N nextcloud_aio_vo...atabase/base/1/1249
O 406.97 MB C 360.83 MB D 28324 N nextcloud_aio_vo...atabase/base/4/3466
O 408.80 MB C 361.36 MB D 28817 N nextcloud_aio_vo...ase/base/16384/2337
O 409.35 MB C 361.91 MB D 28959 N nextcloud_aio_vo...ase/base/16384/1255
O 409.79 MB C 362.35 MB D 29429 N nextcloud_aio_vo...se/base/16384/17163
                                                                        
ception
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/borg/archiver.py", line 5343, in main
    exit_code = archiver.run(args)
                ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/borg/archiver.py", line 5263, in run
    return set_ec(func(args))
                  ^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/borg/archiver.py", line 189, in wrapper
    return method(self, args, repository=repository, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/borg/archiver.py", line 672, in do_create
    create_inner(archive, cache, fso)
  File "/usr/lib/python3.11/site-packages/borg/archiver.py", line 626, in create_inner
    archive.save(comment=args.comment, timestamp=args.timestamp)
  File "/usr/lib/python3.11/site-packages/borg/archive.py", line 666, in save
    self.manifest.write()
  File "/usr/lib/python3.11/site-packages/borg/helpers/manifest.py", line 265, in write
    self.repository.put(self.MANIFEST_ID, self.key.encrypt(data))
  File "/usr/lib/python3.11/site-packages/borg/repository.py", line 1235, in put
    self._delete(id, segment, offset)
  File "/usr/lib/python3.11/site-packages/borg/repository.py", line 1270, in _delete
    segment, size = self.io.write_delete(id)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/borg/repository.py", line 1689, in write_delete
    fd = self.get_write_fd(want_new=(id == Manifest.MANIFEST_ID), raise_full=raise_full)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/borg/repository.py", line 1437, in get_write_fd
    self.close_segment()
  File "/usr/lib/python3.11/site-packages/borg/repository.py", line 1493, in close_segment
    fd.close()
  File "/usr/lib/python3.11/site-packages/borg/platform/base.py", line 194, in close
    self.sync()
  File "/usr/lib/python3.11/site-packages/borg/platform/base.py", line 183, in sync
    platform.fdatasync(self.fd)
ConnectionResetError: [Errno 104] Connection reset by peer

Platform: Linux f7c94a24b25d 5.15.0-105-generic #115-Ubuntu SMP Mon Apr 15 09:52:04 UTC 2024 x86_64
Linux: Unknown Linux  
Borg: 1.2.7  Python: CPython 3.11.9 msgpack: 1.0.6 fuse: llfuse 1.5.0 [pyfuse3,llfuse]
PID: 43  CWD: /
sys.argv: ['/usr/bin/borg', 'create', '-v', '--stats', '--compression', 'auto,zstd', '--exclude-caches', '--progress', '--exclude', '/nextcloud_aio_volumes/nextcloud_aio_nextcloud/data/nextcloud.log*', '--exclude', '/nextcloud_aio_volumes/nextcloud_aio_nextcloud/data/audit.log', '/mnt/borgbackup/borg::20240428_144733-nextcloud-aio', '/nextcloud_aio_volumes/']
SSH_ORIGINAL_COMMAND: None

Deleting the failed backup archive...
Archive 20240428_144733-nextcloud-aio not found (1/1).
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
Deleted data:                    0 B                  0 B                  0 B
All archives:                    0 B                  0 B                  0 B

                       Unique chunks         Total chunks
Chunk index:                       0                    0
------------------------------------------------------------------------------
Backup failed!
You might want to check the backup integrity via the AIO interface.
Deleting borg.config file so that you can choose a different location for the backup.
```

**Comment by ThomasWaldmann** [comment]
```
ConnectionResetError: [Errno 104] Connection reset by peer
```

That's a network / network filesystem issue, not a borg issue.

**Comment by warlordattack** [comment]
I have many things including proxmox VMs backups very large in size, they backup every night with no errors, so i don't understand how this could be network error ?
And if this is due to network what could i do about it ?
Is there some fstab options to use to not have this error or something like this please ?

**Comment by ThomasWaldmann** [comment]
Well, obviously it is. That message is not coming from borg, but from the OS.

borg just tried to sync and close a file.

"connection reset" -> refers to the network connection
"by peer" == "by the other machine" (windows machine?)

Could be a windows issue, maybe also CIFS. Or just a general network hickup.

**Comment by ThomasWaldmann** [comment]
Side note: Recently, a quite serious bug was found in smbfs/cifs, see the other tickets.

But connection reset by peer sounds more like a network issue.
