### ISSUE TITLE
Borg doesn't respond to Ctrl-C as expected

### ISSUE THREAD

**Issue by garethrees** [borgbackup/borg#825]
I'm trying to write a script that pulls a few borg commands together to run some automated backups.

I want to handle interrupts with a cleanup command in the script, but borg doesn't seem to handle the Ctrl-C signal as I'd expect.

I've put together a simple Vagrant box and demo scripts to be able to reproduce the issue: https://github.com/garethrees/borg-trap-test

The box includes two scripts:

- [`traptest`](https://github.com/garethrees/borg-trap-test/blob/master/Vagrantfile#L84-L104): A simple example of how I want to use `trap` and how it responds
- [`borgtest`](https://github.com/garethrees/borg-trap-test/blob/master/Vagrantfile#L11-L81): A simplified example of my backup script

I'll break up the output to explain what's happening at each stage, but you can see the full output here: https://github.com/garethrees/borg-trap-test/issues/1

```sh
# Run the sample script
ubuntu@ubuntu-xenial:~$ ./borgtest
# Make a source and destination
Creating source...
Creating destination...

# Ctrl-C immediately after the borg init
Initializing borg repo...
^CException ignored in: <bound method Repository.__del__ of <Repository /tmp/backups>>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 67, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 155, in close
    if self.lock:
AttributeError: 'Repository' object has no attribute 'lock'
Keyboard interrupt.
Traceback (most recent call last):
  File "/usr/lib/python3.5/socket.py", line 662, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1466, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1420, in run
    return args.func(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 92, in do_init
    repository = self.open_repository(args, create=True, exclusive=True)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 67, in open_repository
    repository = Repository(location.path, create=create, exclusive=exclusive, lock_wait=self.lock_wait, lock=lock)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 57, in __init__
    self._location = Location('file://%s' % self.path)
  File "/usr/lib/python3/dist-packages/borg/helpers.py", line 706, in __init__
    if not self.parse(self.orig):
  File "/usr/lib/python3/dist-packages/borg/helpers.py", line 723, in parse
    text = self.preformat_text(text)
  File "/usr/lib/python3/dist-packages/borg/helpers.py", line 714, in preformat_text
    'fqdn': socket.getfqdn(),
  File "/usr/lib/python3.5/socket.py", line 662, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
KeyboardInterrupt

Platform: Linux ubuntu-xenial 4.4.0-16-generic #32-Ubuntu SMP Thu Mar 24 22:38:01 UTC 2016 x86_64 x86_64
Linux: Ubuntu 16.04 xenial  LibC: glibc 2.9
Borg: 1.0.0  Python: CPython 3.5.1+
PID: 9524  CWD: /home/ubuntu
sys.argv: ['/usr/bin/borg', 'init', '--encryption=none', '/tmp/backups']
SSH_ORIGINAL_COMMAND: None
```

I'm not sure why there's a Python backtrace, but in any case, I'd expect my `clean_up` function to be run now. It isn't:

```sh
# The script continues…
Creating new backup...
reading files cache
processing files
------------------------------------------------------------------------------
Archive name: 4ad26226c097
Archive fingerprint: f2787be4f6a00e28a15164812613b5d2a3296f46bf56cead122b6da344c67636
Time (start): Fri, 2016-04-01 22:19:16
Time (end):   Fri, 2016-04-01 22:19:16
Duration: 0.04 seconds
Number of files: 1
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                  492 B                498 B                498 B
All archives:                  984 B                996 B                996 B

                       Unique chunks         Total chunks
Chunk index:                       4                    4
------------------------------------------------------------------------------
Pruning old backups...
Checking backups...
```

And then the "normal" cleanup is run:

```sh
Unmounting /tmp/backups
Unmounting /tmp/source
```

I'd expect the output to look like this:

```sh
ubuntu@ubuntu-xenial:~$ ./borgtest
Creating source...
Creating destination...
# Ctrl-C immediately after the borg init
Initializing borg repo...
^CUnmounting /tmp/backups
Unmounting /tmp/source
```

Not sure if this is something I'm doing wrong or an issue with borg, but given the simpler example without borg, it feels like it might be borg that's not behaving.

Thanks!

**Comment by Ape** [comment]
Try with the latest version in git master. I think #777 may fix this.

Also, related to #805.

**Comment by ThomasWaldmann** [comment]
Some of the errors you see might be because your host has troubles with its own hostname / its own IP address. Other than that @Ape is right, this might be already fixed in master branch, so please try to reproduce with current code.

**Comment by garethrees** [comment]
Seems like I get the same problem:

```sh
# -----------------------------------------------------------
borg 1.0.1.dev93+ngd6590b4
# -----------------------------------------------------------
Creating source...
Creating destination...
Initializing borg repo...
^CTraceback (most recent call last):
  File "/home/ubuntu/borg-env/bin/borg", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/ubuntu/borg-env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 37, in <module>
    import email.parser
  File "/usr/lib/python3.5/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "/usr/lib/python3.5/email/feedparser.py", line 27, in <module>
    from email import message
  File "/usr/lib/python3.5/email/message.py", line 16, in <module>
    from email import utils
  File "/usr/lib/python3.5/email/utils.py", line 29, in <module>
    import socket
  File "/usr/lib/python3.5/socket.py", line 81, in <module>
    lambda C: C.isupper() and C.startswith('SOCK_'))
  File "/usr/lib/python3.5/enum.py", line 536, in _convert
    module_globals = vars(sys.modules[module])
KeyboardInterrupt
Creating new backup...
Using a pure-python msgpack! This will result in lower performance.
------------------------------------------------------------------------------
Archive name: 1fba230d3da7
Archive fingerprint: b3a3b2b905d03d06bb9996fbcb2d8de1fd180555a4ec08549d553e7ca0c49c65
Time (start): Sat, 2016-04-02 20:41:32
Time (end):   Sat, 2016-04-02 20:41:32
Duration: 0.01 seconds
Number of files: 1
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                  548 B                554 B                554 B
All archives:                2.74 kB              2.77 kB              2.77 kB

                       Unique chunks         Total chunks
Chunk index:                      10                   10
------------------------------------------------------------------------------
Pruning old backups...
Using a pure-python msgpack! This will result in lower performance.
Checking backups...
Using a pure-python msgpack! This will result in lower performance.
Unmounting /tmp/backups
Unmounting /tmp/source
```

**Comment by enkore** [comment]
#777 didn't change how signals / exceptions were handled regarding control flow, it was about proper cleanup and unlocking even on unexpected aborts.

That being said, if I interrupt (^C, SIGINT) borg create or similar commands it exits with exit code 2 (like it should). If you have `set -e` this will abort the script.

**Comment by garethrees** [comment]
Going to close this because I can't really figure out where the problem lies.

I've changed my backup script to check for the existence of the `README` file rather than using `|| true`.

```sh
function init_repo {
  if [[ ! -f /tmp/backups/README ]]; then
    echo "Initializing borg repo..."
    $BACKUP_TOOL init --encryption=none "/tmp/backups"
  fi
}
```
