### ISSUE TITLE
bauerj ARM binary for 1.4.0: broken borg key export --qr-html

### ISSUE THREAD

**Issue by jjakob** [borgbackup/borg#8353]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

yes

## Is this a BUG / ISSUE report or a QUESTION?

bug

#### Your borg version (borg -V).
borg 1.4.0

#### Operating system (distribution) and version.
Platform: Linux pureos 6.6.0-1-librem5 #1 SMP PREEMPT Fri Jun  7 03:48:21 EDT 2024 aarch64
Linux: Unknown Linux
Borg: 1.4.0  Python: CPython 3.12.4 msgpack: 1.0.8 fuse: None [pyfuse3,llfuse]

pre-built binary for arm64 downloaded from https://borg.bauerj.eu/bin/borg-1.4.0-arm64

#### Hardware / network configuration, and filesystems used.
n/a
#### How much data is handled by borg?
n/a
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
`borg key export --qr-html user@192.0.2.3:~/borg borg_key_export.html`

## Describe the problem you're observing.

```
Local Exception
Traceback (most recent call last):
  File "borg/archiver.py", line 5391, in main
  File "borg/archiver.py", line 5309, in run
  File "borg/archiver.py", line 191, in wrapper
  File "borg/archiver.py", line 398, in do_key_export
  File "borg/crypto/keymanager.py", line 101, in export_qr
  File "pkgutil.py", line 453, in get_data
  File "PyInstaller/loader/pyimod02_importers.py", line 228, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEIWu6lTQ/borg/paperkey.html'

Platform: Linux pureos 6.6.0-1-librem5 #1 SMP PREEMPT Fri Jun  7 03:48:21 EDT 2024 aarch64
Linux: Unknown Linux
Borg: 1.4.0  Python: CPython 3.12.4 msgpack: 1.0.8 fuse: None [pyfuse3,llfuse]
PID: 3541  CWD: /root
sys.argv: ['borg', 'key', 'export', '--qr-html', 'user@192.0.2.3:~/borg', 'borg_key_export.html']
SSH_ORIGINAL_COMMAND: None
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
created a new repo with borg init, then tried exporting the key, both regular and `--paper` export worked, but `--qr-html` doesn't.

#### Include any warning/errors/backtraces from the system logs
nothing logged to syslog

**Comment by ThomasWaldmann** [comment]
Oh, looks like the html template that should be included with borg is missing from the pyinstaller-made fat borg binary.

As a workaround you can use another export format for now, they should work, likely only the `--qr-html` format is broken.

**Comment by jjakob** [comment]
I already exported the key and don't need the html version, so that's good. I'm wondering if installing from a source checkout with pip (non-editable) have the same error?

**Comment by ThomasWaldmann** [comment]
# pypi.org package / .tar.gz download on github releases

I installed these via pip into a venv and tested `borg key export --qr-html key.html` - it worked.

**Comment by ThomasWaldmann** [comment]
## 1.4.0 macos fat binary from gh releases

I downloaded that and tested `borg key export --qr-html key.html` - it worked.

**Comment by ThomasWaldmann** [comment]
As I do not build the ARM binaries, it looks like you have to talk to bauerj about the binary he built.

The build process we use for our binaries can be seen in the Vagrantfile.

**Comment by ThomasWaldmann** [comment]
I'll leave this open for a while, but will tag this as wontfix because that binary is not built by me.

**Comment by ThomasWaldmann** [comment]
@jjakob file an issue there: https://gitlab.com/borg-binary-builder/borg-binaries/-/issues

**Comment by jjakob** [comment]
> @jjakob file an issue there: https://gitlab.com/borg-binary-builder/borg-binaries/-/issues

Will do, is this the builder that bauerj uses?

**Comment by ThomasWaldmann** [comment]
@jjakob yes.

**Comment by jjakob** [comment]
https://gitlab.com/borg-binary-builder/borg-binaries/-/issues/12

**Comment by jjakob** [comment]
Somebody already created an issue: https://gitlab.com/borg-binary-builder/borg-binaries/-/issues/14

**Comment by ThomasWaldmann** [comment]
Closing it here, it is tracked there (see links above).
