### ISSUE TITLE
WORKAROUNDS=authenticated_no_key still tries to authenticate archives

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#8400]
## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).

1.4.0, likely all borg versions > 1.2.4.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
WORKAROUNDS=authenticated_no_key borg ...
```

## Describe the problem you're observing.

A repo in authenticated mode is not encrypted, but a borg key is used for the authentication.
If one loses the passphrase, one usually can't access the repo, because borg wants to authenticate all stuff, but has no usable borg key.

`WORKAROUNDS=authenticated_no_key` enables accessing the unencrypted data in such circumstances by disabling the authentication.

#### Include any warning/errors/backtraces from the system logs

```
using builtin fallback logging configuration
33 self tests completed in 0.09 seconds
Verified integrity of /media/backup/index.10758
security: read previous location '/media/backup'
security: read manifest timestamp '2024-09-15T19:18:06.069631'
security: determined newest manifest timestamp as 2024-09-15T19:18:06.069631
security: repository checks ok, allowing access
Data integrity error: Archive authentication did not verify
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/borg/archiver.py", line 5391, in main
    exit_code = archiver.run(args)
                ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/borg/archiver.py", line 5309, in run
    rc = func(args)
         ^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/borg/archiver.py", line 191, in wrapper
    return method(self, args, repository=repository, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/borg/archiver.py", line 199, in wrapper
    archive = Archive(repository, key, manifest, args.location.archive,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/borg/archive.py", line 472, in __init__
    self.load(info.id)
  File "/usr/lib/python3.12/site-packages/borg/archive.py", line 485, in load
    self.metadata = self._load_meta(self.id)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/borg/archive.py", line 477, in _load_meta
    archive, self.tam_verified, _ = self.key.unpack_and_verify_archive(data, force_tam_not_required=True)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/borg/crypto/key.py", line 338, in unpack_and_verify_archive
    raise ArchiveTAMInvalid()
borg.crypto.key.ArchiveTAMInvalid: Data integrity error: Archive authentication did not verify

Platform: Linux jupiter 6.10.11-1-generic #1 SMP PREEMPT_DYNAMIC Thu Sep 19 03:28:27 UTC 2024 x86_64
Linux: Unknown Linux  
Borg: 1.4.0  Python: CPython 3.12.6 msgpack: 1.1.0 fuse: pyfuse3 3.4.0 [pyfuse3,llfuse]
PID: 3302  CWD: /home/callisto/tmp/borg
sys.argv: ['/usr/bin/borg', '--debug', 'extract', '/media/backup::2024-09-16T00:12:04-1.4.0-home']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment]
Fixed in 1.2-maint and 1.4-maint branches, will be in 1.2.9 and 1.4.1.

For master (borg2), no fix is needed.
