### ISSUE TITLE
prune with a series name gives an AssertionError

### ISSUE THREAD

**Issue by witten** [borgbackup/borg#8486]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes.

## Is this a BUG / ISSUE report or a QUESTION?

BUG / ISSUE

## System information. For client/server mode post info for both machines.

Client: Borg 2.0.0b12 (not using a server for this ticket)

#### Operating system (distribution) and version.

Manjaro stable 24.1.1

#### Hardware / network configuration, and filesystems used.

Lenovo X1 Carbon, no network, ext4

#### How much data is handled by borg?

None.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```bash
$ borg2.0.0b12 repo-create --encryption repokey-aes-ocb --debug --repo test.borg
$ borg2.0.0b12 prune --keep-daily 30 --repo test.borg seriesname
```

## Describe the problem you're observing.

The `prune` results in an `AssertionError` when a series name is given (whether or not it matches any archives in the repo).

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes.

#### Include any warning/errors/backtraces from the system logs

```
Local Exception

Error:

AssertionError: match_pattern is a <class 'str'>

If reporting bugs, please include the following:

Traceback (most recent call last):
  File "borg/archiver/__init__.py", line 633, in main
  File "borg/archiver/__init__.py", line 527, in run
  File "borg/archiver/_common.py", line 176, in wrapper
  File "borg/archiver/prune_cmd.py", line 95, in do_prune
  File "borg/manifest.py", line 366, in list
  File "borg/manifest.py", line 178, in _matching_info_tuples
AssertionError: match_pattern is a <class 'str'>

Platform: Linux flux 6.1.112-1-MANJARO #1 SMP PREEMPT_DYNAMIC Mon Sep 30 19:15:46 UTC 2024 x86_64
Linux: Unknown Linux  
Borg: 2.0.0b12  Python: CPython 3.12.6 msgpack: 1.1.0 fuse: llfuse 1.5.1 [pyfuse3,llfuse]
PID: 688783  CWD: /root/tmp
sys.argv: ['/root/borg2.0.0b12', 'prune', '--keep-daily', '30', '--repo', 'test.borg', 'seriesname']
SSH_ORIGINAL_COMMAND: None
```

**Comment by witten** [comment]
Awesome, thank you!
