### ISSUE TITLE
vagrant: freebsd14 box broken

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#8508]
the python 3.9 there has issues:
```
freebsd14: py39-fuse2: commands[0]> py.test -v -n 8 -rs --cov=borg --cov-config=.coveragerc --benchmark-skip --pyargs borg.testsuite
    freebsd14: Traceback (most recent call last):
    freebsd14:   File "/vagrant/borg/borg/.tox/py39-fuse2/bin/py.test", line 8, in <module>
    freebsd14:     sys.exit(console_main())
    freebsd14:   File "/vagrant/borg/borg/.tox/py39-fuse2/lib/python3.9/site-packages/_pytest/config/__init__.py", line 201, in console_main
    freebsd14:     code = main()
    freebsd14:   File "/vagrant/borg/borg/.tox/py39-fuse2/lib/python3.9/site-packages/_pytest/config/__init__.py", line 156, in main
    freebsd14:     config = _prepareconfig(args, plugins)
    freebsd14:   File "/vagrant/borg/borg/.tox/py39-fuse2/lib/python3.9/site-packages/_pytest/config/__init__.py", line 341, in _prepareconfig
    freebsd14:     config = pluginmanager.hook.pytest_cmdline_parse(
    ...
    freebsd14: ModuleNotFoundError: No module named '_sqlite3'
```

Also, the binary made with pyinstaller misses borghash:
```
   freebsd14: [gw7] freebsd14 -- Python 3.10.15 /vagrant/borg/borg/.tox/py310-fuse2/bin/python
    freebsd14: 
    freebsd14: archivers = 'binary_archiver'
    freebsd14: request = <FixtureRequest for <Function test_extract_include_exclude_regex[binary_archiver]>>
    freebsd14: 
    freebsd14:     def test_extract_include_exclude_regex(archivers, request):
    freebsd14:         archiver = request.getfixturevalue(archivers)
    freebsd14: >       cmd(archiver, "repo-create", RK_ENCRYPTION)
    freebsd14: 
    freebsd14: /vagrant/borg/borg/src/borg/testsuite/archiver/extract_cmd_test.py:349:
    freebsd14: _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    freebsd14: 
    freebsd14: archiver = <borg.conftest.ArchiverSetup object at 0x2dc8d110a410>
    freebsd14: args = ('repo-create', '--encryption=repokey-aes-ocb'), kw = {}, exit_code = 0
    freebsd14: fork = True, binary_output = False, ret = 2
    freebsd14: output = 'Traceback (most recent call last):\n  File "borg/archiver/__init__.py", line 23, in <module>\n  File "PyInstaller/loa...\n  File "src/borg/hashindex.pyx", line 6, in init borg.hashindex\nModuleNotFoundError: No module named \'borghash\'\n'
    freebsd14: @py_assert1 = False, @py_format3 = '2 == 0', @py_format5 = 'assert 2 == 0'
    freebsd14: 
    freebsd14:     def cmd(archiver, *args, **kw):
    freebsd14:         exit_code = kw.pop("exit_code", 0)
    freebsd14:         fork = kw.pop("fork", None)
    freebsd14:         binary_output = kw.get("binary_output", False)
    freebsd14:         if fork is None:
    freebsd14:             fork = archiver.FORK_DEFAULT
    freebsd14:         ret, output = exec_cmd(
    freebsd14:             f"--repo={archiver.repository_location}", *args, archiver=archiver.archiver, fork=fork, exe=archiver.EXE, **kw
    freebsd14:         )
    freebsd14:         if ret != exit_code:
    freebsd14:             print(output)
    freebsd14: >       assert ret == exit_code
    freebsd14: E       assert 2 == 0
    freebsd14: 
    freebsd14: /vagrant/borg/borg/src/borg/testsuite/archiver/__init__.py:152: AssertionError
    freebsd14: ----------------------------- Captured stdout call -----------------------------
    freebsd14: Traceback (most recent call last):
    freebsd14:   File "borg/archiver/__init__.py", line 23, in <module>
    freebsd14:   File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
    freebsd14:   File "borg/archiver/_common.py", line 6, in <module>
    freebsd14:   File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
    freebsd14:   File "borg/archive.py", line 25, in <module>
    freebsd14:   File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
    freebsd14:   File "borg/cache.py", line 18, in <module>
    freebsd14:   File "src/borg/hashindex.pyx", line 6, in init borg.hashindex
    freebsd14: ModuleNotFoundError: No module named 'borghash'
```

**Comment by ThomasWaldmann** [comment]
Only for py 3.9 and 3.11, 3.10 and 3.12 work. Strange, they all come from pyenv.

**Comment by ThomasWaldmann** [comment]
fixed by #8520.
