### ISSUE TITLE
TypeError: Argument 'value_format' has incorrect type (expected str, got list)

### ISSUE THREAD

**Issue by dertuxmalwieder** [borgbackup/borg#8567]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug

#### Your borg version (borg -V).

borg 2.0.0b14

#### Operating system (distribution) and version.

OmniOS r151052

#### Hardware / network configuration, and filesystems used.

Standard installation on a virtual server with `virtio` networking.

#### How much data is handled by borg?

Seems to be irrelevant, no file set works.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```shell
/usr/local/bin/borg create --remote-path $remoteBorgBin/borg --compression auto,zlib,8 '{hostname}-{now}' /home/tux/postgres-backups
```

## Describe the problem you're observing.

I would like to backup my PostgreSQL database which I dump into `~/postgres-backups` right before calling `borg`. `BORG_REPO` is filled with a valid repository path. (The data seems to be irrelevant, any other folder than `~/postgres-backups` fails as well.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Every time I run the script, this happens:

```
Local Exception

Error:

TypeError: Argument 'value_format' has incorrect type (expected str, got list)

If reporting bugs, please include the following:

Traceback (most recent call last):
  File "/opt/pipx/venvs/borgbackup/lib/python3.12/site-packages/borg/archiver/__init__.py", line 636, in main
    exit_code = archiver.run(args)
                ^^^^^^^^^^^^^^^^^^
  File "/opt/pipx/venvs/borgbackup/lib/python3.12/site-packages/borg/archiver/__init__.py", line 530, in run
    rc = func(args)
         ^^^^^^^^^^
  File "/opt/pipx/venvs/borgbackup/lib/python3.12/site-packages/borg/archiver/_common.py", line 176, in wrapper
    return method(self, args, repository=repository, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pipx/venvs/borgbackup/lib/python3.12/site-packages/borg/archiver/create_cmd.py", line 268, in do_create
    create_inner(archive, cache, fso)
  File "/opt/pipx/venvs/borgbackup/lib/python3.12/site-packages/borg/archiver/create_cmd.py", line 169, in create_inner
    self._rec_walk(
  File "/opt/pipx/venvs/borgbackup/lib/python3.12/site-packages/borg/archiver/create_cmd.py", line 527, in _rec_walk
    self._rec_walk(
  File "/opt/pipx/venvs/borgbackup/lib/python3.12/site-packages/borg/archiver/create_cmd.py", line 467, in _rec_walk
    status = self._process_any(
             ^^^^^^^^^^^^^^^^^^
  File "/opt/pipx/venvs/borgbackup/lib/python3.12/site-packages/borg/archiver/create_cmd.py", line 284, in _process_any
    return fso.process_file(
           ^^^^^^^^^^^^^^^^^
  File "/opt/pipx/venvs/borgbackup/lib/python3.12/site-packages/borg/archive.py", line 1388, in process_file
    self.process_file_chunks(
  File "/opt/pipx/venvs/borgbackup/lib/python3.12/site-packages/borg/archive.py", line 1149, in process_file_chunks
    chunk_entry = chunk_processor(chunk)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pipx/venvs/borgbackup/lib/python3.12/site-packages/borg/archive.py", line 1139, in chunk_processor
    chunk_entry = cache.add_chunk(chunk_id, {}, data, stats=stats, wait=False, ro_type=ROBJ_FILE_STREAM)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pipx/venvs/borgbackup/lib/python3.12/site-packages/borg/cache.py", line 885, in add_chunk
    exists = self.seen_chunk(id, size)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pipx/venvs/borgbackup/lib/python3.12/site-packages/borg/cache.py", line 846, in seen_chunk
    entry = self.chunks.get(id)
            ^^^^^^^^^^^
  File "/opt/pipx/venvs/borgbackup/lib/python3.12/site-packages/borg/cache.py", line 842, in chunks
    self._chunks = build_chunkindex_from_repo(self.repository, cache_immediately=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pipx/venvs/borgbackup/lib/python3.12/site-packages/borg/cache.py", line 786, in build_chunkindex_from_repo
    chunks_to_merge = read_chunkindex_from_repo_cache(repository, hash)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pipx/venvs/borgbackup/lib/python3.12/site-packages/borg/cache.py", line 771, in read_chunkindex_from_repo_cache
    chunks = ChunkIndex.read(f)
             ^^^^^^^^^^^^^^^^^^
  File "src/borg/hashindex.pyx", line 113, in borg.hashindex.ChunkIndex.read
  File "src/borg/hashindex.pyx", line 56, in borg.hashindex.ChunkIndex.__init__
  File "src/borghash/HashTableNT.pyx", line 186, in borghash.HashTableNT.HashTableNT.read
  File "src/borghash/HashTableNT.pyx", line 204, in borghash.HashTableNT.HashTableNT._read_fd
TypeError: Argument 'value_format' has incorrect type (expected str, got list)

Platform: SunOS cloud.rosaelefanten.org 5.11 omnios-r151052-dbe4644ba92 i86pc
Borg: 2.0.0b14  Python: CPython 3.12.7 msgpack: 1.1.0 fuse: None [pyfuse3,llfuse]
PID: 13856  CWD: /home/tux
sys.argv: ['/usr/local/bin/borg', 'create', '--remote-path', '/home/borg/borg-env/bin/borg', '--compression', 'auto,zlib,8', '{hostname}-{now}', '/home/tux/postgres-backups']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment]
Which version of `borghash` do you have installed? For b14, it should be the latest `0.0.x`.

**Comment by ThomasWaldmann** [comment]
Hmm, did you maybe play with code from > b14 (master branch)?

It looks like your `repo/cache/chunks*` content was created with a newer version that the b14 code can't load. Removing these objects would solve the problem (first repo op will than take a while, rebuilding the chunk index by listing all repo objects).

**Comment by dertuxmalwieder** [comment]
Ah, makes sense: The remote repository runs on b15.dev. That might be the culprit here. I guess that makes this issue invalid. Thanks.
