### ISSUE TITLE
Borg fails when creating an archive

### ISSUE THREAD

**Issue by Ape** [borgbackup/borg#945]
When I create an archive with commit 4f507c0 borg crashes with the following error. Commit 77966c7 works as expected.

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 1961, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 1911, in run
    return args.func(args)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 80, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 290, in do_create
    create_inner(archive, cache)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 262, in create_inner
    read_special=args.read_special, dry_run=dry_run, st=st)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 345, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 345, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 345, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 345, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 345, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 345, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 345, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 319, in _process
    status = archive.process_file(path, st, cache, self.ignore_inode)
  File "/usr/lib/python3.5/site-packages/borg/archive.py", line 602, in process_file
    self.add_item(item)
  File "/usr/lib/python3.5/site-packages/borg/archive.py", line 228, in add_item
    self.items_buffer.add(item)
  File "/usr/lib/python3.5/site-packages/borg/archive.py", line 81, in add
    self.flush()
  File "/usr/lib/python3.5/site-packages/borg/archive.py", line 98, in flush
    self.buffer.write(chunks[-1])
TypeError: a bytes-like object is required, not '_Chunk'
```

**Comment by Ape** [comment]
To command it first occurred with was very complex, but it reproduces with this simple one, too:

```
borg create ::$(date +%Y-%m-%d)-test /home
```

**Comment by enkore** [comment]
Thanks, looks like that was overlooked when changing from tuples to namedtuples everywhere.

**Comment by RonnyPfannschmidt** [comment]
i think this indicates a missing test

**Comment by enkore** [comment]
Indeed. It's a specific branch for the buffer handling, but it should be testable if the metadata buffer size is monkeypatched down from ~1 MB (which is a lot of files).

**Comment by ThomasWaldmann** [comment]
Reopened to fix the test / coverage.
